MLIR: lib/Dialect/Affine/Transforms/AffineLoopNormalize.cpp File Reference
AffineLoopNormalize.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Affine/IR/AffineValueMap.h"
#include "mlir/Dialect/Affine/Passes.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/LoopUtils.h"
Functions
static void normalizeAffineFor (AffineForOp op)
Normalizes affine.for ops.
Function Documentation
normalizeAffineFor()
static void normalizeAffineFor (AffineForOp op) static
Normalizes affine.for ops.
If the affine.for op has only a single iteration only then it is simply promoted, else it is normalized in the traditional way, by converting the lower bound to zero and loop step to one. The upper bound is set to the trip count of the loop. For now, original loops must have lower bound with a single result only. There is no such restriction on upper bounds.
Definition at line 88 of file AffineLoopNormalize.cpp.
References mlir::ceilDiv(), mlir::OpBuilder::create(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), mlir::Builder::getConstantAffineMap(), mlir::Builder::getContext(), mlir::AffineBound::getMap(), mlir::AffineMap::getNumDims(), mlir::AffineBound::getNumOperands(), mlir::AffineMap::getNumSymbols(), mlir::AffineBound::getOperand(), mlir::AffineBound::getOperands(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), mlir::normalizeAffineParallel(), mlir::promoteIfSingleIteration(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::succeeded().