MLIR: lib/Conversion/AsyncToLLVM/AsyncToLLVM.cpp File Reference
AsyncToLLVM.cpp File Reference
#include "mlir/Conversion/AsyncToLLVM/AsyncToLLVM.h"
#include "../PassDetail.h"
#include "mlir/Dialect/Async/IR/Async.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/RegionUtils.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define DEBUG_TYPE "convert-async-to-llvm"
Functions
static void addAsyncRuntimeApiDeclarations (ModuleOp module)
static void addLLVMFuncDecl (ModuleOp module, OpBuilder &builder, StringRef name, LLVM::LLVMType ret, ArrayRef< LLVM::LLVMType > params)
Adds an LLVM function declaration to a module.
static void addCoroutineIntrinsicsDeclarations (ModuleOp module)
Adds coroutine intrinsics declarations to the module.
static void addCRuntimeDeclarations (ModuleOp module)
Adds malloc/free declarations to the module.
static void addResumeFunction (ModuleOp module)
static CoroMachinery setupCoroMachinery (FuncOp func)
static void addSuspensionPoint (CoroMachinery coro, Value coroState, Operation *op, Block *suspended, Block *resume, OpBuilder &builder)
static std::pair< FuncOp, CoroMachinery > outlineExecuteOp (SymbolTable &symbolTable, ExecuteOp execute)
Variables
static constexpr const char kAsyncFnPrefix [] = "async_execute_fn"
static constexpr const char * kAddRef = "mlirAsyncRuntimeAddRef"
static constexpr const char * kDropRef = "mlirAsyncRuntimeDropRef"
static constexpr const char * kCreateToken = "mlirAsyncRuntimeCreateToken"
static constexpr const char * kCreateGroup = "mlirAsyncRuntimeCreateGroup"
static constexpr const char * kEmplaceToken = "mlirAsyncRuntimeEmplaceToken"
static constexpr const char * kAwaitToken = "mlirAsyncRuntimeAwaitToken"
static constexpr const char * kAwaitGroup = "mlirAsyncRuntimeAwaitAllInGroup"
static constexpr const char * kExecute = "mlirAsyncRuntimeExecute"
static constexpr const char * kAddTokenToGroup
static constexpr const char * kAwaitAndExecute
static constexpr const char * kAwaitAllAndExecute
static constexpr const char * kCoroId = "llvm.coro.id"
static constexpr const char * kCoroSizeI64 = "llvm.coro.size.i64"
static constexpr const char * kCoroBegin = "llvm.coro.begin"
static constexpr const char * kCoroSave = "llvm.coro.save"
static constexpr const char * kCoroSuspend = "llvm.coro.suspend"
static constexpr const char * kCoroEnd = "llvm.coro.end"
static constexpr const char * kCoroFree = "llvm.coro.free"
static constexpr const char * kCoroResume = "llvm.coro.resume"
static constexpr const char * kMalloc = "malloc"
static constexpr const char * kFree = "free"
static constexpr const char * kResume = "__resume"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "convert-async-to-llvm"
Definition at line 24 of file AsyncToLLVM.cpp.
Function Documentation
addAsyncRuntimeApiDeclarations()
static void addAsyncRuntimeApiDeclarations (ModuleOp module) static
Definition at line 114 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::atBlockTerminator(), mlir::OpBuilder::create(), kAddRef, kAddTokenToGroup, kAwaitAllAndExecute, kAwaitAndExecute, kAwaitGroup, kAwaitToken, kCreateGroup, kCreateToken, kDropRef, kEmplaceToken, and kExecute.
Referenced by outlineExecuteOp().
addCoroutineIntrinsicsDeclarations()
static void addCoroutineIntrinsicsDeclarations (ModuleOp module) static
Adds coroutine intrinsics declarations to the module.
Definition at line 162 of file AsyncToLLVM.cpp.
References addLLVMFuncDecl(), kCoroBegin, kCoroEnd, kCoroFree, kCoroId, kCoroResume, kCoroSave, kCoroSizeI64, and kCoroSuspend.
Referenced by outlineExecuteOp().
addCRuntimeDeclarations()
static void addCRuntimeDeclarations (ModuleOp module) static
Adds malloc/free declarations to the module.
Definition at line 195 of file AsyncToLLVM.cpp.
References addLLVMFuncDecl(), kFree, and kMalloc.
Referenced by outlineExecuteOp().
addLLVMFuncDecl()
static void addLLVMFuncDecl (ModuleOp module, OpBuilder & builder, StringRef name, LLVM::LLVMType ret, ArrayRef< LLVM::LLVMType > params) static
Adds an LLVM function declaration to a module.
Definition at line 152 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::create(), and mlir::LLVM::LLVMType::getFunctionTy().
Referenced by addCoroutineIntrinsicsDeclarations(), and addCRuntimeDeclarations().
addResumeFunction()
static void addResumeFunction (ModuleOp module) static
Definition at line 218 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::atBlockEnd(), mlir::OpBuilder::create(), mlir::LLVM::LLVMType::getFunctionTy(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::Builder::getSymbolRefAttr(), mlir::LLVM::LLVMType::getVoidTy(), kCoroResume, and kResume.
Referenced by outlineExecuteOp().
addSuspensionPoint()
static void addSuspensionPoint (CoroMachinery coro, Value coroState, Operation * op, Block * suspended, Block * resume, OpBuilder & builder) static
Definition at line 418 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::edsc::op::eq(), mlir::Builder::getBoolAttr(), mlir::Operation::getContext(), mlir::Builder::getI8IntegerAttr(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt8Ty(), mlir::Operation::getLoc(), mlir::Builder::getSymbolRefAttr(), isZero(), kCoroSuspend, mlir::OpBuilder::setInsertionPointToEnd(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by outlineExecuteOp().
outlineExecuteOp()
static std::pair<FuncOp, CoroMachinery> outlineExecuteOp (SymbolTable & symbolTable, ExecuteOp execute) static
Definition at line 468 of file AsyncToLLVM.cpp.
References addAsyncRuntimeApiDeclarations(), addCoroutineIntrinsicsDeclarations(), addCRuntimeDeclarations(), addResumeFunction(), addSuspensionPoint(), mlir::WalkResult::advance(), mlir::applyPartialConversion(), mlir::OpBuilder::atBlockTerminator(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::IntegerType::get(), mlir::Operation::getBlock(), mlir::Operation::getContext(), mlir::Type::getContext(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::OpBuilder::getListener(), mlir::Operation::getLoc(), mlir::Operation::getResultTypes(), mlir::Builder::getSymbolRefAttr(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::getUsedValuesDefinedAbove(), mlir::SymbolTable::insert(), mlir::OwningRewritePatternList::insert(), mlir::WalkResult::interrupt(), mlir::Type::isa(), kAddRef, kAddTokenToGroup, kAsyncFnPrefix, kAwaitAllAndExecute, kAwaitAndExecute, kAwaitGroup, kAwaitToken, kCoroSave, kCreateGroup, kDropRef, kEmplaceToken, kExecute, kResume, mlir::BlockAndValueMapping::map(), mlir::populateFuncOpTypeConversionPattern(), mlir::SymbolTable::Private, mlir::PatternRewriter::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointToStart(), mlir::SymbolTable::setSymbolVisibility(), setupCoroMachinery(), mlir::Block::splitBlock(), mlir::ConversionPatternRewriter::splitBlock(), mlir::success(), and mlir::WalkResult::wasInterrupted().
setupCoroMachinery()
static CoroMachinery setupCoroMachinery (FuncOp func) static
Definition at line 291 of file AsyncToLLVM.cpp.
References mlir::OpBuilder::atBlockBegin(), mlir::OpBuilder::create(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::Builder::getBoolAttr(), mlir::Builder::getI32IntegerAttr(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt32Ty(), mlir::LLVM::LLVMType::getInt64Ty(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::Builder::getSymbolRefAttr(), kCoroBegin, kCoroEnd, kCoroFree, kCoroId, kCoroSizeI64, kCreateToken, kFree, kMalloc, mlir::OpBuilder::setInsertionPointToEnd(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by outlineExecuteOp().
Variable Documentation
kAddRef
constexpr const char* kAddRef = "mlirAsyncRuntimeAddRef" static
Definition at line 36 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAddTokenToGroup
constexpr const char* kAddTokenToGroup static
Initial value:
=
    "mlirAsyncRuntimeAddTokenToGroup"
Definition at line 44 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAsyncFnPrefix
constexpr const char kAsyncFnPrefix[] = "async_execute_fn" static
Definition at line 30 of file AsyncToLLVM.cpp.
Referenced by outlineExecuteOp().
kAwaitAllAndExecute
constexpr const char* kAwaitAllAndExecute static
Initial value:
=
    "mlirAsyncRuntimeAwaitAllInGroupAndExecute"
Definition at line 48 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitAndExecute
constexpr const char* kAwaitAndExecute static
Initial value:
=
    "mlirAsyncRuntimeAwaitTokenAndExecute"
Definition at line 46 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitGroup
constexpr const char* kAwaitGroup = "mlirAsyncRuntimeAwaitAllInGroup" static
Definition at line 42 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kAwaitToken
constexpr const char* kAwaitToken = "mlirAsyncRuntimeAwaitToken" static
Definition at line 41 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kCoroBegin
constexpr const char* kCoroBegin = "llvm.coro.begin" static
Definition at line 144 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroEnd
constexpr const char* kCoroEnd = "llvm.coro.end" static
Definition at line 147 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroFree
constexpr const char* kCoroFree = "llvm.coro.free" static
Definition at line 148 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroId
constexpr const char* kCoroId = "llvm.coro.id" static
Definition at line 142 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroResume
constexpr const char* kCoroResume = "llvm.coro.resume" static
Definition at line 149 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and addResumeFunction().
kCoroSave
constexpr const char* kCoroSave = "llvm.coro.save" static
Definition at line 145 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and outlineExecuteOp().
kCoroSizeI64
constexpr const char* kCoroSizeI64 = "llvm.coro.size.i64" static
Definition at line 143 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and setupCoroMachinery().
kCoroSuspend
constexpr const char* kCoroSuspend = "llvm.coro.suspend" static
Definition at line 146 of file AsyncToLLVM.cpp.
Referenced by addCoroutineIntrinsicsDeclarations(), and addSuspensionPoint().
kCreateGroup
constexpr const char* kCreateGroup = "mlirAsyncRuntimeCreateGroup" static
Definition at line 39 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kCreateToken
constexpr const char* kCreateToken = "mlirAsyncRuntimeCreateToken" static
Definition at line 38 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and setupCoroMachinery().
kDropRef
constexpr const char* kDropRef = "mlirAsyncRuntimeDropRef" static
Definition at line 37 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kEmplaceToken
constexpr const char* kEmplaceToken = "mlirAsyncRuntimeEmplaceToken" static
Definition at line 40 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kExecute
constexpr const char* kExecute = "mlirAsyncRuntimeExecute" static
Definition at line 43 of file AsyncToLLVM.cpp.
Referenced by addAsyncRuntimeApiDeclarations(), and outlineExecuteOp().
kFree
constexpr const char* kFree = "free" static
Definition at line 192 of file AsyncToLLVM.cpp.
Referenced by addCRuntimeDeclarations(), and setupCoroMachinery().
kMalloc
constexpr const char* kMalloc = "malloc" static
Definition at line 191 of file AsyncToLLVM.cpp.
Referenced by addCRuntimeDeclarations(), and setupCoroMachinery().
kResume
constexpr const char* kResume = "__resume" static
Definition at line 213 of file AsyncToLLVM.cpp.
Referenced by addResumeFunction(), and outlineExecuteOp().