MLIR: lib/Parser/AttributeParser.cpp File Reference
AttributeParser.cpp File Reference
#include "Parser.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/IntegerSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Endian.h"
Functions
static Optional< APFloat > buildHexadecimalFloatLiteral (Parser *p, FloatType type, uint64_t value)
Construct a float attribute bitwise equivalent to the integer literal.
static Optional< APInt > buildAttributeAPInt (Type type, bool isNegative, StringRef spelling)
Construct an APint from a parsed value, a known attribute type and sign.
static ParseResult parseElementAttrHexValues (Parser &parser, Token tok, std::string &result)
Parse elements values stored within a hex string.
Function Documentation
buildAttributeAPInt()
static Optional<APInt> buildAttributeAPInt (Type type, bool isNegative, StringRef spelling) static
Construct an APint from a parsed value, a known attribute type and sign.
Definition at line 326 of file AttributeParser.cpp.
References mlir::Type::getIntOrFloatBitWidth(), mlir::Type::isIndex(), and mlir::Type::isSignedInteger().
Referenced by mlir::detail::Parser::parseDecOrHexAttr(), and parseElementAttrHexValues().
buildHexadecimalFloatLiteral()
static Optional<APFloat> buildHexadecimalFloatLiteral (Parser * p, FloatType type, uint64_t value) static
Construct a float attribute bitwise equivalent to the integer literal.
Definition at line 311 of file AttributeParser.cpp.
References mlir::detail::Parser::emitError(), mlir::FloatType::getFloatSemantics(), mlir::FloatType::getWidth(), and mlir::Type::isF64().
Referenced by mlir::detail::Parser::parseDecOrHexAttr(), and parseElementAttrHexValues().
parseElementAttrHexValues()
static ParseResult parseElementAttrHexValues (Parser & parser, Token tok, std::string & result) static
Parse elements values stored within a hex string.
On success, the values are stored into 'result'.
Definition at line 427 of file AttributeParser.cpp.
References buildAttributeAPInt(), buildHexadecimalFloatLiteral(), mlir::DenseIntOrFPElementsAttr::convertEndianOfArrayRefForBEmachine(), mlir::Type::dyn_cast(), mlir::detail::Parser::emitError(), mlir::failed(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::DenseStringElementsAttr::get(), mlir::ShapedType::getElementType(), mlir::Token::getFloatingPointValue(), mlir::FloatType::getFloatSemantics(), mlir::DenseElementsAttr::getFromRawBuffer(), mlir::Token::getHexStringValue(), mlir::Token::getLoc(), mlir::ShapedType::getNumElements(), getShape(), mlir::ShapedType::getShape(), mlir::Token::getSpelling(), mlir::Token::getUInt64IntegerValue(), mlir::DenseElementsAttr::getValue(), mlir::Token::is(), mlir::Type::isa(), mlir::Token::isAny(), mlir::Type::isF64(), mlir::Type::isInteger(), mlir::Type::isIntOrFloat(), mlir::Type::isIntOrIndex(), mlir::Type::isIntOrIndexOrFloat(), mlir::Type::isUnsignedInteger(), mlir::DenseElementsAttr::isValidRawBuffer(), mlir::detail::Parser::parseCommaSeparatedList(), and mlir::success().
Referenced by mlir::detail::Parser::parseOpaqueElementsAttr().