MLIR: include/mlir-c/AffineMap.h File Reference
AffineMap.h File Reference
#include "mlir-c/IR.h"
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Opaque type declarations.
Functions
DEFINE_C_API_STRUCT (MlirAffineMap, const void)
MLIR_CAPI_EXPORTED MlirContext mlirAffineMapGetContext (MlirAffineMap affineMap)
Gets the context that the given affine map was created with.
static bool mlirAffineMapIsNull (MlirAffineMap affineMap)
Checks whether an affine map is null.
MLIR_CAPI_EXPORTED bool mlirAffineMapEqual (MlirAffineMap a1, MlirAffineMap a2)
Checks if two affine maps are equal.
MLIR_CAPI_EXPORTED void mlirAffineMapPrint (MlirAffineMap affineMap, MlirStringCallback callback, void *userData)
Prints an affine map by sending chunks of the string representation and forwarding userData tocallback`.
MLIR_CAPI_EXPORTED void mlirAffineMapDump (MlirAffineMap affineMap)
Prints the affine map to the standard error stream.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapEmptyGet (MlirContext ctx)
Creates a zero result affine map with no dimensions or symbols in the context.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapGet (MlirContext ctx, intptr_t dimCount, intptr_t symbolCount)
Creates a zero result affine map of the given dimensions and symbols in the context.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapConstantGet (MlirContext ctx, int64_t val)
Creates a single constant result affine map in the context.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapMultiDimIdentityGet (MlirContext ctx, intptr_t numDims)
Creates an affine map with 'numDims' identity in the context.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapMinorIdentityGet (MlirContext ctx, intptr_t dims, intptr_t results)
Creates an identity affine map on the most minor dimensions in the context.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapPermutationGet (MlirContext ctx, intptr_t size, unsigned *permutation)
Creates an affine map with a permutation expression and its size in the context.
MLIR_CAPI_EXPORTED bool mlirAffineMapIsIdentity (MlirAffineMap affineMap)
Checks whether the given affine map is an identity affine map.
MLIR_CAPI_EXPORTED bool mlirAffineMapIsMinorIdentity (MlirAffineMap affineMap)
Checks whether the given affine map is a minor identity affine map.
MLIR_CAPI_EXPORTED bool mlirAffineMapIsEmpty (MlirAffineMap affineMap)
Checks whether the given affine map is an empty affine map.
MLIR_CAPI_EXPORTED bool mlirAffineMapIsSingleConstant (MlirAffineMap affineMap)
Checks whether the given affine map is a single result constant affine map.
MLIR_CAPI_EXPORTED int64_t mlirAffineMapGetSingleConstantResult (MlirAffineMap affineMap)
Returns the constant result of the given affine map.
MLIR_CAPI_EXPORTED intptr_t mlirAffineMapGetNumDims (MlirAffineMap affineMap)
Returns the number of dimensions of the given affine map.
MLIR_CAPI_EXPORTED intptr_t mlirAffineMapGetNumSymbols (MlirAffineMap affineMap)
Returns the number of symbols of the given affine map.
MLIR_CAPI_EXPORTED intptr_t mlirAffineMapGetNumResults (MlirAffineMap affineMap)
Returns the number of results of the given affine map.
MLIR_CAPI_EXPORTED intptr_t mlirAffineMapGetNumInputs (MlirAffineMap affineMap)
Returns the number of inputs (dimensions + symbols) of the given affine map.
MLIR_CAPI_EXPORTED bool mlirAffineMapIsProjectedPermutation (MlirAffineMap affineMap)
Checks whether the given affine map represents a subset of a symbol-less permutation map.
MLIR_CAPI_EXPORTED bool mlirAffineMapIsPermutation (MlirAffineMap affineMap)
Checks whether the given affine map represents a symbol-less permutation map.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapGetSubMap (MlirAffineMap affineMap, intptr_t size, intptr_t *resultPos)
Returns the affine map consisting of the resultPos subset.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapGetMajorSubMap (MlirAffineMap affineMap, intptr_t numResults)
Returns the affine map consisting of the most major numResults results.
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapGetMinorSubMap (MlirAffineMap affineMap, intptr_t numResults)
Returns the affine map consisting of the most minor numResults results.
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
struct name {                                                                \
    storage *ptr;                                                              \
  };                                                                           \
  typedef struct name name
Opaque type declarations.
Types are exposed to C bindings as structs containing opaque pointers. They are not supposed to be inspected from C. This allows the underlying representation to change without affecting the API users. The use of structs instead of typedefs enables some type safety as structs are not implicitly convertible to each other.
Instances of these types may or may not own the underlying object. The ownership semantics is defined by how an instance of the type was obtained.
Definition at line 33 of file AffineMap.h.
Function Documentation
DEFINE_C_API_STRUCT()
DEFINE_C_API_STRUCT (MlirAffineMap , const void)
mlirAffineMapConstantGet()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapConstantGet (MlirContext ctx, int64_t val)
Creates a single constant result affine map in the context.
The affine map is owned by the context.
Definition at line 45 of file AffineMap.cpp.
References mlir::AffineMap::getConstantMap(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapDump()
MLIR_CAPI_EXPORTED void mlirAffineMapDump (MlirAffineMap affineMap)
Prints the affine map to the standard error stream.
Definition at line 34 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapEmptyGet()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapEmptyGet (MlirContext ctx)
Creates a zero result affine map with no dimensions or symbols in the context.
The affine map is owned by the context.
Definition at line 36 of file AffineMap.cpp.
References mlir::AffineMap::get(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapEqual()
MLIR_CAPI_EXPORTED bool mlirAffineMapEqual (MlirAffineMap a1, MlirAffineMap a2)
Checks if two affine maps are equal.
Definition at line 24 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGet()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapGet (MlirContext ctx, intptr_t dimCount, intptr_t symbolCount)
Creates a zero result affine map of the given dimensions and symbols in the context.
The affine map is owned by the context.
Definition at line 40 of file AffineMap.cpp.
References mlir::AffineMap::get(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetContext()
MLIR_CAPI_EXPORTED MlirContext mlirAffineMapGetContext (MlirAffineMap affineMap)
Gets the context that the given affine map was created with.
Definition at line 20 of file AffineMap.cpp.
References unwrap(), and wrap().
mlirAffineMapGetMajorSubMap()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapGetMajorSubMap (MlirAffineMap affineMap, intptr_t numResults)
Returns the affine map consisting of the most major numResults results.
Returns the null AffineMap if the numResults is equal to zero. Returns the affineMap if numResults is greater or equals to number of results of the given affine map.
Definition at line 118 of file AffineMap.cpp.
References unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetMinorSubMap()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapGetMinorSubMap (MlirAffineMap affineMap, intptr_t numResults)
Returns the affine map consisting of the most minor numResults results.
Returns the null AffineMap if the numResults is equal to zero. Returns the affineMap if numResults is greater or equals to number of results of the given affine map.
Definition at line 123 of file AffineMap.cpp.
References unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetNumDims()
MLIR_CAPI_EXPORTED intptr_t mlirAffineMapGetNumDims (MlirAffineMap affineMap)
Returns the number of dimensions of the given affine map.
Definition at line 85 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetNumInputs()
MLIR_CAPI_EXPORTED intptr_t mlirAffineMapGetNumInputs (MlirAffineMap affineMap)
Returns the number of inputs (dimensions + symbols) of the given affine map.
Definition at line 97 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetNumResults()
MLIR_CAPI_EXPORTED intptr_t mlirAffineMapGetNumResults (MlirAffineMap affineMap)
Returns the number of results of the given affine map.
Definition at line 93 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetNumSymbols()
MLIR_CAPI_EXPORTED intptr_t mlirAffineMapGetNumSymbols (MlirAffineMap affineMap)
Returns the number of symbols of the given affine map.
Definition at line 89 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetSingleConstantResult()
MLIR_CAPI_EXPORTED int64_t mlirAffineMapGetSingleConstantResult (MlirAffineMap affineMap)
Returns the constant result of the given affine map.
The function asserts that the map has a single constant result.
Definition at line 81 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapGetSubMap()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapGetSubMap (MlirAffineMap affineMap, intptr_t size, intptr_t * resultPos)
Returns the affine map consisting of the resultPos subset.
Definition at line 109 of file AffineMap.cpp.
References unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsEmpty()
MLIR_CAPI_EXPORTED bool mlirAffineMapIsEmpty (MlirAffineMap affineMap)
Checks whether the given affine map is an empty affine map.
Definition at line 73 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsIdentity()
MLIR_CAPI_EXPORTED bool mlirAffineMapIsIdentity (MlirAffineMap affineMap)
Checks whether the given affine map is an identity affine map.
The function asserts that the number of dimensions is greater or equal to the number of results.
Definition at line 65 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsMinorIdentity()
MLIR_CAPI_EXPORTED bool mlirAffineMapIsMinorIdentity (MlirAffineMap affineMap)
Checks whether the given affine map is a minor identity affine map.
Definition at line 69 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsNull()
static bool mlirAffineMapIsNull (MlirAffineMap affineMap) inline static
Checks whether an affine map is null.
Definition at line 47 of file AffineMap.h.
References MLIR_CAPI_EXPORTED, mlirAffineMapConstantGet(), mlirAffineMapDump(), mlirAffineMapEmptyGet(), mlirAffineMapEqual(), mlirAffineMapGet(), mlirAffineMapGetMajorSubMap(), mlirAffineMapGetMinorSubMap(), mlirAffineMapGetNumDims(), mlirAffineMapGetNumInputs(), mlirAffineMapGetNumResults(), mlirAffineMapGetNumSymbols(), mlirAffineMapGetSingleConstantResult(), mlirAffineMapGetSubMap(), mlirAffineMapIsEmpty(), mlirAffineMapIsIdentity(), mlirAffineMapIsMinorIdentity(), mlirAffineMapIsPermutation(), mlirAffineMapIsProjectedPermutation(), mlirAffineMapIsSingleConstant(), mlirAffineMapMinorIdentityGet(), mlirAffineMapMultiDimIdentityGet(), mlirAffineMapPermutationGet(), and mlirAffineMapPrint().
mlirAffineMapIsPermutation()
MLIR_CAPI_EXPORTED bool mlirAffineMapIsPermutation (MlirAffineMap affineMap)
Checks whether the given affine map represents a symbol-less permutation map.
Definition at line 105 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsProjectedPermutation()
MLIR_CAPI_EXPORTED bool mlirAffineMapIsProjectedPermutation (MlirAffineMap affineMap)
Checks whether the given affine map represents a subset of a symbol-less permutation map.
Definition at line 101 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapIsSingleConstant()
MLIR_CAPI_EXPORTED bool mlirAffineMapIsSingleConstant (MlirAffineMap affineMap)
Checks whether the given affine map is a single result constant affine map.
Definition at line 77 of file AffineMap.cpp.
References unwrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapMinorIdentityGet()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapMinorIdentityGet (MlirContext ctx, intptr_t dims, intptr_t results)
Creates an identity affine map on the most minor dimensions in the context.
The affine map is owned by the context. The function asserts that the number of dimensions is greater or equal to the number of results.
Definition at line 54 of file AffineMap.cpp.
References mlir::AffineMap::getMinorIdentityMap(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapMultiDimIdentityGet()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapMultiDimIdentityGet (MlirContext ctx, intptr_t numDims)
Creates an affine map with 'numDims' identity in the context.
The affine map is owned by the context.
Definition at line 49 of file AffineMap.cpp.
References mlir::AffineMap::getMultiDimIdentityMap(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapPermutationGet()
MLIR_CAPI_EXPORTED MlirAffineMap mlirAffineMapPermutationGet (MlirContext ctx, intptr_t size, unsigned * permutation)
Creates an affine map with a permutation expression and its size in the context.
The permutation expression is a non-empty vector of integers. The elements of the permutation vector must be continuous from 0 and cannot be repeated (i.e. [1,2,0] is a valid permutation. [2,0] or [1,1,2] is an invalid invalid permutation.) The affine map is owned by the context.
Definition at line 59 of file AffineMap.cpp.
References mlir::AffineMap::getPermutationMap(), unwrap(), and wrap().
Referenced by mlirAffineMapIsNull().
mlirAffineMapPrint()
MLIR_CAPI_EXPORTED void mlirAffineMapPrint (MlirAffineMap affineMap, MlirStringCallback callback, void * userData)
Prints an affine map by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 28 of file AffineMap.cpp.
References mlir::Diagnostic::print(), and unwrap().
Referenced by mlirAffineMapIsNull().