MLIR: include/mlir-c/AffineExpr.h File Reference
AffineExpr.h File Reference
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Opaque type declarations.
Functions
DEFINE_C_API_STRUCT (MlirAffineExpr, const void)
MLIR_CAPI_EXPORTED MlirContext mlirAffineExprGetContext (MlirAffineExpr affineExpr)
Gets the context that owns the affine expression.
MLIR_CAPI_EXPORTED void mlirAffineExprPrint (MlirAffineExpr affineExpr, MlirStringCallback callback, void *userData)
Prints an affine expression by sending chunks of the string representation and forwarding userData tocallback`.
MLIR_CAPI_EXPORTED void mlirAffineExprDump (MlirAffineExpr affineExpr)
Prints the affine expression to the standard error stream.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsSymbolicOrConstant (MlirAffineExpr affineExpr)
Checks whether the given affine expression is made out of only symbols and constants.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsPureAffine (MlirAffineExpr affineExpr)
Checks whether the given affine expression is a pure affine expression, i.e.
MLIR_CAPI_EXPORTED int64_t mlirAffineExprGetLargestKnownDivisor (MlirAffineExpr affineExpr)
Returns the greatest known integral divisor of this affine expression.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsMultipleOf (MlirAffineExpr affineExpr, int64_t factor)
Checks whether the given affine expression is a multiple of 'factor'.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsFunctionOfDim (MlirAffineExpr affineExpr, intptr_t position)
Checks whether the given affine expression involves AffineDimExpr 'position'.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineDimExprGet (MlirContext ctx, intptr_t position)
Creates an affine dimension expression with 'position' in the context.
MLIR_CAPI_EXPORTED intptr_t mlirAffineDimExprGetPosition (MlirAffineExpr affineExpr)
Returns the position of the given affine dimension expression.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineSymbolExprGet (MlirContext ctx, intptr_t position)
Creates an affine symbol expression with 'position' in the context.
MLIR_CAPI_EXPORTED intptr_t mlirAffineSymbolExprGetPosition (MlirAffineExpr affineExpr)
Returns the position of the given affine symbol expression.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineConstantExprGet (MlirContext ctx, int64_t constant)
Creates an affine constant expression with 'constant' in the context.
MLIR_CAPI_EXPORTED int64_t mlirAffineConstantExprGetValue (MlirAffineExpr affineExpr)
Returns the value of the given affine constant expression.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsAAdd (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an add expression.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineAddExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine add expression with 'lhs' and 'rhs'.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsAMul (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an mul expression.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineMulExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine mul expression with 'lhs' and 'rhs'.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsAMod (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an mod expression.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineModExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine mod expression with 'lhs' and 'rhs'.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsAFloorDiv (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an floordiv expression.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineFloorDivExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine floordiv expression with 'lhs' and 'rhs'.
MLIR_CAPI_EXPORTED bool mlirAffineExprIsACeilDiv (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an ceildiv expression.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineCeilDivExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine ceildiv expression with 'lhs' and 'rhs'.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineBinaryOpExprGetLHS (MlirAffineExpr affineExpr)
Returns the left hand side affine expression of the given affine binary operation expression.
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineBinaryOpExprGetRHS (MlirAffineExpr affineExpr)
Returns the right hand side affine expression of the given affine binary operation expression.
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
struct name {                                                                \
    storage *ptr;                                                              \
  };                                                                           \
  typedef struct name name
Opaque type declarations.
Types are exposed to C bindings as structs containing opaque pointers. They are not supposed to be inspected from C. This allows the underlying representation to change without affecting the API users. The use of structs instead of typedefs enables some type safety as structs are not implicitly convertible to each other.
Instances of these types may or may not own the underlying object. The ownership semantics is defined by how an instance of the type was obtained.
Definition at line 34 of file AffineExpr.h.
Function Documentation
DEFINE_C_API_STRUCT()
DEFINE_C_API_STRUCT (MlirAffineExpr , const void)
mlirAffineAddExprGet()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineAddExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine add expression with 'lhs' and 'rhs'.
Definition at line 99 of file AffineExpr.cpp.
References mlir::Add, mlir::getAffineBinaryOpExpr(), unwrap(), and wrap().
mlirAffineBinaryOpExprGetLHS()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineBinaryOpExprGetLHS (MlirAffineExpr affineExpr)
Returns the left hand side affine expression of the given affine binary operation expression.
Definition at line 162 of file AffineExpr.cpp.
References unwrap(), and wrap().
mlirAffineBinaryOpExprGetRHS()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineBinaryOpExprGetRHS (MlirAffineExpr affineExpr)
Returns the right hand side affine expression of the given affine binary operation expression.
Definition at line 166 of file AffineExpr.cpp.
References unwrap(), and wrap().
mlirAffineCeilDivExprGet()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineCeilDivExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine ceildiv expression with 'lhs' and 'rhs'.
Definition at line 152 of file AffineExpr.cpp.
References mlir::CeilDiv, mlir::getAffineBinaryOpExpr(), unwrap(), and wrap().
mlirAffineConstantExprGet()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineConstantExprGet (MlirContext ctx, int64_t constant)
Creates an affine constant expression with 'constant' in the context.
Definition at line 83 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), unwrap(), and wrap().
mlirAffineConstantExprGetValue()
MLIR_CAPI_EXPORTED int64_t mlirAffineConstantExprGetValue (MlirAffineExpr affineExpr)
Returns the value of the given affine constant expression.
Definition at line 87 of file AffineExpr.cpp.
References unwrap().
mlirAffineDimExprGet()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineDimExprGet (MlirContext ctx, intptr_t position)
Creates an affine dimension expression with 'position' in the context.
Definition at line 59 of file AffineExpr.cpp.
References mlir::getAffineDimExpr(), unwrap(), and wrap().
mlirAffineDimExprGetPosition()
MLIR_CAPI_EXPORTED intptr_t mlirAffineDimExprGetPosition (MlirAffineExpr affineExpr)
Returns the position of the given affine dimension expression.
Definition at line 63 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprDump()
MLIR_CAPI_EXPORTED void mlirAffineExprDump (MlirAffineExpr affineExpr)
Prints the affine expression to the standard error stream.
Definition at line 30 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprGetContext()
MLIR_CAPI_EXPORTED MlirContext mlirAffineExprGetContext (MlirAffineExpr affineExpr)
Gets the context that owns the affine expression.
Definition at line 20 of file AffineExpr.cpp.
References unwrap(), and wrap().
mlirAffineExprGetLargestKnownDivisor()
MLIR_CAPI_EXPORTED int64_t mlirAffineExprGetLargestKnownDivisor (MlirAffineExpr affineExpr)
Returns the greatest known integral divisor of this affine expression.
The result is always positive.
Definition at line 42 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprIsAAdd()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsAAdd (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an add expression.
Definition at line 95 of file AffineExpr.cpp.
References mlir::Add, and unwrap().
mlirAffineExprIsACeilDiv()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsACeilDiv (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an ceildiv expression.
Definition at line 148 of file AffineExpr.cpp.
References mlir::CeilDiv, and unwrap().
mlirAffineExprIsAFloorDiv()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsAFloorDiv (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an floordiv expression.
Definition at line 134 of file AffineExpr.cpp.
References mlir::FloorDiv, and unwrap().
mlirAffineExprIsAMod()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsAMod (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an mod expression.
Definition at line 121 of file AffineExpr.cpp.
References mlir::Mod, and unwrap().
mlirAffineExprIsAMul()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsAMul (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an mul expression.
Definition at line 108 of file AffineExpr.cpp.
References mlir::Mul, and unwrap().
mlirAffineExprIsFunctionOfDim()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsFunctionOfDim (MlirAffineExpr affineExpr, intptr_t position)
Checks whether the given affine expression involves AffineDimExpr 'position'.
Definition at line 50 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprIsMultipleOf()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsMultipleOf (MlirAffineExpr affineExpr, int64_t factor)
Checks whether the given affine expression is a multiple of 'factor'.
Definition at line 46 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprIsPureAffine()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsPureAffine (MlirAffineExpr affineExpr)
Checks whether the given affine expression is a pure affine expression, i.e.
mul, floordiv, ceildic, and mod is only allowed w.r.t constants.
Definition at line 38 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprIsSymbolicOrConstant()
MLIR_CAPI_EXPORTED bool mlirAffineExprIsSymbolicOrConstant (MlirAffineExpr affineExpr)
Checks whether the given affine expression is made out of only symbols and constants.
Definition at line 34 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprPrint()
MLIR_CAPI_EXPORTED void mlirAffineExprPrint (MlirAffineExpr affineExpr, MlirStringCallback callback, void * userData)
Prints an affine expression by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 24 of file AffineExpr.cpp.
References mlir::Diagnostic::print(), and unwrap().
mlirAffineFloorDivExprGet()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineFloorDivExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine floordiv expression with 'lhs' and 'rhs'.
Definition at line 138 of file AffineExpr.cpp.
References mlir::FloorDiv, mlir::getAffineBinaryOpExpr(), unwrap(), and wrap().
mlirAffineModExprGet()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineModExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine mod expression with 'lhs' and 'rhs'.
Definition at line 125 of file AffineExpr.cpp.
References mlir::getAffineBinaryOpExpr(), mlir::Mod, unwrap(), and wrap().
mlirAffineMulExprGet()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineMulExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine mul expression with 'lhs' and 'rhs'.
Definition at line 112 of file AffineExpr.cpp.
References mlir::getAffineBinaryOpExpr(), mlir::Mul, unwrap(), and wrap().
mlirAffineSymbolExprGet()
MLIR_CAPI_EXPORTED MlirAffineExpr mlirAffineSymbolExprGet (MlirContext ctx, intptr_t position)
Creates an affine symbol expression with 'position' in the context.
Definition at line 71 of file AffineExpr.cpp.
References mlir::getAffineSymbolExpr(), unwrap(), and wrap().
mlirAffineSymbolExprGetPosition()
MLIR_CAPI_EXPORTED intptr_t mlirAffineSymbolExprGetPosition (MlirAffineExpr affineExpr)
Returns the position of the given affine symbol expression.
Definition at line 75 of file AffineExpr.cpp.
References unwrap().