MLIR: lib/CAPI/IR/AffineExpr.cpp File Reference
AffineExpr.cpp File Reference
#include "mlir-c/AffineExpr.h"
#include "mlir-c/AffineMap.h"
#include "mlir-c/IR.h"
#include "mlir/CAPI/AffineExpr.h"
#include "mlir/CAPI/AffineMap.h"
#include "mlir/CAPI/IR.h"
#include "mlir/CAPI/Utils.h"
#include "mlir/IR/AffineExpr.h"
Functions
MlirContext mlirAffineExprGetContext (MlirAffineExpr affineExpr)
Gets the context that owns the affine expression.
void mlirAffineExprPrint (MlirAffineExpr affineExpr, MlirStringCallback callback, void *userData)
Prints an affine expression by sending chunks of the string representation and forwarding userData tocallback`.
void mlirAffineExprDump (MlirAffineExpr affineExpr)
Prints the affine expression to the standard error stream.
bool mlirAffineExprIsSymbolicOrConstant (MlirAffineExpr affineExpr)
Checks whether the given affine expression is made out of only symbols and constants.
bool mlirAffineExprIsPureAffine (MlirAffineExpr affineExpr)
Checks whether the given affine expression is a pure affine expression, i.e.
int64_t mlirAffineExprGetLargestKnownDivisor (MlirAffineExpr affineExpr)
Returns the greatest known integral divisor of this affine expression.
bool mlirAffineExprIsMultipleOf (MlirAffineExpr affineExpr, int64_t factor)
Checks whether the given affine expression is a multiple of 'factor'.
bool mlirAffineExprIsFunctionOfDim (MlirAffineExpr affineExpr, intptr_t position)
Checks whether the given affine expression involves AffineDimExpr 'position'.
MlirAffineExpr mlirAffineDimExprGet (MlirContext ctx, intptr_t position)
Creates an affine dimension expression with 'position' in the context.
intptr_t mlirAffineDimExprGetPosition (MlirAffineExpr affineExpr)
Returns the position of the given affine dimension expression.
MlirAffineExpr mlirAffineSymbolExprGet (MlirContext ctx, intptr_t position)
Creates an affine symbol expression with 'position' in the context.
intptr_t mlirAffineSymbolExprGetPosition (MlirAffineExpr affineExpr)
Returns the position of the given affine symbol expression.
MlirAffineExpr mlirAffineConstantExprGet (MlirContext ctx, int64_t constant)
Creates an affine constant expression with 'constant' in the context.
int64_t mlirAffineConstantExprGetValue (MlirAffineExpr affineExpr)
Returns the value of the given affine constant expression.
bool mlirAffineExprIsAAdd (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an add expression.
MlirAffineExpr mlirAffineAddExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine add expression with 'lhs' and 'rhs'.
bool mlirAffineExprIsAMul (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an mul expression.
MlirAffineExpr mlirAffineMulExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine mul expression with 'lhs' and 'rhs'.
bool mlirAffineExprIsAMod (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an mod expression.
MlirAffineExpr mlirAffineModExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine mod expression with 'lhs' and 'rhs'.
bool mlirAffineExprIsAFloorDiv (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an floordiv expression.
MlirAffineExpr mlirAffineFloorDivExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine floordiv expression with 'lhs' and 'rhs'.
bool mlirAffineExprIsACeilDiv (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an ceildiv expression.
MlirAffineExpr mlirAffineCeilDivExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine ceildiv expression with 'lhs' and 'rhs'.
MlirAffineExpr mlirAffineBinaryOpExprGetLHS (MlirAffineExpr affineExpr)
Returns the left hand side affine expression of the given affine binary operation expression.
MlirAffineExpr mlirAffineBinaryOpExprGetRHS (MlirAffineExpr affineExpr)
Returns the right hand side affine expression of the given affine binary operation expression.
Function Documentation
mlirAffineAddExprGet()
MlirAffineExpr mlirAffineAddExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine add expression with 'lhs' and 'rhs'.
Definition at line 99 of file AffineExpr.cpp.
References mlir::Add, mlir::getAffineBinaryOpExpr(), unwrap(), and wrap().
mlirAffineBinaryOpExprGetLHS()
MlirAffineExpr mlirAffineBinaryOpExprGetLHS (MlirAffineExpr affineExpr)
Returns the left hand side affine expression of the given affine binary operation expression.
Definition at line 162 of file AffineExpr.cpp.
References unwrap(), and wrap().
mlirAffineBinaryOpExprGetRHS()
MlirAffineExpr mlirAffineBinaryOpExprGetRHS (MlirAffineExpr affineExpr)
Returns the right hand side affine expression of the given affine binary operation expression.
Definition at line 166 of file AffineExpr.cpp.
References unwrap(), and wrap().
mlirAffineCeilDivExprGet()
MlirAffineExpr mlirAffineCeilDivExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine ceildiv expression with 'lhs' and 'rhs'.
Definition at line 152 of file AffineExpr.cpp.
References mlir::CeilDiv, mlir::getAffineBinaryOpExpr(), unwrap(), and wrap().
mlirAffineConstantExprGet()
MlirAffineExpr mlirAffineConstantExprGet (MlirContext ctx, int64_t constant)
Creates an affine constant expression with 'constant' in the context.
Definition at line 83 of file AffineExpr.cpp.
References mlir::getAffineConstantExpr(), unwrap(), and wrap().
mlirAffineConstantExprGetValue()
int64_t mlirAffineConstantExprGetValue (MlirAffineExpr affineExpr)
Returns the value of the given affine constant expression.
Definition at line 87 of file AffineExpr.cpp.
References unwrap().
mlirAffineDimExprGet()
MlirAffineExpr mlirAffineDimExprGet (MlirContext ctx, intptr_t position)
Creates an affine dimension expression with 'position' in the context.
Definition at line 59 of file AffineExpr.cpp.
References mlir::getAffineDimExpr(), unwrap(), and wrap().
mlirAffineDimExprGetPosition()
intptr_t mlirAffineDimExprGetPosition (MlirAffineExpr affineExpr)
Returns the position of the given affine dimension expression.
Definition at line 63 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprDump()
void mlirAffineExprDump (MlirAffineExpr affineExpr)
Prints the affine expression to the standard error stream.
Definition at line 30 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprGetContext()
MlirContext mlirAffineExprGetContext (MlirAffineExpr affineExpr)
Gets the context that owns the affine expression.
Definition at line 20 of file AffineExpr.cpp.
References unwrap(), and wrap().
mlirAffineExprGetLargestKnownDivisor()
int64_t mlirAffineExprGetLargestKnownDivisor (MlirAffineExpr affineExpr)
Returns the greatest known integral divisor of this affine expression.
The result is always positive.
Definition at line 42 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprIsAAdd()
bool mlirAffineExprIsAAdd (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an add expression.
Definition at line 95 of file AffineExpr.cpp.
References mlir::Add, and unwrap().
mlirAffineExprIsACeilDiv()
bool mlirAffineExprIsACeilDiv (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an ceildiv expression.
Definition at line 148 of file AffineExpr.cpp.
References mlir::CeilDiv, and unwrap().
mlirAffineExprIsAFloorDiv()
bool mlirAffineExprIsAFloorDiv (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an floordiv expression.
Definition at line 134 of file AffineExpr.cpp.
References mlir::FloorDiv, and unwrap().
mlirAffineExprIsAMod()
bool mlirAffineExprIsAMod (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an mod expression.
Definition at line 121 of file AffineExpr.cpp.
References mlir::Mod, and unwrap().
mlirAffineExprIsAMul()
bool mlirAffineExprIsAMul (MlirAffineExpr affineExpr)
Checks whether the given affine expression is an mul expression.
Definition at line 108 of file AffineExpr.cpp.
References mlir::Mul, and unwrap().
mlirAffineExprIsFunctionOfDim()
bool mlirAffineExprIsFunctionOfDim (MlirAffineExpr affineExpr, intptr_t position)
Checks whether the given affine expression involves AffineDimExpr 'position'.
Definition at line 50 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprIsMultipleOf()
bool mlirAffineExprIsMultipleOf (MlirAffineExpr affineExpr, int64_t factor)
Checks whether the given affine expression is a multiple of 'factor'.
Definition at line 46 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprIsPureAffine()
bool mlirAffineExprIsPureAffine (MlirAffineExpr affineExpr)
Checks whether the given affine expression is a pure affine expression, i.e.
mul, floordiv, ceildic, and mod is only allowed w.r.t constants.
Definition at line 38 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprIsSymbolicOrConstant()
bool mlirAffineExprIsSymbolicOrConstant (MlirAffineExpr affineExpr)
Checks whether the given affine expression is made out of only symbols and constants.
Definition at line 34 of file AffineExpr.cpp.
References unwrap().
mlirAffineExprPrint()
void mlirAffineExprPrint (MlirAffineExpr affineExpr, MlirStringCallback callback, void * userData)
Prints an affine expression by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 24 of file AffineExpr.cpp.
References mlir::Diagnostic::print(), and unwrap().
mlirAffineFloorDivExprGet()
MlirAffineExpr mlirAffineFloorDivExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine floordiv expression with 'lhs' and 'rhs'.
Definition at line 138 of file AffineExpr.cpp.
References mlir::FloorDiv, mlir::getAffineBinaryOpExpr(), unwrap(), and wrap().
mlirAffineModExprGet()
MlirAffineExpr mlirAffineModExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine mod expression with 'lhs' and 'rhs'.
Definition at line 125 of file AffineExpr.cpp.
References mlir::getAffineBinaryOpExpr(), mlir::Mod, unwrap(), and wrap().
mlirAffineMulExprGet()
MlirAffineExpr mlirAffineMulExprGet (MlirAffineExpr lhs, MlirAffineExpr rhs)
Creates an affine mul expression with 'lhs' and 'rhs'.
Definition at line 112 of file AffineExpr.cpp.
References mlir::getAffineBinaryOpExpr(), mlir::Mul, unwrap(), and wrap().
mlirAffineSymbolExprGet()
MlirAffineExpr mlirAffineSymbolExprGet (MlirContext ctx, intptr_t position)
Creates an affine symbol expression with 'position' in the context.
Definition at line 71 of file AffineExpr.cpp.
References mlir::getAffineSymbolExpr(), unwrap(), and wrap().
mlirAffineSymbolExprGetPosition()
intptr_t mlirAffineSymbolExprGetPosition (MlirAffineExpr affineExpr)
Returns the position of the given affine symbol expression.
Definition at line 75 of file AffineExpr.cpp.
References unwrap().