MLIR: mlir::LLVM::LLVMStructType Class Reference
mlir::LLVM::LLVMStructType Class Reference
LLVM dialect structure type representing a collection of different-typed elements manipulated together.
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Public Member Functions
LogicalResult setBody (ArrayRef< LLVMType > types, bool isPacked)
Set the body of an identified struct.
bool isPacked ()
Checks if a struct is packed.
bool isIdentified ()
Checks if a struct is identified.
bool isOpaque ()
Checks if a struct is opaque.
bool isInitialized ()
Checks if a struct is initialized.
StringRef getName ()
Returns the name of an identified struct.
ArrayRef< LLVMType > getBody ()
Returns the list of element types contained in a non-opaque struct.
Static Public Member Functions
static bool isValidElementType (LLVMType type)
Checks if the given type can be contained in a structure type.
static LLVMStructType getIdentified (MLIRContext *context, StringRef name)
Gets or creates an identified struct with the given name in the provided context.
static LLVMStructType getIdentifiedChecked (Location loc, StringRef name)
static LLVMStructType getLiteral (MLIRContext *context, ArrayRef< LLVMType > types, bool isPacked=false)
Gets or creates a literal struct with the given body in the provided context.
static LLVMStructType getLiteralChecked (Location loc, ArrayRef< LLVMType > types, bool isPacked=false)
static LLVMStructType getOpaque (StringRef name, MLIRContext *context)
Gets or creates an intentionally-opaque identified struct.
static LLVMStructType getOpaqueChecked (Location loc, StringRef name)
static LogicalResult verifyConstructionInvariants (Location, StringRef, bool)
Verifies that the type about to be constructed is well-formed.
static LogicalResult verifyConstructionInvariants (Location loc, ArrayRef< LLVMType > types, bool)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
LLVM dialect structure type representing a collection of different-typed elements manipulated together.
Structured can optionally be packed, meaning that their elements immediately follow each other in memory without accounting for potential alignment.
Structure types can be identified (named) or literal. Literal structures are uniquely represented by the list of types they contain and packedness. Literal structure types are immutable after construction.
Identified structures are uniquely represented by their name, a string. They have a mutable component, consisting of the list of types they contain, the packedness and the opacity bits. Identified structs can be created without providing the lists of element types, making them suitable to represent recursive, i.e. self-referring, structures. Identified structs without body are considered opaque. For such structs, one can set the body. Identified structs can be created as intentionally-opaque, implying that the caller does not intend to ever set the body (e.g. forward-declarations of structs from another module) and wants to disallow further modification of the body. For intentionally-opaque structs or non-opaque structs with the body, one is not allowed to set another body (however, one can set exactly the same body).
Note that the packedness of the struct takes place in uniquing of literal structs, but does not in uniquing of identified structs.
Definition at line 427 of file LLVMTypes.h.
Member Function Documentation
getBody()
ArrayRef< LLVMType > LLVMStructType::getBody ()
Returns the list of element types contained in a non-opaque struct.
Definition at line 448 of file LLVMTypes.cpp.
Referenced by printStructTypeBody(), and mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
getIdentified()
LLVMStructType LLVMStructType::getIdentified (MLIRContext * context, StringRef name) static
Gets or creates an identified struct with the given name in the provided context.
Note that unlike llvm::StructType::create, this function will NOT rename a struct in case a struct with the same name already exists in the context. Instead, it will just return the existing struct, similarly to the rest of MLIR type ::get methods.
Definition at line 403 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::LLVMType::createStructTy(), and mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType().
getIdentifiedChecked()
LLVMStructType LLVMStructType::getIdentifiedChecked (Location loc, StringRef name) static
Definition at line 408 of file LLVMTypes.cpp.
getLiteral()
LLVMStructType LLVMStructType::getLiteral (MLIRContext * context, ArrayRef< LLVMType > types, bool isPacked = false) static
Gets or creates a literal struct with the given body in the provided context.
Definition at line 413 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::LLVMType::getStructTy(), and mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType().
getLiteralChecked()
LLVMStructType LLVMStructType::getLiteralChecked (Location loc, ArrayRef< LLVMType > types, bool isPacked = false) static
Definition at line 419 of file LLVMTypes.cpp.
getName()
StringRef LLVMStructType::getName ()
Returns the name of an identified struct.
Definition at line 447 of file LLVMTypes.cpp.
Referenced by printStructType(), printStructTypeBody(), and mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
getOpaque()
LLVMStructType LLVMStructType::getOpaque (StringRef name, MLIRContext * context) static
Gets or creates an intentionally-opaque identified struct.
Such a struct cannot have its body set. To create an opaque struct with a mutable body, use getIdentified. Note that unlike llvm::StructType::create, this function will NOT rename a struct in case a struct with the same name already exists in the context. Instead, it will just return the existing struct, similarly to the rest of MLIR type ::get methods.
Definition at line 425 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType().
getOpaqueChecked()
LLVMStructType LLVMStructType::getOpaqueChecked (Location loc, StringRef name) static
Definition at line 429 of file LLVMTypes.cpp.
isIdentified()
bool LLVMStructType::isIdentified ()
Checks if a struct is identified.
Definition at line 441 of file LLVMTypes.cpp.
Referenced by printStructType(), printStructTypeBody(), and mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
isInitialized()
bool LLVMStructType::isInitialized ()
Checks if a struct is initialized.
Definition at line 446 of file LLVMTypes.cpp.
isOpaque()
bool LLVMStructType::isOpaque ()
Checks if a struct is opaque.
Definition at line 442 of file LLVMTypes.cpp.
Referenced by printStructTypeBody(), and mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
isPacked()
bool LLVMStructType::isPacked ()
Checks if a struct is packed.
Definition at line 440 of file LLVMTypes.cpp.
Referenced by printStructTypeBody(), and mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
isValidElementType()
bool LLVMStructType::isValidElementType (LLVMType type) static
Checks if the given type can be contained in a structure type.
Definition at line 398 of file LLVMTypes.cpp.
References mlir::Type::isa().
Referenced by setBody().
setBody()
LogicalResult LLVMStructType::setBody (ArrayRef< LLVMType > types, bool isPacked)
Set the body of an identified struct.
Returns failure if the body could not be set, e.g. if the struct already has a body or if it was marked as intentionally opaque. This might happen in a multi-threaded context when a different thread modified the struct after it was created. Most callers are likely to assert this always succeeds, but it is possible to implement a local renaming scheme based on the result of this call.
Definition at line 433 of file LLVMTypes.cpp.
References isValidElementType().
Referenced by mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType().
verifyConstructionInvariants() [1/2]
LogicalResult LLVMStructType::verifyConstructionInvariants (Location , StringRef , bool) static
Verifies that the type about to be constructed is well-formed.
Definition at line 453 of file LLVMTypes.cpp.
References mlir::success().
verifyConstructionInvariants() [2/2]
LogicalResult LLVMStructType::verifyConstructionInvariants (Location loc, ArrayRef< LLVMType > types, bool) static
Definition at line 459 of file LLVMTypes.cpp.
References mlir::emitError(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMTypes.h
lib/Dialect/LLVMIR/IR/LLVMTypes.cpp