MLIR: mlir::python::PyOperation Class Reference
mlir::python::PyOperation Class Reference
#include "Bindings/Python/IRModules.h"
Public Member Functions
~PyOperation ()
PyOperation & getOperation () override
Each must provide access to the raw Operation.
operator MlirOperation () const
Gets the backing operation.
MlirOperation get () const
PyOperationRef getRef ()
bool isAttached ()
void setAttached ()
void checkValid () const
PyBlock getBlock ()
Gets the owning block or raises an exception if the operation has no owning block.
PyOperationRef getParentOperation ()
Gets the parent operation or raises an exception if the operation has no parent.
pybind11::object createOpView ()
Creates an OpView suitable for this operation.
Public Member Functions inherited from mlir::python::PyOperationBase
virtual ~PyOperationBase ()=default
void print (pybind11::object fileObject, bool binary, llvm::Optional< int64_t > largeElementsLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope)
Implements the bound 'print' method and helps with others.
pybind11::object getAsm (bool binary, llvm::Optional< int64_t > largeElementsLimit, bool enableDebugInfo, bool prettyDebugInfo, bool printGenericOpForm, bool useLocalScope)
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyOperationRef forOperation (PyMlirContextRef contextRef, MlirOperation operation, pybind11::object parentKeepAlive=pybind11::object())
Returns a PyOperation for the given MlirOperation, optionally associating it with a parentKeepAlive.
static PyOperationRef createDetached (PyMlirContextRef contextRef, MlirOperation operation, pybind11::object parentKeepAlive=pybind11::object())
Creates a detached operation.
static pybind11::object create (std::string name, llvm::Optional< std::vector< PyValue *>> operands, llvm::Optional< std::vector< PyType *>> results, llvm::Optional< pybind11::dict > attributes, llvm::Optional< std::vector< PyBlock *>> successors, int regions, DefaultingPyLocation location, pybind11::object ip)
Creates an operation. See corresponding python docstring.
Detailed Description
Definition at line 410 of file IRModules.h.
Constructor & Destructor Documentation
~PyOperation()
PyOperation::~PyOperation ()
Definition at line 738 of file IRModules.cpp.
References mlirOperationDestroy().
Member Function Documentation
checkValid()
void PyOperation::checkValid () const
Definition at line 798 of file IRModules.cpp.
References mlir::python::SetPyError().
Referenced by mlir::python::PyType::createFromCapsule(), mlir::python::PyInsertionPoint::insert(), and mlir::python::PyOperationBase::print().
create()
py::object PyOperation::create (std::string name, llvm::Optional< std::vector< PyValue *>> operands, llvm::Optional< std::vector< PyType *>> results, llvm::Optional< pybind11::dict > attributes, llvm::Optional< std::vector< PyBlock *>> successors, int regions, DefaultingPyLocation location, pybind11::object ip) static
Creates an operation. See corresponding python docstring.
Definition at line 870 of file IRModules.cpp.
References createDetached(), createOpView(), mlir::python::PyObjectRef< T >::get(), mlir::python::PyThreadContextEntry::getDefaultInsertionPoint(), mlir::python::PyInsertionPoint::insert(), mlirAttributeGetContext(), mlirIdentifierGet(), mlirNamedAttributeGet(), mlirOperationCreate(), mlirOperationStateAddAttributes(), mlirOperationStateAddOperands(), mlirOperationStateAddOwnedRegions(), mlirOperationStateAddResults(), mlirOperationStateAddSuccessors(), mlirOperationStateGet(), mlirRegionCreate(), mlir::python::SetPyError(), and toMlirStringRef().
Referenced by mlir::python::PyType::createFromCapsule().
createDetached()
PyOperationRef PyOperation::createDetached (PyMlirContextRef contextRef, MlirOperation operation, pybind11::object parentKeepAlive = pybind11::object()) static
Creates a detached operation.
The operation must not be associated with any existing live operation.
Definition at line 784 of file IRModules.cpp.
Referenced by create().
createOpView()
py::object PyOperation::createOpView ()
Creates an OpView suitable for this operation.
Definition at line 1004 of file IRModules.cpp.
References MlirStringRef::data, mlir::python::PyGlobals::get(), MlirStringRef::length, mlir::python::PyGlobals::lookupRawOpViewClass(), mlirIdentifierStr(), and mlirOperationGetName().
Referenced by create(), and mlir::python::PyType::createFromCapsule().
forOperation()
PyOperationRef PyOperation::forOperation (PyMlirContextRef contextRef, MlirOperation operation, pybind11::object parentKeepAlive = pybind11::object()) static
Returns a PyOperation for the given MlirOperation, optionally associating it with a parentKeepAlive.
Definition at line 768 of file IRModules.cpp.
Referenced by mlir::python::PyInsertionPoint::atBlockBegin(), mlir::python::PyInsertionPoint::atBlockTerminator(), mlir::python::PyType::createFromCapsule(), getParentOperation(), and toMlirStringRef().
get()
MlirOperation mlir::python::PyOperation::get () const inline
Definition at line 429 of file IRModules.h.
Referenced by mlir::python::PyType::createFromCapsule().
getBlock()
PyBlock PyOperation::getBlock ()
Gets the owning block or raises an exception if the operation has no owning block.
Definition at line 863 of file IRModules.cpp.
References mlirBlockIsNull(), and mlirOperationGetBlock().
getOperation()
PyOperation& mlir::python::PyOperation::getOperation () inline override virtual
Each must provide access to the raw Operation.
Implements mlir::python::PyOperationBase.
Definition at line 413 of file IRModules.h.
getParentOperation()
PyOperationRef PyOperation::getParentOperation ()
Gets the parent operation or raises an exception if the operation has no parent.
Definition at line 854 of file IRModules.cpp.
References forOperation(), mlirOperationGetParentOperation(), mlirOperationIsNull(), and mlir::python::SetPyError().
getRef()
PyOperationRef mlir::python::PyOperation::getRef () inline
Definition at line 434 of file IRModules.h.
isAttached()
bool mlir::python::PyOperation::isAttached () inline
Definition at line 439 of file IRModules.h.
Referenced by mlir::python::PyInsertionPoint::insert().
operator MlirOperation()
mlir::python::PyOperation::operator MlirOperation () const inline
Gets the backing operation.
Definition at line 428 of file IRModules.h.
setAttached()
void mlir::python::PyOperation::setAttached () inline
Definition at line 440 of file IRModules.h.
Referenced by mlir::python::PyInsertionPoint::insert().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModules.h
lib/Bindings/Python/IRModules.cpp