MLIR: mlir::Type Class Reference
mlir::Type Class Reference
Instances of the Type class are uniqued, have an immutable identifier and an optional mutable component.
#include "mlir/IR/Types.h"
Public Types
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
Public Member Functions
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os)
Print the current type.
void dump ()
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Protected Attributes
ImplType * impl
Friends
::llvm::hash_code hash_value (Type arg)
Detailed Description
Instances of the Type class are uniqued, have an immutable identifier and an optional mutable component.
They wrap a pointer to the storage object owned by MLIRContext. Therefore, instances of Type are passed around by value.
Some types are "primitives" meaning they do not have any parameters, for example the Index type. Parametric types have additional information that differentiates the types of the same class, for example the Integer type has bitwidth, making i8 and i16 belong to the same kind by be different instances of the IntegerType. Type parameters are part of the unique immutable key. The mutable component of the type can be modified after the type is created, but cannot affect the identity of the type.
Types are constructed and uniqued via the 'detail::TypeUniquer' class.
Derived type classes are expected to implement several required implementation hooks:
Optional:
static LogicalResult verifyConstructionInvariants(Location loc, Args... args)
This method is invoked when calling the 'TypeBase::get/getChecked' methods to ensure that the arguments passed in are valid to construct a type instance with.
This method is expected to return failure if a type cannot be constructed with 'args', success otherwise.
'args' must correspond with the arguments passed into the 'TypeBase::get' call.
Type storage objects inherit from TypeStorage and contain the following:
The dialect that defined the type.
Any parameters of the type.
An optional mutable component. For non-parametric types, a convenience DefaultTypeStorage is provided. Parametric storage types must derive TypeStorage and respect the following:
Define a type alias, KeyTy, to a type that uniquely identifies the instance of the type.
The key type must be constructible from the values passed into the detail::TypeUniquer::get call.
If the KeyTy does not have an llvm::DenseMapInfo specialization, the storage class must define a hashing method: 'static unsigned hashKey(const KeyTy &)'
Provide a method, 'bool operator==(const KeyTy &) const', to compare the storage instance against an instance of the key type.
Provide a static construction method: 'DerivedStorage *construct(TypeStorageAllocator &, const KeyTy &key)' that builds a unique instance of the derived storage. The arguments to this function are an allocator to store any uniqued data within the context and the key type for this storage.
If they have a mutable component, this component must not be a part of
Definition at line 71 of file Types.h.
Member Typedef Documentation
ImplType
using mlir::Type::ImplType = TypeStorage
Definition at line 79 of file Types.h.
TypeBase
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits> using mlir::Type::TypeBase = detail::StorageUserBase<ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits...>
Utility class for implementing types.
Definition at line 77 of file Types.h.
Constructor & Destructor Documentation
Type() [1/3]
constexpr mlir::Type::Type () inline
Definition at line 81 of file Types.h.
Referenced by getFromOpaquePointer(), and Type().
Type() [2/3]
mlir::Type::Type (const ImplType * impl) inline
Definition at line 82 of file Types.h.
References operator=(), and Type().
Type() [3/3]
mlir::Type::Type (const Type & other) default
Member Function Documentation
cast()
template<typename U > U mlir::Type::cast () const
Definition at line 240 of file Types.h.
Referenced by mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::DenseFPElementsAttr::classof(), mlir::DenseIntElementsAttr::classof(), computeTensorReshapeCollapsedType(), convertArrayType(), mlir::LLVM::ModuleTranslation::convertOperation(), convertReassociationIndicesToMaps(), convertScalarType(), createConstantAllBitsSet(), createFPConstant(), createGlobalVarForEntryPointArgument(), createScopedSubViewIntersection(), doubleBuffer(), emitScalarImplementation(), extractOne(), mlir::StructBuilder::extractPtr(), extractShape(), extractVectorTypeFromScalarView(), foldExtractFromBroadcast(), foldExtractFromShapeCast(), foldTransferMaskAttribute(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), generateCopy(), generatePointWiseCopy(), mlir::IntegerAttr::get(), mlir::DenseElementsAttr::get(), getAtomicOpScope(), mlir::spirv::ArrayType::getCapabilities(), mlir::spirv::RuntimeArrayType::getCapabilities(), mlir::spirv::CooperativeMatrixNVType::getCapabilities(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::DenseElementsAttr::getComplexIntValues(), getDimMap(), mlir::AffineDmaStartOp::getDstMemorySpace(), mlir::AffineDmaStartOp::getDstMemRefRank(), mlir::AffineDmaStartOp::getDstMemRefType(), mlir::MemRefDescriptor::getElementPtrType(), mlir::spirv::MatrixType::getElementType(), mlir::spirv::ArrayType::getExtensions(), mlir::spirv::RuntimeArrayType::getExtensions(), mlir::spirv::CooperativeMatrixNVType::getExtensions(), getFullMemRefAsRegion(), mlir::detail::FloatAttributeStorage::getKey(), getLocalInvocationDimSize(), getMemRefAlignment(), getMemRefSizes(), getMultiLevelStrides(), getOrCreateUnrolledVectorSlice(), getPhiIncomingBlock(), mlir::quant::QuantizedType::getQuantizedElementType(), mlir::DenseIntOrFPElementsAttr::getRawComplex(), mlir::spirv::ArrayType::getSizeInBytes(), mlir::AffineDmaStartOp::getSrcMemorySpace(), mlir::AffineDmaStartOp::getSrcMemRefType(), mlir::AffineDmaStartOp::getTagMemRefRank(), mlir::AffineDmaWaitOp::getTagMemRefRank(), mlir::AffineDmaStartOp::getTagMemRefType(), mlir::AffineDmaWaitOp::getTagMemRefType(), mlir::Value::getType(), mlir::ElementsAttr::getType(), mlir::SparseElementsAttr::getValue(), mlir::Builder::getZeroAttr(), hasAllocationScope(), inferExtractOpResultType(), inferStridedSliceOpResultType(), inferTransposeResultType(), insertCopies(), insertOne(), isAsyncWithOneDependency(), mlir::quant::QuantizedType::isCompatibleExpressedType(), isElementwiseMappableOpOnRankedTensors(), isFnEntryBlock(), isMemRefNormalizable(), isRankReducedType(), joinShapes(), makeTiledShapes(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::MemRefDescriptor::MemRefDescriptor(), minusOneIntegerAttribute(), mlir::OperandElementTypeIterator::OperandElementTypeIterator(), operator!(), mlir::DenseElementsAttr::IntElementIterator::operator*(), optionallyTruncateOrExtend(), parseCallOp(), mlir::detail::Parser::parseElementsLiteralType(), parseGenericAtomicRMWOp(), parseNVVMShflSyncBflyOp(), parseSubTensorInsertOp(), parseSubTensorOp(), parseSubViewOp(), populateFromInt64AttrArray(), print(), printLandingpadOp(), produceSubViewErrorMsg(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), mlir::replaceAllMemRefUsesWith(), reshapeLoad(), reshapeLowerToHigher(), mlir::ResultElementTypeIterator::ResultElementTypeIterator(), mlir::LLVM::LLVMType::setStructTyBody(), mlir::MemRefDescriptor::size(), mlir::vector::splitFullAndPartialTransfer(), transferReadVector(), transferWriteVector(), mlir::ComplexStructBuilder::undef(), mlir::MemRefDescriptor::undef(), mlir::UnrankedMemRefDescriptor::undef(), unrollSingleResultStructuredOp(), mlir::vector::unrollSingleResultVectorOp(), unrollTransferReadOp(), mlir::vector::unrollTransferWriteOp(), vectorizeConstant(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), verifyAtomicUpdateOp(), verifyBlockReadWritePtrAndValTypes(), verifyCastOp(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::spirv::MatrixType::verifyConstructionInvariants(), verifyCopyMemory(), verifyLoadStorePtrAndValTypes(), verifyPointerAndCoopMatrixType(), verifyTransferOp(), walkReturnOperations(), and wrapExternalFunction().
classof()
static bool mlir::Type::classof (Type) inline static
Definition at line 102 of file Types.h.
dump()
void Type::dump ()
Definition at line 2529 of file AsmPrinter.cpp.
References print().
Referenced by getTypeID().
dyn_cast()
template<typename U > U mlir::Type::dyn_cast () const
Definition at line 234 of file Types.h.
Referenced by mlir::ValueDecomposer::addDecomposeValueConversion(), appendMangledType(), areVectorCastSimpleCompatible(), mlir::tosa::buildConvOpQuantizationAttr(), mlir::tosa::buildConvOpResultTypeInfo(), buildLLVMFunctionType(), buildLogicalBinaryOp(), mlir::tosa::buildMatMulOpQuantizationAttr(), buildMatMulOpWithQuantInfo(), mlir::tosa::buildPadOpQuantizationAttr(), mlir::tosa::buildQTypeFromMinMax(), mlir::tosa::buildUnaryOpQuantizationAttr(), mlir::spirv::SPIRVType::classof(), mlir::spirv::ScalarType::classof(), mlir::spirv::CompositeType::classof(), mlir::quant::ExpressedToQuantizedConverter::convert(), mlir::LLVMTypeConverter::convertCallingConventionType(), mlir::DenseIntOrFPElementsAttr::convertEndianOfArrayRefForBEmachine(), convertMemrefType(), convertScalarType(), convertTensorType(), createFPConstant(), mlir::VulkanLayoutUtils::decorateType(), mlir::vector::distributPointwiseVectorOp(), forwardPassthroughAttributes(), generateTransferOpSlices(), getBitWidth(), mlir::detail::getDenseElementBitWidth(), getElementPtrType(), getElementType(), mlir::getElementTypeOrSelf(), getEnclosingforOps(), getI1SameShape(), getInsertExtractValueElementType(), getLoadStoreElementType(), getPaddedInput(), getPhiIncomingBlock(), mlir::quant::QuantizedType::getQuantizedElementType(), getShape(), getTensorOrVectorElementType(), getTensorTypeFromMemRefType(), getTransferOpAdapter(), getTypeNumBytes(), getUnaryOpResultType(), mlir::Builder::getZeroAttr(), handleMultidimensionalVectors(), initializeAliases(), insertCopies(), isAllocationSupported(), isBoolScalarOrVector(), isFnEntryBlock(), mlir::VulkanLayoutUtils::isLegalType(), isMemRefNormalizable(), mlir::isOpaqueTypeWithName(), isSignedIntegerOrVector(), isSmallAlloc(), isUnsignedIntegerOrVector(), mlir::spirv::MatrixType::isValidColumnType(), isValidIntOrFloat(), isValidQuantizationSpec(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::TypeConverter::materializeTargetConversion(), minusOneIntegerAttribute(), operator!(), optionallyBroadcast(), parseAllocaOp(), parseAndVerifyMatrixType(), parseAndVerifyType(), parseAtomicCompareExchangeWeakOp(), parseAtomicUpdateOp(), parseAwaitResultType(), parseCallOp(), parseCmpOp(), mlir::OpAsmParser::parseColonType(), parseCompositeConstructOp(), parseConstShapeOp(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), parseExtractElementOp(), parseExtractOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseInsertElementOp(), parseInvokeOp(), mlir::detail::Parser::parseOptionalInteger(), parseOuterProductOp(), parseShuffleVectorOp(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), mlir::DialectAsmParser::parseType(), mlir::OpAsmParser::parseType(), parseVariableOp(), print(), printCalibratedQuantizedType(), mlir::quant::quantizeAttr(), reshapeLowerToHigher(), mlir::VectorType::scaleElementBitwidth(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), mlir::StructBuilder::StructBuilder(), mlir::structFuncArgTypeConverter(), transferWriteVector(), mlir::TypeRange::TypeRange(), unwrap(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), verifyCastOp(), mlir::verifyCompatibleShape(), mlir::quant::QuantizedType::verifyConstructionInvariants(), mlir::IntegerAttr::verifyConstructionInvariants(), and verifyOutputShape().
dyn_cast_or_null()
template<typename U > U mlir::Type::dyn_cast_or_null () const
Definition at line 237 of file Types.h.
Referenced by diag(), getVectorElementwiseOpUnrollState(), operator!(), unrollSingleResultStructuredOp(), mlir::vector::unrollSingleResultVectorOp(), and verify().
getAbstractType()
const AbstractType& mlir::Type::getAbstractType () inline
Return the abstract type descriptor for this type.
Definition at line 169 of file Types.h.
getAsOpaquePointer()
const void* mlir::Type::getAsOpaquePointer () const inline
Methods for supporting PointerLikeTypeTraits.
Definition at line 161 of file Types.h.
References impl.
Referenced by llvm::PointerLikeTypeTraits< mlir::Type >::getAsVoidPointer(), llvm::PointerLikeTypeTraits< mlir::LLVM::LLVMType >::getAsVoidPointer(), mlir::detail::PDLByteCode::initializeMutableState(), and mlir::AttributeStorage::setType().
getContext()
MLIRContext * Type::getContext () const
Return the MLIRContext in which this type was uniqued.
Definition at line 23 of file Types.cpp.
Referenced by mlir::LLVM::LLVMType::createStructTy(), mlir::quant::fakeQuantAttrsToType(), mlir::ComplexType::get(), mlir::spirv::ArrayType::get(), mlir::FloatAttr::get(), mlir::quant::AnyQuantizedType::get(), mlir::IntegerAttr::get(), mlir::spirv::PointerType::get(), mlir::spirv::RuntimeArrayType::get(), mlir::quant::UniformQuantizedType::get(), mlir::LLVM::LLVMArrayType::get(), mlir::LLVM::LLVMFunctionType::get(), mlir::quant::UniformQuantizedPerAxisType::get(), mlir::StringAttr::get(), mlir::VectorType::get(), mlir::LLVM::LLVMPointerType::get(), mlir::quant::CalibratedQuantizedType::get(), mlir::RankedTensorType::get(), mlir::TypeAttr::get(), mlir::spirv::CooperativeMatrixNVType::get(), mlir::UnrankedTensorType::get(), mlir::spirv::MatrixType::get(), mlir::LLVM::LLVMFixedVectorType::get(), mlir::LLVM::LLVMScalableVectorType::get(), mlir::UnrankedMemRefType::get(), mlir::DenseStringElementsAttr::get(), mlir::OpaqueElementsAttr::get(), mlir::SparseElementsAttr::get(), mlir::MemRefType::getChecked(), mlir::Attribute::getContext(), mlir::Value::getContext(), getI1SameShape(), getPhiIncomingBlock(), mlir::DenseIntOrFPElementsAttr::getRaw(), mlir::LLVM::LLVMType::getStructTy(), getTensorTypeFromMemRefType(), getTypeID(), outlineExecuteOp(), parseSymbol(), mlir::Value::setType(), and unwrap().
getDialect()
Dialect Type::getDialect () const
Get the dialect this type is registered to.
Definition at line 19 of file Types.cpp.
Referenced by mlir::quant::QuantizedType::classof(), mlir::spirv::SPIRVType::classof(), mlir::LLVM::LLVMType::classof(), mlir::LLVM::LLVMType::getDialect(), getTypeID(), mlir::TensorType::isValidElementType(), parseAndVerifyType(), printDenseElementsAttrImpl(), and verify().
getFromOpaquePointer()
static Type mlir::Type::getFromOpaquePointer (const void * pointer) inline static
Definition at line 164 of file Types.h.
References Type().
Referenced by mlir::DiagnosticArgument::getAsType(), llvm::PointerLikeTypeTraits< mlir::Type >::getFromVoidPointer(), and mlir::AttributeStorage::getType().
getIntOrFloatBitWidth()
unsigned Type::getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
Definition at line 93 of file Types.cpp.
Referenced by allocBuffer(), buildAttributeAPInt(), mlir::VulkanLayoutUtils::decorateType(), getBitWidth(), mlir::detail::getDenseElementBitWidth(), mlir::ShapedType::getElementTypeBitWidth(), mlir::Builder::getIntegerAttr(), getTypeID(), getTypeNumBytes(), verifyCastOp(), and verifyShuffleOp().
getTypeID()
TypeID mlir::Type::getTypeID () inline
Return a unique identifier for the concrete type.
This is used to support dynamic type casting.
Definition at line 106 of file Types.h.
References dump(), getContext(), getDialect(), getIntOrFloatBitWidth(), hash_value, isBF16(), isF16(), isF32(), isF64(), isIndex(), isInteger(), isIntOrFloat(), isIntOrIndex(), isIntOrIndexOrFloat(), isSignedInteger(), isSignlessInteger(), isSignlessIntOrFloat(), isSignlessIntOrIndex(), isSignlessIntOrIndexOrFloat(), isUnsignedInteger(), and print().
Referenced by areSameShapedTypeIgnoringElementType().
isa() [1/2]
template<typename U > bool mlir::Type::isa () const
Definition at line 224 of file Types.h.
Referenced by areAllLLVMTypes(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::ConstantFloatOp::classof(), mlir::spirv::SPIRVType::classof(), mlir::spirv::CompositeType::classof(), mlir::FloatType::classof(), mlir::ShapedType::classof(), mlir::TensorType::classof(), mlir::BaseMemRefType::classof(), mlir::LLVM::LLVMVectorType::classof(), mlir::DenseFPElementsAttr::classof(), cloneWithLoopRanges(), convertRangeType(), convertStructType(), createConstantAllBitsSet(), mlir::VulkanLayoutUtils::decorateType(), mlir::edsc::op::eq(), foldExtractFromBroadcast(), mlir::quant::ExpressedToQuantizedConverter::forInputType(), genLoad(), mlir::DenseElementsAttr::get(), mlir::SparseElementsAttr::get(), getAtomicOpScope(), getBitWidth(), mlir::OpTrait::util::getBroadcastedType(), mlir::DenseElementsAttr::getComplexFloatValues(), mlir::DenseElementsAttr::getComplexIntValues(), getI1SameShape(), getPhiIncomingBlock(), mlir::LLVMTypeConverter::getPointerBitwidth(), mlir::LLVM::LLVMType::getPrimitiveSizeInBits(), getProducerOfTensor(), mlir::quant::QuantizedType::getQuantizedElementType(), mlir::DenseIntOrFPElementsAttr::getRaw(), getTransferOpAdapter(), getTreePredicates(), getTypeNumBytes(), getVectorType(), mlir::Builder::getZeroAttr(), hasTensorOrVectorType(), mlir::detail::IntegerAttributeStorage::IntegerAttributeStorage(), isAccessIndexInvariant(), mlir::quant::QuantizedType::isCompatibleExpressedType(), isErrorPropagationPossible(), isFnEntryBlock(), isMemRefDereferencingOp(), isMemRefNormalizable(), isQuantizablePrimitiveType(), isRankReducedType(), mlir::async::isRefCounted(), mlir::LLVM::LLVMFunctionType::isValidArgumentType(), mlir::LLVM::LLVMArrayType::isValidElementType(), mlir::VectorType::isValidElementType(), mlir::TensorType::isValidElementType(), mlir::LLVM::LLVMPointerType::isValidElementType(), mlir::LLVM::LLVMStructType::isValidElementType(), mlir::BaseMemRefType::isValidElementType(), mlir::LLVM::LLVMVectorType::isValidElementType(), isValidIntOrFloat(), isValidQuantizationSpec(), mlir::LLVM::LLVMFunctionType::isValidResultType(), mlir::edsc::ops::linalg_generic_pointwise(), makeTiledShapes(), mappingHelper(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::edsc::op::ne(), operator!(), outlineExecuteOp(), mlir::AffineDmaWaitOp::parse(), mlir::detail::Parser::parseComplexType(), parseConstantOp(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), mlir::detail::Parser::parseElementsLiteralType(), mlir::detail::Parser::parseFloatAttr(), parseGlobalVariableOp(), print(), printDenseElementsAttrImpl(), printGPUFuncOp(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), signedCeilNonnegInputs(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::structFuncArgTypeConverter(), mlir::edsc::StructuredIndexed::StructuredIndexed(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), mlir::edsc::op::ult(), mlir::vector::unrollSingleResultVectorOp(), vectorizeConstant(), vectorizeOperand(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), mlir::quant::CalibratedQuantizedType::verifyConstructionInvariants(), verifyFloatTypeInvariants(), verifyIntegerTypeInvariants(), verifyOutputShape(), verifyPointerAndCoopMatrixType(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), and verifyShapeOrExtentTensorOp().
isa() [2/2]
template<typename First , typename Second , typename... Rest> bool mlir::Type::isa () const
Definition at line 230 of file Types.h.
isBF16()
bool Type::isBF16 () const
Definition at line 25 of file Types.cpp.
Referenced by getTypeID(), mlir::quant::QuantizedType::isSigned(), mlir::spirv::ScalarType::isValid(), and parseAndVerifyType().
isF16()
bool Type::isF16 () const
Definition at line 26 of file Types.cpp.
Referenced by getTypeID(), and mlir::quant::QuantizedType::isSigned().
isF32()
bool Type::isF32 () const
Definition at line 27 of file Types.cpp.
Referenced by convertFloatAttr(), getSrcVectorElementType(), getTypeID(), and mlir::quant::QuantizedType::isSigned().
isF64()
bool Type::isF64 () const
Definition at line 28 of file Types.cpp.
Referenced by buildHexadecimalFloatLiteral(), mlir::detail::FloatAttributeStorage::getKey(), getSrcVectorElementType(), getTypeID(), mlir::quant::QuantizedType::isSigned(), and parseElementAttrHexValues().
isIndex()
bool Type::isIndex () const
Definition at line 30 of file Types.cpp.
Referenced by buildAttributeAPInt(), ceilDivPositive(), mlir::ConstantIndexOp::classof(), mlir::IntegerAttr::get(), mlir::detail::getDenseElementBitWidth(), getGenericEffectsImpl(), mlir::Builder::getIntegerAttr(), getTransferOpAdapter(), getTypeID(), mlir::detail::IntegerAttributeStorage::IntegerAttributeStorage(), mlir::quant::QuantizedType::isSigned(), isSmallAlloc(), mlir::isValidDim(), isValidIntOrFloat(), mlir::isValidSymbol(), mlir::DmaStartOp::verify(), mlir::DmaWaitOp::verify(), and verify().
isInteger()
bool Type::isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
Definition at line 33 of file Types.cpp.
Referenced by mlir::detail::DenseIntOrFPElementsAttributeStorage::construct(), mlir::DenseElementsAttr::get(), mlir::SparseElementsAttr::get(), getAtomicOpScope(), mlir::detail::DenseIntOrFPElementsAttributeStorage::getKey(), getTypeID(), isBoolScalarOrVector(), mlir::quant::QuantizedType::isSigned(), mlir::edsc::op::negate(), mlir::detail::DenseIntOrFPElementsAttributeStorage::operator==(), mlir::edsc::op::operator||(), and parseElementAttrHexValues().
isIntOrFloat()
bool Type::isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
Definition at line 89 of file Types.cpp.
Referenced by mlir::DenseElementsAttr::get(), getBitWidth(), getTypeID(), isAllocationSupported(), isFnEntryBlock(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), parseElementAttrHexValues(), and mlir::ComplexType::verifyConstructionInvariants().
isIntOrIndex()
bool Type::isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
Definition at line 87 of file Types.cpp.
Referenced by mlir::DenseIntElementsAttr::classof(), mlir::DenseElementsAttr::get(), getTransferOpAdapter(), getTypeID(), parseElementAttrHexValues(), and verify().
isIntOrIndexOrFloat()
bool Type::isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
Definition at line 91 of file Types.cpp.
Referenced by mlir::DenseElementsAttr::get(), getAtomicOpScope(), getTypeID(), mlir::BaseMemRefType::isValidElementType(), parseElementAttrHexValues(), verify(), and verifyRegionAttribute().
isSignedInteger() [1/2]
bool Type::isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
Definition at line 51 of file Types.cpp.
Referenced by buildAttributeAPInt(), mlir::Builder::getIntegerAttr(), getTypeID(), and isSignedIntegerOrVector().
isSignedInteger() [2/2]
bool Type::isSignedInteger (unsigned width) const
Definition at line 57 of file Types.cpp.
isSignlessInteger() [1/2]
bool Type::isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
Definition at line 39 of file Types.cpp.
Referenced by mlir::ConstantIntOp::build(), mlir::ConstantIntOp::classof(), mlir::IntegerAttr::get(), getTypeID(), signedCeilNonnegInputs(), and verify().
isSignlessInteger() [2/2]
bool Type::isSignlessInteger (unsigned width) const
Definition at line 45 of file Types.cpp.
isSignlessIntOrFloat()
bool Type::isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
Definition at line 83 of file Types.cpp.
Referenced by getTypeID(), mlir::linalg::RegionMatcher::matchAsScalarBinaryOp(), verify(), and verifyShuffleOp().
isSignlessIntOrIndex()
bool Type::isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
Definition at line 75 of file Types.cpp.
Referenced by getTypeID(), and mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike().
isSignlessIntOrIndexOrFloat()
bool Type::isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
Definition at line 79 of file Types.cpp.
Referenced by appendMangledType(), and getTypeID().
isUnsignedInteger() [1/2]
bool Type::isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
Definition at line 63 of file Types.cpp.
Referenced by getTransferOpAdapter(), getTypeID(), isUnsignedIntegerOrVector(), mlir::detail::Parser::parseDecOrHexAttr(), parseElementAttrHexValues(), and printDenseElementsAttrImpl().
isUnsignedInteger() [2/2]
bool Type::isUnsignedInteger (unsigned width) const
Definition at line 69 of file Types.cpp.
operator bool()
mlir::Type::operator bool () const inline explicit
Definition at line 90 of file Types.h.
References impl.
operator!()
bool mlir::Type::operator! () const inline
Definition at line 92 of file Types.h.
References cast(), dyn_cast(), dyn_cast_or_null(), and isa().
operator!=()
bool mlir::Type::operator!= (Type other) const inline
Definition at line 89 of file Types.h.
operator=()
Type& mlir::Type::operator= (const Type & other) default
Referenced by Type().
operator==()
bool mlir::Type::operator== (Type other) const inline
Definition at line 88 of file Types.h.
References impl.
print()
void Type::print (raw_ostream & os)
Print the current type.
Definition at line 2527 of file AsmPrinter.cpp.
Referenced by getTypeID(), and mlir::operator<<().
Friends And Related Function Documentation
hash_value
::llvm::hash_code hash_value (Type arg) friend
Definition at line 220 of file Types.h.
Referenced by getTypeID().
Member Data Documentation
impl
ImplType* mlir::Type::impl protected
Definition at line 172 of file Types.h.
Referenced by getAsOpaquePointer(), mlir::LLVM::LLVMVectorType::getElementType(), mlir::hash_value(), operator bool(), and operator==().
The documentation for this class was generated from the following files:
include/mlir/IR/Types.h
lib/IR/AsmPrinter.cpp
lib/IR/Types.cpp
lib/TableGen/Type.cpp