MLIR: mlir::OperationName Class Reference
mlir::OperationName Class Reference
#include "mlir/IR/OperationSupport.h"
Public Types
using RepresentationUnion = PointerUnion< Identifier, const AbstractOperation * >
Public Member Functions
OperationName (AbstractOperation *op)
OperationName (StringRef name, MLIRContext *context)
Form the OperationName for an op with the specified string.
StringRef getDialect () const
Return the name of the dialect this operation is registered to.
StringRef stripDialect () const
Return the operation name with dialect name stripped, if it has one.
StringRef getStringRef () const
Return the name of this operation. This always succeeds.
Identifier getIdentifier () const
Return the name of this operation as an identifier. This always succeeds.
const AbstractOperation * getAbstractOperation () const
If this operation has a registered operation description, return it.
void print (raw_ostream &os) const
void dump () const
void * getAsOpaquePointer () const
Static Public Member Functions
static OperationName getFromOpaquePointer (const void *pointer)
Detailed Description
Definition at line 325 of file OperationSupport.h.
Member Typedef Documentation
RepresentationUnion
using mlir::OperationName::RepresentationUnion = PointerUnion<Identifier, const AbstractOperation *>
Definition at line 328 of file OperationSupport.h.
Constructor & Destructor Documentation
OperationName() [1/2]
mlir::OperationName::OperationName (AbstractOperation * op) inline
Definition at line 330 of file OperationSupport.h.
References print().
OperationName() [2/2]
OperationName::OperationName (StringRef name, MLIRContext * context)
Form the OperationName for an op with the specified string.
This either is a reference to an AbstractOperation if one is known, or a uniqued Identifier if not.
Definition at line 30 of file Operation.cpp.
References mlir::Identifier::get(), and mlir::AbstractOperation::lookup().
Member Function Documentation
dump()
void OperationName::dump () const
Definition at line 47 of file AsmPrinter.cpp.
References print().
getAbstractOperation()
const AbstractOperation * OperationName::getAbstractOperation () const
If this operation has a registered operation description, return it.
Otherwise return null.
Definition at line 60 of file Operation.cpp.
Referenced by mlir::Operation::create(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::Operation::getAbstractOperation(), mlir::detail::PDLByteCode::initializeMutableState(), mlir::detail::Parser::parseOptionalInteger(), mlir::OpPassManager::setNesting(), and verify().
getAsOpaquePointer()
void* mlir::OperationName::getAsOpaquePointer () const inline
Definition at line 352 of file OperationSupport.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::OperationName >::getAsVoidPointer(), llvm::DenseMapInfo< mlir::OperationName >::getHashValue(), mlir::hash_value(), mlir::operator!=(), and mlir::operator==().
getDialect()
StringRef OperationName::getDialect () const
Return the name of the dialect this operation is registered to.
Definition at line 38 of file Operation.cpp.
Referenced by mlir::ConversionTarget::isLegal().
getFromOpaquePointer()
OperationName OperationName::getFromOpaquePointer (const void * pointer) static
Definition at line 64 of file Operation.cpp.
Referenced by llvm::DenseMapInfo< mlir::OperationName >::getEmptyKey(), llvm::PointerLikeTypeTraits< mlir::OperationName >::getFromVoidPointer(), and llvm::DenseMapInfo< mlir::OperationName >::getTombstoneKey().
getIdentifier()
Identifier OperationName::getIdentifier () const
Return the name of this operation as an identifier. This always succeeds.
Definition at line 54 of file Operation.cpp.
References mlir::Identifier::get().
Referenced by hasSizeMismatch(), parseConstShapeOp(), mlir::PassManager::run(), mlir::detail::OpToOpPassAdaptor::runOnOperation(), and mlir::OpPassManager::setNesting().
getStringRef()
StringRef OperationName::getStringRef () const
Return the name of this operation. This always succeeds.
Definition at line 49 of file Operation.cpp.
Referenced by mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::classof(), cloneOpWithOperandsAndTypes(), mlir::OpBuilder::create(), mlir::OpBuilder::createOrFold(), mlir::linalg::generateLibraryCallName(), inlineCallsInSCC(), mlir::Diagnostic::operator<<(), parseParallelOp(), printDenseElementsAttrImpl(), printStandardBinaryOp(), printStandardCastOp(), printStandardUnaryOp(), vectorizeOneOperation(), and mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait().
print()
void OperationName::print (raw_ostream & os) const
Definition at line 45 of file AsmPrinter.cpp.
Referenced by mlir::operator<<().
stripDialect()
StringRef OperationName::stripDialect () const
Return the operation name with dialect name stripped, if it has one.
Definition at line 43 of file Operation.cpp.
The documentation for this class was generated from the following files:
include/mlir/IR/OperationSupport.h
lib/IR/AsmPrinter.cpp
lib/IR/Operation.cpp