MLIR: mlir::tblgen::TypeDef Class Reference
mlir::tblgen::TypeDef Class Reference
Wrapper class that contains a TableGen TypeDef's record and provides helper methods for accessing them.
#include "mlir/TableGen/TypeDef.h"
Public Member Functions
TypeDef (const llvm::Record *def)
Dialect getDialect () const
StringRef getName () const
bool hasDescription () const
StringRef getDescription () const
bool hasSummary () const
StringRef getSummary () const
StringRef getCppClassName () const
StringRef getCppBaseClassName () const
StringRef getStorageClassName () const
StringRef getStorageNamespace () const
bool genStorageClass () const
bool hasStorageCustomConstructor () const
void getParameters (SmallVectorImpl< TypeParameter > &) const
unsigned getNumParameters () const
Optional< StringRef > getMnemonic () const
Optional< StringRef > getPrinterCode () const
Optional< StringRef > getParserCode () const
bool genAccessors () const
bool genVerifyInvariantsDecl () const
Optional< StringRef > getExtraDecls () const
ArrayRef< llvm::SMLoc > getLoc () const
bool operator== (const TypeDef &other) const
bool operator< (const TypeDef &other) const
operator bool () const
Detailed Description
Wrapper class that contains a TableGen TypeDef's record and provides helper methods for accessing them.
Definition at line 32 of file TypeDef.h.
Constructor & Destructor Documentation
TypeDef()
mlir::tblgen::TypeDef::TypeDef (const llvm::Record * def) inline explicit
Definition at line 34 of file TypeDef.h.
References mlir::operator<(), and mlir::operator==().
Member Function Documentation
genAccessors()
bool TypeDef::genAccessors () const
Definition at line 90 of file TypeDef.cpp.
genStorageClass()
bool TypeDef::genStorageClass () const
Definition at line 63 of file TypeDef.cpp.
genVerifyInvariantsDecl()
bool TypeDef::genVerifyInvariantsDecl () const
Definition at line 93 of file TypeDef.cpp.
getCppBaseClassName()
StringRef TypeDef::getCppBaseClassName () const
Definition at line 34 of file TypeDef.cpp.
getCppClassName()
StringRef TypeDef::getCppClassName () const
Definition at line 30 of file TypeDef.cpp.
getDescription()
StringRef TypeDef::getDescription () const
Definition at line 43 of file TypeDef.cpp.
getDialect()
Dialect TypeDef::getDialect () const
Definition at line 21 of file TypeDef.cpp.
getExtraDecls()
llvm::Optional< StringRef > TypeDef::getExtraDecls () const
Definition at line 96 of file TypeDef.cpp.
getLoc()
llvm::ArrayRef< llvm::SMLoc > TypeDef::getLoc () const
Definition at line 100 of file TypeDef.cpp.
getMnemonic()
llvm::Optional< StringRef > TypeDef::getMnemonic () const
Definition at line 81 of file TypeDef.cpp.
getName()
StringRef TypeDef::getName () const
Definition at line 29 of file TypeDef.cpp.
Referenced by operator<().
getNumParameters()
unsigned TypeDef::getNumParameters () const
Definition at line 77 of file TypeDef.cpp.
getParameters()
void TypeDef::getParameters (SmallVectorImpl< TypeParameter > & parameters) const
Definition at line 69 of file TypeDef.cpp.
getParserCode()
llvm::Optional< StringRef > TypeDef::getParserCode () const
Definition at line 87 of file TypeDef.cpp.
getPrinterCode()
llvm::Optional< StringRef > TypeDef::getPrinterCode () const
Definition at line 84 of file TypeDef.cpp.
getStorageClassName()
StringRef TypeDef::getStorageClassName () const
Definition at line 56 of file TypeDef.cpp.
getStorageNamespace()
StringRef TypeDef::getStorageNamespace () const
Definition at line 59 of file TypeDef.cpp.
getSummary()
StringRef TypeDef::getSummary () const
Definition at line 52 of file TypeDef.cpp.
hasDescription()
bool TypeDef::hasDescription () const
Definition at line 38 of file TypeDef.cpp.
hasStorageCustomConstructor()
bool TypeDef::hasStorageCustomConstructor () const
Definition at line 66 of file TypeDef.cpp.
hasSummary()
bool TypeDef::hasSummary () const
Definition at line 47 of file TypeDef.cpp.
operator bool()
mlir::tblgen::TypeDef::operator bool () const inline
Definition at line 106 of file TypeDef.h.
operator<()
bool TypeDef::operator< (const TypeDef & other) const
Definition at line 105 of file TypeDef.cpp.
References getName().
operator==()
bool TypeDef::operator== (const TypeDef & other) const
Definition at line 101 of file TypeDef.cpp.
The documentation for this class was generated from the following files:
include/mlir/TableGen/TypeDef.h
lib/TableGen/TypeDef.cpp