MLIR: mlir::spirv::TargetEnvAttr Class Reference
mlir::spirv::TargetEnvAttr Class Reference
An attribute that specifies the target version, allowed extensions and capabilities, and resource limits.
#include "mlir/Dialect/SPIRV/SPIRVAttributes.h"
Public Member Functions
VerCapExtAttr getTripleAttr () const
Returns the (version, capabilities, extensions) triple attribute.
Version getVersion () const
Returns the target version.
VerCapExtAttr::ext_range getExtensions ()
Returns the target extensions.
ArrayAttr getExtensionsAttr ()
Returns the target extensions as a string array attribute.
VerCapExtAttr::cap_range getCapabilities ()
Returns the target capabilities.
ArrayAttr getCapabilitiesAttr ()
Returns the target capabilities as an integer array attribute.
Vendor getVendorID () const
Returns the vendor ID.
DeviceType getDeviceType () const
Returns the device type.
uint32_t getDeviceID () const
Returns the device ID.
ResourceLimitsAttr getResourceLimits () const
Returns the target resource limits.
Static Public Member Functions
static TargetEnvAttr get (VerCapExtAttr triple, Vendor vendorID, DeviceType deviceType, uint32_t deviceId, DictionaryAttr limits)
Gets a TargetEnvAttr instance.
static StringRef getKindName ()
Returns the attribute kind's name (without the 'spv.' prefix).
static LogicalResult verifyConstructionInvariants (Location loc, VerCapExtAttr triple, Vendor vendorID, DeviceType deviceType, uint32_t deviceID, DictionaryAttr limits)
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr uint32_t kUnknownDeviceID = 0x7FFFFFFF
ID for unknown devices.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
An attribute that specifies the target version, allowed extensions and capabilities, and resource limits.
These information describes a SPIR-V target environment.
Definition at line 124 of file SPIRVAttributes.h.
Member Function Documentation
get()
spirv::TargetEnvAttr spirv::TargetEnvAttr::get (spirv::VerCapExtAttr triple, Vendor vendorID, DeviceType deviceType, uint32_t deviceId, DictionaryAttr limits) static
Gets a TargetEnvAttr instance.
Definition at line 279 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get().
Referenced by mlir::spirv::getDefaultTargetEnv(), and parseTargetEnvAttr().
getCapabilities()
spirv::VerCapExtAttr::cap_range spirv::TargetEnvAttr::getCapabilities ()
Returns the target capabilities.
Definition at line 307 of file SPIRVAttributes.cpp.
Referenced by mlir::spirv::getAddressingModel(), mlir::spirv::getExecutionModel(), mlir::spirv::getMemoryModel(), mlir::spirv::needsInterfaceVarABIAttrs(), and mlir::spirv::TargetEnv::TargetEnv().
getCapabilitiesAttr()
ArrayAttr spirv::TargetEnvAttr::getCapabilitiesAttr ()
Returns the target capabilities as an integer array attribute.
Definition at line 311 of file SPIRVAttributes.cpp.
getDeviceID()
uint32_t spirv::TargetEnvAttr::getDeviceID () const
Returns the device ID.
Definition at line 323 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by mlir::spirv::TargetEnv::getDeviceID(), and print().
getDeviceType()
spirv::DeviceType spirv::TargetEnvAttr::getDeviceType () const
Returns the device type.
Definition at line 319 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by mlir::spirv::TargetEnv::getDeviceType(), and print().
getExtensions()
spirv::VerCapExtAttr::ext_range spirv::TargetEnvAttr::getExtensions ()
Returns the target extensions.
Definition at line 299 of file SPIRVAttributes.cpp.
Referenced by mlir::spirv::TargetEnv::TargetEnv().
getExtensionsAttr()
ArrayAttr spirv::TargetEnvAttr::getExtensionsAttr ()
Returns the target extensions as a string array attribute.
Definition at line 303 of file SPIRVAttributes.cpp.
getKindName()
StringRef spirv::TargetEnvAttr::getKindName () static
Returns the attribute kind's name (without the 'spv.' prefix).
Definition at line 289 of file SPIRVAttributes.cpp.
Referenced by parseTargetEnvAttr(), and print().
getResourceLimits()
spirv::ResourceLimitsAttr spirv::TargetEnvAttr::getResourceLimits () const
Returns the target resource limits.
Definition at line 327 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by mlir::spirv::TargetEnv::getResourceLimits(), and print().
getTripleAttr()
spirv::VerCapExtAttr spirv::TargetEnvAttr::getTripleAttr () const
Returns the (version, capabilities, extensions) triple attribute.
Definition at line 291 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by print().
getVendorID()
spirv::Vendor spirv::TargetEnvAttr::getVendorID () const
Returns the vendor ID.
Definition at line 315 of file SPIRVAttributes.cpp.
References mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getImpl().
Referenced by mlir::spirv::TargetEnv::getVendorID(), and print().
getVersion()
spirv::Version spirv::TargetEnvAttr::getVersion () const
Returns the target version.
Definition at line 295 of file SPIRVAttributes.cpp.
Referenced by checkAndUpdateCapabilityRequirements(), mlir::spirv::TargetEnv::getVersion(), and mlir::spirv::TargetEnv::TargetEnv().
verifyConstructionInvariants()
LogicalResult spirv::TargetEnvAttr::verifyConstructionInvariants (Location loc, VerCapExtAttr triple, Vendor vendorID, DeviceType deviceType, uint32_t deviceID, DictionaryAttr limits) static
Definition at line 331 of file SPIRVAttributes.cpp.
References mlir::emitError(), and mlir::success().
Member Data Documentation
kUnknownDeviceID
constexpr uint32_t mlir::spirv::TargetEnvAttr::kUnknownDeviceID = 0x7FFFFFFF static
ID for unknown devices.
Definition at line 129 of file SPIRVAttributes.h.
Referenced by mlir::spirv::getDefaultTargetEnv(), parseTargetEnvAttr(), and print().
The documentation for this class was generated from the following files:
include/mlir/Dialect/SPIRV/SPIRVAttributes.h
lib/Dialect/SPIRV/SPIRVAttributes.cpp