MLIR: mlir::BaseMemRefType Class Reference
mlir::BaseMemRefType Class Reference
Base MemRef for Ranked and Unranked variants.
#include "mlir/IR/BuiltinTypes.h"
Public Types
using ImplType = detail::BaseMemRefTypeStorage
Public Types inherited from mlir::ShapedType
using ImplType = detail::ShapedTypeStorage
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
Public Member Functions
unsigned getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Public Member Functions inherited from mlir::ShapedType
Type getElementType () const
Return the element type.
unsigned getElementTypeBitWidth () const
If an element type is an integer or a float, return its width.
int64_t getNumElements () const
If it has static shape, return the number of elements. Otherwise, abort.
int64_t getRank () const
If this is a ranked type, return the rank. Otherwise, abort.
bool hasRank () const
Whether or not this is a ranked type.
ArrayRef< int64_t > getShape () const
If this is a ranked type, return the shape. Otherwise, abort.
bool hasStaticShape () const
If this is unranked type or any dimension has unknown size (<0), it doesn't have static shape.
bool hasStaticShape (ArrayRef< int64_t > shape) const
If this has a static shape and the shape is equal to shape return true.
int64_t getNumDynamicDims () const
If this is a ranked type, return the number of dimensions with dynamic size.
int64_t getDimSize (unsigned idx) const
If this is ranked type, return the size of the specified dimension.
bool isDynamicDim (unsigned idx) const
Returns true if this dimension has a dynamic size (for ranked types); aborts for unranked types.
unsigned getDynamicDimIndex (unsigned index) const
Returns the position of the dynamic dimension relative to just the dynamic dimensions, given its index within the shape.
int64_t getSizeInBits () const
Get the total amount of bits occupied by a value of this type.
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os)
Print the current type.
void dump ()
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static bool isValidElementType (Type type)
Return true if the specified element type is ok in a memref.
static bool classof (Type type)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from mlir::ShapedType
static bool classof (Type type)
Methods for support type inquiry through isa, cast, and dyn_cast.
static constexpr bool isDynamic (int64_t dSize)
Whether the given dimension size indicates a dynamic dimension.
static constexpr bool isDynamicStrideOrOffset (int64_t dStrideOrOffset)
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Static Public Attributes inherited from mlir::ShapedType
static constexpr int64_t kDynamicSize = -1
static constexpr int64_t kDynamicStrideOrOffset
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
Base MemRef for Ranked and Unranked variants.
Definition at line 441 of file BuiltinTypes.h.
Member Typedef Documentation
ImplType
using mlir::BaseMemRefType::ImplType = detail::BaseMemRefTypeStorage
Definition at line 443 of file BuiltinTypes.h.
Member Function Documentation
classof()
bool mlir::BaseMemRefType::classof (Type type) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 645 of file BuiltinTypes.h.
References mlir::Type::isa().
getMemorySpace()
unsigned BaseMemRefType::getMemorySpace () const
Returns the memory space in which data referred to by this memref resides.
Definition at line 424 of file BuiltinTypes.cpp.
Referenced by verify().
isValidElementType()
static bool mlir::BaseMemRefType::isValidElementType (Type type) inline static
Return true if the specified element type is ok in a memref.
Definition at line 447 of file BuiltinTypes.h.
References mlir::Type::isa(), and mlir::Type::isIntOrIndexOrFloat().
Referenced by mlir::MemRefType::getChecked(), and mlir::UnrankedMemRefType::verifyConstructionInvariants().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinTypes.h
lib/IR/BuiltinTypes.cpp