MLIR: mlir::edsc::ScopedContext Class Reference
mlir::edsc::ScopedContext Class Reference
Helper class to transparently handle builder insertion points by RAII.
#include "mlir/EDSC/Builders.h"
Public Member Functions
ScopedContext (OpBuilder &b)
ScopedContext (OpBuilder &b, Location location)
ScopedContext (OpBuilder &b, OpBuilder::InsertPoint newInsertPt, Location location)
Sets the insertion point of the builder to 'newInsertPt' for the duration of the scope.
~ScopedContext ()
Static Public Member Functions
static MLIRContext * getContext ()
static OpBuilder & getBuilderRef ()
static Location getLocation ()
Friends
class NestedBuilder
Only NestedBuilder (which is used to create an operation with a body) may access private members in order to implement scoping.
Detailed Description
Helper class to transparently handle builder insertion points by RAII.
As its name indicates, a ScopedContext is means to be used locally in a scoped fashion. This abstracts away all the boilerplate related to checking proper usage of captures, NestedBuilders as well as handling the setting and restoring of insertion points.
Definition at line 31 of file Builders.h.
Constructor & Destructor Documentation
ScopedContext() [1/3]
mlir::edsc::ScopedContext::ScopedContext (OpBuilder & b)
Definition at line 18 of file Builders.cpp.
References ScopedContext().
Referenced by ScopedContext().
ScopedContext() [2/3]
mlir::edsc::ScopedContext::ScopedContext (OpBuilder & b, Location location)
Definition at line 21 of file Builders.cpp.
References ScopedContext().
ScopedContext() [3/3]
mlir::edsc::ScopedContext::ScopedContext (OpBuilder & b, OpBuilder::InsertPoint newInsertPt, Location location)
Sets the insertion point of the builder to 'newInsertPt' for the duration of the scope.
The existing insertion point of the builder is restored on destruction.
Definition at line 30 of file Builders.cpp.
References mlir::OpBuilder::restoreInsertionPoint(), and ScopedContext().
~ScopedContext()
mlir::edsc::ScopedContext::~ScopedContext ()
Definition at line 39 of file Builders.cpp.
Member Function Documentation
getBuilderRef()
OpBuilder & mlir::edsc::ScopedContext::getBuilderRef () static
Definition at line 48 of file Builders.cpp.
Referenced by mlir::edsc::affineLoopBuilder(), mlir::edsc::affineLoopNestBuilder(), mlir::edsc::appendToBlock(), applyMapToValues(), mlir::edsc::buildInNewBlock(), mlir::edsc::conditionBuilder(), convertRangeType(), createBinaryIndexHandle(), mlir::edsc::createBlock(), mlir::edsc::createBlockInRegion(), createFComparisonExpr(), createIComparisonExpr(), mlir::linalg::GenerateLoopNest< LoopTy >::doit(), emitScalarImplementation(), mlir::edsc::intrinsics::FoldedValueBuilder< Op >::FoldedValueBuilder(), getContext(), getInputAndOutputIndices(), getPaddedInput(), inlineRegionAndEmitStore(), mlir::edsc::loopNestBuilder(), mlir::edsc::makeGenericLinalgOp(), mlir::edsc::OperationBuilder< Op >::OperationBuilder(), permuteIvs(), tileLinalgOpImpl(), and mlir::edsc::ValueBuilder< Op >::ValueBuilder().
getContext()
MLIRContext * mlir::edsc::ScopedContext::getContext () static
Definition at line 60 of file Builders.cpp.
References getBuilderRef(), and mlir::Builder::getContext().
Referenced by mlir::edsc::affineLoopBuilder(), mlir::edsc::affineLoopNestBuilder(), mlir::edsc::appendToBlock(), mlir::edsc::buildInNewBlock(), mlir::edsc::conditionBuilder(), createBinaryIndexHandle(), mlir::edsc::createBlock(), mlir::edsc::createBlockInRegion(), getPaddedInput(), mlir::edsc::ops::linalg_generic_conv_nhwc(), mlir::edsc::ops::linalg_generic_dilated_conv_nhwc(), mlir::edsc::ops::linalg_generic_matmul(), mlir::edsc::loopNestBuilder(), and mlir::edsc::ops::vector_contraction_matmul().
getLocation()
Location mlir::edsc::ScopedContext::getLocation () static
Definition at line 54 of file Builders.cpp.
Referenced by mlir::edsc::affineLoopBuilder(), mlir::edsc::affineLoopNestBuilder(), mlir::edsc::conditionBuilder(), convertRangeType(), createBinaryIndexHandle(), createFComparisonExpr(), createIComparisonExpr(), mlir::linalg::GenerateLoopNest< LoopTy >::doit(), emitScalarImplementation(), mlir::edsc::intrinsics::FoldedValueBuilder< Op >::FoldedValueBuilder(), getInputAndOutputIndices(), mlir::edsc::loopNestBuilder(), mlir::edsc::makeGenericLinalgOp(), mlir::edsc::OperationBuilder< Op >::OperationBuilder(), permuteIvs(), tileLinalgOpImpl(), and mlir::edsc::ValueBuilder< Op >::ValueBuilder().
Friends And Related Function Documentation
NestedBuilder
friend class NestedBuilder friend
Only NestedBuilder (which is used to create an operation with a body) may access private members in order to implement scoping.
Definition at line 50 of file Builders.h.
The documentation for this class was generated from the following files:
include/mlir/EDSC/Builders.h
lib/EDSC/Builders.cpp