MLIR: mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType > Class Template Reference
mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType > Class Template Reference
This class provides a verifier for structured ops that are known to operate on buffers or tensors and that support ins, outs and init arguments.
#include "mlir/Dialect/Linalg/IR/LinalgTraits.h"
Public Member Functions
unsigned getNumInputs ()
unsigned getNumInitTensors ()
unsigned getNumOutputs ()
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, NamedStructuredOpTrait >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType >
This class provides a verifier for structured ops that are known to operate on buffers or tensors and that support ins, outs and init arguments.
This trait must be used in conjunction with an op definition or a trait that provides the methods getNumInputs and getNumOutputs.
Use as a trait as follows:
class MatmulOp : public Op<MatmulOp, OpTrait::NamedStructuredOpTrait> {
Definition at line 95 of file LinalgTraits.h.
Member Function Documentation
getNumInitTensors()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType >::getNumInitTensors () inline
Definition at line 101 of file LinalgTraits.h.
References mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getNumInputs()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType >::getNumInputs () inline
Definition at line 98 of file LinalgTraits.h.
References mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
getNumOutputs()
template<typename ConcreteType > unsigned mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType >::getNumOutputs () inline
Definition at line 104 of file LinalgTraits.h.
References mlir::OpTrait::TraitBase< ConcreteType, NInputs< N >::Impl >::getOperation().
verifyTrait()
template<typename ConcreteType > static LogicalResult mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 109 of file LinalgTraits.h.
References mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getNumResults(), mlir::AffineMap::getResults(), mlir::Operation::getResultTypes(), mlir::success(), and mlir::OpTrait::impl::verifyAtLeastNOperands().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Linalg/IR/LinalgTraits.h