MLIR: mlir::python::PyType Class Reference
mlir::python::PyType Class Reference
Wrapper around the generic MlirType.
#include "Bindings/Python/IRModules.h"
Public Member Functions
PyType (PyMlirContextRef contextRef, MlirType type)
bool operator== (const PyType &other)
operator MlirType () const
MlirType get () const
pybind11::object getCapsule ()
Gets a capsule wrapping the void* within the MlirContext.
Public Member Functions inherited from mlir::python::BaseContextObject
BaseContextObject (PyMlirContextRef ref)
PyMlirContextRef & getContext ()
Accesses the context reference.
Static Public Member Functions
static PyType createFromCapsule (pybind11::object capsule)
Creates a PyMlirContext from the MlirContext wrapped by a capsule.
Detailed Description
Wrapper around the generic MlirType.
The lifetime of a type is bound by the PyContext that created it.
Definition at line 628 of file IRModules.h.
Constructor & Destructor Documentation
PyType()
mlir::python::PyType::PyType (PyMlirContextRef contextRef, MlirType type) inline
Definition at line 630 of file IRModules.h.
References mlir::operator==().
Member Function Documentation
createFromCapsule()
PyType PyType::createFromCapsule (pybind11::object capsule) static
Creates a PyMlirContext from the MlirContext wrapped by a capsule.
Note that PyMlirContext instances are uniqued, so the returned object may be a pre-existing object. Ownership of the underlying MlirContext is taken by calling this function.
Definition at line 1157 of file IRModules.cpp.
References mlir::python::PyInsertionPoint::atBlockBegin(), mlir::python::PyInsertionPoint::atBlockTerminator(), MlirNamedAttribute::attribute, mlir::python::PyOperation::checkValid(), mlir::python::PyMlirContext::contextEnter(), mlir::python::PyLocation::contextEnter(), mlir::python::PyInsertionPoint::contextEnter(), mlir::python::PyMlirContext::contextExit(), mlir::python::PyLocation::contextExit(), mlir::python::PyInsertionPoint::contextExit(), mlir::python::PyOperation::create(), createCustomDialectWrapper(), mlir::python::PyMlirContext::createFromCapsule(), mlir::python::PyLocation::createFromCapsule(), mlir::python::PyModule::createFromCapsule(), mlir::python::PyAttribute::createFromCapsule(), mlir::python::PyMlirContext::createNewContextForInit(), mlir::python::PyOperation::createOpView(), MlirStringRef::data, mlir::python::PyMlirContext::forContext(), mlir::python::PyModule::forModule(), mlir::python::PyOperation::forOperation(), mlir::python::Defaulting< DerivedTy, T >::get(), mlir::python::PyOperation::get(), mlir::python::PyRegion::get(), mlir::python::PyBlock::get(), mlir::python::PyAttribute::get(), get(), mlir::python::PyValue::get(), mlir::python::PyOperationBase::getAsm(), mlir::PyPrintAccumulator::getCallback(), mlir::python::PyMlirContext::getCapsule(), mlir::python::PyLocation::getCapsule(), mlir::python::PyModule::getCapsule(), mlir::python::PyAttribute::getCapsule(), getCapsule(), mlir::python::BaseContextObject::getContext(), mlir::python::PyThreadContextEntry::getDefaultContext(), mlir::python::PyThreadContextEntry::getDefaultInsertionPoint(), mlir::python::PyThreadContextEntry::getDefaultLocation(), mlir::python::PyMlirContext::getLiveCount(), mlir::python::PyMlirContext::getLiveModuleCount(), mlir::python::PyMlirContext::getLiveOperationCount(), mlir::python::PyOperationBase::getOperation(), mlir::python::PyOpView::getOperationObject(), mlir::python::PyValue::getParentOperation(), mlir::PyPrintAccumulator::getUserData(), mlir::python::PyInsertionPoint::insert(), mlir::PyPrintAccumulator::join(), kContextGetFileLocationDocstring, kContextParseTypeDocstring, kDumpDocstring, kModuleParseDocstring, kOperationCreateDocstring, kOperationGetAsmDocstring, kOperationPrintDocstring, kOperationStrDunderDocstring, kValueDunderStrDocstring, MlirStringRef::length, MLIR_PYTHON_CAPI_FACTORY_ATTR, MLIR_PYTHON_CAPI_PTR_ATTR, mlirArrayAttrGet(), mlirArrayAttrGetElement(), mlirArrayAttrGetNumElements(), mlirAttributeDump(), mlirAttributeGetContext(), mlirAttributeGetType(), mlirAttributeIsAArray(), mlirAttributeIsABool(), mlirAttributeIsADenseElements(), mlirAttributeIsADenseFPElements(), mlirAttributeIsADenseIntElements(), mlirAttributeIsADictionary(), mlirAttributeIsAFloat(), mlirAttributeIsAInteger(), mlirAttributeIsAString(), mlirAttributeIsAType(), mlirAttributeIsAUnit(), mlirAttributeIsNull(), mlirAttributeParseGet(), mlirAttributePrint(), mlirBF16TypeGet(), mlirBlockArgumentGetArgNumber(), mlirBlockArgumentGetOwner(), mlirBlockArgumentSetType(), mlirBlockGetArgument(), mlirBlockGetFirstOperation(), mlirBlockGetNumArguments(), mlirBlockPrint(), mlirBoolAttrGet(), mlirBoolAttrGetValue(), mlirComplexTypeGet(), mlirComplexTypeGetElementType(), mlirContextGetAllowUnregisteredDialects(), mlirContextGetOrLoadDialect(), mlirContextSetAllowUnregisteredDialects(), mlirDenseElementsAttrDoubleGet(), mlirDenseElementsAttrFloatGet(), mlirDenseElementsAttrGetBoolValue(), mlirDenseElementsAttrGetDoubleValue(), mlirDenseElementsAttrGetFloatValue(), mlirDenseElementsAttrGetInt32Value(), mlirDenseElementsAttrGetInt64Value(), mlirDenseElementsAttrGetRawData(), mlirDenseElementsAttrGetUInt32Value(), mlirDenseElementsAttrGetUInt64Value(), mlirDenseElementsAttrInt32Get(), mlirDenseElementsAttrInt64Get(), mlirDenseElementsAttrIsSplat(), mlirDenseElementsAttrSplatGet(), mlirDenseElementsAttrUInt32Get(), mlirDenseElementsAttrUInt64Get(), mlirDialectGetNamespace(), mlirDialectIsNull(), mlirDictionaryAttrGet(), mlirDictionaryAttrGetElement(), mlirDictionaryAttrGetElementByName(), mlirDictionaryAttrGetNumElements(), mlirElementsAttrGetNumElements(), mlirF16TypeGet(), mlirF32TypeGet(), mlirF64TypeGet(), mlirFloatAttrDoubleGet(), mlirFloatAttrDoubleGetChecked(), mlirFloatAttrGetValueDouble(), mlirFunctionTypeGet(), mlirFunctionTypeGetInput(), mlirFunctionTypeGetNumInputs(), mlirFunctionTypeGetNumResults(), mlirFunctionTypeGetResult(), mlirIdentifierGet(), mlirIdentifierStr(), mlirIndexTypeGet(), mlirIntegerAttrGet(), mlirIntegerAttrGetValueInt(), mlirIntegerTypeGet(), mlirIntegerTypeGetWidth(), mlirIntegerTypeIsSigned(), mlirIntegerTypeIsSignless(), mlirIntegerTypeIsUnsigned(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), mlirLocationEqual(), mlirLocationFileLineColGet(), mlirLocationPrint(), mlirLocationUnknownGet(), mlirMemRefTypeContiguousGetChecked(), mlirMemRefTypeGetMemorySpace(), mlirMemRefTypeGetNumAffineMaps(), mlirModuleCreateEmpty(), mlirModuleCreateParse(), mlirModuleGetBody(), mlirModuleGetOperation(), mlirModuleIsNull(), mlirNamedAttributeGet(), mlirNoneTypeGet(), mlirOperationDump(), mlirOperationEqual(), mlirOperationGetAttribute(), mlirOperationGetAttributeByName(), mlirOperationGetName(), mlirOperationGetNumAttributes(), mlirOperationGetNumOperands(), mlirOperationGetNumResults(), mlirOperationGetOperand(), mlirOperationGetResult(), mlirOperationPrint(), mlirOperationRemoveAttributeByName(), mlirOperationSetAttributeByName(), mlirOpResultGetOwner(), mlirOpResultGetResultNumber(), mlirPythonCapsuleToType(), mlirRankedTensorTypeGet(), mlirRankedTensorTypeGetChecked(), mlirRegionGetFirstBlock(), mlirShapedTypeGetDimSize(), mlirShapedTypeGetElementType(), mlirShapedTypeGetRank(), mlirShapedTypeHasRank(), mlirShapedTypeHasStaticShape(), mlirShapedTypeIsDynamicDim(), mlirShapedTypeIsDynamicSize(), mlirShapedTypeIsDynamicStrideOrOffset(), mlirStringAttrGet(), mlirStringAttrGetValue(), mlirStringAttrTypedGet(), mlirTupleTypeGet(), mlirTupleTypeGetNumTypes(), mlirTupleTypeGetType(), mlirTypeAttrGet(), mlirTypeAttrGetValue(), mlirTypeDump(), mlirTypeEqual(), mlirTypeGetContext(), mlirTypeIsABF16(), mlirTypeIsAComplex(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), mlirTypeIsAFunction(), mlirTypeIsAIndex(), mlirTypeIsAInteger(), mlirTypeIsAIntegerOrFloat(), mlirTypeIsANone(), mlirTypeIsARankedTensor(), mlirTypeIsAShaped(), mlirTypeIsATuple(), mlirTypeIsAUnrankedMemRef(), mlirTypeIsAUnrankedTensor(), mlirTypeIsAVector(), mlirTypeIsNull(), mlirTypeParseGet(), mlirTypePrint(), mlirUnitAttrGet(), mlirUnrankedMemrefGetMemorySpace(), mlirUnrankedMemRefTypeGetChecked(), mlirUnrankedTensorTypeGetChecked(), mlirValueDump(), mlirValueGetType(), mlirValueIsABlockArgument(), mlirValueIsAOpResult(), mlirValuePrint(), mlirVectorTypeGetChecked(), MlirNamedAttribute::name, mlir::python::PyNamedAttribute::namedAttr, mlir::PyPrintAccumulator::parts, mlir::python::populateIRSubmodule(), mlir::python::PyOperationBase::print(), mlir::python::PyNamedAttribute::PyNamedAttribute(), mlir::python::PyObjectRef< T >::releaseObject(), mlir::python::SetPyError(), and toMlirStringRef().
get()
MlirType mlir::python::PyType::get () const inline
Definition at line 634 of file IRModules.h.
Referenced by createFromCapsule().
getCapsule()
py::object PyType::getCapsule ()
Gets a capsule wrapping the void* within the MlirContext.
Definition at line 1153 of file IRModules.cpp.
References mlirPythonTypeToCapsule().
Referenced by createFromCapsule().
operator MlirType()
mlir::python::PyType::operator MlirType () const inline
Definition at line 633 of file IRModules.h.
operator==()
bool PyType::operator== (const PyType & other)
Definition at line 1149 of file IRModules.cpp.
References mlirTypeEqual().
The documentation for this class was generated from the following files:
lib/Bindings/Python/IRModules.h
lib/Bindings/Python/IRModules.cpp