MLIR: mlir::LLVM::LLVMArrayType Class Reference
mlir::LLVM::LLVMArrayType Class Reference
LLVM dialect array type.
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Public Member Functions
LLVMType getElementType ()
Returns the element type of the array.
unsigned getNumElements ()
Returns the number of elements in the array type.
Static Public Member Functions
static bool isValidElementType (LLVMType type)
Checks if the given type can be used inside an array type.
static LLVMArrayType get (LLVMType elementType, unsigned numElements)
Gets or creates an instance of LLVM dialect array type containing numElements of elementType, in the same context as elementType.
static LLVMArrayType getChecked (Location loc, LLVMType elementType, unsigned numElements)
static LogicalResult verifyConstructionInvariants (Location loc, LLVMType elementType, unsigned numElements)
Verifies that the type about to be constructed is well-formed.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
LLVM dialect array type.
It is an aggregate type representing consecutive elements in memory, parameterized by the number of elements and the element type.
Definition at line 264 of file LLVMTypes.h.
Member Function Documentation
get()
LLVMArrayType LLVMArrayType::get (LLVMType elementType, unsigned numElements) static
Gets or creates an instance of LLVM dialect array type containing numElements of elementType, in the same context as elementType.
Definition at line 266 of file LLVMTypes.cpp.
References mlir::Type::getContext().
Referenced by mlir::LLVM::LLVMType::getArrayTy(), and mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType().
getChecked()
LLVMArrayType LLVMArrayType::getChecked (Location loc, LLVMType elementType, unsigned numElements) static
Definition at line 271 of file LLVMTypes.cpp.
getElementType()
LLVMType LLVMArrayType::getElementType ()
Returns the element type of the array.
Definition at line 277 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
getNumElements()
unsigned LLVMArrayType::getNumElements ()
Returns the number of elements in the array type.
Definition at line 279 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::detail::TypeToLLVMIRTranslatorImpl::translateType().
isValidElementType()
bool LLVMArrayType::isValidElementType (LLVMType type) static
Checks if the given type can be used inside an array type.
Definition at line 261 of file LLVMTypes.cpp.
References mlir::Type::isa().
verifyConstructionInvariants()
LogicalResult LLVMArrayType::verifyConstructionInvariants (Location loc, LLVMType elementType, unsigned numElements) static
Verifies that the type about to be constructed is well-formed.
Definition at line 282 of file LLVMTypes.cpp.
References mlir::emitError(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMTypes.h
lib/Dialect/LLVMIR/IR/LLVMTypes.cpp