MLIR: mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType > Class Template Reference
mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType > Class Template Reference
#include "mlir/IR/OpDefinition.h"
Public Types
using ImplicitTerminatorOpT = TerminatorOpType
The type of the operation used as the implicit terminator type.
template<typename OpT , typename T = void>
using enable_if_single_region = typename std::enable_if_t< OpT::template hasTrait< OneRegion >(), T >
The following are a set of methods only enabled when the parent operation has a single region.
Public Member Functions
Block * getBody (unsigned idx=0)
Region & getBodyRegion (unsigned idx=0)
template<typename OpT = ConcreteType>
enable_if_single_region< OpT, Block::iterator > begin ()
template<typename OpT = ConcreteType>
enable_if_single_region< OpT, Block::iterator > end ()
template<typename OpT = ConcreteType>
enable_if_single_region< OpT, Operation & > front ()
template<typename OpT = ConcreteType>
enable_if_single_region< OpT > push_back (Operation *op)
Insert the operation into the back of the body, before the terminator.
template<typename OpT = ConcreteType>
enable_if_single_region< OpT > insert (Operation *insertPt, Operation *op)
Insert the operation at the given insertion point.
template<typename OpT = ConcreteType>
enable_if_single_region< OpT > insert (Block::iterator insertPt, Operation *op)
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
static void ensureTerminator (Region &region, Builder &builder, Location loc)
Ensure that the given region has the terminator required by this trait.
static void ensureTerminator (Region &region, OpBuilder &builder, Location loc)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, Impl >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename TerminatorOpType>
template<typename ConcreteType>
class mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >
Definition at line 802 of file OpDefinition.h.
Member Typedef Documentation
enable_if_single_region
template<typename TerminatorOpType > template<typename ConcreteType > template<typename OpT , typename T = void> using mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::enable_if_single_region = typename std::enable_if_t<OpT::template hasTrait<OneRegion>(), T>
The following are a set of methods only enabled when the parent operation has a single region.
Each of these methods take an additional template parameter that represents the concrete operation so that we can use SFINAE to disable the methods for non-single region operations.
Definition at line 884 of file OpDefinition.h.
ImplicitTerminatorOpT
template<typename TerminatorOpType > template<typename ConcreteType > using mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::ImplicitTerminatorOpT = TerminatorOpType
The type of the operation used as the implicit terminator type.
Definition at line 814 of file OpDefinition.h.
Member Function Documentation
begin()
template<typename TerminatorOpType > template<typename ConcreteType > template<typename OpT = ConcreteType> enable_if_single_region<OpT, Block::iterator> mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::begin () inline
Definition at line 887 of file OpDefinition.h.
end()
template<typename TerminatorOpType > template<typename ConcreteType > template<typename OpT = ConcreteType> enable_if_single_region<OpT, Block::iterator> mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::end () inline
Definition at line 891 of file OpDefinition.h.
ensureTerminator() [1/2]
template<typename TerminatorOpType > template<typename ConcreteType > static void mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::ensureTerminator (Region & region, Builder & builder, Location loc) inline static
Ensure that the given region has the terminator required by this trait.
If OpBuilder is provided, use it to build the terminator and notify the OpBuilder litsteners accordingly. If only a Builder is provided, locally construct an OpBuilder with no listeners; this should only be used if no OpBuilder is available at the call site, e.g., in the parser.
Definition at line 854 of file OpDefinition.h.
References mlir::impl::ensureRegionTerminator().
ensureTerminator() [2/2]
template<typename TerminatorOpType > template<typename ConcreteType > static void mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::ensureTerminator (Region & region, OpBuilder & builder, Location loc) inline static
Definition at line 859 of file OpDefinition.h.
References mlir::impl::ensureRegionTerminator().
front()
template<typename TerminatorOpType > template<typename ConcreteType > template<typename OpT = ConcreteType> enable_if_single_region<OpT, Operation &> mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::front () inline
Definition at line 895 of file OpDefinition.h.
getBody()
template<typename TerminatorOpType > template<typename ConcreteType > Block* mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::getBody (unsigned idx = 0) inline
Definition at line 865 of file OpDefinition.h.
References mlir::Region::empty(), and mlir::Region::front().
getBodyRegion()
template<typename TerminatorOpType > template<typename ConcreteType > Region& mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::getBodyRegion (unsigned idx = 0) inline
Definition at line 870 of file OpDefinition.h.
insert() [1/2]
template<typename TerminatorOpType > template<typename ConcreteType > template<typename OpT = ConcreteType> enable_if_single_region<OpT> mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::insert (Operation * insertPt, Operation * op) inline
Insert the operation at the given insertion point.
Note: The operation is never inserted after the terminator, even if the insertion point is end().
Definition at line 909 of file OpDefinition.h.
insert() [2/2]
template<typename TerminatorOpType > template<typename ConcreteType > template<typename OpT = ConcreteType> enable_if_single_region<OpT> mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::insert (Block::iterator insertPt, Operation * op) inline
Definition at line 913 of file OpDefinition.h.
push_back()
template<typename TerminatorOpType > template<typename ConcreteType > template<typename OpT = ConcreteType> enable_if_single_region<OpT> mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::push_back (Operation * op) inline
Insert the operation into the back of the body, before the terminator.
Definition at line 901 of file OpDefinition.h.
verifyTrait()
template<typename TerminatorOpType > template<typename ConcreteType > static LogicalResult mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 816 of file OpDefinition.h.
References mlir::Block::back(), mlir::Region::begin(), mlir::Operation::emitOpError(), mlir::Region::empty(), mlir::Block::empty(), mlir::Region::end(), mlir::Region::front(), mlir::Operation::getName(), mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), mlir::OperationName::getStringRef(), and mlir::success().
The documentation for this class was generated from the following file:
include/mlir/IR/OpDefinition.h