MLIR: mlir::BufferAliasAnalysis Class Reference
mlir::BufferAliasAnalysis Class Reference
A straight-forward alias analysis which ensures that all aliases of all values will be determined.
#include "mlir/Analysis/BufferAliasAnalysis.h"
Public Types
using ValueSetT = SmallPtrSet< Value, 16 >
using ValueMapT = llvm::DenseMap< Value, ValueSetT >
Public Member Functions
BufferAliasAnalysis (Operation *op)
Constructs a new alias analysis using the op provided.
ValueMapT::const_iterator find (Value value) const
Find all immediate aliases this value could potentially have.
ValueMapT::const_iterator begin () const
Returns the begin iterator to iterate over all aliases.
ValueMapT::const_iterator end () const
Returns the end iterator that can be used in combination with find.
ValueSetT resolve (Value value) const
Find all immediate and indirect aliases this value could potentially have.
void remove (const SmallPtrSetImpl< Value > &aliasValues)
Removes the given values from all alias sets.
Detailed Description
A straight-forward alias analysis which ensures that all aliases of all values will be determined.
This is a requirement for the BufferPlacement class since you need to determine safe positions to place alloc and deallocs.
Definition at line 21 of file BufferAliasAnalysis.h.
Member Typedef Documentation
ValueMapT
using mlir::BufferAliasAnalysis::ValueMapT = llvm::DenseMap<Value, ValueSetT>
Definition at line 24 of file BufferAliasAnalysis.h.
ValueSetT
using mlir::BufferAliasAnalysis::ValueSetT = SmallPtrSet<Value, 16>
Definition at line 23 of file BufferAliasAnalysis.h.
Constructor & Destructor Documentation
BufferAliasAnalysis()
BufferAliasAnalysis::BufferAliasAnalysis (Operation * op)
Constructs a new alias analysis using the op provided.
Definition at line 18 of file BufferAliasAnalysis.cpp.
Member Function Documentation
begin()
ValueMapT::const_iterator mlir::BufferAliasAnalysis::begin () const inline
Returns the begin iterator to iterate over all aliases.
Definition at line 36 of file BufferAliasAnalysis.h.
end()
ValueMapT::const_iterator mlir::BufferAliasAnalysis::end () const inline
Returns the end iterator that can be used in combination with find.
Definition at line 39 of file BufferAliasAnalysis.h.
References resolve().
find()
ValueMapT::const_iterator mlir::BufferAliasAnalysis::find (Value value) const inline
Find all immediate aliases this value could potentially have.
Definition at line 31 of file BufferAliasAnalysis.h.
remove()
void BufferAliasAnalysis::remove (const SmallPtrSetImpl< Value > & aliasValues)
Removes the given values from all alias sets.
Definition at line 42 of file BufferAliasAnalysis.cpp.
References mlir::Block::succ_begin(), mlir::Block::succ_end(), and mlir::Operation::walk().
resolve()
BufferAliasAnalysis::ValueSetT BufferAliasAnalysis::resolve (Value rootValue) const
Find all immediate and indirect aliases this value could potentially have.
Note that the resulting set will also contain the value provided as it is an alias of itself.
Definition at line 24 of file BufferAliasAnalysis.cpp.
Referenced by end(), and hasAllocationScope().
The documentation for this class was generated from the following files:
include/mlir/Analysis/BufferAliasAnalysis.h
lib/Analysis/BufferAliasAnalysis.cpp