MLIR: mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType > Class Template Reference
mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType > Class Template Reference
This class provides a verifier for structured ops that are known to operate on buffers or tensors.
#include "mlir/Dialect/Linalg/IR/LinalgTraits.h"
Static Public Member Functions
static LogicalResult verifyTrait (Operation *op)
Additional Inherited Members
Protected Member Functions inherited from mlir::OpTrait::TraitBase< ConcreteType, StructuredOpTraits >
Operation * getOperation ()
Return the ultimate Operation being worked on.
Detailed Description
template<typename ConcreteType>
class mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >
This class provides a verifier for structured ops that are known to operate on buffers or tensors.
This trait must be used in conjunction with an op definition or a trait that provides the methods getNumInputs and getNumOutputs. Use as a trait as follows:
class DotOp : public Op<DotOp, OpTrait::StructuredOpTraits> {
Definition at line 71 of file LinalgTraits.h.
Member Function Documentation
verifyTrait()
template<typename ConcreteType > static LogicalResult mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait (Operation * op) inline static
Definition at line 74 of file LinalgTraits.h.
References mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getNumResults(), mlir::success(), and mlir::OpTrait::impl::verifyAtLeastNOperands().
The documentation for this class was generated from the following file:
include/mlir/Dialect/Linalg/IR/LinalgTraits.h