MLIR: mlir::linalg::LinalgOpToLibraryCallRewrite Class Reference
mlir::linalg::LinalgOpToLibraryCallRewrite Class Reference
#include "mlir/Conversion/LinalgToStandard/LinalgToStandard.h"
Public Member Functions
LinalgOpToLibraryCallRewrite ()
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Definition at line 33 of file LinalgToStandard.h.
Constructor & Destructor Documentation
LinalgOpToLibraryCallRewrite()
mlir::linalg::LinalgOpToLibraryCallRewrite::LinalgOpToLibraryCallRewrite () inline
Definition at line 35 of file LinalgToStandard.h.
References matchAndRewrite().
Member Function Documentation
matchAndRewrite()
LogicalResult mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const override virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented from mlir::RewritePattern.
Definition at line 102 of file LinalgToStandard.cpp.
References createTypeCanonicalizedMemRefOperands(), mlir::failure(), getLibraryCallSymbolRef(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by LinalgOpToLibraryCallRewrite().
The documentation for this class was generated from the following files:
include/mlir/Conversion/LinalgToStandard/LinalgToStandard.h
lib/Conversion/LinalgToStandard/LinalgToStandard.cpp