MLIR: mlir::VectorType Class Reference
mlir::VectorType Class Reference
Vector types represent multi-dimensional SIMD vectors, and have a fixed known constant shape with one or more dimension.
#include "mlir/IR/BuiltinTypes.h"
Public Member Functions
ArrayRef< int64_t > getShape () const
VectorType scaleElementBitwidth (unsigned scale)
Get or create a new VectorType with the same shape as this and an element type of bitwidth scaled by scale.
Static Public Member Functions
static VectorType get (ArrayRef< int64_t > shape, Type elementType)
Get or create a new VectorType of the provided shape and element type.
static VectorType getChecked (ArrayRef< int64_t > shape, Type elementType, Location location)
Get or create a new VectorType of the provided shape and element type declared at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Location loc, ArrayRef< int64_t > shape, Type elementType)
Verify the construction of a vector type.
static bool isValidElementType (Type t)
Returns true of the given type can be used as an element of a vector type.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Additional Inherited Members
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Vector types represent multi-dimensional SIMD vectors, and have a fixed known constant shape with one or more dimension.
Definition at line 325 of file BuiltinTypes.h.
Member Function Documentation
get()
VectorType VectorType::get (ArrayRef< int64_t > shape, Type elementType) static
Get or create a new VectorType of the provided shape and element type.
Assumes the arguments define a well-formed VectorType.
Definition at line 312 of file BuiltinTypes.cpp.
References mlir::Type::getContext().
Referenced by adjustType(), applyMapToValues(), broadcast(), buildLogicalBinaryOp(), mlir::quant::QuantizedType::castFromExpressedType(), mlir::quant::QuantizedType::castFromStorageType(), mlir::quant::QuantizedType::castToExpressedType(), mlir::quant::QuantizedType::castToStorageType(), mlir::quant::ExpressedToQuantizedConverter::convert(), convertStructType(), convertVectorType(), mlir::VulkanLayoutUtils::decorateType(), diag(), extractShape(), extractVectorTypeFromScalarView(), generateExtractSlicesOpResultType(), getAtomicOpScope(), mlir::Builder::getBoolVectorAttr(), mlir::OpTrait::util::getBroadcastedType(), mlir::spirv::getEntryPointABIAttr(), getI1SameShape(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getI64VectorAttr(), getOrCreateUnrolledVectorSlice(), getOrInsertBuiltinVariable(), getUnaryOpResultType(), getVectorType(), inferExtractOpResultType(), inferStridedSliceOpResultType(), isFnEntryBlock(), isValidExtractOrInsertSlicesType(), mappingHelper(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::linalg::ConvOpVectorization< ConvOp, N >::matchAndRewrite(), mlirVectorTypeGet(), parseContractionOp(), parseExecuteOp(), parseOuterProductOp(), parseShuffleOp(), mlir::detail::Parser::parseVectorType(), populateFromInt64AttrArray(), reducedVectorTypeBack(), reducedVectorTypeFront(), replaceTransferOpWithMubuf(), scaleElementBitwidth(), mlir::VectorTransferRewriter< TransferOpTy >::tmpMemRefType(), transferWriteVector(), unrollSingleResultStructuredOp(), mlir::vector::unrollSingleResultVectorOp(), vectorizeOneOperation(), vectorizeRootOrTerminal(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), and verifyOutputShape().
getChecked()
VectorType VectorType::getChecked (ArrayRef< int64_t > shape, Type elementType, Location location) static
Get or create a new VectorType of the provided shape and element type declared at the given, potentially unknown, location.
If the VectorType defined by the arguments would be ill-formed, emit errors and return nullptr-wrapping type.
Definition at line 316 of file BuiltinTypes.cpp.
Referenced by mlirVectorTypeGetChecked().
getShape()
ArrayRef< int64_t > VectorType::getShape () const
Definition at line 336 of file BuiltinTypes.cpp.
Referenced by mlir::quant::QuantizedType::castFromStorageType(), convertVectorType(), extractShape(), foldExtractFromShapeCast(), foldTransferMaskAttribute(), generateExtractSlicesOpResultType(), generateTransferOpSlices(), inferExtractOpResultType(), inferStridedSliceOpResultType(), initUnrolledVectorState(), isValidExtractOrInsertSlicesType(), mlir::ContractionOpToDotLowering::matchAndRewrite(), parseContractionOp(), printDenseElementsAttrImpl(), reducedVectorTypeBack(), reducedVectorTypeFront(), mlir::shapeRatio(), mlir::vector::unrollSingleResultVectorOp(), mlir::edsc::VectorBoundsCapture::VectorBoundsCapture(), verify(), verifyOutputShape(), verifyTransferOp(), and verifyVectorShapeCast().
isValidElementType()
static bool mlir::VectorType::isValidElementType (Type t) inline static
Returns true of the given type can be used as an element of a vector type.
In particular, vectors can consist of integer or float primitives.
Definition at line 348 of file BuiltinTypes.h.
References getShape(), and mlir::Type::isa().
Referenced by mlir::detail::Parser::parseVectorType(), vectorizeConstant(), vectorizeRootOrTerminal(), and verify().
scaleElementBitwidth()
VectorType VectorType::scaleElementBitwidth (unsigned scale)
Get or create a new VectorType with the same shape as this and an element type of bitwidth scaled by scale.
Return null if the scaled element type cannot be represented.
Definition at line 338 of file BuiltinTypes.cpp.
References mlir::Type::dyn_cast(), get(), getElementType(), and getShape().
verifyConstructionInvariants()
LogicalResult VectorType::verifyConstructionInvariants (Location loc, ArrayRef< int64_t > shape, Type elementType) static
Verify the construction of a vector type.
Definition at line 321 of file BuiltinTypes.cpp.
References mlir::emitError(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinTypes.h
lib/IR/BuiltinTypes.cpp