MLIR: mlir::ReductionNode Class Reference
mlir::ReductionNode Class Reference
This class defines the ReductionNode which is used to wrap the module of a generated variant and keep track of the necessary metadata for the reduction pass.
#include "mlir/Reducer/ReductionNode.h"
Public Member Functions
ReductionNode (ModuleOp module, ReductionNode *parent)
ReductionNode (ModuleOp module, ReductionNode *parent, std::vector< bool > transformSpace)
void measureAndTest (const Tester &test)
Calculates and initializes the size and interesting values of the node.
ModuleOp getModule () const
Returns the module.
bool isEvaluated () const
Returns true if the size and interestingness have been calculated.
int getSize () const
Returns the size in bytes of the module.
bool isInteresting () const
Returns true if the module exhibits the interesting behavior.
ReductionNode * getVariant (unsigned long index) const
Returns the pointer to a child variant by index.
int variantsSize () const
Returns the number of child variants.
bool variantsEmpty () const
Returns true if the vector containing the child variants is empty.
void organizeVariants (const Tester &test)
Sort the child variants and remove the uninteresting ones.
int transformSpaceSize ()
Returns the number of child variants.
const std::vector< bool > getTransformSpace ()
Returns a vector indicating the transformed indices as true.
Detailed Description
This class defines the ReductionNode which is used to wrap the module of a generated variant and keep track of the necessary metadata for the reduction pass.
The nodes are linked together in a reduction tree structure which defines the relationship between all the different generated variants.
Definition at line 31 of file ReductionNode.h.
Constructor & Destructor Documentation
ReductionNode() [1/2]
mlir::ReductionNode::ReductionNode (ModuleOp module, ReductionNode * parent)
ReductionNode() [2/2]
mlir::ReductionNode::ReductionNode (ModuleOp module, ReductionNode * parent, std::vector< bool > transformSpace)
Member Function Documentation
getModule()
ModuleOp mlir::ReductionNode::getModule () const inline
Returns the module.
Definition at line 42 of file ReductionNode.h.
References getSize(), getTransformSpace(), getVariant(), isEvaluated(), isInteresting(), organizeVariants(), transformSpaceSize(), variantsEmpty(), and variantsSize().
Referenced by mlir::ReductionTreePass< Reducer, mode >::runOnOperation().
getSize()
int mlir::ReductionNode::getSize () const
Returns the size in bytes of the module.
Referenced by getModule().
getTransformSpace()
const std::vector<bool> mlir::ReductionNode::getTransformSpace ()
Returns a vector indicating the transformed indices as true.
Referenced by getModule().
getVariant()
ReductionNode* mlir::ReductionNode::getVariant (unsigned long index) const
Returns the pointer to a child variant by index.
Referenced by getModule(), and mlir::ReductionTreePass< Reducer, mode >::runOnOperation().
isEvaluated()
bool mlir::ReductionNode::isEvaluated () const
Returns true if the size and interestingness have been calculated.
Referenced by getModule().
isInteresting()
bool mlir::ReductionNode::isInteresting () const
Returns true if the module exhibits the interesting behavior.
Referenced by getModule().
measureAndTest()
void mlir::ReductionNode::measureAndTest (const Tester & test)
Calculates and initializes the size and interesting values of the node.
organizeVariants()
void mlir::ReductionNode::organizeVariants (const Tester & test)
Sort the child variants and remove the uninteresting ones.
Referenced by getModule(), and mlir::ReductionTreePass< Reducer, mode >::runOnOperation().
transformSpaceSize()
int mlir::ReductionNode::transformSpaceSize ()
Returns the number of child variants.
Referenced by getModule(), and mlir::ReductionTreePass< Reducer, mode >::runOnOperation().
variantsEmpty()
bool mlir::ReductionNode::variantsEmpty () const
Returns true if the vector containing the child variants is empty.
Referenced by getModule(), and mlir::ReductionTreePass< Reducer, mode >::runOnOperation().
variantsSize()
int mlir::ReductionNode::variantsSize () const
Returns the number of child variants.
Referenced by getModule().
The documentation for this class was generated from the following file:
include/mlir/Reducer/ReductionNode.h