MLIR: mlir::LLVM::LLVMVectorType Class Reference
mlir::LLVM::LLVMVectorType Class Reference
LLVM dialect vector type, represents a sequence of elements that can be processed as one, typically in SIMD context.
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Public Member Functions
LLVMType getElementType ()
Returns the element type of the vector.
llvm::ElementCount getElementCount ()
Returns the number of elements in the vector.
Public Member Functions inherited from mlir::LLVM::LLVMType
LLVMDialect & getDialect ()
llvm::TypeSize getPrimitiveSizeInBits ()
Returns the size of a primitive type (including vectors) in bits, for example, the size of !llvm.i16 is 16 and the size of !llvm.vec<4 x i16> is 64.
bool isBFloatTy ()
Floating-point type utilities.
bool isHalfTy ()
bool isFloatTy ()
bool isDoubleTy ()
bool isFP128Ty ()
bool isX86_FP80Ty ()
bool isFloatingPointTy ()
LLVMType getArrayElementType ()
Array type utilities.
unsigned getArrayNumElements ()
bool isArrayTy ()
bool isIntegerTy ()
Integer type utilities.
bool isIntegerTy (unsigned bitwidth)
unsigned getIntegerBitWidth ()
LLVMType getVectorElementType ()
Vector type utilities.
unsigned getVectorNumElements ()
llvm::ElementCount getVectorElementCount ()
bool isVectorTy ()
LLVMType getFunctionParamType (unsigned argIdx)
Function type utilities.
unsigned getFunctionNumParams ()
LLVMType getFunctionResultType ()
bool isFunctionTy ()
bool isFunctionVarArg ()
LLVMType getPointerTo (unsigned addrSpace=0)
Pointer type utilities.
LLVMType getPointerElementTy ()
bool isPointerTy ()
LLVMType getStructElementType (unsigned i)
Struct type utilities.
unsigned getStructNumElements ()
bool isStructTy ()
bool isVoidTy ()
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os)
Print the current type.
void dump ()
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static bool classof (Type type)
Support type casting functionality.
static bool isValidElementType (LLVMType type)
Checks if the given type can be used in a vector type.
static LogicalResult verifyConstructionInvariants (Location loc, LLVMType elementType, unsigned numElements)
Verifies that the type about to be constructed is well-formed.
Static Public Member Functions inherited from mlir::LLVM::LLVMType
static LLVMType getFromOpaquePointer (const void *ptr)
static bool classof (Type type)
Support for isa/cast.
static LLVMType getDoubleTy (MLIRContext *context)
Utilities used to generate floating point types.
static LLVMType getFloatTy (MLIRContext *context)
static LLVMType getBFloatTy (MLIRContext *context)
static LLVMType getHalfTy (MLIRContext *context)
static LLVMType getFP128Ty (MLIRContext *context)
static LLVMType getX86_FP80Ty (MLIRContext *context)
static LLVMType getIntNTy (MLIRContext *context, unsigned numBits)
Utilities used to generate integer types.
static LLVMType getInt1Ty (MLIRContext *context)
static LLVMType getInt8Ty (MLIRContext *context)
static LLVMType getInt8PtrTy (MLIRContext *context)
static LLVMType getInt16Ty (MLIRContext *context)
static LLVMType getInt32Ty (MLIRContext *context)
static LLVMType getInt64Ty (MLIRContext *context)
static LLVMType getArrayTy (LLVMType elementType, uint64_t numElements)
Utilities used to generate other miscellaneous types.
static LLVMType getFunctionTy (LLVMType result, ArrayRef< LLVMType > params, bool isVarArg)
static LLVMType getFunctionTy (LLVMType result, bool isVarArg)
static LLVMType getStructTy (MLIRContext *context, ArrayRef< LLVMType > elements, bool isPacked=false)
static LLVMType getStructTy (MLIRContext *context, bool isPacked=false)
template<typename... Args>
static std::enable_if< llvm::are_base_of< LLVMType, Args... >::value, LLVMType >::type getStructTy (LLVMType elt1, Args... elts)
static LLVMType getVectorTy (LLVMType elementType, unsigned numElements)
static LLVMType getVoidTy (MLIRContext *context)
Void type utilities.
static LLVMType createStructTy (MLIRContext *context, ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked=false)
static LLVMType createStructTy (MLIRContext *context, Optional< StringRef > name)
static LLVMType createStructTy (ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked=false)
template<typename... Args>
static std::enable_if_t< llvm::are_base_of< LLVMType, Args... >::value, LLVMType > createStructTy (StringRef name, LLVMType elt1, Args... elts)
static LLVMType setStructTyBody (LLVMType structType, ArrayRef< LLVMType > elements, bool isPacked=false)
template<typename... Args>
static std::enable_if_t< llvm::are_base_of< LLVMType, Args... >::value, LLVMType > setStructTyBody (LLVMType structType, LLVMType elt1, Args... elts)
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
LLVM dialect vector type, represents a sequence of elements that can be processed as one, typically in SIMD context.
This is a base class for fixed and scalable vectors.
Definition at line 501 of file LLVMTypes.h.
Member Function Documentation
classof()
bool LLVMVectorType::classof (Type type) static
Support type casting functionality.
Definition at line 477 of file LLVMTypes.cpp.
References mlir::Type::isa().
getElementCount()
llvm::ElementCount LLVMVectorType::getElementCount ()
Returns the number of elements in the vector.
Definition at line 486 of file LLVMTypes.cpp.
Referenced by mlir::LLVM::LLVMType::getPrimitiveSizeInBits().
getElementType()
LLVMType LLVMVectorType::getElementType ()
Returns the element type of the vector.
Definition at line 481 of file LLVMTypes.cpp.
References mlir::Type::impl.
Referenced by mlir::LLVM::LLVMType::getPrimitiveSizeInBits().
isValidElementType()
bool LLVMVectorType::isValidElementType (LLVMType type) static
Checks if the given type can be used in a vector type.
Definition at line 471 of file LLVMTypes.cpp.
References mlir::Type::isa(), and mlir::LLVM::LLVMType::isFloatingPointTy().
verifyConstructionInvariants()
LogicalResult LLVMVectorType::verifyConstructionInvariants (Location loc, LLVMType elementType, unsigned numElements) static
Verifies that the type about to be constructed is well-formed.
Definition at line 495 of file LLVMTypes.cpp.
References mlir::emitError(), and mlir::success().
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMTypes.h
lib/Dialect/LLVMIR/IR/LLVMTypes.cpp