MLIR: mlir::LLVM::LLVMType Class Reference
mlir::LLVM::LLVMType Class Reference
Base class for LLVM dialect types.
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
Public Member Functions
LLVMDialect & getDialect ()
llvm::TypeSize getPrimitiveSizeInBits ()
Returns the size of a primitive type (including vectors) in bits, for example, the size of !llvm.i16 is 16 and the size of !llvm.vec<4 x i16> is 64.
bool isBFloatTy ()
Floating-point type utilities.
bool isHalfTy ()
bool isFloatTy ()
bool isDoubleTy ()
bool isFP128Ty ()
bool isX86_FP80Ty ()
bool isFloatingPointTy ()
LLVMType getArrayElementType ()
Array type utilities.
unsigned getArrayNumElements ()
bool isArrayTy ()
bool isIntegerTy ()
Integer type utilities.
bool isIntegerTy (unsigned bitwidth)
unsigned getIntegerBitWidth ()
LLVMType getVectorElementType ()
Vector type utilities.
unsigned getVectorNumElements ()
llvm::ElementCount getVectorElementCount ()
bool isVectorTy ()
LLVMType getFunctionParamType (unsigned argIdx)
Function type utilities.
unsigned getFunctionNumParams ()
LLVMType getFunctionResultType ()
bool isFunctionTy ()
bool isFunctionVarArg ()
LLVMType getPointerTo (unsigned addrSpace=0)
Pointer type utilities.
LLVMType getPointerElementTy ()
bool isPointerTy ()
LLVMType getStructElementType (unsigned i)
Struct type utilities.
unsigned getStructNumElements ()
bool isStructTy ()
bool isVoidTy ()
Public Member Functions inherited from mlir::Type
constexpr Type ()
Type (const ImplType *impl)
Type (const Type &other)=default
Type & operator= (const Type &other)=default
bool operator== (Type other) const
bool operator!= (Type other) const
operator bool () const
bool operator! () const
template<typename U >
bool isa () const
template<typename First , typename Second , typename... Rest>
bool isa () const
template<typename U >
U dyn_cast () const
template<typename U >
U dyn_cast_or_null () const
template<typename U >
U cast () const
TypeID getTypeID ()
Return a unique identifier for the concrete type.
MLIRContext * getContext () const
Return the MLIRContext in which this type was uniqued.
Dialect & getDialect () const
Get the dialect this type is registered to.
bool isIndex () const
bool isBF16 () const
bool isF16 () const
bool isF32 () const
bool isF64 () const
bool isInteger (unsigned width) const
Return true if this is an integer type with the specified width.
bool isSignlessInteger () const
Return true if this is a signless integer type (with the specified width).
bool isSignlessInteger (unsigned width) const
bool isSignedInteger () const
Return true if this is a signed integer type (with the specified width).
bool isSignedInteger (unsigned width) const
bool isUnsignedInteger () const
Return true if this is an unsigned integer type (with the specified width).
bool isUnsignedInteger (unsigned width) const
unsigned getIntOrFloatBitWidth () const
Return the bit width of an integer or a float type, assert failure on other types.
bool isSignlessIntOrIndex () const
Return true if this is a signless integer or index type.
bool isSignlessIntOrIndexOrFloat () const
Return true if this is a signless integer, index, or float type.
bool isSignlessIntOrFloat () const
Return true of this is a signless integer or a float type.
bool isIntOrIndex () const
Return true if this is an integer (of any signedness) or an index type.
bool isIntOrFloat () const
Return true if this is an integer (of any signedness) or a float type.
bool isIntOrIndexOrFloat () const
Return true if this is an integer (of any signedness), index, or float type.
void print (raw_ostream &os)
Print the current type.
void dump ()
const void * getAsOpaquePointer () const
Methods for supporting PointerLikeTypeTraits.
const AbstractType & getAbstractType ()
Return the abstract type descriptor for this type.
Static Public Member Functions
static LLVMType getFromOpaquePointer (const void *ptr)
static bool classof (Type type)
Support for isa/cast.
static LLVMType getDoubleTy (MLIRContext *context)
Utilities used to generate floating point types.
static LLVMType getFloatTy (MLIRContext *context)
static LLVMType getBFloatTy (MLIRContext *context)
static LLVMType getHalfTy (MLIRContext *context)
static LLVMType getFP128Ty (MLIRContext *context)
static LLVMType getX86_FP80Ty (MLIRContext *context)
static LLVMType getIntNTy (MLIRContext *context, unsigned numBits)
Utilities used to generate integer types.
static LLVMType getInt1Ty (MLIRContext *context)
static LLVMType getInt8Ty (MLIRContext *context)
static LLVMType getInt8PtrTy (MLIRContext *context)
static LLVMType getInt16Ty (MLIRContext *context)
static LLVMType getInt32Ty (MLIRContext *context)
static LLVMType getInt64Ty (MLIRContext *context)
static LLVMType getArrayTy (LLVMType elementType, uint64_t numElements)
Utilities used to generate other miscellaneous types.
static LLVMType getFunctionTy (LLVMType result, ArrayRef< LLVMType > params, bool isVarArg)
static LLVMType getFunctionTy (LLVMType result, bool isVarArg)
static LLVMType getStructTy (MLIRContext *context, ArrayRef< LLVMType > elements, bool isPacked=false)
static LLVMType getStructTy (MLIRContext *context, bool isPacked=false)
template<typename... Args>
static std::enable_if< llvm::are_base_of< LLVMType, Args... >::value, LLVMType >::type getStructTy (LLVMType elt1, Args... elts)
static LLVMType getVectorTy (LLVMType elementType, unsigned numElements)
static LLVMType getVoidTy (MLIRContext *context)
Void type utilities.
static LLVMType createStructTy (MLIRContext *context, ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked=false)
static LLVMType createStructTy (MLIRContext *context, Optional< StringRef > name)
static LLVMType createStructTy (ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked=false)
template<typename... Args>
static std::enable_if_t< llvm::are_base_of< LLVMType, Args... >::value, LLVMType > createStructTy (StringRef name, LLVMType elt1, Args... elts)
static LLVMType setStructTyBody (LLVMType structType, ArrayRef< LLVMType > elements, bool isPacked=false)
template<typename... Args>
static std::enable_if_t< llvm::are_base_of< LLVMType, Args... >::value, LLVMType > setStructTyBody (LLVMType structType, LLVMType elt1, Args... elts)
Static Public Member Functions inherited from mlir::Type
static bool classof (Type)
static Type getFromOpaquePointer (const void *pointer)
Additional Inherited Members
Public Types inherited from mlir::Type
template<typename ConcreteType , typename BaseType , typename StorageType , template< typename T > class... Traits>
using TypeBase = detail::StorageUserBase< ConcreteType, BaseType, StorageType, detail::TypeUniquer, Traits... >
Utility class for implementing types.
using ImplType = TypeStorage
Protected Attributes inherited from mlir::Type
ImplType * impl
Detailed Description
Base class for LLVM dialect types.
The LLVM dialect in MLIR fully reflects the LLVM IR type system, prodiving a separate MLIR type for each LLVM IR type. All types are represented as separate subclasses and are compatible with the isa/cast infrastructure. For convenience, the base class provides most of the APIs available on llvm::Type in addition to MLIR-compatible APIs.
The LLVM dialect type system is closed: parametric types can only refer to other LLVM dialect types. This is consistent with LLVM IR and enables a more concise pretty-printing format.
Similarly to other MLIR types, LLVM dialect types are owned by the MLIR context, have an immutable identifier (for most types except identified structs, the entire type is the identifier) and are thread-safe.
Definition at line 67 of file LLVMTypes.h.
Member Function Documentation
classof()
bool LLVMType::classof (Type type) static
Support for isa/cast.
Definition at line 31 of file LLVMTypes.cpp.
References mlir::Type::getDialect().
createStructTy() [1/4]
LLVMType LLVMType::createStructTy (MLIRContext * context, ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked = false) static
Definition at line 229 of file LLVMTypes.cpp.
References mlir::failed(), and mlir::LLVM::LLVMStructType::getIdentified().
Referenced by isAsyncWithOneDependency().
createStructTy() [2/4]
static LLVMType mlir::LLVM::LLVMType::createStructTy (MLIRContext * context, Optional< StringRef > name) inline static
Definition at line 195 of file LLVMTypes.h.
createStructTy() [3/4]
static LLVMType mlir::LLVM::LLVMType::createStructTy (ArrayRef< LLVMType > elements, Optional< StringRef > name, bool isPacked = false) inline static
Definition at line 200 of file LLVMTypes.h.
createStructTy() [4/4]
template<typename... Args> static std::enable_if_t<llvm::are_base_of<LLVMType, Args...>::value, LLVMType> mlir::LLVM::LLVMType::createStructTy (StringRef name, LLVMType elt1, Args... elts) inline static
Definition at line 212 of file LLVMTypes.h.
References mlir::Type::getContext().
getArrayElementType()
LLVMType LLVMType::getArrayElementType ()
Array type utilities.
Definition at line 86 of file LLVMTypes.cpp.
References getElementType().
Referenced by diag(), extractNDVectorTypeInfo(), and verify().
getArrayNumElements()
unsigned LLVMType::getArrayNumElements ()
Definition at line 93 of file LLVMTypes.cpp.
Referenced by diag(), and verify().
getArrayTy()
LLVMType LLVMType::getArrayTy (LLVMType elementType, uint64_t numElements) static
Utilities used to generate other miscellaneous types.
Definition at line 199 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMArrayType::get().
Referenced by convertArrayType(), convertRuntimeArrayType(), convertStructType(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), parseGlobalOp(), mlir::MemRefDescriptor::size(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getBFloatTy()
LLVMType LLVMType::getBFloatTy (MLIRContext * context) static
Definition at line 173 of file LLVMTypes.cpp.
Referenced by mlir::LLVMTypeConverter::getPointerBitwidth().
getDialect()
LLVMDialect & LLVMType::getDialect ()
Definition at line 35 of file LLVMTypes.cpp.
References mlir::Type::getDialect().
getDoubleTy()
LLVMType LLVMType::getDoubleTy (MLIRContext * context) static
Utilities used to generate floating point types.
Definition at line 165 of file LLVMTypes.cpp.
Referenced by mlir::LLVMTypeConverter::getPointerBitwidth(), and getTransferOpAdapter().
getFloatTy()
LLVMType LLVMType::getFloatTy (MLIRContext * context) static
Definition at line 169 of file LLVMTypes.cpp.
Referenced by mlir::LLVMTypeConverter::getPointerBitwidth(), getTransferOpAdapter(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), and verify().
getFP128Ty()
LLVMType LLVMType::getFP128Ty (MLIRContext * context) static
Definition at line 181 of file LLVMTypes.cpp.
getFromOpaquePointer()
static LLVMType mlir::LLVM::LLVMType::getFromOpaquePointer (const void * ptr) inline static
Definition at line 74 of file LLVMTypes.h.
Referenced by llvm::PointerLikeTypeTraits< mlir::LLVM::LLVMType >::getFromVoidPointer().
getFunctionNumParams()
unsigned LLVMType::getFunctionNumParams ()
Definition at line 122 of file LLVMTypes.cpp.
Referenced by parseShuffleVectorOp(), printLLVMFuncOp(), and verify().
getFunctionParamType()
LLVMType LLVMType::getFunctionParamType (unsigned argIdx)
Function type utilities.
Definition at line 118 of file LLVMTypes.cpp.
Referenced by getLLVMAtomicOrdering(), parseShuffleVectorOp(), printLLVMFuncOp(), and verify().
getFunctionResultType()
LLVMType LLVMType::getFunctionResultType ()
Definition at line 126 of file LLVMTypes.cpp.
Referenced by printLLVMFuncOp(), and verify().
getFunctionTy() [1/2]
LLVMType LLVMType::getFunctionTy (LLVMType result, ArrayRef< LLVMType > params, bool isVarArg) static
Definition at line 203 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMFunctionType::get().
Referenced by addLLVMFuncDecl(), addResumeFunction(), buildLLVMFunctionType(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), mlir::LLVM::ModuleTranslation::convertOperation(), encodeKernelName(), getTransferOpAdapter(), parseCallOp(), parseInvokeOp(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getFunctionTy() [2/2]
static LLVMType mlir::LLVM::LLVMType::getFunctionTy (LLVMType result, bool isVarArg) inline static
Definition at line 168 of file LLVMTypes.h.
getHalfTy()
LLVMType LLVMType::getHalfTy (MLIRContext * context) static
Definition at line 177 of file LLVMTypes.cpp.
Referenced by mlir::LLVMTypeConverter::getPointerBitwidth(), and verify().
getInt16Ty()
static LLVMType mlir::LLVM::LLVMType::getInt16Ty (MLIRContext * context) inline static
Definition at line 154 of file LLVMTypes.h.
getInt1Ty()
static LLVMType mlir::LLVM::LLVMType::getInt1Ty (MLIRContext * context) inline static
Definition at line 145 of file LLVMTypes.h.
Referenced by addSuspensionPoint(), copy(), matchSimpleAtomicOp(), parseAtomicCmpXchgOp(), parseCmpOp(), parseNVVMVoteBallotOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), setupCoroMachinery(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getInt32Ty()
static LLVMType mlir::LLVM::LLVMType::getInt32Ty (MLIRContext * context) inline static
Definition at line 157 of file LLVMTypes.h.
Referenced by convertStructType(), createI32ConstantOf(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), and setupCoroMachinery().
getInt64Ty()
static LLVMType mlir::LLVM::LLVMType::getInt64Ty (MLIRContext * context) inline static
Definition at line 160 of file LLVMTypes.h.
Referenced by getTransferOpAdapter(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::LLVMTypeConverter::promoteOneMemRefDescriptor(), and setupCoroMachinery().
getInt8PtrTy()
static LLVMType mlir::LLVM::LLVMType::getInt8PtrTy (MLIRContext * context) inline static
Definition at line 151 of file LLVMTypes.h.
References getPointerTo().
Referenced by addResumeFunction(), mlir::ConvertToLLVMPattern::getVoidPtrType(), outlineExecuteOp(), mlir::populateGpuToLLVMConversionPatterns(), setupCoroMachinery(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getInt8Ty()
static LLVMType mlir::LLVM::LLVMType::getInt8Ty (MLIRContext * context) inline static
Definition at line 148 of file LLVMTypes.h.
Referenced by addSuspensionPoint(), and parseGlobalOp().
getIntegerBitWidth()
unsigned LLVMType::getIntegerBitWidth ()
Definition at line 82 of file LLVMTypes.cpp.
References getBitWidth().
Referenced by diag(), getLLVMTypeBitWidth(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getIntNTy()
LLVMType LLVMType::getIntNTy (MLIRContext * context, unsigned numBits) static
Utilities used to generate integer types.
Definition at line 192 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMIntegerType::get().
Referenced by mlir::LLVMTypeConverter::getIndexType(), mlir::ConvertToLLVMPattern::getIntPtrType(), mlir::LLVMTypeConverter::getPointerBitwidth(), and mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite().
getPointerElementTy()
LLVMType LLVMType::getPointerElementTy ()
Definition at line 143 of file LLVMTypes.cpp.
References getElementType().
Referenced by mlir::UnrankedMemRefDescriptor::sizeBasePtr(), and verify().
getPointerTo()
LLVMType LLVMType::getPointerTo (unsigned addrSpace = 0)
Pointer type utilities.
Definition at line 139 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMPointerType::get().
Referenced by mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), mlir::ConvertToLLVMPattern::getElementPtrType(), getInt8PtrTy(), mlir::UnrankedMemRefDescriptor::offset(), parseAtomicCmpXchgOp(), parseAtomicRMWOp(), mlir::UnrankedMemRefDescriptor::setOffset(), mlir::UnrankedMemRefDescriptor::setSize(), mlir::UnrankedMemRefDescriptor::setStride(), mlir::MemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::sizeBasePtr(), mlir::UnrankedMemRefDescriptor::stride(), mlir::UnrankedMemRefDescriptor::strideBasePtr(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getPrimitiveSizeInBits()
llvm::TypeSize LLVMType::getPrimitiveSizeInBits ()
Returns the size of a primitive type (including vectors) in bits, for example, the size of !llvm.i16 is 16 and the size of !llvm.vec<4 x i16> is 64.
Returns 0 for non-primitive (aggregates such as struct) or types that don't have a size (such as void).
Definition at line 42 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMIntegerType::getBitWidth(), mlir::LLVM::LLVMVectorType::getElementCount(), mlir::LLVM::LLVMVectorType::getElementType(), getPrimitiveSizeInBits(), and mlir::Type::isa().
Referenced by getPrimitiveSizeInBits().
getStructElementType()
LLVMType LLVMType::getStructElementType (unsigned i)
Struct type utilities.
Definition at line 152 of file LLVMTypes.cpp.
Referenced by parseNVVMShflSyncBflyOp().
getStructNumElements()
unsigned LLVMType::getStructNumElements ()
Definition at line 156 of file LLVMTypes.cpp.
getStructTy() [1/3]
LLVMType LLVMType::getStructTy (MLIRContext * context, ArrayRef< LLVMType > elements, bool isPacked = false) static
Definition at line 208 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMStructType::getLiteral().
Referenced by convertStructType(), convertStructTypePacked(), convertStructTypeWithOffset(), matchSimpleAtomicOp(), mlir::LLVMTypeConverter::packFunctionResults(), parseAtomicCmpXchgOp(), mlir::UnrankedMemRefDescriptor::sizeBasePtr(), and verify().
getStructTy() [2/3]
static LLVMType mlir::LLVM::LLVMType::getStructTy (MLIRContext * context, bool isPacked = false) inline static
Definition at line 173 of file LLVMTypes.h.
getStructTy() [3/3]
template<typename... Args> static std::enable_if<llvm::are_base_of<LLVMType, Args...>::value, LLVMType>::type mlir::LLVM::LLVMType::getStructTy (LLVMType elt1, Args... elts) inline static
Definition at line 179 of file LLVMTypes.h.
References mlir::Type::getContext().
getVectorElementCount()
llvm::ElementCount LLVMType::getVectorElementCount ()
Definition at line 109 of file LLVMTypes.cpp.
Referenced by diag().
getVectorElementType()
LLVMType LLVMType::getVectorElementType ()
Vector type utilities.
Definition at line 102 of file LLVMTypes.cpp.
References getElementType().
Referenced by diag(), getLLVMTypeBitWidth(), and parseCallOp().
getVectorNumElements()
unsigned LLVMType::getVectorNumElements ()
Definition at line 106 of file LLVMTypes.cpp.
Referenced by replaceTransferOpWithMubuf().
getVectorTy()
LLVMType LLVMType::getVectorTy (LLVMType elementType, unsigned numElements) static
Definition at line 213 of file LLVMTypes.cpp.
References mlir::LLVM::LLVMFixedVectorType::get().
Referenced by getIndexedPtrs(), parseCmpOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseShuffleVectorOp(), replaceTransferOpWithMubuf(), and verify().
getVoidTy()
LLVMType LLVMType::getVoidTy (MLIRContext * context) static
Void type utilities.
Definition at line 220 of file LLVMTypes.cpp.
Referenced by addResumeFunction(), buildLLVMFunctionType(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVMTypeConverter::convertFunctionTypeCWrapper(), mlir::LLVM::ModuleTranslation::convertOperation(), encodeKernelName(), getTransferOpAdapter(), mlir::ConvertToLLVMPattern::getVoidType(), parseCallOp(), parseInvokeOp(), and mlir::LLVM::detail::vectorOneToOneRewrite().
getX86_FP80Ty()
LLVMType LLVMType::getX86_FP80Ty (MLIRContext * context) static
Definition at line 185 of file LLVMTypes.cpp.
isArrayTy()
bool LLVMType::isArrayTy ()
Definition at line 97 of file LLVMTypes.cpp.
Referenced by diag(), and verify().
isBFloatTy()
bool mlir::LLVM::LLVMType::isBFloatTy () inline
Floating-point type utilities.
Definition at line 90 of file LLVMTypes.h.
Referenced by verify().
isDoubleTy()
bool mlir::LLVM::LLVMType::isDoubleTy () inline
Definition at line 93 of file LLVMTypes.h.
Referenced by diag(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), and verify().
isFloatingPointTy()
bool mlir::LLVM::LLVMType::isFloatingPointTy () inline
Definition at line 96 of file LLVMTypes.h.
Referenced by mlir::LLVM::LLVMVectorType::isValidElementType(), and verify().
isFloatTy()
bool mlir::LLVM::LLVMType::isFloatTy () inline
Definition at line 92 of file LLVMTypes.h.
Referenced by diag(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), and verify().
isFP128Ty()
bool mlir::LLVM::LLVMType::isFP128Ty () inline
Definition at line 94 of file LLVMTypes.h.
isFunctionTy()
bool LLVMType::isFunctionTy ()
Definition at line 130 of file LLVMTypes.cpp.
Referenced by verify().
isFunctionVarArg()
bool LLVMType::isFunctionVarArg ()
Definition at line 132 of file LLVMTypes.cpp.
Referenced by verify().
isHalfTy()
bool mlir::LLVM::LLVMType::isHalfTy () inline
Definition at line 91 of file LLVMTypes.h.
Referenced by mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), and verify().
isIntegerTy() [1/2]
bool mlir::LLVM::LLVMType::isIntegerTy () inline
Integer type utilities.
Definition at line 108 of file LLVMTypes.h.
Referenced by diag(), and verify().
isIntegerTy() [2/2]
bool LLVMType::isIntegerTy (unsigned bitwidth)
Definition at line 77 of file LLVMTypes.cpp.
isPointerTy()
bool LLVMType::isPointerTy ()
Definition at line 147 of file LLVMTypes.cpp.
Referenced by verify().
isStructTy()
bool LLVMType::isStructTy ()
Definition at line 160 of file LLVMTypes.cpp.
isVectorTy()
bool LLVMType::isVectorTy ()
Definition at line 113 of file LLVMTypes.cpp.
Referenced by diag(), and getLLVMTypeBitWidth().
isVoidTy()
bool LLVMType::isVoidTy ()
Definition at line 224 of file LLVMTypes.cpp.
Referenced by printLLVMFuncOp().
isX86_FP80Ty()
bool mlir::LLVM::LLVMType::isX86_FP80Ty () inline
Definition at line 95 of file LLVMTypes.h.
setStructTyBody() [1/2]
LLVMType LLVMType::setStructTyBody (LLVMType structType, ArrayRef< LLVMType > elements, bool isPacked = false) static
Definition at line 249 of file LLVMTypes.cpp.
References mlir::Type::cast(), and mlir::succeeded().
setStructTyBody() [2/2]
template<typename... Args> static std::enable_if_t<llvm::are_base_of<LLVMType, Args...>::value, LLVMType> mlir::LLVM::LLVMType::setStructTyBody (LLVMType structType, LLVMType elt1, Args... elts) inline static
Definition at line 225 of file LLVMTypes.h.
The documentation for this class was generated from the following files:
include/mlir/Dialect/LLVMIR/LLVMTypes.h
lib/Dialect/LLVMIR/IR/LLVMTypes.cpp