MLIR: mlir::IntegerType Class Reference
mlir::IntegerType Class Reference
Integer types can have arbitrary bitwidth up to a large fixed limit.
#include "mlir/IR/BuiltinTypes.h"
Public Types
enum SignednessSemantics : uint32_t { Signless, Signed, Unsigned }
Signedness semantics.
Public Types inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
using Base = StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits... >
Utility declarations for the concrete attribute class.
using ImplType = StorageT
Public Member Functions
unsigned getWidth () const
Return the bitwidth of this integer type.
SignednessSemantics getSignedness () const
Return the signedness semantics of this integer type.
bool isSignless () const
Return true if this is a signless integer type.
bool isSigned () const
Return true if this is a signed integer type.
bool isUnsigned () const
Return true if this is an unsigned integer type.
IntegerType scaleElementBitwidth (unsigned scale)
Get or create a new IntegerType with the same signedness as this and a bitwidth scaled by scale.
Static Public Member Functions
static IntegerType get (unsigned width, MLIRContext *context)
Get or create a new IntegerType of the given width within the context.
static IntegerType get (unsigned width, SignednessSemantics signedness, MLIRContext *context)
Get or create a new IntegerType of the given width within the context.
static IntegerType getChecked (unsigned width, Location location)
Get or create a new IntegerType of the given width within the context, defined at the given, potentially unknown, location.
static IntegerType getChecked (unsigned width, SignednessSemantics signedness, Location location)
Get or create a new IntegerType of the given width within the context, defined at the given, potentially unknown, location.
static LogicalResult verifyConstructionInvariants (Location loc, unsigned width, SignednessSemantics signedness)
Verify the construction of an integer type.
Static Public Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
static TypeID getTypeID ()
Return a unique identifier for the concrete type.
template<typename T >
static bool classof (T val)
Provide an implementation of 'classof' that compares the type id of the provided value with that of the concrete type.
static detail::InterfaceMap getInterfaceMap ()
Returns an interface map for the interfaces registered to this storage user.
template<typename... Args>
static ConcreteT get (MLIRContext *ctx, Args... args)
Get or create a new ConcreteT instance within the ctx.
template<typename LocationT , typename... Args>
static ConcreteT getChecked (LocationT loc, Args... args)
Get or create a new ConcreteT instance within the ctx, defined at the given, potentially unknown, location.
static ConcreteT getFromOpaquePointer (const void *ptr)
Get an instance of the concrete type from a void pointer.
Static Public Attributes
static constexpr unsigned kMaxWidth = 4096
Integer representation maximal bitwidth.
Additional Inherited Members
Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
LogicalResult mutate (Args &&...args)
Mutate the current storage instance.
ImplType * getImpl () const
Utility for easy access to the storage instance.
Static Protected Member Functions inherited from mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >
template<typename... Args>
static LogicalResult verifyConstructionInvariants (Args... args)
Default implementation that just returns success.
Detailed Description
Integer types can have arbitrary bitwidth up to a large fixed limit.
Definition at line 80 of file BuiltinTypes.h.
Member Enumeration Documentation
SignednessSemantics
enum mlir::IntegerType::SignednessSemantics : uint32_t
Signedness semantics.
Enumerator
Signless
Signed
No signedness semantics.
Unsigned
Signed integer.
Definition at line 86 of file BuiltinTypes.h.
Member Function Documentation
get() [1/2]
IntegerType IntegerType::get (unsigned width, MLIRContext * context) static
Get or create a new IntegerType of the given width within the context.
The created IntegerType is signless (i.e., no signedness semantics). Assume the width is within the allowed range and assert on failures. Use getChecked to handle failures gracefully.
Definition at line 775 of file MLIRContext.cpp.
References Signless.
Referenced by allocBuffer(), mlir::applyCmpPredicate(), mlir::quant::UniformQuantizedPerAxisValueConverter::convert(), convertRangeType(), convertScalarType(), convertStructType(), diag(), getDefaultStorageParams(), mlir::spirv::getEntryPointABIAttr(), getI1SameShape(), mlir::Builder::getI1Type(), mlir::Builder::getI32Type(), mlir::Builder::getI64Type(), mlir::SPIRVTypeConverter::getIndexType(), mlir::Builder::getIntegerType(), getPhiIncomingBlock(), isFnEntryBlock(), makeI64ArrayAttr(), mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite(), mlirIntegerTypeGet(), mlirIntegerTypeSignedGet(), mlirIntegerTypeUnsignedGet(), outlineExecuteOp(), mlir::detail::Parser::parseNonFunctionType(), and scaleElementBitwidth().
get() [2/2]
IntegerType IntegerType::get (unsigned width, IntegerType::SignednessSemantics signedness, MLIRContext * context) static
Get or create a new IntegerType of the given width within the context.
The created IntegerType has signedness semantics as indicated via signedness. Assume the width is within the allowed range and assert on failures. Use getChecked to handle failures gracefully.
Definition at line 779 of file MLIRContext.cpp.
References getCachedIntegerType().
getChecked() [1/2]
IntegerType IntegerType::getChecked (unsigned width, Location location) static
Get or create a new IntegerType of the given width within the context, defined at the given, potentially unknown, location.
The created IntegerType is signless (i.e., no signedness semantics). If the width is outside the allowed range, emit errors and return a null type.
Definition at line 787 of file MLIRContext.cpp.
References Signless.
getChecked() [2/2]
IntegerType IntegerType::getChecked (unsigned width, SignednessSemantics signedness, Location location) static
Get or create a new IntegerType of the given width within the context, defined at the given, potentially unknown, location.
The created IntegerType has signedness semantics as indicated via signedness. If the width is outside the allowed range, emit errors and return a null type.
Definition at line 791 of file MLIRContext.cpp.
References getCachedIntegerType(), mlir::Attribute::getContext(), mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::noneType.
getSignedness()
IntegerType::SignednessSemantics IntegerType::getSignedness () const
Return the signedness semantics of this integer type.
Definition at line 72 of file BuiltinTypes.cpp.
getWidth()
unsigned IntegerType::getWidth () const
Return the bitwidth of this integer type.
Definition at line 70 of file BuiltinTypes.cpp.
Referenced by convertIntegerAttr(), mlir::LLVMTypeConverter::getPointerBitwidth(), mlir::Builder::getZeroAttr(), mlir::spirv::ScalarType::isValid(), parseStorageRange(), parseStorageType(), printDenseElementsAttrImpl(), and verify().
isSigned()
bool mlir::IntegerType::isSigned () const inline
Return true if this is a signed integer type.
Definition at line 132 of file BuiltinTypes.h.
References mlir::quant::QuantizationFlags::Signed.
Referenced by isValidIntOrFloat(), and printDenseElementsAttrImpl().
isSignless()
bool mlir::IntegerType::isSignless () const inline
Return true if this is a signless integer type.
Definition at line 130 of file BuiltinTypes.h.
Referenced by verify().
isUnsigned()
bool mlir::IntegerType::isUnsigned () const inline
Return true if this is an unsigned integer type.
Definition at line 134 of file BuiltinTypes.h.
Referenced by printDenseElementsAttrImpl().
scaleElementBitwidth()
IntegerType IntegerType::scaleElementBitwidth (unsigned scale)
Get or create a new IntegerType with the same signedness as this and a bitwidth scaled by scale.
Return null if the scaled element type cannot be represented.
Definition at line 76 of file BuiltinTypes.cpp.
References get().
verifyConstructionInvariants()
LogicalResult IntegerType::verifyConstructionInvariants (Location loc, unsigned width, SignednessSemantics signedness) static
Verify the construction of an integer type.
Definition at line 61 of file BuiltinTypes.cpp.
References mlir::emitError(), kMaxWidth, and mlir::success().
Member Data Documentation
kMaxWidth
constexpr unsigned IntegerType::kMaxWidth = 4096 static
Integer representation maximal bitwidth.
Definition at line 142 of file BuiltinTypes.h.
Referenced by mlir::ComplexType::getElementType(), mlir::detail::Parser::parseNonFunctionType(), and verifyConstructionInvariants().
The documentation for this class was generated from the following files:
include/mlir/IR/BuiltinTypes.h
lib/IR/BuiltinTypes.cpp
lib/IR/MLIRContext.cpp