MLIR: mlir::OwningRewritePatternList Class Reference
mlir::OwningRewritePatternList Class Reference
#include "mlir/IR/PatternMatch.h"
Public Member Functions
OwningRewritePatternList ()=default
OwningRewritePatternList (std::unique_ptr< RewritePattern > pattern)
Construct a OwningRewritePatternList populated with the given pattern.
OwningRewritePatternList (PDLPatternModule &&pattern)
NativePatternListT & getNativePatterns ()
Return the native patterns held in this list.
PDLPatternModule & getPDLPatterns ()
Return the PDL patterns held in this list.
void clear ()
Clear out all of the held patterns in this list.
template<typename... Ts, typename ConstructorArg , typename... ConstructorArgs, typename = std::enable_if_t<sizeof...(Ts) != 0>>
OwningRewritePatternList & insert (ConstructorArg &&arg, ConstructorArgs &&...args)
Add an instance of each of the pattern types 'Ts' to the pattern list with the given arguments.
template<typename... Ts>
OwningRewritePatternList & insert ()
Add an instance of each of the pattern types 'Ts'.
OwningRewritePatternList & insert (std::unique_ptr< RewritePattern > pattern)
Add the given native pattern to the pattern list.
OwningRewritePatternList & insert (PDLPatternModule &&pattern)
Add the given PDL pattern to the pattern list.
Detailed Description
Definition at line 573 of file PatternMatch.h.
Constructor & Destructor Documentation
OwningRewritePatternList() [1/3]
mlir::OwningRewritePatternList::OwningRewritePatternList () default
OwningRewritePatternList() [2/3]
mlir::OwningRewritePatternList::OwningRewritePatternList (std::unique_ptr< RewritePattern > pattern) inline
Construct a OwningRewritePatternList populated with the given pattern.
Definition at line 580 of file PatternMatch.h.
OwningRewritePatternList() [3/3]
mlir::OwningRewritePatternList::OwningRewritePatternList (PDLPatternModule && pattern) inline
Definition at line 583 of file PatternMatch.h.
Member Function Documentation
clear()
void mlir::OwningRewritePatternList::clear () inline
Clear out all of the held patterns in this list.
Definition at line 593 of file PatternMatch.h.
getNativePatterns()
NativePatternListT& mlir::OwningRewritePatternList::getNativePatterns () inline
Return the native patterns held in this list.
Definition at line 587 of file PatternMatch.h.
getPDLPatterns()
PDLPatternModule& mlir::OwningRewritePatternList::getPDLPatterns () inline
Return the PDL patterns held in this list.
Definition at line 590 of file PatternMatch.h.
insert() [1/4]
template<typename... Ts, typename ConstructorArg , typename... ConstructorArgs, typename = std::enable_if_t<sizeof...(Ts) != 0>> OwningRewritePatternList& mlir::OwningRewritePatternList::insert (ConstructorArg && arg, ConstructorArgs &&... args) inline
Add an instance of each of the pattern types 'Ts' to the pattern list with the given arguments.
Return a reference to this for chaining insertions. Note: ConstructorArg is necessary here to separate the two variadic lists.
Definition at line 608 of file PatternMatch.h.
Referenced by mlir::applyCmpPredicate(), mlir::linalg::Tile< LinalgOpType >::buildRewritePatterns(), mlir::linalg::Promote< LinalgOpType >::buildRewritePatterns(), mlir::linalg::Vectorize< LinalgOpType >::buildRewritePatterns(), mlir::canFoldIntoConsumerOp(), canonicalizeLoopBounds(), mlir::canonicalizeSetAndOperands(), collapseBranch(), encodeKernelName(), extractCompositeElement(), foldExtractStridedOpFromInsertChain(), foldMinMaxOp(), mlir::scf::getParallelForInductionVarOwner(), joinShapes(), lowerEntryPointABIAttr(), lowerLinalgToLoopsImpl(), outlineExecuteOp(), parseConstShapeOp(), mlir::populateAffineToStdConversionPatterns(), mlir::populateAffineToVectorConversionPatterns(), mlir::populateArmNeonToLLVMConversionPatterns(), mlir::populateArmSVEToLLVMConversionPatterns(), mlir::populateAVX512ToLLVMConversionPatterns(), mlir::populateBranchOpInterfaceAndReturnOpTypeConversionPattern(), mlir::populateBuiltinFuncToSPIRVPatterns(), mlir::populateCallOpTypeConversionPattern(), mlir::populateConvertShapeConstraintsConversionPatterns(), mlir::populateDecomposeCallGraphTypesPatterns(), mlir::populateElementwiseToLinalgConversionPatterns(), mlir::populateEliminateBufferizeMaterializationsPatterns(), mlir::populateExpandTanhPattern(), mlir::populateFoldReshapeOpsByExpansionPatterns(), mlir::populateFoldReshapeOpsByLinearizationPatterns(), mlir::populateFuncOpTypeConversionPattern(), mlir::populateGpuAllReducePatterns(), mlir::populateGpuToLLVMConversionPatterns(), mlir::populateGpuToNVVMConversionPatterns(), mlir::populateGpuToROCDLConversionPatterns(), mlir::populateGPUToSPIRVPatterns(), mlir::linalg::populateLinalgBufferizePatterns(), mlir::linalg::populateLinalgConvGeneralizationPatterns(), mlir::populateLinalgFoldUnitExtentDimsPatterns(), mlir::linalg::populateLinalgNamedOpsGeneralizationPatterns(), mlir::populateLinalgTensorOpsFusionPatterns(), mlir::populateLinalgToLLVMConversionPatterns(), mlir::populateLinalgToSPIRVPatterns(), mlir::linalg::populateLinalgToStandardConversionPatterns(), mlir::populateLoopToStdConversionPatterns(), mlir::populateOpenMPToLLVMConversionPatterns(), mlir::populateParallelLoopToGPUPatterns(), mlir::populateRemoveShapeConstraintsPatterns(), mlir::scf::populateSCFStructuralTypeConversionsAndLegality(), mlir::populateSCFToSPIRVPatterns(), mlir::populateShapeRewritePatterns(), mlir::populateShapeStructuralTypeConversionsAndLegality(), mlir::populateShapeToStandardConversionPatterns(), mlir::linalg::populateSparsificationPatterns(), populateSPIRVLayoutInfoPatterns(), mlir::populateSPIRVToLLVMConversionPatterns(), mlir::populateSPIRVToLLVMFunctionConversionPatterns(), mlir::populateSPIRVToLLVMModuleConversionPatterns(), mlir::populateStandardToSPIRVPatterns(), mlir::populateStdBufferizePatterns(), mlir::populateStdExpandOpsPatterns(), mlir::populateStdLegalizationPatternsForSPIRVLowering(), mlir::populateStdToLLVMFuncOpConversionPattern(), mlir::populateStdToLLVMMemoryConversionPatterns(), mlir::populateStdToLLVMNonMemoryConversionPatterns(), mlir::populateTensorBufferizePatterns(), mlir::vector::populateVectorContractLoweringPatterns(), populateVectorizationPatterns(), mlir::vector::populateVectorSlicesLoweringPatterns(), mlir::populateVectorToLLVMConversionPatterns(), mlir::populateVectorToLLVMMatrixConversionPatterns(), mlir::populateVectorToROCDLConversionPatterns(), mlir::populateVectorToSCFConversionPatterns(), mlir::populateVectorToSPIRVPatterns(), mlir::vector::populateVectorToVectorCanonicalizationPatterns(), mlir::vector::populateVectorToVectorTransformationPatterns(), print(), replaceOpWithRegion(), reshapeLowerToHigher(), mlir::linalg::tileLinalgOp(), mlir::linalg::CodegenStrategy::transform(), and verify().
insert() [2/4]
template<typename... Ts> OwningRewritePatternList& mlir::OwningRewritePatternList::insert () inline
Add an instance of each of the pattern types 'Ts'.
Return a reference to this for chaining insertions.
Definition at line 620 of file PatternMatch.h.
insert() [3/4]
OwningRewritePatternList& mlir::OwningRewritePatternList::insert (std::unique_ptr< RewritePattern > pattern) inline
Add the given native pattern to the pattern list.
Return a reference to this for chaining insertions.
Definition at line 627 of file PatternMatch.h.
insert() [4/4]
OwningRewritePatternList& mlir::OwningRewritePatternList::insert (PDLPatternModule && pattern) inline
Add the given PDL pattern to the pattern list.
Return a reference to this for chaining insertions.
Definition at line 634 of file PatternMatch.h.
The documentation for this class was generated from the following file:
include/mlir/IR/PatternMatch.h