MLIR: mlir::edsc::BoundsCapture Class Reference
mlir::edsc::BoundsCapture Class Reference
Base class for MemRefBoundsCapture and VectorBoundsCapture.
#include "mlir/Dialect/StandardOps/EDSC/Builders.h"
Public Member Functions
unsigned rank () const
Value lb (unsigned idx) const
Value ub (unsigned idx) const
int64_t step (unsigned idx) const
std::tuple< Value, Value, int64_t > range (unsigned idx) const
void swapRanges (unsigned i, unsigned j)
ArrayRef< Value > getLbs () const
ArrayRef< Value > getUbs () const
ArrayRef< int64_t > getSteps () const
Protected Attributes
SmallVector< Value, 8 > lbs
SmallVector< Value, 8 > ubs
SmallVector< int64_t, 8 > steps
Detailed Description
Base class for MemRefBoundsCapture and VectorBoundsCapture.
Definition at line 20 of file Builders.h.
Member Function Documentation
getLbs()
ArrayRef<Value> mlir::edsc::BoundsCapture::getLbs () const inline
Definition at line 37 of file Builders.h.
References lbs.
Referenced by applyMapToValues(), and insertCopyLoops().
getSteps()
ArrayRef<int64_t> mlir::edsc::BoundsCapture::getSteps () const inline
Definition at line 39 of file Builders.h.
References steps.
Referenced by applyMapToValues(), and insertCopyLoops().
getUbs()
ArrayRef<Value> mlir::edsc::BoundsCapture::getUbs () const inline
Definition at line 38 of file Builders.h.
References ubs.
Referenced by applyMapToValues(), and insertCopyLoops().
lb()
Value mlir::edsc::BoundsCapture::lb (unsigned idx) const inline
Definition at line 23 of file Builders.h.
References lbs.
range()
std::tuple<Value, Value, int64_t> mlir::edsc::BoundsCapture::range (unsigned idx) const inline
Definition at line 26 of file Builders.h.
References lbs, steps, and ubs.
rank()
unsigned mlir::edsc::BoundsCapture::rank () const inline
Definition at line 22 of file Builders.h.
References lbs.
Referenced by mlir::edsc::MemRefBoundsCapture::fastestVarying(), and insertCopyLoops().
step()
int64_t mlir::edsc::BoundsCapture::step (unsigned idx) const inline
Definition at line 25 of file Builders.h.
References steps.
swapRanges()
void mlir::edsc::BoundsCapture::swapRanges (unsigned i, unsigned j) inline
Definition at line 29 of file Builders.h.
References lbs, steps, and ubs.
ub()
Value mlir::edsc::BoundsCapture::ub (unsigned idx) const inline
Definition at line 24 of file Builders.h.
References ubs.
Member Data Documentation
lbs
SmallVector<Value, 8> mlir::edsc::BoundsCapture::lbs protected
Definition at line 42 of file Builders.h.
Referenced by getLbs(), lb(), range(), rank(), and swapRanges().
steps
SmallVector<int64_t, 8> mlir::edsc::BoundsCapture::steps protected
Definition at line 44 of file Builders.h.
Referenced by getSteps(), range(), step(), and swapRanges().
ubs
SmallVector<Value, 8> mlir::edsc::BoundsCapture::ubs protected
Definition at line 43 of file Builders.h.
Referenced by getUbs(), range(), swapRanges(), and ub().
The documentation for this class was generated from the following file:
include/mlir/Dialect/StandardOps/EDSC/Builders.h