MLIR: mlir::pdl_to_pdl_interp::Position Class Reference
mlir::pdl_to_pdl_interp::Position Class Reference abstract
A position describes a value on the input IR on which a predicate may be applied, such as an operation or attribute.
#include "Conversion/PDLToPDLInterp/Predicate.h"
Public Member Functions
Position (Predicates::Kind kind)
virtual ~Position ()
virtual ArrayRef< unsigned > getIndex () const =0
Returns the base node position. This is an array of indices.
Position * getParent () const
Returns the parent position. The root operation position has no parent.
Predicates::Kind getKind () const
Returns the kind of this position.
Protected Attributes
Position * parent = nullptr
Link to the parent position.
Additional Inherited Members
Protected Member Functions inherited from mlir::StorageUniquer::BaseStorage
BaseStorage ()=default
Detailed Description
A position describes a value on the input IR on which a predicate may be applied, such as an operation or attribute.
This enables re-use between predicates, and assists generating bytecode and memory management.
Operation positions form the base of other positions, which are formed relative to a parent operation, e.g. OperandPosition<[0] -> 1>. Operations are indexed by child index: [0, 1, 2] refers to the 3rd child of the 2nd child of the root operation.
Positions are linked to their parent position, which describes how to obtain a positional value. As a concrete example, getting OperationPosition<[0, 1]> would be root->getOperand(1)->getDefiningOp(), so its parent is OperandPosition<[0] -> 1>, whose parent is OperationPosition<[0]>.
Definition at line 140 of file Predicate.h.
Constructor & Destructor Documentation
Position()
mlir::pdl_to_pdl_interp::Position::Position (Predicates::Kind kind) inline explicit
Definition at line 142 of file Predicate.h.
~Position()
Position::~Position () virtual
Definition at line 18 of file Predicate.cpp.
Member Function Documentation
getIndex()
virtual ArrayRef<unsigned> mlir::pdl_to_pdl_interp::Position::getIndex () const pure virtual
Returns the base node position. This is an array of indices.
Implemented in mlir::pdl_to_pdl_interp::TypePosition, mlir::pdl_to_pdl_interp::ResultPosition, mlir::pdl_to_pdl_interp::OperationPosition, mlir::pdl_to_pdl_interp::OperandPosition, and mlir::pdl_to_pdl_interp::AttributePosition.
Referenced by buildPredicateList(), and comparePosDepth().
getKind()
Predicates::Kind mlir::pdl_to_pdl_interp::Position::getKind () const inline
Returns the kind of this position.
Definition at line 152 of file Predicate.h.
Referenced by buildPredicateList(), and getTreePredicates().
getParent()
Position* mlir::pdl_to_pdl_interp::Position::getParent () const inline
Returns the parent position. The root operation position has no parent.
Definition at line 149 of file Predicate.h.
Member Data Documentation
parent
Position* mlir::pdl_to_pdl_interp::Position::parent = nullptr protected
Link to the parent position.
Definition at line 156 of file Predicate.h.
Referenced by mlir::pdl_to_pdl_interp::AttributePosition::AttributePosition(), mlir::pdl_to_pdl_interp::OperationPosition::get(), and mlir::pdl_to_pdl_interp::OperandPosition::OperandPosition().
The documentation for this class was generated from the following files:
lib/Conversion/PDLToPDLInterp/Predicate.h
lib/Conversion/PDLToPDLInterp/Predicate.cpp