MLIR: mlir::Pattern Class Reference
mlir::Pattern Class Reference
This class contains all of the data related to a pattern, but does not contain any methods or logic for the actual matching.
#include "mlir/IR/PatternMatch.h"
Classes
struct MatchAnyOpTypeTag
This class acts as a special tag that makes the desire to match "any" operation type explicit.
Public Member Functions
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Protected Member Functions
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
This class contains all of the data related to a pattern, but does not contain any methods or logic for the actual matching.
This class is solely used to interface with the metadata of a pattern, such as the benefit or root operation.
Definition at line 69 of file PatternMatch.h.
Constructor & Destructor Documentation
Pattern() [1/4]
Pattern::Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext * context) protected
Construct a pattern with a certain benefit that matches the operation with the given root name.
Definition at line 32 of file PatternMatch.cpp.
Referenced by mlir::RewritePattern::matchAndRewrite().
Pattern() [2/4]
Pattern::Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag) protected
Construct a pattern with a certain benefit that matches any operation type.
MatchAnyOpTypeTag is just a tag to ensure that the "match any" behavior is what the user actually desired, MatchAnyOpTypeTag() should always be supplied here.
Definition at line 35 of file PatternMatch.cpp.
Pattern() [3/4]
Pattern::Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext * context) protected
Construct a pattern with a certain benefit that matches the operation with the given root name.
generatedNames contains the names of operations that may be generated during a successful rewrite.
Definition at line 37 of file PatternMatch.cpp.
Pattern() [4/4]
Pattern::Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext * context, MatchAnyOpTypeTag tag) protected
Construct a pattern that may match any operation type.
generatedNames contains the names of operations that may be generated during a successful rewrite. MatchAnyOpTypeTag is just a tag to ensure that the "match any" behavior is what the user actually desired, MatchAnyOpTypeTag() should always be supplied here.
Definition at line 46 of file PatternMatch.cpp.
Member Function Documentation
getBenefit()
int Pattern::getBenefit () const inline
Return the benefit (the inverse of "cost") of matching this pattern.
The benefit of a Pattern is always static - rewrites that may have dynamic benefit can be instantiated multiple times (different Pattern instances) for each benefit that they may return, and be guarded by different match condition predicates.
Definition at line 84 of file PatternMatch.h.
Referenced by mlir::PatternApplicator::applyDefaultCostModel(), and mlir::PatternApplicator::matchAndRewrite().
getGeneratedOps()
ArrayRef<OperationName> mlir::Pattern::getGeneratedOps () const inline
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Definition at line 73 of file PatternMatch.h.
Referenced by mlir::ConversionPattern::matchAndRewrite().
getRootKind()
Optional<OperationName> mlir::Pattern::getRootKind () const inline
Return the root node that this pattern matches.
Patterns that can match multiple root types return None.
Definition at line 77 of file PatternMatch.h.
Referenced by mlir::ConversionPattern::matchAndRewrite().
hasBoundedRewriteRecursion()
bool mlir::Pattern::hasBoundedRewriteRecursion () const inline
Returns true if this pattern is known to result in recursive application, i.e.
this pattern may generate IR that also matches this pattern, but is known to bound the recursion. This signals to a rewrite driver that it is safe to apply this pattern recursively to generated IR.
Definition at line 90 of file PatternMatch.h.
Referenced by mlir::ConversionPattern::matchAndRewrite().
setHasBoundedRewriteRecursion()
void mlir::Pattern::setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg = true) inline protected
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Definition at line 121 of file PatternMatch.h.
The documentation for this class was generated from the following files:
include/mlir/IR/PatternMatch.h
lib/IR/PatternMatch.cpp
lib/TableGen/Pattern.cpp