MLIR: mlir::detail::PDLByteCode Class Reference
mlir::detail::PDLByteCode Class Reference
The bytecode class is also the interpreter.
#include "Rewrite/ByteCode.h"
Classes
struct MatchResult
Each successful match returns a MatchResult, which contains information necessary to execute the rewriter and indicates the originating pattern.
Public Member Functions
PDLByteCode (ModuleOp module, llvm::StringMap< PDLConstraintFunction > constraintFns, llvm::StringMap< PDLCreateFunction > createFns, llvm::StringMap< PDLRewriteFunction > rewriteFns)
Create a ByteCode instance from the given module containing operations in the PDL interpreter dialect.
ArrayRef< PDLByteCodePattern > getPatterns () const
Return the patterns held by the bytecode.
void initializeMutableState (PDLByteCodeMutableState &state) const
Initialize the given state such that it can be used to execute the current bytecode.
void match (Operation *op, PatternRewriter &rewriter, SmallVectorImpl< MatchResult > &matches, PDLByteCodeMutableState &state) const
Run the pattern matcher on the given root operation, collecting the matched patterns in matches.
void rewrite (PatternRewriter &rewriter, const MatchResult &match, PDLByteCodeMutableState &state) const
Run the rewriter of the given pattern that was previously matched in match.
Detailed Description
The bytecode class is also the interpreter.
Contains the bytecode itself, the static info, addresses of the rewriter functions, the interpreter memory buffer, and the execution context.
Definition at line 93 of file ByteCode.h.
Constructor & Destructor Documentation
PDLByteCode()
PDLByteCode::PDLByteCode (ModuleOp module, llvm::StringMap< PDLConstraintFunction > constraintFns, llvm::StringMap< PDLCreateFunction > createFns, llvm::StringMap< PDLRewriteFunction > rewriteFns)
Create a ByteCode instance from the given module containing operations in the PDL interpreter dialect.
Definition at line 679 of file ByteCode.cpp.
Member Function Documentation
getPatterns()
ArrayRef<PDLByteCodePattern> mlir::detail::PDLByteCode::getPatterns () const inline
Return the patterns held by the bytecode.
Definition at line 121 of file ByteCode.h.
initializeMutableState()
void PDLByteCode::initializeMutableState (PDLByteCodeMutableState & state) const
Initialize the given state such that it can be used to execute the current bytecode.
Definition at line 699 of file ByteCode.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::OpBuilder::createOperation(), mlir::PatternRewriter::eraseOp(), mlir::failed(), mlir::OperationName::getAbstractOperation(), mlir::Type::getAsOpaquePointer(), mlir::Value::getAsOpaquePointer(), mlir::Operation::getAttr(), mlir::PatternBenefit::getBenefit(), mlir::OperationState::getContext(), mlir::Value::getDefiningOp(), mlir::NamedAttrList::getDictionary(), mlir::Builder::getFusedLoc(), mlir::AbstractOperation::getInterface(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::Attribute::getType(), mlir::Value::getType(), mlir::PatternBenefit::isImpossibleToMatch(), mlir::OperationState::location, mlir::OperationState::name, mlir::OperationState::operands, mlir::OperationState::regions, mlir::PatternRewriter::replaceOp(), resultIndex(), mlir::succeeded(), and mlir::OperationState::types.
match()
void PDLByteCode::match (Operation * op, PatternRewriter & rewriter, SmallVectorImpl< MatchResult > & matches, PDLByteCodeMutableState & state) const
Run the pattern matcher on the given root operation, collecting the matched patterns in matches.
Definition at line 1234 of file ByteCode.cpp.
References mlir::detail::PDLByteCode::MatchResult::benefit.
Referenced by mlir::PatternApplicator::matchAndRewrite().
rewrite()
void PDLByteCode::rewrite (PatternRewriter & rewriter, const MatchResult & match, PDLByteCodeMutableState & state) const
Run the rewriter of the given pattern that was previously matched in match.
Run the rewriter of the given pattern on the root operation op.
Definition at line 1255 of file ByteCode.cpp.
References copy(), mlir::detail::PDLByteCodePattern::getRewriterAddr(), mlir::detail::PDLByteCode::MatchResult::location, mlir::detail::PDLByteCode::MatchResult::pattern, and mlir::detail::PDLByteCode::MatchResult::values.
Referenced by mlir::PatternApplicator::matchAndRewrite().
The documentation for this class was generated from the following files:
lib/Rewrite/ByteCode.h
lib/Rewrite/ByteCode.cpp