MLIR: mlir::FrozenRewritePatternList Class Reference
mlir::FrozenRewritePatternList Class Reference
This class represents a frozen set of patterns that can be processed by a pattern applicator.
#include "mlir/Rewrite/FrozenRewritePatternList.h"
Public Member Functions
FrozenRewritePatternList ()
Freeze the patterns held in patterns, and take ownership.
FrozenRewritePatternList (OwningRewritePatternList &&patterns)
FrozenRewritePatternList (FrozenRewritePatternList &&patterns)=default
FrozenRewritePatternList (const FrozenRewritePatternList &patterns)=default
FrozenRewritePatternList & operator= (const FrozenRewritePatternList &patterns)=default
FrozenRewritePatternList & operator= (FrozenRewritePatternList &&patterns)=default
~FrozenRewritePatternList ()
iterator_range< llvm::pointee_iterator< NativePatternListT::const_iterator > > getNativePatterns () const
Return the native patterns held by this list.
const detail::PDLByteCode * getPDLByteCode () const
Return the compiled PDL bytecode held by this list.
Detailed Description
This class represents a frozen set of patterns that can be processed by a pattern applicator.
This class is designed to enable caching pattern lists such that they need not be continuously recomputed. Note that all copies of this class share the same compiled pattern list, allowing for a reduction in the number of duplicated patterns that need to be created.
Definition at line 24 of file FrozenRewritePatternList.h.
Constructor & Destructor Documentation
FrozenRewritePatternList() [1/4]
FrozenRewritePatternList::FrozenRewritePatternList ()
Freeze the patterns held in patterns, and take ownership.
Definition at line 53 of file FrozenRewritePatternList.cpp.
FrozenRewritePatternList() [2/4]
FrozenRewritePatternList::FrozenRewritePatternList (OwningRewritePatternList && patterns)
Definition at line 56 of file FrozenRewritePatternList.cpp.
References convertPDLToPDLInterp(), and mlir::failed().
FrozenRewritePatternList() [3/4]
mlir::FrozenRewritePatternList::FrozenRewritePatternList (FrozenRewritePatternList && patterns) default
FrozenRewritePatternList() [4/4]
mlir::FrozenRewritePatternList::FrozenRewritePatternList (const FrozenRewritePatternList & patterns) default
~FrozenRewritePatternList()
FrozenRewritePatternList::~FrozenRewritePatternList ()
Definition at line 76 of file FrozenRewritePatternList.cpp.
Member Function Documentation
getNativePatterns()
iterator_range<llvm::pointee_iterator<NativePatternListT::const_iterator> > mlir::FrozenRewritePatternList::getNativePatterns () const inline
Return the native patterns held by this list.
Definition at line 41 of file FrozenRewritePatternList.h.
Referenced by mlir::PatternApplicator::applyCostModel(), and mlir::PatternApplicator::walkAllPatterns().
getPDLByteCode()
const detail::PDLByteCode* mlir::FrozenRewritePatternList::getPDLByteCode () const inline
Return the compiled PDL bytecode held by this list.
Returns null if there are no PDL patterns within the list.
Definition at line 48 of file FrozenRewritePatternList.h.
Referenced by mlir::PatternApplicator::applyCostModel(), mlir::PatternApplicator::matchAndRewrite(), mlir::PatternApplicator::PatternApplicator(), and mlir::PatternApplicator::walkAllPatterns().
operator=() [1/2]
FrozenRewritePatternList& mlir::FrozenRewritePatternList::operator= (const FrozenRewritePatternList & patterns) default
operator=() [2/2]
FrozenRewritePatternList& mlir::FrozenRewritePatternList::operator= (FrozenRewritePatternList && patterns) default
The documentation for this class was generated from the following files:
include/mlir/Rewrite/FrozenRewritePatternList.h
lib/Rewrite/FrozenRewritePatternList.cpp