MLIR: mlir::MLIRContext Class Reference
mlir::MLIRContext Class Reference
MLIRContext is the top-level object for a collection of MLIR operations.
#include "mlir/IR/MLIRContext.h"
Public Member Functions
MLIRContext ()
Create a new Context.
~MLIRContext ()
std::vector< Dialect * > getLoadedDialects ()
Return information about all IR dialects loaded in the context.
DialectRegistry & getDialectRegistry ()
Return the dialect registry associated with this context.
std::vector< StringRef > getAvailableDialects ()
Return information about all available dialects in the registry in this context.
Dialect * getLoadedDialect (StringRef name)
Get a registered IR dialect with the given namespace.
template<typename T >
T * getLoadedDialect ()
Get a registered IR dialect for the given derived dialect type.
template<typename T >
T * getOrLoadDialect ()
Get (or create) a dialect for the given derived dialect type.
template<typename Dialect >
void loadDialect ()
Load a dialect in the context.
template<typename Dialect , typename OtherDialect , typename... MoreDialects>
void loadDialect ()
Load a list dialects in the context.
Dialect * getOrLoadDialect (StringRef name)
Get (or create) a dialect for the given derived dialect name.
bool allowsUnregisteredDialects ()
Return true if we allow to create operation for unregistered dialects.
void allowUnregisteredDialects (bool allow=true)
Enables creating operations in unregistered dialects.
bool isMultithreadingEnabled ()
Return true if multi-threading is enabled by the context.
void disableMultithreading (bool disable=true)
Set the flag specifying if multi-threading is disabled by the context.
void enableMultithreading (bool enable=true)
bool shouldPrintOpOnDiagnostic ()
Return true if we should attach the operation to diagnostics emitted via Operation::emit.
void printOpOnDiagnostic (bool enable)
Set the flag specifying if we should attach the operation to diagnostics emitted via Operation::emit.
bool shouldPrintStackTraceOnDiagnostic ()
Return true if we should attach the current stacktrace to diagnostics when emitted.
void printStackTraceOnDiagnostic (bool enable)
Set the flag specifying if we should attach the current stacktrace when emitting diagnostics.
std::vector< AbstractOperation * > getRegisteredOperations ()
Return information about all registered operations.
bool isOperationRegistered (StringRef name)
Return true if this operation name is registered in this context.
MLIRContextImpl & getImpl ()
DiagnosticEngine & getDiagEngine ()
Returns the diagnostic engine for this context.
StorageUniquer & getAffineUniquer ()
Returns the storage uniquer used for creating affine constructs.
StorageUniquer & getTypeUniquer ()
Returns the storage uniquer used for constructing type storage instances.
StorageUniquer & getAttributeUniquer ()
Returns the storage uniquer used for constructing attribute storage instances.
void enterMultiThreadedExecution ()
These APIs are tracking whether the context will be used in a multithreading environment: this has no effect other than enabling assertions on misuses of some APIs.
void exitMultiThreadedExecution ()
Detailed Description
MLIRContext is the top-level object for a collection of MLIR operations.
It holds immortal uniqued objects like types, and the tables used to unique them.
MLIRContext gets a redundant "MLIR" prefix because otherwise it ends up with a very generic name ("Context") and because it is uncommon for clients to interact with it.
Definition at line 36 of file MLIRContext.h.
Constructor & Destructor Documentation
MLIRContext()
MLIRContext::MLIRContext () explicit
Create a new Context.
The loadAllDialects parameters allows to load all dialects from the global registry on Context construction. It is deprecated and will be removed soon.
Types. Floating-point Types.
Index Type.
Integer Types.
None Type.
of the above types internally. Bool Attributes.
Unit Attribute.
Unknown Location Attribute.
The empty dictionary attribute.
Definition at line 334 of file MLIRContext.cpp.
References clOptions, disableMultithreading(), printOpOnDiagnostic(), printStackTraceOnDiagnostic(), and mlir::IntegerType::Signless.
Referenced by getImpl().
~MLIRContext()
MLIRContext::~MLIRContext ()
Definition at line 396 of file MLIRContext.cpp.
Member Function Documentation
allowsUnregisteredDialects()
bool MLIRContext::allowsUnregisteredDialects ()
Return true if we allow to create operation for unregistered dialects.
Definition at line 491 of file MLIRContext.cpp.
Referenced by loadDialect().
allowUnregisteredDialects()
void MLIRContext::allowUnregisteredDialects (bool allow = true)
Enables creating operations in unregistered dialects.
Definition at line 495 of file MLIRContext.cpp.
Referenced by loadDialect(), and processBuffer().
disableMultithreading()
void MLIRContext::disableMultithreading (bool disable = true)
Set the flag specifying if multi-threading is disabled by the context.
Definition at line 505 of file MLIRContext.cpp.
Referenced by enableMultithreading(), loadDialect(), MLIRContext(), and performActions().
enableMultithreading()
void mlir::MLIRContext::enableMultithreading (bool enable = true) inline
Definition at line 107 of file MLIRContext.h.
References disableMultithreading(), getRegisteredOperations(), isOperationRegistered(), printOpOnDiagnostic(), printStackTraceOnDiagnostic(), shouldPrintOpOnDiagnostic(), and shouldPrintStackTraceOnDiagnostic().
Referenced by performActions().
enterMultiThreadedExecution()
void MLIRContext::enterMultiThreadedExecution ()
These APIs are tracking whether the context will be used in a multithreading environment: this has no effect other than enabling assertions on misuses of some APIs.
Definition at line 514 of file MLIRContext.cpp.
Referenced by getImpl(), and mlir::PassManager::run().
exitMultiThreadedExecution()
void MLIRContext::exitMultiThreadedExecution ()
Definition at line 519 of file MLIRContext.cpp.
Referenced by getImpl(), and mlir::PassManager::run().
getAffineUniquer()
StorageUniquer & MLIRContext::getAffineUniquer ()
Returns the storage uniquer used for creating affine constructs.
Definition at line 851 of file MLIRContext.cpp.
References getImpl(), and safeGetOrCreate().
Referenced by mlir::AffineExpr::ceilDiv(), mlir::AffineExpr::floorDiv(), mlir::getAffineConstantExpr(), getAffineDimOrSymbol(), getImpl(), mlir::AffineExpr::operator%(), mlir::AffineExpr::operator*(), and mlir::AffineExpr::operator+().
getAttributeUniquer()
StorageUniquer & MLIRContext::getAttributeUniquer ()
Returns the storage uniquer used for constructing attribute storage instances.
This should not be used directly.
Definition at line 815 of file MLIRContext.cpp.
References mlir::AttributeStorage::getType(), mlir::AttributeStorage::initialize(), mlir::AbstractAttribute::lookup(), and mlir::AttributeStorage::setType().
Referenced by mlir::detail::AttributeUniquer::get(), getImpl(), mlir::detail::AttributeUniquer::mutate(), and mlir::detail::AttributeUniquer::registerAttribute().
getAvailableDialects()
std::vector< StringRef > MLIRContext::getAvailableDialects ()
Return information about all available dialects in the registry in this context.
Definition at line 435 of file MLIRContext.cpp.
getDiagEngine()
DiagnosticEngine & MLIRContext::getDiagEngine ()
Returns the diagnostic engine for this context.
Definition at line 413 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::diagEngine, and getImpl().
Referenced by emitDiag(), getImpl(), and mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl().
getDialectRegistry()
DialectRegistry & MLIRContext::getDialectRegistry ()
Return the dialect registry associated with this context.
Definition at line 419 of file MLIRContext.cpp.
Referenced by mlir::JitRunnerMain(), processBuffer(), roundTripModule(), and mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration().
getImpl()
MLIRContextImpl& mlir::MLIRContext::getImpl () inline
Definition at line 137 of file MLIRContext.h.
References enterMultiThreadedExecution(), exitMultiThreadedExecution(), getAffineUniquer(), getAttributeUniquer(), getDiagEngine(), getOrLoadDialect(), getTypeUniquer(), MLIRContext(), and mlir::registerMLIRContextCLOptions().
Referenced by mlir::detail::generateUnknownStorageLocation(), mlir::Identifier::get(), mlir::UnknownLoc::get(), mlir::BoolAttr::get(), mlir::UnitAttr::get(), getAffineUniquer(), getCachedIntegerType(), mlir::IntegerType::getChecked(), getDiagEngine(), getOrLoadDialect(), getTypeUniquer(), mlir::AbstractType::lookup(), mlir::AbstractAttribute::lookup(), and mlir::AbstractOperation::lookup().
getLoadedDialect() [1/2]
Dialect * MLIRContext::getLoadedDialect (StringRef name)
Get a registered IR dialect with the given namespace.
If an exact match is not found, then return nullptr.
If none is found, then return nullptr.
Definition at line 444 of file MLIRContext.cpp.
Referenced by mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait().
getLoadedDialect() [2/2]
template<typename T > T* mlir::MLIRContext::getLoadedDialect () inline
Get a registered IR dialect for the given derived dialect type.
The derived type must provide a static 'getDialectNamespace' method.
Definition at line 62 of file MLIRContext.h.
Referenced by getOrLoadDialect().
getLoadedDialects()
std::vector< Dialect * > MLIRContext::getLoadedDialects ()
Return information about all IR dialects loaded in the context.
Return information about all registered IR dialects.
Definition at line 424 of file MLIRContext.cpp.
Referenced by mlir::detail::DialectInterfaceCollectionBase::DialectInterfaceCollectionBase().
getOrLoadDialect() [1/2]
template<typename T > T* mlir::MLIRContext::getOrLoadDialect () inline
Get (or create) a dialect for the given derived dialect type.
The derived type must provide a static 'getDialectNamespace' method.
Definition at line 69 of file MLIRContext.h.
Referenced by getImpl(), getOrLoadDialect(), mlir::DialectRegistry::insert(), loadDialect(), mlir::detail::Parser::parseAttributeDict(), mlir::detail::Parser::parseExtendedAttr(), mlir::detail::Parser::parseOpaqueElementsAttr(), mlir::LLVM::ModuleTranslation::prepareLLVMModule(), and mlir::SDBMExpr::tryConvertAffineExpr().
getOrLoadDialect() [2/2]
Dialect * MLIRContext::getOrLoadDialect (StringRef name)
Get (or create) a dialect for the given derived dialect name.
The dialect will be loaded from the registry if no dialect is found. If no dialect is loaded for this name and none is available in the registry, returns nullptr.
Definition at line 450 of file MLIRContext.cpp.
References getImpl(), getLoadedDialect(), and getOrLoadDialect().
getRegisteredOperations()
std::vector< AbstractOperation * > MLIRContext::getRegisteredOperations ()
Return information about all registered operations.
This isn't very efficient: typically you should ask the operations about their properties directly.
This isn't very efficient, typically you should ask the operations about their properties directly.
Definition at line 552 of file MLIRContext.cpp.
Referenced by enableMultithreading().
getTypeUniquer()
StorageUniquer & MLIRContext::getTypeUniquer ()
Returns the storage uniquer used for constructing type storage instances.
This should not be used directly.
Definition at line 728 of file MLIRContext.cpp.
References mlir::MLIRContextImpl::bf16Ty, mlir::MLIRContextImpl::f16Ty, mlir::MLIRContextImpl::f32Ty, mlir::MLIRContextImpl::f64Ty, getImpl(), and mlir::MLIRContextImpl::indexTy.
Referenced by mlir::detail::TypeUniquer::get(), getImpl(), mlir::detail::TypeUniquer::mutate(), and mlir::detail::TypeUniquer::registerType().
isMultithreadingEnabled()
bool MLIRContext::isMultithreadingEnabled ()
Return true if multi-threading is enabled by the context.
Return true if multi-threading is disabled by the context.
Definition at line 500 of file MLIRContext.cpp.
Referenced by mlir::PassManager::enableIRPrinting(), mlir::Identifier::get(), inlineCallsInSCC(), loadDialect(), and performActions().
isOperationRegistered()
bool MLIRContext::isOperationRegistered (StringRef name)
Return true if this operation name is registered in this context.
Definition at line 572 of file MLIRContext.cpp.
Referenced by enableMultithreading().
loadDialect() [1/2]
template<typename Dialect > void mlir::MLIRContext::loadDialect () inline
Load a dialect in the context.
Definition at line 79 of file MLIRContext.h.
Referenced by deserializeModule(), loadDialect(), and mlir::translateLLVMIRToModule().
loadDialect() [2/2]
template<typename Dialect , typename OtherDialect , typename... MoreDialects> void mlir::MLIRContext::loadDialect () inline
Load a list dialects in the context.
Definition at line 85 of file MLIRContext.h.
References allowsUnregisteredDialects(), allowUnregisteredDialects(), disableMultithreading(), getOrLoadDialect(), isMultithreadingEnabled(), and loadDialect().
printOpOnDiagnostic()
void MLIRContext::printOpOnDiagnostic (bool enable)
Set the flag specifying if we should attach the operation to diagnostics emitted via Operation::emit.
Definition at line 533 of file MLIRContext.cpp.
Referenced by enableMultithreading(), hasSizeMismatch(), MLIRContext(), mlir::mlirTranslateMain(), and processBuffer().
printStackTraceOnDiagnostic()
void MLIRContext::printStackTraceOnDiagnostic (bool enable)
Set the flag specifying if we should attach the current stacktrace when emitting diagnostics.
Definition at line 545 of file MLIRContext.cpp.
Referenced by enableMultithreading(), and MLIRContext().
shouldPrintOpOnDiagnostic()
bool MLIRContext::shouldPrintOpOnDiagnostic ()
Return true if we should attach the operation to diagnostics emitted via Operation::emit.
Definition at line 527 of file MLIRContext.cpp.
Referenced by enableMultithreading(), and hasSizeMismatch().
shouldPrintStackTraceOnDiagnostic()
bool MLIRContext::shouldPrintStackTraceOnDiagnostic ()
Return true if we should attach the current stacktrace to diagnostics when emitted.
Definition at line 539 of file MLIRContext.cpp.
Referenced by emitDiag(), and enableMultithreading().
The documentation for this class was generated from the following files:
include/mlir/IR/MLIRContext.h
lib/IR/MLIRContext.cpp