MLIR: mlir::python::PyValue Class Reference
mlir::python::PyValue Class Reference
Wrapper around the generic MlirValue.
#include "Bindings/Python/IRModules.h"
Public Member Functions
PyValue (PyOperationRef parentOperation, MlirValue value)
MlirValue get ()
PyOperationRef & getParentOperation ()
void checkValid ()
Detailed Description
Wrapper around the generic MlirValue.
Values are managed completely by the operation that resulted in their definition. For op result value, this is the operation that defines the value. For block argument values, this is the operation that contains the block to which the value is an argument (blocks cannot be detached in Python bindings so such operation always exists).
Definition at line 655 of file IRModules.h.
Constructor & Destructor Documentation
PyValue()
mlir::python::PyValue::PyValue (PyOperationRef parentOperation, MlirValue value) inline
Definition at line 657 of file IRModules.h.
Member Function Documentation
checkValid()
void mlir::python::PyValue::checkValid () inline
Definition at line 663 of file IRModules.h.
References mlir::python::populateIRSubmodule().
get()
MlirValue mlir::python::PyValue::get () inline
Definition at line 660 of file IRModules.h.
Referenced by mlir::python::PyType::createFromCapsule().
getParentOperation()
PyOperationRef& mlir::python::PyValue::getParentOperation () inline
Definition at line 661 of file IRModules.h.
Referenced by mlir::python::PyType::createFromCapsule().
The documentation for this class was generated from the following file:
lib/Bindings/Python/IRModules.h