MLIR: mlir::ConvertToLLVMPattern Class Reference
mlir::ConvertToLLVMPattern Class Reference
Base class for operation conversions targeting the LLVM IR dialect.
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
Public Member Functions
ConvertToLLVMPattern (StringRef rootOpName, MLIRContext *context, LLVMTypeConverter &typeConverter, PatternBenefit benefit=1)
Public Member Functions inherited from mlir::ConversionPattern
virtual void rewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement rewriting.
virtual LogicalResult matchAndRewrite (Operation *op, ArrayRef< Value > operands, ConversionPatternRewriter &rewriter) const
Hook for derived classes to implement combined matching and rewriting.
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match and rewrite the IR root at the specified operation.
TypeConverter * getTypeConverter () const
Return the type converter held by this pattern, or nullptr if the pattern does not require type conversion.
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Protected Member Functions
LLVM::LLVMDialect & getDialect () const
Returns the LLVM dialect.
LLVMTypeConverter * getTypeConverter () const
LLVM::LLVMType getIndexType () const
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
LLVM::LLVMType getIntPtrType (unsigned addressSpace=0) const
Gets the MLIR type wrapping the LLVM integer type whose bit width corresponds to that of a LLVM pointer type.
LLVM::LLVMType getVoidType () const
Gets the MLIR type wrapping the LLVM void type.
LLVM::LLVMType getVoidPtrType () const
Get the MLIR type wrapping the LLVM i8* type.
Value createIndexConstant (ConversionPatternRewriter &builder, Location loc, uint64_t value) const
Create an LLVM dialect operation defining the given index constant.
Value getStridedElementPtr (Location loc, MemRefType type, Value memRefDesc, ValueRange indices, ConversionPatternRewriter &rewriter) const
Value getDataPtr (Location loc, MemRefType type, Value memRefDesc, ValueRange indices, ConversionPatternRewriter &rewriter) const
bool isSupportedMemRefType (MemRefType type) const
Returns if the givem memref type is supported.
Type getElementPtrType (MemRefType type) const
Returns the type of a pointer to an element of the memref.
void getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ArrayRef< Value > dynamicSizes, ConversionPatternRewriter &rewriter, SmallVectorImpl< Value > &sizes, SmallVectorImpl< Value > &strides, Value &sizeBytes) const
Computes sizes, strides and buffer size in bytes of memRefType with identity layout.
Value getSizeInBytes (Location loc, Type type, ConversionPatternRewriter &rewriter) const
Computes the size of type in bytes.
Value getNumElements (Location loc, ArrayRef< Value > shape, ConversionPatternRewriter &rewriter) const
Computes total number of elements for the given shape.
MemRefDescriptor createMemRefDescriptor (Location loc, MemRefType memRefType, Value allocatedPtr, Value alignedPtr, ArrayRef< Value > sizes, ArrayRef< Value > strides, ConversionPatternRewriter &rewriter) const
Creates and populates a canonical memref descriptor struct.
Protected Member Functions inherited from mlir::ConversionPattern
ConversionPattern (StringRef rootName, PatternBenefit benefit, TypeConverter &typeConverter, MLIRContext *ctx)
Construct a conversion pattern that matches an operation with the given root name.
ConversionPattern (PatternBenefit benefit, TypeConverter &typeConverter, MatchAnyOpTypeTag tag)
Construct a conversion pattern that matches any operation type.
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Additional Inherited Members
Protected Attributes inherited from mlir::ConversionPattern
TypeConverter * typeConverter = nullptr
An optional type converter for use by this pattern.
Detailed Description
Base class for operation conversions targeting the LLVM IR dialect.
It provides the conversion patterns with access to the LLVMTypeConverter and the LowerToLLVMOptions. The class captures the LLVMTypeConverter and the LowerToLLVMOptions by reference meaning the references have to remain alive during the entire pattern lifetime.
Definition at line 478 of file ConvertStandardToLLVM.h.
Constructor & Destructor Documentation
ConvertToLLVMPattern()
ConvertToLLVMPattern::ConvertToLLVMPattern (StringRef rootOpName, MLIRContext * context, LLVMTypeConverter & typeConverter, PatternBenefit benefit = 1)
Definition at line 445 of file StandardToLLVM.cpp.
Member Function Documentation
createIndexConstant()
Value ConvertToLLVMPattern::createIndexConstant (ConversionPatternRewriter & builder, Location loc, uint64_t value) const protected
Create an LLVM dialect operation defining the given index constant.
Definition at line 1043 of file StandardToLLVM.cpp.
References createIndexAttrConstant().
Referenced by mlir::LLVM::detail::vectorOneToOneRewrite().
createMemRefDescriptor()
MemRefDescriptor ConvertToLLVMPattern::createMemRefDescriptor (Location loc, MemRefType memRefType, Value allocatedPtr, Value alignedPtr, ArrayRef< Value > sizes, ArrayRef< Value > strides, ConversionPatternRewriter & rewriter) const protected
Creates and populates a canonical memref descriptor struct.
Creates and populates the memref descriptor struct given all its fields.
Definition at line 1182 of file StandardToLLVM.cpp.
References mlir::detail::enumerate(), mlir::StructBuilder::structType, and mlir::MemRefDescriptor::undef().
getDataPtr()
Value ConvertToLLVMPattern::getDataPtr (Location loc, MemRefType type, Value memRefDesc, ValueRange indices, ConversionPatternRewriter & rewriter) const protected
Definition at line 1084 of file StandardToLLVM.cpp.
getDialect()
LLVM::LLVMDialect & ConvertToLLVMPattern::getDialect () const protected
Returns the LLVM dialect.
Definition at line 1020 of file StandardToLLVM.cpp.
getElementPtrType()
Type ConvertToLLVMPattern::getElementPtrType (MemRefType type) const protected
Returns the type of a pointer to an element of the memref.
Definition at line 1100 of file StandardToLLVM.cpp.
References mlir::LLVM::LLVMType::getPointerTo(), and unwrap().
getIndexType()
LLVM::LLVMType ConvertToLLVMPattern::getIndexType () const protected
Gets the MLIR type wrapping the LLVM integer type whose bit width is defined by the used type converter.
Definition at line 1024 of file StandardToLLVM.cpp.
Referenced by mlir::LLVM::detail::vectorOneToOneRewrite().
getIntPtrType()
LLVM::LLVMType ConvertToLLVMPattern::getIntPtrType (unsigned addressSpace = 0) const protected
Gets the MLIR type wrapping the LLVM integer type whose bit width corresponds to that of a LLVM pointer type.
Definition at line 1029 of file StandardToLLVM.cpp.
References mlir::LLVM::LLVMType::getIntNTy().
getMemRefDescriptorSizes()
void ConvertToLLVMPattern::getMemRefDescriptorSizes (Location loc, MemRefType memRefType, ArrayRef< Value > dynamicSizes, ConversionPatternRewriter & rewriter, SmallVectorImpl< Value > & sizes, SmallVectorImpl< Value > & strides, Value & sizeBytes) const protected
Computes sizes, strides and buffer size in bytes of memRefType with identity layout.
Emits constant ops for the static sizes of memRefType, and uses dynamicSizes for the others. Emits instructions to compute strides and buffer size from these sizes.
For example, memref<4x?xf32> emits: sizes[0] = llvm.mlir.constant(4 : index) : !llvm.i64 sizes[1] = dynamicSizes[0] strides[1] = llvm.mlir.constant(1 : index) : !llvm.i64 strides[0] = sizes[0] size = llvm.mul sizes[0], sizes[1] : !llvm.i64 nullptr = llvm.mlir.null : !llvm.ptr<float> gep = llvm.getelementptr nullptr[size] : (!llvm.ptr<float>, !llvm.i64) -> !llvm.ptr<float> sizeBytes = llvm.ptrtoint gep : !llvm.ptr<float> to !llvm.i64
Definition at line 1106 of file StandardToLLVM.cpp.
References mlir::OpBuilder::create(), getElementPtrType(), mlir::MemRefType::getShape(), mlir::ShapedType::kDynamicSize, mlir::UnrankedMemRefDescriptor::size(), and mlir::UnrankedMemRefDescriptor::stride().
getNumElements()
Value ConvertToLLVMPattern::getNumElements (Location loc, ArrayRef< Value > shape, ConversionPatternRewriter & rewriter) const protected
Computes total number of elements for the given shape.
Definition at line 1170 of file StandardToLLVM.cpp.
References mlir::OpBuilder::create().
getSizeInBytes()
Value ConvertToLLVMPattern::getSizeInBytes (Location loc, Type type, ConversionPatternRewriter & rewriter) const protected
Computes the size of type in bytes.
Definition at line 1154 of file StandardToLLVM.cpp.
References mlir::Value::cast(), and mlir::OpBuilder::create().
getStridedElementPtr()
Value ConvertToLLVMPattern::getStridedElementPtr (Location loc, MemRefType type, Value memRefDesc, ValueRange indices, ConversionPatternRewriter & rewriter) const protected
Definition at line 1048 of file StandardToLLVM.cpp.
References mlir::MemRefDescriptor::alignedPtr(), mlir::OpBuilder::create(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefDescriptor::getElementPtrType(), mlir::getStridesAndOffset(), mlir::MemRefDescriptor::offset(), mlir::UnrankedMemRefDescriptor::offset(), mlir::MemRefDescriptor::stride(), mlir::UnrankedMemRefDescriptor::stride(), and mlir::succeeded().
getTypeConverter()
LLVMTypeConverter * ConvertToLLVMPattern::getTypeConverter () const protected
Definition at line 1015 of file StandardToLLVM.cpp.
References mlir::ConversionPattern::getTypeConverter().
Referenced by mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite().
getVoidPtrType()
LLVM::LLVMType ConvertToLLVMPattern::getVoidPtrType () const protected
Get the MLIR type wrapping the LLVM i8* type.
Definition at line 1039 of file StandardToLLVM.cpp.
References mlir::LLVM::LLVMType::getInt8PtrTy().
Referenced by mlir::LLVM::detail::vectorOneToOneRewrite().
getVoidType()
LLVM::LLVMType ConvertToLLVMPattern::getVoidType () const protected
Gets the MLIR type wrapping the LLVM void type.
Definition at line 1035 of file StandardToLLVM.cpp.
References mlir::LLVM::LLVMType::getVoidTy().
isSupportedMemRefType()
bool ConvertToLLVMPattern::isSupportedMemRefType (MemRefType type) const protected
Returns if the givem memref type is supported.
Definition at line 1092 of file StandardToLLVM.cpp.
References mlir::MemRefType::getAffineMaps().
The documentation for this class was generated from the following files:
include/mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h
lib/Conversion/StandardToLLVM/StandardToLLVM.cpp