MLIR: lib/Conversion/SPIRVToLLVM/ConvertLaunchFuncToLLVMCalls.cpp File Reference
ConvertLaunchFuncToLLVMCalls.cpp File Reference
#include "../PassDetail.h"
#include "mlir/Conversion/SPIRVToLLVM/ConvertSPIRVToLLVM.h"
#include "mlir/Conversion/SPIRVToLLVM/ConvertSPIRVToLLVMPass.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/SymbolTable.h"
#include "mlir/Transforms/DialectConversion.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static std::string descriptorSetName ()
Returns the string name of the DescriptorSet decoration.
static std::string bindingName ()
Returns the string name of the Binding decoration.
static unsigned calculateGlobalIndex (spirv::GlobalVariableOp op)
Calculates the index of the kernel's operand that is represented by the given global variable with the bind attribute.
static void copy (Location loc, Value dst, Value src, Value size, OpBuilder &builder)
Copies the given number of bytes from src to dst pointers.
static std::string createGlobalVariableWithBindName (spirv::GlobalVariableOp op, StringRef kernelModuleName)
Encodes the binding and descriptor set numbers into a new symbolic name.
static bool hasDescriptorSetAndBinding (spirv::GlobalVariableOp op)
Returns true if the given global variable has both a descriptor set number and a binding number.
static LogicalResult getKernelGlobalVariables (spirv::ModuleOp module, DenseMap< uint32_t, spirv::GlobalVariableOp > &globalVariableMap)
Fills globalVariableMap with SPIR-V global variables that represent kernel arguments from the given SPIR-V module.
static LogicalResult encodeKernelName (spirv::ModuleOp module)
Encodes the SPIR-V module's symbolic name into the name of the entry point function.
Variables
static constexpr const char kSPIRVModule [] = "__spv__"
Function Documentation
bindingName()
static std::string bindingName () static
Returns the string name of the Binding decoration.
Definition at line 44 of file ConvertLaunchFuncToLLVMCalls.cpp.
Referenced by calculateGlobalIndex(), createGlobalVariableWithBindName(), hasDescriptorSetAndBinding(), parseVariableDecorations(), printVariableDecorations(), and verify().
calculateGlobalIndex()
static unsigned calculateGlobalIndex (spirv::GlobalVariableOp op) static
Calculates the index of the kernel's operand that is represented by the given global variable with the bind attribute.
We assume that the index of each kernel's operand is mapped to (descriptorSet, binding) by the map: i -> (0, i) which is implemented under LowerABIAttributesPass.
Definition at line 54 of file ConvertLaunchFuncToLLVMCalls.cpp.
References bindingName(), and mlir::IntegerAttr::getInt().
Referenced by getKernelGlobalVariables().
copy()
static void copy (Location loc, Value dst, Value src, Value size, OpBuilder & builder) static
Copies the given number of bytes from src to dst pointers.
Definition at line 60 of file ConvertLaunchFuncToLLVMCalls.cpp.
References mlir::OpBuilder::create(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), and mlir::LLVM::LLVMType::getInt1Ty().
Referenced by mlir::FlatAffineConstraints::addConstantLowerBound(), mlir::FlatAffineConstraints::addEquality(), mlir::FlatAffineConstraints::addInequality(), mlir::FlatAffineConstraints::addLocalFloorDiv(), mlir::FlatAffineConstraints::clearAndCopyFrom(), mlir::detail::DenseIntOrFPElementsAttributeStorage::construct(), mlir::detail::DenseStringElementsAttributeStorage::construct(), doubleBuffer(), encodeKernelName(), mlir::OpTrait::util::getBroadcastedShape(), mlir::edsc::makeGenericLinalgOp(), GpuAsyncRegionPass::ThreadTokenCallback::operator()(), mlir::FlatAffineConstraints::removeEquality(), mlir::FlatAffineConstraints::removeInequality(), mlir::detail::PDLByteCode::rewrite(), mlir::shapeRatio(), tileLinalgOpImpl(), mlir::FlatAffineConstraints::unionBoundingBox(), walkReturnOperations(), and GpuAsyncRegionPass::DeferWaitCallback::~DeferWaitCallback().
createGlobalVariableWithBindName()
static std::string createGlobalVariableWithBindName (spirv::GlobalVariableOp op, StringRef kernelModuleName) static
Encodes the binding and descriptor set numbers into a new symbolic name.
The name is specified by {kernel_module_name}_{variable_name}_descriptor_set{ds}_binding{b} to avoid symbolic conflicts, where 'ds' and 'b' are descriptor set and binding numbers.
Definition at line 75 of file ConvertLaunchFuncToLLVMCalls.cpp.
References bindingName(), descriptorSetName(), and mlir::IntegerAttr::getInt().
Referenced by encodeKernelName().
descriptorSetName()
static std::string descriptorSetName () static
Returns the string name of the DescriptorSet decoration.
Definition at line 38 of file ConvertLaunchFuncToLLVMCalls.cpp.
Referenced by createGlobalVariableWithBindName(), hasDescriptorSetAndBinding(), parseVariableDecorations(), printVariableDecorations(), and verify().
encodeKernelName()
static LogicalResult encodeKernelName (spirv::ModuleOp module) static
Encodes the SPIR-V module's symbolic name into the name of the entry point function.
Definition at line 117 of file ConvertLaunchFuncToLLVMCalls.cpp.
References mlir::ConversionTarget::addLegalDialect(), mlir::applyPartialConversion(), mlir::Location::cast(), copy(), mlir::OpBuilder::create(), createGlobalVariableWithBindName(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::Builder::getContext(), mlir::LLVM::LLVMType::getFunctionTy(), getKernelGlobalVariables(), mlir::Builder::getUnknownLoc(), mlir::LLVM::LLVMType::getVoidTy(), mlir::OwningRewritePatternList::insert(), mlir::kDeriveIndexBitwidthFromDataLayout, kSPIRVModule, options, mlir::populateSPIRVToLLVMTypeConversion(), mlir::populateStdToLLVMConversionPatterns(), mlir::SymbolTable::replaceAllSymbolUses(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToStart(), mlir::SymbolTable::setSymbolName(), and mlir::success().
getKernelGlobalVariables()
static LogicalResult getKernelGlobalVariables (spirv::ModuleOp module, DenseMap< uint32_t, spirv::GlobalVariableOp > & globalVariableMap) static
Fills globalVariableMap with SPIR-V global variables that represent kernel arguments from the given SPIR-V module.
We assume that the module contains a single entry point function. Hence, all spv.globalVariables with a bind attribute are kernel arguments.
Definition at line 99 of file ConvertLaunchFuncToLLVMCalls.cpp.
References calculateGlobalIndex(), hasDescriptorSetAndBinding(), and mlir::success().
Referenced by encodeKernelName().
hasDescriptorSetAndBinding()
static bool hasDescriptorSetAndBinding (spirv::GlobalVariableOp op) static
Returns true if the given global variable has both a descriptor set number and a binding number.
Definition at line 88 of file ConvertLaunchFuncToLLVMCalls.cpp.
References bindingName(), and descriptorSetName().
Referenced by getKernelGlobalVariables().
Variable Documentation
kSPIRVModule
constexpr const char kSPIRVModule[] = "__spv__" static
Definition at line 31 of file ConvertLaunchFuncToLLVMCalls.cpp.
Referenced by encodeKernelName().