MLIR: lib/Conversion/GPUCommon/ConvertLaunchFuncToRuntimeCalls.cpp File Reference
ConvertLaunchFuncToRuntimeCalls.cpp File Reference
#include "mlir/Conversion/GPUCommon/GPUCommonPass.h"
#include "../PassDetail.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FormatVariadic.h"
Functions
static LogicalResult areAllLLVMTypes (Operation *op, ValueRange operands, ConversionPatternRewriter &rewriter)
static LogicalResult isAsyncWithOneDependency (ConversionPatternRewriter &rewriter, gpu::AsyncOpInterface op)
Variables
static constexpr const char * kGpuBinaryStorageSuffix = "_gpubin_cst"
Function Documentation
areAllLLVMTypes()
static LogicalResult areAllLLVMTypes (Operation * op, ValueRange operands, ConversionPatternRewriter & rewriter) static
Definition at line 300 of file ConvertLaunchFuncToRuntimeCalls.cpp.
References mlir::Value::getType(), mlir::Type::isa(), mlir::ConversionPatternRewriter::notifyMatchFailure(), and mlir::success().
Referenced by isAsyncWithOneDependency().
isAsyncWithOneDependency()
static LogicalResult isAsyncWithOneDependency (ConversionPatternRewriter & rewriter, gpu::AsyncOpInterface op) static
Definition at line 311 of file ConvertLaunchFuncToRuntimeCalls.cpp.
References areAllLLVMTypes(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::LLVM::createGlobalString(), mlir::LLVM::LLVMType::createStructTy(), mlir::detail::enumerate(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), getElementPtrType(), getElementType(), mlir::Builder::getI32IntegerAttr(), mlir::Attribute::getType(), kGpuBinaryStorageSuffix, mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::ConversionPatternRewriter::replaceOp(), mlir::OpBuilder::restoreInsertionPoint(), mlir::OpBuilder::saveInsertionPoint(), mlir::OpBuilder::setInsertionPointAfter(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::success().
Variable Documentation
kGpuBinaryStorageSuffix
constexpr const char* kGpuBinaryStorageSuffix = "_gpubin_cst" static
Definition at line 37 of file ConvertLaunchFuncToRuntimeCalls.cpp.
Referenced by isAsyncWithOneDependency().