MLIR: lib/Conversion/AVX512ToLLVM/ConvertAVX512ToLLVM.cpp File Reference
ConvertAVX512ToLLVM.cpp File Reference
#include "mlir/Conversion/AVX512ToLLVM/ConvertAVX512ToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Dialect/AVX512/AVX512Dialect.h"
#include "mlir/Dialect/LLVMIR/LLVMAVX512Dialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
Functions
template<typename OpTy >
static Type getSrcVectorElementType (Operation *op)
Function Documentation
getSrcVectorElementType()
template<typename OpTy > static Type getSrcVectorElementType (Operation * op) static
Definition at line 25 of file ConvertAVX512ToLLVM.cpp.
References mlir::failure(), getElementType(), mlir::Type::isF32(), mlir::Type::isF64(), and mlir::LLVM::detail::oneToOneRewrite().