MLIR: lib/Target/LLVMIR/ConvertToROCDLIR.cpp File Reference
ConvertToROCDLIR.cpp File Reference
#include "mlir/Target/ROCDLIR.h"
#include "mlir/Dialect/GPU/GPUDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "mlir/Translation.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/ToolOutputFile.h"
#include "mlir/Dialect/LLVMIR/ROCDLConversions.inc"
Namespaces
mlir
Include the generated interface declarations.
Functions
static llvm::Value * createIntrinsicCall (llvm::IRBuilder<> &builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value *> args={}, ArrayRef< llvm::Type *> tys={})
static llvm::Value * createDeviceFunctionCall (llvm::IRBuilder<> &builder, StringRef fn_name, int parameter)
void mlir::registerToROCDLIRTranslation ()
Function Documentation
createDeviceFunctionCall()
static llvm::Value* createDeviceFunctionCall (llvm::IRBuilder<> & builder, StringRef fn_name, int parameter) static
Definition at line 44 of file ConvertToROCDLIR.cpp.
References mlir::LLVM::ModuleTranslation::convertOperation(), mlir::LLVM::ModuleTranslation::ModuleTranslation(), and mlir::translateModuleToROCDLIR().
createIntrinsicCall()
static llvm::Value* createIntrinsicCall (llvm::IRBuilder<> & builder, llvm::Intrinsic::ID intrinsic, ArrayRef< llvm::Value *> args = {}, ArrayRef< llvm::Type *> tys = {}) static
Definition at line 31 of file ConvertToROCDLIR.cpp.