MLIR: lib/Target/LLVMIR/DebugTranslation.cpp File Reference
DebugTranslation.cpp File Reference
#include "DebugTranslation.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
Functions
static WalkResult interruptIfValidLocation (Operation *op)
A utility walker that interrupts if the operation has valid debug information.
static FileLineColLoc extractFileLoc (Location loc)
Attempt to extract a filename for the given loc.
Function Documentation
extractFileLoc()
static FileLineColLoc extractFileLoc (Location loc) static
Attempt to extract a filename for the given loc.
Definition at line 68 of file DebugTranslation.cpp.
References mlir::Location::dyn_cast().
Referenced by mlir::LLVM::detail::DebugTranslation::translate().
interruptIfValidLocation()
static WalkResult interruptIfValidLocation (Operation * op) static
A utility walker that interrupts if the operation has valid debug information.
Definition at line 22 of file DebugTranslation.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getLoc(), mlir::WalkResult::interrupt(), and mlir::Location::isa().
Referenced by mlir::LLVM::detail::DebugTranslation::DebugTranslation(), and mlir::LLVM::detail::DebugTranslation::translate().