MLIR: lib/Target/SPIRV/Deserialization.cpp File Reference
Deserialization.cpp File Reference
#include "mlir/Target/SPIRV/Deserialization.h"
#include "mlir/Dialect/SPIRV/SPIRVAttributes.h"
#include "mlir/Dialect/SPIRV/SPIRVModule.h"
#include "mlir/Dialect/SPIRV/SPIRVOps.h"
#include "mlir/Dialect/SPIRV/SPIRVTypes.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Location.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Target/SPIRV/SPIRVBinaryUtils.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/bit.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/SPIRV/SPIRVSerialization.inc"
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "spirv-deserialization"
#define MIN_VERSION_CASE(v)
#define GET_DESERIALIZATION_FNS
Functions
static StringRef decodeStringLiteral (ArrayRef< uint32_t > words, unsigned &wordIndex)
Decodes a string literal in words starting at wordIndex.
static spirv::Opcode extractOpcode (uint32_t word)
Extracts the opcode from the given first word of a SPIR-V instruction.
static bool isFnEntryBlock (Block *block)
Returns true if the given block is a function entry block.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-deserialization"
Definition at line 35 of file Deserialization.cpp.
GET_DESERIALIZATION_FNS
#define GET_DESERIALIZATION_FNS
Definition at line 2780 of file Deserialization.cpp.
MIN_VERSION_CASE
#define MIN_VERSION_CASE (v)
Value:
case v:                                                                      \
    version = spirv::Version::V_1_##v;                                         \
    break
Referenced by isFnEntryBlock().
Function Documentation
decodeStringLiteral()
static StringRef decodeStringLiteral (ArrayRef< uint32_t > words, unsigned & wordIndex) inline static
Decodes a string literal in words starting at wordIndex.
Update the latter to point to the position in words after the string literal.
Definition at line 39 of file Deserialization.cpp.
Referenced by isFnEntryBlock().
extractOpcode()
static spirv::Opcode extractOpcode (uint32_t word) inline static
Extracts the opcode from the given first word of a SPIR-V instruction.
Definition at line 47 of file Deserialization.cpp.
Referenced by isFnEntryBlock().
isFnEntryBlock()
static bool isFnEntryBlock (Block * block) inline static
Returns true if the given block is a function entry block.
Definition at line 52 of file Deserialization.cpp.
References mlir::Region::back(), mlir::Block::begin(), mlir::Type::cast(), mlir::Operation::clone(), mlir::Operation::create(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::debugString(), decodeStringLiteral(), mlir::spirv::deserialize(), mlir::Type::dyn_cast(), mlir::emitError(), extractOpcode(), mlir::failed(), mlir::failure(), mlir::spirv::VerCapExtAttr::get(), mlir::IntegerType::get(), mlir::spirv::ArrayType::get(), mlir::FunctionType::get(), mlir::UnknownLoc::get(), mlir::spirv::PointerType::get(), mlir::spirv::RuntimeArrayType::get(), mlir::spirv::StructType::get(), mlir::VectorType::get(), mlir::TypeAttr::get(), mlir::spirv::CooperativeMatrixNVType::get(), mlir::spirv::MatrixType::get(), mlir::DenseElementsAttr::get(), mlir::Builder::getArrayAttr(), mlir::OpBuilder::getBlock(), mlir::Operation::getBlockOperands(), mlir::spirv::StructType::getEmpty(), mlir::Builder::getFileLineColLoc(), mlir::Builder::getI32IntegerAttr(), mlir::spirv::StructType::getIdentified(), mlir::Builder::getIdentifier(), mlir::Builder::getNamedAttr(), mlir::Operation::getOpOperands(), mlir::Block::getParentOp(), mlir::Operation::getRegion(), mlir::Builder::getSymbolRefAttr(), mlir::Block::getTerminator(), mlir::Type::isa(), mlir::Block::isEntryBlock(), mlir::Type::isIntOrFloat(), mlir::spirv::kHeaderWordCount, mlir::spirv::kMagicNumber, mlir::BlockAndValueMapping::lookupOrNull(), mlir::BlockAndValueMapping::map(), MIN_VERSION_CASE, mlir::Operation::print(), mlir::Block::print(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::quant::QuantizationFlags::Signed, mlir::succeeded(), and mlir::success().