MLIR: lib/Dialect/Linalg/Transforms/Bufferize.cpp File Reference
Bufferize.cpp File Reference
#include "mlir/Transforms/Bufferize.h"
#include "PassDetail.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/Transforms/Passes.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/BuiltinDialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Pass/Pass.h"
Functions
static Value maybeConvertToIndex (Location loc, Value val, OpBuilder &b)
static Value cloneMemref (Location loc, Value memref, OpBuilder &b)
static LogicalResult allocateBuffersForResults (Location loc, LinalgOp linalgOp, linalg::GenericOpAdaptor &adaptor, SmallVectorImpl< Value > &resultBuffers, OpBuilder &b)
template<typename GenericOpTy >
static void finalizeBufferAllocationForGenericOp (ConversionPatternRewriter &rewriter, GenericOpTy genericOp, ValueRange inputs, ValueRange outputs)
Specialization for linalg::GenericOp and linalg::IndexedGenericOp.
static void finalizeBufferAllocation (ConversionPatternRewriter &rewriter, linalg::LinalgOp linalgOp, ValueRange inputs, ValueRange outputs)
Specialization for all other linalg::LinalgOp.
Function Documentation
allocateBuffersForResults()
static LogicalResult allocateBuffersForResults (Location loc, LinalgOp linalgOp, linalg::GenericOpAdaptor & adaptor, SmallVectorImpl< Value > & resultBuffers, OpBuilder & b) static
Definition at line 44 of file Bufferize.cpp.
References cloneMemref(), mlir::detail::enumerate(), mlir::failure(), maybeConvertToIndex(), resultIndex(), and mlir::success().
Referenced by finalizeBufferAllocation().
cloneMemref()
static Value cloneMemref (Location loc, Value memref, OpBuilder & b) static
Definition at line 30 of file Bufferize.cpp.
References mlir::detail::enumerate().
Referenced by allocateBuffersForResults(), and finalizeBufferAllocation().
finalizeBufferAllocation()
static void finalizeBufferAllocation (ConversionPatternRewriter & rewriter, linalg::LinalgOp linalgOp, ValueRange inputs, ValueRange outputs) static
Specialization for all other linalg::LinalgOp.
Definition at line 153 of file Bufferize.cpp.
References allocateBuffersForResults(), mlir::applyPartialConversion(), cloneMemref(), extractFromI64ArrayAttr(), mlir::failed(), mlir::failure(), mlir::linalg::populateLinalgBufferizePatterns(), and mlir::success().
finalizeBufferAllocationForGenericOp()
template<typename GenericOpTy > static void finalizeBufferAllocationForGenericOp (ConversionPatternRewriter & rewriter, GenericOpTy genericOp, ValueRange inputs, ValueRange outputs) static
Specialization for linalg::GenericOp and linalg::IndexedGenericOp.
A pattern to convert Generic Linalg operations which work on tensors to use buffers. BufferPlacement pass should be later used to move Alloc operations to the correct positions and insert the missing Dealloc operations in the correct places.
Definition at line 114 of file Bufferize.cpp.
References getElementType().
maybeConvertToIndex()
static Value maybeConvertToIndex (Location loc, Value val, OpBuilder & b) static
Definition at line 24 of file Bufferize.cpp.
Referenced by allocateBuffersForResults().