MLIR: lib/Dialect/StandardOps/EDSC/Builders.cpp File Reference
Builders.cpp File Reference
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
Functions
static SmallVector< Value, 8 > getMemRefSizes (Value memRef)
Function Documentation
getMemRefSizes()
static SmallVector<Value, 8> getMemRefSizes (Value memRef) static
Definition at line 17 of file Builders.cpp.
References mlir::Type::cast(), mlir::MemRefType::getShape(), mlir::Value::getType(), and mlir::isStrided().
Referenced by mlir::edsc::MemRefBoundsCapture::MemRefBoundsCapture().