MLIR: lib/Dialect/SCF/EDSC/Builders.cpp File Reference
Builders.cpp File Reference
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
Functions
static std::function< void(OpBuilder &, Location)> wrapIfBody (function_ref< scf::ValueVector()> body, TypeRange expectedTypes)
static std::function< void(OpBuilder &, Location)> wrapZeroResultIfBody (function_ref< void()> body)
Function Documentation
wrapIfBody()
static std::function<void(OpBuilder &, Location)> wrapIfBody (function_ref< scf::ValueVector()> body, TypeRange expectedTypes) static
Definition at line 84 of file Builders.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::edsc::conditionBuilder().
wrapZeroResultIfBody()
static std::function<void(OpBuilder &, Location)> wrapZeroResultIfBody (function_ref< void()> body) static
Definition at line 112 of file Builders.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::edsc::conditionBuilder().