MLIR: lib/Dialect/Quant/IR/TypeParser.cpp File Reference
TypeParser.cpp File Reference
#include "mlir/Dialect/Quant/QuantOps.h"
#include "mlir/Dialect/Quant/QuantTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Types.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
Functions
static IntegerType parseStorageType (DialectAsmParser &parser, bool &isSigned)
static ParseResult parseStorageRange (DialectAsmParser &parser, IntegerType storageType, bool isSigned, int64_t &storageTypeMin, int64_t &storageTypeMax)
static FloatType parseExpressedTypeAndRange (DialectAsmParser &parser, double &min, double &max)
static Type parseAnyType (DialectAsmParser &parser, Location loc)
Parses an AnyQuantizedType.
static ParseResult parseQuantParams (DialectAsmParser &parser, double &scale, int64_t &zeroPoint)
static Type parseUniformType (DialectAsmParser &parser, Location loc)
Parses a UniformQuantizedType.
static Type parseCalibratedType (DialectAsmParser &parser, Location loc)
Parses an CalibratedQuantizedType.
static void printStorageType (QuantizedType type, DialectAsmPrinter &out)
static void printQuantParams (double scale, int64_t zeroPoint, DialectAsmPrinter &out)
static void printAnyQuantizedType (AnyQuantizedType type, DialectAsmPrinter &out)
Helper that prints a AnyQuantizedType.
static void printUniformQuantizedType (UniformQuantizedType type, DialectAsmPrinter &out)
Helper that prints a UniformQuantizedType.
static void printUniformQuantizedPerAxisType (UniformQuantizedPerAxisType type, DialectAsmPrinter &out)
Helper that prints a UniformQuantizedPerAxisType.
static void printCalibratedQuantizedType (CalibratedQuantizedType type, DialectAsmPrinter &out)
Helper that prints a CalibratedQuantizedType.
Function Documentation
parseAnyType()
static Type parseAnyType (DialectAsmParser & parser, Location loc) static
Parses an AnyQuantizedType.
any ::= any< storage-spec (expressed-type-spec)?> storage-spec ::= storage-type (< storage-range >)? storage-range ::= integer-literal : integer-literal storage-type ::= (i | u) integer-literal expressed-type-spec ::= : f integer-literal
Definition at line 120 of file TypeParser.cpp.
References mlir::quant::AnyQuantizedType::getChecked(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseLess(), mlir::DialectAsmParser::parseOptionalColon(), parseStorageRange(), parseStorageType(), mlir::DialectAsmParser::parseType(), mlir::quant::QuantizationFlags::Signed, and mlir::succeeded().
Referenced by parseCalibratedType().
parseCalibratedType()
static Type parseCalibratedType (DialectAsmParser & parser, Location loc) static
Parses an CalibratedQuantizedType.
calibrated ::= calibrated< expressed-spec > expressed-spec ::= expressed-type < calibrated-range > expressed-type ::= f integer-literal calibrated-range ::= float-literal : float-literal
Definition at line 297 of file TypeParser.cpp.
References mlir::DialectAsmParser::emitError(), mlir::failed(), mlir::quant::CalibratedQuantizedType::getChecked(), mlir::DialectAsmParser::getEncodedSourceLoc(), mlir::DialectAsmParser::getNameLoc(), parseAnyType(), parseExpressedTypeAndRange(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseKeyword(), mlir::DialectAsmParser::parseLess(), mlir::LLVM::detail::parseType(), and parseUniformType().
parseExpressedTypeAndRange()
static FloatType parseExpressedTypeAndRange (DialectAsmParser & parser, double & min, double & max) static
Definition at line 94 of file TypeParser.cpp.
References mlir::DialectAsmParser::emitError(), mlir::failed(), mlir::DialectAsmParser::getCurrentLocation(), mlir::DialectAsmParser::parseColon(), mlir::DialectAsmParser::parseFloat(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseLess(), and mlir::DialectAsmParser::parseType().
Referenced by parseCalibratedType().
parseQuantParams()
static ParseResult parseQuantParams (DialectAsmParser & parser, double & scale, int64_t & zeroPoint) static
Definition at line 162 of file TypeParser.cpp.
References mlir::failed(), mlir::failure(), mlir::DialectAsmParser::parseFloat(), mlir::DialectAsmParser::parseInteger(), mlir::DialectAsmParser::parseOptionalColon(), and mlir::success().
Referenced by parseUniformType().
parseStorageRange()
static ParseResult parseStorageRange (DialectAsmParser & parser, IntegerType storageType, bool isSigned, int64_t & storageTypeMin, int64_t & storageTypeMax) static
Definition at line 63 of file TypeParser.cpp.
References mlir::DialectAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::DialectAsmParser::getCurrentLocation(), mlir::quant::QuantizedType::getDefaultMaximumForInteger(), mlir::quant::QuantizedType::getDefaultMinimumForInteger(), mlir::IntegerType::getWidth(), mlir::DialectAsmParser::parseColon(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseInteger(), mlir::DialectAsmParser::parseOptionalLess(), and mlir::success().
Referenced by parseAnyType(), and parseUniformType().
parseStorageType()
static IntegerType parseStorageType (DialectAsmParser & parser, bool & isSigned) static
Definition at line 25 of file TypeParser.cpp.
References mlir::DialectAsmParser::emitError(), mlir::failed(), mlir::DialectAsmParser::getBuilder(), mlir::DialectAsmParser::getCurrentLocation(), mlir::Builder::getIntegerType(), mlir::IntegerType::getWidth(), mlir::quant::QuantizedType::MaxStorageBits, mlir::DialectAsmParser::parseOptionalKeyword(), and mlir::DialectAsmParser::parseType().
Referenced by parseAnyType(), and parseUniformType().
parseUniformType()
static Type parseUniformType (DialectAsmParser & parser, Location loc) static
Parses a UniformQuantizedType.
uniform_type ::= uniform_per_layer | uniform_per_axis uniform_per_layer ::= uniform< storage-spec expressed-type-spec , scale-zero > uniform_per_axis ::= uniform< storage-spec expressed-type-spec axis-spec , scale-zero-list > storage-spec ::= storage-type (< storage-range >)? storage-range ::= integer-literal : integer-literal storage-type ::= (i | u) integer-literal expressed-type-spec ::= : f integer-literal axis-spec ::= : integer-literal scale-zero ::= float-literal : integer-literal scale-zero-list ::= { scale-zero (, scale-zero)* }
Definition at line 194 of file TypeParser.cpp.
References mlir::DialectAsmParser::emitError(), mlir::quant::UniformQuantizedType::getChecked(), mlir::quant::UniformQuantizedPerAxisType::getChecked(), mlir::DialectAsmParser::getCurrentLocation(), mlir::DialectAsmParser::parseColon(), mlir::DialectAsmParser::parseComma(), mlir::DialectAsmParser::parseGreater(), mlir::DialectAsmParser::parseInteger(), mlir::DialectAsmParser::parseLBrace(), mlir::DialectAsmParser::parseLess(), mlir::DialectAsmParser::parseOptionalColon(), mlir::DialectAsmParser::parseOptionalComma(), parseQuantParams(), mlir::DialectAsmParser::parseRBrace(), parseStorageRange(), parseStorageType(), mlir::DialectAsmParser::parseType(), mlir::quant::QuantizationFlags::Signed, and mlir::succeeded().
Referenced by parseCalibratedType().
printAnyQuantizedType()
static void printAnyQuantizedType (AnyQuantizedType type, DialectAsmPrinter & out) static
Helper that prints a AnyQuantizedType.
Definition at line 371 of file TypeParser.cpp.
References printStorageType().
Referenced by printCalibratedQuantizedType().
printCalibratedQuantizedType()
static void printCalibratedQuantizedType (CalibratedQuantizedType type, DialectAsmPrinter & out) static
Helper that prints a CalibratedQuantizedType.
Definition at line 416 of file TypeParser.cpp.
References mlir::Type::dyn_cast(), mlir::quant::CalibratedQuantizedType::getMax(), mlir::quant::CalibratedQuantizedType::getMin(), printAnyQuantizedType(), mlir::LLVM::detail::printType(), printUniformQuantizedPerAxisType(), and printUniformQuantizedType().
printQuantParams()
static void printQuantParams (double scale, int64_t zeroPoint, DialectAsmPrinter & out) static
Definition at line 362 of file TypeParser.cpp.
Referenced by printUniformQuantizedPerAxisType(), and printUniformQuantizedType().
printStorageType()
static void printStorageType (QuantizedType type, DialectAsmPrinter & out) static
Definition at line 340 of file TypeParser.cpp.
References mlir::quant::QuantizedType::getDefaultMaximumForInteger(), mlir::quant::QuantizedType::getDefaultMinimumForInteger(), mlir::quant::QuantizedType::getStorageTypeIntegralWidth(), mlir::quant::QuantizedType::getStorageTypeMax(), mlir::quant::QuantizedType::getStorageTypeMin(), and mlir::quant::QuantizedType::isSigned().
Referenced by printAnyQuantizedType(), printUniformQuantizedPerAxisType(), and printUniformQuantizedType().
printUniformQuantizedPerAxisType()
static void printUniformQuantizedPerAxisType (UniformQuantizedPerAxisType type, DialectAsmPrinter & out) static
Helper that prints a UniformQuantizedPerAxisType.
Definition at line 394 of file TypeParser.cpp.
References mlir::quant::UniformQuantizedPerAxisType::getQuantizedDimension(), mlir::quant::UniformQuantizedPerAxisType::getScales(), mlir::quant::UniformQuantizedPerAxisType::getZeroPoints(), printQuantParams(), and printStorageType().
Referenced by printCalibratedQuantizedType().
printUniformQuantizedType()
static void printUniformQuantizedType (UniformQuantizedType type, DialectAsmPrinter & out) static
Helper that prints a UniformQuantizedType.
Definition at line 382 of file TypeParser.cpp.
References mlir::quant::UniformQuantizedType::getScale(), mlir::quant::UniformQuantizedType::getZeroPoint(), printQuantParams(), and printStorageType().
Referenced by printCalibratedQuantizedType().