MLIR: lib/IR/Dominance.cpp File Reference
Dominance.cpp File Reference
#include "mlir/IR/Dominance.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/RegionKindInterface.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/GenericDomTreeConstruction.h"
Functions
static bool hasSSADominance (Operation *op, unsigned index)
Return true if the region with the given index inside the operation has SSA dominance.
template<typename FuncT >
Block * traverseAncestors (Block *block, const FuncT &func)
Walks up the list of containers of the given block and calls the user-defined traversal function for every pair of a region and block that could be found during traversal.
static bool tryGetBlocksInSameRegion (Block *&a, Block *&b)
Tries to update the given block references to live in the same region by exploring the relationship of both blocks with respect to their regions.
Function Documentation
hasSSADominance()
static bool hasSSADominance (Operation * op, unsigned index) static
Return true if the region with the given index inside the operation has SSA dominance.
Definition at line 29 of file Dominance.cpp.
References mlir::Operation::isRegistered().
Referenced by mlir::DominanceInfo::properlyDominates(), mlir::PostDominanceInfo::properlyPostDominates(), and mlir::detail::DominanceInfoBase< true >::recalculate().
traverseAncestors()
template<typename FuncT > Block* traverseAncestors (Block * block, const FuncT & func)
Walks up the list of containers of the given block and calls the user-defined traversal function for every pair of a region and block that could be found during traversal.
If the user-defined function returns true for a given pair, traverseAncestors will return the current block. Nullptr otherwise.
Definition at line 77 of file Dominance.cpp.
References mlir::Operation::getBlock(), mlir::Block::getParent(), and mlir::Region::getParentOp().
Referenced by mlir::detail::DominanceInfoBase< true >::properlyDominates(), and tryGetBlocksInSameRegion().
tryGetBlocksInSameRegion()
static bool tryGetBlocksInSameRegion (Block *& a, Block *& b) static
Tries to update the given block references to live in the same region by exploring the relationship of both blocks with respect to their regions.
Definition at line 103 of file Dominance.cpp.
References mlir::Block::getParent(), and traverseAncestors().
Referenced by mlir::detail::DominanceInfoBase< true >::findNearestCommonDominator().