MLIR: lib/Rewrite/FrozenRewritePatternList.cpp File Reference
FrozenRewritePatternList.cpp File Reference
#include "mlir/Rewrite/FrozenRewritePatternList.h"
#include "ByteCode.h"
#include "mlir/Conversion/PDLToPDLInterp/PDLToPDLInterp.h"
#include "mlir/Dialect/PDL/IR/PDL.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Pass/PassManager.h"
Functions
static LogicalResult convertPDLToPDLInterp (ModuleOp pdlModule)
Function Documentation
convertPDLToPDLInterp()
static LogicalResult convertPDLToPDLInterp (ModuleOp pdlModule) static
Lower the PDL pattern module to the interpreter dialect.
Definition at line 19 of file FrozenRewritePatternList.cpp.
References mlir::createPDLToPDLInterpPass(), mlir::PassManager::enableVerifier(), mlir::failed(), mlir::failure(), mlir::isOpTriviallyDead(), and mlir::success().
Referenced by mlir::FrozenRewritePatternList::FrozenRewritePatternList().