MLIR: lib/Dialect/Linalg/Transforms/Fusion.cpp File Reference
Fusion.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Dominance.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include <set>
Classes
struct ShapeDimension
Macros
#define DEBUG_TYPE "linalg-fusion"
Functions
static void inferShapeComponents (AffineMap permutationMap, ArrayRef< Range > loopRanges, SmallVectorImpl< Value > &offsets, SmallVectorImpl< Value > &sizes, SmallVectorImpl< Value > &strides)
Implements a simple high-level fusion pass on linalg structured operations.
static LinalgOp cloneWithLoopRanges (OpBuilder &b, Location loc, LinalgOp op, ArrayRef< Range > loopRanges)
static ShapeDimension getShapeDefiningLoopRange (LinalgOp op, unsigned loopDepth, bool fromSubViewOpOnly=false)
static LinalgOp fuse (OpBuilder &b, LinalgOp producer, const DenseMap< unsigned, Range > &fusedLoopsAndRanges)
Fuse the producer by cloning the producer.
static Range getRangeFromOperandShape (OpBuilder &b, Location loc, Value shapedOperand, unsigned dim)
Get the loop range for a dimension dim based on the shapedOperand.
static LinalgOp fuse (OpBuilder &b, LinalgOp producer, unsigned producerIdx, LinalgOp consumer, unsigned consumerIdx)
Fuses the producer of producerIdx into the loop immediately enclosing consumer.
static bool isStructurallyFusableProducer (LinalgOp producer, Value consumedView, LinalgOp consumer)
static bool isSameSubView (Value a, Value b)
static Optional< LinalgDependenceGraph::LinalgDependenceGraphElem > findFusableProducer (LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph &dependenceGraph)
static void getProducerOfTensor (Value tensor, LinalgOp &producer, unsigned &outputIndex)
Walk back use-def chain through scf::For yields.
static AffineMap pruneReductionDimsFromMap (ArrayRef< Attribute > iteratorTypes, AffineMap map)
Prune all dimensions that are of reduction iterator type from map.
static Optional< AffineMap > getConsumerLoopToProducerLoopMap (LinalgDependenceGraph::LinalgDependenceGraphElem dependence)
Returns the mapping from iterations in the consumer that write to the same location as the iterations in the producer.
static bool doesTransposeAccess (AffineMap map, const std::set< unsigned > &fusableLoops)
Given a projected permutation map, returns true if the map changes the order in which the fused loop dimension appear.
static std::set< unsigned > collectFusableLoops (ArrayRef< LinalgOp > ops, const FusableOpDependencesTy &fusableDependences)
Returns the positions of the loop in op that can be tiled based on the operations that are to be fused with it.
static Optional< TiledLinalgOp > tileRootOperation (OpBuilder &builder, LinalgOp op, ArrayRef< Value > tileSizeVector, const LinalgTilingOptions &options, const std::set< unsigned > &fusedLoops)
Tile the fused loops in the root operation, by setting the tile sizes for all other loops to zero (those will be tiled later).
static SmallVector< LinalgOp, 1 > fuseOperations (OpBuilder &builder, LinalgOp tiledOp, ArrayRef< LinalgOp > fusionCandidates, const FusableOpDependencesTy &fusableDependences, const std::set< unsigned > &fusedLoops)
Fuse the operations in fusionCandidates with tiledOp.
template<typename LoopType >
static Optional< TiledAndFusedLinalgOps > tileAndFuseLinalgOpsImpl (OpBuilder &builder, ArrayRef< LinalgOp > ops, const LinalgDependenceGraph &dependenceGraph, const LinalgTilingOptions &tilingOptions)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-fusion"
Definition at line 33 of file Fusion.cpp.
Function Documentation
cloneWithLoopRanges()
static LinalgOp cloneWithLoopRanges (OpBuilder & b, Location loc, LinalgOp op, ArrayRef< Range > loopRanges) static
Definition at line 90 of file Fusion.cpp.
References mlir::Operation::clone(), mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::Value::getType(), inferShapeComponents(), mlir::Type::isa(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::Value::replaceAllUsesExcept(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by fuse().
collectFusableLoops()
static std::set<unsigned> collectFusableLoops (ArrayRef< LinalgOp > ops, const FusableOpDependencesTy & fusableDependences) static
Returns the positions of the loop in op that can be tiled based on the operations that are to be fused with it.
For example, in a
linalg.matmul ins(a, b : ...) outs(c : ...)
if the producer of a needs to be fused with this op, only the i loop of the matmul can be tiled while fusing. If producer of a, and b are to be fused, then no loops can be tiled while fusing. The conditions used are:
Only parallel loops can be used for tile + fuse. Find the number of common outer parallel loops between the op and its producers being fused.
Of the parallel loops only some can be fused. Only those loops can be fused such where the fusable loops iteration space only touches one tile of the fused operation. This is because the producer (which is writing the fused subview) has update semantics.
Since an inverse computation is needed, we need to consider the projection of the producerIndexMap w.r.t the parallel loops. The actual fusable loops are the dimensions of the consumerLoopToProducerLoop map that correspond to parallel loops and appear in the result of the map
Example 1: linalg.fill(c, cst) linalg.matmul ins(a, b) outs(c) Number of parallel loops : 2 producerIndexMap = affine_map<(i, j) ->(i , j)> consumerIndexMap = affine_map<(i, j, k) -> (i, j)> consumerLoopToProducerLoop = affine_map<(i, j, k) -> (i, j)> Fused dimensions : i, j
Example 2: linalg.matmul ins(a, b) outs(c) linalg.generic {indexing_maps = [affine_map<(i, j) -> (j, i)>, ... iterator_types = ["parallel", "parallel"]} ins(c) ...
Number of parallel loops = 2: producerIndexMap (projected to parallel loops) = affine_map<(i, j) -> (i, j)> consumerLoopToProducerLoop2 = affine_map<(i, j) -> (j, i)> Fused dimensions : i, j
Example 3: linalg.copy(s, b) linalg.matmul ins(a, b) outs(c)
Number of parallel loops = 2 produceIndexMap : affine_map<(i, j) -> (i, j)> consumerLoopToProduceLoops = affine_map<(i, j, k) -> (k, j)> submap with only parallel loops = affine_map<(i, j) -> (j)> Fused dimensions : j
Definition at line 656 of file Fusion.cpp.
References mlir::Attribute::cast(), doesTransposeAccess(), getConsumerLoopToProducerLoopMap(), and mlir::getParallelIteratorTypeName().
Referenced by tileAndFuseLinalgOpsImpl().
doesTransposeAccess()
static bool doesTransposeAccess (AffineMap map, const std::set< unsigned > & fusableLoops) static
Given a projected permutation map, returns true if the map changes the order in which the fused loop dimension appear.
Definition at line 586 of file Fusion.cpp.
References mlir::AffineMap::getResults().
Referenced by collectFusableLoops().
findFusableProducer()
static Optional<LinalgDependenceGraph::LinalgDependenceGraphElem> findFusableProducer (LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph & dependenceGraph) static
Definition at line 381 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::getDependencesInto(), mlir::linalg::isFusableInto(), and isSameSubView().
Referenced by mlir::linalg::findAllFusableDependences(), and mlir::linalg::fuseProducerOfBuffer().
fuse() [1/2]
static LinalgOp fuse (OpBuilder & b, LinalgOp producer, const DenseMap< unsigned, Range > & fusedLoopsAndRanges) static
Fuse the producer by cloning the producer.
The fusedLoopsAndRanges provides the loop range information for the fused loops. The rest are obtained from the producer itself, since they are not tiled + fused.
Definition at line 210 of file Fusion.cpp.
References cloneWithLoopRanges(), and getShapeDefiningLoopRange().
Referenced by fuse(), fuseOperations(), mlir::linalg::fuseProducerOfBuffer(), and mlir::linalg::fuseProducerOfTensor().
fuse() [2/2]
static LinalgOp fuse (OpBuilder & b, LinalgOp producer, unsigned producerIdx, LinalgOp consumer, unsigned consumerIdx) static
Fuses the producer of producerIdx into the loop immediately enclosing consumer.
This is achieved by "recomputing" the producer at the time it is needed just before the `consumer.
Depending on the type of consumer.getShapedOperand(consumerIdx), there are 2 cases:
Buffer case: producerIdx is the index of the buffer in producer.getOutputBuffers().
Tensor case: producerIdx is the index of the tensor in producer.getResults().
Definition at line 261 of file Fusion.cpp.
References mlir::Value::cast(), mlir::detail::enumerate(), fuse(), getRangeFromOperandShape(), and mlir::AffineMap::getResults().
fuseOperations()
static SmallVector<LinalgOp, 1> fuseOperations (OpBuilder & builder, LinalgOp tiledOp, ArrayRef< LinalgOp > fusionCandidates, const FusableOpDependencesTy & fusableDependences, const std::set< unsigned > & fusedLoops) static
Fuse the operations in fusionCandidates with tiledOp.
Latter is expected to be a tiled operation such that it is valid to fuse all operations in fusionCandidates, i.e. move the operation within the inter-tile loops of tiledOp.
Definition at line 812 of file Fusion.cpp.
References ShapeDimension::dimension, mlir::detail::enumerate(), fuse(), getRangeFromOperandShape(), getShapeDefiningLoopRange(), mlir::OpBuilder::setInsertionPoint(), and ShapeDimension::shape.
Referenced by tileAndFuseLinalgOpsImpl().
getConsumerLoopToProducerLoopMap()
static Optional<AffineMap> getConsumerLoopToProducerLoopMap (LinalgDependenceGraph::LinalgDependenceGraphElem dependence) static
Returns the mapping from iterations in the consumer that write to the same location as the iterations in the producer.
To do so use
indexing map of the fused view in the consumer : consumerIndexMap
indexing map of the fused view in the producer : producerIndexMap consumerLoopToProducerLoop = inverse(producerIndexMap).compose(consumerIndexMap)
Definition at line 548 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::dependentOpView, mlir::AffineMap::getNumResults(), mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraphElem::indexingOpView, mlir::inversePermutation(), mlir::AffineMap::isPermutation(), mlir::linalg::LinalgDependenceGraph::LinalgOpView::op, mlir::linalg::LinalgDependenceGraph::LinalgOpView::operandIndex, mlir::AffineMap::print(), and pruneReductionDimsFromMap().
Referenced by collectFusableLoops().
getProducerOfTensor()
static void getProducerOfTensor (Value tensor, LinalgOp & producer, unsigned & outputIndex) static
Walk back use-def chain through scf::For yields.
Sets producer and outputIndex if it finds a producer LinalgOp
Definition at line 465 of file Fusion.cpp.
References mlir::Value::cast(), mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::Value::getType(), and mlir::Type::isa().
Referenced by mlir::linalg::fuseProducerOfTensor().
getRangeFromOperandShape()
static Range getRangeFromOperandShape (OpBuilder & b, Location loc, Value shapedOperand, unsigned dim) static
Get the loop range for a dimension dim based on the shapedOperand.
It is expected to be defined by a subview op or a subtensor op.
Definition at line 241 of file Fusion.cpp.
References mlir::Value::getDefiningOp().
Referenced by fuse(), and fuseOperations().
getShapeDefiningLoopRange()
static ShapeDimension getShapeDefiningLoopRange (LinalgOp op, unsigned loopDepth, bool fromSubViewOpOnly = false) static
Definition at line 166 of file Fusion.cpp.
References mlir::Value::dyn_cast(), and mlir::detail::enumerate().
Referenced by fuse(), and fuseOperations().
inferShapeComponents()
static void inferShapeComponents (AffineMap permutationMap, ArrayRef< Range > loopRanges, SmallVectorImpl< Value > & offsets, SmallVectorImpl< Value > & sizes, SmallVectorImpl< Value > & strides) static
Implements a simple high-level fusion pass on linalg structured operations.
In each block, linalg ops are processed in reverse textual order. Given a linalg op O, fusion occurs by:
inspecting the linalg ops that write into the views read by O. There are 2 cases: a) buffer case: use the SSA value of the views and a simple alias analysis on subview ops to determine producer-consumer dependences; b) tensor case: use SSA use-def chains on subtensor ops;
greedily fuse the linalg ops that produce the subview/subtensor.
inspect the fused ops and determine whether they have other remaining LinalgOp uses. If not, then erase the original producing linalg op.
More advanced use cases, analyses as well as profitability heuristics are left for future work.
Definition at line 60 of file Fusion.cpp.
References mlir::AffineMap::getNumResults(), mlir::AffineMap::getResults(), and mlir::AffineMap::isProjectedPermutation().
Referenced by cloneWithLoopRanges().
isSameSubView()
static bool isSameSubView (Value a, Value b) static
Skip the "source" operand.
Definition at line 354 of file Fusion.cpp.
References mlir::Value::getDefiningOp().
Referenced by findFusableProducer().
isStructurallyFusableProducer()
static bool isStructurallyFusableProducer (LinalgOp producer, Value consumedView, LinalgOp consumer) static
Definition at line 279 of file Fusion.cpp.
Referenced by mlir::linalg::isProducerLastWriteOfView().
pruneReductionDimsFromMap()
static AffineMap pruneReductionDimsFromMap (ArrayRef< Attribute > iteratorTypes, AffineMap map) static
Prune all dimensions that are of reduction iterator type from map.
Definition at line 532 of file Fusion.cpp.
References mlir::detail::enumerate(), mlir::getProjectedMap(), and mlir::isParallelIterator().
Referenced by getConsumerLoopToProducerLoopMap().
tileAndFuseLinalgOpsImpl()
template<typename LoopType > static Optional<TiledAndFusedLinalgOps> tileAndFuseLinalgOpsImpl (OpBuilder & builder, ArrayRef< LinalgOp > ops, const LinalgDependenceGraph & dependenceGraph, const LinalgTilingOptions & tilingOptions) static
Definition at line 836 of file Fusion.cpp.
References collectFusableLoops(), mlir::detail::enumerate(), mlir::linalg::findAllFusableDependences(), mlir::linalg::TiledAndFusedLinalgOps::fusedLoopDims, mlir::linalg::TiledAndFusedLinalgOps::fusedLoops, mlir::linalg::TiledAndFusedLinalgOps::fusedProducers, fuseOperations(), mlir::linalg::LinalgTilingOptions::interchangeVector, mlir::linalg::TiledAndFusedLinalgOps::op, mlir::OpBuilder::setInsertionPoint(), tileRootOperation(), and mlir::linalg::LinalgTilingOptions::tileSizeComputationFunction.
tileRootOperation()
static Optional<TiledLinalgOp> tileRootOperation (OpBuilder & builder, LinalgOp op, ArrayRef< Value > tileSizeVector, const LinalgTilingOptions & options, const std::set< unsigned > & fusedLoops) static
Tile the fused loops in the root operation, by setting the tile sizes for all other loops to zero (those will be tiled later).
Definition at line 794 of file Fusion.cpp.
References options, mlir::linalg::LinalgTilingOptions::setTileSizes(), and mlir::linalg::tileLinalgOp().
Referenced by tileAndFuseLinalgOpsImpl().