MLIR: include/mlir-c/Pass.h File Reference
Pass.h File Reference
#include "mlir-c/IR.h"
#include "mlir-c/Support.h"
Macros
#define DEFINE_C_API_STRUCT(name, storage)
Opaque type declarations.
Functions
DEFINE_C_API_STRUCT (MlirPass, void)
DEFINE_C_API_STRUCT (MlirPassManager, void)
DEFINE_C_API_STRUCT (MlirOpPassManager, void)
MLIR_CAPI_EXPORTED MlirPassManager mlirPassManagerCreate (MlirContext ctx)
Create a new top-level PassManager.
MLIR_CAPI_EXPORTED void mlirPassManagerDestroy (MlirPassManager passManager)
Destroy the provided PassManager.
static bool mlirPassManagerIsNull (MlirPassManager passManager)
Checks if a PassManager is null.
MLIR_CAPI_EXPORTED MlirOpPassManager mlirPassManagerGetAsOpPassManager (MlirPassManager passManager)
Cast a top-level PassManager to a generic OpPassManager.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirPassManagerRun (MlirPassManager passManager, MlirModule module)
Run the provided passManager on the given module.
MLIR_CAPI_EXPORTED MlirOpPassManager mlirPassManagerGetNestedUnder (MlirPassManager passManager, MlirStringRef operationName)
Nest an OpPassManager under the top-level PassManager, the nested passmanager will only run on operations matching the provided name.
MLIR_CAPI_EXPORTED MlirOpPassManager mlirOpPassManagerGetNestedUnder (MlirOpPassManager passManager, MlirStringRef operationName)
Nest an OpPassManager under the provided OpPassManager, the nested passmanager will only run on operations matching the provided name.
MLIR_CAPI_EXPORTED void mlirPassManagerAddOwnedPass (MlirPassManager passManager, MlirPass pass)
Add a pass and transfer ownership to the provided top-level mlirPassManager.
MLIR_CAPI_EXPORTED void mlirOpPassManagerAddOwnedPass (MlirOpPassManager passManager, MlirPass pass)
Add a pass and transfer ownership to the provided mlirOpPassManager.
MLIR_CAPI_EXPORTED void mlirPrintPassPipeline (MlirOpPassManager passManager, MlirStringCallback callback, void *userData)
Print a textual MLIR pass pipeline by sending chunks of the string representation and forwarding userData tocallback`.
MLIR_CAPI_EXPORTED MlirLogicalResult mlirParsePassPipeline (MlirOpPassManager passManager, MlirStringRef pipeline)
Parse a textual MLIR pass pipeline and add it to the provided OpPassManager.
Macro Definition Documentation
DEFINE_C_API_STRUCT
#define DEFINE_C_API_STRUCT (name, storage)
Value:
struct name {                                                                \
    storage *ptr;                                                              \
  };                                                                           \
  typedef struct name name
Opaque type declarations.
Types are exposed to C bindings as structs containing opaque pointers. They are not supposed to be inspected from C. This allows the underlying representation to change without affecting the API users. The use of structs instead of typedefs enables some type safety as structs are not implicitly convertible to each other.
Instances of these types may or may not own the underlying object. The ownership semantics is defined by how an instance of the type was obtained.
Definition at line 38 of file Pass.h.
Function Documentation
DEFINE_C_API_STRUCT() [1/3]
DEFINE_C_API_STRUCT (MlirPass , void)
DEFINE_C_API_STRUCT() [2/3]
DEFINE_C_API_STRUCT (MlirPassManager , void)
DEFINE_C_API_STRUCT() [3/3]
DEFINE_C_API_STRUCT (MlirOpPassManager , void)
mlirOpPassManagerAddOwnedPass()
MLIR_CAPI_EXPORTED void mlirOpPassManagerAddOwnedPass (MlirOpPassManager passManager, MlirPass pass)
Add a pass and transfer ownership to the provided mlirOpPassManager.
If the pass is not a generic operation pass or matching the type of the provided PassManager, a new OpPassManager is implicitly nested under the provided PassManager.
Definition at line 55 of file Pass.cpp.
References unwrap().
Referenced by mlirPassManagerIsNull().
mlirOpPassManagerGetNestedUnder()
MLIR_CAPI_EXPORTED MlirOpPassManager mlirOpPassManagerGetNestedUnder (MlirOpPassManager passManager, MlirStringRef operationName)
Nest an OpPassManager under the provided OpPassManager, the nested passmanager will only run on operations matching the provided name.
The returned OpPassManager will be destroyed when the parent is destroyed.
Definition at line 46 of file Pass.cpp.
References unwrap(), and wrap().
Referenced by mlirPassManagerIsNull().
mlirParsePassPipeline()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirParsePassPipeline (MlirOpPassManager passManager, MlirStringRef pipeline)
Parse a textual MLIR pass pipeline and add it to the provided OpPassManager.
Definition at line 66 of file Pass.cpp.
References mlir::parsePassPipeline(), unwrap(), and wrap().
Referenced by mlirPassManagerIsNull().
mlirPassManagerAddOwnedPass()
MLIR_CAPI_EXPORTED void mlirPassManagerAddOwnedPass (MlirPassManager passManager, MlirPass pass)
Add a pass and transfer ownership to the provided top-level mlirPassManager.
If the pass is not a generic operation pass or a ModulePass, a new OpPassManager is implicitly nested under the provided PassManager.
Definition at line 51 of file Pass.cpp.
References unwrap().
Referenced by mlirPassManagerIsNull().
mlirPassManagerCreate()
MLIR_CAPI_EXPORTED MlirPassManager mlirPassManagerCreate (MlirContext ctx)
Create a new top-level PassManager.
Definition at line 23 of file Pass.cpp.
References unwrap(), and wrap().
mlirPassManagerDestroy()
MLIR_CAPI_EXPORTED void mlirPassManagerDestroy (MlirPassManager passManager)
Destroy the provided PassManager.
Definition at line 27 of file Pass.cpp.
References unwrap().
mlirPassManagerGetAsOpPassManager()
MLIR_CAPI_EXPORTED MlirOpPassManager mlirPassManagerGetAsOpPassManager (MlirPassManager passManager)
Cast a top-level PassManager to a generic OpPassManager.
Definition at line 32 of file Pass.cpp.
References unwrap(), and wrap().
Referenced by mlirPassManagerIsNull().
mlirPassManagerGetNestedUnder()
MLIR_CAPI_EXPORTED MlirOpPassManager mlirPassManagerGetNestedUnder (MlirPassManager passManager, MlirStringRef operationName)
Nest an OpPassManager under the top-level PassManager, the nested passmanager will only run on operations matching the provided name.
The returned OpPassManager will be destroyed when the parent is destroyed. To further nest more OpPassManager under the newly returned one, see mlirOpPassManagerNest below.
Definition at line 41 of file Pass.cpp.
References unwrap(), and wrap().
Referenced by mlirPassManagerIsNull().
mlirPassManagerIsNull()
static bool mlirPassManagerIsNull (MlirPassManager passManager) inline static
Checks if a PassManager is null.
Definition at line 57 of file Pass.h.
References MLIR_CAPI_EXPORTED, mlirOpPassManagerAddOwnedPass(), mlirOpPassManagerGetNestedUnder(), mlirParsePassPipeline(), mlirPassManagerAddOwnedPass(), mlirPassManagerGetAsOpPassManager(), mlirPassManagerGetNestedUnder(), mlirPassManagerRun(), and mlirPrintPassPipeline().
mlirPassManagerRun()
MLIR_CAPI_EXPORTED MlirLogicalResult mlirPassManagerRun (MlirPassManager passManager, MlirModule module)
Run the provided passManager on the given module.
Definition at line 36 of file Pass.cpp.
References unwrap(), and wrap().
Referenced by mlirPassManagerIsNull().
mlirPrintPassPipeline()
MLIR_CAPI_EXPORTED void mlirPrintPassPipeline (MlirOpPassManager passManager, MlirStringCallback callback, void * userData)
Print a textual MLIR pass pipeline by sending chunks of the string representation and forwarding userData tocallback`.
Note that the callback may be called several times with consecutive chunks of the string.
Definition at line 60 of file Pass.cpp.
References unwrap().
Referenced by mlirPassManagerIsNull().