MLIR: lib/IR/BuiltinTypes.cpp File Reference
BuiltinTypes.cpp File Reference
#include "mlir/IR/BuiltinTypes.h"
#include "TypeDetail.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/Twine.h"
#include "mlir/IR/BuiltinTypes.cpp.inc"
Macros
#define GET_TYPEDEF_CLASSES
Tablegen Type Definitions.
Functions
void iterateIndicesExcept (unsigned totalIndices, ArrayRef< unsigned > indices, function_ref< void(unsigned)> callback)
Helper to call a callback once on each index in the range [0, totalIndices), except for the indices given in indices.
static LogicalResult checkTensorElementType (Location location, Type elementType)
static void extractStridesFromTerm (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr &offset)
static LogicalResult extractStrides (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr &offset)
Takes a single AffineExpr e and populates the strides array with the strides expressions for each dim position.
Macro Definition Documentation
GET_TYPEDEF_CLASSES
#define GET_TYPEDEF_CLASSES
Tablegen Type Definitions.
Definition at line 27 of file BuiltinTypes.cpp.
Function Documentation
checkTensorElementType()
static LogicalResult checkTensorElementType (Location location, Type elementType) static
Definition at line 356 of file BuiltinTypes.cpp.
References mlir::emitError(), mlir::TensorType::isValidElementType(), and mlir::success().
Referenced by mlir::RankedTensorType::verifyConstructionInvariants(), and mlir::UnrankedTensorType::verifyConstructionInvariants().
extractStrides()
static LogicalResult extractStrides (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr & offset) static
Takes a single AffineExpr e and populates the strides array with the strides expressions for each dim position.
The convention is that the strides for dimensions d0, .. dn appear in order to make indexing intuitive into the result.
Definition at line 558 of file BuiltinTypes.cpp.
References mlir::Add, mlir::CeilDiv, mlir::AffineExpr::dyn_cast(), extractStridesFromTerm(), mlir::failure(), mlir::FloorDiv, mlir::Mod, mlir::Mul, mlir::succeeded(), and mlir::success().
Referenced by foldExtractStridedOpFromInsertChain(), and mlir::getStridesAndOffset().
extractStridesFromTerm()
static void extractStridesFromTerm (AffineExpr e, AffineExpr multiplicativeFactor, MutableArrayRef< AffineExpr > strides, AffineExpr & offset) static
Definition at line 543 of file BuiltinTypes.cpp.
References mlir::AffineExpr::dyn_cast().
Referenced by extractStrides().
iterateIndicesExcept()
void iterateIndicesExcept (unsigned totalIndices, ArrayRef< unsigned > indices, function_ref< void(unsigned)> callback) inline
Helper to call a callback once on each index in the range [0, totalIndices), except for the indices given in indices.
indices is allowed to have duplicates and can be in any order.
Definition at line 149 of file BuiltinTypes.cpp.
Referenced by mlir::FunctionType::getWithoutArgsAndResults().