MLIR: lib/IR/AffineMap.cpp File Reference
AffineMap.cpp File Reference
#include "mlir/IR/AffineMap.h"
#include "AffineMapDetail.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"
Functions
template<typename AffineExprContainer >
static void getMaxDimAndSymbol (ArrayRef< AffineExprContainer > exprsList, int64_t &maxDim, int64_t &maxSym)
template<typename AffineExprContainer >
static SmallVector< AffineMap, 4 > inferFromExprList (ArrayRef< AffineExprContainer > exprsList)
Function Documentation
getMaxDimAndSymbol()
template<typename AffineExprContainer > static void getMaxDimAndSymbol (ArrayRef< AffineExprContainer > exprsList, int64_t & maxDim, int64_t & maxSym) static
Definition at line 128 of file AffineMap.cpp.
References mlir::AffineExpr::dyn_cast(), and mlir::AffineExpr::walk().
Referenced by inferFromExprList().
inferFromExprList()
template<typename AffineExprContainer > static SmallVector<AffineMap, 4> inferFromExprList (ArrayRef< AffineExprContainer > exprsList) static
Definition at line 144 of file AffineMap.cpp.
References mlir::AffineMap::get(), and getMaxDimAndSymbol().
Referenced by mlir::AffineMap::AffineMap(), and mlir::AffineMap::inferFromExprList().