MLIR: lib/Bindings/Python/IRModules.cpp File Reference
IRModules.cpp File Reference
#include "IRModules.h"
#include "Globals.h"
#include "PybindUtils.h"
#include "mlir-c/Bindings/Python/Interop.h"
#include "mlir-c/BuiltinAttributes.h"
#include "mlir-c/BuiltinTypes.h"
#include "mlir-c/Registration.h"
#include "llvm/ADT/SmallVector.h"
#include <pybind11/stl.h>
Functions
static int mlirTypeIsAIntegerOrFloat (MlirType type)
Checks whether the given type is an integer or float type.
static py::object createCustomDialectWrapper (const std::string &dialectNamespace, py::object dialectDescriptor)
static MlirStringRef toMlirStringRef (const std::string &s)
Variables
static const char kContextParseTypeDocstring []
static const char kContextGetFileLocationDocstring []
static const char kModuleParseDocstring []
static const char kOperationCreateDocstring []
static const char kOperationPrintDocstring []
static const char kOperationGetAsmDocstring []
static const char kOperationStrDunderDocstring []
static const char kDumpDocstring []
static const char kAppendBlockDocstring []
static const char kValueDunderStrDocstring []
Function Documentation
createCustomDialectWrapper()
static py::object createCustomDialectWrapper (const std::string & dialectNamespace, py::object dialectDescriptor) static
Definition at line 139 of file IRModules.cpp.
References mlir::python::PyGlobals::get(), and mlir::python::PyGlobals::lookupDialectClass().
Referenced by mlir::python::PyType::createFromCapsule().
mlirTypeIsAIntegerOrFloat()
static int mlirTypeIsAIntegerOrFloat (MlirType type) static
Checks whether the given type is an integer or float type.
Definition at line 133 of file IRModules.cpp.
References mlirTypeIsABF16(), mlirTypeIsAF16(), mlirTypeIsAF32(), mlirTypeIsAF64(), and mlirTypeIsAInteger().
Referenced by mlir::python::PyType::createFromCapsule().
toMlirStringRef()
static MlirStringRef toMlirStringRef (const std::string & s) static
Definition at line 151 of file IRModules.cpp.
References mlir::python::PyOperation::forOperation(), mlir::python::PyObjectRef< T >::get(), kAppendBlockDocstring, mlirBlockCreate(), mlirBlockGetFirstOperation(), mlirBlockGetNextInRegion(), mlirBlockIsNull(), mlirOperationGetNextInBlock(), mlirOperationGetNumRegions(), mlirOperationGetRegion(), mlirOperationIsNull(), mlirRegionAppendOwnedBlock(), mlirRegionGetFirstBlock(), mlirStringRefCreate(), mlir::python::PyMlirContext::PyMlirContext(), and mlir::python::SetPyError().
Referenced by mlir::python::PyOperation::create(), mlir::python::PyType::createFromCapsule(), and mlir::python::PyNamedAttribute::PyNamedAttribute().
Variable Documentation
kAppendBlockDocstring
const char kAppendBlockDocstring[] static
Initial value:
=
    R"(Appends a new block, with argument types as positional args.
Returns:
  The created block.
)"
Definition at line 113 of file IRModules.cpp.
Referenced by toMlirStringRef().
kContextGetFileLocationDocstring
const char kContextGetFileLocationDocstring[] static
Initial value:
=
    R"(Gets a Location representing a file, line and column)"
Definition at line 41 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().
kContextParseTypeDocstring
const char kContextParseTypeDocstring[] static
Initial value:
=
    R"(Parses the assembly form of a type.
Returns a Type object or raises a ValueError if the type cannot be parsed.
See also: https://mlir.llvm.org/docs/LangRef/#type-system
)"
Definition at line 33 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().
kDumpDocstring
const char kDumpDocstring[] static
Initial value:
=
    R"(Dumps a debug representation of the object to stderr.)"
Definition at line 110 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().
kModuleParseDocstring
const char kModuleParseDocstring[] static
Initial value:
=
    R"(Parses a module's assembly format from a string.
Returns a new MlirModule or raises a ValueError if the parsing fails.
See also: https://mlir.llvm.org/docs/LangRef/
)"
Definition at line 44 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().
kOperationCreateDocstring
const char kOperationCreateDocstring[] static
Initial value:
=
    R"(Creates a new operation.
Args:
  name: Operation name (e.g. "dialect.operation").
  results: Sequence of Type representing op result types.
  attributes: Dict of str:Attribute.
  successors: List of Block for the operation's successors.
  regions: Number of regions to create.
  location: A Location object (defaults to resolve from context manager).
  ip: An InsertionPoint (defaults to resolve from context manager or set to
    False to disable insertion, even with an insertion point set in the
    context manager).
Returns:
  A new "detached" Operation object. Detached operations can be added
  to blocks, which causes them to become "attached."
)"
Definition at line 52 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().
kOperationGetAsmDocstring
const char kOperationGetAsmDocstring[] static
Initial value:
=
    R"(Gets the assembly form of the operation with all options available.
Args:
  binary: Whether to return a bytes (True) or str (False) object. Defaults to
    False.
  ... others ...: See the print() method for common keyword arguments for
    configuring the printout.
Returns:
  Either a bytes or str object, depending on the setting of the 'binary'
  argument.
)"
Definition at line 89 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().
kOperationPrintDocstring
const char kOperationPrintDocstring[] static
Initial value:
=
    R"(Prints the assembly form of the operation to a file like object.
Args:
  file: The file like object to write to. Defaults to sys.stdout.
  binary: Whether to write bytes (True) or str (False). Defaults to False.
  large_elements_limit: Whether to elide elements attributes above this
    number of elements. Defaults to None (no limit).
  enable_debug_info: Whether to print debug/location information. Defaults
    to False.
  pretty_debug_info: Whether to format debug information for easier reading
    by a human (warning: the result is unparseable).
  print_generic_op_form: Whether to print the generic assembly forms of all
    ops. Defaults to False.
  use_local_Scope: Whether to print in a way that is more optimized for
    multi-threaded access but may not be consistent with how the overall
    module prints.
)"
Definition at line 70 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().
kOperationStrDunderDocstring
const char kOperationStrDunderDocstring[] static
Initial value:
=
    R"(Gets the assembly form of the operation with default options.
If more advanced control over the assembly formatting or I/O options is needed,
use the dedicated print or get_asm method, which supports keyword arguments to
customize behavior.
)"
Definition at line 102 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().
kValueDunderStrDocstring
const char kValueDunderStrDocstring[] static
Initial value:
=
    R"(Returns the string form of the value.
If the value is a block argument, this is the assembly form of its type and the
position in the argument list. If the value is an operation result, this is
equivalent to printing the operation that produced it.
)"
Definition at line 120 of file IRModules.cpp.
Referenced by mlir::python::PyType::createFromCapsule().