MLIR: lib/Conversion/LinalgToLLVM/LinalgToLLVM.cpp File Reference
LinalgToLLVM.cpp File Reference
#include "mlir/Conversion/LinalgToLLVM/LinalgToLLVM.h"
#include "../PassDetail.h"
#include "mlir/Conversion/AffineToStandard/AffineToStandard.h"
#include "mlir/Conversion/SCFToStandard/SCFToStandard.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
#include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
#include "mlir/Conversion/VectorToSCF/VectorToSCF.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/IR/LinalgTypes.h"
#include "mlir/Dialect/Linalg/Passes.h"
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/Types.h"
#include "mlir/Support/LogicalResult.h"
#include "mlir/Transforms/DialectConversion.h"
#include "mlir/Transforms/Passes.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/ErrorHandling.h"
Typedefs
using llvm_add = ValueBuilder< LLVM::AddOp >
using llvm_bitcast = ValueBuilder< LLVM::BitcastOp >
using llvm_constant = ValueBuilder< LLVM::ConstantOp >
using llvm_extractvalue = ValueBuilder< LLVM::ExtractValueOp >
using llvm_gep = ValueBuilder< LLVM::GEPOp >
using llvm_insertvalue = ValueBuilder< LLVM::InsertValueOp >
using llvm_call = OperationBuilder< LLVM::CallOp >
using llvm_icmp = ValueBuilder< LLVM::ICmpOp >
using llvm_load = ValueBuilder< LLVM::LoadOp >
using llvm_store = OperationBuilder< LLVM::StoreOp >
using llvm_select = ValueBuilder< LLVM::SelectOp >
using llvm_mul = ValueBuilder< LLVM::MulOp >
using llvm_ptrtoint = ValueBuilder< LLVM::PtrToIntOp >
using llvm_sub = ValueBuilder< LLVM::SubOp >
using llvm_undef = ValueBuilder< LLVM::UndefOp >
using llvm_urem = ValueBuilder< LLVM::URemOp >
using llvm_alloca = ValueBuilder< LLVM::AllocaOp >
using llvm_return = OperationBuilder< LLVM::ReturnOp >
Functions
template<typename T >
static LLVMType getPtrToElementType (T containerType, LLVMTypeConverter &lowering)
static Type convertRangeType (RangeType t, LLVMTypeConverter &converter)
Convert the given range descriptor type to the LLVMIR dialect.
Typedef Documentation
llvm_add
using llvm_add = ValueBuilder<LLVM::AddOp>
Definition at line 50 of file LinalgToLLVM.cpp.
llvm_alloca
using llvm_alloca = ValueBuilder<LLVM::AllocaOp>
Definition at line 66 of file LinalgToLLVM.cpp.
llvm_bitcast
using llvm_bitcast = ValueBuilder<LLVM::BitcastOp>
Definition at line 51 of file LinalgToLLVM.cpp.
llvm_call
using llvm_call = OperationBuilder<LLVM::CallOp>
Definition at line 56 of file LinalgToLLVM.cpp.
llvm_constant
using llvm_constant = ValueBuilder<LLVM::ConstantOp>
Definition at line 52 of file LinalgToLLVM.cpp.
llvm_extractvalue
using llvm_extractvalue = ValueBuilder<LLVM::ExtractValueOp>
Definition at line 53 of file LinalgToLLVM.cpp.
llvm_gep
using llvm_gep = ValueBuilder<LLVM::GEPOp>
Definition at line 54 of file LinalgToLLVM.cpp.
llvm_icmp
using llvm_icmp = ValueBuilder<LLVM::ICmpOp>
Definition at line 57 of file LinalgToLLVM.cpp.
llvm_insertvalue
using llvm_insertvalue = ValueBuilder<LLVM::InsertValueOp>
Definition at line 55 of file LinalgToLLVM.cpp.
llvm_load
using llvm_load = ValueBuilder<LLVM::LoadOp>
Definition at line 58 of file LinalgToLLVM.cpp.
llvm_mul
using llvm_mul = ValueBuilder<LLVM::MulOp>
Definition at line 61 of file LinalgToLLVM.cpp.
llvm_ptrtoint
using llvm_ptrtoint = ValueBuilder<LLVM::PtrToIntOp>
Definition at line 62 of file LinalgToLLVM.cpp.
llvm_return
using llvm_return = OperationBuilder<LLVM::ReturnOp>
Definition at line 67 of file LinalgToLLVM.cpp.
llvm_select
using llvm_select = ValueBuilder<LLVM::SelectOp>
Definition at line 60 of file LinalgToLLVM.cpp.
llvm_store
using llvm_store = OperationBuilder<LLVM::StoreOp>
Definition at line 59 of file LinalgToLLVM.cpp.
llvm_sub
using llvm_sub = ValueBuilder<LLVM::SubOp>
Definition at line 63 of file LinalgToLLVM.cpp.
llvm_undef
using llvm_undef = ValueBuilder<LLVM::UndefOp>
Definition at line 64 of file LinalgToLLVM.cpp.
llvm_urem
using llvm_urem = ValueBuilder<LLVM::URemOp>
Definition at line 65 of file LinalgToLLVM.cpp.
Function Documentation
convertRangeType()
static Type convertRangeType (RangeType t, LLVMTypeConverter & converter) static
Convert the given range descriptor type to the LLVMIR dialect.
Range descriptor contains the range bounds and the step as 64-bit integers.
struct { int64_t min; int64_t max; int64_t step; };
Definition at line 85 of file LinalgToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::IntegerType::get(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerAttr(), mlir::Builder::getIntegerType(), mlir::edsc::ScopedContext::getLocation(), mlir::MemRefType::getShape(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::Type::isa(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::edsc::op::slt(), mlir::success(), and mlir::MemRefDescriptor::undef().
Referenced by mlir::populateLinalgToLLVMConversionPatterns().
getPtrToElementType()
template<typename T > static LLVMType getPtrToElementType (T containerType, LLVMTypeConverter & lowering) static
Definition at line 70 of file LinalgToLLVM.cpp.
References mlir::TypeConverter::convertType().