MLIR: lib/Transforms/Utils/LoopFusionUtils.cpp File Reference
LoopFusionUtils.cpp File Reference
#include "mlir/Transforms/LoopFusionUtils.h"
#include "mlir/Analysis/AffineAnalysis.h"
#include "mlir/Analysis/AffineStructures.h"
#include "mlir/Analysis/LoopAnalysis.h"
#include "mlir/Analysis/Utils.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Operation.h"
#include "mlir/Transforms/LoopUtils.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "loop-fusion-utils"
Functions
static void getLoadAndStoreMemRefAccesses (Operation *opA, DenseMap< Value, bool > &values)
static bool isDependentLoadOrStoreOp (Operation *op, DenseMap< Value, bool > &values)
Returns true if 'op' is a load or store operation which access a memref accessed 'values' and at least one of the access is a store operation.
static Operation * getFirstDependentOpInRange (Operation *opA, Operation *opB)
static Operation * getLastDependentOpInRange (Operation *opA, Operation *opB)
static Operation * getFusedLoopNestInsertionPoint (AffineForOp srcForOp, AffineForOp dstForOp)
static bool gatherLoadsAndStores (AffineForOp forOp, SmallVectorImpl< Operation *> &loadAndStoreOps)
static unsigned getMaxLoopDepth (ArrayRef< Operation *> dstOps, FusionStrategy fusionStrategy)
Returns the maximum loop depth at which we could fuse producer loop 'srcForOp' into consumer loop 'dstForOp' without violating data dependences.
static int64_t getComputeCostHelper (Operation *forOp, LoopNestStats &stats, llvm::SmallDenseMap< Operation *, uint64_t, 8 > *tripCountOverrideMap, DenseMap< Operation *, int64_t > *computeCostMap)
static Optional< uint64_t > getConstDifference (AffineMap lbMap, AffineMap ubMap)
static uint64_t getSliceIterationCount (const llvm::SmallDenseMap< Operation *, uint64_t, 8 > &sliceTripCountMap)
static bool buildSliceTripCountMap (const ComputationSliceState &slice, llvm::SmallDenseMap< Operation *, uint64_t, 8 > *tripCountMap)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loop-fusion-utils"
Definition at line 32 of file LoopFusionUtils.cpp.
Function Documentation
buildSliceTripCountMap()
static bool buildSliceTripCountMap (const ComputationSliceState & slice, llvm::SmallDenseMap< Operation *, uint64_t, 8 > * tripCountMap) static
Definition at line 517 of file LoopFusionUtils.cpp.
References mlir::getConstantTripCount(), getConstDifference(), mlir::getForInductionVarOwner(), mlir::ComputationSliceState::ivs, mlir::ComputationSliceState::lbs, and mlir::ComputationSliceState::ubs.
Referenced by mlir::getFusionComputeCost().
gatherLoadsAndStores()
static bool gatherLoadsAndStores (AffineForOp forOp, SmallVectorImpl< Operation *> & loadAndStoreOps) static
Definition at line 178 of file LoopFusionUtils.cpp.
Referenced by mlir::canFuseLoops().
getComputeCostHelper()
static int64_t getComputeCostHelper (Operation * forOp, LoopNestStats & stats, llvm::SmallDenseMap< Operation *, uint64_t, 8 > * tripCountOverrideMap, DenseMap< Operation *, int64_t > * computeCostMap) static
Definition at line 454 of file LoopFusionUtils.cpp.
References mlir::LoopNestStats::loopMap, mlir::LoopNestStats::opCountMap, and mlir::LoopNestStats::tripCountMap.
Referenced by mlir::getComputeCost(), and mlir::getFusionComputeCost().
getConstDifference()
static Optional<uint64_t> getConstDifference (AffineMap lbMap, AffineMap ubMap) static
Definition at line 487 of file LoopFusionUtils.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), and mlir::simplifyAffineExpr().
Referenced by buildSliceTripCountMap().
getFirstDependentOpInRange()
static Operation* getFirstDependentOpInRange (Operation * opA, Operation * opB) static
Definition at line 66 of file LoopFusionUtils.cpp.
References getLoadAndStoreMemRefAccesses(), isDependentLoadOrStoreOp(), and mlir::Operation::walk().
Referenced by getFusedLoopNestInsertionPoint().
getFusedLoopNestInsertionPoint()
static Operation* getFusedLoopNestInsertionPoint (AffineForOp srcForOp, AffineForOp dstForOp) static
Definition at line 137 of file LoopFusionUtils.cpp.
References getFirstDependentOpInRange(), getLastDependentOpInRange(), and mlir::Operation::isBeforeInBlock().
Referenced by mlir::canFuseLoops(), and isMemRefDereferencingOp().
getLastDependentOpInRange()
static Operation* getLastDependentOpInRange (Operation * opA, Operation * opB) static
Definition at line 92 of file LoopFusionUtils.cpp.
References mlir::WalkResult::advance(), getLoadAndStoreMemRefAccesses(), mlir::getLoopIVs(), mlir::Operation::getResults(), mlir::Operation::getUsers(), mlir::WalkResult::interrupt(), isDependentLoadOrStoreOp(), and mlir::Operation::walk().
Referenced by getFusedLoopNestInsertionPoint().
getLoadAndStoreMemRefAccesses()
static void getLoadAndStoreMemRefAccesses (Operation * opA, DenseMap< Value, bool > & values) static
Definition at line 38 of file LoopFusionUtils.cpp.
References mlir::Operation::walk().
Referenced by getFirstDependentOpInRange(), and getLastDependentOpInRange().
getMaxLoopDepth()
static unsigned getMaxLoopDepth (ArrayRef< Operation *> dstOps, FusionStrategy fusionStrategy) static
Returns the maximum loop depth at which we could fuse producer loop 'srcForOp' into consumer loop 'dstForOp' without violating data dependences.
Definition at line 194 of file LoopFusionUtils.cpp.
References mlir::checkMemrefAccessDependence(), mlir::getInnermostCommonLoopDepth(), mlir::getNumCommonSurroundingLoops(), mlir::hasDependence(), mlir::FusionStrategy::memref, mlir::FusionStrategy::ProducerConsumer, and mlir::FusionStrategy::strategy.
Referenced by mlir::canFuseLoops().
getSliceIterationCount()
static uint64_t getSliceIterationCount (const llvm::SmallDenseMap< Operation *, uint64_t, 8 > & sliceTripCountMap) static
Definition at line 503 of file LoopFusionUtils.cpp.
Referenced by mlir::getFusionComputeCost().
isDependentLoadOrStoreOp()
static bool isDependentLoadOrStoreOp (Operation * op, DenseMap< Value, bool > & values) static
Returns true if 'op' is a load or store operation which access a memref accessed 'values' and at least one of the access is a store operation.
Returns false otherwise.
Definition at line 53 of file LoopFusionUtils.cpp.
Referenced by getFirstDependentOpInRange(), and getLastDependentOpInRange().