MLIR: mlir::linalg Namespace Reference
mlir::linalg Namespace Reference
Classes
struct AffineMinSCFCanonicalizationPattern
Canonicalize AffineMinOp operations in the context of enclosing scf.for and scf.parallel by:
class Aliases
A very primitive alias analysis which just records for each view, either:
struct CodegenStrategy
Codegen strategy controls how a Linalg op is progressively lowered.
class ConvOpVectorization
Converts Convolution op into vector contraction.
class CopyOpToLibraryCallRewrite
Rewrite pattern specialization for CopyOp, kicks in when both input and output permutations are left unspecified or are the identity.
class CopyTransposeRewrite
Rewrite CopyOp with permutations into a sequence of TransposeOp and permutation-free CopyOp.
struct FusionInfo
A struct containing the Linalg producer before and after fusion.
struct GenerateLoopNest
Utility class used to generate nested loops with ranges described by loopRanges and loop type described by the iteratorTypes.
class IndexedGenericOpToLibraryCallRewrite
Conversion pattern specialization for IndexedGenericOp, has special handling for the extra index operands.
struct LinalgBaseInterchangePattern
Linalg interchange patterns.
struct LinalgBasePromotionPattern
Linalg promotion patterns.
struct LinalgBaseTileAndFusePattern
struct LinalgBaseTilingPattern
struct LinalgBaseVectorizationPattern
Linalg vectorization patterns.
struct LinalgCopyVTRForwardingPattern
Match and rewrite for the pattern: ``` alloc = ...
struct LinalgCopyVTWForwardingPattern
Match and rewrite for the pattern: ``` alloc = ...
class LinalgDependenceGraph
Data structure for holding a dependence graph that operates on LinalgOp and views as SSA values.
struct LinalgFusionOptions
struct LinalgInterchangePattern
struct LinalgLoopDistributionOptions
Options that allow distribution of loops generated in Linalg transforms to processors while generating the loops.
struct LinalgLoweringPattern
struct LinalgMarker
Helper class to control common attribute matching and setting behavior.
class LinalgOpToLibraryCallRewrite
struct LinalgPromotionOptions
struct LinalgPromotionPattern
struct LinalgTileAndFusePattern
struct LinalgTilingOptions
struct LinalgTilingPattern
struct LinalgTransforms
struct LinalgVectorizationPattern
struct ProcInfo
Callback function type used to get processor ID, and number of processors used for distribution for all parallel loops generated.
struct Promote
Promotion transformation enqueues a particular stage-1 pattern for Promote<LinalgOpType>with the appropriate options.
struct PromotionInfo
Creates a new buffer using the allocationFn provided.
class RangeType
A RangeType represents a minimal range abstraction (min, max, step).
struct RegionMatcher
A struct containing common matchers over linalg op's region.
struct SparsificationOptions
Sparsification options.
struct Tile
Promotion transformation enqueues a particular stage-1 pattern for Tile<LinalgOpType>with the appropriate options.
struct TiledAndFusedLinalgOps
Fuse a sequence of linalg operations (ops) using tile-and-fuse.
struct TiledLinalgOp
struct Transformation
Abstract Transformation class applied in a sequence that also handles state through markers.
struct Vectorize
Vectorization transformation enqueues a particular stage-1 pattern for LinalgVectorizationPattern<LinalgOpType> as well as copy to vector transfer rewrite forwarding patterns.
Typedefs
using LoopRangeBuilder = std::function< SmallVector< Range, 4 >(OpBuilder &, Location)>
using ReassociationIndices = SmallVector< int64_t, 2 >
using ReassociationExprs = SmallVector< AffineExpr, 2 >
using LinalgLoops = SmallVector< Operation *, 4 >
using AllocBufferCallbackFn = std::function< Optional< Value >(OpBuilder &b, SubViewOp subView, ArrayRef< Value > boundingSubViewSize, OperationFolder *folder)>
Callback function type used to perform the allocation for the promoted subView.
using DeallocBufferCallbackFn = std::function< LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
using CopyCallbackFn = std::function< LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
using TileSizeComputationFunction = std::function< SmallVector< Value, 4 >(OpBuilder &, Operation *)>
using FusableOpDependencesTy = llvm::MapVector< Operation *, SmallVector< LinalgDependenceGraph::LinalgDependenceGraphElem, 1 > >
using ProcInfoCallBackFn = std::function< SmallVector< ProcInfo, 2 >(OpBuilder &b, Location loc, ArrayRef< Range > parallelLoopRanges)>
Enumerations
enum LinalgTilingLoopType { LinalgTilingLoopType::Loops = 0, LinalgTilingLoopType::AffineLoops = 1, LinalgTilingLoopType::ParallelLoops = 2 }
Linalg tiling patterns.
enum LinalgLoweringType { LinalgLoweringType::LibraryCall = 0, LinalgLoweringType::Loops = 1, LinalgLoweringType::AffineLoops = 2, LinalgLoweringType::ParallelLoops = 3 }
Linalg lowering patterns.
enum SparseParallelizationStrategy {
SparseParallelizationStrategy::kNone, SparseParallelizationStrategy::kDenseOuterLoop, SparseParallelizationStrategy::kAnyStorageOuterLoop, SparseParallelizationStrategy::kDenseAnyLoop,
SparseParallelizationStrategy::kAnyStorageAnyLoop
}
Defines a parallelization strategy.
enum SparseVectorizationStrategy { SparseVectorizationStrategy::kNone, SparseVectorizationStrategy::kDenseInnerLoop, SparseVectorizationStrategy::kAnyStorageInnerLoop }
Defines a vectorization strategy.
enum SparseIntType { SparseIntType::kNative, SparseIntType::kI64, SparseIntType::kI32 }
Defines a type for "pointer" and "index" storage in the sparse storage scheme, with a choice between the native platform-dependent index width, 64-bit integers, or 32-bit integers.
enum DistributionMethod { DistributionMethod::Cyclic = 0, DistributionMethod::CyclicNumProcsGeNumIters = 1, DistributionMethod::CyclicNumProcsEqNumIters = 2 }
Scheme used to distribute loops to processors.
Functions
void populateLinalgToStandardConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Populate the given list with patterns that convert from Linalg to Standard.
SmallVector< Value, 4 > applyMapToValues (OpBuilder &b, Location loc, AffineMap map, ValueRange values)
Returns the values obtained by applying map to the list of values.
LoopRangeBuilder defaultLoopRangesBuilder (LinalgOp op)
Provide a very simple inference procedure to build the loop ranges from the op and its operands.
std::string generateLibraryCallName (Operation *op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
SmallVector< AffineExpr, 4 > makeAffineDimExprs (unsigned num, unsigned &startIdx, MLIRContext *context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
template<typename PoolingOp >
SmallVector< AffineExpr, 4 > weightedPoolingInputIndex (PoolingOp op, ArrayRef< AffineExpr > outputDims, ArrayRef< AffineExpr > windowDims)
Builds the indexing expressions for a ConvOp/PoolingOp op.
AffineMap extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext *context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
SmallVector< AffineExpr, 4 > concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
void getDimsOfType (Operation *op, StringRef iteratorTypeName, SmallVectorImpl< AffineExpr > &res)
Return the dims that are iteratorTypeName loops in the LinalgOp op.
void hoistViewAllocOps (FuncOp func)
Hoist alloc/dealloc pairs and alloca op out of immediately enclosing scf::ForOp if both conditions are true:
void hoistRedundantVectorTransfers (FuncOp func)
Hoist vector.transfer_read/vector.transfer_write pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
void populateConvVectorizationPatterns (MLIRContext *context, SmallVectorImpl< OwningRewritePatternList > &patterns, ArrayRef< int64_t > tileSizes)
Populates patterns for vectorization of all ConvN-D ops.
void populateLinalgBufferizePatterns (MLIRContext *context, BufferizeTypeConverter &converter, OwningRewritePatternList &patterns)
Populates the given list with patterns to bufferize linalg ops.
Optional< TiledLinalgOp > tileLinalgOp (OpBuilder &b, LinalgOp op, const LinalgTilingOptions &options)
Performs standalone tiling of a single LinalgOp by tileSizes.
Optional< TiledAndFusedLinalgOps > tileAndFuseLinalgOps (OpBuilder &builder, ArrayRef< LinalgOp > ops, const LinalgDependenceGraph &dependenceGraph, const LinalgTilingOptions &tilingOptions)
LinalgOp interchange (LinalgOp op, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions of op.
Optional< PromotionInfo > promoteSubviewAsNewBuffer (OpBuilder &b, Location loc, SubViewOp subView, AllocBufferCallbackFn allocationFn, OperationFolder *folder=nullptr)
Optional< LinalgOp > promoteSubViews (OpBuilder &b, LinalgOp op, LinalgPromotionOptions options, OperationFolder *folder=nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
void vectorizeLinalgOp (OpBuilder &builder, Operation *op)
Emit a suitable vector form for a Linalg op with fully static shape.
template<typename LoopTy >
Optional< LinalgLoops > linalgLowerOpToLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of LoopTy with the proper body for op.
LogicalResult linalgOpToLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of scf.for with the proper body for op.
LogicalResult linalgOpToParallelLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of scf.parallel with the proper body for op.
LogicalResult linalgOpToAffineLoops (OpBuilder &builder, Operation *op)
Emits a loop nest of affine.for with the proper body for op.
LogicalResult interchangeGenericLinalgOpPrecondition (Operation *op, ArrayRef< unsigned > interchangeVector)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
LogicalResult promoteSubviewsPrecondition (Operation *op, LinalgPromotionOptions options)
Promote std.subviews feeding linalg operations.
LogicalResult vectorizeLinalgOpPrecondition (Operation *op)
Rewrite a linalg.generic into a suitable vector.contraction op.
OwningRewritePatternList getLinalgTilingCanonicalizationPatterns (MLIRContext *ctx)
Canonicalization patterns relevant to apply after tiling patterns.
void populateLinalgTilingCanonicalizationPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
void populateLinalgNamedOpsGeneralizationPatterns (MLIRContext *context, OwningRewritePatternList &patterns, LinalgMarker marker=LinalgMarker())
Linalg generalization patterns.
void populateLinalgConvGeneralizationPatterns (MLIRContext *context, OwningRewritePatternList &patterns, LinalgMarker marker=LinalgMarker())
Populates patterns with patterns to convert linalg.conv ops to linalg.generic ops.
LogicalResult applyStagedPatterns (Operation *op, ArrayRef< FrozenRewritePatternList > stage1Patterns, const FrozenRewritePatternList &stage2Patterns, function_ref< LogicalResult(Operation *)> stage3Lambda=nullptr)
Helper function to allow applying rewrite patterns, interleaved with more global transformations, in a staged fashion:
void populateSparsificationPatterns (MLIRContext *context, OwningRewritePatternList &patterns, const SparsificationOptions &options=SparsificationOptions())
Set up sparsification rewriting rules with the given options.
bool isParallelIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isReductionIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isWindowIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
bool isProducerLastWriteOfView (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
bool isFusableInto (const LinalgDependenceGraph &graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
FusableOpDependencesTy findAllFusableDependences (ArrayRef< LinalgOp > ops, const LinalgDependenceGraph &dependenceGraph)
Find all dependences that are fusable.
Optional< FusionInfo > fuseProducerOfBuffer (OpBuilder &b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph &graph)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
Optional< FusionInfo > fuseProducerOfTensor (OpBuilder &b, LinalgOp consumer, unsigned consumerIdx)
Tensor counterpart of fuseProducerOfBuffer.
Optional< SmallVector< Value, 1 > > fuseTensorOps (PatternRewriter &rewriter, Operation *consumer, unsigned consumerIdx)
Fuse linalg operation on tensors, with the producer of the operand at position consumerIdx of the consumer.
SmallVector< int64_t, 8 > getStaticShape (LinalgOp linalgOp)
Like getShape, but only returns statically-known information, without generating any new IR.
Optional< SmallVector< int64_t, 4 > > getStaticLoopRanges (LinalgOp linalgOp)
Returns the statically-known loop ranges of the linalgOp.
template<typename T , unsigned N>
void applyPermutationToVector (SmallVector< T, N > &inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
static void updateBoundsForCyclicDistribution (OpBuilder &builder, Location loc, Value procId, Value nprocs, Value &lb, Value &ub, Value &step)
Update the lb, ub and step to get per processor lb, ub and step.
static void generateParallelLoopNest (ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > &ivStorage, ArrayRef< DistributionMethod > distributionMethod={})
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
Typedef Documentation
AllocBufferCallbackFn
using mlir::linalg::AllocBufferCallbackFn = typedef std::function<Optional<Value>(OpBuilder &b, SubViewOp subView, ArrayRef<Value> boundingSubViewSize, OperationFolder *folder)>
Callback function type used to perform the allocation for the promoted subView.
In boundingSubViewsize a best attempt is made to find the smallest constant value for the size of the buffer needed for each dimension. If that is not possible, contains the dynamic size of the subview. The call back should return the buffer to use.
Definition at line 151 of file Transforms.h.
CopyCallbackFn
using mlir::linalg::CopyCallbackFn = typedef std::function<LogicalResult(OpBuilder &b, Value src, Value dst)>
Callback function type used to insert copy from original subview to subview of the promoted region for the read operands/subview of promoted region to original subview for the results.
The copy has to happen from src to dst.
Definition at line 163 of file Transforms.h.
DeallocBufferCallbackFn
using mlir::linalg::DeallocBufferCallbackFn = typedef std::function<LogicalResult(OpBuilder &b, Value buffer)>
Callback function type used to deallocate the buffers used to hold the promoted subview.
Definition at line 156 of file Transforms.h.
FusableOpDependencesTy
using mlir::linalg::FusableOpDependencesTy = typedef llvm::MapVector< Operation *, SmallVector<LinalgDependenceGraph::LinalgDependenceGraphElem, 1> >
Definition at line 88 of file Utils.h.
LinalgLoops
using mlir::linalg::LinalgLoops = typedef SmallVector<Operation *, 4>
Definition at line 32 of file Transforms.h.
LoopRangeBuilder
using mlir::linalg::LoopRangeBuilder = typedef std::function<SmallVector<Range, 4>(OpBuilder &, Location)>
Definition at line 44 of file LinalgOps.h.
ProcInfoCallBackFn
using mlir::linalg::ProcInfoCallBackFn = typedef std::function<SmallVector<ProcInfo, 2>(OpBuilder &b, Location loc, ArrayRef<Range> parallelLoopRanges)>
Definition at line 188 of file Utils.h.
ReassociationExprs
using mlir::linalg::ReassociationExprs = typedef SmallVector<AffineExpr, 2>
Definition at line 60 of file LinalgOps.h.
ReassociationIndices
using mlir::linalg::ReassociationIndices = typedef SmallVector<int64_t, 2>
Definition at line 59 of file LinalgOps.h.
TileSizeComputationFunction
using mlir::linalg::TileSizeComputationFunction = typedef std::function<SmallVector<Value, 4>(OpBuilder &, Operation *)>
Definition at line 333 of file Transforms.h.
Enumeration Type Documentation
DistributionMethod
enum mlir::linalg::DistributionMethod strong
Scheme used to distribute loops to processors.
Enumerator
Cyclic
Cyclic distribution where no assumption is made about the dynamic relationship between number of processors and number of iterations of the distributed loop.
Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
scf.parallel(iv)= (lb + procId * step) to (ub) step (step * nprocs)
CyclicNumProcsGeNumIters
Cyclic distribution where the number of processors can be assumed to be more than or equal to the number of iterations of the distributed loop.
In such cases, a simple in-bounds check is enough (instead of materializing a loop). Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
iv = lb + procId * step cond = cmpi "slt", iv, ub scf.if cond { ... }
CyclicNumProcsEqNumIters
Cyclic distribution where the number of processors can be assumed to be equal to the number of iterations of the distributed loop.
In such cases, no bounds check is needed. Distributes the following loop
scf.parallel (iv) = (lb) to (ub) step (step)
to
iv = lb + procId * step
Definition at line 141 of file Utils.h.
LinalgLoweringType
enum mlir::linalg::LinalgLoweringType strong
Linalg lowering patterns.
Apply the linalgLowerOpToLoops transformation as a pattern. marker controls LinalgTransformMarker matching and update when specified. See linalgLowerOpToLoops for more details.
Enumerator
LibraryCall
Loops
AffineLoops
ParallelLoops
Definition at line 584 of file Transforms.h.
LinalgTilingLoopType
enum mlir::linalg::LinalgTilingLoopType strong
Linalg tiling patterns.
Apply the tileLinalgOp transformation as a pattern. marker controls LinalgTransformMarker matching and update when specified. See tileLinalgOp for more details.
Enumerator
Loops
AffineLoops
ParallelLoops
Definition at line 326 of file Transforms.h.
SparseIntType
enum mlir::linalg::SparseIntType strong
Defines a type for "pointer" and "index" storage in the sparse storage scheme, with a choice between the native platform-dependent index width, 64-bit integers, or 32-bit integers.
A narrow width obviously reduces the memory footprint of the sparse storage scheme, but the width should suffice to define the total required range (viz. the maximum number of stored entries per indirection level for the "pointers" and the maximum value of each tensor index over all dimensions for the "indices").
Enumerator
kNative
kI64
kI32
Definition at line 838 of file Transforms.h.
SparseParallelizationStrategy
enum mlir::linalg::SparseParallelizationStrategy strong
Defines a parallelization strategy.
Any implicit loop in the Linalg operation that is marked "parallel" (thus not "reduction") is a candidate for parallelization. The loop is made parallel if (1) allowed by the strategy (e.g., AnyStorageOuterLoop considers either a dense or sparse outermost loop only), and (2) the generated code is an actual for-loop (and not a co-iterating while-loop).
Enumerator
kNone
kDenseOuterLoop
kAnyStorageOuterLoop
kDenseAnyLoop
kAnyStorageAnyLoop
Definition at line 811 of file Transforms.h.
SparseVectorizationStrategy
enum mlir::linalg::SparseVectorizationStrategy strong
Defines a vectorization strategy.
Any implicit inner loop in the Linalg operation is a candidate (full SIMD for "parallel" loops and horizontal SIMD for "reduction" loops). A loop is actually vectorized if (1) allowed by the strategy, and (2) the emitted code is an actual for-loop (and not a co-iterating while-loop).
Enumerator
kNone
kDenseInnerLoop
kAnyStorageInnerLoop
Definition at line 825 of file Transforms.h.
Function Documentation
applyMapToValues()
SmallVector< Value, 4 > mlir::linalg::applyMapToValues (OpBuilder & b, Location loc, AffineMap map, ValueRange values)
Returns the values obtained by applying map to the list of values.
Definition at line 44 of file LinalgOps.cpp.
References buildNamedStructuredOpRegionAndAttributes(), mlir::OpBuilder::create(), createFoldedComposedAffineApply(), mlir::AffineMap::get(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::ShapedType::getRank(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), parseCommonStructuredOpParts(), parseNamedStructuredOp(), parseNamedStructuredOpRegion(), parseNamedStructuredOpResults(), printCommonStructuredOpParts(), printNamedStructuredOp(), printNamedStructuredOpResults(), and verifyNamedStructuredOp().
applyPermutationToVector()
template<typename T , unsigned N> void mlir::linalg::applyPermutationToVector (SmallVector< T, N > & inVec, ArrayRef< unsigned > permutation)
Apply the permutation defined by permutation to inVec.
Element i in inVec is mapped to location j = permutation[i]. E.g.: for an input vector `inVec = ['a', 'b', 'c']and a permutation vector permutation = [2, 0, 1], this function leavesinVec = ['c', 'a', 'b']`.
Definition at line 132 of file Utils.h.
Referenced by interchange(), and tileLinalgOpImpl().
applyStagedPatterns()
LogicalResult mlir::linalg::applyStagedPatterns (Operation * op, ArrayRef< FrozenRewritePatternList > stage1Patterns, const FrozenRewritePatternList & stage2Patterns, function_ref< LogicalResult(Operation *)> stage3Lambda = nullptr)
Helper function to allow applying rewrite patterns, interleaved with more global transformations, in a staged fashion:
the first stage consists of a list of FrozenRewritePatternList. Each FrozenRewritePatternList in this list is applied once, in order.
the second stage consists of a single OwningRewritePattern that is applied greedily until convergence.
the third stage consists of applying a lambda, generally used for non-local transformation effects. This allows creating custom fused transformations where patterns can be ordered and applied at a finer granularity than a sequence of traditional compiler passes.
Definition at line 316 of file Transforms.cpp.
References mlir::applyPatternsAndFoldGreedily(), DBGS, mlir::failed(), mlir::failure(), and mlir::success().
Referenced by mlir::linalg::ConvOpVectorization< ConvOp, N >::ConvOpVectorization(), and mlir::linalg::CodegenStrategy::transform().
concat()
SmallVector< AffineExpr, 4 > mlir::linalg::concat (ArrayRef< AffineExpr > a, ArrayRef< AffineExpr > b)
Return the vector that is the concatenation of a and b.
Definition at line 1388 of file LinalgOps.cpp.
Referenced by mlir::Simplex::makeProduct().
defaultLoopRangesBuilder()
LoopRangeBuilder mlir::linalg::defaultLoopRangesBuilder (LinalgOp op)
Provide a very simple inference procedure to build the loop ranges from the op and its operands.
This only works with permutation affine maps and patterns of the form (m, n)[s] -> (m + n - s floordiv 2). A more advanced Tensor-Comprehension like inference is possible but has proven to be ambiguous in unfavorable case. As a consequence, we relax the default behavior very conservatively and provide an op-specified hook so that Linalg ops may override the behavior.
extractOrIdentityMap()
AffineMap mlir::linalg::extractOrIdentityMap (Optional< AffineMap > maybeMap, unsigned rank, MLIRContext * context)
Returns maybeMap.get() if maybeMap is set, otherwise returns the symbol-less identity map of rank.
Definition at line 1340 of file LinalgOps.cpp.
References mlir::AffineMap::get(), and mlir::AffineMap::getMultiDimIdentityMap().
findAllFusableDependences()
FusableOpDependencesTy mlir::linalg::findAllFusableDependences (ArrayRef< LinalgOp > ops, const LinalgDependenceGraph & dependenceGraph)
Find all dependences that are fusable.
Definition at line 726 of file Fusion.cpp.
References findFusableProducer(), and mlir::AffineMap::isProjectedPermutation().
Referenced by tileAndFuseLinalgOpsImpl().
fuseProducerOfBuffer()
Optional< FusionInfo > mlir::linalg::fuseProducerOfBuffer (OpBuilder & b, LinalgOp consumer, unsigned consumerIdx, const LinalgDependenceGraph & graph)
Fuses producer into consumer if the producer is structurally feasible and the fusion would not violate dependencies.
Implements the fusion part of the "tileAndFuse on buffers" transformation and thus requires the consumerdIdx^th operand of consumer to be a subview op (generally obtained by applying the tiling transformation).
Definition at line 427 of file Fusion.cpp.
References findFusableProducer(), fuse(), mlir::Value::getDefiningOp(), and mlir::OpBuilder::setInsertionPoint().
fuseProducerOfTensor()
Optional< FusionInfo > mlir::linalg::fuseProducerOfTensor (OpBuilder & b, LinalgOp consumer, unsigned consumerIdx)
Tensor counterpart of fuseProducerOfBuffer.
This implements the fusion part of the "tileAndFuse on tensors" transformation and thus requires the consumerdIdx^th operand of consumer to be the result of a subtensor op (generally obtained by applying the tiling transformation).
Definition at line 490 of file Fusion.cpp.
References mlir::OpBuilder::create(), fuse(), mlir::OpOperand::get(), mlir::Value::getDefiningOp(), getProducerOfTensor(), mlir::Value::getType(), mlir::OpOperand::set(), and mlir::OpBuilder::setInsertionPoint().
fuseTensorOps()
Optional< SmallVector< Value, 1 > > mlir::linalg::fuseTensorOps (PatternRewriter & rewriter, Operation * consumer, unsigned consumerIdx)
Fuse linalg operation on tensors, with the producer of the operand at position consumerIdx of the consumer.
Definition at line 935 of file FusionOnTensors.cpp.
References mlir::applyPatternsAndFoldGreedily(), mlir::PatternRewriter::eraseOp(), mlir::failure(), fuseTensorOpsImpl(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getRegions(), mlir::populateFoldReshapeOpsByLinearizationPatterns(), mlir::populateLinalgTensorOpsFusionPatterns(), mlir::PatternRewriter::replaceOp(), mlir::success(), and mlir::Operation::use_empty().
generateLibraryCallName()
std::string mlir::linalg::generateLibraryCallName (Operation * op)
Returns the name mangled library call name to disambiguate between different overloads at the C level.
The name mangling scheme is basic and uses MLIR type names:
form a string which is the concatenation of the linalg op name with all the operand type names, separate by underscores;
drop the linalg. prefix, and the <, >, ? symbols from the type. Assumes op is a LinalgOp.
Examples:
linalg.fill(A, f) : memref<f32>, f32 name mangles into linalg_fill_viewf32_f32_impl
linalg.dot A, B, C : (memref<?xf32, stride_specification>, memref<?xf32, stride_specification>, memref<f32>) name mangles into linalg_dot_viewxf32_viewxf32_viewf32_impl
linalg.matmul(...) : memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification>, memref<?x?xf32, stride_specification> name mangles into linalg_matmul_viewxxf32_viewxxf32_viewxxf32_impl
Definition at line 1417 of file LinalgOps.cpp.
References appendMangledType(), foldMemRefCast(), foldReshapeOp(), mlir::Operation::getName(), mlir::Operation::getOperandTypes(), mlir::OperationName::getStringRef(), and mlir::succeeded().
generateParallelLoopNest()
static void mlir::linalg::generateParallelLoopNest (ValueRange lbs, ValueRange ubs, ValueRange steps, ArrayRef< Attribute > iteratorTypes, function_ref< void(ValueRange)> bodyBuilderFn, SmallVectorImpl< Value > & ivStorage, ArrayRef< DistributionMethod > distributionMethod = {}) static
Generates a loop nest consisting of scf.parallel and scf.for, depending on the `iteratorTypes.
` Consecutive parallel loops create a single scf.parallel operation; each sequential loop creates a new scf.for operation. The body of the innermost loop is populated by bodyBuilderFn that accepts a range of induction variables for all loops. ivStorage is used to store the partial list of induction variables.
Definition at line 203 of file Utils.cpp.
References mlir::edsc::conditionBuilder(), Cyclic, CyclicNumProcsEqNumIters, CyclicNumProcsGeNumIters, isParallelIteratorType(), mlir::edsc::loopNestBuilder(), and mlir::edsc::op::slt().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
getDimsOfType()
void mlir::linalg::getDimsOfType (Operation * op, StringRef iteratorTypeName, SmallVectorImpl< AffineExpr > & res)
Return the dims that are iteratorTypeName loops in the LinalgOp op.
Assumes op is a LinalgOp.
Definition at line 1325 of file LinalgOps.cpp.
References mlir::getAffineDimExpr(), and mlir::Operation::getContext().
getLinalgTilingCanonicalizationPatterns()
OwningRewritePatternList mlir::linalg::getLinalgTilingCanonicalizationPatterns (MLIRContext * ctx)
Canonicalization patterns relevant to apply after tiling patterns.
These are applied automatically by the tiling pass but need to be applied manually when tiling is called programmatically.
Definition at line 555 of file Tiling.cpp.
References populateLinalgTilingCanonicalizationPatterns().
Referenced by applyTilingToLoopPatterns(), mlir::linalg::LinalgTilingOptions::setDistributionOptions(), and mlir::linalg::CodegenStrategy::transform().
getStaticLoopRanges()
Optional< SmallVector< int64_t, 4 > > mlir::linalg::getStaticLoopRanges (LinalgOp linalgOp)
Returns the statically-known loop ranges of the linalgOp.
Composes linalgOp.getShapesToLoopsMap() with the result of getStaticShape. Returns None if linalgOp.getShapesToLoopsMap() fails. Returns -1 for non-statically-known loop ranges.
Definition at line 116 of file Utils.cpp.
References mlir::AffineMap::compose(), and getStaticShape().
Referenced by fuseWithReshapeByExpansion().
getStaticShape()
SmallVector< int64_t, 8 > mlir::linalg::getStaticShape (LinalgOp linalgOp)
Like getShape, but only returns statically-known information, without generating any new IR.
For each shape dimension, returns >=0 if that dimension is statically known, or -1 otherwise.
Definition at line 101 of file Utils.cpp.
References getShape().
Referenced by getStaticLoopRanges().
hoistRedundantVectorTransfers()
void mlir::linalg::hoistRedundantVectorTransfers (FuncOp func)
Hoist vector.transfer_read/vector.transfer_write pairs out of immediately enclosing scf::ForOp iteratively, if the following conditions are true:
The two ops access the same memref with the same indices.
All operands are invariant under the enclosing scf::ForOp.
No uses of the memref either dominate the transfer_read or are dominated by the transfer_write (i.e. no aliasing between the write and the read across the loop) To improve hoisting opportunities, call the moveLoopInvariantCode helper function on the candidate loop above which to hoist. Hoisting the transfers results in scf::ForOp yielding the value that originally transited through memory.
Definition at line 84 of file Hoisting.cpp.
References mlir::WalkResult::advance(), mlir::cloneWithNewYields(), DBGS, mlir::failed(), mlir::getForwardSlice(), mlir::WalkResult::interrupt(), mlir::moveLoopInvariantCode(), and mlir::DominanceInfo::properlyDominates().
Referenced by mlir::linalg::CodegenStrategy::transform().
hoistViewAllocOps()
void mlir::linalg::hoistViewAllocOps (FuncOp func)
Hoist alloc/dealloc pairs and alloca op out of immediately enclosing scf::ForOp if both conditions are true:
All operands are defined outside the loop.
All uses are ViewLikeOp or DeallocOp.
Definition at line 37 of file Hoisting.cpp.
References DBGS, mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getParentOp(), mlir::Operation::getResult(), mlir::Value::getUses(), and mlir::Operation::moveAfter().
Referenced by mlir::linalg::CodegenStrategy::transform().
interchange()
LinalgOp mlir::linalg::interchange (LinalgOp op, ArrayRef< unsigned > interchangeVector)
Interchanges the iterator_types and iterator_maps dimensions of op.
This is an in-place transformation controlled by interchangeVector. An empty vector is interpreted as the identity permutation and the transformation returns early.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed with interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..op.rank without duplications (i.e. [1,1,2] is an invalid permutation).
Definition at line 56 of file Interchange.cpp.
References applyPermutationToVector(), mlir::AffineMap::compose(), mlir::AffineMapAttr::get(), mlir::ArrayAttr::get(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), mlir::AffineMap::getPermutationMap(), and mlir::inversePermutation().
Referenced by mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite().
interchangeGenericLinalgOpPrecondition()
LogicalResult mlir::linalg::interchangeGenericLinalgOpPrecondition (Operation * op, ArrayRef< unsigned > interchangeVector)
Emits a generic or indexed_generic operation with the indexing_maps and iterator_types permutated according to permutation.
Definition at line 35 of file Interchange.cpp.
References mlir::failure(), mlir::Operation::getContext(), mlir::AffineMap::getPermutationMap(), mlir::inversePermutation(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite().
isFusableInto()
bool mlir::linalg::isFusableInto (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether fusing the specific producer of the consumedView is feasible.
This checks producer is the last write of consumedView and that no interleaved dependence would be violated (RAW, WAR or WAW).
Definition at line 324 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringDependences(), and isProducerLastWriteOfView().
Referenced by findFusableProducer().
isParallelIteratorType()
bool mlir::linalg::isParallelIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 60 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getParallelIteratorTypeName().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit(), generateParallelLoopNest(), and genFor().
isProducerLastWriteOfView()
bool mlir::linalg::isProducerLastWriteOfView (const LinalgDependenceGraph & graph, LinalgOp consumer, Value consumedView, LinalgOp producer)
Checks whether the specific producer is the last write to exactly the whole consumedView.
This checks structural dominance, that the dependence is a RAW without any interleaved write to any piece of consumedView.
Definition at line 300 of file Fusion.cpp.
References mlir::linalg::LinalgDependenceGraph::findCoveringWrites(), and isStructurallyFusableProducer().
Referenced by isFusableInto().
isReductionIteratorType()
bool mlir::linalg::isReductionIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 67 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getReductionIteratorTypeName().
isWindowIteratorType()
bool mlir::linalg::isWindowIteratorType (Attribute attr)
Checks if an iterator_type attribute is parallel.
Definition at line 74 of file Utils.cpp.
References mlir::Attribute::dyn_cast(), and mlir::getWindowIteratorTypeName().
linalgLowerOpToLoops()
template<typename LoopTy > template Optional< LinalgLoops > mlir::linalg::linalgLowerOpToLoops< AffineForOp > (OpBuilder & builder, Operation * op)
Emits a loop nest of LoopTy with the proper body for op.
Emits a loop nest with the proper body for op.
Definition at line 657 of file Loops.cpp.
linalgOpToAffineLoops()
LogicalResult mlir::linalg::linalgOpToAffineLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of affine.for with the proper body for op.
Definition at line 673 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
linalgOpToLoops()
LogicalResult mlir::linalg::linalgOpToLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of scf.for with the proper body for op.
Definition at line 680 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
linalgOpToParallelLoops()
LogicalResult mlir::linalg::linalgOpToParallelLoops (OpBuilder & builder, Operation * op)
Emits a loop nest of scf.parallel with the proper body for op.
Definition at line 686 of file Loops.cpp.
References mlir::failure(), and mlir::success().
Referenced by mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
makeAffineDimExprs()
SmallVector< AffineExpr, 4 > mlir::linalg::makeAffineDimExprs (unsigned num, unsigned & startIdx, MLIRContext * context)
Returns num AffineDimExpr dimensions at positions [startIdx, startIdx + num) and increments startIdx to startIdx + num.
Definition at line 1351 of file LinalgOps.cpp.
References mlir::getAffineDimExpr().
populateConvVectorizationPatterns()
void mlir::linalg::populateConvVectorizationPatterns (MLIRContext * context, SmallVectorImpl< OwningRewritePatternList > & patterns, ArrayRef< int64_t > tileSizes)
Populates patterns for vectorization of all ConvN-D ops.
Definition at line 633 of file Vectorization.cpp.
populateLinalgBufferizePatterns()
void mlir::linalg::populateLinalgBufferizePatterns (MLIRContext * context, BufferizeTypeConverter & converter, OwningRewritePatternList & patterns)
Populates the given list with patterns to bufferize linalg ops.
Definition at line 352 of file Bufferize.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by finalizeBufferAllocation().
populateLinalgConvGeneralizationPatterns()
void mlir::linalg::populateLinalgConvGeneralizationPatterns (MLIRContext * context, OwningRewritePatternList & patterns, linalg::LinalgMarker marker = LinalgMarker())
Populates patterns with patterns to convert linalg.conv ops to linalg.generic ops.
Definition at line 166 of file Generalization.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by createGenericOpFromNamedOp(), and mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
populateLinalgNamedOpsGeneralizationPatterns()
void mlir::linalg::populateLinalgNamedOpsGeneralizationPatterns (MLIRContext * context, OwningRewritePatternList & patterns, linalg::LinalgMarker marker = LinalgMarker())
Linalg generalization patterns.
Populates patterns with patterns to convert spec-generated named ops to linalg.generic ops.
Definition at line 172 of file Generalization.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by createGenericOpFromNamedOp(), and mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite().
populateLinalgTilingCanonicalizationPatterns()
void mlir::linalg::populateLinalgTilingCanonicalizationPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Definition at line 561 of file Tiling.cpp.
Referenced by getLinalgTilingCanonicalizationPatterns(), and mlir::linalg::LinalgTilingOptions::setDistributionOptions().
populateLinalgToStandardConversionPatterns()
void mlir::linalg::populateLinalgToStandardConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Populate the given list with patterns that convert from Linalg to Standard.
Definition at line 187 of file LinalgToStandard.cpp.
References mlir::ConversionTarget::addLegalDialect(), mlir::ConversionTarget::addLegalOp(), mlir::applyFullConversion(), mlir::failed(), and mlir::OwningRewritePatternList::insert().
populateSparsificationPatterns()
void mlir::linalg::populateSparsificationPatterns (MLIRContext * context, OwningRewritePatternList & patterns, const SparsificationOptions & options = SparsificationOptions())
Set up sparsification rewriting rules with the given options.
Populates the given patterns list with rewriting rules required for the sparsification of linear algebra operations.
Definition at line 1053 of file Sparsification.cpp.
References mlir::OwningRewritePatternList::insert(), and options.
promoteSubviewAsNewBuffer()
Optional< PromotionInfo > mlir::linalg::promoteSubviewAsNewBuffer (OpBuilder & b, Location loc, SubViewOp subView, AllocBufferCallbackFn allocationFn, OperationFolder * folder = nullptr)
Definition at line 231 of file Promotion.cpp.
References mlir::detail::enumerate(), and extractSmallestConstantBoundingSize().
Referenced by promoteSubViews().
promoteSubViews()
Optional< LinalgOp > mlir::linalg::promoteSubViews (OpBuilder & b, LinalgOp op, LinalgPromotionOptions options, OperationFolder * folder = nullptr)
Promotes the subViews into a new buffer allocated at the insertion point b.
Promotion occurs in 3 steps:
Create a new buffer for a full tile (i.e. not clipped at the boundary).
Take a full view on the buffer.
Take a partial slice of the full view in step 2. and copy into it. Infers statically sized buffers from subViews unless dynamicBuffers is true.
Returns the modified linalg op (the modification happens in place) as well as all the copy ops created.
Definition at line 387 of file Promotion.cpp.
References mlir::failed(), promoteSubViews(), promoteSubviewsPrecondition(), mlir::linalg::LinalgPromotionOptions::setDynamicBuffers(), and mlir::linalg::LinalgPromotionOptions::setUseAlloca().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite().
promoteSubviewsPrecondition()
LogicalResult mlir::linalg::promoteSubviewsPrecondition (Operation * op, LinalgPromotionOptions options)
Promote std.subviews feeding linalg operations.
Definition at line 367 of file Promotion.cpp.
References mlir::detail::enumerate(), mlir::failure(), mlir::linalg::LinalgPromotionOptions::operandsToPromote, and mlir::success().
Referenced by mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), and promoteSubViews().
tileAndFuseLinalgOps()
Optional< TiledAndFusedLinalgOps > mlir::linalg::tileAndFuseLinalgOps (OpBuilder & builder, ArrayRef< LinalgOp > ops, const LinalgDependenceGraph & dependenceGraph, const LinalgTilingOptions & tilingOptions)
Definition at line 897 of file Fusion.cpp.
References mlir::linalg::LinalgTilingOptions::loopType.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
tileLinalgOp()
Optional< TiledLinalgOp > mlir::linalg::tileLinalgOp (OpBuilder & b, LinalgOp op, const LinalgTilingOptions & options)
Performs standalone tiling of a single LinalgOp by tileSizes.
and permute the loop nest according to interchangeVector The permutation is expressed as a list of integers that specify the new ordering of the loop nest. The length of interchangeVector must be equal to the length of tileSizes. An empty vector is interpreted as the identity permutation and the transformation returns early.
Returns a struct containing the tiled loops in the specified order and the cloned op if successful, llvm::None otherwise.
E.g. the permutation (i,j,k) -> (j,k,i) is expressed by interchangeVector = [1,2,0]. All values in interchangeVector must be integers, in the range 0..tileSizes.size() without duplications (i.e. [1,1,2] is an invalid permutation).
Definition at line 499 of file Tiling.cpp.
References mlir::Identifier::get(), mlir::OwningRewritePatternList::insert(), mlir::linalg::LinalgTilingOptions::loopType, and options.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), mlir::linalg::LinalgBaseTilingPattern::matchAndRewriteBase(), and tileRootOperation().
updateBoundsForCyclicDistribution()
static void mlir::linalg::updateBoundsForCyclicDistribution (OpBuilder & builder, Location loc, Value procId, Value nprocs, Value & lb, Value & ub, Value & step) static
Update the lb, ub and step to get per processor lb, ub and step.
Definition at line 182 of file Utils.cpp.
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit().
vectorizeLinalgOp()
void mlir::linalg::vectorizeLinalgOp (OpBuilder & builder, Operation * op)
Emit a suitable vector form for a Linalg op with fully static shape.
Definition at line 294 of file Vectorization.cpp.
References DEBUG_TYPE, extractVectorTypeFromScalarView(), mlir::Operation::getLoc(), isContraction(), isElementwise(), mlir::succeeded(), transferReadVector(), transferWriteVector(), vectorizeElementwise(), and vectorizeLinalgOpPrecondition().
Referenced by mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite().
vectorizeLinalgOpPrecondition()
LogicalResult mlir::linalg::vectorizeLinalgOpPrecondition (Operation * op)
Rewrite a linalg.generic into a suitable vector.contraction op.
Definition at line 277 of file Vectorization.cpp.
References mlir::failure(), mlir::ShapedType::hasStaticShape(), isContraction(), isElementwise(), and mlir::success().
Referenced by mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite(), and vectorizeLinalgOp().
weightedPoolingInputIndex()
template<typename PoolingOp > SmallVector< AffineExpr, 4 > mlir::linalg::weightedPoolingInputIndex (PoolingOp op, ArrayRef< AffineExpr > outputDims, ArrayRef< AffineExpr > windowDims)
Builds the indexing expressions for a ConvOp/PoolingOp op.
Returns the vector of AffineMaps representing: stride[i] * outputDims[i] + dilation[i] * windowDims[i] - pad_low[i]
Definition at line 1362 of file LinalgOps.cpp.