MLIR: mlir::python Namespace Reference
mlir::python Namespace Reference
Classes
class BaseContextObject
Base class for all objects that directly or indirectly depend on an MlirContext.
class Defaulting
CRTP template for special wrapper types that are allowed to be passed in as 'None' function arguments and can be resolved by some global mechanic if so.
class DefaultingPyLocation
Used in function arguments when None should resolve to the current context manager set instance.
class DefaultingPyMlirContext
Used in function arguments when None should resolve to the current context manager set instance.
class PyAttribute
Wrapper around the generic MlirAttribute.
class PyBlock
Wrapper around an MlirBlock.
class PyDialect
User-level dialect object.
class PyDialectDescriptor
Wrapper around an MlirDialect.
class PyDialects
User-level object for accessing dialects with dotted syntax such as: ctx.dialect.std.
class PyGlobals
Globals that are always accessible once the extension has been initialized.
class PyInsertionPoint
An insertion point maintains a pointer to a Block and a reference operation.
class PyLocation
Wrapper around an MlirLocation.
class PyMlirContext
class PyModule
class PyNamedAttribute
Represents a Python MlirNamedAttr, carrying an optional owned name.
class PyObjectRef
Template for a reference to a concrete type which captures a python reference to its underlying python object.
class PyOperation
class PyOperationBase
Base class for PyOperation and PyOpView which exposes the primary, user visible methods for manipulating it.
class PyOpView
A PyOpView is equivalent to the C++ "Op" wrappers: these are the basis for providing more instance-specific accessors and serve as the base class for custom ODS-style operation classes.
class PyRegion
Wrapper around an MlirRegion.
class PyThreadContextEntry
Tracks an entry in the thread context stack.
class PyType
Wrapper around the generic MlirType.
class PyValue
Wrapper around the generic MlirValue.
Typedefs
using PyMlirContextRef = PyObjectRef< PyMlirContext >
Wrapper around MlirContext.
using PyModuleRef = PyObjectRef< PyModule >
using PyOperationRef = PyObjectRef< PyOperation >
Functions
void populateIRSubmodule (pybind11::module &m)
void populatePassManagerSubmodule (pybind11::module &m)
pybind11::error_already_set SetPyError (PyObject *excClass, const llvm::Twine &message)
Typedef Documentation
PyMlirContextRef
using mlir::python::PyMlirContextRef = typedef PyObjectRef<PyMlirContext>
Wrapper around MlirContext.
Definition at line 148 of file IRModules.h.
PyModuleRef
using mlir::python::PyModuleRef = typedef PyObjectRef<PyModule>
Definition at line 347 of file IRModules.h.
PyOperationRef
using mlir::python::PyOperationRef = typedef PyObjectRef<PyOperation>
Definition at line 409 of file IRModules.h.
Function Documentation
populateIRSubmodule()
void mlir::python::populateIRSubmodule (pybind11::module & m)
Referenced by mlir::python::PyValue::checkValid(), mlir::python::PyType::createFromCapsule(), and PYBIND11_MODULE().
populatePassManagerSubmodule()
void mlir::python::populatePassManagerSubmodule (pybind11::module & m)
Referenced by PYBIND11_MODULE().
SetPyError()
pybind11::error_already_set mlir::python::SetPyError (PyObject * excClass, const llvm::Twine & message)
Definition at line 14 of file PybindUtils.cpp.
Referenced by mlir::python::PyInsertionPoint::atBlockTerminator(), mlir::python::PyOperation::checkValid(), mlir::python::PyOperation::create(), mlir::python::PyType::createFromCapsule(), mlir::Sliceable< Derived, ElementTy >::dunderGetItem(), mlir::Sliceable< Derived, ElementTy >::dunderGetItemSlice(), mlir::python::PyDialects::getDialectForKey(), mlir::python::PyOperation::getParentOperation(), mlir::python::PyInsertionPoint::insert(), mlir::python::PyThreadContextEntry::popContext(), mlir::python::PyThreadContextEntry::popInsertionPoint(), mlir::python::PyThreadContextEntry::popLocation(), mlir::python::PyGlobals::registerDialectImpl(), mlir::python::PyGlobals::registerOperationImpl(), mlir::python::DefaultingPyMlirContext::resolve(), mlir::python::DefaultingPyLocation::resolve(), and toMlirStringRef().