MLIR: mlir Namespace Reference
mlir Namespace Reference
Include the generated interface declarations.
Namespaces
_dlloader
acc
async
AttributeTrait
detail
dialects
edsc
gpu
impl
ir
linalg
LLVM
matcher
matchers
MemoryEffects
NVVM
omp
op_definition_impl
ops_assertions
Overloaded arithmetic operators for SDBM expressions asserting that their arguments have the proper SDBM expression subtype.
OpTrait
passmanager
pdl
pdl_interp
pdl_to_pdl_interp
python
quant
ReductionTreeUtils
ROCDL
scf
shape
SideEffects
spirv
tblgen
tensor
tosa
transforms
TypeTrait
vector
Classes
class AbstractAttribute
This class contains all of the static information common to all instances of a registered Attribute.
class AbstractOperation
This is a "type erased" representation of a registered operation.
class AbstractType
This class contains all of the static information common to all instances of a registered Type.
struct AffineApplyNormalizer
An AffineApplyNormalizer is a helper class that supports renumbering operands of AffineApplyOp.
class AffineBinaryOpExpr
Affine binary operation expression.
class AffineBound
AffineBound represents a lower or upper bound in the for operation.
class AffineConstantExpr
An integer constant appearing in affine expression.
struct AffineCopyOptions
Explicit copy / DMA generation options for mlir::affineDataCopyGenerate.
class AffineDimExpr
A dimensional identifier appearing in an affine expression.
class AffineDmaStartOp
AffineDmaStartOp starts a non-blocking DMA operation that transfers data from a source memref to a destination memref.
class AffineDmaWaitOp
AffineDmaWaitOp blocks until the completion of a DMA operation associated with the tag element 'tag[index]'.
class AffineExpr
Base type for affine expression.
class AffineExprVisitor
Base class for AffineExpr visitors/walkers.
class AffineMap
A multi-dimensional affine map Affine map's are immutable like Type's, and they are uniqued.
class AffineMapAttr
class AffineReadOpInterface
class AffineSymbolExpr
A symbolic identifier appearing in an affine expression.
class AffineValueMap
An AffineValueMap is an affine map plus its ML value operands and results for analysis purposes.
class AffineWriteOpInterface
class AnalysisManager
This class represents an analysis manager for a particular operation instance.
class ArrayAttr
Array attributes are lists of other attributes.
class AsmState
This class provides management for the lifetime of the state used when printing the IR.
class Attribute
Attributes are known-constant values of operations.
class AttributeInterface
This class represents the base of an attribute interface.
class AttributeStorage
Base storage class appearing in an attribute.
class BaseMemRefType
Base MemRef for Ranked and Unranked variants.
class Block
Block represents an ordered list of Operations.
class BlockAndValueMapping
class BlockArgument
Block arguments are values.
class BlockNumberOfExecutionsInfo
Represents number of block executions information.
class BlockOperand
Terminator operations can have Block operands to represent successors.
class BlockRange
This class provides an abstraction over the different types of ranges over Blocks.
class BoolAttr
Special case of IntegerAttr to represent boolean integers, i.e., signless i1 integers.
class BufferAliasAnalysis
A straight-forward alias analysis which ensures that all aliases of all values will be determined.
class BufferizeTypeConverter
A helper type converter class that automatically populates the relevant materializations and type conversions for bufferization.
class BufferPlacementAllocs
A simple analysis that detects allocation operations.
class BufferPlacementTransformationBase
The base class for all BufferPlacement transformations.
class Builder
This class is a general helper class for creating context-global objects like types, attributes, and affine expressions.
class CallGraph
class CallGraphNode
This class represents a single callable in the callgraph.
struct CallInterfaceCallable
A callable is either a symbol, or an SSA value, that is referenced by a call-like operation.
class CallSiteLoc
Represents a location as call site.
class ComplexStructBuilder
class ComplexType
The 'complex' type represents a complex number with a parameterized element type, which is composed of a real and imaginary value of that element type.
struct ComputationSliceState
ComputationSliceState aggregates loop IVs, loop bound AffineMaps and their associated operands for a set of loops within a loop nest (typically the set of loops surrounding a store operation).
class ConstantFloatOp
This is a refinement of the "constant" op for the case where it is returning a float value of FloatType.
class ConstantIndexOp
This is a refinement of the "constant" op for the case where it is returning an integer value of Index type.
class ConstantIntOp
This is a refinement of the "constant" op for the case where it is returning an integer value of IntegerType.
class ContractionOpLowering
Progressive lowering of ContractionOp.
class ContractionOpToDotLowering
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to an output-size-unrolled sequence: ``` out = constant ...
class ContractionOpToMatmulOpLowering
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to:
%flattened_a = vector.shape_cast %a
%flattened_b = vector.shape_cast %b
%flattened_d = vector.matmul %flattened_a, %flattened_b
%d = vector.shape_cast %%flattened_d
%e = add %c, %d
vector.matmul later lowers to llvm.matrix.multiply.
class ContractionOpToOuterProductOpLowering
Progressive lowering of a vector.contract a, b, c with row-major matmul semantics to a reduction_size-unrolled sequence: ``` at = vector.transpose a, [1, 0] bRow0 = vector.extract b[0] atRow0 = vector.extract at[0] c0 = vector.outerproduct atRow0, bRow0, c ...
class ConversionPattern
Base class for the conversion patterns.
class ConversionPatternRewriter
This class implements a pattern rewriter for use with ConversionPatterns.
class ConversionTarget
This class describes a specific conversion target.
class ConvertOpToLLVMPattern
Utility class for operation conversions targeting the LLVM dialect that match exactly one source operation.
class ConvertToLLVMPattern
Base class for operation conversions targeting the LLVM IR dialect.
struct CopyGenerateResult
Result for calling generateCopyForMemRegion.
class DenseElementsAttr
An attribute that represents a reference to a dense vector or tensor object.
class DenseFPElementsAttr
An attribute that represents a reference to a dense float vector or tensor object.
class DenseIntElementsAttr
An attribute that represents a reference to a dense integer vector or tensor object.
class DenseIntOrFPElementsAttr
An attribute class for specializing behavior of Int and Floating-point densely packed string arrays.
class DenseStringElementsAttr
An attribute class for representing dense arrays of strings.
struct DependenceComponent
struct DependenceResult
Checks whether two accesses to the same memref access the same element.
class Diagnostic
This class contains all of the information necessary to report a diagnostic to the DiagnosticEngine.
class DiagnosticArgument
A variant type that holds a single argument for a diagnostic.
class DiagnosticEngine
This class is the main interface for diagnostics.
class Dialect
Dialects are groups of MLIR operations, types and attributes, as well as behavior associated with the entire group.
class DialectAsmParser
The DialectAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
class DialectAsmPrinter
This is a pure-virtual base class that exposes the asmprinter hooks necessary to implement a custom printAttribute/printType() method on a dialect.
class DialectDecodeAttributesInterface
Define an interface to decode opaque constant tensor.
class DialectFoldInterface
Define a fold interface to allow for dialects to control specific aspects of the folding behavior for operations they define.
class DialectInlinerInterface
This is the interface that must be implemented by the dialects of operations to be inlined.
class DialectInterface
This class represents an interface overridden for a single dialect.
class DialectInterfaceCollection
A collection of dialect interfaces within a context, for a given concrete interface type.
class DialectRegistry
The DialectRegistry maps a dialect namespace to a constructor for the matching dialect.
class DictionaryAttr
Dictionary attribute is an attribute that represents a sorted collection of named attribute values.
class DmaStartOp
class DmaWaitOp
class DominanceInfo
A class for computing basic dominance information.
class ElementsAttr
A base attribute that represents a reference to a static shaped tensor or vector constant.
struct EmptyPipelineOptions
A default empty option struct to be used for passes that do not need to take any options.
class ExecutionEngine
JIT-backed execution engine for MLIR modules.
class FailureOr
This class provides support for representing a failure result, or a valid value of type T.
class FileLineColLoc
Represents a location derived from a file/line/column location.
class FilteredValueUseIterator
class FlatAffineConstraints
A flat list of affine equalities and inequalities in the form.
class FlatSymbolRefAttr
A symbol reference with a reference path containing a single element.
class FloatAttr
class FloatType
struct Fraction
A class to represent fractions.
class FrozenRewritePatternList
This class represents a frozen set of patterns that can be processed by a pattern applicator.
class FunctionPass
A model for providing function pass specific utilities.
class FunctionType
Function types map from a list of inputs to a list of results.
class FusedLoc
Represents a value composed of multiple source constructs, with an optional metadata attribute.
struct FusionResult
struct FusionStrategy
Describes the fusion strategy to be used in the Affine loop fusion utilities.
class GBRSimplex
Given a simplex for a polytope, construct a new simplex whose variables are identified with a pair of points (x, y) in the original polytope.
class GenInfo
Structure to group information about a generator (argument to invoke via mlir-tblgen, description, and generator function).
struct GenNameParser
Adds command line option for each registered generator.
struct GenRegistration
GenRegistration provides a global initializer that registers a generator function.
struct GPUFuncOpLowering
struct GPUIndexIntrinsicOpLowering
struct GPUReturnOpLowering
class Identifier
This class represents a uniqued string owned by an MLIRContext.
class InFlightDiagnostic
This class represents a diagnostic that is inflight and set to be reported.
class InlinerInterface
This interface provides the hooks into the inlining interface.
class IntegerAttr
class IntegerSet
An integer set representing a conjunction of one or more affine equalities and inequalities.
class IntegerSetAttr
class IntegerType
Integer types can have arbitrary bitwidth up to a large fixed limit.
class IntInfty
A utility class for SDBM to represent an integer with potentially infinite positive value.
class IRObjectWithUseList
This class represents a single IR object that contains a use list.
class IROperand
A reference to a value, suitable for use as an operand of an operation.
struct JitRunnerConfig
class Lexer
This class breaks up the current file into a token stream.
class Liveness
Represents an analysis for computing liveness information from a given top-level operation.
class LivenessBlockInfo
This class represents liveness information on block level.
class LLVMConversionTarget
Derived class that automatically populates legalization information for different LLVM ops.
class LLVMTypeConverter
Conversion from types in the Standard dialect to the LLVM IR dialect.
class Location
This class defines the main interface for locations in MLIR and acts as a non-nullable wrapper around a LocationAttr.
class LocationAttr
Location objects represent source locations information in MLIR.
struct LogicalResult
Values that can be used to signal success/failure.
struct LoopNestStats
LoopNestStats aggregates various per-loop statistics (eg.
struct LowerToLLVMOptions
Options to control the Standard dialect to LLVM lowering.
struct LowerVectorToLLVMOptions
Options to control Vector to LLVM lowering.
class Matrix
This is a simple class to represent a resizable matrix.
struct MemRefAccess
Encapsulates a memref load or store access information.
class MemRefDescriptor
Helper class to produce LLVM dialect operations extracting or inserting elements of a MemRef descriptor.
class MemRefDescriptorView
Helper class allowing the user to access a range of Values that correspond to an unpacked memref descriptor using named accessors.
struct MemRefRegion
A region of a memref's data space; this is typically constructed by analyzing load/store op's on this memref and the index space of loops surrounding such op's.
class MemRefType
MemRef types represent a region of memory that have a shape with a fixed number of dimensions.
class MLIRContext
MLIRContext is the top-level object for a collection of MLIR operations.
class MLIRContextImpl
This is the implementation of the MLIRContext class, using the pImpl idiom.
class ModuleAnalysisManager
An analysis manager class specifically for the top-level operation.
struct MutableAffineMap
A mutable affine map. Its affine expressions are however unique.
class MutableDictionaryAttr
A MutableDictionaryAttr is a mutable wrapper around a DictionaryAttr.
class MutableOperandRange
This class provides a mutable adaptor for a range of operands.
class NamedAttrList
NamedAttrList is array of NamedAttributes that tracks whether it is sorted and does some basic work to remain sorted.
class NameLoc
Represents an identity name attached to a child location.
class NestedMatch
An NestedPattern captures nested patterns in the IR.
class NestedPattern
class NestedPatternContext
RAII structure to transparently manage the bump allocator for NestedPattern and NestedMatch classes.
class NumberOfExecutions
Represents an analysis for computing how many times a block or an operation within a region is executed each time that region is entered.
class OneToOneConvertToLLVMPattern
Generic implementation of one-to-one conversion from "SourceOp" to "TargetOp" where the latter belongs to the LLVM dialect or an equivalent.
class Op
This provides public APIs that all operations should have.
class OpaqueAttr
Opaque attributes represent attributes of non-registered dialects.
class OpaqueElementsAttr
An opaque attribute that represents a reference to a vector or tensor constant with opaque content.
class OpaqueLoc
Represents a location that is external to MLIR.
class OpaqueType
Opaque types represent types of non-registered dialects.
class OpAsmDialectInterface
class OpAsmParser
The OpAsmParser has methods for interacting with the asm parser: parsing things from it, emitting errors etc.
class OpAsmPrinter
This is a pure-virtual base class that exposes the asmprinter hooks necessary to implement a custom print() method.
class OpBuilder
This class helps build Operations.
struct OpConversionPattern
OpConversionPattern is a wrapper around ConversionPattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
class OperandElementTypeIterator
class OperandRange
This class implements the operand iterators for the Operation class.
class Operation
Operation is a basic unit of execution within MLIR.
struct OperationEquivalence
This class provides utilities for computing if two operations are equivalent.
class OperationFolder
A utility class for folding operations, and unifying duplicated constants generated along the way.
class OperationName
class OperationPass
Pass to transform an operation of a specific type.
class OperationPass< void >
Pass to transform an operation.
struct OperationState
This represents an operation in an abstracted form, suitable for use with the builder APIs.
class OpFoldResult
This class represents a single result from folding an operation.
class OpInterface
This class represents the base of an operation interface.
class OpOperand
This class represents an operand of an operation.
class OpPassManager
This class represents a pass manager that runs passes on a specific operation type.
class OpPrintingFlags
Set of flags used to control the behavior of the various IR print methods (e.g.
class OpReducer
The OpReducer class defines a variant generator method that produces multiple variants by eliminating different OpType operations from the parent module.
class OpReducerImpl
class OpResult
This is a value defined by a result of an operation.
struct OpRewritePattern
OpRewritePattern is a wrapper around RewritePattern that allows for matching and rewriting against an instance of a derived operation class as opposed to a raw Operation.
class OpState
This is the concrete base class that holds the operation pointer and has non-generic methods that only depend on State (to avoid having them instantiated on template types that don't affect them.
class OptionalParseResult
This class implements Optional functionality for ParseResult.
struct OpToFuncCallLowering
Rewriting that replace SourceOp with a CallOp to f32Func or f64Func depending on the element type that Op operates upon.
class OptReductionPass
class OwningModuleRef
This class acts as an owning reference to a module, and will automatically destroy the held module on destruction if the held module is valid.
class OwningOpRef
This class acts as an owning reference to an op, and will automatically destroy the held op on destruction if the held op is valid.
class OwningRewritePatternList
class ParallelDiagnosticHandler
This class is a utility diagnostic handler for use when multi-threading some part of the compiler where diagnostics may be emitted.
class ParseResult
This class represents success/failure for operation parsing.
class Pass
The abstract base pass class.
class PassInfo
A structure to represent the information for a derived pass class.
class PassInstrumentation
PassInstrumentation provides several entry points into the pass manager infrastructure.
class PassInstrumentor
This class holds a collection of PassInstrumentation objects, and invokes their respective call backs.
class PassManager
The main pass manager and pipeline builder.
class PassNameCLParser
This class implements a command-line parser spefically for MLIR pass names.
class PassPipelineCLParser
This class implements a command-line parser for MLIR passes.
class PassPipelineInfo
A structure to represent the information of a registered pass pipeline.
class PassPipelineOptions
Subclasses of PassPipelineOptions provide a set of options that can be used to initialize a pass pipeline.
struct PassPipelineRegistration
PassPipelineRegistration provides a global initializer that registers a Pass pipeline builder routine.
struct PassPipelineRegistration< EmptyPipelineOptions >
Convenience specialization of PassPipelineRegistration for EmptyPassOptions that does not pass an empty options struct to the pass builder function.
struct PassRegistration
PassRegistration provides a global initializer that registers a Pass allocation routine for a concrete pass instance.
class PassRegistryEntry
Structure to group information about a passes and pass pipelines (argument to invoke via mlir-opt, description, pass pipeline builder).
class PassWrapper
This class provides a CRTP wrapper around a base pass class to define several necessary utility methods.
class Pattern
This class contains all of the data related to a pattern, but does not contain any methods or logic for the actual matching.
class PatternApplicator
This class manages the application of a group of rewrite patterns, with a user-provided cost model.
class PatternBenefit
This class represents the benefit of a pattern match in a unitless scheme that ranges from 0 (very little benefit) to 65K.
class PatternRewriter
This class coordinates the application of a pattern to the current function, providing a way to create operations and keep track of what gets deleted.
class PDLPatternModule
This class contains all of the necessary data for a set of PDL patterns, or pattern rewrites specified in the form of the PDL dialect.
class PDLValue
Storage type of byte-code interpreter values.
class PostDominanceInfo
A class for computing basic postdominance information.
class PredecessorIterator
Implement a predecessor iterator for blocks.
class PresburgerSet
This class can represent a union of FlatAffineConstraints, with support for union, intersection, subtraction and complement operations, as well as sampling.
class PyFileAccumulator
Accumulates int a python file-like object, either writing text (default) or binary.
struct PyPrintAccumulator
Accumulates into a python string from a method that accepts an MlirStringCallback.
struct PySinglePartStringAccumulator
Accumulates into a python string from a method that is expected to make one (no more, no less) call to the callback (asserts internally on violation).
struct Range
Auxiliary range data structure to unpack the offset, size and stride operands into a list of triples.
class RankedTensorType
Ranked tensor types represent multi-dimensional arrays that have a shape with a fixed number of dimensions.
class raw_indented_ostream
raw_ostream subclass that simplifies indention a sequence of code.
class ReductionNode
This class defines the ReductionNode which is used to wrap the module of a generated variant and keep track of the necessary metadata for the reduction pass.
class ReductionTreePass
This class defines the Reduction Tree Pass.
class Region
This class contains a list of basic blocks and a link to the parent operation it is attached to.
class RegionRange
This class provides an abstraction over the different types of ranges over Regions.
class RegionSuccessor
This class represents a successor of a region.
class ResultElementTypeIterator
class ResultRange
This class implements the result iterators for the Operation class.
class RewritePattern
RewritePattern is the common base class for all DAG to DAG replacements.
struct ScfToSPIRVContext
struct ScfToSPIRVContextImpl
class ScopedDiagnosticHandler
This diagnostic handler is a simple RAII class that registers and erases a diagnostic handler on a given context.
class SDBM
Striped difference-bound matrix is a representation of an integer set bound by a system of SDBMExprs interpreted as inequalities "expr <= 0".
class SDBMConstantExpr
SDBM constant expression, wraps a 64-bit integer.
class SDBMDialect
class SDBMDiffExpr
SDBM difference expression.
class SDBMDimExpr
SDBM dimension expression.
class SDBMDirectExpr
SDBM direct expression includes exactly one variable (symbol or dimension), which is not negated in the expression.
class SDBMExpr
Striped Difference-Bounded Matrix (SDBM) expression is a base left-hand side expression for the SDBM framework.
class SDBMInputExpr
SDBM "input" variable expression can be either a dimension identifier or a symbol identifier.
class SDBMNegExpr
Negation of an SDBM variable expression.
class SDBMStripeExpr
SDBM stripe expression "x # C" where "x" is a term expression, "C" is a constant expression and "#" is the stripe operator defined as: x # C = x - x mod C.
class SDBMSumExpr
SDBM sum expression. LHS is a term expression and RHS is a constant.
class SDBMSymbolExpr
SDBM symbol expression.
class SDBMTermExpr
SDBM term expression can be one of:
class SDBMVaryingExpr
SDBM varying expression can be one of:
class SDBMVisitor
A visitor class for SDBM expressions.
class ShapedType
This is a common base class between Vector, UnrankedTensor, RankedTensor, and MemRef types because they share behavior and semantics around shape, rank, and fixed element type.
class ShapedTypeComponents
ShapedTypeComponents that represents the components of a ShapedType.
class SimpleAffineExprFlattener
class SimpleObjectCache
A simple object cache following Lang's LLJITWithObjectCache example.
class Simplex
This class implements a version of the Simplex and Generalized Basis Reduction algorithms, which can perform analysis of integer sets with affine inequalities and equalities.
class Sliceable
A CRTP base class for pseudo-containers willing to support Python-type slicing access on top of indexed access.
class SourceMgrDiagnosticHandler
This class is a utility diagnostic handler for use with llvm::SourceMgr.
class SourceMgrDiagnosticVerifierHandler
This class is a utility diagnostic handler for use with llvm::SourceMgr that verifies that emitted diagnostics match 'expected-*' lines on the corresponding line of the source file.
class SparseElementsAttr
An attribute that represents a reference to a sparse vector or tensor object.
class SPIRVOpLowering
Base class to define a conversion pattern to lower SourceOp into SPIR-V.
class SPIRVToLLVMConversion
class SPIRVTypeConverter
Type conversion from builtin types to SPIR-V types for shader interface.
class SplatElementsAttr
An attribute that represents a reference to a splat vector or tensor constant, meaning all of the elements have the same value.
class StorageUniquer
A utility class to get or create instances of "storage classes".
class StringAttr
class StructBuilder
Helper class to produce LLVM dialect operations extracting or inserting values to a struct.
class SuccessorRange
This class implements the successor iterators for Block.
class SymbolRefAttr
A symbol reference attribute represents a symbolic reference to another operation.
class SymbolTable
This class allows for representing and managing the symbol table used by operations with the 'SymbolTable' trait.
class SymbolTableCollection
This class represents a collection of SymbolTables.
class TensorType
Tensor types represent multi-dimensional arrays, and have two variants: RankedTensorType and UnrankedTensorType.
class Tester
This class is used to keep track of the testing environment of the tool.
class ThreadLocalCache
This class provides support for defining a thread local object with non static storage duration.
class Token
This represents a token in the MLIR syntax.
struct TranslateFromMLIRRegistration
struct TranslateRegistration
struct TranslateToMLIRRegistration
Use Translate[ToMLIR|FromMLIR]Registration as an initializer that registers a function and associates it with name.
struct TranslationParser
A command line parser for translation functions.
class TupleType
Tuple types represent a collection of other types.
class Type
Instances of the Type class are uniqued, have an immutable identifier and an optional mutable component.
class TypeAttr
class TypeConverter
Type conversion class.
class TypeID
This class provides an efficient unique identifier for a specific C++ type.
class TypeInterface
This class represents the base of a type interface.
class TypeRange
This class provides an abstraction over the various different ranges of value types.
class TypeStorage
Base storage class appearing in a Type.
class UnitAttr
Unit attributes are attributes that hold no specific value and are given meaning by their existence.
class UnknownLoc
Represents an unknown location.
class UnrankedMemRefDescriptor
class UnrankedMemRefType
Unranked MemRef type represent multi-dimensional MemRefs that have an unknown rank.
class UnrankedTensorType
Unranked tensor types represent multi-dimensional arrays that have an unknown shape.
class Value
This class represents an instance of an SSA value in the MLIR system, representing a computable value that has a type and a set of users.
class ValueDecomposer
This class provides a hook that expands one Value into multiple Value's, with a TypeConverter-inspired callback registration mechanism.
class ValueRange
This class provides an abstraction over the different types of ranges over Values.
class ValueTypeIterator
This class implements iteration on the types of a given range of values.
class ValueTypeRange
This class implements iteration on the types of a given range of values.
class ValueUseIterator
An iterator class that allows for iterating over the uses of an IR operand type.
class ValueUserIterator
An iterator over the users of an IRObject.
class VectorConvertToLLVMPattern
Basic lowering implementation to rewrite Ops with just one result to the LLVM Dialect.
struct VectorizationStrategy
Holds parameters to perform n-D vectorization on a single loop nest.
struct VectorTransferRewriter
Implements lowering of TransferReadOp and TransferWriteOp to a proper abstraction for the hardware.
struct VectorTransferToSCFOptions
Control whether unrolling is used when lowering vector transfer ops to SCF.
class VectorType
Vector types represent multi-dimensional SIMD vectors, and have a fixed known constant shape with one or more dimension.
class VulkanLayoutUtils
According to the Vulkan spec "14.5.4. Offset and Stride Assignment": "There are different alignment requirements depending on the specific resources and on the features enabled on the device.
class WalkResult
A utility result that is used to signal if a walk method should be interrupted or advance.
Typedefs
using VectorizableLoopFun = std::function< bool(AffineForOp)>
using FilterFunctionType = std::function< bool(Operation &)>
A NestedPattern is a nested operation walker that:
using TransitiveFilter = std::function< bool(Operation *)>
Type of the condition to limit the propagation of transitive use-defs.
using OwnedBlob = std::unique_ptr< std::vector< char > >
using BlobGenerator = std::function< OwnedBlob(const std::string &, Location, StringRef)>
using LoweringCallback = std::function< std::unique_ptr< llvm::Module >(Operation *, llvm::LLVMContext &, StringRef)>
using NamedAttribute = std::pair< Identifier, Attribute >
NamedAttribute is combination of a name, represented by an Identifier, and a value, represented by an Attribute.
using DefaultAttributeStorage = AttributeStorage
Default storage type for attributes that require no additional initialization or storage.
using AttributeStorageAllocator = StorageUniquer::StorageAllocator
using DialectAllocatorFunction = std::function< Dialect *(MLIRContext *)>
using DominanceInfoNode = llvm::DomTreeNodeBase< Block >
using OpAsmSetValueNameFn = function_ref< void(Value, StringRef)>
A functor used to set the name of the start of a result group of an operation.
using PDLConstraintFunction = std::function< LogicalResult(ArrayRef< PDLValue >, ArrayAttr, PatternRewriter &)>
A generic PDL pattern constraint function.
using PDLCreateFunction = std::function< PDLValue(ArrayRef< PDLValue >, ArrayAttr, PatternRewriter &)>
A native PDL creation function.
using PDLRewriteFunction = std::function< void(Operation *, ArrayRef< PDLValue >, ArrayAttr, PatternRewriter &)>
A native PDL rewrite function.
using PDLSingleEntityConstraintFunction = std::function< LogicalResult(PDLValue, ArrayAttr, PatternRewriter &)>
A generic PDL pattern constraint function.
using DefaultTypeStorage = TypeStorage
Default storage type for types that require no additional initialization or storage.
using TypeStorageAllocator = StorageUniquer::StorageAllocator
This is a utility allocator used to allocate memory for instances of derived Types.
using OperandElementTypeRange = iterator_range< OperandElementTypeIterator >
using ResultElementTypeRange = iterator_range< ResultElementTypeIterator >
using PassRegistryFunction = std::function< LogicalResult(OpPassManager &, StringRef options, function_ref< LogicalResult(const Twine &)> errorHandler)>
A registry function that adds passes to the given pass manager.
using PassAllocatorFunction = std::function< std::unique_ptr< Pass >()>
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>>
using DenseMap = llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >
template<typename ValueT , typename ValueInfoT = DenseMapInfo<ValueT>>
using DenseSet = llvm::DenseSet< ValueT, ValueInfoT >
template<typename AllocatorTy = llvm::MallocAllocator>
using StringSet = llvm::StringSet< AllocatorTy >
template<typename T , typename R = T>
using StringSwitch = llvm::StringSwitch< T, R >
template<typename T , typename ResultT = void>
using TypeSwitch = llvm::TypeSwitch< T, ResultT >
template<typename Fn >
using function_ref = llvm::function_ref< Fn >
using ChunkBufferHandler = function_ref< LogicalResult(std::unique_ptr< llvm::MemoryBuffer > chunkBuffer, raw_ostream &os)>
using GenFunction = std::function< bool(const llvm::RecordKeeper &recordKeeper, raw_ostream &os)>
Generator function to invoke.
using Loops = SmallVector< scf::ForOp, 8 >
Performs tiling fo imperfectly nested loops (with interchange) by strip-mining the forOps by sizes and sinking them, in their order of occurrence in forOps, under each of the targets.
using TileLoops = std::pair< Loops, Loops >
using TranslateSourceMgrToMLIRFunction = std::function< OwningModuleRef(llvm::SourceMgr &sourceMgr, MLIRContext *)>
Interface of the function that translates the sources managed by sourceMgr to MLIR.
using TranslateStringRefToMLIRFunction = std::function< OwningModuleRef(llvm::StringRef, MLIRContext *)>
Interface of the function that translates the given string to MLIR.
using TranslateFromMLIRFunction = std::function< LogicalResult(ModuleOp, llvm::raw_ostream &output)>
Interface of the function that translates MLIR to a different format and outputs the result to a stream.
using TranslateFunction = std::function< LogicalResult(llvm::SourceMgr &sourceMgr, llvm::raw_ostream &output, MLIRContext *)>
Interface of the function that performs file-to-file translation involving MLIR.
using Direction = Simplex::Direction
Enumerations
enum SDBMExprKind {
SDBMExprKind::Add, SDBMExprKind::Stripe, SDBMExprKind::Diff, SDBMExprKind::Constant,
SDBMExprKind::DimId, SDBMExprKind::SymbolId, SDBMExprKind::Neg
}
enum IteratorType { IteratorType::Parallel, IteratorType::Reduction }
Typed representation for loop type strings.
enum AffineExprKind {
AffineExprKind::Add, AffineExprKind::Mul, AffineExprKind::Mod, AffineExprKind::FloorDiv,
AffineExprKind::CeilDiv, AffineExprKind::LAST_AFFINE_BINARY_OP = CeilDiv, AffineExprKind::Constant, AffineExprKind::DimId,
AffineExprKind::SymbolId
}
enum DiagnosticSeverity { DiagnosticSeverity::Note, DiagnosticSeverity::Warning, DiagnosticSeverity::Error, DiagnosticSeverity::Remark }
Defines the different supported severity of a diagnostic.
enum OperationProperty { OperationProperty::Commutative = 0x1, OperationProperty::Terminator = 0x2, OperationProperty::IsolatedFromAbove = 0x4 }
enum RegionKind { RegionKind::SSACFG, RegionKind::Graph }
The kinds of regions contained in an operation.
enum PassDisplayMode { PassDisplayMode::List, PassDisplayMode::Pipeline }
An enum describing the different display modes for the information within the pass manager.
enum TraversalMode { SinglePath, Backtrack, MultiPath }
traversal.
Functions
void getReachableAffineApplyOps (ArrayRef< Value > operands, SmallVectorImpl< Operation *> &affineApplyOps)
Returns in affineApplyOps, the sequence of those AffineApplyOp Operations that are reachable via a search starting from operands and ending at those operands that are not the result of an AffineApplyOp.
LogicalResult getIndexSet (MutableArrayRef< Operation *> ops, FlatAffineConstraints *domain)
Builds a system of constraints with dimensional identifiers corresponding to the loop IVs of the forOps and AffineIfOp's operands appearing in that order.
DependenceResult checkMemrefAccessDependence (const MemRefAccess &srcAccess, const MemRefAccess &dstAccess, unsigned loopDepth, FlatAffineConstraints *dependenceConstraints, SmallVector< DependenceComponent, 2 > *dependenceComponents, bool allowRAR=false)
bool hasDependence (DependenceResult result)
Utility function that returns true if the provided DependenceResult corresponds to a dependence result.
void getDependenceComponents (AffineForOp forOp, unsigned maxLoopDepth, std::vector< SmallVector< DependenceComponent, 2 >> *depCompsVec)
Returns in 'depCompsVec', dependence components for dependences between all load and store ops in loop nest rooted at 'forOp', at loop depths in range [1, maxLoopDepth].
LogicalResult getFlattenedAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols, SmallVectorImpl< int64_t > *flattenedExpr, FlatAffineConstraints *cst=nullptr)
Flattens 'expr' into 'flattenedExpr', which contains the coefficients of the dimensions, symbols, and additional variables that represent floor divisions of dimensions, symbols, and in turn other floor divisions.
LogicalResult getFlattenedAffineExprs (AffineMap map, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs, FlatAffineConstraints *cst=nullptr)
Flattens the result expressions of the map to their corresponding flattened forms and set in 'flattenedExprs'.
LogicalResult getFlattenedAffineExprs (IntegerSet set, std::vector< SmallVector< int64_t, 8 >> *flattenedExprs, FlatAffineConstraints *cst=nullptr)
void buildTripCountMapAndOperands (AffineForOp forOp, AffineMap *map, SmallVectorImpl< Value > *operands)
Returns the trip count of the loop as an affine map with its corresponding operands if the latter is expressible as an affine expression, and nullptr otherwise.
Optional< uint64_t > getConstantTripCount (AffineForOp forOp)
Returns the trip count of the loop if it's a constant, None otherwise.
uint64_t getLargestDivisorOfTripCount (AffineForOp forOp)
Returns the greatest known integral divisor of the trip count.
DenseSet< Value, DenseMapInfo< Value > > getInvariantAccesses (Value iv, ArrayRef< Value > indices)
Given an induction variable iv of type AffineForOp and indices of type IndexType, returns the set of indices that are independent of iv.
bool isVectorizableLoopBody (AffineForOp loop, NestedPattern &vectorTransferMatcher)
Checks whether the loop is structurally vectorizable; i.e.
bool isVectorizableLoopBody (AffineForOp loop, int *memRefDim, NestedPattern &vectorTransferMatcher)
Checks whether the loop is structurally vectorizable and that all the LoadOp and StoreOp matched have access indexing functions that are are either:
bool isOpwiseShiftValid (AffineForOp forOp, ArrayRef< uint64_t > shifts)
Checks where SSA dominance would be violated if a for op's body operations are shifted by the specified shifts.
bool defaultFilterFunction (Operation &)
int compare (Fraction x, Fraction y)
Three-way comparison between two fractions.
int64_t floor (Fraction f)
int64_t ceil (Fraction f)
Fraction operator- (Fraction x)
bool operator< (Fraction x, Fraction y)
bool operator<= (Fraction x, Fraction y)
bool operator== (Fraction x, Fraction y)
bool operator> (Fraction x, Fraction y)
bool operator>= (Fraction x, Fraction y)
Fraction operator* (Fraction x, Fraction y)
void getForwardSlice (Operation *op, llvm::SetVector< Operation *> *forwardSlice, TransitiveFilter filter=[](Operation *) { return true;})
Fills forwardSlice with the computed forward slice (i.e.
void getBackwardSlice (Operation *op, llvm::SetVector< Operation *> *backwardSlice, TransitiveFilter filter=[](Operation *) { return true;})
Fills backwardSlice with the computed backward slice (i.e.
llvm::SetVector< Operation * > getSlice (Operation *op, TransitiveFilter backwardFilter=[](Operation *) { return true;}, TransitiveFilter forwardFilter=[](Operation *) { return true;})
Iteratively computes backward slices and forward slices until a fixed point is reached.
llvm::SetVector< Operation * > topologicalSort (const llvm::SetVector< Operation *> &toSort)
Multi-root DAG topological sort.
void getLoopIVs (Operation &op, SmallVectorImpl< AffineForOp > *loops)
Populates 'loops' with IVs of the loops surrounding 'op' ordered from the outermost 'affine.for' operation to the innermost one.
void getEnclosingAffineForAndIfOps (Operation &op, SmallVectorImpl< Operation *> *ops)
Populates 'ops' with IVs of the loops surrounding op, along with affine.if operations interleaved between these loops, ordered from the outermost affine.for or affine.if operation to the innermost one.
unsigned getNestingDepth (Operation *op)
Returns the nesting depth of this operation, i.e., the number of loops surrounding this operation.
void getSequentialLoops (AffineForOp forOp, llvm::SmallDenseSet< Value, 8 > *sequentialLoops)
Returns in 'sequentialLoops' all sequential loops in loop nest rooted at 'forOp'.
void getComputationSliceState (Operation *depSourceOp, Operation *depSinkOp, FlatAffineConstraints *dependenceConstraints, unsigned loopDepth, bool isBackwardSlice, ComputationSliceState *sliceState)
Computes the computation slice loop bounds for one loop nest as affine maps of the other loop nest's IVs and symbols, using 'dependenceConstraints' computed between 'depSourceAccess' and 'depSinkAccess'.
LogicalResult computeSliceUnion (ArrayRef< Operation *> opsA, ArrayRef< Operation *> opsB, unsigned loopDepth, unsigned numCommonLoops, bool isBackwardSlice, ComputationSliceState *sliceUnion)
Computes in 'sliceUnion' the union of all slice bounds computed at 'loopDepth' between all dependent pairs of ops in 'opsA' and 'opsB'.
AffineForOp insertBackwardComputationSlice (Operation *srcOpInst, Operation *dstOpInst, unsigned dstLoopDepth, ComputationSliceState *sliceState)
Creates a clone of the computation contained in the loop nest surrounding 'srcOpInst', slices the iteration space of src loop based on slice bounds in 'sliceState', and inserts the computation slice at the beginning of the operation block of the loop at 'dstLoopDepth' in the loop nest surrounding 'dstOpInst'.
Optional< uint64_t > getMemRefSizeInBytes (MemRefType memRefType)
Returns the size of memref data in bytes if it's statically shaped, None otherwise.
template<typename LoadOrStoreOpPointer >
LogicalResult boundCheckLoadOrStoreOp (LoadOrStoreOpPointer loadOrStoreOp, bool emitError=true)
Checks a load or store op for an out of bound access; returns failure if the access is out of bounds along any of the dimensions, success otherwise.
unsigned getNumCommonSurroundingLoops (Operation &A, Operation &B)
Returns the number of surrounding loops common to both A and B.
Optional< int64_t > getMemoryFootprintBytes (AffineForOp forOp, int memorySpace=-1)
Gets the memory footprint of all data touched in the specified memory space in bytes; if the memory space is unspecified, considers all memory spaces.
bool isLoopParallel (AffineForOp forOp)
Returns true if `forOp' is a parallel loop.
IntegerSet simplifyIntegerSet (IntegerSet set)
Simplify the integer set by simplifying the underlying affine expressions by flattening and some simple inference.
unsigned getInnermostCommonLoopDepth (ArrayRef< Operation *> ops, SmallVectorImpl< AffineForOp > *surroundingLoops=nullptr)
Returns the innermost common loop depth for the set of operations in 'ops'.
Value expandAffineExpr (OpBuilder &builder, Location loc, AffineExpr expr, ValueRange dimValues, ValueRange symbolValues)
Emit code that computes the given affine expression using standard arithmetic operations applied to the provided dimension and symbol values.
Optional< SmallVector< Value, 8 > > expandAffineMap (OpBuilder &builder, Location loc, AffineMap affineMap, ValueRange operands)
Create a sequence of operations that implement the affineMap applied to the given operands (as it it were an AffineApplyOp).
void populateAffineToStdConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Collect a set of patterns to convert from the Affine dialect to the Standard dialect, in particular convert structured affine control flow into CFG branch-based control flow.
void populateAffineToVectorConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Collect a set of patterns to convert vector-related Affine ops to the Vector dialect.
Value lowerAffineLowerBound (AffineForOp op, OpBuilder &builder)
Emit code that computes the lower bound of the given affine loop using standard arithmetic operations.
Value lowerAffineUpperBound (AffineForOp op, OpBuilder &builder)
Emit code that computes the upper bound of the given affine loop using standard arithmetic operations.
std::unique_ptr< Pass > createLowerAffinePass ()
Lowers affine control flow operations (ForStmt, IfStmt and AffineApplyOp) to equivalent lower-level constructs (flow of basic blocks and arithmetic primitives).
void populateArmNeonToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from theArmNeon dialect to LLVM.
void populateArmSVEToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the ArmSVE dialect to LLVM.
std::unique_ptr< OperationPass< ModuleOp > > createConvertAsyncToLLVMPass ()
Create a pass to convert Async operations to the LLVM dialect.
void populateAVX512ToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the AVX512 dialect to LLVM.
std::unique_ptr< OperationPass< ModuleOp > > createGpuToLLVMConversionPass (StringRef gpuBinaryAnnotation="")
Creates a pass to convert a gpu.launch_func operation into a sequence of GPU runtime calls.
void populateGpuToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns, StringRef gpuBinaryAnnotation)
Collect a set of patterns to convert from the GPU dialect to LLVM.
std::unique_ptr< OperationPass< gpu::GPUModuleOp > > createConvertGPUKernelToBlobPass (LoweringCallback loweringCallback, BlobGenerator blobGenerator, StringRef triple, StringRef targetChip, StringRef features, StringRef gpuBinaryAnnotation)
Creates a pass to convert kernel functions into GPU target object blobs.
void configureGpuToNVVMConversionLegality (ConversionTarget &target)
Configure target to convert from the GPU dialect to NVVM.
void populateGpuToNVVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the GPU dialect to NVVM.
std::unique_ptr< OperationPass< gpu::GPUModuleOp > > createLowerGpuOpsToNVVMOpsPass (unsigned indexBitwidth=kDeriveIndexBitwidthFromDataLayout)
Creates a pass that lowers GPU dialect operations to NVVM counterparts.
void populateGpuToROCDLConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the GPU dialect to ROCDL.
void configureGpuToROCDLConversionLegality (ConversionTarget &target)
Configure target to convert from the GPU dialect to ROCDL.
std::unique_ptr< OperationPass< gpu::GPUModuleOp > > createLowerGpuOpsToROCDLOpsPass (unsigned indexBitwidth=kDeriveIndexBitwidthFromDataLayout)
Creates a pass that lowers GPU dialect operations to ROCDL counterparts.
void populateGPUToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating GPU Ops to SPIR-V ops.
std::unique_ptr< OperationPass< ModuleOp > > createConvertGPUToSPIRVPass ()
Pass to convert GPU Ops to SPIR-V ops.
std::unique_ptr< OperationPass< ModuleOp > > createConvertVulkanLaunchFuncToVulkanCallsPass ()
std::unique_ptr< OperationPass< mlir::ModuleOp > > createConvertGpuLaunchFuncToVulkanLaunchFuncPass ()
void populateLinalgToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Populate the given list with patterns that convert from Linalg to LLVM.
std::unique_ptr< OperationPass< ModuleOp > > createConvertLinalgToLLVMPass ()
Create a pass to convert Linalg operations to the LLVMIR dialect.
void populateLinalgToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating Linalg ops to SPIR-V ops.
std::unique_ptr< OperationPass< ModuleOp > > createLinalgToSPIRVPass ()
Creates and returns a pass to convert Linalg ops to SPIR-V ops.
std::unique_ptr< OperationPass< ModuleOp > > createConvertLinalgToStandardPass ()
Create a pass to convert Linalg operations to the Standard dialect.
void populateOpenMPToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Populate the given list with patterns that convert from OpenMP to LLVM.
std::unique_ptr< OperationPass< ModuleOp > > createConvertOpenMPToLLVMPass ()
Create a pass to convert OpenMP operations to the LLVMIR dialect.
std::unique_ptr< OperationPass< ModuleOp > > createPDLToPDLInterpPass ()
Creates and returns a pass to convert PDL ops to PDL interpreter ops.
LogicalResult convertAffineLoopNestToGPULaunch (AffineForOp forOp, unsigned numBlockDims, unsigned numThreadDims)
Convert a perfect affine loop nest with the outermost loop identified by forOp into a gpu::Launch operation.
void populateParallelLoopToGPUPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Adds the conversion pattern from scf.parallel to gpu.launch to the provided pattern list.
void configureParallelLoopToGPULegality (ConversionTarget &target)
Configures the rewrite target such that only scf.parallel operations that are not rewritten by the provided patterns are legal.
std::unique_ptr< OperationPass< FuncOp > > createAffineForToGPUPass (unsigned numBlockDims, unsigned numThreadDims)
Create a pass that converts loop nests into GPU kernels.
std::unique_ptr< OperationPass< FuncOp > > createAffineForToGPUPass ()
std::unique_ptr< Pass > createParallelLoopToGpuPass ()
Creates a pass that converts scf.parallel operations into a gpu.launch operation.
std::unique_ptr< OperationPass< FuncOp > > createConvertSCFToOpenMPPass ()
void populateSCFToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, ScfToSPIRVContext &scfToSPIRVContext, OwningRewritePatternList &patterns)
Collects a set of patterns to lower from scf.for, scf.if, and loop.terminator to CFG operations within the SPIR-V dialect.
void populateLoopToStdConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Collect a set of patterns to lower from scf.for, scf.if, and loop.terminator to CFG operations within the Standard dialect, in particular convert structured control flow into CFG branch-based control flow.
std::unique_ptr< Pass > createLowerToCFGPass ()
Creates a pass to convert scf.for, scf.if and loop.terminator ops to CFG.
void populateShapeToStandardConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
std::unique_ptr< OperationPass< ModuleOp > > createConvertShapeToStandardPass ()
void populateConvertShapeConstraintsConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
std::unique_ptr< OperationPass< FuncOp > > createConvertShapeConstraintsPass ()
void encodeBindAttribute (ModuleOp module)
Encodes global variable's descriptor set and binding into its name if they both exist.
void populateSPIRVToLLVMTypeConversion (LLVMTypeConverter &typeConverter)
Populates type conversions with additional SPIR-V types.
void populateSPIRVToLLVMConversionPatterns (MLIRContext *context, LLVMTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Populates the given list with patterns that convert from SPIR-V to LLVM.
void populateSPIRVToLLVMFunctionConversionPatterns (MLIRContext *context, LLVMTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Populates the given list with patterns for function conversion from SPIR-V to LLVM.
void populateSPIRVToLLVMModuleConversionPatterns (MLIRContext *context, LLVMTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Populates the given patterns for module conversion from SPIR-V to LLVM.
std::unique_ptr< OperationPass< ModuleOp > > createLowerHostCodeToLLVMPass ()
Creates a pass to emulate gpu.launch_func call in LLVM dialect and lower the host module code to LLVM.
std::unique_ptr< OperationPass< ModuleOp > > createConvertSPIRVToLLVMPass ()
Creates a pass to convert SPIR-V operations to the LLVMIR dialect.
LogicalResult structFuncArgTypeConverter (LLVMTypeConverter &converter, Type type, SmallVectorImpl< Type > &result)
Callback to convert function argument types.
LogicalResult barePtrFuncArgTypeConverter (LLVMTypeConverter &converter, Type type, SmallVectorImpl< Type > &result)
Callback to convert function argument types.
void populateStdToLLVMMemoryConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert memory-related operations from the Standard dialect to the LLVM dialect, excluding non-memory-related operations and FuncOp.
void populateStdToLLVMNonMemoryConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the Standard dialect to the LLVM dialect, excluding the memory-related operations.
void populateStdToLLVMFuncOpConversionPattern (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect the default pattern to convert a FuncOp to the LLVM dialect.
void populateStdToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect the patterns to convert from the Standard dialect to LLVM.
std::unique_ptr< OperationPass< ModuleOp > > createLowerToLLVMPass (const LowerToLLVMOptions &options=LowerToLLVMOptions::getDefaultOptions())
Creates a pass to convert the Standard dialect into the LLVMIR dialect.
void populateStandardToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating StandardOps to SPIR-V ops.
void populateStdLegalizationPatternsForSPIRVLowering (MLIRContext *context, OwningRewritePatternList &patterns)
Appends to a pattern list patterns to legalize ops that are not directly lowered to SPIR-V.
std::unique_ptr< OperationPass< ModuleOp > > createConvertStandardToSPIRVPass ()
Pass to convert StandardOps to SPIR-V ops.
std::unique_ptr< Pass > createLegalizeStdOpsForSPIRVLoweringPass ()
Pass to legalize ops that are not directly lowered to SPIR-V.
void populateVectorToLLVMMatrixConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from Vector contractions to LLVM Matrix Intrinsics.
void populateVectorToLLVMConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns, bool reassociateFPReductions=false, bool enableIndexOptimizations=true)
Collect a set of patterns to convert from the Vector dialect to LLVM.
std::unique_ptr< OperationPass< ModuleOp > > createConvertVectorToLLVMPass (const LowerVectorToLLVMOptions &options=LowerVectorToLLVMOptions())
Create a pass to convert vector operations to the LLVMIR dialect.
void populateVectorToROCDLConversionPatterns (LLVMTypeConverter &converter, OwningRewritePatternList &patterns)
Collect a set of patterns to convert from the GPU dialect to ROCDL.
std::unique_ptr< OperationPass< ModuleOp > > createConvertVectorToROCDLPass ()
Create a pass to convert vector operations to the ROCDL dialect.
void populateVectorToSCFConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *context, const VectorTransferToSCFOptions &options=VectorTransferToSCFOptions())
Collect a set of patterns to convert from the Vector dialect to SCF + std.
std::unique_ptr< Pass > createConvertVectorToSCFPass (const VectorTransferToSCFOptions &options=VectorTransferToSCFOptions())
Create a pass to convert a subset of vector ops to SCF.
void populateVectorToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating Vector Ops to SPIR-V ops.
std::unique_ptr< OperationPass< ModuleOp > > createConvertVectorToSPIRVPass ()
Pass to convert Vector Ops to SPIR-V ops.
bool isTopLevelValue (Value value)
A utility function to check if a value is defined at the top level of an op with trait AffineScope or is a region argument for such an op.
bool isValidDim (Value value)
Returns true if the given Value can be used as a dimension id in the region of the closest surrounding op that has the trait AffineScope.
bool isValidDim (Value value, Region *region)
Returns true if the given Value can be used as a dimension id in region, i.e., for all its uses in region.
bool isValidSymbol (Value value)
Returns true if the given value can be used as a symbol in the region of the closest surrounding op that has the trait AffineScope.
bool isValidSymbol (Value value, Region *region)
Returns true if the given Value can be used as a symbol for region, i.e., for all its uses in region.
ParseResult parseDimAndSymbolList (OpAsmParser &parser, SmallVectorImpl< Value > &operands, unsigned &numDims)
Parses dimension and symbol list and returns true if parsing failed.
void canonicalizeMapAndOperands (AffineMap *map, SmallVectorImpl< Value > *operands)
Modifies both map and operands in-place so as to:
void canonicalizeSetAndOperands (IntegerSet *set, SmallVectorImpl< Value > *operands)
Canonicalizes an integer set the same way canonicalizeMapAndOperands does for affine maps.
AffineApplyOp makeComposedAffineApply (OpBuilder &b, Location loc, AffineMap map, ArrayRef< Value > operands)
Returns a composed AffineApplyOp by composing map and operands with other AffineApplyOps supplying those operands.
void fullyComposeAffineMapAndOperands (AffineMap *map, SmallVectorImpl< Value > *operands)
Given an affine map map and its input operands, this method composes into map, maps of AffineApplyOps whose results are the values in operands, iteratively until no more of operands are the result of an AffineApplyOp.
bool isForInductionVar (Value val)
Returns true if the provided value is the induction variable of a AffineForOp.
AffineForOp getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
void extractForInductionVars (ArrayRef< AffineForOp > forInsts, SmallVectorImpl< Value > *ivs)
Extracts the induction variables from a list of AffineForOps and places them in the output argument ivs.
void buildAffineLoopNest (OpBuilder &builder, Location loc, ArrayRef< int64_t > lbs, ArrayRef< int64_t > ubs, ArrayRef< int64_t > steps, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn=nullptr)
Builds a perfect nest of affine "for" loops, i.e.
void buildAffineLoopNest (OpBuilder &builder, Location loc, ValueRange lbs, ValueRange ubs, ArrayRef< int64_t > steps, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn=nullptr)
std::unique_ptr< OperationPass< FuncOp > > createSimplifyAffineStructuresPass ()
Creates a simplification pass for affine structures (maps and sets).
std::unique_ptr< OperationPass< FuncOp > > createAffineLoopInvariantCodeMotionPass ()
Creates a loop invariant code motion pass that hoists loop invariant operations out of affine loops.
std::unique_ptr< OperationPass< FuncOp > > createAffineParallelizePass ()
Creates a pass to convert all parallel affine.for's into 1-d affine.parallel ops.
std::unique_ptr< OperationPass< FuncOp > > createAffineLoopNormalizePass ()
Apply normalization transformations to affine loop-like ops.
std::unique_ptr< OperationPass< FuncOp > > createAffineDataCopyGenerationPass (unsigned slowMemorySpace, unsigned fastMemorySpace, unsigned tagMemorySpace=0, int minDmaTransferSize=1024, uint64_t fastMemCapacityBytes=std::numeric_limits< uint64_t >::max())
Performs packing (or explicit copying) of accessed memref regions into buffers in the specified faster memory space through either pointwise copies or DMA operations.
std::unique_ptr< OperationPass< FuncOp > > createAffineDataCopyGenerationPass ()
Overload relying on pass options for initialization.
std::unique_ptr< OperationPass< FuncOp > > createLoopTilingPass (uint64_t cacheSizeBytes)
Creates a pass to perform tiling on loop nests.
std::unique_ptr< OperationPass< FuncOp > > createLoopTilingPass ()
Overload relying on pass options for initialization.
std::unique_ptr< OperationPass< FuncOp > > createLoopUnrollPass (int unrollFactor=-1, bool unrollUpToFactor=false, bool unrollFull=false, const std::function< unsigned(AffineForOp)> &getUnrollFactor=nullptr)
Creates a loop unrolling pass with the provided parameters.
std::unique_ptr< OperationPass< FuncOp > > createLoopUnrollAndJamPass (int unrollJamFactor=-1)
Creates a loop unroll jam pass to unroll jam by the specified factor.
std::unique_ptr< OperationPass< FuncOp > > createSuperVectorizePass (ArrayRef< int64_t > virtualVectorSize)
Creates a pass to vectorize loops, operations and data types using a target-independent, n-D super-vector abstraction.
std::unique_ptr< OperationPass< FuncOp > > createSuperVectorizePass ()
Overload relying on pass options for initialization.
void affineParallelize (AffineForOp forOp)
Replaces parallel affine.for op with 1-d affine.parallel op.
LogicalResult hoistAffineIfOp (AffineIfOp ifOp, bool *folded=nullptr)
Hoists out affine.if/else to as high as possible, i.e., past all invariant affine.fors/parallel's.
void vectorizeAffineLoops (Operation *parentOp, llvm::DenseSet< Operation *, DenseMapInfo< Operation *>> &loops, ArrayRef< int64_t > vectorSizes, ArrayRef< int64_t > fastestVaryingPattern)
Vectorizes affine loops in 'loops' using the n-D vectorization factors in 'vectorSizes'.
LogicalResult vectorizeAffineLoopNest (std::vector< SmallVector< AffineForOp, 2 >> &loops, const VectorizationStrategy &strategy)
External utility to vectorize affine loops from a single loop nest using an n-D vectorization strategy (see doc in VectorizationStrategy definition).
void normalizeAffineParallel (AffineParallelOp op)
Normalize a affine.parallel op so that lower bounds are 0 and steps are 1.
std::unique_ptr< OperationPass< FuncOp > > createAsyncParallelForPass ()
std::unique_ptr< OperationPass< FuncOp > > createAsyncParallelForPass (int numWorkerThreads)
std::unique_ptr< OperationPass< FuncOp > > createAsyncRefCountingPass ()
std::unique_ptr< OperationPass< FuncOp > > createAsyncRefCountingOptimizationPass ()
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref<ElementValueT(ElementValueT, ElementValueT)>>
Attribute constFoldBinaryOp (ArrayRef< Attribute > operands, const CalculationT &calculate)
Performs constant folding calculate with element-wise behavior on the two attributes in operands and returns the result if possible.
void promoteToWorkgroupMemory (gpu::GPUFuncOp op, unsigned arg)
Promotes a function argument to workgroup memory in the given function.
void greedilyMapParallelSCFToGPU (Region &region)
Maps the parallel loops found in the given function to workgroups.
std::unique_ptr< OperationPass< ModuleOp > > createGpuKernelOutliningPass ()
Replaces gpu.launch with gpu.launch_func by moving the region into a separate kernel function.
std::unique_ptr< OperationPass< FuncOp > > createGpuAsyncRegionPass ()
Rewrites a function region so that GPU ops execute asynchronously.
void populateGpuAllReducePatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Collect a set of patterns to rewrite all-reduce ops within the GPU dialect.
void populateGpuRewritePatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Collect all patterns to rewrite ops within the GPU dialect.
gpu::GPUFuncOp outlineKernelFunc (gpu::LaunchOp launchOp, StringRef kernelFnName, SmallVectorImpl< Value > &operands)
Get a gpu.func created from outlining the region of a gpu.launch op with the given kernelFnName.
LogicalResult sinkOperationsIntoLaunchOp (gpu::LaunchOp launchOp)
Sink operations into the launchOp to reduce the number of values that are used within the region of the operation, but defined outside of the region.
std::unique_ptr< OperationPass< FuncOp > > createConvertElementwiseToLinalgPass ()
std::unique_ptr< OperationPass< FuncOp > > createLinalgFoldUnitExtentDimsPass ()
std::unique_ptr< Pass > createLinalgFusionOfTensorOpsPass ()
std::unique_ptr< Pass > createFoldReshapeOpsByLinearizationPass ()
std::unique_ptr< OperationPass< FuncOp > > createLinalgTilingPass (ArrayRef< int64_t > tileSizes={})
std::unique_ptr< OperationPass< FuncOp > > createLinalgTilingToParallelLoopsPass (ArrayRef< int64_t > tileSizes={})
std::unique_ptr< OperationPass< FuncOp > > createLinalgPromotionPass (bool dynamicBuffers, bool useAlloca)
std::unique_ptr< OperationPass< FuncOp > > createLinalgPromotionPass ()
std::unique_ptr< OperationPass< FuncOp > > createConvertLinalgToLoopsPass ()
Create a pass to convert Linalg operations to scf.for loops and std.load/std.store accesses.
std::unique_ptr< OperationPass< FuncOp > > createConvertLinalgToParallelLoopsPass ()
Create a pass to convert Linalg operations to scf.parallel loops and std.load/std.store accesses.
std::unique_ptr< OperationPass< FuncOp > > createConvertLinalgToAffineLoopsPass ()
Create a pass to convert Linalg operations to affine.for loops and affine_load/affine_store accesses.
std::unique_ptr< OperationPass< FuncOp > > createLinalgBufferizePass ()
Create a pass to convert Linalg operations which work on tensors to use buffers instead.
void populateElementwiseToLinalgConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
Populate patterns that convert ElementwiseMappable ops to linalg parallel loops.
std::unique_ptr< OperationPass< FuncOp > > createLinalgGeneralizationPass ()
Create a pass to conver named Linalg operations to Linalg generic operations.
void populateFoldReshapeOpsByExpansionPatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Patterns to fold an expanding (collapsing) tensor_reshape operation with its producer (consumer) generic operation by expanding the dimensionality of the loop in the generic op.
void populateFoldReshapeOpsByLinearizationPatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic/indexed_generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic/indexed_generic operation.
void populateLinalgTensorOpsFusionPatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Patterns for fusing linalg operation on tensors.
void populateLinalgFoldUnitExtentDimsPatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Patterns to fold unit-extent dimensions in operands/results of linalg ops on tensors.
std::unique_ptr< Pass > createSCFBufferizePass ()
Creates a pass that bufferizes the SCF dialect.
std::unique_ptr< Pass > createForLoopSpecializationPass ()
Creates a pass that specializes for loop for unrolling and vectorization.
std::unique_ptr< Pass > createParallelLoopFusionPass ()
Creates a loop fusion pass which fuses parallel loops.
std::unique_ptr< Pass > createParallelLoopSpecializationPass ()
Creates a pass that specializes parallel loop for unrolling and vectorization.
std::unique_ptr< Pass > createParallelLoopTilingPass (llvm::ArrayRef< int64_t > tileSize={})
Creates a pass which tiles innermost parallel loops.
scf::ForOp cloneWithNewYields (OpBuilder &b, scf::ForOp loop, ValueRange newIterOperands, ValueRange newYieldedValues, bool replaceLoopResults=true)
Create a clone of loop with newIterOperands added as new initialization values and newYieldedValues added as new yielded values.
void outlineIfOp (OpBuilder &b, scf::IfOp ifOp, FuncOp *thenFn, StringRef thenFnName, FuncOp *elseFn, StringRef elseFnName)
Outline the then and/or else regions of ifOp as follows:
IntInfty operator+ (IntInfty lhs, IntInfty rhs)
bool operator< (IntInfty lhs, IntInfty rhs)
bool operator<= (IntInfty lhs, IntInfty rhs)
bool operator== (IntInfty lhs, IntInfty rhs)
bool operator!= (IntInfty lhs, IntInfty rhs)
std::unique_ptr< Pass > createShapeToShapeLowering ()
Creates an instance of the ShapeToShapeLowering pass that legalizes Shape dialect to be convertible to Standard.
void populateShapeRewritePatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Collects a set of patterns to rewrite ops within the Shape dialect.
void populateRemoveShapeConstraintsPatterns (OwningRewritePatternList &patterns, MLIRContext *ctx)
std::unique_ptr< FunctionPass > createRemoveShapeConstraintsPass ()
void populateShapeStructuralTypeConversionsAndLegality (MLIRContext *context, TypeConverter &typeConverter, OwningRewritePatternList &patterns, ConversionTarget &target)
Populates patterns for shape dialect structural type conversions and sets up the provided ConversionTarget with the appropriate legality configuration for the ops to get converted properly.
std::unique_ptr< FunctionPass > createShapeBufferizePass ()
template<typename EnumClass , typename ParserType >
static ParseResult parseEnumKeywordAttr (EnumClass &value, ParserType &parser, StringRef attrName=spirv::attributeName< EnumClass >())
Parses the next keyword in parser as an enumerant of the given EnumClass.
void populateBuiltinFuncToSPIRVPatterns (MLIRContext *context, SPIRVTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Appends to a pattern list additional patterns for translating the builtin func op to the SPIR-V dialect.
raw_ostream & operator<< (raw_ostream &os, Range &range)
SmallVector< Range, 8 > getOrCreateRanges (OffsetSizeAndStrideOpInterface op, OpBuilder &b, Location loc)
Return the list of Range (i.e.
llvm::Optional< SmallVector< bool, 4 > > computeRankReductionMask (ArrayRef< int64_t > originalShape, ArrayRef< int64_t > reducedShape)
Given an originalShape and a reducedShape assumed to be a subset of originalShape with some 1 entries erased, return the vector of booleans that specifies which of the entries of originalShape are keep to obtain reducedShape.
bool canFoldIntoConsumerOp (MemRefCastOp castOp)
Determines whether MemRefCastOp casts to a more dynamic version of the source memref.
bool canFoldIntoConsumerOp (TensorCastOp castOp)
Counterpart of canFoldIntoConsumerOp(MemRefCastOp castOp) for tensors.
bool applyCmpPredicate (CmpIPredicate predicate, const APInt &lhs, const APInt &rhs)
Compute lhs pred rhs, where pred is one of the known integer comparison predicates.
bool applyCmpPredicate (CmpFPredicate predicate, const APFloat &lhs, const APFloat &rhs)
Compute lhs pred rhs, where pred is one of the known floating point comparison predicates.
void populateDecomposeCallGraphTypesPatterns (MLIRContext *context, TypeConverter &typeConverter, ValueDecomposer &decomposer, OwningRewritePatternList &patterns)
Populates the patterns needed to drive the conversion process for decomposing call graph types with the given ValueDecomposer.
void populateCallOpTypeConversionPattern (OwningRewritePatternList &patterns, MLIRContext *ctx, TypeConverter &converter)
Add a pattern to the given pattern list to convert the operand and result types of a CallOp with the given type converter.
void populateBranchOpInterfaceAndReturnOpTypeConversionPattern (OwningRewritePatternList &patterns, MLIRContext *ctx, TypeConverter &converter)
Add a pattern to the given pattern list to rewrite branch operations and return to use operands that have been legalized by the conversion framework.
void populateExpandTanhPattern (OwningRewritePatternList &patterns, MLIRContext *ctx)
void populateStdBufferizePatterns (MLIRContext *context, BufferizeTypeConverter &typeConverter, OwningRewritePatternList &patterns)
std::unique_ptr< Pass > createStdBufferizePass ()
Creates an instance of std bufferization pass.
std::unique_ptr< Pass > createFuncBufferizePass ()
Creates an instance of func bufferization pass.
std::unique_ptr< Pass > createTensorConstantBufferizePass ()
Creates an instance of tensor constant bufferization pass.
std::unique_ptr< Pass > createStdExpandOpsPass ()
Creates an instance of the StdExpand pass that legalizes Std dialect ops to be convertible to LLVM.
void populateStdExpandOpsPatterns (MLIRContext *context, OwningRewritePatternList &patterns)
Collects a set of patterns to rewrite ops within the Std dialect.
void populateTensorBufferizePatterns (MLIRContext *context, BufferizeTypeConverter &typeConverter, OwningRewritePatternList &patterns)
std::unique_ptr< Pass > createTensorBufferizePass ()
Creates an instance of tensor dialect bufferization pass.
bool isRowMajorMatmul (ArrayAttr indexingMaps)
bool isColumnMajorMatmul (ArrayAttr indexingMaps)
constexpr StringRef getIndexingMapsAttrName ()
Attribute name for the AffineArrayAttr which encodes the relationship between a structured op iterators' and its operands.
constexpr StringRef getIteratorTypesAttrName ()
Attribute name for the StrArrayAttr which encodes the type of a structured op's iterators.
constexpr StringRef getDocAttrName ()
Attribute name for the StringAttr which encodes an optional documentation string of the structured op.
constexpr StringRef getLibraryCallAttrName ()
Attribute name for the StrArrayAttr which encodes the external library function that implements the structured op.
constexpr StringRef getSparseAttrName ()
Attribute name for the ArrayAttr of StrArrayAttr that encodes sparsity.
constexpr StringRef getStridesAttrName ()
Attribute name for the StrArrayAttr which encodes the value of strides.
constexpr StringRef getDilationsAttrName ()
Attribute name for the StrArrayAttr which encodes the value of dilations.
constexpr StringRef getPaddingAttrName ()
Attribute name for the StrArrayAttr which encodes the value of paddings.
constexpr StringRef getParallelIteratorTypeName ()
Use to encode that a particular iterator type has parallel semantics.
bool isParallelIterator (Attribute attr)
constexpr StringRef getReductionIteratorTypeName ()
Use to encode that a particular iterator type has reduction semantics.
bool isReductionIterator (Attribute attr)
constexpr StringRef getWindowIteratorTypeName ()
Use to encode that a particular iterator type has window semantics.
bool isWindowIterator (Attribute attr)
ArrayRef< StringRef > getAllIteratorTypeNames ()
Use to encode that a particular iterator type has window semantics.
unsigned getNumIterators (StringRef name, ArrayAttr iteratorTypes)
Returns the iterator of a certain type.
unsigned getNumIterators (ArrayAttr iteratorTypes)
StringRef toString (IteratorType t)
constexpr StringRef getSparseDimName ()
Use to encode a dense or sparse dimension.
bool isSparseDim (Attribute attr)
constexpr StringRef getDenseDimName ()
bool isDenseDim (Attribute attr)
void populateVectorToVectorConversionPatterns (MLIRContext *context, OwningRewritePatternList &patterns, ArrayRef< int64_t > coarseVectorShape={}, ArrayRef< int64_t > fineVectorShape={})
Collect a set of patterns to convert from the Vector dialect to itself.
int64_t computeMaxLinearIndex (ArrayRef< int64_t > basis)
Return the number of elements of basis, 0 if empty.
SmallVector< int64_t, 8 > computeStrides (ArrayRef< int64_t > shape)
Given a shape with sizes greater than 0 along all dimensions, return the distance, in number of elements, between a slice in a dimension and the next slice in the same dimension.
SmallVector< int64_t, 4 > computeStrides (ArrayRef< int64_t > shape, ArrayRef< int64_t > sizes)
Given the shape and sizes of a vector, returns the corresponding strides for each dimension.
int64_t linearize (ArrayRef< int64_t > offsets, ArrayRef< int64_t > basis)
Computes and returns the linearized index of 'offsets' w.r.t. 'basis'.
SmallVector< int64_t, 4 > delinearize (ArrayRef< int64_t > strides, int64_t linearIndex)
Given the strides together with a linear index in the dimension space, returns the vector-space offsets in each dimension for a de-linearized index.
SmallVector< int64_t, 4 > computeElementOffsetsFromVectorSliceOffsets (ArrayRef< int64_t > sizes, ArrayRef< int64_t > vectorOffsets)
Given the target sizes of a vector, together with vector-space offsets, returns the element-space offsets for each dimension.
SmallVector< int64_t, 4 > computeSliceSizes (ArrayRef< int64_t > shape, ArrayRef< int64_t > sizes, ArrayRef< int64_t > elementOffsets)
Given the shape, sizes, and element-space offsets of a vector, returns the slize sizes for each dimension.
Optional< SmallVector< int64_t, 4 > > shapeRatio (ArrayRef< int64_t > superShape, ArrayRef< int64_t > subShape)
Computes and returns the multi-dimensional ratio of superShape to subShape.
Optional< SmallVector< int64_t, 4 > > shapeRatio (VectorType superVectorType, VectorType subVectorType)
Computes and returns the multi-dimensional ratio of the shapes of superVector to subVector.
int JitRunnerMain (int argc, char **argv, JitRunnerConfig config={})
Entry point for all CPU runners.
void initializeLLVMPasses ()
Initialize LLVM passes that can be used when running MLIR code using ExecutionEngine.
void registerAllDialects (DialectRegistry &registry)
void registerAllPasses ()
void registerFromLLVMIRTranslation ()
void registerFromSPIRVTranslation ()
void registerToLLVMIRTranslation ()
void registerToSPIRVTranslation ()
void registerToNVVMIRTranslation ()
void registerToROCDLIRTranslation ()
void registerArmNeonToLLVMIRTranslation ()
void registerAVX512ToLLVMIRTranslation ()
void registerArmSVEToLLVMIRTranslation ()
void registerAllTranslations ()
bool isOpTriviallyDead (Operation *op)
Return true if the given operation is unused, and has no side effects on memory that prevent erasing.
bool wouldOpBeTriviallyDead (Operation *op)
Return true if the given operation would be dead if unused, and has no side effects on memory that would prevent erasing.
LogicalResult verify (OffsetSizeAndStrideOpInterface op)
void printOffsetsSizesAndStrides (OpAsmPrinter &p, OffsetSizeAndStrideOpInterface op, StringRef offsetPrefix="", StringRef sizePrefix=" ", StringRef stridePrefix=" ", ArrayRef< StringRef > elidedAttrs=OffsetSizeAndStrideOpInterface::getSpecialAttrNames())
Print part of an op of the form: `` <optional-offset-prefix>[offset-list] <optional-size-prefix>[size-list] <optional-stride-prefix>[ stride-list ] ```.
ParseResult parseOffsetsSizesAndStrides (OpAsmParser &parser, OperationState &result, ArrayRef< int > segmentSizes, llvm::function_ref< ParseResult(OpAsmParser &, OperationState &)> preResolutionFn=nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalOffsetPrefix=nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalSizePrefix=nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalStridePrefix=nullptr)
Parse trailing part of an op of the form: `` <optional-offset-prefix>[offset-list] <optional-size-prefix>[size-list] <optional-stride-prefix>[ stride-list ] ``` Each entry in the offset, size and stride list either resolves to an integer constant or an operand of index type.
ParseResult parseOffsetsSizesAndStrides (OpAsmParser &parser, OperationState &result, ArrayRef< int > segmentSizes, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalOffsetPrefix=nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalSizePrefix=nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalStridePrefix=nullptr)
preResolutionFn-less version of parseOffsetsSizesAndStrides.
inline ::llvm::hash_code hash_value (AffineExpr arg)
Make AffineExpr hashable.
AffineExpr operator+ (int64_t val, AffineExpr expr)
AffineExpr operator* (int64_t val, AffineExpr expr)
AffineExpr operator- (int64_t val, AffineExpr expr)
AffineExpr getAffineDimExpr (unsigned position, MLIRContext *context)
These free functions allow clients of the API to not use classes in detail.
AffineExpr getAffineSymbolExpr (unsigned position, MLIRContext *context)
AffineExpr getAffineConstantExpr (int64_t constant, MLIRContext *context)
AffineExpr getAffineBinaryOpExpr (AffineExprKind kind, AffineExpr lhs, AffineExpr rhs)
AffineExpr getAffineExprFromFlatForm (ArrayRef< int64_t > flatExprs, unsigned numDims, unsigned numSymbols, ArrayRef< AffineExpr > localExprs, MLIRContext *context)
Constructs an affine expression from a flat ArrayRef.
raw_ostream & operator<< (raw_ostream &os, AffineExpr expr)
AffineExpr simplifyAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols)
Simplify an affine expression by flattening and some amount of simple analysis.
template<typename... AffineExprTy>
void bindDims (MLIRContext *ctx, AffineExprTy &... exprs)
Bind a list of AffineExpr references to DimExpr at positions: [0 .
inline ::llvm::hash_code hash_value (AffineMap arg)
AffineMap simplifyAffineMap (AffineMap map)
Simplifies an affine map by simplifying its underlying AffineExpr results.
AffineMap removeDuplicateExprs (AffineMap map)
Returns a map with the same dimension and symbol count as map, but whose results are the unique affine expressions of map.
AffineMap inversePermutation (AffineMap map)
Returns a map of codomain to domain dimensions such that the first codomain dimension for a particular domain dimension is selected.
AffineMap concatAffineMaps (ArrayRef< AffineMap > maps)
Concatenates a list of maps into a single AffineMap, stepping over potentially empty maps.
AffineMap getProjectedMap (AffineMap map, ArrayRef< unsigned > projectedDimensions)
raw_ostream & operator<< (raw_ostream &os, AffineMap map)
void registerAsmPrinterCLOptions ()
Register a set of useful command-line options that can be used to configure various flags within the AsmPrinter.
raw_ostream & operator<< (raw_ostream &os, Attribute attr)
inline ::llvm::hash_code hash_value (Attribute arg)
bool operator< (const NamedAttribute &lhs, const NamedAttribute &rhs)
bool operator< (const NamedAttribute &lhs, StringRef rhs)
inline ::llvm::hash_code hash_value (const MutableDictionaryAttr &arg)
LogicalResult getStridesAndOffset (MemRefType t, SmallVectorImpl< int64_t > &strides, int64_t &offset)
Returns the strides of the MemRef if the layout map is in strided form.
LogicalResult getStridesAndOffset (MemRefType t, SmallVectorImpl< AffineExpr > &strides, AffineExpr &offset)
AffineMap makeStridedLinearLayoutMap (ArrayRef< int64_t > strides, int64_t offset, MLIRContext *context)
Given a list of strides (in which MemRefType::getDynamicStrideOrOffset() represents a dynamic value), return the single result AffineMap which represents the linearized strided layout map.
MemRefType canonicalizeStridedLayout (MemRefType t)
Return a version of t with identity layout if it can be determined statically that the layout is the canonical contiguous strided layout.
MemRefType eraseStridedLayout (MemRefType t)
Return a version of t with a layout that has all dynamic offset and strides.
AffineExpr makeCanonicalStridedLayoutExpr (ArrayRef< int64_t > sizes, ArrayRef< AffineExpr > exprs, MLIRContext *context)
Given MemRef sizes that are either static or dynamic, returns the canonical "contiguous" strides AffineExpr.
AffineExpr makeCanonicalStridedLayoutExpr (ArrayRef< int64_t > sizes, MLIRContext *context)
Return the result of makeCanonicalStrudedLayoutExpr for the common case where exprs is {d0, d1, .., d_(sizes.size()-1)}.
bool isStrided (MemRefType t)
Return true if the layout for t is compatible with strided semantics.
raw_ostream & operator<< (raw_ostream &os, const DiagnosticArgument &arg)
raw_ostream & operator<< (raw_ostream &os, const Diagnostic &diag)
InFlightDiagnostic emitError (Location loc)
Utility method to emit an error message using this location.
InFlightDiagnostic emitError (Location loc, const Twine &message)
InFlightDiagnostic emitWarning (Location loc)
Utility method to emit a warning message using this location.
InFlightDiagnostic emitWarning (Location loc, const Twine &message)
InFlightDiagnostic emitRemark (Location loc)
Utility method to emit a remark message using this location.
InFlightDiagnostic emitRemark (Location loc, const Twine &message)
template<typename... Args>
LogicalResult emitOptionalError (Optional< Location > loc, Args &&... args)
Overloads of the above emission functions that take an optionally null location.
template<typename... Args>
LogicalResult emitOptionalWarning (Optional< Location > loc, Args &&... args)
template<typename... Args>
LogicalResult emitOptionalRemark (Optional< Location > loc, Args &&... args)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, Attribute attr)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, const APFloat &value)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, float value)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, double value)
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, Type type)
template<typename T , typename std::enable_if< !std::is_convertible< T &, Attribute &>::value &&!std::is_convertible< T &, Type &>::value &&!std::is_convertible< T &, APFloat &>::value &&!llvm::is_one_of< T, double, float >::value, T >::type * = nullptr>
DialectAsmPrinter & operator<< (DialectAsmPrinter &p, const T &other)
raw_ostream & operator<< (raw_ostream &os, Identifier identifier)
bool operator== (Identifier lhs, StringRef rhs)
bool operator!= (Identifier lhs, StringRef rhs)
bool operator== (StringRef lhs, Identifier rhs)
bool operator!= (StringRef lhs, Identifier rhs)
llvm::hash_code hash_value (Identifier arg)
inline ::llvm::hash_code hash_value (IntegerSet arg)
raw_ostream & operator<< (raw_ostream &os, const Location &loc)
inline ::llvm::hash_code hash_value (Location arg)
detail::constant_op_matcher m_Constant ()
Matches a constant foldable operation.
template<typename AttrT >
detail::constant_op_binder< AttrT > m_Constant (AttrT *bind_value)
Matches a value from a constant foldable operation and writes the value to bind_value.
detail::constant_int_value_matcher< 1 > m_One ()
Matches a constant scalar / vector splat / tensor splat integer one.
template<typename OpClass >
detail::op_matcher< OpClass > m_Op ()
Matches the given OpClass.
detail::constant_int_value_matcher< 0 > m_Zero ()
Matches a constant scalar / vector splat / tensor splat integer zero.
detail::constant_int_not_value_matcher< 0 > m_NonZero ()
Matches a constant scalar / vector splat / tensor splat integer that is any non-zero value.
template<typename Pattern >
bool matchPattern (Value value, const Pattern &pattern)
Entry point for matching a pattern over a Value.
template<typename Pattern >
bool matchPattern (Operation *op, const Pattern &pattern)
Entry point for matching a pattern over an Operation.
detail::constant_int_op_binder m_ConstantInt (IntegerAttr::ValueType *bind_value)
Matches a constant holding a scalar/vector/tensor integer (splat) and writes the integer value to bind_value.
template<typename OpType , typename... Matchers>
auto m_Op (Matchers... matchers)
void registerMLIRContextCLOptions ()
Register a set of useful command-line options that can be used to configure various flags within the MLIRContext.
bool operator== (OpState lhs, OpState rhs)
bool operator!= (OpState lhs, OpState rhs)
raw_ostream & operator<< (raw_ostream &os, OpState &op)
Allow printing to a stream.
raw_ostream & operator<< (raw_ostream &os, Operation &op)
raw_ostream & operator<< (raw_ostream &os, OperationName identifier)
bool operator== (OperationName lhs, OperationName rhs)
bool operator!= (OperationName lhs, OperationName rhs)
llvm::hash_code hash_value (OperationName arg)
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
Enable Bitmask enums for OperationEquivalence::Flags.
OpAsmPrinter & operator<< (OpAsmPrinter &p, Value value)
template<typename T , typename std::enable_if< std::is_convertible< T &, ValueRange >::value &&!std::is_convertible< T &, Value &>::value, T >::type * = nullptr>
OpAsmPrinter & operator<< (OpAsmPrinter &p, const T &values)
OpAsmPrinter & operator<< (OpAsmPrinter &p, Type type)
OpAsmPrinter & operator<< (OpAsmPrinter &p, Attribute attr)
OpAsmPrinter & operator<< (OpAsmPrinter &p, bool value)
OpAsmPrinter & operator<< (OpAsmPrinter &p, Block *value)
template<typename ValueRangeT >
OpAsmPrinter & operator<< (OpAsmPrinter &p, const ValueTypeRange< ValueRangeT > &types)
OpAsmPrinter & operator<< (OpAsmPrinter &p, const TypeRange &types)
OpAsmPrinter & operator<< (OpAsmPrinter &p, ArrayRef< Type > types)
raw_ostream & operator<< (raw_ostream &os, PDLValue value)
inline ::llvm::hash_code hash_value (TypeRange arg)
Make TypeRange hashable.
template<typename RangeT >
bool operator== (ArrayRef< Type > lhs, const ValueTypeRange< RangeT > &rhs)
raw_ostream & operator<< (raw_ostream &os, Type type)
inline ::llvm::hash_code hash_value (Type arg)
Type getElementTypeOrSelf (Type type)
Return the element type or return the type itself.
Type getElementTypeOrSelf (Attribute attr)
Return the element type or return the type itself.
Type getElementTypeOrSelf (Value val)
SmallVector< Type, 10 > getFlattenedTypes (TupleType t)
Get the types within a nested Tuple.
bool isOpaqueTypeWithName (Type type, StringRef dialect, StringRef typeData)
Return true if the specified type is an opaque type with the specified dialect and typeData.
LogicalResult verifyCompatibleShape (ArrayRef< int64_t > shape1, ArrayRef< int64_t > shape2)
Returns success if the given two shapes are compatible.
LogicalResult verifyCompatibleShape (Type type1, Type type2)
Returns success if the given two types have compatible shape.
raw_ostream & operator<< (raw_ostream &os, Value value)
inline ::llvm::hash_code hash_value (Value arg)
Make Value hashable.
LogicalResult verify (Operation *op)
Perform (potentially expensive) checks of invariants, used to detect compiler bugs, on this operation and any nested operations.
LogicalResult parseSourceFile (const llvm::SourceMgr &sourceMgr, Block *block, MLIRContext *context, LocationAttr *sourceFileLoc=nullptr)
This parses the file specified by the indicated SourceMgr and appends parsed operations to the given block.
LogicalResult parseSourceFile (llvm::StringRef filename, Block *block, MLIRContext *context, LocationAttr *sourceFileLoc=nullptr)
This parses the file specified by the indicated filename and appends parsed operations to the given block.
LogicalResult parseSourceFile (llvm::StringRef filename, llvm::SourceMgr &sourceMgr, Block *block, MLIRContext *context, LocationAttr *sourceFileLoc=nullptr)
This parses the file specified by the indicated filename using the provided SourceMgr and appends parsed operations to the given block.
LogicalResult parseSourceString (llvm::StringRef sourceStr, Block *block, MLIRContext *context, LocationAttr *sourceFileLoc=nullptr)
This parses the IR string and appends parsed operations to the given block.
template<typename ContainerOpT >
OwningOpRef< ContainerOpT > parseSourceFile (const llvm::SourceMgr &sourceMgr, MLIRContext *context)
This parses the file specified by the indicated SourceMgr.
template<typename ContainerOpT >
OwningOpRef< ContainerOpT > parseSourceFile (llvm::StringRef filename, MLIRContext *context)
This parses the file specified by the indicated filename.
template<typename ContainerOpT >
OwningOpRef< ContainerOpT > parseSourceFile (llvm::StringRef filename, llvm::SourceMgr &sourceMgr, MLIRContext *context)
This parses the file specified by the indicated filename using the provided SourceMgr.
template<typename ContainerOpT >
OwningOpRef< ContainerOpT > parseSourceString (llvm::StringRef sourceStr, MLIRContext *context)
This parses the provided string containing MLIR.
Attribute parseAttribute (llvm::StringRef attrStr, MLIRContext *context)
This parses a single MLIR attribute to an MLIR context if it was valid.
Attribute parseAttribute (llvm::StringRef attrStr, Type type)
Attribute parseAttribute (llvm::StringRef attrStr, MLIRContext *context, size_t &numRead)
This parses a single MLIR attribute to an MLIR context if it was valid.
Attribute parseAttribute (llvm::StringRef attrStr, Type type, size_t &numRead)
Type parseType (llvm::StringRef typeStr, MLIRContext *context)
This parses a single MLIR type to an MLIR context if it was valid.
Type parseType (llvm::StringRef typeStr, MLIRContext *context, size_t &numRead)
This parses a single MLIR type to an MLIR context if it was valid.
void registerPassManagerCLOptions ()
Register a set of useful command-line options that can be used to configure a pass manager.
void applyPassManagerCLOptions (PassManager &pm)
Apply any values provided to the pass manager options that were registered with 'registerPassManagerOptions'.
void registerPassPipeline (StringRef arg, StringRef description, const PassRegistryFunction &function, std::function< void(function_ref< void(const detail::PassOptions &)>)> optHandler)
Register a specific dialect pipeline registry function with the system, typically used through the PassPipelineRegistration template.
void registerPass (StringRef arg, StringRef description, const PassAllocatorFunction &function)
Register a specific dialect pass allocator function with the system, typically used through the PassRegistration template.
LogicalResult parsePassPipeline (StringRef pipeline, OpPassManager &pm, raw_ostream &errorStream=llvm::errs())
This function parses the textual representation of a pass pipeline, and adds the result to 'pm' on success.
template<typename T >
static std::string debugString (T &op)
std::unique_ptr< llvm::MemoryBuffer > openInputFile (llvm::StringRef inputFilename, std::string *errorMessage=nullptr)
Open the file specified by its name for reading.
std::unique_ptr< llvm::ToolOutputFile > openOutputFile (llvm::StringRef outputFilename, std::string *errorMessage=nullptr)
Open the file specified by its name for writing.
LogicalResult success (bool isSuccess=true)
Utility function to generate a LogicalResult.
LogicalResult failure (bool isFailure=true)
Utility function to generate a LogicalResult.
bool succeeded (LogicalResult result)
Utility function that returns true if the provided LogicalResult corresponds to a success value.
bool failed (LogicalResult result)
Utility function that returns true if the provided LogicalResult corresponds to a failure value.
int64_t ceilDiv (int64_t lhs, int64_t rhs)
Returns the result of MLIR's ceildiv operation on constants.
int64_t floorDiv (int64_t lhs, int64_t rhs)
Returns the result of MLIR's floordiv operation on constants.
int64_t mod (int64_t lhs, int64_t rhs)
Returns MLIR's mod operation on constants.
int64_t lcm (int64_t a, int64_t b)
Returns the least common multiple of 'a' and 'b'.
LogicalResult MlirOptMain (llvm::raw_ostream &outputStream, std::unique_ptr< llvm::MemoryBuffer > buffer, const PassPipelineCLParser &passPipeline, DialectRegistry &registry, bool splitInputFile, bool verifyDiagnostics, bool verifyPasses, bool allowUnregisteredDialects, bool preloadDialectsInContext=true)
Perform the core processing behind mlir-opt:
LogicalResult MlirOptMain (int argc, char **argv, llvm::StringRef toolName, DialectRegistry &registry, bool preloadDialectsInContext=true)
Implementation for tools like mlir-opt.
LogicalResult splitAndProcessBuffer (std::unique_ptr< llvm::MemoryBuffer > originalBuffer, ChunkBufferHandler processChunkBuffer, raw_ostream &os)
Splits the specified buffer on a marker (// -----), processes each chunk independently according to the normal processChunkBuffer logic, and writes all results to os.
inline ::llvm::hash_code hash_value (TypeID id)
Enable hashing TypeID.
std::unique_ptr< llvm::Module > translateModuleToLLVMIR (ModuleOp m, llvm::LLVMContext &llvmContext, StringRef name="LLVMDialectModule")
Convert the given MLIR module into LLVM IR.
OwningModuleRef translateLLVMIRToModule (std::unique_ptr< llvm::Module > llvmModule, MLIRContext *context)
Convert the given LLVM module into MLIR's LLVM dialect.
std::unique_ptr< llvm::Module > translateModuleToNVVMIR (Operation *m, llvm::LLVMContext &llvmContext, llvm::StringRef name="LLVMDialectModule")
Convert the given LLVM-module-like operation into NVVM IR.
std::unique_ptr< llvm::Module > translateModuleToROCDLIR (Operation *m, llvm::LLVMContext &llvmContext, llvm::StringRef name="LLVMDialectModule")
Convert the given LLVM-module-like operation into ROCDL IR.
void populateBufferizeMaterializationLegality (ConversionTarget &target)
Marks ops used by bufferization for type conversion materializations as "legal" in the given ConversionTarget.
void populateEliminateBufferizeMaterializationsPatterns (MLIRContext *context, BufferizeTypeConverter &typeConverter, OwningRewritePatternList &patterns)
Populate patterns to eliminate bufferize materializations.
void populateFuncOpTypeConversionPattern (OwningRewritePatternList &patterns, MLIRContext *ctx, TypeConverter &converter)
Add a pattern to the given pattern list to convert the signature of a FuncOp with the given type converter.
LLVM_NODISCARD LogicalResult applyPartialConversion (ArrayRef< Operation *> ops, ConversionTarget &target, const FrozenRewritePatternList &patterns, DenseSet< Operation *> *unconvertedOps=nullptr)
Below we define several entry points for operation conversion.
LLVM_NODISCARD LogicalResult applyPartialConversion (Operation *op, ConversionTarget &target, const FrozenRewritePatternList &patterns, DenseSet< Operation *> *unconvertedOps=nullptr)
LLVM_NODISCARD LogicalResult applyFullConversion (ArrayRef< Operation *> ops, ConversionTarget &target, const FrozenRewritePatternList &patterns)
Apply a complete conversion on the given operations, and all nested operations.
LLVM_NODISCARD LogicalResult applyFullConversion (Operation *op, ConversionTarget &target, const FrozenRewritePatternList &patterns)
LLVM_NODISCARD LogicalResult applyAnalysisConversion (ArrayRef< Operation *> ops, ConversionTarget &target, const FrozenRewritePatternList &patterns, DenseSet< Operation *> &convertedOps)
Apply an analysis conversion on the given operations, and all nested operations.
LLVM_NODISCARD LogicalResult applyAnalysisConversion (Operation *op, ConversionTarget &target, const FrozenRewritePatternList &patterns, DenseSet< Operation *> &convertedOps)
LogicalResult applyPatternsAndFoldGreedily (Operation *op, const FrozenRewritePatternList &patterns)
Rewrite the regions of the specified operation, which must be isolated from above, by repeatedly applying the highest benefit patterns in a greedy work-list driven manner.
LogicalResult applyPatternsAndFoldGreedily (Operation *op, const FrozenRewritePatternList &patterns, unsigned maxIterations)
Rewrite the regions of the specified operation, with a user-provided limit on iterations to attempt before reaching convergence.
LogicalResult applyPatternsAndFoldGreedily (MutableArrayRef< Region > regions, const FrozenRewritePatternList &patterns)
Rewrite the given regions, which must be isolated from above.
LogicalResult applyPatternsAndFoldGreedily (MutableArrayRef< Region > regions, const FrozenRewritePatternList &patterns, unsigned maxIterations)
Rewrite the given regions, with a user-provided limit on iterations to attempt before reaching convergence.
LogicalResult applyOpPatternsAndFold (Operation *op, const FrozenRewritePatternList &patterns, bool *erased=nullptr)
Applies the specified patterns on op alone while also trying to fold it, by selecting the highest benefits patterns in a greedy manner.
LogicalResult inlineRegion (InlinerInterface &interface, Region *src, Operation *inlinePoint, BlockAndValueMapping &mapper, ValueRange resultsToReplace, TypeRange regionResultTypes, Optional< Location > inlineLoc=llvm::None, bool shouldCloneInlinedRegion=true)
This function inlines a region, 'src', into another.
LogicalResult inlineRegion (InlinerInterface &interface, Region *src, Operation *inlinePoint, ValueRange inlinedOperands, ValueRange resultsToReplace, Optional< Location > inlineLoc=llvm::None, bool shouldCloneInlinedRegion=true)
This function is an overload of the above 'inlineRegion' that allows for providing the set of operands ('inlinedOperands') that should be used in-favor of the region arguments when inlining.
LogicalResult inlineCall (InlinerInterface &interface, CallOpInterface call, CallableOpInterface callable, Region *src, bool shouldCloneInlinedRegion=true)
This function inlines a given region, 'src', of a callable operation, 'callable', into the location defined by the given call operation.
void generateLocationsFromIR (raw_ostream &os, StringRef fileName, Operation *op, OpPrintingFlags flags)
This function generates new locations from the given IR by snapshotting the IR to the given stream, and using the printed locations within that stream.
LogicalResult generateLocationsFromIR (StringRef fileName, Operation *op, OpPrintingFlags flags)
This function generates new locations from the given IR by snapshotting the IR to the given file, and using the printed locations within that file.
void generateLocationsFromIR (raw_ostream &os, StringRef fileName, StringRef tag, Operation *op, OpPrintingFlags flags)
This function generates new locations from the given IR by snapshotting the IR to the given stream, and using the printed locations within that stream.
LogicalResult generateLocationsFromIR (StringRef fileName, StringRef tag, Operation *op, OpPrintingFlags flags)
This function generates new locations from the given IR by snapshotting the IR to the given file, and using the printed locations within that file.
std::unique_ptr< Pass > createLocationSnapshotPass (OpPrintingFlags flags, StringRef fileName="", StringRef tag="")
Create a pass to generate new locations by snapshotting the IR to the given file, and using the printed locations within that file.
std::unique_ptr< Pass > createLocationSnapshotPass ()
Overload utilizing pass options for initialization.
FusionResult canFuseLoops (AffineForOp srcForOp, AffineForOp dstForOp, unsigned dstLoopDepth, ComputationSliceState *srcSlice, FusionStrategy fusionStrategy={ FusionStrategy::Generic, Value()})
Checks the feasibility of fusing the loop nest rooted at 'srcForOp' into the loop nest rooted at 'dstForOp' at 'dstLoopDepth'.
void fuseLoops (AffineForOp srcForOp, AffineForOp dstForOp, const ComputationSliceState &srcSlice)
Fuses 'srcForOp' into 'dstForOp' with destination loop block insertion point and source slice loop bounds specified in 'srcSlice'.
bool getLoopNestStats (AffineForOp forOp, LoopNestStats *stats)
Collect loop nest statistics (eg.
int64_t getComputeCost (AffineForOp forOp, LoopNestStats &stats)
Computes the total cost of the loop nest rooted at 'forOp' using 'stats'.
bool getFusionComputeCost (AffineForOp srcForOp, LoopNestStats &srcStats, AffineForOp dstForOp, LoopNestStats &dstStats, const ComputationSliceState &slice, int64_t *computeCost)
Computes and returns in 'computeCost', the total compute cost of fusing the 'slice' of the loop nest rooted at 'srcForOp' into 'dstForOp'.
LogicalResult loopUnrollFull (AffineForOp forOp)
Unrolls this for operation completely if the trip count is known to be constant.
LogicalResult loopUnrollByFactor (AffineForOp forOp, uint64_t unrollFactor)
Unrolls this for operation by the specified unroll factor.
LogicalResult loopUnrollByFactor (scf::ForOp forOp, uint64_t unrollFactor)
Unrolls 'forOp' by 'unrollFactor', returns success if the loop is unrolled.
LogicalResult loopUnrollUpToFactor (AffineForOp forOp, uint64_t unrollFactor)
Unrolls this loop by the specified unroll factor or its trip count, whichever is lower.
bool LLVM_ATTRIBUTE_UNUSED isPerfectlyNested (ArrayRef< AffineForOp > loops)
Returns true if loops is a perfectly nested loop nest, where loops appear in it from outermost to innermost.
void getPerfectlyNestedLoops (SmallVectorImpl< AffineForOp > &nestedLoops, AffineForOp root)
Get perfectly nested sequence of loops starting at root of loop nest (the first op being another AffineFor, and the second op - a terminator).
void getPerfectlyNestedLoops (SmallVectorImpl< scf::ForOp > &nestedLoops, scf::ForOp root)
LogicalResult loopUnrollJamByFactor (AffineForOp forOp, uint64_t unrollJamFactor)
Unrolls and jams this loop by the specified factor.
LogicalResult loopUnrollJamUpToFactor (AffineForOp forOp, uint64_t unrollJamFactor)
Unrolls and jams this loop by the specified factor or by the trip count (if constant), whichever is lower.
LogicalResult promoteIfSingleIteration (AffineForOp forOp)
Promotes the loop body of a AffineForOp/scf::ForOp to its containing block if the loop was known to have a single iteration.
LogicalResult promoteIfSingleIteration (scf::ForOp forOp)
Promotes the loop body of a forOp to its containing block if the forOp it can be determined that the loop has a single iteration.
void promoteSingleIterationLoops (FuncOp f)
Promotes all single iteration AffineForOp's in the Function, i.e., moves their body into the containing Block.
LLVM_NODISCARD LogicalResult affineForOpBodySkew (AffineForOp forOp, ArrayRef< uint64_t > shifts, bool unrollPrologueEpilogue=false)
Skew the operations in an affine.for's body with the specified operation-wise shifts.
void getTileableBands (FuncOp f, std::vector< SmallVector< AffineForOp, 6 >> *bands)
Identify valid and profitable bands of loops to tile.
LLVM_NODISCARD LogicalResult tilePerfectlyNested (MutableArrayRef< AffineForOp > input, ArrayRef< unsigned > tileSizes, SmallVectorImpl< AffineForOp > *tiledNest=nullptr)
Tiles the specified band of perfectly nested loops creating tile-space loops and intra-tile loops.
LLVM_NODISCARD LogicalResult tilePerfectlyNestedParametric (MutableArrayRef< AffineForOp > input, ArrayRef< Value > tileSizes, SmallVectorImpl< AffineForOp > *tiledNest=nullptr)
Tiles the specified band of perfectly nested loops creating tile-space loops and intra-tile loops, using SSA values as tiling parameters.
void interchangeLoops (AffineForOp forOpA, AffineForOp forOpB)
Performs loop interchange on 'forOpA' and 'forOpB'.
bool isValidLoopInterchangePermutation (ArrayRef< AffineForOp > loops, ArrayRef< unsigned > loopPermMap)
Checks if the loop interchange permutation 'loopPermMap', of the perfectly nested sequence of loops in 'loops', would violate dependences (loop 'i' in 'loops' is mapped to location 'j = 'loopPermMap[i]' in the interchange).
unsigned permuteLoops (MutableArrayRef< AffineForOp > inputNest, ArrayRef< unsigned > permMap)
Performs a loop permutation on a perfectly nested loop nest inputNest (where the contained loops appear from outer to inner) as specified by the permutation permMap: loop 'i' in inputNest is mapped to location 'loopPermMap[i]', where positions 0, 1, ...
AffineForOp sinkSequentialLoops (AffineForOp forOp)
SmallVector< SmallVector< AffineForOp, 8 >, 8 > tile (ArrayRef< AffineForOp > forOps, ArrayRef< uint64_t > sizes, ArrayRef< AffineForOp > targets)
SmallVector< Loops, 8 > tile (ArrayRef< scf::ForOp > forOps, ArrayRef< Value > sizes, ArrayRef< scf::ForOp > targets)
SmallVector< AffineForOp, 8 > tile (ArrayRef< AffineForOp > forOps, ArrayRef< uint64_t > sizes, AffineForOp target)
Performs tiling (with interchange) by strip-mining the forOps by sizes and sinking them, in their order of occurrence in forOps, under target.
Loops tile (ArrayRef< scf::ForOp > forOps, ArrayRef< Value > sizes, scf::ForOp target)
Loops tilePerfectlyNested (scf::ForOp rootForOp, ArrayRef< Value > sizes)
Tile a nest of scf::ForOp loops rooted at rootForOp with the given (parametric) sizes.
uint64_t affineDataCopyGenerate (Block::iterator begin, Block::iterator end, const AffineCopyOptions &copyOptions, Optional< Value > filterMemRef, DenseSet< Operation *> &copyNests)
Performs explicit copying for the contiguous sequence of operations in the block iterator range [`begin', `end'), where `end' can't be past the terminator of the block (since additional operations are potentially inserted right before end.
uint64_t affineDataCopyGenerate (AffineForOp forOp, const AffineCopyOptions &copyOptions, Optional< Value > filterMemRef, DenseSet< Operation *> &copyNests)
A convenience version of affineDataCopyGenerate for all ops in the body of an AffineForOp.
LogicalResult generateCopyForMemRegion (const MemRefRegion &memrefRegion, Operation *analyzedOp, const AffineCopyOptions &copyOptions, CopyGenerateResult &result)
generateCopyForMemRegion is similar to affineDataCopyGenerate, but works with a single memref region.
TileLoops extractFixedOuterLoops (scf::ForOp rootFOrOp, ArrayRef< int64_t > sizes)
Tile a nest of standard for loops rooted at rootForOp by finding such parametric tile sizes that the outer loops have a fixed number of iterations as defined in sizes.
void coalesceLoops (MutableArrayRef< scf::ForOp > loops)
Replace a perfect nest of "for" loops with a single linearized loop.
void collapseParallelLoops (scf::ParallelOp loops, ArrayRef< std::vector< unsigned >> combinedDimensions)
Take the ParallelLoop and for each set of dimension indices, combine them into a single dimension.
void mapLoopToProcessorIds (scf::ForOp forOp, ArrayRef< Value > processorId, ArrayRef< Value > numProcessors)
Maps forOp for execution on a parallel grid of virtual processorIds of size given by numProcessors.
void gatherLoops (FuncOp func, std::vector< SmallVector< AffineForOp, 2 >> &depthToLoops)
Gathers all AffineForOps in 'func' grouped by loop depth.
AffineForOp createCanonicalizedAffineForOp (OpBuilder b, Location loc, ValueRange lbOperands, AffineMap lbMap, ValueRange ubOperands, AffineMap ubMap, int64_t step=1)
Creates an AffineForOp while ensuring that the lower and upper bounds are canonicalized, i.e., unused and duplicate operands are removed, any constant operands propagated/folded in, and duplicate bound maps dropped.
LogicalResult separateFullTiles (MutableArrayRef< AffineForOp > nest, SmallVectorImpl< AffineForOp > *fullTileNest=nullptr)
Separates full tiles from partial tiles for a perfect nest nest by generating a conditional guard that selects between the full tile version and the partial tile version using an AffineIfOp.
LogicalResult moveLoopInvariantCode (LoopLikeOpInterface looplike)
Move loop invariant code out of looplike.
std::unique_ptr< Pass > createBufferDeallocationPass ()
Creates an instance of the BufferDeallocation pass to free all allocated buffers.
std::unique_ptr< Pass > createBufferHoistingPass ()
Creates a pass that moves allocations upwards to reduce the number of required copies that are inserted during the BufferDeallocation pass.
std::unique_ptr< Pass > createBufferLoopHoistingPass ()
Creates a pass that moves allocations upwards out of loops.
std::unique_ptr< Pass > createPromoteBuffersToStackPass (unsigned maxAllocSizeInBytes=1024, unsigned bitwidthOfIndexType=64, unsigned maxRankOfAllocatedMemRef=1)
Creates a pass that promotes heap-based allocations to stack-based ones.
std::unique_ptr< FunctionPass > createFinalizingBufferizePass ()
Creates a pass that finalizes a partial bufferization by removing remaining tensor_load and tensor_to_memref operations.
std::unique_ptr< Pass > createBufferResultsToOutParamsPass ()
Creates a pass that converts memref function results to out-params.
std::unique_ptr< Pass > createCanonicalizerPass ()
Creates an instance of the Canonicalizer pass.
std::unique_ptr< Pass > createCopyRemovalPass ()
Create a pass that removes unnecessary Copy operations.
std::unique_ptr< Pass > createCSEPass ()
Creates a pass to perform common sub expression elimination.
std::unique_ptr< OperationPass< FuncOp > > createLoopFusionPass (unsigned fastMemorySpace=0, uint64_t localBufSizeThreshold=0, bool maximalFusion=false)
Creates a loop fusion pass which fuses loops.
std::unique_ptr< Pass > createLoopInvariantCodeMotionPass ()
Creates a loop invariant code motion pass that hoists loop invariant instructions out of the loop.
std::unique_ptr< OperationPass< FuncOp > > createPipelineDataTransferPass ()
Creates a pass to pipeline explicit movement of data across levels of the memory hierarchy.
std::unique_ptr< OperationPass< FuncOp > > createLoopCoalescingPass ()
Creates a pass that transforms perfectly nested loops with independent bounds into a single loop.
std::unique_ptr< Pass > createParallelLoopCollapsingPass ()
Creates a pass that transforms a single ParallelLoop over N induction variables into another ParallelLoop over less than N induction variables.
std::unique_ptr< OperationPass< FuncOp > > createMemRefDataFlowOptPass ()
Creates a pass to perform optimizations relying on memref dataflow such as store to load forwarding, elimination of dead stores, and dead allocs.
std::unique_ptr< Pass > createStripDebugInfoPass ()
Creates a pass to strip debug information from a function.
std::unique_ptr< Pass > createPrintOpStatsPass ()
Creates a pass which prints the list of ops and the number of occurrences in the module.
std::unique_ptr< Pass > createInlinerPass ()
Creates a pass which inlines calls and callable operations as defined by the CallGraph.
std::unique_ptr< Pass > createInlinerPass (llvm::StringMap< OpPassManager > opPipelines)
Creates an instance of the inliner pass, and use the provided pass managers when optimizing callable operations with names matching the key type.
std::unique_ptr< Pass > createInlinerPass (llvm::StringMap< OpPassManager > opPipelines, std::function< void(OpPassManager &)> defaultPipelineBuilder)
Creates an instance of the inliner pass, and use the provided pass managers when optimizing callable operations with names matching the key type.
std::unique_ptr< Pass > createSCCPPass ()
Creates a pass which performs sparse conditional constant propagation over nested operations.
std::unique_ptr< Pass > createSymbolDCEPass ()
Creates a pass which delete symbol operations that are unreachable.
std::unique_ptr< OperationPass< ModuleOp > > createNormalizeMemRefsPass ()
Creates an interprocedural pass to normalize memrefs to have a trivial (identity) layout map.
template<typename Range >
bool areValuesDefinedAbove (Range values, Region &limit)
Check if all values in the provided range are defined above the limit region.
void replaceAllUsesInRegionWith (Value orig, Value replacement, Region &region)
Replace all uses of orig within the given region with replacement.
void visitUsedValuesDefinedAbove (Region &region, Region &limit, function_ref< void(OpOperand *)> callback)
Calls callback for each use of a value within region or its descendants that was defined at the ancestors of the limit.
void visitUsedValuesDefinedAbove (MutableArrayRef< Region > regions, function_ref< void(OpOperand *)> callback)
Calls callback for each use of a value within any of the regions provided that was defined in one of the ancestors.
void getUsedValuesDefinedAbove (Region &region, Region &limit, llvm::SetVector< Value > &values)
Fill values with a list of values defined at the ancestors of the limit region and used within region or its descendants.
void getUsedValuesDefinedAbove (MutableArrayRef< Region > regions, llvm::SetVector< Value > &values)
Fill values with a list of values used within any of the regions provided but defined in one of the ancestors.
LogicalResult simplifyRegions (MutableArrayRef< Region > regions)
Run a set of structural simplifications over the given regions.
LogicalResult replaceAllMemRefUsesWith (Value oldMemRef, Value newMemRef, ArrayRef< Value > extraIndices={}, AffineMap indexRemap=AffineMap(), ArrayRef< Value > extraOperands={}, ArrayRef< Value > symbolOperands={}, Operation *domInstFilter=nullptr, Operation *postDomInstFilter=nullptr, bool allowNonDereferencingOps=false, bool replaceInDeallocOp=false)
Replaces all "dereferencing" uses of oldMemRef with newMemRef while optionally remapping the old memref's indices using the supplied affine map, indexRemap.
LogicalResult replaceAllMemRefUsesWith (Value oldMemRef, Value newMemRef, Operation *op, ArrayRef< Value > extraIndices={}, AffineMap indexRemap=AffineMap(), ArrayRef< Value > extraOperands={}, ArrayRef< Value > symbolOperands={}, bool allowNonDereferencingOps=false)
Performs the same replacement as the other version above but only for the dereferencing uses of oldMemRef in op, except in cases where 'allowNonDereferencingOps' is set to true where we replace the non-dereferencing uses as well.
LogicalResult normalizeMemRef (AllocOp op)
Rewrites the memref defined by this alloc op to have an identity layout map and updates all its indexing uses.
MemRefType normalizeMemRefType (MemRefType memrefType, OpBuilder builder, unsigned numSymbolicOperands)
Uses the old memref type map layout and computes the new memref type to have a new shape and a layout map, where the old layout map has been normalized to an identity layout map.
Operation * createComposedAffineApplyOp (OpBuilder &builder, Location loc, ArrayRef< Value > operands, ArrayRef< Operation *> affineApplyOps, SmallVectorImpl< Value > *results)
Creates and inserts into 'builder' a new AffineApplyOp, with the number of its results equal to the number of operands, as a composition of all other AffineApplyOps reachable from input parameter 'operands'.
void createAffineComputationSlice (Operation *opInst, SmallVectorImpl< AffineApplyOp > *sliceOps)
Given an operation, inserts one or more single result affine apply operations, results of which are exclusively used by this operation.
void viewGraph (Block &block, const Twine &name, bool shortNames=false, const Twine &title="", llvm::GraphProgram::Name program=llvm::GraphProgram::DOT)
Displays the graph in a window.
raw_ostream & writeGraph (raw_ostream &os, Block &block, bool shortNames=false, const Twine &title="")
std::unique_ptr< OperationPass< ModuleOp > > createPrintOpGraphPass (raw_ostream &os=llvm::errs(), bool shortNames=false, const Twine &title="")
Creates a pass to print op graphs.
void viewGraph (Region &region, const Twine &name, bool shortNames=false, const Twine &title="", llvm::GraphProgram::Name program=llvm::GraphProgram::DOT)
Displays the CFG in a window.
raw_ostream & writeGraph (raw_ostream &os, Region &region, bool shortNames=false, const Twine &title="")
std::unique_ptr< mlir::OperationPass< mlir::FuncOp > > createPrintCFGGraphPass (raw_ostream &os=llvm::errs(), bool shortNames=false, const Twine &title="")
Creates a pass to print CFG graphs.
LogicalResult mlirTranslateMain (int argc, char **argv, llvm::StringRef toolName)
Translate to/from an MLIR module from/to an external representation (e.g.
template<typename ConcreteDialect >
void registerDialect (DialectRegistry &registry)
void vectorizeAffineLoops (Operation *parentOp, DenseSet< Operation *> &loops, ArrayRef< int64_t > vectorSizes, ArrayRef< int64_t > fastestVaryingPattern)
External utility to vectorize affine loops in 'loops' using the n-D vectorization factors in 'vectorSizes'.
void registerTestRoundtripSPIRV ()
void registerTestRoundtripDebugSPIRV ()
Variables
static constexpr unsigned kDeriveIndexBitwidthFromDataLayout = 0
Value to pass as bitwidth for the index type when the converter is expected to derive the bitwidth from the LLVM data layout.
std::function< llvm::Error(llvm::Module *)> makeOptimizingTransformer (unsigned optLevel, unsigned sizeLevel, llvm::TargetMachine *targetMachine)
Create a module transformer function for MLIR ExecutionEngine that runs LLVM IR passes corresponding to the given speed and size optimization levels (e.g.
std::function< llvm::Error(llvm::Module *)> makeLLVMPassesTransformer (llvm::ArrayRef< const llvm::PassInfo *> llvmPasses, llvm::Optional< unsigned > mbOptLevel, llvm::TargetMachine *targetMachine, unsigned optPassesInsertPos=0)
Create a module transformer function for MLIR ExecutionEngine that runs LLVM IR passes explicitly specified, plus an optional optimization level, Any optimization passes, if present, will be inserted before the pass at position optPassesInsertPos.
const int64_t kUnknownNumRegionInvocations = -1
const int nullIndex = std::numeric_limits<int>::max()
Detailed Description
Include the generated interface declarations.
ValueType.
Typedef Documentation
AttributeStorageAllocator
using mlir::AttributeStorageAllocator = typedef StorageUniquer::StorageAllocator
Definition at line 131 of file AttributeSupport.h.
BlobGenerator
using mlir::BlobGenerator = typedef std::function<OwnedBlob(const std::string &, Location, StringRef)>
Definition at line 37 of file GPUCommonPass.h.
ChunkBufferHandler
using mlir::ChunkBufferHandler = typedef function_ref<LogicalResult(std::unique_ptr<llvm::MemoryBuffer> chunkBuffer, raw_ostream &os)>
Definition at line 28 of file ToolUtilities.h.
DefaultAttributeStorage
using mlir::DefaultAttributeStorage = typedef AttributeStorage
Default storage type for attributes that require no additional initialization or storage.
Definition at line 123 of file AttributeSupport.h.
DefaultTypeStorage
using mlir::DefaultTypeStorage = typedef TypeStorage
Default storage type for types that require no additional initialization or storage.
Definition at line 108 of file TypeSupport.h.
DenseMap
template<typename KeyT , typename ValueT , typename KeyInfoT = DenseMapInfo<KeyT>, typename BucketT = llvm::detail::DenseMapPair<KeyT, ValueT>> using mlir::DenseMap = typedef llvm::DenseMap<KeyT, ValueT, KeyInfoT, BucketT>
Definition at line 103 of file LLVM.h.
DenseSet
template<typename ValueT , typename ValueInfoT = DenseMapInfo<ValueT>> using mlir::DenseSet = typedef llvm::DenseSet<ValueT, ValueInfoT>
Definition at line 105 of file LLVM.h.
DialectAllocatorFunction
using mlir::DialectAllocatorFunction = typedef std::function<Dialect *(MLIRContext *)>
Definition at line 28 of file Dialect.h.
Direction
using mlir::Direction = typedef Simplex::Direction
Definition at line 14 of file Simplex.cpp.
DominanceInfoNode
using mlir::DominanceInfoNode = typedef llvm::DomTreeNodeBase<Block>
Definition at line 19 of file Dominance.h.
FilterFunctionType
using mlir::FilterFunctionType = typedef std::function<bool(Operation &)>
A NestedPattern is a nested operation walker that:
recursively matches a substructure in the tree;
uses a filter function to refine matches with extra semantic constraints (passed via a lambda of type FilterFunctionType);
TODO: optionally applies actions (lambda).
Nested patterns are meant to capture imperfectly nested loops while matching properties over the whole loop nest. For instance, in vectorization we are interested in capturing all the imperfectly nested loops of a certain type and such that all the load and stores have certain access patterns along the loops' induction variables). Such NestedMatches are first captured using the match function and are later processed to analyze properties and apply transformations in a non-greedy way.
The NestedMatches captured in the IR can grow large, especially after aggressive unrolling. As experience has shown, it is generally better to use a plain walk over operations to match flat patterns but the current implementation is competitive nonetheless.
Definition at line 90 of file NestedMatcher.h.
function_ref
template<typename Fn > using mlir::function_ref = typedef llvm::function_ref<Fn>
Definition at line 126 of file LLVM.h.
GenFunction
using mlir::GenFunction = typedef std::function<bool(const llvm::RecordKeeper &recordKeeper, raw_ostream &os)>
Generator function to invoke.
Definition at line 24 of file GenInfo.h.
Loops
using mlir::Loops = typedef SmallVector<scf::ForOp, 8>
Performs tiling fo imperfectly nested loops (with interchange) by strip-mining the forOps by sizes and sinking them, in their order of occurrence in forOps, under each of the targets.
Returns the new AffineForOps, one per each of (forOps, targets) pair, nested immediately under each of targets.
Definition at line 145 of file LoopUtils.h.
LoweringCallback
using mlir::LoweringCallback = typedef std::function<std::unique_ptr<llvm::Module>(Operation *, llvm::LLVMContext &, StringRef)>
Definition at line 39 of file GPUCommonPass.h.
NamedAttribute
using mlir::NamedAttribute = typedef std::pair<Identifier, Attribute>
NamedAttribute is combination of a name, represented by an Identifier, and a value, represented by an Attribute.
The attribute pointer should always be non-null.
Definition at line 130 of file Attributes.h.
OpAsmSetValueNameFn
using mlir::OpAsmSetValueNameFn = typedef function_ref<void(Value, StringRef)>
A functor used to set the name of the start of a result group of an operation.
See 'getAsmResultNames' below for more details.
Definition at line 869 of file OpImplementation.h.
OperandElementTypeRange
using mlir::OperandElementTypeRange = typedef iterator_range<OperandElementTypeIterator>
Definition at line 77 of file TypeUtilities.h.
OwnedBlob
using mlir::OwnedBlob = typedef std::unique_ptr<std::vector<char> >
Definition at line 35 of file GPUCommonPass.h.
PassAllocatorFunction
using mlir::PassAllocatorFunction = typedef std::function<std::unique_ptr<Pass>()>
Definition at line 37 of file PassRegistry.h.
PassRegistryFunction
using mlir::PassRegistryFunction = typedef std::function<LogicalResult(OpPassManager &, StringRef options, function_ref<LogicalResult(const Twine &)> errorHandler)>
A registry function that adds passes to the given pass manager.
This should also parse options and return success() if parsing succeeded. errorHandler is a functor used to emit errors during parsing. parameter corresponds to the raw location within the pipeline string. This should always return failure.
Definition at line 36 of file PassRegistry.h.
PDLConstraintFunction
using mlir::PDLConstraintFunction = typedef std::function<LogicalResult(ArrayRef<PDLValue>, ArrayAttr, PatternRewriter &)>
A generic PDL pattern constraint function.
This function applies a constraint to a given set of opaque PDLValue entities. The second parameter is a set of constant value parameters specified in Attribute form. Returns success if the constraint successfully held, failure otherwise.
Definition at line 312 of file PatternMatch.h.
PDLCreateFunction
using mlir::PDLCreateFunction = typedef std::function<PDLValue(ArrayRef<PDLValue>, ArrayAttr, PatternRewriter &)>
A native PDL creation function.
This function creates a new PDLValue given a set of existing PDL values, a set of constant parameters specified in Attribute form, and a PatternRewriter. Returns the newly created PDLValue.
Definition at line 317 of file PatternMatch.h.
PDLRewriteFunction
using mlir::PDLRewriteFunction = typedef std::function<void(Operation *, ArrayRef<PDLValue>, ArrayAttr, PatternRewriter &)>
A native PDL rewrite function.
This function rewrites the given root operation using the provided PatternRewriter. This method is only invoked when the corresponding match was successful.
Definition at line 322 of file PatternMatch.h.
PDLSingleEntityConstraintFunction
using mlir::PDLSingleEntityConstraintFunction = typedef std::function<LogicalResult(PDLValue, ArrayAttr, PatternRewriter &)>
A generic PDL pattern constraint function.
This function applies a constraint to a given opaque PDLValue entity. The second parameter is a set of constant value parameters specified in Attribute form. Returns success if the constraint successfully held, failure otherwise.
Definition at line 328 of file PatternMatch.h.
ResultElementTypeRange
using mlir::ResultElementTypeRange = typedef iterator_range<ResultElementTypeIterator>
Definition at line 94 of file TypeUtilities.h.
StringSet
template<typename AllocatorTy = llvm::MallocAllocator> using mlir::StringSet = typedef llvm::StringSet<AllocatorTy>
Definition at line 107 of file LLVM.h.
StringSwitch
template<typename T , typename R = T> using mlir::StringSwitch = typedef llvm::StringSwitch<T, R>
Definition at line 117 of file LLVM.h.
TileLoops
using mlir::TileLoops = typedef std::pair<Loops, Loops>
Definition at line 146 of file LoopUtils.h.
TransitiveFilter
using mlir::TransitiveFilter = typedef std::function<bool(Operation *)>
Type of the condition to limit the propagation of transitive use-defs.
This can be used in particular to limit the propagation to a given Scope or to avoid passing through certain types of operation in a configurable manner.
Definition at line 27 of file SliceAnalysis.h.
TranslateFromMLIRFunction
using mlir::TranslateFromMLIRFunction = typedef std::function<LogicalResult(ModuleOp, llvm::raw_ostream &output)>
Interface of the function that translates MLIR to a different format and outputs the result to a stream.
It is allowed to modify the module.
Definition at line 47 of file Translation.h.
TranslateFunction
using mlir::TranslateFunction = typedef std::function<LogicalResult(llvm::SourceMgr &sourceMgr, llvm::raw_ostream &output, MLIRContext *)>
Interface of the function that performs file-to-file translation involving MLIR.
The input file is held in the given MemoryBuffer; the output file should be written to the given raw_ostream. The implementation should create all MLIR constructs needed during the process inside the given context. This can be used for round-tripping external formats through the MLIR system.
Definition at line 55 of file Translation.h.
TranslateSourceMgrToMLIRFunction
using mlir::TranslateSourceMgrToMLIRFunction = typedef std::function<OwningModuleRef(llvm::SourceMgr &sourceMgr, MLIRContext *)>
Interface of the function that translates the sources managed by sourceMgr to MLIR.
The source manager has at least one buffer. The implementation should create a new MLIR ModuleOp in the given context and return a pointer to it, or a nullptr in case of any error.
Definition at line 35 of file Translation.h.
TranslateStringRefToMLIRFunction
using mlir::TranslateStringRefToMLIRFunction = typedef std::function<OwningModuleRef(llvm::StringRef, MLIRContext *)>
Interface of the function that translates the given string to MLIR.
The implementation should create a new MLIR ModuleOp in the given context. If source-related error reporting is required from within the function, use TranslateSourceMgrToMLIRFunction instead.
Definition at line 42 of file Translation.h.
TypeStorageAllocator
using mlir::TypeStorageAllocator = typedef StorageUniquer::StorageAllocator
This is a utility allocator used to allocate memory for instances of derived Types.
Definition at line 116 of file TypeSupport.h.
TypeSwitch
template<typename T , typename ResultT = void> using mlir::TypeSwitch = typedef llvm::TypeSwitch<T, ResultT>
Definition at line 120 of file LLVM.h.
VectorizableLoopFun
using mlir::VectorizableLoopFun = typedef std::function<bool(AffineForOp)>
Definition at line 63 of file LoopAnalysis.h.
Enumeration Type Documentation
AffineExprKind
enum mlir::AffineExprKind strong
Enumerator
Add
Mul
RHS of mul is always a constant or a symbolic expression.
Mod
RHS of mod is always a constant or a symbolic expression with a positive value.
FloorDiv
RHS of floordiv is always a constant or a symbolic expression.
CeilDiv
RHS of ceildiv is always a constant or a symbolic expression.
LAST_AFFINE_BINARY_OP
This is a marker for the last affine binary op.
The range of binary op's is expected to be this element and earlier.
Constant
Constant integer.
DimId
Dimensional identifier.
SymbolId
Symbolic identifier.
Definition at line 38 of file AffineExpr.h.
DiagnosticSeverity
enum mlir::DiagnosticSeverity strong
Defines the different supported severity of a diagnostic.
Enumerator
Note
Warning
Error
Remark
Definition at line 39 of file Diagnostics.h.
IteratorType
enum mlir::IteratorType strong
Typed representation for loop type strings.
Enumerator
Parallel
Reduction
Definition at line 124 of file StructuredOpsUtils.h.
OperationProperty
enum mlir::OperationProperty strong
Enumerator
Commutative
This bit is set for an operation if it is a commutative operation: that is an operator where order of operands does not change the result of the operation.
For example, in a binary commutative operation, "a op b" and "b op a" produce the same results.
Terminator
This bit is set for an operation if it is a terminator: that means an operation at the end of a block.
IsolatedFromAbove
This bit is set for operations that are completely isolated from above.
This is used for operations whose regions are explicit capture only, i.e. they are never allowed to implicitly reference values defined above the parent operation.
Definition at line 59 of file OperationSupport.h.
PassDisplayMode
enum mlir::PassDisplayMode strong
An enum describing the different display modes for the information within the pass manager.
Enumerator
List
Pipeline
Definition at line 146 of file PassManager.h.
RegionKind
enum mlir::RegionKind strong
The kinds of regions contained in an operation.
SSACFG regions require the SSA-Dominance property to hold. Graph regions do not require SSA-Dominance. If a registered operation does not implement RegionKindInterface, then any regions it contains are assumed to be SSACFG regions.
Enumerator
SSACFG
Graph
Definition at line 26 of file RegionKindInterface.h.
SDBMExprKind
enum mlir::SDBMExprKind strong
Enumerator
Add
Stripe
Diff
Constant
DimId
SymbolId
Neg
Definition at line 26 of file SDBMExpr.h.
TraversalMode
enum mlir::TraversalMode
traversal.
Enumerator
SinglePath
Backtrack
MultiPath
Definition at line 34 of file ReductionTreePass.h.
Function Documentation
affineDataCopyGenerate() [1/2]
uint64_t mlir::affineDataCopyGenerate (Block::iterator begin, Block::iterator end, const AffineCopyOptions & copyOptions, Optional< Value > filterMemRef, DenseSet< Operation *> & copyNests)
Performs explicit copying for the contiguous sequence of operations in the block iterator range [`begin', `end'), where `end' can't be past the terminator of the block (since additional operations are potentially inserted right before end.
Returns the total size of fast memory space buffers used. copyOptions provides various parameters, and the output argument copyNests is the set of all copy nests inserted, each represented by its root affine.for. Since we generate alloc's and dealloc's for all fast buffers (before and after the range of operations resp. or at a hoisted position), all of the fast memory capacity is assumed to be available for processing this block range. When 'filterMemRef' is specified, copies are only generated for the provided MemRef.
Definition at line 2651 of file LoopUtils.cpp.
References mlir::Operation::emitError(), failed(), mlir::AffineCopyOptions::fastMemCapacityBytes, findHighestBlockForPlacement(), generateCopy(), getFullMemRefAsRegion(), mlir::Operation::getLoc(), getNestingDepth(), mlir::AffineCopyOptions::slowMemorySpace, and succeeded().
Referenced by affineDataCopyGenerate(), and createAffineDataCopyGenerationPass().
affineDataCopyGenerate() [2/2]
uint64_t mlir::affineDataCopyGenerate (AffineForOp forOp, const AffineCopyOptions & copyOptions, Optional< Value > filterMemRef, DenseSet< Operation *> & copyNests)
A convenience version of affineDataCopyGenerate for all ops in the body of an AffineForOp.
Definition at line 2842 of file LoopUtils.cpp.
References affineDataCopyGenerate().
affineForOpBodySkew()
LogicalResult mlir::affineForOpBodySkew (AffineForOp forOp, ArrayRef< uint64_t > shifts, bool unrollPrologueEpilogue = false)
Skew the operations in an affine.for's body with the specified operation-wise shifts.
The shifts are with respect to the original execution order, and are multiplied by the loop 'step' before being applied. If unrollPrologueEpilogue is set, fully unroll the prologue and epilogue loops when possible.
Definition at line 305 of file LoopUtils.cpp.
References applyOpPatternsAndFold(), generateShiftedLoop(), getConstantTripCount(), mlir::Builder::getShiftedAffineMap(), isOpwiseShiftValid(), loopUnrollFull(), and success().
Referenced by findMatchingStartFinishInsts().
affineParallelize()
void mlir::affineParallelize (AffineForOp forOp)
Replaces parallel affine.for op with 1-d affine.parallel op.
Replace affine.for with a 1-d affine.parallel and clone the former's body into the latter while remapping values.
mlir::isLoopParallel detect the parallel affine.for ops. There is no cost model currently used to drive this parallelization.
Definition at line 134 of file Utils.cpp.
References mlir::OpBuilder::create(), mlir::Attribute::getContext(), mlir::AffineMap::getMultiDimIdentityMap(), and mlir::AffineMap::getNumResults().
applyAnalysisConversion() [1/2]
LogicalResult mlir::applyAnalysisConversion (ArrayRef< Operation *> ops, ConversionTarget & target, const FrozenRewritePatternList & patterns, DenseSet< Operation *> & convertedOps)
Apply an analysis conversion on the given operations, and all nested operations.
This method analyzes which operations would be successfully converted to the target if a conversion was applied. All operations that were found to be legalizable to the given 'target' are placed within the provided 'convertedOps' set; note that no actual rewrites are applied to the operations on success and only pre-existing operations are added to the set. This method only returns failure if there are unreachable blocks in any of the regions nested within 'ops'.
This method analyzes which operations would be successfully converted to the target if a conversion was applied. All operations that were found to be legalizable to the given 'target' are placed within the provided 'convertedOps' set; note that no actual rewrites are applied to the operations on success and only pre-existing operations are added to the set.
Definition at line 2716 of file DialectConversion.cpp.
Referenced by applyAnalysisConversion(), and mlir::ConversionTarget::isDynamicallyLegal().
applyAnalysisConversion() [2/2]
LogicalResult mlir::applyAnalysisConversion (Operation * op, ConversionTarget & target, const FrozenRewritePatternList & patterns, DenseSet< Operation *> & convertedOps)
Definition at line 2725 of file DialectConversion.cpp.
References applyAnalysisConversion().
applyCmpPredicate() [1/2]
bool mlir::applyCmpPredicate (CmpIPredicate predicate, const APInt & lhs, const APInt & rhs)
Compute lhs pred rhs, where pred is one of the known integer comparison predicates.
Definition at line 780 of file Ops.cpp.
References mlir::edsc::op::eq(), mlir::edsc::op::ne(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), and mlir::edsc::op::ult().
Referenced by applyCmpPredicate(), applyCmpPredicateToEqualOperands(), and mlir::DmaWaitOp::getNumElements().
applyCmpPredicate() [2/2]
bool mlir::applyCmpPredicate (CmpFPredicate predicate, const APFloat & lhs, const APFloat & rhs)
Compute lhs pred rhs, where pred is one of the known floating point comparison predicates.
Definition at line 858 of file Ops.cpp.
References applyCmpPredicate(), collapseBranch(), mlir::OpBuilder::create(), failed(), failure(), mlir::IntegerType::get(), mlir::IntegerAttr::get(), mlir::Block::getSinglePredecessor(), mlir::Block::getTerminator(), mlir::Block::getUniquePredecessor(), mlir::FloatAttr::getValue(), mlir::OwningRewritePatternList::insert(), m_NonZero(), m_Zero(), matchPattern(), mlir::PatternRewriter::replaceOpWithNewOp(), and success().
applyFullConversion() [1/2]
LogicalResult mlir::applyFullConversion (ArrayRef< Operation *> ops, ConversionTarget & target, const FrozenRewritePatternList & patterns)
Apply a complete conversion on the given operations, and all nested operations.
This method returns failure if the conversion of any operation fails, or if there are unreachable blocks in any of the regions nested within 'ops'.
This method will return failure if the conversion of any operation fails.
Definition at line 2698 of file DialectConversion.cpp.
Referenced by applyFullConversion(), mlir::ConversionTarget::isDynamicallyLegal(), populateEliminateBufferizeMaterializationsPatterns(), populateLinalgToLLVMConversionPatterns(), mlir::linalg::populateLinalgToStandardConversionPatterns(), populateSPIRVLayoutInfoPatterns(), and populateVectorToSPIRVPatterns().
applyFullConversion() [2/2]
LogicalResult mlir::applyFullConversion (Operation * op, ConversionTarget & target, const FrozenRewritePatternList & patterns)
Definition at line 2704 of file DialectConversion.cpp.
References applyFullConversion().
applyOpPatternsAndFold()
LogicalResult mlir::applyOpPatternsAndFold (Operation * op, const FrozenRewritePatternList & patterns, bool * erased = nullptr)
Applies the specified patterns on op alone while also trying to fold it, by selecting the highest benefits patterns in a greedy manner.
Rewrites only op using the supplied canonicalization patterns and folding.
Returns success if no more patterns can be matched. erased is set to true if op was folded away or erased as a result of becoming dead. Note: This does not apply any patterns recursively to the regions of op.
erased is set to true if the op is erased as a result of being folded, replaced, or dead.
Definition at line 359 of file GreedyPatternRewriteDriver.cpp.
References failed(), and mlir::Operation::getContext().
Referenced by affineForOpBodySkew(), createAffineDataCopyGenerationPass(), createSimplifyAffineStructuresPass(), and hoistAffineIfOp().
applyPartialConversion() [1/2]
LogicalResult mlir::applyPartialConversion (ArrayRef< Operation *> ops, ConversionTarget & target, const FrozenRewritePatternList & patterns, DenseSet< Operation *> * unconvertedOps = nullptr)
Below we define several entry points for operation conversion.
Apply a partial conversion on the given operations and all nested operations.
It is important to note that the patterns provided to the conversion framework may have additional constraints. See the PatternRewriter Hooks section of the ConversionPatternRewriter, to see what additional constraints are imposed on the use of the PatternRewriter. Apply a partial conversion on the given operations and all nested operations. This method converts as many operations to the target as possible, ignoring operations that failed to legalize. This method only returns failure if there ops explicitly marked as illegal. If an unconvertedOps set is provided, all operations that are found not to be legalizable to the given target are placed within that set. (Note that if there is an op explicitly marked as illegal, the conversion terminates and the unconvertedOps set will not necessarily be complete.)
This method converts as many operations to the target as possible, ignoring operations that failed to legalize. This method only returns failure if there ops explicitly marked as illegal. If an unconvertedOps set is provided, all operations that are found not to be legalizable to the given target are placed within that set. (Note that if there is an op explicitly marked as illegal, the conversion terminates and the unconvertedOps set will not necessarily be complete.)
Definition at line 2678 of file DialectConversion.cpp.
Referenced by applyPartialConversion(), encodeKernelName(), finalizeBufferAllocation(), mlir::ConversionTarget::isDynamicallyLegal(), lowerEntryPointABIAttr(), outlineExecuteOp(), populateAffineToVectorConversionPatterns(), populateElementwiseToLinalgConversionPatterns(), populateLoopToStdConversionPatterns(), populateOpenMPToLLVMConversionPatterns(), populateStdBufferizePatterns(), populateTensorBufferizePatterns(), populateVectorToROCDLConversionPatterns(), and mlir::LLVMTypeConverter::promoteOperands().
applyPartialConversion() [2/2]
LogicalResult mlir::applyPartialConversion (Operation * op, ConversionTarget & target, const FrozenRewritePatternList & patterns, DenseSet< Operation *> * unconvertedOps = nullptr)
Definition at line 2687 of file DialectConversion.cpp.
References applyPartialConversion().
applyPassManagerCLOptions()
void mlir::applyPassManagerCLOptions (PassManager & pm)
Apply any values provided to the pass manager options that were registered with 'registerPassManagerOptions'.
Definition at line 150 of file PassManagerOptions.cpp.
References mlir::PassManager::enableCrashReproducerGeneration(), and mlir::PassManager::enableStatistics().
Referenced by mlir::PassManager::PassTimingConfig::getDisplayMode(), and performActions().
applyPatternsAndFoldGreedily() [1/4]
LogicalResult mlir::applyPatternsAndFoldGreedily (Operation * op, const FrozenRewritePatternList & patterns)
Rewrite the regions of the specified operation, which must be isolated from above, by repeatedly applying the highest benefit patterns in a greedy work-list driven manner.
This variant may stop after a predefined number of iterations, see the alternative below to provide a specific number of iterations before stopping in absence of convergence. Return success if the iterative process converged and no more patterns can be matched in the result operation regions. Note: This does not apply patterns to the top-level operation itself. These methods also perform folding and simple dead-code elimination before attempting to match any of the provided patterns.
Return success if no more patterns can be matched in the result operation regions. Note: This does not apply patterns to the top-level operation itself.
Definition at line 221 of file GreedyPatternRewriteDriver.cpp.
Referenced by applyPatternsAndFoldGreedily(), mlir::linalg::applyStagedPatterns(), applyTilingToLoopPatterns(), createGenericOpFromNamedOp(), mlir::linalg::fuseTensorOps(), hoistAffineIfOp(), lowerLinalgToLoopsImpl(), populateConvertShapeConstraintsConversionPatterns(), populateLinalgFoldUnitExtentDimsPatterns(), populateStdLegalizationPatternsForSPIRVLowering(), populateVectorToSCFConversionPatterns(), reshapeLowerToHigher(), and mlir::linalg::CodegenStrategy::transform().
applyPatternsAndFoldGreedily() [2/4]
LogicalResult mlir::applyPatternsAndFoldGreedily (Operation * op, const FrozenRewritePatternList & patterns, unsigned maxIterations)
Rewrite the regions of the specified operation, with a user-provided limit on iterations to attempt before reaching convergence.
Definition at line 226 of file GreedyPatternRewriteDriver.cpp.
References applyPatternsAndFoldGreedily(), and mlir::Operation::getRegions().
applyPatternsAndFoldGreedily() [3/4]
LogicalResult mlir::applyPatternsAndFoldGreedily (MutableArrayRef< Region > regions, const FrozenRewritePatternList & patterns)
Rewrite the given regions, which must be isolated from above.
Definition at line 234 of file GreedyPatternRewriteDriver.cpp.
References applyPatternsAndFoldGreedily().
applyPatternsAndFoldGreedily() [4/4]
LogicalResult mlir::applyPatternsAndFoldGreedily (MutableArrayRef< Region > regions, const FrozenRewritePatternList & patterns, unsigned maxIterations)
Rewrite the given regions, with a user-provided limit on iterations to attempt before reaching convergence.
Definition at line 240 of file GreedyPatternRewriteDriver.cpp.
References mlir::Operation::erase(), failure(), isOpTriviallyDead(), succeeded(), and success().
areValuesDefinedAbove()
template<typename Range > bool mlir::areValuesDefinedAbove (Range values, Region & limit)
Check if all values in the provided range are defined above the limit region.
That is, if they are defined in a region that is a proper ancestor of limit.
Definition at line 23 of file RegionUtils.h.
References getUsedValuesDefinedAbove(), replaceAllUsesInRegionWith(), simplifyRegions(), and visitUsedValuesDefinedAbove().
Referenced by checkAffineLoopNestMappableImpl().
barePtrFuncArgTypeConverter()
LogicalResult mlir::barePtrFuncArgTypeConverter (LLVMTypeConverter & converter, Type type, SmallVectorImpl< Type > & result)
Callback to convert function argument types.
It converts MemRef function arguments to bare pointers to the MemRef element type.
Definition at line 88 of file StandardToLLVM.cpp.
References mlir::LLVMTypeConverter::convertCallingConventionType(), failure(), and success().
Referenced by mlir::LLVMTypeConverter::convertFunctionSignature().
bindDims()
template<typename... AffineExprTy> void mlir::bindDims (MLIRContext * ctx, AffineExprTy &... exprs)
Bind a list of AffineExpr references to DimExpr at positions: [0 .
. sizeof...(exprs)]
Definition at line 291 of file AffineExpr.h.
Referenced by createScopedSubViewIntersection(), isColumnMajorMatmul(), isRowMajorMatmul(), mlir::edsc::ops::linalg_generic_conv_nhwc(), mlir::edsc::ops::linalg_generic_dilated_conv_nhwc(), mlir::edsc::ops::linalg_generic_matmul(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), mlir::ContractionOpToDotLowering::matchAndRewrite(), and mlir::edsc::ops::vector_contraction_matmul().
boundCheckLoadOrStoreOp()
template<typename LoadOrStoreOpPointer > LogicalResult mlir::boundCheckLoadOrStoreOp (LoadOrStoreOpPointer loadOrStoreOp, bool emitError = true)
Checks a load or store op for an out of bound access; returns failure if the access is out of bounds along any of the dimensions, success otherwise.
Emits a diagnostic error (with location information) if emitError is true.
Referenced by getMemRefSizeInBytes().
buildAffineLoopNest() [1/2]
void mlir::buildAffineLoopNest (OpBuilder & builder, Location loc, ArrayRef< int64_t > lbs, ArrayRef< int64_t > ubs, ArrayRef< int64_t > steps, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn = nullptr)
Builds a perfect nest of affine "for" loops, i.e.
each loop except the innermost only contains another loop and a terminator. The loops iterate from "lbs" to "ubs" with "steps". The body of the innermost loop is populated by calling "bodyBuilderFn" and providing it with an OpBuilder, a Location and a list of loop induction variables.
Definition at line 1987 of file AffineOps.cpp.
References buildAffineLoopFromConstants(), and buildAffineLoopNestImpl().
Referenced by mlir::edsc::affineLoopNestBuilder().
buildAffineLoopNest() [2/2]
void mlir::buildAffineLoopNest (OpBuilder & builder, Location loc, ValueRange lbs, ValueRange ubs, ArrayRef< int64_t > steps, function_ref< void(OpBuilder &, Location, ValueRange)> bodyBuilderFn = nullptr)
Definition at line 1995 of file AffineOps.cpp.
References buildAffineLoopFromValues(), buildAffineLoopNestImpl(), mlir::PatternRewriter::eraseBlock(), failure(), mlir::PatternRewriter::finalizeRootUpdate(), mlir::PatternRewriter::startRootUpdate(), and success().
buildTripCountMapAndOperands()
void mlir::buildTripCountMapAndOperands (AffineForOp forOp, AffineMap * tripCountMap, SmallVectorImpl< Value > * tripCountOperands)
Returns the trip count of the loop as an affine map with its corresponding operands if the latter is expressible as an affine expression, and nullptr otherwise.
Returns the trip count of the loop as an affine expression if the latter is expressible as an affine expression, and nullptr otherwise.
This method always succeeds as long as the lower bound is not a multi-result map. The trip count expression is simplified before returning. This method only utilizes map composition to construct lower and upper bounds before computing the trip count expressions
The trip count expression is simplified before returning. This method only utilizes map composition to construct lower and upper bounds before computing the trip count expressions.
Definition at line 33 of file LoopAnalysis.cpp.
References ceilDiv(), mlir::AffineValueMap::difference(), and mlir::AffineMap::get().
Referenced by getCleanupLoopLowerBound(), getConstantTripCount(), and getLargestDivisorOfTripCount().
canFoldIntoConsumerOp() [1/2]
bool mlir::canFoldIntoConsumerOp (MemRefCastOp castOp)
Determines whether MemRefCastOp casts to a more dynamic version of the source memref.
This is useful to to fold a memref_cast into a consuming op and implement canonicalization patterns for ops in different dialects that may consume the results of memref_cast operations. Such foldable memref_cast operations are typically inserted as view and subview ops and are canonicalized, to preserve the type compatibility of their uses.
Returns true when all conditions are met:
source and result are ranked memrefs with strided semantics and same element type and rank.
each of the source's size, offset or stride has more static information than the corresponding result's size, offset or stride.
Example 1:
%1 = memref_cast %0 : memref<8x16xf32> to memref<?x?xf32>
%2 = consumer %1 ... : memref<?x?xf32> ...
may fold into:
%2 = consumer %0 ... : memref<8x16xf32> ...
Example 2:
%1 = memref_cast %0 : memref<?x16xf32, affine_map<(i, j)->(16 * i + j)>>
       to memref<?x?xf32>
consumer %1 : memref<?x?xf32> ...
may fold into:
consumer %0 ... : memref<?x16xf32, affine_map<(i, j)->(16 * i + j)>>
This is useful to to fold a memref_cast into a consuming op and implement canonicalization patterns for ops in different dialects that may consume the results of memref_cast operations. Such foldable memref_cast operations are typically inserted as view and subview ops are canonicalized, to preserve the type compatibility of their uses.
Returns true when all conditions are met:
source and result are ranked memrefs with strided semantics and same element type and rank.
each of the source's size, offset or stride has more static information than the corresponding result's size, offset or stride.
Example 1:
%1 = memref_cast %0 : memref<8x16xf32> to memref<?x?xf32>
%2 = consumer %1 ... : memref<?x?xf32> ...
may fold into:
%2 = consumer %0 ... : memref<8x16xf32> ...
Example 2:
%1 = memref_cast %0 : memref<?x16xf32, affine_map<(i, j)->(16 * i + j)>>
       to memref<?x?xf32>
consumer %1 : memref<?x?xf32> ...
may fold into:
consumer %0 ... : memref<?x16xf32, affine_map<(i, j)->(16 * i + j)>>
Definition at line 3472 of file Ops.cpp.
References failed(), mlir::MemRefType::getShape(), and getStridesAndOffset().
Referenced by canFoldIntoConsumerOp(), foldMemRefCast(), mlir::DmaWaitOp::getNumElements(), and verifyNamedStructuredOp().
canFoldIntoConsumerOp() [2/2]
bool mlir::canFoldIntoConsumerOp (TensorCastOp castOp)
Counterpart of canFoldIntoConsumerOp(MemRefCastOp castOp) for tensors.
Determines whether TensorCastOp casts to a more dynamic version of the source tensor. This is useful to fold a tensor_cast into a consuming op and implement canonicalization patterns for ops in different dialects that may consume the results of tensor_cast operations. Such foldable tensor_cast operations are typically inserted as subtensor ops and are canonicalized, to preserve the type compatibility of their uses.
Returns true when all conditions are met:
source and result are ranked tensors with same element type and rank.
the tensor type has more static information than the result
Example:
%1 = tensor_cast %0 : tensor<8x16xf32> to tensor<?x?xf32>
%2 = consumer %1 ... : tensor<?x?xf32> ...
folds into:
%2 = consumer %0 ... : tensor<8x16xf32> ...
Definition at line 3544 of file Ops.cpp.
References canFoldIntoConsumerOp(), mlir::OpBuilder::create(), extractFromI64ArrayAttr(), failure(), mlir::RankedTensorType::getShape(), mlir::OwningRewritePatternList::insert(), mlir::ShapedType::isDynamic(), m_ConstantIndex(), matchPattern(), mlir::PatternRewriter::replaceOpWithNewOp(), and success().
canFuseLoops()
FusionResult mlir::canFuseLoops (AffineForOp srcForOp, AffineForOp dstForOp, unsigned dstLoopDepth, ComputationSliceState * srcSlice, FusionStrategy fusionStrategy = { FusionStrategy::Generic, Value()})
Checks the feasibility of fusing the loop nest rooted at 'srcForOp' into the loop nest rooted at 'dstForOp' at 'dstLoopDepth'.
Returns FusionResult 'Success' if fusion of the src/dst loop nests is feasible (i.e. they are in the same block and dependences would not be violated). Otherwise returns a FusionResult explaining why fusion is not feasible. NOTE: This function is not feature complete and should only be used in testing. TODO: Update comments when this function is fully implemented.
Definition at line 263 of file LoopFusionUtils.cpp.
References computeSliceUnion(), mlir::FusionResult::FailBlockDependence, failed(), mlir::FusionResult::FailFusionDependence, mlir::FusionResult::FailPrecondition, gatherLoadsAndStores(), mlir::FusionStrategy::Generic, getFusedLoopNestInsertionPoint(), getMaxLoopDepth(), getNumCommonSurroundingLoops(), mlir::FusionStrategy::memref, mlir::FusionStrategy::ProducerConsumer, mlir::FusionStrategy::Sibling, mlir::FusionStrategy::strategy, and mlir::FusionResult::Success.
Referenced by mlir::FusionStrategy::FusionStrategy(), and isFusionProfitable().
canonicalizeMapAndOperands()
void mlir::canonicalizeMapAndOperands (AffineMap * map, SmallVectorImpl< Value > * operands)
Modifies both map and operands in-place so as to:
drop duplicate operands
drop unused dims and symbols from map
promote valid symbols to symbolic operands in case they appeared as dimensional operands
propagate constant operands and drop them
Definition at line 980 of file AffineOps.cpp.
Referenced by mlir::FlatAffineConstraints::addLowerOrUpperBound(), applyMapToValues(), augmentMapAndBounds(), canonicalizeLoopBounds(), composeAffineMapAndOperands(), createCanonicalizedAffineForOp(), createFoldedComposedAffineApply(), mlir::AffineValueMap::difference(), fuseLoops(), generatePointWiseCopy(), mlir::MemRefAccess::getAccessMap(), getCleanupLoopLowerBound(), mlir::AffineDmaWaitOp::getTagMapAttrName(), makeCanonicalAffineApplies(), mlir::linalg::AffineMinSCFCanonicalizationPattern::matchAndRewrite(), replaceAllMemRefUsesWith(), and substitute().
canonicalizeSetAndOperands()
void mlir::canonicalizeSetAndOperands (IntegerSet * set, SmallVectorImpl< Value > * operands)
Canonicalizes an integer set the same way canonicalizeMapAndOperands does for affine maps.
Definition at line 985 of file AffineOps.cpp.
References composeAffineMapAndOperands(), failure(), mlir::OwningRewritePatternList::insert(), mlir::PatternRewriter::replaceOpWithNewOp(), and success().
Referenced by createSeparationCondition(), mlir::AffineDmaWaitOp::getTagMapAttrName(), and print().
canonicalizeStridedLayout()
MemRefType mlir::canonicalizeStridedLayout (MemRefType t)
Return a version of t with identity layout if it can be determined statically that the layout is the canonical contiguous strided layout.
Otherwise pass t's layout into simplifyAffineMap and return a copy of t with simplified layout.
Otherwise pass t's layout into simplifyAffineMap and return a copy of t with simplified layout. If t has multiple layout maps or a multi-result layout, just return t.
Definition at line 764 of file BuiltinTypes.cpp.
References mlir::AffineMap::get(), mlir::MemRefType::getAffineMaps(), mlir::MemRefType::getShape(), makeCanonicalStridedLayoutExpr(), mlir::MemRefType::Builder::setAffineMaps(), and simplifyAffineExpr().
Referenced by mlir::TensorType::classof(), computeReshapeCollapsedType(), and verify().
ceil()
int64_t mlir::ceil (Fraction f) inline
Definition at line 57 of file Fraction.h.
References ceilDiv(), mlir::Fraction::den, and mlir::Fraction::num.
Referenced by mlir::Simplex::computeIntegerBounds(), and signedCeilNonnegInputs().
ceilDiv()
int64_t mlir::ceilDiv (int64_t lhs, int64_t rhs) inline
Returns the result of MLIR's ceildiv operation on constants.
The RHS is expected to be non-zero.
Definition at line 23 of file MathExtras.h.
Referenced by buildTripCountMapAndOperands(), ceil(), mlir::UnrankedMemRefDescriptor::computeSizes(), computeStrides(), mlir::FlatAffineConstraints::getConstantBoundOnDimSize(), loopUnrollByFactor(), normalizeAffineFor(), mlir::AffineExpr::operator!(), parseForOp(), processParallelLoop(), promoteIfSingleIteration(), and setInterTileBoundsParametric().
checkMemrefAccessDependence()
DependenceResult mlir::checkMemrefAccessDependence (const MemRefAccess & srcAccess, const MemRefAccess & dstAccess, unsigned loopDepth, FlatAffineConstraints * dependenceConstraints, SmallVector< DependenceComponent, 2 > * dependenceComponents, bool allowRAR = false)
Definition at line 859 of file AffineAnalysis.cpp.
References addDomainConstraints(), addMemRefAccessConstraints(), addOrderingConstraints(), buildDimAndSymbolPositionMaps(), computeDirectionVector(), mlir::Operation::dump(), mlir::FlatAffineConstraints::dump(), failed(), mlir::DependenceResult::Failure, mlir::MemRefAccess::getAccessMap(), getNumCommonLoops(), mlir::FlatAffineConstraints::getNumDimIds(), getOpIndexSet(), mlir::DependenceResult::HasDependence, initDependenceConstraints(), mlir::FlatAffineConstraints::isEmpty(), mlir::MemRefAccess::memref, mlir::DependenceResult::NoDependence, mlir::MemRefAccess::opInst, and srcAppearsBeforeDstInAncestralBlock().
Referenced by checkTilingLegalityImpl(), computeSliceUnion(), createMemRefDataFlowOptPass(), mlir::DependenceResult::DependenceResult(), getDependenceComponents(), getMaxLoopDepth(), and isLoopParallel().
cloneWithNewYields()
scf::ForOp mlir::cloneWithNewYields (OpBuilder & b, scf::ForOp loop, ValueRange newIterOperands, ValueRange newYieldedValues, bool replaceLoopResults = true)
Create a clone of loop with newIterOperands added as new initialization values and newYieldedValues added as new yielded values.
The returned ForOp has newYieldedValues.size() new result values. The loop induction variable and newIterOperands are remapped to the new induction variable and the new entry block arguments respectively.
Additionally, if replaceLoopResults is true, all uses of loop.getResults() are replaced with the first loop.getNumResults() return values respectively. This additional replacement is provided as a convenience to update the consumers of loop, in the case e.g. when loop is soon to be deleted.
Return the cloned loop.
This convenience function is useful to factorize common mechanisms related to hoisting roundtrips to memory into yields. It does not perform any legality checks.
Prerequisite: newYieldedValues.size() == newYieldedValues.size().
Definition at line 25 of file Utils.cpp.
References mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::BlockAndValueMapping::map(), mlir::Operation::replaceAllUsesWith(), mlir::OpBuilder::setInsertionPoint(), and mlir::OpBuilder::setInsertionPointToStart().
Referenced by mlir::linalg::hoistRedundantVectorTransfers().
coalesceLoops()
void mlir::coalesceLoops (MutableArrayRef< scf::ForOp > loops)
Replace a perfect nest of "for" loops with a single linearized loop.
Assumes loops contains a list of perfectly nested loops with bounds and steps independent of any loop induction variable involved in the nest.
Definition at line 1975 of file LoopUtils.cpp.
References mlir::OpBuilder::create(), normalizeLoop(), replaceAllUsesInRegionWith(), and mlir::OpBuilder::setInsertionPointToStart().
collapseParallelLoops()
void mlir::collapseParallelLoops (scf::ParallelOp loops, ArrayRef< std::vector< unsigned >> combinedDimensions)
Take the ParallelLoop and for each set of dimension indices, combine them into a single dimension.
combinedDimensions must contain each index into loops exactly once.
Definition at line 2030 of file LoopUtils.cpp.
References mlir::OpBuilder::atBlockBegin(), mlir::OpBuilder::create(), normalizeLoop(), and replaceAllUsesInRegionWith().
compare()
int mlir::compare (Fraction x, Fraction y) inline
Three-way comparison between two fractions.
Returns +1, 0, and -1 if the first fraction is greater than, equal to, or less than the second fraction, respectively.
Definition at line 46 of file Fraction.h.
References mlir::Fraction::den, and mlir::Fraction::num.
Referenced by operator<(), operator<=(), operator==(), operator>(), and operator>=().
computeElementOffsetsFromVectorSliceOffsets()
SmallVector< int64_t, 4 > mlir::computeElementOffsetsFromVectorSliceOffsets (ArrayRef< int64_t > sizes, ArrayRef< int64_t > vectorOffsets)
Given the target sizes of a vector, together with vector-space offsets, returns the element-space offsets for each dimension.
Definition at line 93 of file VectorUtils.cpp.
Referenced by generateExtractSlicesOpResultType(), generateTransferOpSlices(), isValidExtractOrInsertSlicesType(), unrollSingleResultStructuredOp(), and mlir::vector::unrollSingleResultVectorOp().
computeMaxLinearIndex()
int64_t mlir::computeMaxLinearIndex (ArrayRef< int64_t > basis)
Return the number of elements of basis, 0 if empty.
Definition at line 33 of file VectorUtils.cpp.
Referenced by applyMapToValues(), generateExtractSlicesOpResultType(), initUnrolledVectorState(), and unrollSingleResultStructuredOp().
computeRankReductionMask()
llvm::Optional< SmallVector< bool, 4 > > mlir::computeRankReductionMask (ArrayRef< int64_t > originalShape, ArrayRef< int64_t > reducedShape)
Given an originalShape and a reducedShape assumed to be a subset of originalShape with some 1 entries erased, return the vector of booleans that specifies which of the entries of originalShape are keep to obtain reducedShape.
The returned mask can be applied as a projection to originalShape to obtain the reducedShape. This mask is useful to track which dimensions must be kept when e.g. compute MemRef strides under rank-reducing operations. Return None if reducedShape cannot be obtained by dropping only 1 entries in originalShape.
Definition at line 3148 of file Ops.cpp.
Referenced by mlir::DmaWaitOp::getNumElements(), isRankReducedType(), and mlir::LLVM::detail::vectorOneToOneRewrite().
computeSliceSizes()
SmallVector< int64_t, 4 > mlir::computeSliceSizes (ArrayRef< int64_t > shape, ArrayRef< int64_t > sizes, ArrayRef< int64_t > elementOffsets)
Given the shape, sizes, and element-space offsets of a vector, returns the slize sizes for each dimension.
Definition at line 102 of file VectorUtils.cpp.
Referenced by generateExtractSlicesOpResultType(), isValidExtractOrInsertSlicesType(), and mlir::vector::unrollSingleResultVectorOp().
computeSliceUnion()
LogicalResult mlir::computeSliceUnion (ArrayRef< Operation *> opsA, ArrayRef< Operation *> opsB, unsigned loopDepth, unsigned numCommonLoops, bool isBackwardSlice, ComputationSliceState * sliceUnion)
Computes in 'sliceUnion' the union of all slice bounds computed at 'loopDepth' between all dependent pairs of ops in 'opsA' and 'opsB'.
The parameter 'numCommonLoops' is the number of loops common to the operations in 'opsA' and 'opsB'. If 'isBackwardSlice' is true, computes slice bounds for loop nest surrounding ops in 'opsA', as a function of IVs and symbols of loop nest surrounding ops in 'opsB' at 'loopDepth'. If 'isBackwardSlice' is false, computes slice bounds for loop nest surrounding ops in 'opsB', as a function of IVs and symbols of loop nest surrounding ops in 'opsA' at 'loopDepth'. Returns 'success' if union was computed, 'failure' otherwise.
Returns 'Success' if union was computed, 'failure' otherwise.
Definition at line 598 of file Utils.cpp.
References addMissingLoopIVBounds(), mlir::FlatAffineConstraints::areIdsAlignedWithOther(), checkMemrefAccessDependence(), mlir::ComputationSliceState::clearBounds(), mlir::FlatAffineConstraints::convertLoopIVSymbolsToDims(), failed(), failure(), mlir::DependenceResult::Failure, mlir::ComputationSliceState::getAsConstraints(), getComputationSliceState(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getIdValues(), getInnermostCommonLoopDepth(), getNestingDepth(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), mlir::FlatAffineConstraints::getNumDimIds(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::ComputationSliceState::insertPoint, mlir::ComputationSliceState::ivs, mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, mlir::MemRefAccess::memref, mlir::FlatAffineConstraints::mergeAndAlignIdsWithOther(), mlir::DependenceResult::NoDependence, mlir::MemRefAccess::opInst, success(), mlir::ComputationSliceState::ubOperands, mlir::ComputationSliceState::ubs, mlir::FlatAffineConstraints::unionBoundingBox(), and mlir::DependenceResult::value.
Referenced by canFuseLoops(), and mlir::ComputationSliceState::isEmpty().
computeStrides() [1/2]
SmallVector< int64_t, 8 > mlir::computeStrides (ArrayRef< int64_t > shape)
Given a shape with sizes greater than 0 along all dimensions, return the distance, in number of elements, between a slice in a dimension and the next slice in the same dimension.
e.g. shape[3, 4, 5] -> linearization_basis[20, 5, 1]
Definition at line 44 of file VectorUtils.cpp.
Referenced by applyMapToValues(), generateExtractSlicesOpResultType(), generateTransferOpSlices(), initUnrolledVectorState(), isValidExtractOrInsertSlicesType(), unrollSingleResultStructuredOp(), and mlir::vector::unrollSingleResultVectorOp().
computeStrides() [2/2]
SmallVector< int64_t, 4 > mlir::computeStrides (ArrayRef< int64_t > shape, ArrayRef< int64_t > sizes)
Given the shape and sizes of a vector, returns the corresponding strides for each dimension.
TODO: needs better doc of how it is used.
Definition at line 58 of file VectorUtils.cpp.
References ceilDiv().
concatAffineMaps()
AffineMap mlir::concatAffineMaps (ArrayRef< AffineMap > maps)
Concatenates a list of maps into a single AffineMap, stepping over potentially empty maps.
Assumes each of the underlying map has 0 symbols. The resulting map has a number of dims equal to the max of maps' dims and the concatenated results as its results. Returns an empty map if all input maps are empty.
Example: When applied to the following list of 3 affine maps,
{
  (i, j, k) -> (i, k),
  (i, j, k) -> (k, j),
  (i, j, k) -> (i, j)
}
Returns the map:
(i, j, k) -> (i, k, k, j, i, j)
Definition at line 441 of file AffineMap.cpp.
References mlir::AffineMap::get().
Referenced by fuseWithReshapeByExpansion(), mlir::MutableAffineMap::getContext(), replaceBlockArgForUnitDimLoops< IndexedGenericOp >(), replaceUnitDims(), and replaceUnitExtents().
configureGpuToNVVMConversionLegality()
void mlir::configureGpuToNVVMConversionLegality (ConversionTarget & target)
Configure target to convert from the GPU dialect to NVVM.
Definition at line 144 of file LowerGpuOpsToNVVMOps.cpp.
References mlir::ConversionTarget::addIllegalDialect(), mlir::ConversionTarget::addIllegalOp(), mlir::ConversionTarget::addLegalDialect(), and mlir::ConversionTarget::addLegalOp().
configureGpuToROCDLConversionLegality()
void mlir::configureGpuToROCDLConversionLegality (ConversionTarget & target)
Configure target to convert from the GPU dialect to ROCDL.
Definition at line 80 of file LowerGpuOpsToROCDLOps.cpp.
References mlir::ConversionTarget::addIllegalDialect(), mlir::ConversionTarget::addIllegalOp(), mlir::ConversionTarget::addLegalDialect(), and mlir::ConversionTarget::addLegalOp().
configureParallelLoopToGPULegality()
void mlir::configureParallelLoopToGPULegality (ConversionTarget & target)
Configures the rewrite target such that only scf.parallel operations that are not rewritten by the provided patterns are legal.
Definition at line 649 of file SCFToGPU.cpp.
References mlir::ConversionTarget::addDynamicallyLegalOp(), and mlir::gpu::getMappingAttrName().
constFoldBinaryOp()
template<class AttrElementT , class ElementValueT = typename AttrElementT::ValueType, class CalculationT = function_ref<ElementValueT(ElementValueT, ElementValueT)>> Attribute mlir::constFoldBinaryOp (ArrayRef< Attribute > operands, const CalculationT & calculate)
Performs constant folding calculate with element-wise behavior on the two attributes in operands and returns the result if possible.
Definition at line 30 of file CommonFolders.h.
References mlir::DenseElementsAttr::get(), mlir::DenseElementsAttr::getSplatValue(), and mlir::ElementsAttr::getValues().
convertAffineLoopNestToGPULaunch()
LogicalResult mlir::convertAffineLoopNestToGPULaunch (AffineForOp forOp, unsigned numBlockDims, unsigned numThreadDims)
Convert a perfect affine loop nest with the outermost loop identified by forOp into a gpu::Launch operation.
Map numBlockDims outer loops to GPU blocks and numThreadDims to GPU threads. The bounds of the loops that are mapped should be independent of the induction variables of the other mapped loops.
No check on the size of the block or grid, or on the validity of parallelization is performed, it is under the responsibility of the caller to strip-mine the loops and to perform the dependence analysis before calling the conversion.
Definition at line 279 of file SCFToGPU.cpp.
References convertAffineLoopNestToGPULaunch().
createAffineComputationSlice()
void mlir::createAffineComputationSlice (Operation * opInst, SmallVectorImpl< AffineApplyOp > * sliceOps)
Given an operation, inserts one or more single result affine apply operations, results of which are exclusively used by this operation.
Given an operation, inserts one or more single result affine apply operations, results of which are exclusively used by this operation operation.
The operands of these newly created affine apply ops are guaranteed to be loop iterators or terminal symbols of a function.
Before
affine.for i = 0 to #map(N) idx = affine.apply (d0) -> (d0 mod 2) (i) send A[idx], ... v = "compute"(idx, ...)
After
affine.for i = 0 to #map(N) idx = affine.apply (d0) -> (d0 mod 2) (i) send A[idx], ... idx_ = affine.apply (d0) -> (d0 mod 2) (i) v = "compute"(idx_, ...) This allows the application of different transformations on send and compute (for eg. different shifts/delays)
Fills sliceOps with the list of affine.apply operations. In the following cases, sliceOps remains empty:
If none of opInst's operands were the result of an affine.apply (i.e., there was no affine computation slice to create).
If all the affine.apply op's supplying operands to this opInst did not have any uses other than those in this opInst.
The operands of these newly created affine apply ops are guaranteed to be loop iterators or terminal symbols of a function.
Before
affine.for i = 0 to #map(N) idx = affine.apply (d0) -> (d0 mod 2) (i) "send"(idx, A, ...) "compute"(idx)
After
affine.for i = 0 to #map(N) idx = affine.apply (d0) -> (d0 mod 2) (i) "send"(idx, A, ...) idx_ = affine.apply (d0) -> (d0 mod 2) (i) "compute"(idx_)
This allows applying different transformations on send and compute (for eg. different shifts/delays).
Returns nullptr either if none of opInst's operands were the result of an affine.apply and thus there was no affine computation slice to create, or if all the affine.apply op's supplying operands to this opInst did not have any uses besides this opInst; otherwise returns the list of affine.apply operations created in output argument sliceOps.
Definition at line 328 of file Utils.cpp.
References mlir::OpBuilder::create(), fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::Operation::getLoc(), mlir::Builder::getMultiDimIdentityMap(), mlir::Operation::getNumOperands(), mlir::Operation::getOperands(), getReachableAffineApplyOps(), and mlir::Operation::setOperand().
Referenced by findMatchingStartFinishInsts().
createAffineDataCopyGenerationPass() [1/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createAffineDataCopyGenerationPass (unsigned slowMemorySpace, unsigned fastMemorySpace, unsigned tagMemorySpace = 0, int minDmaTransferSize = 1024, uint64_t fastMemCapacityBytes = std::numeric_limits<uint64_t>::max())
Performs packing (or explicit copying) of accessed memref regions into buffers in the specified faster memory space through either pointwise copies or DMA operations.
Generates copies for memref's living in 'slowMemorySpace' into newly created buffers in 'fastMemorySpace', and replaces memory operations to the former by the latter.
Only load op's handled for now. TODO: extend this to store op's.
Definition at line 79 of file AffineDataCopyGeneration.cpp.
createAffineDataCopyGenerationPass() [2/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createAffineDataCopyGenerationPass ()
Overload relying on pass options for initialization.
Definition at line 87 of file AffineDataCopyGeneration.cpp.
References affineDataCopyGenerate(), applyOpPatternsAndFold(), mlir::Block::begin(), mlir::OpBuilder::create(), mlir::Block::empty(), mlir::Block::end(), getMemoryFootprintBytes(), promoteIfSingleIteration(), and success().
createAffineForToGPUPass() [1/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createAffineForToGPUPass (unsigned numBlockDims, unsigned numThreadDims)
Create a pass that converts loop nests into GPU kernels.
It considers top-level affine.for operations as roots of loop nests and converts them to the gpu.launch operations if possible.
No check on the size of the block or grid, or on the validity of parallelization is performed, it is under the responsibility of the caller to strip-mine the loops and to perform the dependence analysis before calling the conversion.
Definition at line 66 of file SCFToGPUPass.cpp.
createAffineForToGPUPass() [2/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createAffineForToGPUPass ()
Definition at line 69 of file SCFToGPUPass.cpp.
createAffineLoopInvariantCodeMotionPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createAffineLoopInvariantCodeMotionPass ()
Creates a loop invariant code motion pass that hoists loop invariant operations out of affine loops.
Definition at line 233 of file AffineLoopInvariantCodeMotion.cpp.
createAffineLoopNormalizePass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createAffineLoopNormalizePass ()
Apply normalization transformations to affine loop-like ops.
Definition at line 202 of file AffineLoopNormalize.cpp.
createAffineParallelizePass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createAffineParallelizePass ()
Creates a pass to convert all parallel affine.for's into 1-d affine.parallel ops.
Definition at line 63 of file AffineParallelize.cpp.
createAsyncParallelForPass() [1/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createAsyncParallelForPass ()
Definition at line 280 of file AsyncParallelFor.cpp.
createAsyncParallelForPass() [2/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createAsyncParallelForPass (int numWorkerThreads)
Definition at line 285 of file AsyncParallelFor.cpp.
createAsyncRefCountingOptimizationPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createAsyncRefCountingOptimizationPass ()
Definition at line 216 of file AsyncRefCountingOptimization.cpp.
createAsyncRefCountingPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createAsyncRefCountingPass ()
Definition at line 322 of file AsyncRefCounting.cpp.
createBufferDeallocationPass()
std::unique_ptr< Pass > mlir::createBufferDeallocationPass ()
Creates an instance of the BufferDeallocation pass to free all allocated buffers.
Definition at line 528 of file BufferDeallocation.cpp.
createBufferHoistingPass()
std::unique_ptr< Pass > mlir::createBufferHoistingPass ()
Creates a pass that moves allocations upwards to reduce the number of required copies that are inserted during the BufferDeallocation pass.
Definition at line 383 of file BufferOptimizations.cpp.
createBufferLoopHoistingPass()
std::unique_ptr< Pass > mlir::createBufferLoopHoistingPass ()
Creates a pass that moves allocations upwards out of loops.
This avoids reallocations inside of loops.
Definition at line 387 of file BufferOptimizations.cpp.
createBufferResultsToOutParamsPass()
std::unique_ptr< Pass > mlir::createBufferResultsToOutParamsPass ()
Creates a pass that converts memref function results to out-params.
Definition at line 141 of file BufferResultsToOutParams.cpp.
createCanonicalizedAffineForOp()
AffineForOp mlir::createCanonicalizedAffineForOp (OpBuilder b, Location loc, ValueRange lbOperands, AffineMap lbMap, ValueRange ubOperands, AffineMap ubMap, int64_t step = 1)
Creates an AffineForOp while ensuring that the lower and upper bounds are canonicalized, i.e., unused and duplicate operands are removed, any constant operands propagated/folded in, and duplicate bound maps dropped.
Definition at line 2907 of file LoopUtils.cpp.
References canonicalizeMapAndOperands(), mlir::OpBuilder::create(), fullyComposeAffineMapAndOperands(), and removeDuplicateExprs().
Referenced by createFullTiles(), and generatePointWiseCopy().
createCanonicalizerPass()
std::unique_ptr< Pass > mlir::createCanonicalizerPass ()
Creates an instance of the Canonicalizer pass.
Create a Canonicalizer pass.
Definition at line 41 of file Canonicalizer.cpp.
Referenced by defaultInlinerOptPipeline().
createComposedAffineApplyOp()
Operation* mlir::createComposedAffineApplyOp (OpBuilder & builder, Location loc, ArrayRef< Value > operands, ArrayRef< Operation *> affineApplyOps, SmallVectorImpl< Value > * results)
Creates and inserts into 'builder' a new AffineApplyOp, with the number of its results equal to the number of operands, as a composition of all other AffineApplyOps reachable from input parameter 'operands'.
If different operands were drawing results from multiple affine apply ops, these will also be collected into a single (multi-result) affine apply op. The final results of the composed AffineApplyOp are returned in output parameter 'results'. Returns the affine apply op created.
createConvertAsyncToLLVMPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertAsyncToLLVMPass ()
Create a pass to convert Async operations to the LLVM dialect.
Definition at line 883 of file AsyncToLLVM.cpp.
createConvertElementwiseToLinalgPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createConvertElementwiseToLinalgPass ()
Definition at line 96 of file ElementwiseToLinalg.cpp.
createConvertGPUKernelToBlobPass()
std::unique_ptr< OperationPass< gpu::GPUModuleOp > > mlir::createConvertGPUKernelToBlobPass (LoweringCallback loweringCallback, BlobGenerator blobGenerator, StringRef triple, StringRef targetChip, StringRef features, StringRef gpuBinaryAnnotation)
Creates a pass to convert kernel functions into GPU target object blobs.
This transformation takes the body of each function that is annotated with the 'gpu.kernel' attribute, copies it to a new LLVM module, compiles the module with help of the GPU backend to target object and then invokes the provided blobGenerator to produce a binary blob. Such blob is then attached as a string attribute to the kernel function.
Following callbacks are to be provided by user:
loweringCallback : lower the module to an LLVM module.
blobGenerator : build a blob executable on target GPU.
Information wrt LLVM backend are to be supplied by user:
triple : target triple to be used.
targetChip : mcpu to be used.
features : target-specific features to be used.
Information about result attribute is to be specified by user:
gpuBinaryAnnotation : the name of the attribute which contains the blob.
After the transformation, the body of the kernel function is removed (i.e., it is turned into a declaration).
Definition at line 155 of file ConvertKernelFuncToBlob.cpp.
createConvertGpuLaunchFuncToVulkanLaunchFuncPass()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > mlir::createConvertGpuLaunchFuncToVulkanLaunchFuncPass ()
Definition at line 191 of file ConvertGPULaunchFuncToVulkanLaunchFunc.cpp.
createConvertGPUToSPIRVPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertGPUToSPIRVPass ()
Pass to convert GPU Ops to SPIR-V ops.
For a gpu.func to be converted, it should have a spv.entry_point_abi attribute.
Definition at line 71 of file ConvertGPUToSPIRVPass.cpp.
createConvertLinalgToAffineLoopsPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createConvertLinalgToAffineLoopsPass ()
Create a pass to convert Linalg operations to affine.for loops and affine_load/affine_store accesses.
Placeholder for now, this is NYI.
Definition at line 651 of file Loops.cpp.
createConvertLinalgToLLVMPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertLinalgToLLVMPass ()
Create a pass to convert Linalg operations to the LLVMIR dialect.
Definition at line 331 of file LinalgToLLVM.cpp.
createConvertLinalgToLoopsPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createConvertLinalgToLoopsPass ()
Create a pass to convert Linalg operations to scf.for loops and std.load/std.store accesses.
Definition at line 641 of file Loops.cpp.
createConvertLinalgToParallelLoopsPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createConvertLinalgToParallelLoopsPass ()
Create a pass to convert Linalg operations to scf.parallel loops and std.load/std.store accesses.
Definition at line 646 of file Loops.cpp.
createConvertLinalgToStandardPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertLinalgToStandardPass ()
Create a pass to convert Linalg operations to the Standard dialect.
Definition at line 220 of file LinalgToStandard.cpp.
createConvertOpenMPToLLVMPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertOpenMPToLLVMPass ()
Create a pass to convert OpenMP operations to the LLVMIR dialect.
Definition at line 75 of file OpenMPToLLVM.cpp.
createConvertSCFToOpenMPPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createConvertSCFToOpenMPPass ()
Definition at line 111 of file SCFToOpenMP.cpp.
createConvertShapeConstraintsPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createConvertShapeConstraintsPass ()
Definition at line 135 of file ConvertShapeConstraints.cpp.
createConvertShapeToStandardPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertShapeToStandardPass ()
Definition at line 625 of file ShapeToStandard.cpp.
createConvertSPIRVToLLVMPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertSPIRVToLLVMPass ()
Creates a pass to convert SPIR-V operations to the LLVMIR dialect.
Definition at line 59 of file ConvertSPIRVToLLVMPass.cpp.
createConvertStandardToSPIRVPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertStandardToSPIRVPass ()
Pass to convert StandardOps to SPIR-V ops.
Definition at line 48 of file ConvertStandardToSPIRVPass.cpp.
createConvertVectorToLLVMPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertVectorToLLVMPass (const LowerVectorToLLVMOptions & options = LowerVectorToLLVMOptions())
Create a pass to convert vector operations to the LLVMIR dialect.
Definition at line 99 of file ConvertVectorToLLVMPass.cpp.
References options.
createConvertVectorToROCDLPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertVectorToROCDLPass ()
Create a pass to convert vector operations to the ROCDL dialect.
Definition at line 179 of file VectorToROCDL.cpp.
createConvertVectorToSCFPass()
std::unique_ptr< Pass > mlir::createConvertVectorToSCFPass (const VectorTransferToSCFOptions & options = VectorTransferToSCFOptions())
Create a pass to convert a subset of vector ops to SCF.
Definition at line 720 of file VectorToSCF.cpp.
References mlir::VectorTransferRewriter< TransferOpTy >::options.
createConvertVectorToSPIRVPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createConvertVectorToSPIRVPass ()
Pass to convert Vector Ops to SPIR-V ops.
Definition at line 155 of file VectorToSPIRV.cpp.
createConvertVulkanLaunchFuncToVulkanCallsPass()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > mlir::createConvertVulkanLaunchFuncToVulkanCallsPass ()
Definition at line 434 of file ConvertLaunchFuncToVulkanCalls.cpp.
createCopyRemovalPass()
std::unique_ptr< Pass > mlir::createCopyRemovalPass ()
Create a pass that removes unnecessary Copy operations.
Definition at line 215 of file CopyRemoval.cpp.
createCSEPass()
std::unique_ptr< Pass > mlir::createCSEPass ()
Creates a pass to perform common sub expression elimination.
Definition at line 236 of file CSE.cpp.
createFinalizingBufferizePass()
std::unique_ptr< FunctionPass > mlir::createFinalizingBufferizePass ()
Creates a pass that finalizes a partial bufferization by removing remaining tensor_load and tensor_to_memref operations.
Definition at line 126 of file Bufferize.cpp.
createFoldReshapeOpsByLinearizationPass()
std::unique_ptr< Pass > mlir::createFoldReshapeOpsByLinearizationPass ()
Definition at line 1034 of file FusionOnTensors.cpp.
createForLoopSpecializationPass()
std::unique_ptr< Pass > mlir::createForLoopSpecializationPass ()
Creates a pass that specializes for loop for unrolling and vectorization.
Definition at line 113 of file LoopSpecialization.cpp.
createFuncBufferizePass()
std::unique_ptr< Pass > mlir::createFuncBufferizePass ()
Creates an instance of func bufferization pass.
Definition at line 84 of file FuncBufferize.cpp.
createGpuAsyncRegionPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createGpuAsyncRegionPass ()
Rewrites a function region so that GPU ops execute asynchronously.
Definition at line 273 of file AsyncRegionRewriter.cpp.
createGpuKernelOutliningPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createGpuKernelOutliningPass ()
Replaces gpu.launch with gpu.launch_func by moving the region into a separate kernel function.
Definition at line 317 of file KernelOutlining.cpp.
createGpuToLLVMConversionPass()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > mlir::createGpuToLLVMConversionPass (StringRef gpuBinaryAnnotation = "")
Creates a pass to convert a gpu.launch_func operation into a sequence of GPU runtime calls.
This pass does not generate code to call GPU runtime APIs directly but instead uses a small wrapper library that exports a stable and conveniently typed ABI on top of GPU runtimes such as CUDA or ROCm (HIP).
Definition at line 647 of file ConvertLaunchFuncToRuntimeCalls.cpp.
createInlinerPass() [1/3]
std::unique_ptr< Pass > mlir::createInlinerPass ()
Creates a pass which inlines calls and callable operations as defined by the CallGraph.
Definition at line 782 of file Inliner.cpp.
createInlinerPass() [2/3]
std::unique_ptr< Pass > mlir::createInlinerPass (llvm::StringMap< OpPassManager > opPipelines)
Creates an instance of the inliner pass, and use the provided pass managers when optimizing callable operations with names matching the key type.
Callable operations with a name not within the provided map will use the default inliner pipeline during optimization.
Definition at line 786 of file Inliner.cpp.
References defaultInlinerOptPipeline().
createInlinerPass() [3/3]
std::unique_ptr<Pass> mlir::createInlinerPass (llvm::StringMap< OpPassManager > opPipelines, std::function< void(OpPassManager &)> defaultPipelineBuilder)
Creates an instance of the inliner pass, and use the provided pass managers when optimizing callable operations with names matching the key type.
Callable operations with a name not within the provided map will use the provided default pipeline builder.
Definition at line 791 of file Inliner.cpp.
createLegalizeStdOpsForSPIRVLoweringPass()
std::unique_ptr< Pass > mlir::createLegalizeStdOpsForSPIRVLoweringPass ()
Pass to legalize ops that are not directly lowered to SPIR-V.
Definition at line 209 of file LegalizeStandardForSPIRV.cpp.
createLinalgBufferizePass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLinalgBufferizePass ()
Create a pass to convert Linalg operations which work on tensors to use buffers instead.
Definition at line 348 of file Bufferize.cpp.
createLinalgFoldUnitExtentDimsPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLinalgFoldUnitExtentDimsPass ()
Definition at line 524 of file DropUnitDims.cpp.
createLinalgFusionOfTensorOpsPass()
std::unique_ptr< Pass > mlir::createLinalgFusionOfTensorOpsPass ()
Definition at line 1030 of file FusionOnTensors.cpp.
createLinalgGeneralizationPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLinalgGeneralizationPass ()
Create a pass to conver named Linalg operations to Linalg generic operations.
Definition at line 178 of file Generalization.cpp.
createLinalgPromotionPass() [1/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createLinalgPromotionPass (bool dynamicBuffers, bool useAlloca)
Definition at line 422 of file Promotion.cpp.
createLinalgPromotionPass() [2/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createLinalgPromotionPass ()
Definition at line 425 of file Promotion.cpp.
createLinalgTilingPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLinalgTilingPass (ArrayRef< int64_t > tileSizes = {})
Definition at line 634 of file Tiling.cpp.
createLinalgTilingToParallelLoopsPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLinalgTilingToParallelLoopsPass (ArrayRef< int64_t > tileSizes = {})
Definition at line 639 of file Tiling.cpp.
createLinalgToSPIRVPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createLinalgToSPIRVPass ()
Creates and returns a pass to convert Linalg ops to SPIR-V ops.
Definition at line 48 of file LinalgToSPIRVPass.cpp.
createLocationSnapshotPass() [1/2]
std::unique_ptr< Pass > mlir::createLocationSnapshotPass (OpPrintingFlags flags, StringRef fileName = "", StringRef tag = "")
Create a pass to generate new locations by snapshotting the IR to the given file, and using the printed locations within that file.
If filename is empty, a temporary file is generated instead. If a 'tag' is non-empty, the generated locations are represented as a NameLoc with the given tag as the name, and then fused with the existing locations. Otherwise, the existing locations are replaced.
Definition at line 146 of file LocationSnapshot.cpp.
createLocationSnapshotPass() [2/2]
std::unique_ptr< Pass > mlir::createLocationSnapshotPass ()
Overload utilizing pass options for initialization.
Definition at line 151 of file LocationSnapshot.cpp.
createLoopCoalescingPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLoopCoalescingPass ()
Creates a pass that transforms perfectly nested loops with independent bounds into a single loop.
Definition at line 88 of file LoopCoalescing.cpp.
createLoopFusionPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLoopFusionPass (unsigned fastMemorySpace = 0, uint64_t localBufSizeThreshold = 0, bool maximalFusion = false)
Creates a loop fusion pass which fuses loops.
Buffers of size less than or equal to localBufSizeThreshold are promoted to memory space `fastMemorySpace'.
Definition at line 65 of file LoopFusion.cpp.
createLoopInvariantCodeMotionPass()
std::unique_ptr< Pass > mlir::createLoopInvariantCodeMotionPass ()
Creates a loop invariant code motion pass that hoists loop invariant instructions out of the loop.
Definition at line 123 of file LoopInvariantCodeMotion.cpp.
Referenced by mlir::linalg::CodegenStrategy::transform().
createLoopTilingPass() [1/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createLoopTilingPass (uint64_t cacheSizeBytes)
Creates a pass to perform tiling on loop nests.
Creates a pass to perform loop tiling on all suitable loop nests of a Function.
Definition at line 57 of file LoopTiling.cpp.
createLoopTilingPass() [2/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createLoopTilingPass ()
Overload relying on pass options for initialization.
Definition at line 60 of file LoopTiling.cpp.
createLoopUnrollAndJamPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLoopUnrollAndJamPass (int unrollJamFactor = -1)
Creates a loop unroll jam pass to unroll jam by the specified factor.
A factor of -1 lets the pass use the default factor or the one on the command line if provided.
Definition at line 66 of file LoopUnrollAndJam.cpp.
References loopUnrollJamByFactor().
createLoopUnrollPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createLoopUnrollPass (int unrollFactor = -1, bool unrollUpToFactor = false, bool unrollFull = false, const std::function< unsigned(AffineForOp)> & getUnrollFactor = nullptr)
Creates a loop unrolling pass with the provided parameters.
'getUnrollFactor' is a function callback for clients to supply a function that computes an unroll factor - the callback takes precedence over unroll factors supplied through other means. If -1 is passed as the unrollFactor and no callback is provided, anything passed from the command-line (if at all) or the default unroll factor is used (LoopUnroll:kDefaultUnrollFactor).
Definition at line 135 of file LoopUnroll.cpp.
createLowerAffinePass()
std::unique_ptr< Pass > mlir::createLowerAffinePass ()
Lowers affine control flow operations (ForStmt, IfStmt and AffineApplyOp) to equivalent lower-level constructs (flow of basic blocks and arithmetic primitives).
Lowers If and For operations within a function into their lower level CFG equivalent blocks.
Definition at line 691 of file AffineToStandard.cpp.
createLowerGpuOpsToNVVMOpsPass()
std::unique_ptr< OperationPass< gpu::GPUModuleOp > > mlir::createLowerGpuOpsToNVVMOpsPass (unsigned indexBitwidth = kDeriveIndexBitwidthFromDataLayout)
Creates a pass that lowers GPU dialect operations to NVVM counterparts.
The index bitwidth used for the lowering of the device side index computations is configurable.
Definition at line 207 of file LowerGpuOpsToNVVMOps.cpp.
createLowerGpuOpsToROCDLOpsPass()
std::unique_ptr< OperationPass< gpu::GPUModuleOp > > mlir::createLowerGpuOpsToROCDLOpsPass (unsigned indexBitwidth = kDeriveIndexBitwidthFromDataLayout)
Creates a pass that lowers GPU dialect operations to ROCDL counterparts.
The index bitwidth used for the lowering of the device side index computations is configurable.
Definition at line 139 of file LowerGpuOpsToROCDLOps.cpp.
createLowerHostCodeToLLVMPass()
std::unique_ptr< mlir::OperationPass< mlir::ModuleOp > > mlir::createLowerHostCodeToLLVMPass ()
Creates a pass to emulate gpu.launch_func call in LLVM dialect and lower the host module code to LLVM.
This transformation creates a sequence of global variables that are later linked to the varables in the kernel module, and a series of copies to/from them to emulate the memory transfer from the host or to the device sides. It also converts the remaining Standard dialect into LLVM dialect, emitting C wrappers.
Definition at line 305 of file ConvertLaunchFuncToLLVMCalls.cpp.
createLowerToCFGPass()
std::unique_ptr< Pass > mlir::createLowerToCFGPass ()
Creates a pass to convert scf.for, scf.if and loop.terminator ops to CFG.
Definition at line 591 of file SCFToStandard.cpp.
createLowerToLLVMPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createLowerToLLVMPass (const LowerToLLVMOptions & options = LowerToLLVMOptions::getDefaultOptions())
Creates a pass to convert the Standard dialect into the LLVMIR dialect.
stdlib malloc/free is used by default for allocating memrefs allocated with std.alloc, while LLVM's alloca is used for those allocated with std.alloca.
Definition at line 4173 of file StandardToLLVM.cpp.
References mlir::LowerToLLVMOptions::dataLayout, mlir::LowerToLLVMOptions::emitCWrappers, mlir::LowerToLLVMOptions::indexBitwidth, mlir::LowerToLLVMOptions::useAlignedAlloc, and mlir::LowerToLLVMOptions::useBarePtrCallConv.
Referenced by mlir::LowerToLLVMOptions::getDefaultOptions().
createMemRefDataFlowOptPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createMemRefDataFlowOptPass ()
Creates a pass to perform optimizations relying on memref dataflow such as store to load forwarding, elimination of dead stores, and dead allocs.
Definition at line 81 of file MemRefDataFlowOpt.cpp.
References checkMemrefAccessDependence(), mlir::Operation::erase(), mlir::OpState::erase(), mlir::AffineReadOpInterface::getMemRef(), getNestingDepth(), getNumCommonSurroundingLoops(), mlir::Value::getUsers(), mlir::AffineReadOpInterface::getValue(), hasDependence(), and mlir::Value::replaceAllUsesWith().
createNormalizeMemRefsPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createNormalizeMemRefsPass ()
Creates an interprocedural pass to normalize memrefs to have a trivial (identity) layout map.
Definition at line 44 of file NormalizeMemRefs.cpp.
createParallelLoopCollapsingPass()
std::unique_ptr< Pass > mlir::createParallelLoopCollapsingPass ()
Creates a pass that transforms a single ParallelLoop over N induction variables into another ParallelLoop over less than N induction variables.
Definition at line 43 of file ParallelLoopCollapsing.cpp.
createParallelLoopFusionPass()
std::unique_ptr< Pass > mlir::createParallelLoopFusionPass ()
Creates a loop fusion pass which fuses parallel loops.
Definition at line 173 of file ParallelLoopFusion.cpp.
createParallelLoopSpecializationPass()
std::unique_ptr< Pass > mlir::createParallelLoopSpecializationPass ()
Creates a pass that specializes parallel loop for unrolling and vectorization.
Definition at line 109 of file LoopSpecialization.cpp.
createParallelLoopTilingPass()
std::unique_ptr< Pass > mlir::createParallelLoopTilingPass (llvm::ArrayRef< int64_t > tileSize = {})
Creates a pass which tiles innermost parallel loops.
Definition at line 173 of file ParallelLoopTiling.cpp.
createParallelLoopToGpuPass()
std::unique_ptr< Pass > mlir::createParallelLoopToGpuPass ()
Creates a pass that converts scf.parallel operations into a gpu.launch operation.
The mapping of loop dimensions to launch dimensions is derived from mapping attributes. See ParallelToGpuLaunchLowering::matchAndRewrite for a description of the used attributes.
Definition at line 73 of file SCFToGPUPass.cpp.
createPDLToPDLInterpPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createPDLToPDLInterpPass ()
Creates and returns a pass to convert PDL ops to PDL interpreter ops.
Definition at line 692 of file PDLToPDLInterp.cpp.
Referenced by convertPDLToPDLInterp().
createPipelineDataTransferPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createPipelineDataTransferPass ()
Creates a pass to pipeline explicit movement of data across levels of the memory hierarchy.
Definition at line 43 of file PipelineDataTransfer.cpp.
createPrintCFGGraphPass()
std::unique_ptr< mlir::OperationPass< mlir::FuncOp > > mlir::createPrintCFGGraphPass (raw_ostream & os = llvm::errs(), bool shortNames = false, const Twine & title = "")
Creates a pass to print CFG graphs.
Definition at line 79 of file ViewRegionGraph.cpp.
createPrintOpGraphPass()
std::unique_ptr< OperationPass< ModuleOp > > mlir::createPrintOpGraphPass (raw_ostream & os = llvm::errs(), bool shortNames = false, const Twine & title = "")
Creates a pass to print op graphs.
Definition at line 164 of file ViewOpGraph.cpp.
createPrintOpStatsPass()
std::unique_ptr< Pass > mlir::createPrintOpStatsPass ()
Creates a pass which prints the list of ops and the number of occurrences in the module.
Definition at line 83 of file OpStats.cpp.
createPromoteBuffersToStackPass()
std::unique_ptr< Pass > mlir::createPromoteBuffersToStackPass (unsigned maxAllocSizeInBytes = 1024, unsigned bitwidthOfIndexType = 64, unsigned maxRankOfAllocatedMemRef = 1)
Creates a pass that promotes heap-based allocations to stack-based ones.
Only buffers smaller than the provided size are promoted. Dynamic shaped buffers are promoted up to the given rank.
Definition at line 392 of file BufferOptimizations.cpp.
createRemoveShapeConstraintsPass()
std::unique_ptr< FunctionPass > mlir::createRemoveShapeConstraintsPass ()
Definition at line 63 of file RemoveShapeConstraints.cpp.
createSCCPPass()
std::unique_ptr< Pass > mlir::createSCCPPass ()
Creates a pass which performs sparse conditional constant propagation over nested operations.
Definition at line 929 of file SCCP.cpp.
createSCFBufferizePass()
std::unique_ptr< Pass > mlir::createSCFBufferizePass ()
Creates a pass that bufferizes the SCF dialect.
Definition at line 39 of file Bufferize.cpp.
createShapeBufferizePass()
std::unique_ptr< FunctionPass > mlir::createShapeBufferizePass ()
Definition at line 36 of file Bufferize.cpp.
createShapeToShapeLowering()
std::unique_ptr< Pass > mlir::createShapeToShapeLowering ()
Creates an instance of the ShapeToShapeLowering pass that legalizes Shape dialect to be convertible to Standard.
For example, shape.num_elements get transformed to shape.reduce, which can be lowered to SCF and Standard.
Definition at line 80 of file ShapeToShapeLowering.cpp.
createSimplifyAffineStructuresPass()
std::unique_ptr< OperationPass< FuncOp > > mlir::createSimplifyAffineStructuresPass ()
Creates a simplification pass for affine structures (maps and sets).
In addition, this pass also normalizes memrefs to have the trivial (identity) layout map.
Definition at line 75 of file SimplifyAffineStructures.cpp.
References applyOpPatternsAndFold(), and mlir::Operation::getAttrs().
createStdBufferizePass()
std::unique_ptr< Pass > mlir::createStdBufferizePass ()
Creates an instance of std bufferization pass.
Definition at line 201 of file Bufferize.cpp.
createStdExpandOpsPass()
std::unique_ptr< Pass > mlir::createStdExpandOpsPass ()
Creates an instance of the StdExpand pass that legalizes Std dialect ops to be convertible to LLVM.
For example, std.ceildivi_signed gets transformed to a number of std operations, which can be lowered to LLVM; memref_reshape gets converted to memref_reinterpret_cast.
Definition at line 246 of file ExpandOps.cpp.
createStripDebugInfoPass()
std::unique_ptr< Pass > mlir::createStripDebugInfoPass ()
Creates a pass to strip debug information from a function.
Definition at line 30 of file StripDebugInfo.cpp.
createSuperVectorizePass() [1/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createSuperVectorizePass (ArrayRef< int64_t > virtualVectorSize)
Creates a pass to vectorize loops, operations and data types using a target-independent, n-D super-vector abstraction.
Definition at line 1428 of file SuperVectorize.cpp.
createSuperVectorizePass() [2/2]
std::unique_ptr< OperationPass< FuncOp > > mlir::createSuperVectorizePass ()
Overload relying on pass options for initialization.
Definition at line 1431 of file SuperVectorize.cpp.
createSymbolDCEPass()
std::unique_ptr< Pass > mlir::createSymbolDCEPass ()
Creates a pass which delete symbol operations that are unreachable.
This pass may only be scheduled on an operation that defines a SymbolTable.
Definition at line 144 of file SymbolDCE.cpp.
createTensorBufferizePass()
std::unique_ptr< Pass > mlir::createTensorBufferizePass ()
Creates an instance of tensor dialect bufferization pass.
Definition at line 62 of file Bufferize.cpp.
createTensorConstantBufferizePass()
std::unique_ptr< Pass > mlir::createTensorConstantBufferizePass ()
Creates an instance of tensor constant bufferization pass.
Definition at line 122 of file TensorConstantBufferize.cpp.
debugString()
template<typename T > static std::string mlir::debugString (T & op) static
Definition at line 27 of file DebugStringHelper.h.
Referenced by isFnEntryBlock().
defaultFilterFunction()
bool mlir::defaultFilterFunction (Operation &) inline
Definition at line 91 of file NestedMatcher.h.
delinearize()
SmallVector< int64_t, 4 > mlir::delinearize (ArrayRef< int64_t > strides, int64_t linearIndex)
Given the strides together with a linear index in the dimension space, returns the vector-space offsets in each dimension for a de-linearized index.
Definition at line 81 of file VectorUtils.cpp.
Referenced by applyMapToValues(), foldExtractFromShapeCast(), generateExtractSlicesOpResultType(), generateTransferOpSlices(), isValidExtractOrInsertSlicesType(), unrollSingleResultStructuredOp(), and mlir::vector::unrollSingleResultVectorOp().
emitError() [1/2]
InFlightDiagnostic mlir::emitError (Location loc)
Utility method to emit an error message using this location.
Emit an error message using this location.
Definition at line 301 of file Diagnostics.cpp.
Referenced by buildSequentialConstant(), checkedAddLLVMFnAttribute(), checkTensorElementType(), computeConversionSet(), mlir::LLVM::ModuleTranslation::convertOperation(), deserializeModule(), diag(), mlir::Operation::emitError(), mlir::OpState::erase(), mlir::quant::fakeQuantAttrsToType(), forwardPassthroughAttributes(), mlir::MemRefType::getChecked(), getElementPtrType(), getElementType(), mlir::Lexer::getEncodedSourceLocation(), getInnermostElementType(), getLLVMAtomicOrdering(), getMemRefSizeInBytes(), getOrInsertBuiltinVariable(), getPhiIncomingBlock(), isFnEntryBlock(), logFailure(), mlirEmitError(), parseAccessChainOp(), mlir::detail::Parser::parseAffineMapReference(), mlir::OpAsmParser::parseAssignmentList(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::detail::Parser::parseCommaSeparatedListUntil(), mlir::detail::Parser::parseExtendedAttr(), mlir::DialectAsmParser::parseInteger(), mlir::OpAsmParser::parseInteger(), mlir::detail::Parser::parseIntegerSetReference(), mlir::DialectAsmParser::parseKeyword(), mlir::OpAsmParser::parseKeyword(), mlir::DialectAsmParser::parseOptionalInteger(), mlir::OpAsmParser::parseOptionalInteger(), mlir::detail::Parser::parsePrettyDialectSymbolName(), mlir::OpAsmParser::parseSymbolName(), mlir::DialectAsmParser::parseType(), mlir::OpAsmParser::parseType(), performActions(), mlir::OpAsmParser::resolveOperands(), translateLLVMIRToModule(), translateModuleToLLVMIR(), unwrap(), mlir::quant::QuantizedType::verifyConstructionInvariants(), mlir::spirv::InterfaceVarABIAttr::verifyConstructionInvariants(), mlir::ComplexType::verifyConstructionInvariants(), mlir::spirv::VerCapExtAttr::verifyConstructionInvariants(), mlir::IntegerType::verifyConstructionInvariants(), mlir::spirv::TargetEnvAttr::verifyConstructionInvariants(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::OpaqueType::verifyConstructionInvariants(), mlir::IntegerAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::LLVM::LLVMArrayType::verifyConstructionInvariants(), mlir::OpaqueAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), mlir::LLVM::LLVMFunctionType::verifyConstructionInvariants(), mlir::VectorType::verifyConstructionInvariants(), mlir::LLVM::LLVMIntegerType::verifyConstructionInvariants(), mlir::LLVM::LLVMPointerType::verifyConstructionInvariants(), mlir::quant::CalibratedQuantizedType::verifyConstructionInvariants(), mlir::RankedTensorType::verifyConstructionInvariants(), mlir::spirv::MatrixType::verifyConstructionInvariants(), mlir::LLVM::LLVMStructType::verifyConstructionInvariants(), mlir::LLVM::LLVMVectorType::verifyConstructionInvariants(), mlir::UnrankedMemRefType::verifyConstructionInvariants(), verifyFloatTypeInvariants(), verifyIntegerTypeInvariants(), and verifyRegionAttribute().
emitError() [2/2]
InFlightDiagnostic mlir::emitError (Location loc, const Twine & message)
Definition at line 302 of file Diagnostics.cpp.
References emitDiag(), and Error.
Referenced by emitOptionalError().
emitOptionalError()
template<typename... Args> LogicalResult mlir::emitOptionalError (Optional< Location > loc, Args &&... args)
Overloads of the above emission functions that take an optionally null location.
If the location is null, no diagnostic is emitted and a failure is returned. Given that the provided location may be null, these methods take the diagnostic arguments directly instead of relying on the returned InFlightDiagnostic.
Definition at line 471 of file Diagnostics.h.
References mlir::InFlightDiagnostic::append(), emitError(), and failure().
Referenced by mlir::MemRefType::getChecked().
emitOptionalRemark()
template<typename... Args> LogicalResult mlir::emitOptionalRemark (Optional< Location > loc, Args &&... args)
Definition at line 483 of file Diagnostics.h.
References mlir::InFlightDiagnostic::append(), emitRemark(), and failure().
emitOptionalWarning()
template<typename... Args> LogicalResult mlir::emitOptionalWarning (Optional< Location > loc, Args &&... args)
Definition at line 477 of file Diagnostics.h.
References mlir::InFlightDiagnostic::append(), emitWarning(), and failure().
emitRemark() [1/2]
InFlightDiagnostic mlir::emitRemark (Location loc)
Utility method to emit a remark message using this location.
Emit a remark message using this location.
Definition at line 315 of file Diagnostics.cpp.
Referenced by mlir::Operation::emitRemark(), and mlir::OpState::erase().
emitRemark() [2/2]
InFlightDiagnostic mlir::emitRemark (Location loc, const Twine & message)
Definition at line 318 of file Diagnostics.cpp.
References emitDiag(), and Remark.
Referenced by emitOptionalRemark().
emitWarning() [1/2]
InFlightDiagnostic mlir::emitWarning (Location loc)
Utility method to emit a warning message using this location.
Emit a warning message using this location.
Definition at line 307 of file Diagnostics.cpp.
Referenced by mlir::Operation::emitWarning(), mlir::OpState::erase(), and getLLVMAtomicOrdering().
emitWarning() [2/2]
InFlightDiagnostic mlir::emitWarning (Location loc, const Twine & message)
Definition at line 310 of file Diagnostics.cpp.
References emitDiag(), and Warning.
Referenced by emitOptionalWarning().
encodeBindAttribute()
void mlir::encodeBindAttribute (ModuleOp module)
Encodes global variable's descriptor set and binding into its name if they both exist.
Definition at line 1529 of file ConvertSPIRVToLLVM.cpp.
References failed(), mlir::IntegerAttr::getInt(), mlir::IntegerAttr::getValue(), kBinding, kDescriptorSet, mlir::SymbolTable::replaceAllSymbolUses(), and mlir::SymbolTable::setSymbolName().
eraseStridedLayout()
MemRefType mlir::eraseStridedLayout (MemRefType t)
Return a version of t with a layout that has all dynamic offset and strides.
This is used to erase the static layout.
Definition at line 822 of file BuiltinTypes.cpp.
References mlir::ShapedType::kDynamicStrideOrOffset, makeStridedLinearLayoutMap(), and mlir::MemRefType::Builder::setAffineMaps().
Referenced by mlir::TensorType::classof(), createTypeCanonicalizedMemRefOperands(), and extractOperandTypes().
expandAffineExpr()
mlir::Value mlir::expandAffineExpr (OpBuilder & builder, Location loc, AffineExpr expr, ValueRange dimValues, ValueRange symbolValues)
Emit code that computes the given affine expression using standard arithmetic operations applied to the provided dimension and symbol values.
Create a sequence of operations that implement the expr applied to the given dimension and symbol values.
Definition at line 213 of file AffineToStandard.cpp.
Referenced by expandAffineMap(), and lowerAffineLowerBound().
expandAffineMap()
Optional< SmallVector< Value, 8 > > mlir::expandAffineMap (OpBuilder & builder, Location loc, AffineMap affineMap, ValueRange operands)
Create a sequence of operations that implement the affineMap applied to the given operands (as it it were an AffineApplyOp).
Definition at line 221 of file AffineToStandard.cpp.
References expandAffineExpr(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getResults(), and mlir::vector::None.
Referenced by lowerAffineLowerBound(), lowerAffineMapMax(), and lowerAffineMapMin().
extractFixedOuterLoops()
TileLoops mlir::extractFixedOuterLoops (scf::ForOp rootFOrOp, ArrayRef< int64_t > sizes)
Tile a nest of standard for loops rooted at rootForOp by finding such parametric tile sizes that the outer loops have a fixed number of iterations as defined in sizes.
Definition at line 1862 of file LoopUtils.cpp.
References ceilDivPositive(), mlir::OpBuilder::create(), getPerfectlyNestedLoopsImpl(), tile(), and tryIsolateBands().
extractForInductionVars()
void mlir::extractForInductionVars (ArrayRef< AffineForOp > forInsts, SmallVectorImpl< Value > * ivs)
Extracts the induction variables from a list of AffineForOps and places them in the output argument ivs.
Extracts the induction variables from a list of AffineForOps and returns them.
Definition at line 1913 of file AffineOps.cpp.
Referenced by mlir::MemRefRegion::compute(), getFullMemRefAsRegion(), getIndexSet(), tilePerfectlyNested(), and tilePerfectlyNestedParametric().
failed()
bool mlir::failed (LogicalResult result) inline
Utility function that returns true if the provided LogicalResult corresponds to a failure value.
Definition at line 46 of file LogicalResult.h.
References mlir::LogicalResult::Failure, and mlir::LogicalResult::value.
Referenced by mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addInductionVarOrTerminalSymbol(), mlir::Simplex::addInequality(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), addMemRefAccessConstraints(), addMissingLoopIVBounds(), mlir::FlatAffineConstraints::addSliceBounds(), mlir::PassPipelineCLParser::addToPipeline(), adjustToDivisorsOfTripCounts(), affineDataCopyGenerate(), analyzeProfitability(), applyCmpPredicate(), applyOpPatternsAndFold(), mlir::linalg::applyStagedPatterns(), canFoldIntoConsumerOp(), canFuseLoops(), canFuseSrcWhichWritesToLiveOut(), checkAndUpdateCapabilityRequirements(), checkMemrefAccessDependence(), collapseBranch(), mlir::spirv::combine(), mlir::FlatAffineConstraints::composeMap(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::MemRefRegion::compute(), computeConversionSet(), computeSliceUnion(), mlir::FlatAffineConstraints::constantFoldIdRange(), mlir::detail::constructContainerOpForParserIfNecessary(), convertAffineLoopNestToGPULaunch(), mlir::TypeConverter::convertBlockSignature(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVM::ModuleTranslation::convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::convertOmpParallel(), mlir::LLVM::ModuleTranslation::convertOperation(), convertPDLToPDLInterp(), convertRangeType(), mlir::detail::ConversionPatternRewriterImpl::convertRegionTypes(), mlir::TypeConverter::convertSignatureArg(), mlir::TypeConverter::convertSignatureArgs(), convertStructType(), convertToLaunchFuncOp(), mlir::TypeConverter::convertType(), mlir::TypeConverter::convertTypes(), mlir::OperationFolder::create(), mlir::PassPipelineOptions< EmptyPipelineOptions >::createFromString(), createGenericOpFromNamedOp(), mlir::LLVM::LLVMType::createStructTy(), mlir::OpaqueElementsAttr::decode(), mlir::ValueDecomposer::decomposeValue(), mlir::spirv::deserialize(), diag(), doubleBuffer(), encodeBindAttribute(), encodeKernelName(), extractCompositeElement(), mlir::FailureOr< T >::FailureOr(), finalizeBufferAllocation(), findMatchingStartFinishInsts(), mlir::FlatAffineConstraints::FlatAffineConstraints(), foldLoopBounds(), forwardPassthroughAttributes(), mlir::FrozenRewritePatternList::FrozenRewritePatternList(), generateCopyForMemRegion(), generateLocationsFromIR(), mlir::spirv::SPIRVConversionTarget::get(), mlir::ComputationSliceState::getAsConstraints(), mlir::FlatAffineConstraints::getAsIntegerSet(), getBase(), getBasePtr(), getCastCompatibleMemRefType(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::getChecked(), getDefaultABIAttrs(), mlir::spirv::getElementPtr(), getElementPtrType(), mlir::spirv::StructType::getEmpty(), mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::getFromOpaquePointer(), getIndexedPtrs(), getIndexSet(), mlir::FlatAffineConstraints::getIneqAsAffineValueMap(), getLLVMAtomicOrdering(), getMemoryFootprintBytes(), getMemRefSizeInBytes(), mlir::detail::PassOptions::getOptionWidth(), mlir::OperationFolder::getOrCreateConstant(), getPhiIncomingBlock(), getStridesAndOffset(), getTransferOpAdapter(), getTypeNumBytes(), hasSizeMismatch(), mlir::linalg::hoistRedundantVectorTransfers(), mlir::detail::inferReturnTensorTypes(), mlir::detail::PDLByteCode::initializeMutableState(), inlineCall(), inlineCallsInSCC(), isAsyncWithOneDependency(), isFnEntryBlock(), isFusionProfitable(), isMemRefNormalizable(), JitRunnerMain(), mlir::SymbolTable::lookupSymbolIn(), mlir::SymbolTableCollection::lookupSymbolIn(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::vector::UnrollVectorPattern::matchAndRewrite(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ConversionPattern::matchAndRewrite(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), mlir::ContractionOpToDotLowering::matchAndRewrite(), mlir::OpConversionPattern< SPIRVOp >::matchAndRewrite(), mlir::linalg::LinalgTilingPattern< OpTy >::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite(), mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite(), mlir::linalg::LinalgBaseTilingPattern::matchAndRewriteBase(), matchSimpleAtomicOp(), MlirOptMain(), mlirTranslateMain(), moveLoopInvariantCode(), normalizeMemRef(), normalizeMemRefType(), mlir::ParseResult::operator bool(), outlineExecuteOp(), parseAffineParallelOp(), parseAndVerify< unsigned >(), parseArrayType(), parseAttributions(), parseBound(), parseCalibratedType(), parseConstShapeOp(), parseElementAttrHexValues(), parseExecuteOp(), parseExpressedTypeAndRange(), parseFenceOp(), parseFuncOp(), mlir::impl::parseFunctionArgumentList(), mlir::impl::parseFunctionLikeOp(), parseFunctionResultList(), parseGenericOp(), parseGlobalOp(), parseGPUFuncOp(), parseInterfaceVarABIAttr(), parseKeywordList(), parseListOfOperandsOrIntegers(), parseLLVMFuncOp(), parseLoopOp(), parseMemRefReinterpretCastOp(), mlir::detail::Parser::parseMemRefType(), parseOperandList(), parseOperationOp(), parseOptionalArrayStride(), mlir::detail::Parser::parseOptionalInteger(), mlir::DialectAsmParser::parseOptionalInteger(), mlir::OpAsmParser::parseOptionalInteger(), parseParallelOp(), parsePassPipeline(), parseQuantParams(), parseRuntimeArrayType(), parseSourceFile(), parseSourceString(), parseStorageRange(), parseStorageType(), mlir::detail::Parser::parseStridedLayout(), parseStructMemberDecorations(), parseStructType(), parseSubTensorInsertOp(), parseSubTensorOp(), parseSubViewOp(), mlir::OpAsmParser::parseSymbolName(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), performActions(), performPreTilingChecks(), populateAffineToVectorConversionPatterns(), populateConvertShapeConstraintsConversionPatterns(), populateElementwiseToLinalgConversionPatterns(), populateEliminateBufferizeMaterializationsPatterns(), populateLinalgToLLVMConversionPatterns(), mlir::linalg::populateLinalgToStandardConversionPatterns(), populateLoopToStdConversionPatterns(), populateOpenMPToLLVMConversionPatterns(), populateSPIRVLayoutInfoPatterns(), populateStdBufferizePatterns(), populateTensorBufferizePatterns(), populateVectorToROCDLConversionPatterns(), populateVectorToSPIRVPatterns(), printFloatValue(), processParallelLoop(), mlir::LLVMTypeConverter::promoteOperands(), mlir::linalg::promoteSubViews(), promoteSubViews(), registerTranslateToMLIRFunction(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), replaceAllMemRefUsesWith(), replaceTransferOpWithLoadOrStore(), replaceTransferOpWithMasked(), resolveSourceIndices(), roundTripModule(), mlir::detail::OpToOpPassAdaptor::runOnOperation(), runTransformOnCGSCCs(), separateFullTiles(), serializeModule(), mlir::OpPassManager::setNesting(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), splitAndProcessBuffer(), tilePerfectlyNested(), tilePerfectlyNestedParametric(), mlir::linalg::CodegenStrategy::transform(), translateLLVMIRToModule(), mlir::LLVM::ModuleTranslation::translateModule(), mlir::OpBuilder::tryFold(), mlir::OperationFolder::tryToFold(), updateCalls(), updateSymbolAndAllUses(), vectorizeAffineForOp(), vectorizeLoopNest(), vectorizeLoops(), vectorizeLoopsAndLoads(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), verify(), verifyAttributions(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::IntegerAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), verifyCopyMemory(), verifyGenericOp(), verifyGroupNonUniformArithmeticOp(), mlir::detail::verifyInferredResultTypes(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), verifySingleInputPoolingOp(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait(), mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType >::verifyTrait(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait(), mlir::detail::verifyTypesAlongControlFlowEdges(), visitInPrettyBlockOrder(), and wrapExternalFunction().
failure()
LogicalResult mlir::failure (bool isFailure = true) inline
Utility function to generate a LogicalResult.
If isFailure is true a failure result is generated, otherwise a 'success' result is generated.
Definition at line 33 of file LogicalResult.h.
References mlir::LogicalResult::Failure, and mlir::LogicalResult::Success.
Referenced by ableToUpdatePredOperands(), mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), addMemRefAccessConstraints(), addMissingLoopIVBounds(), mlir::FlatAffineConstraints::addSliceBounds(), mlir::PassPipelineCLParser::addToPipeline(), allocateBuffersForResults(), analyzeProfitability(), applyCmpPredicate(), applyPatternsAndFoldGreedily(), mlir::linalg::applyStagedPatterns(), barePtrFuncArgTypeConverter(), mlir::ConstantIndexOp::build(), buildAffineLoopNest(), canFoldIntoConsumerOp(), mlir::AffineValueMap::canonicalize(), canonicalizeLoopBounds(), canonicalizeSetAndOperands(), checkCapabilityRequirements(), checkExtensionRequirements(), checkIfHyperRectangular(), collapseBranch(), collapseReassociationMaps(), collectValidReferencesFor(), mlir::FlatAffineConstraints::composeMap(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::MemRefRegion::compute(), computeConversionSet(), computeSliceUnion(), mlir::AffineMap::constantFold(), mlir::FlatAffineConstraints::constantFoldId(), convertAffineLoopNestToGPULaunch(), mlir::TypeConverter::convertBlockSignature(), mlir::LLVM::ModuleTranslation::convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::convertOmpParallel(), mlir::LLVM::ModuleTranslation::convertOperation(), convertPDLToPDLInterp(), convertRangeType(), mlir::detail::ConversionPatternRewriterImpl::convertRegionTypes(), mlir::TypeConverter::convertSignatureArg(), mlir::TypeConverter::convertSignatureArgs(), convertStructType(), mlir::TypeConverter::convertType(), mlir::TypeConverter::convertTypes(), createFullTiles(), createGenericOpFromNamedOp(), mlir::DialectDecodeAttributesInterface::decode(), mlir::ValueDecomposer::decomposeValue(), emitOptionalError(), emitOptionalRemark(), emitOptionalWarning(), encodeKernelName(), extractCompositeElement(), extractStrides(), extractValueFromConstOp(), finalizeBufferAllocation(), mlir::DialectFoldInterface::fold(), mlir::Operation::fold(), foldExtractOpFromExtractChain(), foldExtractOpFromTranspose(), foldExtractStridedOpFromInsertChain(), foldLoopBounds(), mlir::op_definition_impl::foldTrait(), mlir::op_definition_impl::foldTraits(), foldTransferMaskAttribute(), forwardPassthroughAttributes(), mlir::linalg::fuseTensorOps(), fuseWithReshapeByExpansion(), generateCopy(), genStmt(), mlir::OpAsmDialectInterface::getAlias(), mlir::ComputationSliceState::getAsConstraints(), getAtomicOpScope(), getBase(), getBasePtr(), getDefaultABIAttrs(), mlir::spirv::getExecutionModel(), getFlattenedAffineExprs(), mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::getFromOpaquePointer(), getIndexedPtrs(), getIndexSet(), getInterfaceVariables(), getLaunchConfigIndex(), getLLVMAtomicOrdering(), getLocalInvocationDimSize(), mlir::spirv::getMemoryModel(), getMemRefAlignment(), getMemRefSizeInBytes(), mlir::detail::PassOptions::getOptionWidth(), mlir::OperationFolder::getOrCreateConstant(), getOrCreateRanges(), mlir::scf::getParallelForInductionVarOwner(), getPhiIncomingBlock(), getSrcVectorElementType(), getStridesAndOffset(), getTransferOpAdapter(), handleMultidimensionalVectors(), hasSizeMismatch(), hoistAffineIfOp(), hoistOpsBetween(), mlir::detail::inferReturnTensorTypes(), initializeAliases(), inlineCall(), inlineCallsInSCC(), inlineRegion(), mlir::linalg::interchangeGenericLinalgOpPrecondition(), isAsyncWithOneDependency(), isContraction(), isFnEntryBlock(), joinShapes(), mlir::linalg::linalgOpToAffineLoops(), mlir::linalg::linalgOpToLoops(), linalgOpToLoopsImpl(), mlir::linalg::linalgOpToParallelLoops(), logFailure(), lookupSymbolInImpl(), loopUnrollByFactor(), loopUnrollFull(), loopUnrollJamByFactor(), lowerAffineLowerBound(), lowerEntryPointABIAttr(), lowerLinalgToLoopsImpl(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), mlir::linalg::CopyOpToLibraryCallRewrite::matchAndRewrite(), mlir::PatternApplicator::matchAndRewrite(), mlir::linalg::CopyTransposeRewrite::matchAndRewrite(), mlir::linalg::IndexedGenericOpToLibraryCallRewrite::matchAndRewrite(), mlir::vector::UnrollVectorPattern::matchAndRewrite(), mlir::RewritePattern::matchAndRewrite(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), mlir::OpRewritePattern< vector::ContractionOp >::matchAndRewrite(), mlir::vector::PointwiseExtractPattern::matchAndRewrite(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ConversionPattern::matchAndRewrite(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), mlir::ContractionOpToDotLowering::matchAndRewrite(), mlir::OpConversionPattern< SPIRVOp >::matchAndRewrite(), mlir::linalg::LinalgTilingPattern< OpTy >::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite(), mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite(), mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite(), mlir::ConvertOpToLLVMPattern< gpu::ReturnOp >::matchAndRewrite(), mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite(), mlir::linalg::AffineMinSCFCanonicalizationPattern::matchAndRewrite(), mlir::linalg::ConvOpVectorization< ConvOp, N >::matchAndRewrite(), TransferReadExtractPattern::matchAndRewrite(), TransferWriteInsertPattern::matchAndRewrite(), mlir::linalg::LinalgBaseTilingPattern::matchAndRewriteBase(), matchSimpleAtomicOp(), mergeIdenticalBlocks(), MlirOptMain(), mlirTranslateMain(), mlir::LLVM::detail::LLVMStructTypeStorage::mutate(), mlir::spirv::detail::StructTypeStorage::mutate(), normalizeMemRef(), mlir::PatternRewriter::notifyMatchFailure(), mlir::detail::ConversionPatternRewriterImpl::notifyMatchFailure(), mlir::LLVM::detail::oneToOneRewrite(), mlir::Diagnostic::operator LogicalResult(), mlir::InFlightDiagnostic::operator LogicalResult(), outlineExecuteOp(), mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl(), mlir::AffineDmaStartOp::parse(), mlir::DmaStartOp::parse(), mlir::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineApplyOp(), parseAffineForOp(), parseAffineIfOp(), parseAffineLoadOp(), mlir::detail::Parser::parseAffineMapReference(), parseAffineMinMaxOp(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAffineStoreOp(), parseAffineVectorLoadOp(), parseAffineVectorStoreOp(), parseAllocaOp(), parseAllocateAndAllocator(), parseAssumingOp(), parseAtomicBinOp(), parseAtomicCmpXchgOp(), parseAtomicCompareExchangeWeakOp(), parseAtomicOrdering(), parseAtomicRMWOp(), parseAtomicUpdateOp(), mlir::detail::Parser::parseAttribute(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), mlir::detail::Parser::parseAttributeDict(), parseAttributions(), parseAwaitResultType(), parseBound(), parseBranchConditionalOp(), parseCallOp(), mlir::detail::Parser::parseCallSiteLocation(), mlir::impl::parseCastOp(), parseCmpOp(), mlir::OpAsmParser::parseColonType(), mlir::detail::Parser::parseCommaSeparatedList(), mlir::detail::Parser::parseCommaSeparatedListUntil(), parseCommonStructuredOpParts(), parseCompositeConstructOp(), parseCompositeExtractOp(), parseCompositeInsertOp(), parseConstantOp(), parseConstShapeOp(), parseContractionOp(), parseControlAttribute(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseCreateOperationOp(), parseDimAndSymbolList(), mlir::detail::Parser::parseDimensionListRanked(), parseDynamicTensorFromElementsOp(), parseElementAttrHexValues(), parseEntryPointOp(), parseEnumKeywordAttr(), parseEnumKeywordAttr(), parseEnumStrAttr(), parseExecuteOp(), parseExecutionModeOp(), parseExtractElementOp(), parseExtractOp(), parseExtractValueOp(), parseFenceOp(), parseForOp(), mlir::detail::PassOptions::parseFromString(), parseFuncOp(), mlir::impl::parseFunctionArgumentList(), parseFunctionLibraryOp(), mlir::impl::parseFunctionLikeOp(), parseFunctionResultList(), mlir::detail::Parser::parseFunctionResultTypes(), mlir::impl::parseFunctionSignature(), mlir::detail::Parser::parseFusedLocation(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGPUModuleOp(), parseGroupNonUniformArithmeticOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), mlir::detail::Parser::parseIntegerSetReference(), parseInvokeOp(), parseKeywordList(), mlir::OpAsmParser::parseKeywordType(), parseLandingpadOp(), parseLaunchOp(), parseListOfOperandsOrIntegers(), parseLLVMFuncOp(), parseLoadOp(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseLoopOp(), parseMemoryAccessAttributes(), parseMemRefReinterpretCastOp(), mlir::detail::Parser::parseMemRefType(), parseModuleOp(), parseNamedStructuredOp(), parseNamedStructuredOpResults(), mlir::detail::Parser::parseNameOrFileLineColLocation(), parseNVVMShflSyncBflyOp(), parseNVVMVoteBallotOp(), parseOffsetsSizesAndStrides(), mlir::impl::parseOneResultSameOperandTypeOp(), parseOperandAndType(), parseOperandAndTypeList(), parseOperandList(), parseOperationOp(), parseOptionalArrayStride(), mlir::detail::Parser::parseOptionalAttributeWithToken(), mlir::detail::Parser::parseOptionalInteger(), parseOptionalLLVMKeyword(), parseOptionalOperand(), parseOptionalOperandAndType(), mlir::detail::Parser::parseOptionalType(), mlir::impl::parseOptionalVisibilityKeyword(), parseOuterProductOp(), parseParallelOp(), parsePassPipeline(), parsePrefetchOp(), parseQuantParams(), parseReduceOp(), parseReductionOp(), parseRegions(), parseReturnOp(), parseROCDLMubufLoadOp(), parseROCDLMubufStoreOp(), parseSelectionOp(), parseSelectOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSizeAssignment(), parseSliceOp(), parseSourceMemoryAccessAttributes(), parseSourceString(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseSpecConstantOperationOp(), parseStorageRange(), parseStoreOp(), mlir::detail::Parser::parseStrideList(), parseStructMemberDecorations(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), parseSubTensorInsertOp(), parseSubTensorOp(), parseSubViewOp(), parseTransferReadOp(), parseTransferWriteOp(), parseTransposeOp(), parseTupleGetOp(), parseTupleOp(), mlir::DialectAsmParser::parseType(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::parseTypeList(), mlir::detail::Parser::parseTypeListNoParens(), mlir::detail::Parser::parseTypeListParens(), parseUnaryOp(), parseVariableDecorations(), parseVariableOp(), parseVerCapExtAttr(), parseViewOp(), parseYieldOp(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration(), performActions(), populateCallOpTypeConversionPattern(), print(), processParallelLoop(), promoteIfSingleIteration(), mlir::linalg::promoteSubviewsPrecondition(), registerArmNeonToLLVMIRTranslation(), registerArmSVEToLLVMIRTranslation(), registerAVX512ToLLVMIRTranslation(), registerToLLVMIRTranslation(), registerToNVVMIRTranslation(), registerToROCDLIRTranslation(), registerTranslateToMLIRFunction(), replaceAllMemRefUsesWith(), replaceAllSymbolUsesImpl(), replaceBlockArgForUnitDimLoops< IndexedGenericOp >(), replaceOpWithRegion(), replaceTransferOpWithLoadOrStore(), replaceTransferOpWithMasked(), replaceTransferOpWithMubuf(), replaceUnitExtents(), replaceWithLoadOrStore(), reshapeLowerToHigher(), mlir::OpAsmParser::resolveOperands(), resolveSourceIndices(), roundTripModule(), runRegionDCE(), runTransformOnCGSCCs(), separateFullTiles(), serializeModule(), mlir::OpPassManager::setNesting(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), splitAndProcessBuffer(), mlir::vector::splitFullAndPartialTransfer(), mlir::vector::splitFullAndPartialTransferPrecondition(), structFuncArgTypeConverter(), tilePerfectlyNested(), tilePerfectlyNestedParametric(), mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration(), mlir::OpBuilder::tryFold(), tryIsolateBands(), mlir::OperationFolder::tryToFold(), mlir::FlatAffineConstraints::unionBoundingBox(), mlir::vector::unrollSingleResultVectorOp(), mlir::vector::unrollTransferWriteOp(), updateCalls(), vectorizeAffineForOp(), mlir::linalg::vectorizeLinalgOpPrecondition(), vectorizeLoopNest(), vectorizeLoopsAndLoads(), vectorizeNonTerminals(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), mlir::SourceMgrDiagnosticVerifierHandler::verify(), verify(), verifyAttributions(), verifyCompatibleShape(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::IntegerAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), verifyConvOp(), verifyCopyMemory(), verifyDependencies(), verifyGenericOp(), mlir::detail::verifyInferredResultTypes(), verifyLoopOp(), verifyNamedStructuredOp(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), verifySingleInputPoolingOp(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait(), mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType >::verifyTrait(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyTrait(), mlir::OpTrait::IsIsolatedFromAbove< ConcreteType >::verifyTrait(), mlir::op_definition_impl::verifyTraitsImpl(), mlir::detail::verifyTypesAlongControlFlowEdges(), visitInPrettyBlockOrder(), and wrapExternalFunction().
floor()
int64_t mlir::floor (Fraction f) inline
Definition at line 55 of file Fraction.h.
References mlir::Fraction::den, floorDiv(), and mlir::Fraction::num.
Referenced by mlir::Simplex::computeIntegerBounds().
floorDiv()
int64_t mlir::floorDiv (int64_t lhs, int64_t rhs) inline
Returns the result of MLIR's floordiv operation on constants.
The RHS is expected to be non-zero.
Definition at line 32 of file MathExtras.h.
Referenced by mlir::FlatAffineConstraints::containsPoint(), createPrivateMemRef(), floor(), generateCopy(), mlir::FlatAffineConstraints::getConstantBoundOnDimSize(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::AffineExpr::operator!(), mlir::GBRSimplex::removeLastEquality(), and substituteLoopInExpr().
fullyComposeAffineMapAndOperands()
void mlir::fullyComposeAffineMapAndOperands (AffineMap * map, SmallVectorImpl< Value > * operands)
Given an affine map map and its input operands, this method composes into map, maps of AffineApplyOps whose results are the values in operands, iteratively until no more of operands are the result of an AffineApplyOp.
When this function returns, map becomes the composed affine map, and each Value in operands is guaranteed to be either a loop IV or a terminal symbol, i.e., a symbol defined at the top level or a block/function argument.
Definition at line 839 of file AffineOps.cpp.
References composeAffineMapAndOperands(), and mlir::Value::getDefiningOp().
Referenced by mlir::FlatAffineConstraints::addLowerOrUpperBound(), applyMapToValues(), createAffineComputationSlice(), createCanonicalizedAffineForOp(), createFoldedComposedAffineApply(), mlir::AffineValueMap::difference(), generateCopy(), generatePointWiseCopy(), mlir::MemRefAccess::getAccessMap(), getCleanupLoopLowerBound(), mlir::AffineDmaWaitOp::getTagMapAttrName(), replaceAllMemRefUsesWith(), and substitute().
fuseLoops()
void mlir::fuseLoops (AffineForOp srcForOp, AffineForOp dstForOp, const ComputationSliceState & srcSlice)
Fuses 'srcForOp' into 'dstForOp' with destination loop block insertion point and source slice loop bounds specified in 'srcSlice'.
Definition at line 367 of file LoopFusionUtils.cpp.
References canonicalizeMapAndOperands(), getForInductionVarOwner(), mlir::ComputationSliceState::insertPoint, mlir::ComputationSliceState::ivs, mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, promoteIfSingleIteration(), mlir::ComputationSliceState::ubOperands, and mlir::ComputationSliceState::ubs.
Referenced by mlir::FusionStrategy::FusionStrategy(), and isFusionProfitable().
gatherLoops()
void mlir::gatherLoops (FuncOp func, std::vector< SmallVector< AffineForOp, 2 >> & depthToLoops)
Gathers all AffineForOps in 'func' grouped by loop depth.
Definition at line 2891 of file LoopUtils.cpp.
References gatherLoopsInBlock().
generateCopyForMemRegion()
LogicalResult mlir::generateCopyForMemRegion (const MemRefRegion & memrefRegion, Operation * analyzedOp, const AffineCopyOptions & copyOptions, CopyGenerateResult & result)
generateCopyForMemRegion is similar to affineDataCopyGenerate, but works with a single memref region.
memrefRegion is supposed to contain analysis information within analyzedOp. The generated prologue and epilogue always surround analyzedOp.
Note that analyzedOp is a single op for API convenience, and the [begin, end) version can be added as needed.
Also note that certain options in copyOptions aren't looked at anymore, like slowMemorySpace.
Definition at line 2851 of file LoopUtils.cpp.
References mlir::CopyGenerateResult::alloc, mlir::CopyGenerateResult::copyNest, failed(), generateCopy(), mlir::Operation::getBlock(), mlir::MemRefRegion::memref, mlir::CopyGenerateResult::sizeInBytes, and success().
generateLocationsFromIR() [1/4]
void mlir::generateLocationsFromIR (raw_ostream & os, StringRef fileName, Operation * op, OpPrintingFlags flags)
This function generates new locations from the given IR by snapshotting the IR to the given stream, and using the printed locations within that stream.
The generated locations replace the current operation locations.
Definition at line 95 of file LocationSnapshot.cpp.
Referenced by generateLocationsFromIR(), and generateLocationsFromIR().
generateLocationsFromIR() [2/4]
LogicalResult mlir::generateLocationsFromIR (StringRef fileName, Operation * op, OpPrintingFlags flags)
This function generates new locations from the given IR by snapshotting the IR to the given file, and using the printed locations within that file.
If filename is empty, a temporary file is generated instead.
Definition at line 102 of file LocationSnapshot.cpp.
References generateLocationsFromIR().
generateLocationsFromIR() [3/4]
void mlir::generateLocationsFromIR (raw_ostream & os, StringRef fileName, StringRef tag, Operation * op, OpPrintingFlags flags)
This function generates new locations from the given IR by snapshotting the IR to the given stream, and using the printed locations within that stream.
The generated locations are represented as a NameLoc with the given tag as the name, and then fused with the existing locations.
Definition at line 111 of file LocationSnapshot.cpp.
References generateLocationsFromIR().
generateLocationsFromIR() [4/4]
LogicalResult mlir::generateLocationsFromIR (StringRef fileName, StringRef tag, Operation * op, OpPrintingFlags flags)
This function generates new locations from the given IR by snapshotting the IR to the given file, and using the printed locations within that file.
If filename is empty, a temporary file is generated instead.
Definition at line 119 of file LocationSnapshot.cpp.
References failed(), generateLocationsFromIR(), and generateLocationsFromIR().
getAffineBinaryOpExpr()
AffineExpr mlir::getAffineBinaryOpExpr (AffineExprKind kind, AffineExpr lhs, AffineExpr rhs)
Definition at line 43 of file AffineExpr.cpp.
References Add, CeilDiv, mlir::AffineExpr::ceilDiv(), FloorDiv, mlir::AffineExpr::floorDiv(), Mod, and Mul.
Referenced by mlir::SDBMExpr::getAsAffineExpr(), mlirAffineAddExprGet(), mlirAffineCeilDivExprGet(), mlirAffineFloorDivExprGet(), mlirAffineModExprGet(), mlirAffineMulExprGet(), operator-(), mlir::AffineExpr::replace(), mlir::AffineExpr::replaceDimsAndSymbols(), simplifyAdd(), simplifySemiAffine(), substWithMin(), and symbolicDivide().
getAffineConstantExpr()
AffineExpr mlir::getAffineConstantExpr (int64_t constant, MLIRContext * context)
Definition at line 478 of file AffineExpr.cpp.
References mlir::StorageUniquer::get(), and mlir::MLIRContext::getAffineUniquer().
Referenced by canonicalizeMapOrSetAndOperands(), categorizeValueByAffineType(), mlir::AffineExpr::ceilDiv(), mlir::AffineMap::compose(), detectAsFloorDiv(), mlir::AffineExpr::floorDiv(), generateTransferOpSlices(), mlir::Builder::getAffineConstantExpr(), getAffineExprFromFlatForm(), mlir::SDBMExpr::getAsAffineExpr(), mlir::FlatAffineConstraints::getAsIntegerSet(), mlir::AffineMap::getConstantMap(), mlir::IntegerSet::getEmptySet(), getLocalInvocationDimSize(), getPaddedInput(), getProjectedMap(), mlir::FlatAffineConstraints::getSliceBounds(), getStridesAndOffset(), makeCanonicalStridedLayoutExpr(), makePermutationMap(), makeStridedLinearLayoutMap(), mlirAffineConstantExprGet(), mlir::AffineExpr::operator%(), mlir::AffineExpr::operator*(), mlir::AffineExpr::operator+(), mlir::AffineExpr::operator-(), operator-(), mlir::AffineExpr::operator==(), mlir::AffineMap::partialConstantFold(), replaceUnitDims(), replaceUnitExtents(), simplifyAdd(), simplifyCeilDiv(), simplifyFloorDiv(), simplifyMod(), simplifyMul(), simplifySemiAffine(), symbolicDivide(), verifyOutputShape(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), and mlir::SimpleAffineExprFlattener::visitModExpr().
getAffineDimExpr()
AffineExpr mlir::getAffineDimExpr (unsigned position, MLIRContext * context)
These free functions allow clients of the API to not use classes in detail.
Definition at line 453 of file AffineExpr.cpp.
References DimId, and getAffineDimOrSymbol().
Referenced by adjustMap(), mlir::detail::bindDims(), calculateImplicitMap(), canonicalizeMapOrSetAndOperands(), canonicalizePromotedSymbols(), categorizeValueByAffineType(), collapseReassociationMaps(), mlir::AffineMap::compose(), computeLocalVars(), generateTransferOpSlices(), mlir::Builder::getAffineDimExpr(), getAffineExprFromFlatForm(), mlir::SDBMExpr::getAsAffineExpr(), getDimMap(), mlir::linalg::getDimsOfType(), getLocalInvocationDimSize(), mlir::AffineMap::getMultiDimIdentityMap(), getPaddedInput(), mlir::AffineMap::getPermutationMap(), getProjectedMap(), mlir::FlatAffineConstraints::getSliceBounds(), inversePermutation(), mlir::AffineExpr::isFunctionOfDim(), mlir::linalg::makeAffineDimExprs(), makeCanonicalStridedLayoutExpr(), makePermutationMap(), makeStridedLinearLayoutMap(), makeTiledShapes(), mlir::linalg::ConvOpVectorization< ConvOp, N >::matchAndRewrite(), mlirAffineDimExprGet(), operator-(), promoteComposedSymbolsAsDims(), replaceUnitDims(), replaceUnitExtents(), substitute(), substituteLoopInExpr(), mlir::scf::tileParallelLoop(), and verify().
getAffineExprFromFlatForm()
AffineExpr mlir::getAffineExprFromFlatForm (ArrayRef< int64_t > flatExprs, unsigned numDims, unsigned numSymbols, ArrayRef< AffineExpr > localExprs, MLIRContext * context)
Constructs an affine expression from a flat ArrayRef.
If there are local identifiers (neither dimensional nor symbolic) that appear in the sum of products expression, 'localExprs' is expected to have the AffineExpr for it, and is substituted into. The ArrayRef 'eq' is expected to be in the format [dims, symbols, locals, constant term].
If there are local identifiers (neither dimensional nor symbolic) that appear in the sum of products expression, localExprs is expected to have the AffineExpr for it, and is substituted into. The ArrayRef flatExprs is expected to be in the format [dims, symbols, locals, constant term].
Definition at line 826 of file AffineExpr.cpp.
References mlir::AffineExpr::expr, getAffineConstantExpr(), getAffineDimExpr(), and getAffineSymbolExpr().
Referenced by mlir::FlatAffineConstraints::getAsIntegerSet(), mlir::FlatAffineConstraints::getIneqAsAffineValueMap(), mlir::FlatAffineConstraints::getLowerAndUpperBound(), operator-(), simplifyAffineExpr(), mlir::SimpleAffineExprFlattener::visitConstantExpr(), and mlir::SimpleAffineExprFlattener::visitModExpr().
getAffineSymbolExpr()
AffineExpr mlir::getAffineSymbolExpr (unsigned position, MLIRContext * context)
Definition at line 463 of file AffineExpr.cpp.
References getAffineDimOrSymbol(), and SymbolId.
Referenced by canonicalizeMapOrSetAndOperands(), canonicalizePromotedSymbols(), categorizeValueByAffineType(), mlir::AffineMap::compose(), computeLocalVars(), getAffineExprFromFlatForm(), mlir::Builder::getAffineSymbolExpr(), mlir::SDBMExpr::getAsAffineExpr(), mlir::FlatAffineConstraints::getSliceBounds(), makeCanonicalStridedLayoutExpr(), makeStridedLinearLayoutMap(), mlirAffineSymbolExprGet(), operator-(), promoteComposedSymbolsAsDims(), replaceUnitDims(), mlir::AffineExpr::shiftSymbols(), substituteLoopInExpr(), and verify().
getAllIteratorTypeNames()
ArrayRef<StringRef> mlir::getAllIteratorTypeNames () inline
Use to encode that a particular iterator type has window semantics.
Definition at line 99 of file StructuredOpsUtils.h.
References getParallelIteratorTypeName(), getReductionIteratorTypeName(), and getWindowIteratorTypeName().
Referenced by getNumIterators().
getBackwardSlice()
void mlir::getBackwardSlice (Operation * op, llvm::SetVector< Operation *> * backwardSlice, TransitiveFilter filter = [](Operation *) { return true;})
Fills backwardSlice with the computed backward slice (i.e.
all the transitive defs of op), without including that operation.
This additionally takes a TransitiveFilter which acts as a frontier: when looking at defs transitively, an operation that does not pass the filter is never propagated through. This allows in particular to carve out the scope within a ForInst or the scope within an IfInst.
The implementation traverses the def chains in postorder traversal for efficiency reasons: if an operation is already in backwardSlice, no need to traverse its definitions again. Since useuse-def chains form a DAG, this terminates.
Upon return to the root call, backwardSlice is filled with a postorder list of defs. This happens to be a topological order, from the point of view of the use-def chains.
Example starting from node 8
1 2 3 4 |_______| |______| | | | | 5 6 |___|_____________| | | 7 8 |_______________| | 9
Assuming all local orders match the numbering order: {1, 2, 5, 3, 4, 6}
Referenced by getBackwardSliceImpl(), and getSlice().
getComputationSliceState()
void mlir::getComputationSliceState (Operation * depSourceOp, Operation * depSinkOp, FlatAffineConstraints * dependenceConstraints, unsigned loopDepth, bool isBackwardSlice, ComputationSliceState * sliceState)
Computes the computation slice loop bounds for one loop nest as affine maps of the other loop nest's IVs and symbols, using 'dependenceConstraints' computed between 'depSourceAccess' and 'depSinkAccess'.
If 'isBackwardSlice' is true, a backwards slice is computed in which the slice bounds of loop nest surrounding 'depSourceAccess' are computed in terms of loop IVs and symbols of the loop nest surrounding 'depSinkAccess' at 'loopDepth'. If 'isBackwardSlice' is false, a forward slice is computed in which the slice bounds of loop nest surrounding 'depSinkAccess' are computed in terms of loop IVs and symbols of the loop nest surrounding 'depSourceAccess' at 'loopDepth'. The slice loop bounds and associated operands are returned in 'sliceState'.
Definition at line 757 of file Utils.cpp.
References mlir::Operation::getContext(), mlir::FlatAffineConstraints::getIdValue(), mlir::FlatAffineConstraints::getIdValues(), getLoopIVs(), mlir::FlatAffineConstraints::getNumDimAndSymbolIds(), getSequentialLoops(), mlir::FlatAffineConstraints::getSliceBounds(), mlir::ComputationSliceState::insertPoint, mlir::ComputationSliceState::ivs, kSliceFusionBarrierAttrName, mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, mlir::FlatAffineConstraints::projectOut(), mlir::ComputationSliceState::ubOperands, and mlir::ComputationSliceState::ubs.
Referenced by computeSliceUnion(), and mlir::ComputationSliceState::isEmpty().
getComputeCost()
int64_t mlir::getComputeCost (AffineForOp forOp, LoopNestStats & stats)
Computes the total cost of the loop nest rooted at 'forOp' using 'stats'.
Currently, the total cost is computed by counting the total operation instance count (i.e. total number of operations in the loop body * loop trip count) for the entire loop nest.
Definition at line 554 of file LoopFusionUtils.cpp.
References getComputeCostHelper().
Referenced by isFusionProfitable().
getConstantTripCount()
Optional< uint64_t > mlir::getConstantTripCount (AffineForOp forOp)
Returns the trip count of the loop if it's a constant, None otherwise.
This uses affine expression analysis and is able to determine constant trip count in non-trivial cases.
This method uses affine expression analysis (in turn using getTripCount) and is able to determine constant trip count in non-trivial cases.
Definition at line 87 of file LoopAnalysis.cpp.
References buildTripCountMapAndOperands(), and mlir::AffineMap::getResults().
Referenced by adjustToDivisorsOfTripCounts(), affineForOpBodySkew(), buildSliceTripCountMap(), constructTiledIndexSetHyperRect(), findMatchingStartFinishInsts(), gatherInnermostLoops(), getLoopNestStats(), loopUnrollByFactor(), loopUnrollFull(), loopUnrollJamByFactor(), loopUnrollJamUpToFactor(), loopUnrollUpToFactor(), and promoteIfSingleIteration().
getDenseDimName()
constexpr StringRef mlir::getDenseDimName ()
Definition at line 142 of file StructuredOpsUtils.h.
Referenced by isDenseDim().
getDependenceComponents()
void mlir::getDependenceComponents (AffineForOp forOp, unsigned maxLoopDepth, std::vector< SmallVector< DependenceComponent, 2 >> * depCompsVec)
Returns in 'depCompsVec', dependence components for dependences between all load and store ops in loop nest rooted at 'forOp', at loop depths in range [1, maxLoopDepth].
Gathers dependence components for dependences between all ops in loop nest rooted at 'forOp' at loop depths in range [1, maxLoopDepth].
Definition at line 952 of file AffineAnalysis.cpp.
References checkMemrefAccessDependence(), and hasDependence().
Referenced by hasDependence(), isValidLoopInterchangePermutation(), and sinkSequentialLoops().
getDilationsAttrName()
constexpr StringRef mlir::getDilationsAttrName ()
Attribute name for the StrArrayAttr which encodes the value of dilations.
Definition at line 72 of file StructuredOpsUtils.h.
getDocAttrName()
constexpr StringRef mlir::getDocAttrName ()
Attribute name for the StringAttr which encodes an optional documentation string of the structured op.
Definition at line 59 of file StructuredOpsUtils.h.
getElementTypeOrSelf() [1/3]
Type mlir::getElementTypeOrSelf (Type type)
Return the element type or return the type itself.
Definition at line 21 of file TypeUtilities.cpp.
References mlir::Type::dyn_cast().
Referenced by buildNamedStructuredOpRegionAndAttributesImpl(), extractShape(), mlir::OpTrait::util::getBroadcastedType(), getElementTypeOrSelf(), mlir::edsc::makeGenericLinalgOp(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), and mlir::OpTrait::impl::verifySameOperandsElementType().
getElementTypeOrSelf() [2/3]
Type mlir::getElementTypeOrSelf (Attribute attr)
Return the element type or return the type itself.
Definition at line 31 of file TypeUtilities.cpp.
References getElementTypeOrSelf(), and mlir::Attribute::getType().
getElementTypeOrSelf() [3/3]
Type mlir::getElementTypeOrSelf (Value val)
Definition at line 27 of file TypeUtilities.cpp.
References getElementTypeOrSelf(), and mlir::Value::getType().
getEnclosingAffineForAndIfOps()
void mlir::getEnclosingAffineForAndIfOps (Operation & op, SmallVectorImpl< Operation *> * ops)
Populates 'ops' with IVs of the loops surrounding op, along with affine.if operations interleaved between these loops, ordered from the outermost affine.for or affine.if operation to the innermost one.
Populates 'ops' with IVs of the loops surrounding op, along with affine.if operations interleaved between these loops, ordered from the outermost affine.for operation to the innermost one.
Definition at line 50 of file Utils.cpp.
References mlir::Operation::getParentOp().
Referenced by getOpIndexSet().
getFlattenedAffineExpr()
LogicalResult mlir::getFlattenedAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols, SmallVectorImpl< int64_t > * flattenedExpr, FlatAffineConstraints * cst = nullptr)
Flattens 'expr' into 'flattenedExpr', which contains the coefficients of the dimensions, symbols, and additional variables that represent floor divisions of dimensions, symbols, and in turn other floor divisions.
Returns failure if 'expr' could not be flattened (i.e., semi-affine is not yet handled). 'cst' contains constraints that connect newly introduced local identifiers to existing dimensional and symbolic identifiers. See documentation for AffineExprFlattener on how mod's and div's are flattened.
Definition at line 103 of file AffineStructures.cpp.
References getFlattenedAffineExprs().
Referenced by mlir::FlatAffineConstraints::setIdValues().
getFlattenedAffineExprs() [1/2]
LogicalResult mlir::getFlattenedAffineExprs (AffineMap map, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs, FlatAffineConstraints * localVarCst = nullptr)
Flattens the result expressions of the map to their corresponding flattened forms and set in 'flattenedExprs'.
Flattens the expressions in map.
Returns failure if any expression in the map could not be flattened (i.e., semi-affine is not yet handled). 'cst' contains constraints that connect newly introduced local identifiers to existing dimensional and / symbolic identifiers. See documentation for AffineExprFlattener on how mod's and div's are flattened. For all affine expressions that share the same operands (like those of an affine map), this method should be used instead of repeatedly calling getFlattenedAffineExpr since local variables added to deal with div's and mod's will be reused across expressions.
Returns failure if 'expr' was unable to be flattened (i.e., semi-affine expressions not handled yet).
Definition at line 116 of file AffineStructures.cpp.
References getFlattenedAffineExprs(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), mlir::FlatAffineConstraints::reset(), and success().
Referenced by mlir::FlatAffineConstraints::addLowerOrUpperBound(), addMemRefAccessConstraints(), mlir::FlatAffineConstraints::composeMap(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::FlatAffineConstraints::FlatAffineConstraints(), getFlattenedAffineExpr(), and mlir::FlatAffineConstraints::setIdValues().
getFlattenedAffineExprs() [2/2]
LogicalResult mlir::getFlattenedAffineExprs (IntegerSet set, std::vector< SmallVector< int64_t, 8 >> * flattenedExprs, FlatAffineConstraints * cst = nullptr)
Definition at line 128 of file AffineStructures.cpp.
References getFlattenedAffineExprs(), mlir::FlatAffineConstraints::reset(), and success().
getFlattenedTypes()
SmallVector< Type, 10 > mlir::getFlattenedTypes (TupleType t)
Get the types within a nested Tuple.
A helper for the class method that handles storage concerns, which is tricky to do in tablegen.
Definition at line 35 of file TypeUtilities.cpp.
References mlir::TupleType::getFlattenedTypes().
getForInductionVarOwner()
ForOp mlir::scf::getForInductionVarOwner (Value val)
Returns the loop parent of an induction variable.
If the provided value is not an induction variable, then return nullptr.
Definition at line 1903 of file AffineOps.cpp.
References mlir::Value::dyn_cast(), mlir::BlockArgument::getOwner(), mlir::Block::getParent(), and mlir::Region::getParentOp().
Referenced by mlir::FlatAffineConstraints::addInductionVarOrTerminalSymbol(), addMissingLoopIVBounds(), buildSliceTripCountMap(), mlir::MemRefRegion::compute(), mlir::FlatAffineConstraints::convertLoopIVSymbolsToDims(), fuseLoops(), mlir::ComputationSliceState::getAsConstraints(), getBackwardSliceImpl(), getCommonBlock(), getNumCommonLoops(), isForInductionVar(), and isOpLoopInvariant().
getForwardSlice()
void mlir::getForwardSlice (Operation * op, llvm::SetVector< Operation *> * forwardSlice, TransitiveFilter filter = [](Operation *) { return true;})
Fills forwardSlice with the computed forward slice (i.e.
all the transitive uses of op), without including that operation.
This additionally takes a TransitiveFilter which acts as a frontier: when looking at uses transitively, an operation that does not pass the filter is never propagated through. This allows in particular to carve out the scope within a ForInst or the scope within an IfInst.
The implementation traverses the use chains in postorder traversal for efficiency reasons: if an operation is already in forwardSlice, no need to traverse its uses again. Since use-def chains form a DAG, this terminates.
Upon return to the root call, forwardSlice is filled with a postorder list of uses (i.e. a reverse topological order). To get a proper topological order, we just just reverse the order in forwardSlice before returning.
Example starting from node 0
          0
___________|___________ 1 2 3 4 |_______| |______| | | | | 5 6 |___|_____________| | | 7 8 |_______________| | 9
Assuming all local orders match the numbering order:
after getting back to the root getForwardSlice, forwardSlice may contain: {9, 7, 8, 5, 1, 2, 6, 3, 4}
reversing the result of 1. gives: {4, 3, 6, 2, 1, 5, 8, 7, 9}
Referenced by getForwardSliceImpl(), getSlice(), hoistOpsBetween(), mlir::linalg::hoistRedundantVectorTransfers(), and vectorizeNonTerminals().
getFusionComputeCost()
bool mlir::getFusionComputeCost (AffineForOp srcForOp, LoopNestStats & srcStats, AffineForOp dstForOp, LoopNestStats & dstStats, const ComputationSliceState & slice, int64_t * computeCost)
Computes and returns in 'computeCost', the total compute cost of fusing the 'slice' of the loop nest rooted at 'srcForOp' into 'dstForOp'.
Currently, the total cost is computed by counting the total operation instance count (i.e. total number of operations in the loop body * loop trip count) for the entire loop nest. Returns true on success, failure otherwise (e.g. non-constant trip counts).
Currently, the total cost is computed by counting the total operation instance count (i.e. total number of operations in the loop body * loop trip count) for the entire loop nest.
Definition at line 565 of file LoopFusionUtils.cpp.
References buildSliceTripCountMap(), getComputeCostHelper(), getLoopIVs(), getSliceIterationCount(), and mlir::ComputationSliceState::insertPoint.
Referenced by isFusionProfitable().
getIndexingMapsAttrName()
constexpr StringRef mlir::getIndexingMapsAttrName ()
Attribute name for the AffineArrayAttr which encodes the relationship between a structured op iterators' and its operands.
Definition at line 51 of file StructuredOpsUtils.h.
Referenced by mlir::linalg::interchange(), print(), and verify().
getIndexSet()
LogicalResult mlir::getIndexSet (MutableArrayRef< Operation *> ops, FlatAffineConstraints * domain)
Builds a system of constraints with dimensional identifiers corresponding to the loop IVs of the forOps and AffineIfOp's operands appearing in that order.
Bounds of the loop are used to add appropriate inequalities. Constraints from the index sets of AffineIfOp are also added. Any symbols founds in the bound operands are added as symbols in the system. Returns failure for the yet unimplemented cases. ops accepts both AffineForOp and AffineIfOp.
Definition at line 88 of file AffineAnalysis.cpp.
References mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addAffineIfOpDomain(), extractForInductionVars(), failed(), failure(), mlir::FlatAffineConstraints::reset(), and success().
Referenced by checkIfHyperRectangular(), createFullTiles(), createSeparationCondition(), and getOpIndexSet().
getInnermostCommonLoopDepth()
unsigned mlir::getInnermostCommonLoopDepth (ArrayRef< Operation *> ops, SmallVectorImpl< AffineForOp > * surroundingLoops = nullptr)
Returns the innermost common loop depth for the set of operations in 'ops'.
Definition at line 568 of file Utils.cpp.
References getLoopIVs().
Referenced by computeSliceUnion(), getMaxLoopDepth(), and isFusionProfitable().
getInvariantAccesses()
DenseSet< Value > mlir::getInvariantAccesses (Value iv, ArrayRef< Value > indices)
Given an induction variable iv of type AffineForOp and indices of type IndexType, returns the set of indices that are independent of iv.
Prerequisites (inherited from isAccessInvariant above):
iv and indices of the proper type;
at most one affine.apply is reachable from each index in indices;
Emits a note if it encounters a chain of affine.apply and conservatively those cases.
Definition at line 187 of file LoopAnalysis.cpp.
References isAccessIndexInvariant().
Referenced by makePermutationMap().
getIteratorTypesAttrName()
constexpr StringRef mlir::getIteratorTypesAttrName ()
Attribute name for the StrArrayAttr which encodes the type of a structured op's iterators.
Definition at line 55 of file StructuredOpsUtils.h.
Referenced by mlir::linalg::interchange(), print(), and verify().
getLargestDivisorOfTripCount()
uint64_t mlir::getLargestDivisorOfTripCount (AffineForOp forOp)
Returns the greatest known integral divisor of the trip count.
Affine expression analysis is used (indirectly through getTripCount), and this method is thus able to determine non-trivial divisors.
Definition at line 113 of file LoopAnalysis.cpp.
References buildTripCountMapAndOperands(), mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResults().
Referenced by constructTiledIndexSetHyperRect(), loopUnrollByFactor(), and loopUnrollJamByFactor().
getLibraryCallAttrName()
constexpr StringRef mlir::getLibraryCallAttrName ()
Attribute name for the StrArrayAttr which encodes the external library function that implements the structured op.
Definition at line 63 of file StructuredOpsUtils.h.
getLoopIVs()
void mlir::getLoopIVs (Operation & op, SmallVectorImpl< AffineForOp > * loops)
Populates 'loops' with IVs of the loops surrounding 'op' ordered from the outermost 'affine.for' operation to the innermost one.
Definition at line 33 of file Utils.cpp.
References mlir::Operation::getParentOp().
Referenced by mlir::MemRefRegion::compute(), findHighestBlockForPlacement(), getComputationSliceState(), getFullMemRefAsRegion(), getFusionComputeCost(), getInnermostCommonLoopDepth(), getLastDependentOpInRange(), getNumCommonSurroundingLoops(), insertBackwardComputationSlice(), isFusionProfitable(), isMemRefDereferencingOp(), and isOpLoopInvariant().
getLoopNestStats()
bool mlir::getLoopNestStats (AffineForOp forOpRoot, LoopNestStats * stats)
Collect loop nest statistics (eg.
loop trip count and operation count) in 'stats' for loop nest rooted at 'forOp'. Returns true on success, returns false otherwise.
Definition at line 402 of file LoopFusionUtils.cpp.
References mlir::WalkResult::advance(), getConstantTripCount(), mlir::WalkResult::interrupt(), mlir::LoopNestStats::loopMap, mlir::LoopNestStats::opCountMap, and mlir::LoopNestStats::tripCountMap.
Referenced by isFusionProfitable().
getMemoryFootprintBytes()
Optional< int64_t > mlir::getMemoryFootprintBytes (AffineForOp forOp, int memorySpace = -1)
Gets the memory footprint of all data touched in the specified memory space in bytes; if the memory space is unspecified, considers all memory spaces.
Definition at line 1033 of file Utils.cpp.
References getMemoryFootprintBytes().
Referenced by adjustToDivisorsOfTripCounts(), createAffineDataCopyGenerationPass(), and isFusionProfitable().
getMemRefSizeInBytes()
Optional< uint64_t > mlir::getMemRefSizeInBytes (MemRefType memRefType)
Returns the size of memref data in bytes if it's statically shaped, None otherwise.
If the element of the memref has vector type, takes into account size of the vector as well.
Definition at line 433 of file Utils.cpp.
References mlir::FlatAffineConstraints::addConstantUpperBound(), boundCheckLoadOrStoreOp(), emitError(), failed(), failure(), mlir::Operation::getLoc(), getMemRefEltSizeInBytes(), and success().
Referenced by generateCopy().
getNestingDepth()
unsigned mlir::getNestingDepth (Operation * op)
Returns the nesting depth of this operation, i.e., the number of loops surrounding this operation.
Returns the nesting depth of this statement, i.e., the number of loops surrounding this statement.
Definition at line 944 of file Utils.cpp.
References mlir::Operation::getParentOp().
Referenced by affineDataCopyGenerate(), computeSliceUnion(), createMemRefDataFlowOptPass(), getMemoryFootprintBytes(), isFusionProfitable(), and isLoopParallel().
getNumCommonSurroundingLoops()
unsigned mlir::getNumCommonSurroundingLoops (Operation & A, Operation & B)
Returns the number of surrounding loops common to both A and B.
Returns the number of surrounding loops common to 'loopsA' and 'loopsB', where each lists loops from outer-most to inner-most in loop nest.
Definition at line 974 of file Utils.cpp.
References getLoopIVs().
Referenced by canFuseLoops(), createMemRefDataFlowOptPass(), and getMaxLoopDepth().
getNumIterators() [1/2]
unsigned mlir::getNumIterators (StringRef name, ArrayAttr iteratorTypes) inline
Returns the iterator of a certain type.
Definition at line 107 of file StructuredOpsUtils.h.
References mlir::Attribute::cast(), and getAllIteratorTypeNames().
Referenced by getNumIterators().
getNumIterators() [2/2]
unsigned mlir::getNumIterators (ArrayAttr iteratorTypes) inline
Definition at line 116 of file StructuredOpsUtils.h.
References getAllIteratorTypeNames(), and getNumIterators().
getOrCreateRanges()
SmallVector< Range, 8 > mlir::getOrCreateRanges (OffsetSizeAndStrideOpInterface op, OpBuilder & b, Location loc)
Return the list of Range (i.e.
offset, size, stride). Each Range entry contains either the dynamic value or a ConstantIndexOp constructed with b at location loc.
Definition at line 3316 of file Ops.cpp.
References mlir::OpBuilder::create(), extractFromI64ArrayAttr(), failure(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), m_ConstantIndex(), matchPattern(), mlir::PatternRewriter::replaceOpWithNewOp(), and success().
getPaddingAttrName()
constexpr StringRef mlir::getPaddingAttrName ()
Attribute name for the StrArrayAttr which encodes the value of paddings.
Definition at line 75 of file StructuredOpsUtils.h.
getParallelIteratorTypeName()
constexpr StringRef mlir::getParallelIteratorTypeName ()
Use to encode that a particular iterator type has parallel semantics.
Definition at line 78 of file StructuredOpsUtils.h.
Referenced by collectFusableLoops(), fuseWithReshapeByExpansion(), getAllIteratorTypeNames(), getDimMap(), isElementwiseMappableOpOnRankedTensors(), isFusableWithReshapeByDimExpansion(), isParallelIterator(), mlir::linalg::isParallelIteratorType(), replaceBlockArgForUnitDimLoops< IndexedGenericOp >(), and toString().
getPerfectlyNestedLoops() [1/2]
void mlir::getPerfectlyNestedLoops (SmallVectorImpl< AffineForOp > & nestedLoops, AffineForOp root)
Get perfectly nested sequence of loops starting at root of loop nest (the first op being another AffineFor, and the second op - a terminator).
A loop is perfectly nested iff: the first op in the loop's body is another AffineForOp, and the second op is a terminator).
Definition at line 1006 of file LoopUtils.cpp.
References getPerfectlyNestedLoopsImpl().
Referenced by getTileableBands(), and sinkSequentialLoops().
getPerfectlyNestedLoops() [2/2]
void mlir::getPerfectlyNestedLoops (SmallVectorImpl< scf::ForOp > & nestedLoops, scf::ForOp root)
Definition at line 1011 of file LoopUtils.cpp.
References getPerfectlyNestedLoopsImpl().
getProjectedMap()
AffineMap mlir::getProjectedMap (AffineMap map, ArrayRef< unsigned > projectedDimensions)
Definition at line 458 of file AffineMap.cpp.
References mlir::AffineMap::compose(), mlir::detail::enumerate(), mlir::AffineMap::get(), getAffineConstantExpr(), getAffineDimExpr(), mlir::AffineMap::getContext(), and mlir::AffineMap::getNumDims().
Referenced by mlir::MutableAffineMap::getContext(), and pruneReductionDimsFromMap().
getReachableAffineApplyOps()
void mlir::getReachableAffineApplyOps (ArrayRef< Value > operands, SmallVectorImpl< Operation *> & affineApplyOps)
Returns in affineApplyOps, the sequence of those AffineApplyOp Operations that are reachable via a search starting from operands and ending at those operands that are not the result of an AffineApplyOp.
Returns the sequence of AffineApplyOp Operations operation in 'affineApplyOps', which are reachable via a search starting from 'operands', and ending at operands which are not defined by AffineApplyOps.
Definition at line 38 of file AffineAnalysis.cpp.
Referenced by createAffineComputationSlice(), findMatchingStartFinishInsts(), and isAccessIndexInvariant().
getReductionIteratorTypeName()
constexpr StringRef mlir::getReductionIteratorTypeName ()
Use to encode that a particular iterator type has reduction semantics.
Definition at line 85 of file StructuredOpsUtils.h.
Referenced by getAllIteratorTypeNames(), getDimMap(), isReductionIterator(), mlir::linalg::isReductionIteratorType(), and toString().
getSequentialLoops()
void mlir::getSequentialLoops (AffineForOp forOp, llvm::SmallDenseSet< Value, 8 > * sequentialLoops)
Returns in 'sequentialLoops' all sequential loops in loop nest rooted at 'forOp'.
Definition at line 1043 of file Utils.cpp.
References isLoopParallel().
Referenced by getComputationSliceState().
getSlice()
SetVector< Operation * > mlir::getSlice (Operation * op, TransitiveFilter backwardFilter = [](Operation *) { return true; }, TransitiveFilter forwardFilter = [](Operation *) { return true; })
Iteratively computes backward slices and forward slices until a fixed point is reached.
Returns an llvm::SetVector<Operation *> which includes the original operation.
This allows building a slice (i.e. multi-root DAG where everything that is reachable from an Value in forward and backward direction is contained in the slice). This is the abstraction we need to materialize all the operations for supervectorization without worrying about orderings and Value replacements.
Example starting from any node
1 2 3 4 |_______| |______| | | | | | 5 6___| |___|_____________| | | | | 7 8 | |_______________| | | | 9 10
Return the whole DAG in some topological order.
The implementation works by just filling up a worklist with iterative alternate calls to getBackwardSlice and getForwardSlice.
The following section describes some additional implementation considerations for a potentially more efficient implementation but they are just an intuition without proof, we still use a worklist for now.
Additional implementation considerations
Consider the defs-op-uses hourglass.
\ / defs (in some topological order) \/ op /\ / \ uses (in some topological order) /____\
We want to iteratively apply getSlice to construct the whole list of Operation that are reachable by (use|def)+ from op. We want the resulting slice in topological order. Ideally we would like the ordering to be maintained in-place to avoid copying Operation at each step. Keeping this ordering by construction seems very unclear, so we list invariants in the hope of seeing whether useful properties pop up.
In the following: we use |= for set inclusion; we use << for set topological ordering (i.e. each pair is ordered).
Assumption:
We wish to maintain the following property by a recursive argument: """ defs << {op} <<uses are in topological order. """ The property clearly holds for 0 and 1-sized uses and defs;
Invariants:
defs and uses are in topological order internally, by construction;
for any {x} |= defs, defs(x) |= defs; because all go through op
for any {x} |= uses, defs |= defs(x); because all go through op
for any {x} |= defs, uses |= uses(x); because all go through op
for any {x} |= uses, uses(x) |= uses; because all go through op
Intuitively, we should be able to recurse like: preorder(defs) - op - postorder(uses) and keep things ordered but this is still hand-wavy and not worth the trouble for now: punt to a simple worklist-based solution.
Definition at line 136 of file SliceAnalysis.cpp.
References getBackwardSlice(), getForwardSlice(), and topologicalSort().
getSparseAttrName()
constexpr StringRef mlir::getSparseAttrName ()
Attribute name for the ArrayAttr of StrArrayAttr that encodes sparsity.
Definition at line 66 of file StructuredOpsUtils.h.
getSparseDimName()
constexpr StringRef mlir::getSparseDimName ()
Use to encode a dense or sparse dimension.
Definition at line 137 of file StructuredOpsUtils.h.
Referenced by isSparseDim().
getStridesAndOffset() [1/2]
LogicalResult mlir::getStridesAndOffset (MemRefType t, SmallVectorImpl< int64_t > & strides, int64_t & offset)
Returns the strides of the MemRef if the layout map is in strided form.
MemRefs with layout maps in strided form include:
empty or identity layout map, in which case the stride information is the canonical form computed from sizes;
single affine map layout of the form K + k0 * d0 + ... kn * dn, where K and ki's are constants or symbols.
A stride specification is a list of integer values that are either static or dynamic (encoded with getDynamicStrideOrOffset()). Strides encode the distance in the number of elements between successive entries along a particular dimension. For example, memref<42x16xf32, (64 * d0 + d1)> specifies a view into a non-contiguous memory region of 42 by 16 f32 elements in which the distance between two consecutive elements along the outer dimension is 1 and the distance between two consecutive elements along the inner dimension is 64.
Returns whether a simple strided form can be extracted from the composition of the layout map.
The convention is that the strides for dimensions d0, .. dn appear in order to make indexing intuitive into the result.
Definition at line 671 of file BuiltinTypes.cpp.
References mlir::AffineExpr::dyn_cast(), failed(), failure(), mlir::ShapedType::kDynamicStrideOrOffset, and success().
Referenced by canFoldIntoConsumerOp(), computeReshapeCollapsedType(), convertRangeType(), mlir::MemRefDescriptor::fromStaticShape(), getBase(), getCastCompatibleMemRefType(), mlir::spirv::getElementPtr(), mlir::ConvertToLLVMPattern::getStridedElementPtr(), getTransferOpAdapter(), getTypeNumBytes(), inferTransposeResultType(), isRankReducedType(), isStrided(), mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
getStridesAndOffset() [2/2]
LogicalResult mlir::getStridesAndOffset (MemRefType t, SmallVectorImpl< AffineExpr > & strides, AffineExpr & offset)
In practice, a strided memref must be internally non-aliasing. Test against 0 as a proxy. TODO: static cases can have more advanced checks. TODO: dynamic cases would require a way to compare symbolic expressions and would probably need an affine set context propagated everywhere.
Definition at line 602 of file BuiltinTypes.cpp.
References extractStrides(), failed(), failure(), getAffineConstantExpr(), mlir::MemRefType::getAffineMaps(), mlir::AffineExpr::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResult(), mlir::MemRefType::getShape(), mlir::AffineMap::isIdentity(), makeCanonicalStridedLayoutExpr(), simplifyAffineExpr(), succeeded(), and success().
Referenced by mlir::TensorType::classof().
getStridesAttrName()
constexpr StringRef mlir::getStridesAttrName ()
Attribute name for the StrArrayAttr which encodes the value of strides.
Definition at line 69 of file StructuredOpsUtils.h.
Referenced by foldExtractFromShapeCast(), inferStridedSliceOpResultType(), and verify().
getTileableBands()
void mlir::getTileableBands (FuncOp f, std::vector< SmallVector< AffineForOp, 6 >> * bands)
Identify valid and profitable bands of loops to tile.
This is currently just a temporary placeholder to test the mechanics of tiled code generation. Returns all maximal outermost perfect loop nests to tile.
Definition at line 1019 of file LoopUtils.cpp.
References getPerfectlyNestedLoops().
Referenced by adjustToDivisorsOfTripCounts().
getUsedValuesDefinedAbove() [1/2]
void mlir::getUsedValuesDefinedAbove (Region & region, Region & limit, llvm::SetVector< Value > & values)
Fill values with a list of values defined at the ancestors of the limit region and used within region or its descendants.
Definition at line 58 of file RegionUtils.cpp.
References mlir::OpOperand::get(), and visitUsedValuesDefinedAbove().
Referenced by areValuesDefinedAbove(), getUsedValuesDefinedAbove(), outlineExecuteOp(), outlineIfOp(), outlineKernelFuncImpl(), and sinkOperationsIntoLaunchOp().
getUsedValuesDefinedAbove() [2/2]
void mlir::getUsedValuesDefinedAbove (MutableArrayRef< Region > regions, llvm::SetVector< Value > & values)
Fill values with a list of values used within any of the regions provided but defined in one of the ancestors.
Definition at line 65 of file RegionUtils.cpp.
References getUsedValuesDefinedAbove().
getWindowIteratorTypeName()
constexpr StringRef mlir::getWindowIteratorTypeName ()
Use to encode that a particular iterator type has window semantics.
Definition at line 92 of file StructuredOpsUtils.h.
Referenced by getAllIteratorTypeNames(), isWindowIterator(), and mlir::linalg::isWindowIteratorType().
greedilyMapParallelSCFToGPU()
void mlir::greedilyMapParallelSCFToGPU (Region & region)
Maps the parallel loops found in the given function to workgroups.
The first loop encountered will be mapped to the global workgroup and the second loop encountered to the local workgroup. Within each mapping, the first three dimensions are mapped to x/y/z hardware ids and all following dimensions are mapped to sequential loops.
Definition at line 148 of file ParallelLoopMapper.cpp.
References mapParallelOp(), and mlir::Region::walk().
Referenced by mlir::gpu::getProcessor().
hasDependence()
bool mlir::hasDependence (DependenceResult result) inline
Utility function that returns true if the provided DependenceResult corresponds to a dependence result.
Definition at line 120 of file AffineAnalysis.h.
References getDependenceComponents(), mlir::DependenceResult::HasDependence, and mlir::DependenceResult::value.
Referenced by checkTilingLegalityImpl(), createMemRefDataFlowOptPass(), getDependenceComponents(), and getMaxLoopDepth().
hash_value() [1/12]
inline ::llvm::hash_code mlir::hash_value (TypeRange arg)
Make TypeRange hashable.
Definition at line 79 of file TypeRange.h.
hash_value() [2/12]
inline ::llvm::hash_code mlir::hash_value (TypeID id)
Enable hashing TypeID.
Definition at line 96 of file TypeID.h.
hash_value() [3/12]
llvm::hash_code mlir::hash_value (Identifier arg) inline
Definition at line 97 of file Identifier.h.
References mlir::Identifier::getAsOpaquePointer().
hash_value() [4/12]
inline ::llvm::hash_code mlir::hash_value (IntegerSet arg)
Definition at line 114 of file IntegerSet.h.
hash_value() [5/12]
inline ::llvm::hash_code mlir::hash_value (Attribute arg)
Definition at line 119 of file Attributes.h.
References mlir::Attribute::impl.
hash_value() [6/12]
inline ::llvm::hash_code mlir::hash_value (AffineExpr arg)
Make AffineExpr hashable.
Definition at line 219 of file AffineExpr.h.
References mlir::AffineExpr::expr.
Referenced by mlir::Location::dump(), mlir::MutableDictionaryAttr::empty(), mlir::TypeID::getFromOpaquePointer(), mlir::Value::getFromOpaquePointer(), llvm::DenseMapInfo< mlir::FuncOp >::getHashValue(), llvm::DenseMapInfo< mlir::Identifier >::getHashValue(), llvm::DenseMapInfo< mlir::IntegerSet >::getHashValue(), llvm::DenseMapInfo< mlir::TypeRange >::getHashValue(), llvm::DenseMapInfo< mlir::TypeID >::getHashValue(), llvm::DenseMapInfo< mlir::Attribute >::getHashValue(), llvm::DenseMapInfo< mlir::Type >::getHashValue(), llvm::DenseMapInfo< mlir::Location >::getHashValue(), llvm::DenseMapInfo< mlir::AffineExpr >::getHashValue(), llvm::DenseMapInfo< mlir::AffineMap >::getHashValue(), llvm::DenseMapInfo< mlir::Value >::getHashValue(), llvm::DenseMapInfo< mlir::BlockArgument >::getHashValue(), llvm::DenseMapInfo< mlir::LLVM::LLVMType >::getHashValue(), hash_value(), mlir::AffineExpr::operator!(), mlir::AffineMap::operator!=(), and mlir::IntegerSet::operator==().
hash_value() [7/12]
inline ::llvm::hash_code mlir::hash_value (AffineMap arg)
Definition at line 219 of file AffineMap.h.
hash_value() [8/12]
inline ::llvm::hash_code mlir::hash_value (Type arg)
Definition at line 220 of file Types.h.
References mlir::Type::impl.
hash_value() [9/12]
inline ::llvm::hash_code mlir::hash_value (Location arg)
Definition at line 264 of file Location.h.
References hash_value(), and mlir::Location::impl.
hash_value() [10/12]
inline ::llvm::hash_code mlir::hash_value (Value arg)
Make Value hashable.
Definition at line 346 of file Value.h.
References mlir::Value::ownerAndKind.
hash_value() [11/12]
llvm::hash_code mlir::hash_value (OperationName arg) inline
Definition at line 377 of file OperationSupport.h.
References mlir::OperationName::getAsOpaquePointer().
hash_value() [12/12]
inline ::llvm::hash_code mlir::hash_value (const MutableDictionaryAttr & arg)
Definition at line 1538 of file BuiltinAttributes.h.
References hash_value().
hoistAffineIfOp()
LogicalResult mlir::hoistAffineIfOp (AffineIfOp ifOp, bool * folded = nullptr)
Hoists out affine.if/else to as high as possible, i.e., past all invariant affine.fors/parallel's.
Returns success if any hoisting happened; folded` is set to true if the op was folded or erased. This hoisting could lead to significant code expansion in some cases.
Definition at line 180 of file Utils.cpp.
References applyOpPatternsAndFold(), applyPatternsAndFoldGreedily(), failure(), getOutermostInvariantForOp(), isForInductionVar(), isTopLevelValue(), and success().
initializeLLVMPasses()
void mlir::initializeLLVMPasses ()
Initialize LLVM passes that can be used when running MLIR code using ExecutionEngine.
Definition at line 47 of file OptUtils.cpp.
inlineCall()
LogicalResult mlir::inlineCall (InlinerInterface & interface, CallOpInterface call, CallableOpInterface callable, Region * src, bool shouldCloneInlinedRegion = true)
This function inlines a given region, 'src', of a callable operation, 'callable', into the location defined by the given call operation.
This function returns failure if inlining is not possible, success otherwise. On failure, no changes are made to the module. 'shouldCloneInlinedRegion' corresponds to whether the source region should be cloned into the 'call' or spliced directly.
Definition at line 297 of file InliningUtils.cpp.
References mlir::Region::empty(), failed(), failure(), mlir::Region::front(), mlir::Value::getDefiningOp(), mlir::DialectInterfaceCollection< InterfaceType >::getInterfaceFor(), mlir::Value::getType(), mlir::BlockArgument::getType(), inlineRegion(), mlir::InlinerInterface::isLegalToInline(), mlir::BlockAndValueMapping::map(), materializeConversion(), mlir::Value::replaceAllUsesWith(), mlir::Operation::replaceUsesOfWith(), mlir::OpBuilder::setInsertionPointAfter(), and success().
Referenced by inlineCallsInSCC(), and mlir::InlinerInterface::processInlinedBlocks().
inlineRegion() [1/2]
LogicalResult mlir::inlineRegion (InlinerInterface & interface, Region * src, Operation * inlinePoint, BlockAndValueMapping & mapper, ValueRange resultsToReplace, TypeRange regionResultTypes, Optional< Location > inlineLoc = llvm::None, bool shouldCloneInlinedRegion = true)
This function inlines a region, 'src', into another.
This function returns failure if it is not possible to inline this function. If the function returned failure, then no changes to the module have been made.
The provided 'inlinePoint' must be within a region, and corresponds to the location where the 'src' region should be inlined. 'mapping' contains any remapped operands that are used within the region, and must include remappings for the entry arguments to the region. 'resultsToReplace' corresponds to any results that should be replaced by terminators within the inlined region. 'regionResultTypes' specifies the expected return types of the terminators in the region. 'inlineLoc' is an optional Location that, if provided, will be used to update the inlined operations' location information. 'shouldCloneInlinedRegion' corresponds to whether the source region should be cloned into the 'inlinePoint' or spliced directly.
Handle the terminators for each of the new blocks.
Definition at line 140 of file InliningUtils.cpp.
References mlir::Block::addArgument(), mlir::Region::begin(), mlir::Block::begin(), mlir::Region::cloneInto(), mlir::BlockAndValueMapping::contains(), mlir::Region::empty(), mlir::Region::end(), mlir::Block::end(), mlir::detail::enumerate(), mlir::Block::erase(), failure(), mlir::Region::front(), mlir::Operation::getBlock(), mlir::Region::getBlocks(), mlir::Block::getOperations(), mlir::Block::getParent(), mlir::InlinerInterface::handleTerminator(), mlir::InlinerInterface::isLegalToInline(), mlir::InlinerInterface::processInlinedBlocks(), remapInlinedLocations(), remapInlinedOperands(), mlir::Block::splitBlock(), and success().
Referenced by inlineCall(), inlineRegion(), and mlir::InlinerInterface::processInlinedBlocks().
inlineRegion() [2/2]
LogicalResult mlir::inlineRegion (InlinerInterface & interface, Region * src, Operation * inlinePoint, ValueRange inlinedOperands, ValueRange resultsToReplace, Optional< Location > inlineLoc = llvm::None, bool shouldCloneInlinedRegion = true)
This function is an overload of the above 'inlineRegion' that allows for providing the set of operands ('inlinedOperands') that should be used in-favor of the region arguments when inlining.
Definition at line 238 of file InliningUtils.cpp.
References mlir::Region::empty(), failure(), mlir::Region::front(), mlir::BlockArgument::getType(), mlir::ValueRange::getTypes(), inlineRegion(), and mlir::BlockAndValueMapping::map().
insertBackwardComputationSlice()
AffineForOp mlir::insertBackwardComputationSlice (Operation * srcOpInst, Operation * dstOpInst, unsigned dstLoopDepth, ComputationSliceState * sliceState)
Creates a clone of the computation contained in the loop nest surrounding 'srcOpInst', slices the iteration space of src loop based on slice bounds in 'sliceState', and inserts the computation slice at the beginning of the operation block of the loop at 'dstLoopDepth' in the loop nest surrounding 'dstOpInst'.
Creates a computation slice of the loop nest surrounding 'srcOpInst', updates the slice loop bounds with any non-null bound maps specified in 'sliceState', and inserts this slice into the loop nest surrounding 'dstOpInst' at loop depth 'dstLoopDepth'.
Returns the top-level loop of the computation slice on success, returns nullptr otherwise.
Definition at line 855 of file Utils.cpp.
References mlir::Operation::emitError(), findInstPosition(), getInstAtPosition(), getLoopIVs(), mlir::ComputationSliceState::lbOperands, mlir::ComputationSliceState::lbs, mlir::ComputationSliceState::ubOperands, and mlir::ComputationSliceState::ubs.
Referenced by mlir::ComputationSliceState::isEmpty().
interchangeLoops()
void mlir::interchangeLoops (AffineForOp forOpA, AffineForOp forOpB)
Performs loop interchange on 'forOpA' and 'forOpB'.
Performs loop interchange on 'forOpA' and 'forOpB', where 'forOpB' is nested within 'forOpA' as the only non-terminator operation in its block.
Requires that 'forOpA' and 'forOpB' are part of a perfectly nested sequence of loops.
Definition at line 1404 of file LoopUtils.cpp.
inversePermutation()
AffineMap mlir::inversePermutation (AffineMap map)
Returns a map of codomain to domain dimensions such that the first codomain dimension for a particular domain dimension is selected.
Returns an empty map if the input map is empty. Returns null map (not empty map) if map is not invertible (i.e. map does not contain a subset that is a permutation of full domain rank).
Prerequisites:
map has no symbols.
Example 1:
(d0, d1, d2) -> (d1, d1, d0, d2, d1, d2, d1, d0)
                  0       2   3
returns:
(d0, d1, d2, d3, d4, d5, d6, d7) -> (d2, d0, d3)
Example 2:
(d0, d1, d2) -> (d1, d0 + d1, d0, d2, d1, d2, d1, d0)
                  0            2   3
returns:
(d0, d1, d2, d3, d4, d5, d6, d7) -> (d2, d0, d3)
Definition at line 417 of file AffineMap.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::detail::enumerate(), mlir::AffineMap::get(), getAffineDimExpr(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and mlir::AffineMap::isEmpty().
Referenced by foldExtractOpFromTranspose(), fuseTensorOpsImpl(), fuseWithReshapeByExpansion(), getConsumerLoopToProducerLoopMap(), mlir::MutableAffineMap::getContext(), getIndexingMapOfProducerOperandsInFusedOp(), mlir::linalg::interchange(), mlir::linalg::interchangeGenericLinalgOpPrecondition(), replaceBlockArgForUnitDimLoops< IndexedGenericOp >(), replaceUnitDims(), replaceUnitExtents(), and tileLinalgOpImpl().
isColumnMajorMatmul()
bool mlir::isColumnMajorMatmul (ArrayAttr indexingMaps) inline
Definition at line 38 of file StructuredOpsUtils.h.
References bindDims(), mlir::AffineMap::get(), mlir::AffineMapAttr::get(), and mlir::ArrayAttr::get().
isDenseDim()
bool mlir::isDenseDim (Attribute attr) inline
Definition at line 143 of file StructuredOpsUtils.h.
References mlir::Attribute::dyn_cast_or_null(), getDenseDimName(), and mlir::StringAttr::getValue().
Referenced by findSparseAnnotations(), and getGenericEffectsImpl().
isForInductionVar()
bool mlir::isForInductionVar (Value val)
Returns true if the provided value is the induction variable of a AffineForOp.
Definition at line 1897 of file AffineOps.cpp.
References getForInductionVarOwner().
Referenced by mlir::FlatAffineConstraints::addInductionVarOrTerminalSymbol(), addMemRefAccessConstraints(), addMissingLoopIVBounds(), buildDimAndSymbolPositionMaps(), getNumCommonLoops(), hoistAffineIfOp(), initDependenceConstraints(), and isAccessIndexInvariant().
isLoopParallel()
bool mlir::isLoopParallel (AffineForOp forOp)
Returns true if `forOp' is a parallel loop.
Returns true if 'forOp' is parallel.
Definition at line 1053 of file Utils.cpp.
References mlir::WalkResult::advance(), checkMemrefAccessDependence(), getNestingDepth(), mlir::WalkResult::interrupt(), mlir::DependenceResult::NoDependence, and mlir::DependenceResult::value.
Referenced by createSuperVectorizePass(), and getSequentialLoops().
isOpaqueTypeWithName()
bool mlir::isOpaqueTypeWithName (Type type, StringRef dialect, StringRef typeData)
Return true if the specified type is an opaque type with the specified dialect and typeData.
Definition at line 43 of file TypeUtilities.cpp.
References mlir::Type::dyn_cast().
isOpTriviallyDead()
bool mlir::isOpTriviallyDead (Operation * op)
Return true if the given operation is unused, and has no side effects on memory that prevent erasing.
Definition at line 32 of file SideEffectInterfaces.cpp.
References mlir::Operation::use_empty(), and wouldOpBeTriviallyDead().
Referenced by applyPatternsAndFoldGreedily(), and convertPDLToPDLInterp().
isOpwiseShiftValid()
bool mlir::isOpwiseShiftValid (AffineForOp forOp, ArrayRef< uint64_t > shifts)
Checks where SSA dominance would be violated if a for op's body operations are shifted by the specified shifts.
Checks whether SSA dominance would be violated if a for op's body operations are shifted by the specified shifts.
This method checks if a 'def' and all its uses have the same shift factor.
Definition at line 361 of file LoopAnalysis.cpp.
References mlir::detail::enumerate(), and mlir::Value::getUsers().
Referenced by affineForOpBodySkew(), and findMatchingStartFinishInsts().
isParallelIterator()
bool mlir::isParallelIterator (Attribute attr) inline
Definition at line 79 of file StructuredOpsUtils.h.
References mlir::Attribute::dyn_cast_or_null(), getParallelIteratorTypeName(), and mlir::StringAttr::getValue().
Referenced by mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), mlir::ContractionOpToDotLowering::matchAndRewrite(), and pruneReductionDimsFromMap().
isPerfectlyNested()
bool LLVM_ATTRIBUTE_UNUSED mlir::isPerfectlyNested (ArrayRef< AffineForOp > loops)
Returns true if loops is a perfectly nested loop nest, where loops appear in it from outermost to innermost.
Definition at line 1476 of file LoopUtils.cpp.
Referenced by performPreTilingChecks(), and permuteLoops().
isReductionIterator()
bool mlir::isReductionIterator (Attribute attr) inline
Definition at line 86 of file StructuredOpsUtils.h.
References mlir::Attribute::dyn_cast_or_null(), getReductionIteratorTypeName(), and mlir::StringAttr::getValue().
Referenced by mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), and mlir::ContractionOpToDotLowering::matchAndRewrite().
isRowMajorMatmul()
bool mlir::isRowMajorMatmul (ArrayAttr indexingMaps) inline
Definition at line 27 of file StructuredOpsUtils.h.
References bindDims(), mlir::AffineMap::get(), mlir::AffineMapAttr::get(), and mlir::ArrayAttr::get().
Referenced by mlir::ContractionOpToMatmulOpLowering::matchAndRewrite().
isSparseDim()
bool mlir::isSparseDim (Attribute attr) inline
Definition at line 138 of file StructuredOpsUtils.h.
References mlir::Attribute::dyn_cast_or_null(), getSparseDimName(), and mlir::StringAttr::getValue().
Referenced by findSparseAnnotations(), and getGenericEffectsImpl().
isStrided()
bool mlir::isStrided (MemRefType t)
Return true if the layout for t is compatible with strided semantics.
Definition at line 838 of file BuiltinTypes.cpp.
References getStridesAndOffset(), and succeeded().
Referenced by mlir::TensorType::classof(), getMemRefSizes(), mlir::DmaStartOp::getNumElementsPerStride(), mlir::DmaStartOp::getStride(), mlir::AffineDmaStartOp::parse(), mlir::DmaStartOp::parse(), mlir::AffineDmaStartOp::print(), mlir::DmaStartOp::print(), mlir::DmaStartOp::verify(), and verify().
isTopLevelValue()
bool mlir::isTopLevelValue (Value value)
A utility function to check if a value is defined at the top level of an op with trait AffineScope or is a region argument for such an op.
A utility function to check if a value is defined at the top level of an op with trait AffineScope.
A value of index type defined at the top level is always a valid symbol for all its uses.
If the value is defined in an unlinked region, conservatively assume it is not top-level. A value of index type defined at the top level is always a valid symbol.
Definition at line 225 of file AffineOps.cpp.
References mlir::Value::dyn_cast(), mlir::Value::getDefiningOp(), mlir::Operation::getParentOp(), and mlir::Operation::hasTrait().
Referenced by mlir::FlatAffineConstraints::addInductionVarOrTerminalSymbol(), hoistAffineIfOp(), isDimOpValidSymbol(), isValidDim(), isValidSymbol(), and remainsLegalAfterInline().
isValidDim() [1/2]
bool mlir::isValidDim (Value value)
Returns true if the given Value can be used as a dimension id in the region of the closest surrounding op that has the trait AffineScope.
Definition at line 256 of file AffineOps.cpp.
References mlir::Value::cast(), getAffineScope(), mlir::Value::getDefiningOp(), mlir::Value::getType(), and mlir::Type::isIndex().
Referenced by categorizeValueByAffineType(), mlir::AffineDmaWaitOp::getTagMapAttrName(), isValidAffineIndexOperand(), remainsLegalAfterInline(), replaceAllMemRefUsesWith(), verify(), and verifyDimAndSymbolIdentifiers().
isValidDim() [2/2]
bool mlir::isValidDim (Value value, Region * region)
Returns true if the given Value can be used as a dimension id in region, i.e., for all its uses in region.
Definition at line 276 of file AffineOps.cpp.
References mlir::Value::cast(), mlir::Value::getDefiningOp(), mlir::Value::getType(), mlir::Type::isIndex(), isTopLevelValue(), and isValidSymbol().
isValidLoopInterchangePermutation()
bool mlir::isValidLoopInterchangePermutation (ArrayRef< AffineForOp > loops, ArrayRef< unsigned > loopPermMap)
Checks if the loop interchange permutation 'loopPermMap', of the perfectly nested sequence of loops in 'loops', would violate dependences (loop 'i' in 'loops' is mapped to location 'j = 'loopPermMap[i]' in the interchange).
Checks if the loop interchange permutation 'loopPermMap' of the perfectly nested sequence of loops in 'loops' would violate dependences.
Definition at line 1462 of file LoopUtils.cpp.
References checkLoopInterchangeDependences(), and getDependenceComponents().
isValidSymbol() [1/2]
bool mlir::isValidSymbol (Value value)
Returns true if the given value can be used as a symbol in the region of the closest surrounding op that has the trait AffineScope.
Definition at line 351 of file AffineOps.cpp.
References getAffineScope(), mlir::Value::getDefiningOp(), mlir::Value::getType(), mlir::Type::isIndex(), and isTopLevelValue().
Referenced by addMemRefAccessConstraints(), buildDimAndSymbolPositionMaps(), canonicalizePromotedSymbols(), categorizeValueByAffineType(), mlir::MemRefRegion::compute(), mlir::ComputationSliceState::getAsConstraints(), mlir::AffineDmaWaitOp::getTagMapAttrName(), initDependenceConstraints(), isMemRefSizeValidSymbol(), isValidAffineIndexOperand(), isValidDim(), isValidSymbol(), promoteComposedSymbolsAsDims(), remainsLegalAfterInline(), replaceAllMemRefUsesWith(), verify(), and verifyDimAndSymbolIdentifiers().
isValidSymbol() [2/2]
bool mlir::isValidSymbol (Value value, Region * region)
Returns true if the given Value can be used as a symbol for region, i.e., for all its uses in region.
A value can be used as a symbol for region iff it meets onf of the the following conditions: *) It is a constant.
*) It is the result of an affine apply operation with symbol arguments. *) It is a result of the dim op on a memref whose corresponding size is a valid symbol. *) It is defined at the top level of 'region' or is its argument. *) It dominates region's parent op. If region is null, conservatively assume the symbol definition scope does not exist and only accept the values that would be symbols regardless of the surrounding region structure, i.e. the first three cases above.
Definition at line 377 of file AffineOps.cpp.
References mlir::Value::getDefiningOp(), mlir::Region::getParentOp(), mlir::Operation::getParentRegion(), mlir::Value::getType(), isDimOpValidSymbol(), mlir::Type::isIndex(), mlir::Operation::isKnownIsolatedFromAbove(), isTopLevelValue(), isValidSymbol(), m_Constant(), and matchPattern().
isVectorizableLoopBody() [1/2]
bool mlir::isVectorizableLoopBody (AffineForOp loop, NestedPattern & vectorTransferMatcher)
Checks whether the loop is structurally vectorizable; i.e.
:
no conditionals are nested under the loop;
all nested load/stores are to scalar MemRefs. TODO: relax the no-conditionals restriction
Definition at line 351 of file LoopAnalysis.cpp.
References isVectorizableLoopBodyWithOpCond().
Referenced by isVectorizableLoopPtrFactory(), and vectorizeLoopNest().
isVectorizableLoopBody() [2/2]
bool mlir::isVectorizableLoopBody (AffineForOp loop, int * memRefDim, NestedPattern & vectorTransferMatcher)
Checks whether the loop is structurally vectorizable and that all the LoadOp and StoreOp matched have access indexing functions that are are either:
invariant along the loop induction variable created by 'loop';
varying along at most one memory dimension. If such a unique dimension is found, it is written into memRefDim.
Definition at line 328 of file LoopAnalysis.cpp.
References isContiguousAccess(), and isVectorizableLoopBodyWithOpCond().
isWindowIterator()
bool mlir::isWindowIterator (Attribute attr) inline
Definition at line 93 of file StructuredOpsUtils.h.
References mlir::Attribute::dyn_cast_or_null(), mlir::StringAttr::getValue(), and getWindowIteratorTypeName().
JitRunnerMain()
int mlir::JitRunnerMain (int argc, char ** argv, JitRunnerConfig config = {})
Entry point for all CPU runners.
Expects the common argc/argv arguments for standard C++ main functions.
Definition at line 246 of file JitRunner.cpp.
References compileAndExecuteVoidFunction(), Error, failed(), getCommandLineOptLevel(), mlir::MLIRContext::getDialectRegistry(), mlir::JitRunnerConfig::llvmModuleBuilder, make_string_error(), makeLLVMPassesTransformer, mlir::JitRunnerConfig::mlirTransformer, options, parseMLIRInput(), registerAllDialects(), and mlir::JitRunnerConfig::runtimesymbolMap.
lcm()
int64_t mlir::lcm (int64_t a, int64_t b) inline
Returns the least common multiple of 'a' and 'b'.
Definition at line 49 of file MathExtras.h.
Referenced by eliminateFromConstraint(), getNewNumDimsSymbols(), and mlir::Simplex::Simplex().
linearize()
int64_t mlir::linearize (ArrayRef< int64_t > offsets, ArrayRef< int64_t > basis)
Computes and returns the linearized index of 'offsets' w.r.t. 'basis'.
Definition at line 73 of file VectorUtils.cpp.
Referenced by foldExtractFromShapeCast(), getUnrolledVectorLinearIndex(), and mlir::vector::unrollSingleResultVectorOp().
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE()
mlir::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
Enable Bitmask enums for OperationEquivalence::Flags.
loopUnrollByFactor() [1/2]
LogicalResult mlir::loopUnrollByFactor (AffineForOp forOp, uint64_t unrollFactor)
Unrolls this for operation by the specified unroll factor.
Unrolls this loop by the specified factor.
Returns failure if the loop cannot be unrolled either due to restrictions or due to invalid unroll factors. Requires positive loop bounds and step.
Returns success if the loop is successfully unrolled.
Definition at line 1099 of file LoopUtils.cpp.
References failure(), generateUnrolledLoop(), mlir::AffineMap::get(), getCleanupLoopLowerBound(), getConstantTripCount(), getLargestDivisorOfTripCount(), promoteIfSingleIteration(), and success().
Referenced by gatherInnermostLoops(), loopUnrollFull(), and loopUnrollUpToFactor().
loopUnrollByFactor() [2/2]
LogicalResult mlir::loopUnrollByFactor (scf::ForOp forOp, uint64_t unrollFactor)
Unrolls 'forOp' by 'unrollFactor', returns success if the loop is unrolled.
Definition at line 1163 of file LoopUtils.cpp.
References ceilDiv(), ceilDivPositive(), mlir::OpBuilder::create(), generateUnrolledLoop(), mlir::Value::getDefiningOp(), mlir::ConstantIndexOp::getValue(), promoteIfSingleIteration(), and success().
loopUnrollFull()
LogicalResult mlir::loopUnrollFull (AffineForOp forOp)
Unrolls this for operation completely if the trip count is known to be constant.
Unrolls this loop completely.
Returns failure otherwise.
Definition at line 1031 of file LoopUtils.cpp.
References failure(), getConstantTripCount(), loopUnrollByFactor(), and promoteIfSingleIteration().
Referenced by affineForOpBodySkew(), and gatherInnermostLoops().
loopUnrollJamByFactor()
LogicalResult mlir::loopUnrollJamByFactor (AffineForOp forOp, uint64_t unrollJamFactor)
Unrolls and jams this loop by the specified factor.
Returns success if the loop is successfully unroll-jammed.
Definition at line 1284 of file LoopUtils.cpp.
References mlir::Block::begin(), mlir::Block::end(), failure(), mlir::AffineMap::get(), mlir::Builder::getAffineDimExpr(), getCleanupLoopLowerBound(), getConstantTripCount(), getLargestDivisorOfTripCount(), mlir::Operation::getRegions(), mlir::BlockAndValueMapping::map(), promoteIfSingleIteration(), success(), mlir::Value::use_empty(), and mlir::detail::walk().
Referenced by createLoopUnrollAndJamPass(), and loopUnrollJamUpToFactor().
loopUnrollJamUpToFactor()
LogicalResult mlir::loopUnrollJamUpToFactor (AffineForOp forOp, uint64_t unrollJamFactor)
Unrolls and jams this loop by the specified factor or by the trip count (if constant), whichever is lower.
Definition at line 1274 of file LoopUtils.cpp.
References getConstantTripCount(), and loopUnrollJamByFactor().
loopUnrollUpToFactor()
LogicalResult mlir::loopUnrollUpToFactor (AffineForOp forOp, uint64_t unrollFactor)
Unrolls this loop by the specified unroll factor or its trip count, whichever is lower.
Unrolls this loop by the specified factor or by the trip count (if constant) whichever is lower.
Definition at line 1044 of file LoopUtils.cpp.
References getConstantTripCount(), and loopUnrollByFactor().
Referenced by gatherInnermostLoops().
lowerAffineLowerBound()
Value mlir::lowerAffineLowerBound (AffineForOp op, OpBuilder & builder)
Emit code that computes the lower bound of the given affine loop using standard arithmetic operations.
Emit instructions that correspond to the affine map in the lower bound applied to the respective operands, and compute the maximum value across the results.
Definition at line 292 of file AffineToStandard.cpp.
References mlir::Location::cast(), mlir::OpBuilder::create(), mlir::edsc::op::eq(), mlir::PatternRewriter::eraseBlock(), mlir::PatternRewriter::eraseOp(), expandAffineExpr(), expandAffineMap(), failure(), mlir::AffineDmaStartOp::getDstMap(), mlir::DmaStartOp::getDstMemRef(), mlir::AffineDmaStartOp::getDstMemRefOperandIndex(), mlir::IntegerAttr::getInt(), mlir::OpState::getLoc(), mlir::DmaStartOp::getNumElements(), mlir::DmaWaitOp::getNumElements(), mlir::DmaStartOp::getNumElementsPerStride(), mlir::AffineDmaStartOp::getSrcMap(), mlir::DmaStartOp::getSrcMemRef(), mlir::AffineDmaStartOp::getSrcMemRefOperandIndex(), mlir::DmaStartOp::getStride(), mlir::AffineDmaWaitOp::getTagIndices(), mlir::AffineDmaStartOp::getTagMap(), mlir::AffineDmaWaitOp::getTagMap(), mlir::DmaStartOp::getTagMemRef(), mlir::DmaWaitOp::getTagMemRef(), mlir::AffineDmaStartOp::getTagMemRefOperandIndex(), mlir::PatternRewriter::inlineRegionBefore(), lowerAffineMapMax(), lowerAffineMapMin(), lowerAffineUpperBound(), mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::edsc::op::sge(), and success().
Referenced by getOrEmitLowerBound().
lowerAffineUpperBound()
Value mlir::lowerAffineUpperBound (AffineForOp op, OpBuilder & builder)
Emit code that computes the upper bound of the given affine loop using standard arithmetic operations.
Emit instructions that correspond to the affine map in the upper bound applied to the respective operands, and compute the minimum value across the results.
Definition at line 284 of file AffineToStandard.cpp.
References lowerAffineMapMin().
Referenced by getOrEmitUpperBound(), and lowerAffineLowerBound().
m_Constant() [1/2]
detail::constant_op_matcher mlir::m_Constant () inline
Matches a constant foldable operation.
Definition at line 210 of file Matchers.h.
Referenced by canonicalizeMapOrSetAndOperands(), collapseBranch(), computeRegionBlockNumberOfExecutions(), foldLoopBounds(), mlir::OperationFolder::getOrCreateConstant(), isValidSymbol(), materializeConstant(), mlir::OperationFolder::notifyRemoval(), remainsLegalAfterInline(), mlir::OpBuilder::tryFold(), and verify().
m_Constant() [2/2]
template<typename AttrT > detail::constant_op_binder<AttrT> mlir::m_Constant (AttrT * bind_value) inline
Matches a value from a constant foldable operation and writes the value to bind_value.
Definition at line 217 of file Matchers.h.
References mlir::detail::attr_value_binder< AttrClass, ValueType, typename >::bind_value.
m_ConstantInt()
detail::constant_int_op_binder mlir::m_ConstantInt (IntegerAttr::ValueType * bind_value) inline
Matches a constant holding a scalar/vector/tensor integer (splat) and writes the integer value to bind_value.
Definition at line 260 of file Matchers.h.
Referenced by verify().
m_NonZero()
detail::constant_int_not_value_matcher<0> mlir::m_NonZero () inline
Matches a constant scalar / vector splat / tensor splat integer that is any non-zero value.
Definition at line 238 of file Matchers.h.
Referenced by applyCmpPredicate().
m_One()
detail::constant_int_value_matcher<1> mlir::m_One () inline
Matches a constant scalar / vector splat / tensor splat integer one.
Definition at line 222 of file Matchers.h.
Referenced by extractCompositeElement(), and verify().
m_Op() [1/2]
template<typename OpClass > detail::op_matcher<OpClass> mlir::m_Op () inline
Matches the given OpClass.
Definition at line 227 of file Matchers.h.
m_Op() [2/2]
template<typename OpType , typename... Matchers> auto mlir::m_Op (Matchers... matchers)
Definition at line 265 of file Matchers.h.
m_Zero()
detail::constant_int_value_matcher<0> mlir::m_Zero () inline
Matches a constant scalar / vector splat / tensor splat integer zero.
Definition at line 232 of file Matchers.h.
Referenced by applyCmpPredicate(), extractCompositeElement(), getTensorTypeFromMemRefType(), and verify().
makeCanonicalStridedLayoutExpr() [1/2]
AffineExpr mlir::makeCanonicalStridedLayoutExpr (ArrayRef< int64_t > sizes, ArrayRef< AffineExpr > exprs, MLIRContext * context)
Given MemRef sizes that are either static or dynamic, returns the canonical "contiguous" strides AffineExpr.
Strides are multiplicative and once a dynamic dimension is encountered, all canonical strides become dynamic and need to be encoded with a different symbol. For canonical strides expressions, the offset is always 0 and and fastest varying stride is always 1.
Examples:
memref<3x4x5xf32> has canonical stride expression 20*exprs[0] + 5*exprs[1] + exprs[2].
memref<3x?x5xf32> has canonical stride expression s0*exprs[0] + 5*exprs[1] + exprs[2].
memref<3x4x?xf32> has canonical stride expression s1*exprs[0] + s0*exprs[1] + exprs[2].
Definition at line 788 of file BuiltinTypes.cpp.
References getAffineConstantExpr(), getAffineSymbolExpr(), mlir::AffineMap::inferFromExprList(), and simplifyAffineExpr().
Referenced by canonicalizeStridedLayout(), getStridesAndOffset(), linearizeCollapsedDims(), and makeCanonicalStridedLayoutExpr().
makeCanonicalStridedLayoutExpr() [2/2]
AffineExpr mlir::makeCanonicalStridedLayoutExpr (ArrayRef< int64_t > sizes, MLIRContext * context)
Return the result of makeCanonicalStrudedLayoutExpr for the common case where exprs is {d0, d1, .., d_(sizes.size()-1)}.
Definition at line 828 of file BuiltinTypes.cpp.
References getAffineDimExpr(), and makeCanonicalStridedLayoutExpr().
Referenced by mlir::TensorType::classof().
makeComposedAffineApply()
AffineApplyOp mlir::makeComposedAffineApply (OpBuilder & b, Location loc, AffineMap map, ArrayRef< Value > operands)
Returns a composed AffineApplyOp by composing map and operands with other AffineApplyOps supplying those operands.
The operands of the resulting AffineApplyOp do not change the length of AffineApplyOp chains.
Definition at line 848 of file AffineOps.cpp.
References composeAffineMapAndOperands(), and mlir::OpBuilder::create().
Referenced by createBinaryIndexHandle(), and mlir::AffineDmaWaitOp::getTagMapAttrName().
makeStridedLinearLayoutMap()
AffineMap mlir::makeStridedLinearLayoutMap (ArrayRef< int64_t > strides, int64_t offset, MLIRContext * context)
Given a list of strides (in which MemRefType::getDynamicStrideOrOffset() represents a dynamic value), return the single result AffineMap which represents the linearized strided layout map.
Dimensions correspond to the offset followed by the strides in order. Symbols are inserted for each dynamic dimension in order. A stride cannot take value 0.
Examples:
For offset: 0 strides: ?, ?, 1 return (i, j, k)[M, N]->(M * i + N * j + k)
For offset: 3 strides: 32, ?, 16 return (i, j, k)[M]->(3 + 32 * i + M * j + 16 * k)
For offset: ? strides: ?, ?, ? return (i, j, k)[off, M, N, P]->(off + M * i + N * j + P * k)
Definition at line 723 of file BuiltinTypes.cpp.
References mlir::detail::enumerate(), mlir::AffineMap::get(), getAffineConstantExpr(), getAffineDimExpr(), getAffineSymbolExpr(), and mlir::MemRefType::getDynamicStrideOrOffset().
Referenced by mlir::TensorType::classof(), computeReshapeCollapsedType(), eraseStridedLayout(), getCastCompatibleMemRefType(), inferTransposeResultType(), isRankReducedType(), mlir::detail::Parser::parseMemRefType(), and verify().
mapLoopToProcessorIds()
void mlir::mapLoopToProcessorIds (scf::ForOp forOp, ArrayRef< Value > processorId, ArrayRef< Value > numProcessors)
Maps forOp for execution on a parallel grid of virtual processorIds of size given by numProcessors.
This is achieved by embedding the SSA values corresponding to processorIds and numProcessors into the bounds and step of the forOp. No check is performed on the legality of the rewrite, it is the caller's responsibility to ensure legality.
Requires that processorIds and numProcessors have the same size and that for each idx, processorIds[idx] takes, at runtime, all values between 0 and numProcessors[idx] - 1. This corresponds to traditional use cases for:
GPU (threadIdx, get_local_id(), ...)
MPI (MPI_Comm_rank)
OpenMP (omp_get_thread_num)
Example: Assuming a 2-d grid with processorIds = [blockIdx.x, threadIdx.x] and numProcessors = [gridDim.x, blockDim.x], the loop:
scf.for %i = %lb to %ub step %step {
  ...
}
is rewritten into a version resembling the following pseudo-IR:
scf.for %i = %lb + %step * (threadIdx.x + blockIdx.x * blockDim.x)
   to %ub step %gridDim.x * blockDim.x * %step {
  ...
}
Definition at line 2111 of file LoopUtils.cpp.
References mlir::OpBuilder::create().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit(), and insertCopyLoops().
matchPattern() [1/2]
template<typename Pattern > bool mlir::matchPattern (Value value, const Pattern & pattern) inline
Entry point for matching a pattern over a Value.
Definition at line 244 of file Matchers.h.
References mlir::Value::getDefiningOp().
Referenced by applyCmpPredicate(), canFoldIntoConsumerOp(), canonicalizeMapOrSetAndOperands(), collapseBranch(), computeRegionBlockNumberOfExecutions(), extractCompositeElement(), foldLoopBounds(), mlir::OperationFolder::getOrCreateConstant(), getOrCreateRanges(), getTensorTypeFromMemRefType(), isValidSymbol(), materializeConstant(), mlir::OperationFolder::notifyRemoval(), remainsLegalAfterInline(), mlir::OpBuilder::tryFold(), and verify().
matchPattern() [2/2]
template<typename Pattern > bool mlir::matchPattern (Operation * op, const Pattern & pattern) inline
Entry point for matching a pattern over an Operation.
Definition at line 253 of file Matchers.h.
References mlir::detail::attr_value_binder< AttrClass, ValueType, typename >::match().
MlirOptMain() [1/2]
LogicalResult mlir::MlirOptMain (llvm::raw_ostream & outputStream, std::unique_ptr< llvm::MemoryBuffer > buffer, const PassPipelineCLParser & passPipeline, DialectRegistry & registry, bool splitInputFile, bool verifyDiagnostics, bool verifyPasses, bool allowUnregisteredDialects, bool preloadDialectsInContext = true)
Perform the core processing behind mlir-opt:
outputStream is the stream where the resulting IR is printed.
buffer is the in-memory file to parser and process.
passPipeline is the specification of the pipeline that will be applied.
registry should contain all the dialects that can be parsed in the source.
splitInputFile will look for a "-----" marker in the input file, and load each chunk in an individual ModuleOp processed separately.
verifyDiagnostics enables a verification mode where comments starting with "expected-(error|note|remark|warning)" are parsed in the input and matched against emitted diagnostics.
verifyPasses enables the IR verifier in-between each pass in the pipeline.
allowUnregisteredDialects allows to parse and create operation without registering the Dialect in the MLIRContext.
preloadDialectsInContext will trigger the upfront loading of all dialects from the global registry in the MLIRContext. This option is deprecated and will be removed soon.
Referenced by MlirOptMain(), and processBuffer().
MlirOptMain() [2/2]
LogicalResult mlir::MlirOptMain (int argc, char ** argv, llvm::StringRef toolName, DialectRegistry & registry, bool preloadDialectsInContext = true)
Implementation for tools like mlir-opt.
toolName is used for the header displayed by --help.
registry should contain all the dialects that can be parsed in the source.
preloadDialectsInContext will trigger the upfront loading of all dialects from the global registry in the MLIRContext. This option is deprecated and will be removed soon.
Definition at line 151 of file MlirOptMain.cpp.
References failed(), failure(), MlirOptMain(), openInputFile(), openOutputFile(), registerAsmPrinterCLOptions(), registerMLIRContextCLOptions(), registerPassManagerCLOptions(), and success().
mlirTranslateMain()
LogicalResult mlir::mlirTranslateMain (int argc, char ** argv, llvm::StringRef toolName)
Translate to/from an MLIR module from/to an external representation (e.g.
LLVM IR, SPIRV binary, ...). This is the entry point for the implementation of tools like mlir-translate. The translation to perform is parsed from the command line. The toolName argument is used for the header displayed by --help.
Definition at line 129 of file Translation.cpp.
References failed(), failure(), openInputFile(), openOutputFile(), mlir::MLIRContext::printOpOnDiagnostic(), processBuffer(), registerAsmPrinterCLOptions(), registerMLIRContextCLOptions(), splitAndProcessBuffer(), success(), and mlir::SourceMgrDiagnosticVerifierHandler::verify().
mod()
int64_t mlir::mod (int64_t lhs, int64_t rhs) inline
Returns MLIR's mod operation on constants.
MLIR's mod operation yields the remainder of the Euclidean division of 'lhs' by 'rhs', and is therefore not C's % operator. The RHS is always expected to be positive, and the result is always non-negative.
Definition at line 43 of file MathExtras.h.
Referenced by simplifyMod(), and mlir::LLVM::detail::vectorOneToOneRewrite().
moveLoopInvariantCode()
LogicalResult mlir::moveLoopInvariantCode (LoopLikeOpInterface looplike)
Move loop invariant code out of looplike.
Definition at line 78 of file LoopInvariantCodeMotion.cpp.
References canBeHoisted(), and failed().
Referenced by mlir::linalg::hoistRedundantVectorTransfers().
normalizeAffineParallel()
void mlir::normalizeAffineParallel (AffineParallelOp op)
Normalize a affine.parallel op so that lower bounds are 0 and steps are 1.
As currently implemented, this transformation cannot fail and will return early if the op is already in a normalized form.
Definition at line 23 of file AffineLoopNormalize.cpp.
References mlir::OpBuilder::atBlockBegin(), mlir::AffineExpr::ceilDiv(), mlir::AffineMap::get(), mlir::Builder::getAffineConstantExpr(), mlir::AffineValueMap::getNumDims(), mlir::AffineMap::getNumDims(), mlir::AffineValueMap::getNumSymbols(), mlir::AffineMap::getNumSymbols(), mlir::AffineValueMap::getOperands(), mlir::AffineValueMap::getResult(), mlir::AffineMap::getResult(), mlir::AffineMap::getResults(), and mlir::Value::replaceAllUsesExcept().
Referenced by normalizeAffineFor().
normalizeMemRef()
LogicalResult mlir::normalizeMemRef (AllocOp op)
Rewrites the memref defined by this alloc op to have an identity layout map and updates all its indexing uses.
Returns failure if any of its uses escape (while leaving the IR in a valid state).
Definition at line 396 of file Utils.cpp.
References mlir::OpBuilder::create(), failed(), failure(), mlir::MemRefType::getAffineMaps(), mlir::Value::getUsers(), normalizeMemRefType(), replaceAllMemRefUsesWith(), mlir::Value::replaceAllUsesWith(), and success().
Referenced by isMemRefNormalizable().
normalizeMemRefType()
MemRefType mlir::normalizeMemRefType (MemRefType memrefType, OpBuilder builder, unsigned numSymbolicOperands)
Uses the old memref type map layout and computes the new memref type to have a new shape and a layout map, where the old layout map has been normalized to an identity layout map.
It returns the old memref in case no normalization was needed or a failure occurs while transforming the old map layout to an identity layout map.
Definition at line 437 of file Utils.cpp.
References mlir::FlatAffineConstraints::addConstantLowerBound(), mlir::FlatAffineConstraints::addConstantUpperBound(), mlir::FlatAffineConstraints::composeMatchingMap(), failed(), mlir::MemRefType::getAffineMaps(), mlir::FlatAffineConstraints::getConstantUpperBound(), mlir::Builder::getMultiDimIdentityMap(), mlir::FlatAffineConstraints::getNumIds(), mlir::FlatAffineConstraints::getNumLocalIds(), mlir::AffineMap::getNumResults(), mlir::MemRefType::getShape(), mlir::FlatAffineConstraints::projectOut(), and mlir::MemRefType::Builder::setShape().
Referenced by isMemRefNormalizable(), and normalizeMemRef().
openInputFile()
std::unique_ptr<llvm::MemoryBuffer> mlir::openInputFile (llvm::StringRef inputFilename, std::string * errorMessage = nullptr)
Open the file specified by its name for reading.
Write the error message to errorMessage if errors occur and errorMessage is not nullptr.
Referenced by MlirOptMain(), mlirTranslateMain(), and parseMLIRInput().
openOutputFile()
std::unique_ptr<llvm::ToolOutputFile> mlir::openOutputFile (llvm::StringRef outputFilename, std::string * errorMessage = nullptr)
Open the file specified by its name for writing.
Write the error message to errorMessage if errors occur and errorMessage is not nullptr.
Referenced by mlir::SimpleObjectCache::dumpToObjectFile(), generateLocationsFromIR(), hasSizeMismatch(), MlirOptMain(), and mlirTranslateMain().
operator!=() [1/5]
bool mlir::operator!= (Identifier lhs, StringRef rhs) inline
Definition at line 89 of file Identifier.h.
operator!=() [2/5]
bool mlir::operator!= (IntInfty lhs, IntInfty rhs) inline
Definition at line 94 of file SDBM.h.
operator!=() [3/5]
bool mlir::operator!= (StringRef lhs, Identifier rhs) inline
Definition at line 94 of file Identifier.h.
operator!=() [4/5]
bool mlir::operator!= (OpState lhs, OpState rhs) inline
Definition at line 269 of file OpDefinition.h.
References mlir::OpState::getOperation().
operator!=() [5/5]
bool mlir::operator!= (OperationName lhs, OperationName rhs) inline
Definition at line 372 of file OperationSupport.h.
References mlir::OperationName::getAsOpaquePointer().
operator*() [1/2]
Fraction mlir::operator* (Fraction x, Fraction y) inline
Definition at line 71 of file Fraction.h.
References mlir::Fraction::den, mlir::Fraction::Fraction(), and mlir::Fraction::num.
Referenced by mlir::ArrayAttr::empty(), mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs(), and mlir::AffineExpr::operator!().
operator*() [2/2]
AffineExpr mlir::operator* (int64_t val, AffineExpr expr) inline
Definition at line 224 of file AffineExpr.h.
operator+() [1/2]
IntInfty mlir::operator+ (IntInfty lhs, IntInfty rhs) inline
Definition at line 57 of file SDBM.h.
References mlir::IntInfty::getValue(), mlir::IntInfty::infty, and mlir::IntInfty::isFinite().
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs(), and mlir::AffineExpr::operator!().
operator+() [2/2]
AffineExpr mlir::operator+ (int64_t val, AffineExpr expr) inline
Definition at line 223 of file AffineExpr.h.
operator-() [1/2]
Fraction mlir::operator- (Fraction x) inline
Definition at line 59 of file Fraction.h.
References mlir::Fraction::den, mlir::Fraction::Fraction(), and mlir::Fraction::num.
Referenced by mlir::edsc::TemplatedIndexedValue< Load, Store >::getElementalTypeAs(), mlir::AffineExpr::operator!(), mlir::SDBMExpr::operator!(), and mlir::ops_assertions::operator+().
operator-() [2/2]
AffineExpr mlir::operator- (int64_t val, AffineExpr expr) inline
Definition at line 225 of file AffineExpr.h.
References getAffineBinaryOpExpr(), getAffineConstantExpr(), getAffineDimExpr(), getAffineExprFromFlatForm(), getAffineSymbolExpr(), and operator<<().
operator<() [1/4]
bool mlir::operator< (Fraction x, Fraction y) inline
Definition at line 61 of file Fraction.h.
References compare().
Referenced by buildPredicateList(), mlir::tblgen::Dialect::operator!=(), and mlir::tblgen::TypeDef::TypeDef().
operator<() [2/4]
bool mlir::operator< (IntInfty lhs, IntInfty rhs) inline
Definition at line 82 of file SDBM.h.
References mlir::IntInfty::getValue().
operator<() [3/4]
bool mlir::operator< (const NamedAttribute & lhs, const NamedAttribute & rhs)
Definition at line 49 of file Attributes.cpp.
operator<() [4/4]
bool mlir::operator< (const NamedAttribute & lhs, StringRef rhs)
Definition at line 52 of file Attributes.cpp.
operator<<() [1/29]
raw_ostream & mlir::operator<< (raw_ostream & os, Range & range)
Definition at line 3308 of file Ops.cpp.
References mlir::Range::offset, mlir::Range::size, and mlir::Range::stride.
Referenced by operator-(), and operator<<().
operator<<() [2/29]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, Attribute attr) inline
Definition at line 56 of file DialectImplementation.h.
References mlir::DialectAsmPrinter::printAttribute().
operator<<() [3/29]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, const APFloat & value) inline
Definition at line 61 of file DialectImplementation.h.
References mlir::DialectAsmPrinter::printFloat().
operator<<() [4/29]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, float value) inline
Definition at line 66 of file DialectImplementation.h.
operator<<() [5/29]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, double value) inline
Definition at line 69 of file DialectImplementation.h.
operator<<() [6/29]
DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, Type type) inline
Definition at line 73 of file DialectImplementation.h.
References mlir::DialectAsmPrinter::printType().
operator<<() [7/29]
raw_ostream& mlir::operator<< (raw_ostream & os, Identifier identifier) inline
Definition at line 80 of file Identifier.h.
References mlir::Identifier::print().
operator<<() [8/29]
template<typename T , typename std::enable_if< !std::is_convertible< T &, Attribute &>::value &&!std::is_convertible< T &, Type &>::value &&!std::is_convertible< T &, APFloat &>::value &&!llvm::is_one_of< T, double, float >::value, T >::type * = nullptr> DialectAsmPrinter& mlir::operator<< (DialectAsmPrinter & p, const T & other) inline
Definition at line 87 of file DialectImplementation.h.
References mlir::DialectAsmPrinter::getStream().
operator<<() [9/29]
raw_ostream& mlir::operator<< (raw_ostream & os, const Location & loc) inline
Definition at line 92 of file Location.h.
References mlir::Location::print().
operator<<() [10/29]
raw_ostream& mlir::operator<< (raw_ostream & os, Attribute attr) inline
Definition at line 93 of file Attributes.h.
References mlir::Attribute::print().
operator<<() [11/29]
raw_ostream& mlir::operator<< (raw_ostream & os, const DiagnosticArgument & arg) inline
Definition at line 145 of file Diagnostics.h.
References mlir::DiagnosticArgument::print().
operator<<() [12/29]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, Value value) inline
Definition at line 156 of file OpImplementation.h.
References mlir::OpAsmPrinter::printOperand().
operator<<() [13/29]
template<typename T , typename std::enable_if< std::is_convertible< T &, ValueRange >::value &&!std::is_convertible< T &, Value &>::value, T >::type * = nullptr> OpAsmPrinter & mlir::operator<< (OpAsmPrinter & p, const T & values) inline
Definition at line 165 of file OpImplementation.h.
References mlir::OpAsmPrinter::printOperands().
operator<<() [14/29]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, Type type) inline
Definition at line 170 of file OpImplementation.h.
References mlir::OpAsmPrinter::printType().
operator<<() [15/29]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, Attribute attr) inline
Definition at line 175 of file OpImplementation.h.
References mlir::OpAsmPrinter::getStream(), operator<<(), and mlir::OpAsmPrinter::printAttribute().
operator<<() [16/29]
raw_ostream& mlir::operator<< (raw_ostream & os, Type type) inline
Definition at line 175 of file Types.h.
References mlir::Type::print().
operator<<() [17/29]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, bool value) inline
Definition at line 195 of file OpImplementation.h.
operator<<() [18/29]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, Block * value) inline
Definition at line 199 of file OpImplementation.h.
References mlir::OpAsmPrinter::printSuccessor().
operator<<() [19/29]
template<typename ValueRangeT > OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, const ValueTypeRange< ValueRangeT > & types) inline
Definition at line 205 of file OpImplementation.h.
operator<<() [20/29]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, const TypeRange & types) inline
Definition at line 210 of file OpImplementation.h.
operator<<() [21/29]
OpAsmPrinter& mlir::operator<< (OpAsmPrinter & p, ArrayRef< Type > types) inline
Definition at line 214 of file OpImplementation.h.
operator<<() [22/29]
raw_ostream& mlir::operator<< (raw_ostream & os, Value value) inline
Definition at line 240 of file Value.h.
References mlir::Value::print().
operator<<() [23/29]
raw_ostream & mlir::operator<< (raw_ostream & os, AffineExpr expr)
Definition at line 816 of file AffineExpr.cpp.
References mlir::AffineExpr::print().
operator<<() [24/29]
raw_ostream& mlir::operator<< (raw_ostream & os, OpState & op) inline
Allow printing to a stream.
Definition at line 279 of file OpDefinition.h.
References mlir::OpTrait::impl::foldIdempotent(), mlir::OpTrait::impl::foldInvolution(), mlir::OpState::print(), mlir::OpTrait::impl::verifyAtLeastNOperands(), mlir::OpTrait::impl::verifyAtLeastNRegions(), mlir::OpTrait::impl::verifyAtLeastNResults(), mlir::OpTrait::impl::verifyAtLeastNSuccessors(), mlir::OpTrait::impl::verifyElementwiseMappable(), mlir::OpTrait::impl::verifyIsIdempotent(), mlir::OpTrait::impl::verifyIsInvolution(), mlir::OpTrait::impl::verifyIsTerminator(), mlir::OpTrait::impl::verifyNOperands(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::OpTrait::impl::verifyNRegions(), mlir::OpTrait::impl::verifyNResults(), mlir::OpTrait::impl::verifyNSuccessors(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOneRegion(), mlir::OpTrait::impl::verifyOneResult(), mlir::OpTrait::impl::verifyOneSuccessor(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifyOperandSizeAttr(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifyResultSizeAttr(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), mlir::OpTrait::impl::verifyZeroOperands(), mlir::OpTrait::impl::verifyZeroRegion(), mlir::OpTrait::impl::verifyZeroResult(), and mlir::OpTrait::impl::verifyZeroSuccessor().
operator<<() [25/29]
raw_ostream& mlir::operator<< (raw_ostream & os, const Diagnostic & diag) inline
Definition at line 297 of file Diagnostics.h.
References mlir::Diagnostic::print().
operator<<() [26/29]
raw_ostream& mlir::operator<< (raw_ostream & os, PDLValue value) inline
Definition at line 299 of file PatternMatch.h.
References mlir::PDLValue::print().
operator<<() [27/29]
raw_ostream& mlir::operator<< (raw_ostream & os, AffineMap map) inline
Definition at line 333 of file AffineMap.h.
References mlir::AffineMap::print().
operator<<() [28/29]
raw_ostream& mlir::operator<< (raw_ostream & os, OperationName identifier) inline
Definition at line 363 of file OperationSupport.h.
References mlir::OperationName::print().
operator<<() [29/29]
raw_ostream& mlir::operator<< (raw_ostream & os, Operation & op) inline
Definition at line 757 of file Operation.h.
References mlir::Operation::print().
operator<=() [1/2]
bool mlir::operator<= (Fraction x, Fraction y) inline
Definition at line 63 of file Fraction.h.
References compare().
operator<=() [2/2]
bool mlir::operator<= (IntInfty lhs, IntInfty rhs) inline
Definition at line 86 of file SDBM.h.
References mlir::IntInfty::getValue().
operator==() [1/7]
bool mlir::operator== (Fraction x, Fraction y) inline
Definition at line 65 of file Fraction.h.
References compare().
Referenced by mlir::AffineExpr::operator!=(), mlir::python::PyAttribute::PyAttribute(), mlir::python::PyType::PyType(), and mlir::tblgen::TypeDef::TypeDef().
operator==() [2/7]
bool mlir::operator== (Identifier lhs, StringRef rhs) inline
Definition at line 86 of file Identifier.h.
References mlir::Identifier::strref().
operator==() [3/7]
bool mlir::operator== (IntInfty lhs, IntInfty rhs) inline
Definition at line 90 of file SDBM.h.
References mlir::IntInfty::getValue().
operator==() [4/7]
bool mlir::operator== (StringRef lhs, Identifier rhs) inline
Definition at line 91 of file Identifier.h.
References mlir::Identifier::strref().
operator==() [5/7]
template<typename RangeT > bool mlir::operator== (ArrayRef< Type > lhs, const ValueTypeRange< RangeT > & rhs) inline
Definition at line 127 of file TypeRange.h.
operator==() [6/7]
bool mlir::operator== (OpState lhs, OpState rhs) inline
Definition at line 266 of file OpDefinition.h.
References mlir::OpState::getOperation().
operator==() [7/7]
bool mlir::operator== (OperationName lhs, OperationName rhs) inline
Definition at line 368 of file OperationSupport.h.
References mlir::OperationName::getAsOpaquePointer().
operator>()
bool mlir::operator> (Fraction x, Fraction y) inline
Definition at line 67 of file Fraction.h.
References compare().
operator>=()
bool mlir::operator>= (Fraction x, Fraction y) inline
Definition at line 69 of file Fraction.h.
References compare().
outlineIfOp()
void mlir::outlineIfOp (OpBuilder & b, scf::IfOp ifOp, FuncOp * thenFn, StringRef thenFnName, FuncOp * elseFn, StringRef elseFnName)
Outline the then and/or else regions of ifOp as follows:
if thenFn is not null, thenFnName must be specified and the then region is inlined into a new FuncOp that is captured by the pointer.
if elseFn is not null, elseFnName must be specified and the else region is inlined into a new FuncOp that is captured by the pointer.
Definition at line 80 of file Utils.cpp.
References mlir::Block::clear(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::Region::front(), mlir::FunctionType::get(), mlir::Region::getBlocks(), mlir::Operation::getOperands(), mlir::Operation::getResults(), mlir::Operation::getResultTypes(), mlir::Block::getTerminator(), getUsedValuesDefinedAbove(), mlir::BlockAndValueMapping::lookup(), mlir::BlockAndValueMapping::map(), mlir::OpBuilder::setInsertionPoint(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), and mlir::Block::without_terminator().
outlineKernelFunc()
gpu::GPUFuncOp mlir::outlineKernelFunc (gpu::LaunchOp launchOp, StringRef kernelFnName, llvm::SmallVectorImpl< Value > & operands)
Get a gpu.func created from outlining the region of a gpu.launch op with the given kernelFnName.
The region of the launchOp can use values from above. These need to be captured and passed as arguments to the generated gpu.func. The generated function has arguments
corresponding to the values passed in as operands, in that order.
any additional values that might be used within the region of the launchOp and defined above it. These captured values are appended to the operands list.
Definition at line 197 of file KernelOutlining.cpp.
References outlineKernelFuncImpl().
parseAttribute() [1/4]
Attribute mlir::parseAttribute (llvm::StringRef attrStr, MLIRContext * context)
This parses a single MLIR attribute to an MLIR context if it was valid.
If not, an error message is emitted through a new SourceMgrDiagnosticHandler constructed from a new SourceMgr with a single a MemoryBuffer wrapping attrStr. If the passed attrStr has additional tokens that were not part of the type, an error is emitted.
Referenced by mlirAttributeParseGet(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), mlir::DialectAsmParser::parseKeyword(), mlir::OpAsmParser::parseOptionalInteger(), parseSymbol(), and parseTargetEnvAttr().
parseAttribute() [2/4]
Attribute mlir::parseAttribute (llvm::StringRef attrStr, Type type)
parseAttribute() [3/4]
Attribute mlir::parseAttribute (llvm::StringRef attrStr, MLIRContext * context, size_t & numRead)
This parses a single MLIR attribute to an MLIR context if it was valid.
If not, an error message is emitted through a new SourceMgrDiagnosticHandler constructed from a new SourceMgr with a single a MemoryBuffer wrapping attrStr. The number of characters of attrStr parsed in the process is returned in numRead.
parseAttribute() [4/4]
Attribute mlir::parseAttribute (llvm::StringRef attrStr, Type type, size_t & numRead)
Referenced by parseSourceString().
parseDimAndSymbolList()
ParseResult mlir::parseDimAndSymbolList (OpAsmParser & parser, SmallVectorImpl< Value > & operands, unsigned & numDims)
Parses dimension and symbol list and returns true if parsing failed.
Definition at line 435 of file AffineOps.cpp.
References failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OpAsmParser::OptionalSquare, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseOperandList(), and mlir::OpAsmParser::resolveOperands().
Referenced by mlir::AffineDmaWaitOp::getTagMapAttrName(), parseAffineApplyOp(), parseAffineIfOp(), and parseBound().
parseEnumKeywordAttr()
template<typename EnumClass , typename ParserType > static ParseResult mlir::parseEnumKeywordAttr (EnumClass & value, ParserType & parser, StringRef attrName = spirv::attributeName<EnumClass>()) static
Parses the next keyword in parser as an enumerant of the given EnumClass.
Definition at line 25 of file ParserUtils.h.
References failure(), and success().
Referenced by parseControlAttribute(), parseCooperativeMatrixType(), parseEnumKeywordAttr(), and parseModuleOp().
parseOffsetsSizesAndStrides() [1/2]
ParseResult mlir::parseOffsetsSizesAndStrides (OpAsmParser & parser, OperationState & result, ArrayRef< int > segmentSizes, llvm::function_ref< ParseResult(OpAsmParser &, OperationState &)> preResolutionFn = nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalOffsetPrefix = nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalSizePrefix = nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalStridePrefix = nullptr)
Parse trailing part of an op of the form: `` <optional-offset-prefix>[offset-list] <optional-size-prefix>[size-list] <optional-stride-prefix>[ stride-list ] ``` Each entry in the offset, size and stride list either resolves to an integer constant or an operand of index type.
Constants are added to the result as named integer array attributes with name OffsetSizeAndStrideOpInterface::getStaticOffsetsAttrName() (resp. getStaticSizesAttrName(), getStaticStridesAttrName()).
Append the number of offset, size and stride operands to segmentSizes before adding it to result as the named attribute: OpTrait::AttrSizedOperandSegments<void>::getOperandSegmentSizeAttr().
Offset, size and stride operands resolution occurs after preResolutionFn to give a chance to leading operands to resolve first, after parsing the types.
Definition at line 155 of file ViewLikeInterface.cpp.
References mlir::OperationState::addAttribute(), failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::OperationState::operands, parseListOfOperandsOrIntegers(), and mlir::OpAsmParser::resolveOperands().
Referenced by parseMemRefReinterpretCastOp(), parseOffsetsSizesAndStrides(), parseSubTensorInsertOp(), parseSubTensorOp(), and parseSubViewOp().
parseOffsetsSizesAndStrides() [2/2]
ParseResult mlir::parseOffsetsSizesAndStrides (OpAsmParser & parser, OperationState & result, ArrayRef< int > segmentSizes, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalOffsetPrefix = nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalSizePrefix = nullptr, llvm::function_ref< ParseResult(OpAsmParser &)> parseOptionalStridePrefix = nullptr)
preResolutionFn-less version of parseOffsetsSizesAndStrides.
Definition at line 145 of file ViewLikeInterface.cpp.
References parseOffsetsSizesAndStrides().
parsePassPipeline()
LogicalResult mlir::parsePassPipeline (StringRef pipeline, OpPassManager & pm, raw_ostream & errorStream = llvm::errs())
This function parses the textual representation of a pass pipeline, and adds the result to 'pm' on success.
This function returns failure if the given pipeline was invalid. 'errorStream' is the output stream used to emit errors found during parsing.
This function returns failure if the given pipeline was invalid. 'errorStream' is an optional parameter that, if non-null, will be used to emit errors found during parsing.
Definition at line 470 of file PassRegistry.cpp.
References failed(), failure(), options, and success().
Referenced by inlineCallsInSCC(), mlirParsePassPipeline(), and mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration().
parseSourceFile() [1/6]
LogicalResult mlir::parseSourceFile (const llvm::SourceMgr & sourceMgr, Block * block, MLIRContext * context, LocationAttr * sourceFileLoc = nullptr)
This parses the file specified by the indicated SourceMgr and appends parsed operations to the given block.
If the block is non-empty, the operations are placed before the current terminator. If parsing is successful, success is returned. Otherwise, an error message is emitted through the error handler registered in the context, and failure is returned. If sourceFileLoc is non-null, it is populated with a file location representing the start of the source file that is being parsed.
Definition at line 2086 of file Parser.cpp.
References mlir::FileLineColLoc::get().
Referenced by parseMLIRInput(), parseSourceFile(), parseSourceString(), performActions(), and mlir::TranslateFromMLIRRegistration::TranslateFromMLIRRegistration().
parseSourceFile() [2/6]
LogicalResult mlir::parseSourceFile (llvm::StringRef filename, Block * block, MLIRContext * context, LocationAttr * sourceFileLoc = nullptr)
This parses the file specified by the indicated filename and appends parsed operations to the given block.
If the block is non-empty, the operations are placed before the current terminator. If parsing is successful, success is returned. Otherwise, an error message is emitted through the error handler registered in the context, and failure is returned. If sourceFileLoc is non-null, it is populated with a file location representing the start of the source file that is being parsed.
Definition at line 2101 of file Parser.cpp.
References parseSourceFile().
parseSourceFile() [3/6]
LogicalResult mlir::parseSourceFile (llvm::StringRef filename, llvm::SourceMgr & sourceMgr, Block * block, MLIRContext * context, LocationAttr * sourceFileLoc = nullptr)
This parses the file specified by the indicated filename using the provided SourceMgr and appends parsed operations to the given block.
If the block is non-empty, the operations are placed before the current terminator. If parsing is successful, success is returned. Otherwise, an error message is emitted through the error handler registered in the context, and failure is returned. If sourceFileLoc is non-null, it is populated with a file location representing the start of the source file that is being parsed.
Definition at line 2108 of file Parser.cpp.
References mlir::detail::Parser::emitError(), mlir::UnknownLoc::get(), and parseSourceFile().
parseSourceFile() [4/6]
template<typename ContainerOpT > OwningModuleRef mlir::parseSourceFile (const llvm::SourceMgr & sourceMgr, MLIRContext * context) inline
This parses the file specified by the indicated SourceMgr.
TODO: These methods are deprecated in favor of the above template versions.
If the source IR contained a single instance of ContainerOpT, it is returned. Otherwise, a new instance of ContainerOpT is constructed containing all of the parsed operations. If parsing was not successful, null is returned and an error message is emitted through the error handler registered in the context, and failure is returned. ContainerOpT is required to have a single region containing a single block, and must implement the SingleBlockImplicitTerminator trait.
They should be removed when usages have been updated.
Definition at line 129 of file Parser.h.
References failed(), and parseSourceFile().
parseSourceFile() [5/6]
template<typename ContainerOpT > OwningModuleRef mlir::parseSourceFile (llvm::StringRef filename, MLIRContext * context) inline
This parses the file specified by the indicated filename.
If the source IR contained a single instance of ContainerOpT, it is returned. Otherwise, a new instance of ContainerOpT is constructed containing all of the parsed operations. If parsing was not successful, null is returned and an error message is emitted through the error handler registered in the context, and failure is returned. ContainerOpT is required to have a single region containing a single block, and must implement the SingleBlockImplicitTerminator trait.
Definition at line 147 of file Parser.h.
References failed(), and parseSourceFile().
parseSourceFile() [6/6]
template<typename ContainerOpT > OwningModuleRef mlir::parseSourceFile (llvm::StringRef filename, llvm::SourceMgr & sourceMgr, MLIRContext * context) inline
This parses the file specified by the indicated filename using the provided SourceMgr.
If the source IR contained a single instance of ContainerOpT, it is returned. Otherwise, a new instance of ContainerOpT is constructed containing all of the parsed operations. If parsing was not successful, null is returned and an error message is emitted through the error handler registered in the context, and failure is returned. ContainerOpT is required to have a single region containing a single block, and must implement the SingleBlockImplicitTerminator trait.
Definition at line 166 of file Parser.h.
References failed().
Referenced by mlir::detail::constructContainerOpForParserIfNecessary(), parseSourceFile(), and parseSourceString().
parseSourceString() [1/2]
LogicalResult mlir::parseSourceString (llvm::StringRef sourceStr, Block * block, MLIRContext * context, LocationAttr * sourceFileLoc = nullptr)
This parses the IR string and appends parsed operations to the given block.
If the block is non-empty, the operations are placed before the current terminator. If parsing is successful, success is returned. Otherwise, an error message is emitted through the error handler registered in the context, and failure is returned. If sourceFileLoc is non-null, it is populated with a file location representing the start of the source file that is being parsed.
Definition at line 2127 of file Parser.cpp.
References failure(), and parseSourceFile().
Referenced by mlirModuleCreateParse().
parseSourceString() [2/2]
template<typename ContainerOpT > OwningModuleRef mlir::parseSourceString (llvm::StringRef sourceStr, MLIRContext * context) inline
This parses the provided string containing MLIR.
If the source IR contained a single instance of ContainerOpT, it is returned. Otherwise, a new instance of ContainerOpT is constructed containing all of the parsed operations. If parsing was not successful, null is returned and an error message is emitted through the error handler registered in the context, and failure is returned. ContainerOpT is required to have a single region containing a single block, and must implement the SingleBlockImplicitTerminator trait.
Definition at line 187 of file Parser.h.
References failed(), parseAttribute(), parseSourceFile(), and parseType().
Referenced by mlir::detail::constructContainerOpForParserIfNecessary().
parseType() [1/2]
Type mlir::parseType (llvm::StringRef typeStr, MLIRContext * context)
This parses a single MLIR type to an MLIR context if it was valid.
If not, an error message is emitted through a new SourceMgrDiagnosticHandler constructed from a new SourceMgr with a single a MemoryBuffer wrapping typeStr. If the passed typeStr has additional tokens that were not part of the type, an error is emitted.
Referenced by mlirTypeParseGet(), mlir::DialectAsmParser::parseAttribute(), mlir::detail::Parser::parseExtendedAttr(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseRegionArgumentList(), parseSymbol(), mlir::DialectAsmParser::parseType(), mlir::OpAsmParser::parseType(), and mlir::OpAsmParser::parseTypeList().
parseType() [2/2]
Type mlir::parseType (llvm::StringRef typeStr, MLIRContext * context, size_t & numRead)
This parses a single MLIR type to an MLIR context if it was valid.
If not, an error message is emitted through a new SourceMgrDiagnosticHandler constructed from a new SourceMgr with a single a MemoryBuffer wrapping typeStr. The number of characters of typeStr parsed in the process is returned in numRead.
Referenced by parseSourceString().
permuteLoops()
unsigned mlir::permuteLoops (MutableArrayRef< AffineForOp > inputNest, ArrayRef< unsigned > permMap)
Performs a loop permutation on a perfectly nested loop nest inputNest (where the contained loops appear from outer to inner) as specified by the permutation permMap: loop 'i' in inputNest is mapped to location 'loopPermMap[i]', where positions 0, 1, ...
are from the outermost position to inner. Returns the position in inputNest of the AffineForOp that becomes the new outermost loop of this nest. This method always succeeds, asserts out on invalid input / specifications.
Definition at line 1498 of file LoopUtils.cpp.
References mlir::detail::enumerate(), and isPerfectlyNested().
Referenced by sinkSequentialLoops().
populateAffineToStdConversionPatterns()
void mlir::populateAffineToStdConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Collect a set of patterns to convert from the Affine dialect to the Standard dialect, in particular convert structured affine control flow into CFG branch-based control flow.
Definition at line 645 of file AffineToStandard.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by populateAffineToVectorConversionPatterns(), and populateLinalgToLLVMConversionPatterns().
populateAffineToVectorConversionPatterns()
void mlir::populateAffineToVectorConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Collect a set of patterns to convert vector-related Affine ops to the Vector dialect.
Definition at line 664 of file AffineToStandard.cpp.
References mlir::ConversionTarget::addLegalDialect(), applyPartialConversion(), failed(), mlir::OwningRewritePatternList::insert(), and populateAffineToStdConversionPatterns().
populateArmNeonToLLVMConversionPatterns()
void mlir::populateArmNeonToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from theArmNeon dialect to LLVM.
Populate the given list with patterns that convert from ArmNeon to LLVM.
Definition at line 28 of file ArmNeonToLLVM.cpp.
References mlir::OwningRewritePatternList::insert().
populateArmSVEToLLVMConversionPatterns()
void mlir::populateArmSVEToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the ArmSVE dialect to LLVM.
Populate the given list with patterns that convert from ArmSVE to LLVM.
Definition at line 63 of file ArmSVEToLLVM.cpp.
References mlir::TypeConverter::addConversion(), convertScalableVectorTypeToLLVM(), and mlir::OwningRewritePatternList::insert().
populateAVX512ToLLVMConversionPatterns()
void mlir::populateAVX512ToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the AVX512 dialect to LLVM.
Populate the given list with patterns that convert from AVX512 to LLVM.
Definition at line 83 of file ConvertAVX512ToLLVM.cpp.
References mlir::LLVMTypeConverter::getContext(), and mlir::OwningRewritePatternList::insert().
populateBranchOpInterfaceAndReturnOpTypeConversionPattern()
void mlir::populateBranchOpInterfaceAndReturnOpTypeConversionPattern (OwningRewritePatternList & patterns, MLIRContext * ctx, TypeConverter & converter)
Add a pattern to the given pattern list to rewrite branch operations and return to use operands that have been legalized by the conversion framework.
This can only be done if the branch operation implements the BranchOpInterface. Only needed for partial conversions.
Definition at line 105 of file FuncConversions.cpp.
References mlir::OwningRewritePatternList::insert().
populateBufferizeMaterializationLegality()
void mlir::populateBufferizeMaterializationLegality (ConversionTarget & target)
Marks ops used by bufferization for type conversion materializations as "legal" in the given ConversionTarget.
This function should be called by all bufferization passes using BufferizeTypeConverter so that materializations work proprely. One exception is bufferization passes doing "full" conversions, where it can be desirable for even the materializations to remain illegal so that they are eliminated, such as via the patterns in populateEliminateBufferizeMaterializationsPatterns.
Definition at line 49 of file Bufferize.cpp.
References mlir::ConversionTarget::addLegalOp(), mlir::OpConversionPattern< SourceOp >::OpConversionPattern(), mlir::ConversionPatternRewriter::replaceOp(), and success().
populateBuiltinFuncToSPIRVPatterns()
void mlir::populateBuiltinFuncToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Appends to a pattern list additional patterns for translating the builtin func op to the SPIR-V dialect.
These patterns do not handle shader interface/ABI; they convert function parameters to be of SPIR-V allowed types.
Definition at line 511 of file SPIRVLowering.cpp.
References mlir::OwningRewritePatternList::insert().
populateCallOpTypeConversionPattern()
void mlir::populateCallOpTypeConversionPattern (OwningRewritePatternList & patterns, MLIRContext * ctx, TypeConverter & converter)
Add a pattern to the given pattern list to convert the operand and result types of a CallOp with the given type converter.
Definition at line 40 of file FuncConversions.cpp.
References failure(), mlir::Operation::getBlock(), mlir::Block::getNumSuccessors(), mlir::OwningRewritePatternList::insert(), mlir::Operation::operand_begin(), mlir::Operation::operand_end(), mlir::Operation::setOperands(), success(), and mlir::PatternRewriter::updateRootInPlace().
populateConvertShapeConstraintsConversionPatterns()
void mlir::populateConvertShapeConstraintsConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Definition at line 108 of file ConvertShapeConstraints.cpp.
References applyPatternsAndFoldGreedily(), failed(), and mlir::OwningRewritePatternList::insert().
populateDecomposeCallGraphTypesPatterns()
void mlir::populateDecomposeCallGraphTypesPatterns (MLIRContext * context, TypeConverter & typeConverter, ValueDecomposer & decomposer, OwningRewritePatternList & patterns)
Populates the patterns needed to drive the conversion process for decomposing call graph types with the given ValueDecomposer.
Definition at line 185 of file DecomposeCallGraphTypes.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by mlir::ValueDecomposer::addDecomposeValueConversion().
populateElementwiseToLinalgConversionPatterns()
void mlir::populateElementwiseToLinalgConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Populate patterns that convert ElementwiseMappable ops to linalg parallel loops.
Definition at line 69 of file ElementwiseToLinalg.cpp.
References applyPartialConversion(), failed(), mlir::OwningRewritePatternList::insert(), isElementwiseMappableOpOnRankedTensors(), and mlir::ConversionTarget::markUnknownOpDynamicallyLegal().
populateEliminateBufferizeMaterializationsPatterns()
void mlir::populateEliminateBufferizeMaterializationsPatterns (MLIRContext * context, BufferizeTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Populate patterns to eliminate bufferize materializations.
In particular, these are the tensor_load/tensor_to_memref ops.
Definition at line 85 of file Bufferize.cpp.
References applyFullConversion(), failed(), mlir::OwningRewritePatternList::insert(), mlir::TypeConverter::isLegal(), and mlir::ConversionTarget::markUnknownOpDynamicallyLegal().
populateExpandTanhPattern()
void mlir::populateExpandTanhPattern (OwningRewritePatternList & patterns, MLIRContext * ctx)
Definition at line 67 of file ExpandTanh.cpp.
References mlir::OwningRewritePatternList::insert().
populateFoldReshapeOpsByExpansionPatterns()
void mlir::populateFoldReshapeOpsByExpansionPatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Patterns to fold an expanding (collapsing) tensor_reshape operation with its producer (consumer) generic operation by expanding the dimensionality of the loop in the generic op.
Definition at line 1011 of file FusionOnTensors.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by populateLinalgTensorOpsFusionPatterns().
populateFoldReshapeOpsByLinearizationPatterns()
void mlir::populateFoldReshapeOpsByLinearizationPatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Patterns to fold a collapsing (expanding) tensor_reshape operation with its producer (consumer) generic/indexed_generic operation by linearizing the indexing map used to access the source (target) of the reshape operation in the generic/indexed_generic operation.
Definition at line 1004 of file FusionOnTensors.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by mlir::linalg::fuseTensorOps().
populateFuncOpTypeConversionPattern()
void mlir::populateFuncOpTypeConversionPattern (OwningRewritePatternList & patterns, MLIRContext * ctx, TypeConverter & converter)
Add a pattern to the given pattern list to convert the signature of a FuncOp with the given type converter.
Definition at line 2542 of file DialectConversion.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by mlir::OpConversionPattern< SPIRVOp >::matchAndRewrite(), and outlineExecuteOp().
populateGpuAllReducePatterns()
void mlir::populateGpuAllReducePatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Collect a set of patterns to rewrite all-reduce ops within the GPU dialect.
Definition at line 400 of file AllReduceLowering.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by populateGpuRewritePatterns().
populateGpuRewritePatterns()
void mlir::populateGpuRewritePatterns (MLIRContext * context, OwningRewritePatternList & patterns) inline
Collect all patterns to rewrite ops within the GPU dialect.
Definition at line 31 of file Passes.h.
References populateGpuAllReducePatterns().
populateGpuToLLVMConversionPatterns()
void mlir::populateGpuToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns, StringRef gpuBinaryAnnotation)
Collect a set of patterns to convert from the GPU dialect to LLVM.
Definition at line 651 of file ConvertLaunchFuncToRuntimeCalls.cpp.
References mlir::TypeConverter::addConversion(), mlir::LLVMTypeConverter::getContext(), mlir::LLVM::LLVMType::getInt8PtrTy(), and mlir::OwningRewritePatternList::insert().
populateGpuToNVVMConversionPatterns()
void mlir::populateGpuToNVVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the GPU dialect to NVVM.
Definition at line 157 of file LowerGpuOpsToNVVMOps.cpp.
References mlir::LLVMTypeConverter::getDialect(), and mlir::OwningRewritePatternList::insert().
populateGpuToROCDLConversionPatterns()
void mlir::populateGpuToROCDLConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the GPU dialect to ROCDL.
Definition at line 93 of file LowerGpuOpsToROCDLOps.cpp.
References mlir::LLVMTypeConverter::getDialect(), and mlir::OwningRewritePatternList::insert().
populateGPUToSPIRVPatterns()
void mlir::populateGPUToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Appends to a pattern list additional patterns for translating GPU Ops to SPIR-V ops.
For a gpu.func to be converted, it should have a spv.entry_point_abi attribute.
Definition at line 330 of file ConvertGPUToSPIRV.cpp.
References mlir::OwningRewritePatternList::insert().
populateLinalgFoldUnitExtentDimsPatterns()
void mlir::populateLinalgFoldUnitExtentDimsPatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Patterns to fold unit-extent dimensions in operands/results of linalg ops on tensors.
Patterns that are used to canonicalize the use of unit-extent dims for broadcasting.
Definition at line 495 of file DropUnitDims.cpp.
References applyPatternsAndFoldGreedily(), and mlir::OwningRewritePatternList::insert().
populateLinalgTensorOpsFusionPatterns()
void mlir::populateLinalgTensorOpsFusionPatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Patterns for fusing linalg operation on tensors.
Definition at line 1019 of file FusionOnTensors.cpp.
References mlir::OwningRewritePatternList::insert(), and populateFoldReshapeOpsByExpansionPatterns().
Referenced by mlir::linalg::fuseTensorOps().
populateLinalgToLLVMConversionPatterns()
void mlir::populateLinalgToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Populate the given list with patterns that convert from Linalg to LLVM.
Definition at line 294 of file LinalgToLLVM.cpp.
References mlir::TypeConverter::addConversion(), mlir::ConversionTarget::addLegalOp(), applyFullConversion(), convertRangeType(), failed(), mlir::OwningRewritePatternList::insert(), populateAffineToStdConversionPatterns(), populateLoopToStdConversionPatterns(), populateStdToLLVMConversionPatterns(), populateVectorToLLVMConversionPatterns(), populateVectorToLLVMMatrixConversionPatterns(), and populateVectorToSCFConversionPatterns().
populateLinalgToSPIRVPatterns()
void mlir::populateLinalgToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Appends to a pattern list additional patterns for translating Linalg ops to SPIR-V ops.
Definition at line 204 of file LinalgToSPIRV.cpp.
References mlir::OwningRewritePatternList::insert().
populateLoopToStdConversionPatterns()
void mlir::populateLoopToStdConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Collect a set of patterns to lower from scf.for, scf.if, and loop.terminator to CFG operations within the Standard dialect, in particular convert structured control flow into CFG branch-based control flow.
Definition at line 571 of file SCFToStandard.cpp.
References mlir::ConversionTarget::addIllegalOp(), applyPartialConversion(), failed(), mlir::OwningRewritePatternList::insert(), and mlir::ConversionTarget::markUnknownOpDynamicallyLegal().
Referenced by populateLinalgToLLVMConversionPatterns().
populateOpenMPToLLVMConversionPatterns()
void mlir::populateOpenMPToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Populate the given list with patterns that convert from OpenMP to LLVM.
Definition at line 44 of file OpenMPToLLVM.cpp.
References mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::ConversionTarget::addLegalOp(), applyPartialConversion(), failed(), mlir::OwningRewritePatternList::insert(), mlir::TypeConverter::isLegal(), and populateStdToLLVMConversionPatterns().
populateParallelLoopToGPUPatterns()
void mlir::populateParallelLoopToGPUPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Adds the conversion pattern from scf.parallel to gpu.launch to the provided pattern list.
Definition at line 644 of file SCFToGPU.cpp.
References mlir::OwningRewritePatternList::insert().
populateRemoveShapeConstraintsPatterns()
void mlir::populateRemoveShapeConstraintsPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Definition at line 58 of file RemoveShapeConstraints.cpp.
References mlir::OwningRewritePatternList::insert().
populateSCFToSPIRVPatterns()
void mlir::populateSCFToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, ScfToSPIRVContext & scfToSPIRVContext, OwningRewritePatternList & patterns)
Collects a set of patterns to lower from scf.for, scf.if, and loop.terminator to CFG operations within the SPIR-V dialect.
Definition at line 292 of file SCFToSPIRV.cpp.
References mlir::ScfToSPIRVContext::getImpl(), and mlir::OwningRewritePatternList::insert().
Referenced by mlir::ScfToSPIRVContext::getImpl().
populateShapeRewritePatterns()
void mlir::populateShapeRewritePatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Collects a set of patterns to rewrite ops within the Shape dialect.
Definition at line 75 of file ShapeToShapeLowering.cpp.
References mlir::OwningRewritePatternList::insert().
populateShapeStructuralTypeConversionsAndLegality()
void mlir::populateShapeStructuralTypeConversionsAndLegality (MLIRContext * context, TypeConverter & typeConverter, OwningRewritePatternList & patterns, ConversionTarget & target)
Populates patterns for shape dialect structural type conversions and sets up the provided ConversionTarget with the appropriate legality configuration for the ops to get converted properly.
A "structural" type conversion is one where the underlying ops are completely agnostic to the actual types involved and simply need to update their types consistently. An example of this is shape.assuming – the shape.assuming op and the corresponding shape.assuming_yield op need to have consistent types, but the exact types don't matter. So all that we need to do for a structural type conversion is to update both of their types consistently to the new types prescribed by the TypeConverter.
Definition at line 59 of file StructuralTypeConversions.cpp.
References mlir::ConversionTarget::addDynamicallyLegalOp(), and mlir::OwningRewritePatternList::insert().
populateShapeToStandardConversionPatterns()
void mlir::populateShapeToStandardConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * ctx)
Definition at line 603 of file ShapeToStandard.cpp.
References mlir::OwningRewritePatternList::insert().
populateSPIRVToLLVMConversionPatterns()
void mlir::populateSPIRVToLLVMConversionPatterns (MLIRContext * context, LLVMTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Populates the given list with patterns that convert from SPIR-V to LLVM.
Definition at line 1394 of file ConvertSPIRVToLLVM.cpp.
References mlir::OwningRewritePatternList::insert(), and mlir::edsc::op::uge().
populateSPIRVToLLVMFunctionConversionPatterns()
void mlir::populateSPIRVToLLVMFunctionConversionPatterns (MLIRContext * context, LLVMTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Populates the given list with patterns for function conversion from SPIR-V to LLVM.
Definition at line 1509 of file ConvertSPIRVToLLVM.cpp.
References mlir::OwningRewritePatternList::insert().
populateSPIRVToLLVMModuleConversionPatterns()
void mlir::populateSPIRVToLLVMModuleConversionPatterns (MLIRContext * context, LLVMTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Populates the given patterns for module conversion from SPIR-V to LLVM.
Definition at line 1515 of file ConvertSPIRVToLLVM.cpp.
References mlir::OwningRewritePatternList::insert().
populateSPIRVToLLVMTypeConversion()
void mlir::populateSPIRVToLLVMTypeConversion (LLVMTypeConverter & typeConverter)
Populates type conversions with additional SPIR-V types.
Definition at line 1379 of file ConvertSPIRVToLLVM.cpp.
References mlir::TypeConverter::addConversion(), convertArrayType(), convertPointerType(), convertRuntimeArrayType(), and convertStructType().
Referenced by encodeKernelName().
populateStandardToSPIRVPatterns()
void mlir::populateStandardToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Appends to a pattern list additional patterns for translating StandardOps to SPIR-V ops.
Also adds the patterns legalize ops not directly translated to SPIR-V dialect.
Definition at line 1070 of file ConvertStandardToSPIRV.cpp.
References mlir::OwningRewritePatternList::insert().
populateStdBufferizePatterns()
void mlir::populateStdBufferizePatterns (MLIRContext * context, BufferizeTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Definition at line 157 of file Bufferize.cpp.
References mlir::ConversionTarget::addDynamicallyLegalOp(), mlir::ConversionTarget::addIllegalOp(), mlir::ConversionTarget::addLegalDialect(), applyPartialConversion(), failed(), mlir::OwningRewritePatternList::insert(), and mlir::TypeConverter::isLegal().
populateStdExpandOpsPatterns()
void mlir::populateStdExpandOpsPatterns (MLIRContext * context, OwningRewritePatternList & patterns)
Collects a set of patterns to rewrite ops within the Std dialect.
Definition at line 239 of file ExpandOps.cpp.
References mlir::OwningRewritePatternList::insert().
populateStdLegalizationPatternsForSPIRVLowering()
void mlir::populateStdLegalizationPatternsForSPIRVLowering (MLIRContext * context, OwningRewritePatternList & patterns)
Appends to a pattern list patterns to legalize ops that are not directly lowered to SPIR-V.
Definition at line 182 of file LegalizeStandardForSPIRV.cpp.
References applyPatternsAndFoldGreedily(), and mlir::OwningRewritePatternList::insert().
populateStdToLLVMConversionPatterns()
void mlir::populateStdToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect the patterns to convert from the Standard dialect to LLVM.
The conversion patterns capture the LLVMTypeConverter and the LowerToLLVMOptions by reference meaning the references have to remain alive during the entire pattern lifetime.
Definition at line 4030 of file StandardToLLVM.cpp.
References populateStdToLLVMFuncOpConversionPattern(), populateStdToLLVMMemoryConversionPatterns(), and populateStdToLLVMNonMemoryConversionPatterns().
Referenced by encodeKernelName(), mlir::LowerToLLVMOptions::getDefaultOptions(), populateLinalgToLLVMConversionPatterns(), populateOpenMPToLLVMConversionPatterns(), populateVectorToROCDLConversionPatterns(), and mlir::LLVMTypeConverter::promoteOperands().
populateStdToLLVMFuncOpConversionPattern()
void mlir::populateStdToLLVMFuncOpConversionPattern (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect the default pattern to convert a FuncOp to the LLVM dialect.
If emitCWrappers is set, the pattern will also produce functions that pass memref descriptors by pointer-to-structure in addition to the default unpacked form.
Definition at line 4022 of file StandardToLLVM.cpp.
References mlir::LLVMTypeConverter::getOptions(), mlir::OwningRewritePatternList::insert(), and mlir::LowerToLLVMOptions::useBarePtrCallConv.
Referenced by mlir::LowerToLLVMOptions::getDefaultOptions(), and populateStdToLLVMConversionPatterns().
populateStdToLLVMMemoryConversionPatterns()
void mlir::populateStdToLLVMMemoryConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert memory-related operations from the Standard dialect to the LLVM dialect, excluding non-memory-related operations and FuncOp.
Definition at line 3997 of file StandardToLLVM.cpp.
References mlir::LLVMTypeConverter::getOptions(), mlir::OwningRewritePatternList::insert(), and mlir::LowerToLLVMOptions::useAlignedAlloc.
Referenced by mlir::LowerToLLVMOptions::getDefaultOptions(), and populateStdToLLVMConversionPatterns().
populateStdToLLVMNonMemoryConversionPatterns()
void mlir::populateStdToLLVMNonMemoryConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the Standard dialect to the LLVM dialect, excluding the memory-related operations.
Collect a set of patterns to convert from the Standard dialect to LLVM.
Definition at line 3924 of file StandardToLLVM.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by mlir::LowerToLLVMOptions::getDefaultOptions(), and populateStdToLLVMConversionPatterns().
populateTensorBufferizePatterns()
void mlir::populateTensorBufferizePatterns (MLIRContext * context, BufferizeTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Definition at line 37 of file Bufferize.cpp.
References mlir::ConversionTarget::addIllegalOp(), mlir::ConversionTarget::addLegalDialect(), applyPartialConversion(), failed(), and mlir::OwningRewritePatternList::insert().
populateVectorToLLVMConversionPatterns()
void mlir::populateVectorToLLVMConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns, bool reassociateFPReductions = false, bool enableIndexOptimizations = true)
Collect a set of patterns to convert from the Vector dialect to LLVM.
Populate the given list with patterns that convert from Vector to LLVM.
Definition at line 1504 of file ConvertVectorToLLVM.cpp.
References mlir::LLVMTypeConverter::getDialect(), and mlir::OwningRewritePatternList::insert().
Referenced by populateLinalgToLLVMConversionPatterns().
populateVectorToLLVMMatrixConversionPatterns()
void mlir::populateVectorToLLVMMatrixConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from Vector contractions to LLVM Matrix Intrinsics.
To lower to assembly, the LLVM flag -lower-matrix-intrinsics will be needed when invoking LLVM.
Definition at line 1537 of file ConvertVectorToLLVM.cpp.
References mlir::OwningRewritePatternList::insert().
Referenced by populateLinalgToLLVMConversionPatterns().
populateVectorToROCDLConversionPatterns()
void mlir::populateVectorToROCDLConversionPatterns (LLVMTypeConverter & converter, OwningRewritePatternList & patterns)
Collect a set of patterns to convert from the GPU dialect to ROCDL.
Definition at line 150 of file VectorToROCDL.cpp.
References mlir::ConversionTarget::addLegalDialect(), applyPartialConversion(), failed(), mlir::OwningRewritePatternList::insert(), and populateStdToLLVMConversionPatterns().
populateVectorToSCFConversionPatterns()
void mlir::populateVectorToSCFConversionPatterns (OwningRewritePatternList & patterns, MLIRContext * context, const VectorTransferToSCFOptions & options = VectorTransferToSCFOptions())
Collect a set of patterns to convert from the Vector dialect to SCF + std.
Definition at line 689 of file VectorToSCF.cpp.
References applyPatternsAndFoldGreedily(), mlir::OwningRewritePatternList::insert(), mlir::VectorTransferRewriter< TransferOpTy >::options, and mlir::VectorTransferToSCFOptions::unroll.
Referenced by populateLinalgToLLVMConversionPatterns(), and mlir::linalg::CodegenStrategy::transform().
populateVectorToSPIRVPatterns()
void mlir::populateVectorToSPIRVPatterns (MLIRContext * context, SPIRVTypeConverter & typeConverter, OwningRewritePatternList & patterns)
Appends to a pattern list additional patterns for translating Vector Ops to SPIR-V ops.
Definition at line 120 of file VectorToSPIRV.cpp.
References applyFullConversion(), failed(), mlir::spirv::SPIRVConversionTarget::get(), mlir::OwningRewritePatternList::insert(), and mlir::spirv::lookupTargetEnvOrDefault().
populateVectorToVectorConversionPatterns()
void mlir::populateVectorToVectorConversionPatterns (MLIRContext * context, OwningRewritePatternList & patterns, ArrayRef< int64_t > coarseVectorShape = {}, ArrayRef< int64_t > fineVectorShape = {})
Collect a set of patterns to convert from the Vector dialect to itself.
Should be merged with populateVectorToSCFLoweringPattern.
printOffsetsSizesAndStrides()
void mlir::printOffsetsSizesAndStrides (OpAsmPrinter & p, OffsetSizeAndStrideOpInterface op, StringRef offsetPrefix = "", StringRef sizePrefix = " ", StringRef stridePrefix = " ", ArrayRef< StringRef > elidedAttrs = OffsetSizeAndStrideOpInterface::getSpecialAttrNames())
Print part of an op of the form: `` <optional-offset-prefix>[offset-list] <optional-size-prefix>[size-list] <optional-stride-prefix>[ stride-list ] ```.
Definition at line 80 of file ViewLikeInterface.cpp.
References mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), printListOfOperandsOrIntegers(), and mlir::OpAsmPrinter::printOptionalAttrDict().
Referenced by print().
promoteIfSingleIteration() [1/2]
LogicalResult mlir::promoteIfSingleIteration (AffineForOp forOp)
Promotes the loop body of a AffineForOp/scf::ForOp to its containing block if the loop was known to have a single iteration.
Promotes the loop body of a forOp to its containing block if the forOp was known to have a single iteration.
Definition at line 153 of file LoopUtils.cpp.
References mlir::OpBuilder::create(), failure(), getConstantTripCount(), mlir::Builder::getDimIdentityMap(), and success().
Referenced by createAffineDataCopyGenerationPass(), fuseLoops(), generateShiftedLoop(), loopUnrollByFactor(), loopUnrollFull(), loopUnrollJamByFactor(), normalizeAffineFor(), and promoteSingleIterationLoops().
promoteIfSingleIteration() [2/2]
LogicalResult mlir::promoteIfSingleIteration (scf::ForOp forOp)
Promotes the loop body of a forOp to its containing block if the forOp it can be determined that the loop has a single iteration.
Definition at line 195 of file LoopUtils.cpp.
References ceilDiv(), failure(), mlir::ConstantIndexOp::getValue(), and success().
promoteSingleIterationLoops()
void mlir::promoteSingleIterationLoops (FuncOp f)
Promotes all single iteration AffineForOp's in the Function, i.e., moves their body into the containing Block.
Promotes all single iteration 'for' ops in f, i.e., moves their body into the containing Block.
Definition at line 233 of file LoopUtils.cpp.
References promoteIfSingleIteration().
Referenced by mlir::linalg::CodegenStrategy::transform().
promoteToWorkgroupMemory()
void mlir::promoteToWorkgroupMemory (gpu::GPUFuncOp op, unsigned arg)
Promotes a function argument to workgroup memory in the given function.
The copies will be inserted in the beginning and in the end of the function.
Referenced by insertCopies().
registerAllDialects()
void mlir::registerAllDialects (DialectRegistry & registry) inline
Definition at line 48 of file InitAllDialects.h.
References mlir::DialectRegistry::insert().
Referenced by JitRunnerMain(), and mlirRegisterAllDialects().
registerAllPasses()
void mlir::registerAllPasses () inline
Definition at line 43 of file InitAllPasses.h.
registerAllTranslations()
void mlir::registerAllTranslations () inline
Definition at line 32 of file InitAllTranslations.h.
References registerArmNeonToLLVMIRTranslation(), registerArmSVEToLLVMIRTranslation(), registerAVX512ToLLVMIRTranslation(), registerFromLLVMIRTranslation(), registerFromSPIRVTranslation(), registerToLLVMIRTranslation(), registerToNVVMIRTranslation(), registerToROCDLIRTranslation(), and registerToSPIRVTranslation().
registerArmNeonToLLVMIRTranslation()
void mlir::registerArmNeonToLLVMIRTranslation ()
Definition at line 46 of file LLVMArmNeonIntr.cpp.
References failure(), and success().
Referenced by registerAllTranslations().
registerArmSVEToLLVMIRTranslation()
void mlir::registerArmSVEToLLVMIRTranslation ()
Definition at line 46 of file LLVMArmSVEIntr.cpp.
References failure(), success(), and translateLLVMArmSVEModuleToLLVMIR().
Referenced by registerAllTranslations().
registerAsmPrinterCLOptions()
void mlir::registerAsmPrinterCLOptions ()
Register a set of useful command-line options that can be used to configure various flags within the AsmPrinter.
Definition at line 105 of file AsmPrinter.cpp.
References clOptions.
Referenced by mlir::AsmState::getImpl(), MlirOptMain(), and mlirTranslateMain().
registerAVX512ToLLVMIRTranslation()
void mlir::registerAVX512ToLLVMIRTranslation ()
Definition at line 46 of file LLVMAVX512Intr.cpp.
References failure(), and success().
Referenced by registerAllTranslations().
registerDialect()
template<typename ConcreteDialect > void mlir::registerDialect (DialectRegistry & registry)
registerFromLLVMIRTranslation()
void mlir::registerFromLLVMIRTranslation ()
Definition at line 876 of file ConvertFromLLVMIR.cpp.
References translateLLVMIRToModule().
Referenced by registerAllTranslations().
registerFromSPIRVTranslation()
void mlir::registerFromSPIRVTranslation ()
Definition at line 67 of file TranslateRegistration.cpp.
References deserializeModule().
Referenced by registerAllTranslations().
registerMLIRContextCLOptions()
void mlir::registerMLIRContextCLOptions ()
Register a set of useful command-line options that can be used to configure various flags within the MLIRContext.
These flags are used when constructing an MLIR context for initialization.
Definition at line 79 of file MLIRContext.cpp.
References clOptions.
Referenced by mlir::MLIRContext::getImpl(), MlirOptMain(), and mlirTranslateMain().
registerPass()
void mlir::registerPass (StringRef arg, StringRef description, const PassAllocatorFunction & function)
Register a specific dialect pass allocator function with the system, typically used through the PassRegistration template.
Definition at line 105 of file PassRegistry.cpp.
References passRegistry.
Referenced by mlir::PassRegistration< ConcretePass >::PassRegistration().
registerPassManagerCLOptions()
void mlir::registerPassManagerCLOptions ()
Register a set of useful command-line options that can be used to configure a pass manager.
The values of these options can be applied via the 'applyPassManagerCLOptions' method below.
Definition at line 145 of file PassManagerOptions.cpp.
References options.
Referenced by mlir::PassManager::PassTimingConfig::getDisplayMode(), and MlirOptMain().
registerPassPipeline()
void mlir::registerPassPipeline (StringRef arg, StringRef description, const PassRegistryFunction & function, std::function< void(function_ref< void(const detail::PassOptions &)>)> optHandler)
Register a specific dialect pipeline registry function with the system, typically used through the PassPipelineRegistration template.
Referenced by mlir::PassRegistryEntry::getOptionWidth(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), and mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration().
registerTestRoundtripDebugSPIRV()
void mlir::registerTestRoundtripDebugSPIRV ()
Definition at line 168 of file TranslateRegistration.cpp.
References roundTripModule().
registerTestRoundtripSPIRV()
void mlir::registerTestRoundtripSPIRV ()
Definition at line 157 of file TranslateRegistration.cpp.
References roundTripModule().
registerToLLVMIRTranslation()
void mlir::registerToLLVMIRTranslation ()
Definition at line 39 of file ConvertToLLVMIR.cpp.
References failure(), and success().
Referenced by registerAllTranslations().
registerToNVVMIRTranslation()
void mlir::registerToNVVMIRTranslation ()
Definition at line 100 of file ConvertToNVVMIR.cpp.
References failure(), success(), and translateModuleToNVVMIR().
Referenced by registerAllTranslations().
registerToROCDLIRTranslation()
void mlir::registerToROCDLIRTranslation ()
Definition at line 104 of file ConvertToROCDLIR.cpp.
References failure(), success(), and translateModuleToROCDLIR().
Referenced by registerAllTranslations().
registerToSPIRVTranslation()
void mlir::registerToSPIRVTranslation ()
Definition at line 108 of file TranslateRegistration.cpp.
References serializeModule().
Referenced by registerAllTranslations().
removeDuplicateExprs()
AffineMap mlir::removeDuplicateExprs (AffineMap map)
Returns a map with the same dimension and symbol count as map, but whose results are the unique affine expressions of map.
Definition at line 408 of file AffineMap.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), and mlir::AffineMap::getResults().
Referenced by canonicalizeLoopBounds(), createCanonicalizedAffineForOp(), and mlir::MutableAffineMap::getContext().
replaceAllMemRefUsesWith() [1/2]
LogicalResult mlir::replaceAllMemRefUsesWith (Value oldMemRef, Value newMemRef, ArrayRef< Value > extraIndices = {}, AffineMap indexRemap = AffineMap(), ArrayRef< Value > extraOperands = {}, ArrayRef< Value > symbolOperands = {}, Operation * domInstFilter = nullptr, Operation * postDomInstFilter = nullptr, bool allowNonDereferencingOps = false, bool replaceInDeallocOp = false)
Replaces all "dereferencing" uses of oldMemRef with newMemRef while optionally remapping the old memref's indices using the supplied affine map, indexRemap.
The new memref could be of a different shape or rank. extraIndices provides any additional access indices to be added to the start.
indexRemap remaps indices of the old memref access to a new set of indices that are used to index the memref. Additional input operands to indexRemap can be optionally provided in extraOperands, and they occupy the start of its input list. indexRemap's dimensional inputs are expected to correspond to memref's indices, and its symbolic inputs if any should be provided in symbolOperands.
domInstFilter, if non-null, restricts the replacement to only those operations that are dominated by the former; similarly, postDomInstFilter restricts replacement to only those operations that are postdominated by it.
'allowNonDereferencingOps', if set, allows replacement of non-dereferencing uses of a memref without any requirement for access index rewrites. The default value of this flag variable is false.
'replaceInDeallocOp', if set, lets DeallocOp, a non-dereferencing user, to also be a candidate for replacement. The default value of this flag is false.
Returns true on success and false if the replacement is not possible, whenever a memref is used as an operand in a non-dereferencing context and 'allowNonDereferencingOps' is false, except for dealloc's on the memref which are left untouched. See comments at function definition for an example.
Definition at line 220 of file Utils.cpp.
References mlir::Type::cast(), failed(), failure(), getElementType(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getParentOfType(), mlir::Value::getType(), mlir::Value::getUsers(), isMemRefDereferencingOp(), and success().
Referenced by createPrivateMemRef(), doubleBuffer(), generateCopy(), isMemRefNormalizable(), and normalizeMemRef().
replaceAllMemRefUsesWith() [2/2]
LogicalResult mlir::replaceAllMemRefUsesWith (Value oldMemRef, Value newMemRef, Operation * op, ArrayRef< Value > extraIndices = {}, AffineMap indexRemap = AffineMap(), ArrayRef< Value > extraOperands = {}, ArrayRef< Value > symbolOperands = {}, bool allowNonDereferencingOps = false)
Performs the same replacement as the other version above but only for the dereferencing uses of oldMemRef in op, except in cases where 'allowNonDereferencingOps' is set to true where we replace the non-dereferencing uses as well.
Definition at line 45 of file Utils.cpp.
References canonicalizeMapAndOperands(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOperation(), mlir::detail::enumerate(), mlir::Operation::erase(), failure(), fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::AffineMapAttr::get(), getAffineMapAttrForMemRef(), mlir::Operation::getAttrs(), getElementType(), mlir::Operation::getLoc(), mlir::Builder::getMultiDimIdentityMap(), mlir::Operation::getName(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumInputs(), mlir::Operation::getNumOperands(), mlir::AffineMap::getNumResults(), mlir::Operation::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getOperands(), mlir::AffineMap::getResults(), mlir::Operation::getResults(), mlir::Value::getType(), isMemRefDereferencingOp(), isValidDim(), isValidSymbol(), mlir::Operation::operand_begin(), mlir::Operation::operand_end(), mlir::OperationState::operands, mlir::Operation::replaceAllUsesWith(), mlir::Operation::setOperand(), simplifyAffineMap(), and success().
replaceAllUsesInRegionWith()
void mlir::replaceAllUsesInRegionWith (Value orig, Value replacement, Region & region)
Replace all uses of orig within the given region with replacement.
Definition at line 23 of file RegionUtils.cpp.
References mlir::Value::getUses(), and mlir::Region::isAncestor().
Referenced by areValuesDefinedAbove(), coalesceLoops(), collapseParallelLoops(), sinkOperationsIntoLaunchOp(), and stripmineSink().
separateFullTiles()
LogicalResult mlir::separateFullTiles (MutableArrayRef< AffineForOp > nest, SmallVectorImpl< AffineForOp > * fullTileNest = nullptr)
Separates full tiles from partial tiles for a perfect nest nest by generating a conditional guard that selects between the full tile version and the partial tile version using an AffineIfOp.
The original loop nest is replaced by this guarded two version form.
affine.if (cond) // full_tile else // partial tile
Definition at line 3066 of file LoopUtils.cpp.
References createFullTiles(), createSeparationCondition(), mlir::Block::end(), failed(), failure(), mlir::Block::getOperations(), and success().
Referenced by adjustToDivisorsOfTripCounts().
shapeRatio() [1/2]
Optional< SmallVector< int64_t, 4 > > mlir::shapeRatio (ArrayRef< int64_t > superShape, ArrayRef< int64_t > subShape)
Computes and returns the multi-dimensional ratio of superShape to subShape.
This is calculated by performing a traversal from minor to major dimensions (i.e. in reverse shape order). If integral division is not possible, returns None. The ArrayRefs are assumed (and enforced) to only contain > 1 values. This constraint comes from the fact that they are meant to be used with VectorTypes, for which the property holds by construction.
Examples:
shapeRatio({3, 4, 5, 8}, {2, 5, 2}) returns {3, 2, 1, 4}
shapeRatio({3, 4, 4, 8}, {2, 5, 2}) returns None
shapeRatio({1, 2, 10, 32}, {2, 5, 2}) returns {1, 1, 2, 16}
Definition at line 111 of file VectorUtils.cpp.
References copy().
Referenced by generateExtractSlicesOpResultType(), generateTransferOpSlices(), getEnclosingforOps(), initUnrolledVectorState(), mlir::vector::UnrollVectorPattern::matchAndRewrite(), shapeRatio(), and unrollSingleResultStructuredOp().
shapeRatio() [2/2]
Optional< SmallVector< int64_t, 4 > > mlir::shapeRatio (VectorType superVectorType, VectorType subVectorType)
Computes and returns the multi-dimensional ratio of the shapes of superVector to subVector.
If integral division is not possible, returns None. Assumes and enforces that the VectorTypes have the same elemental type.
Definition at line 147 of file VectorUtils.cpp.
References mlir::VectorType::getShape(), and shapeRatio().
simplifyAffineExpr()
AffineExpr mlir::simplifyAffineExpr (AffineExpr expr, unsigned numDims, unsigned numSymbols)
Simplify an affine expression by flattening and some amount of simple analysis.
Simplify the affine expression by flattening it and reconstructing it.
This has complexity linear in the number of nodes in 'expr'. Returns the simplified expression, which is the same as the input expression if it can't be simplified.
Definition at line 1072 of file AffineExpr.cpp.
References getAffineExprFromFlatForm(), mlir::AffineExpr::getContext(), mlir::AffineExpr::isPureAffine(), mlir::SimpleAffineExprFlattener::localExprs, mlir::SimpleAffineExprFlattener::operandExprStack, simplifySemiAffine(), and mlir::AffineExprVisitor< SubClass, RetTy >::walkPostOrder().
Referenced by canonicalizeStridedLayout(), mlir::AffineExpr::cast(), createPrivateMemRef(), getConstDifference(), mlir::FlatAffineConstraints::getSliceBounds(), getStridesAndOffset(), mlir::edsc::ops::linalg_generic_conv_nhwc(), mlir::edsc::ops::linalg_generic_dilated_conv_nhwc(), makeCanonicalStridedLayoutExpr(), mlir::MutableAffineMap::simplify(), and simplifyAffineMap().
simplifyAffineMap()
AffineMap mlir::simplifyAffineMap (AffineMap map)
Simplifies an affine map by simplifying its underlying AffineExpr results.
Definition at line 398 of file AffineMap.cpp.
References mlir::AffineMap::get(), mlir::AffineMap::getContext(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumSymbols(), mlir::AffineMap::getResults(), and simplifyAffineExpr().
Referenced by mlir::FlatAffineConstraints::addLowerOrUpperBound(), mlir::AffineApplyNormalizer::AffineApplyNormalizer(), mlir::AffineValueMap::difference(), generatePointWiseCopy(), mlir::MemRefAccess::getAccessMap(), getCleanupLoopLowerBound(), mlir::MutableAffineMap::getContext(), mlir::linalg::AffineMinSCFCanonicalizationPattern::matchAndRewrite(), replaceAllMemRefUsesWith(), replaceUnitDims(), substitute(), and verifyOutputShape().
simplifyIntegerSet()
IntegerSet mlir::simplifyIntegerSet (IntegerSet set)
Simplify the integer set by simplifying the underlying affine expressions by flattening and some simple inference.
Also, drop any duplicate constraints. Returns the simplified integer set. This method runs in time linear in the number of constraints.
Definition at line 1089 of file Utils.cpp.
References mlir::FlatAffineConstraints::getAsIntegerSet(), mlir::IntegerSet::getEmptySet(), mlir::FlatAffineConstraints::isEmpty(), and mlir::FlatAffineConstraints::removeTrivialRedundancy().
simplifyRegions()
LogicalResult mlir::simplifyRegions (MutableArrayRef< Region > regions)
Run a set of structural simplifications over the given regions.
This includes transformations like unreachable block elimination, dead argument elimination, as well as some other DCE. This function returns success if any of the regions were simplified, failure otherwise.
Definition at line 696 of file RegionUtils.cpp.
References eraseUnreachableBlocks(), mergeIdenticalBlocks(), runRegionDCE(), succeeded(), and success().
Referenced by areValuesDefinedAbove().
sinkOperationsIntoLaunchOp()
LogicalResult mlir::sinkOperationsIntoLaunchOp (gpu::LaunchOp launchOp)
Sink operations into the launchOp to reduce the number of values that are used within the region of the operation, but defined outside of the region.
Definition at line 106 of file KernelOutlining.cpp.
References mlir::OpBuilder::clone(), extractBeneficiaryOps(), mlir::Operation::getResults(), getUsedValuesDefinedAbove(), replaceAllUsesInRegionWith(), and success().
Referenced by convertToLaunchFuncOp().
sinkSequentialLoops()
AffineForOp mlir::sinkSequentialLoops (AffineForOp forOp)
Definition at line 1568 of file LoopUtils.cpp.
References checkLoopInterchangeDependences(), getDependenceComponents(), getPerfectlyNestedLoops(), mlir::matcher::isParallelLoop(), mlir::DependenceComponent::lb, permuteLoops(), and mlir::DependenceComponent::ub.
Referenced by isFusionProfitable(), and sinkSequentialLoops().
splitAndProcessBuffer()
LogicalResult mlir::splitAndProcessBuffer (std::unique_ptr< llvm::MemoryBuffer > originalBuffer, ChunkBufferHandler processChunkBuffer, raw_ostream & os)
Splits the specified buffer on a marker (// -----), processes each chunk independently according to the normal processChunkBuffer logic, and writes all results to os.
This is used to allow a large number of small independent tests to be put into a single file.
Definition at line 21 of file ToolUtilities.cpp.
References failed(), and failure().
Referenced by mlirTranslateMain(), and processBuffer().
structFuncArgTypeConverter()
LogicalResult mlir::structFuncArgTypeConverter (LLVMTypeConverter & converter, Type type, SmallVectorImpl< Type > & result)
Callback to convert function argument types.
Give structFuncArgTypeConverter access to memref-specific functions.
It converts a MemRef function argument to a list of non-aggregate types containing descriptor information, and an UnrankedmemRef function argument to a list containing the rank and a pointer to a descriptor struct.
Definition at line 59 of file StandardToLLVM.cpp.
References mlir::TypeConverter::convertType(), mlir::Type::dyn_cast(), failure(), mlir::Type::isa(), and success().
succeeded()
bool mlir::succeeded (LogicalResult result) inline
Utility function that returns true if the provided LogicalResult corresponds to a success value.
Definition at line 40 of file LogicalResult.h.
References mlir::LogicalResult::Success, and mlir::LogicalResult::value.
Referenced by affineDataCopyGenerate(), applyPatternsAndFoldGreedily(), canonicalizeLoopBounds(), collectSymbolScopes(), mlir::MemRefRegion::compute(), computeReshapeCollapsedType(), convertScalarType(), mlir::TypeConverter::convertType(), convertVectorType(), mlir::OpBuilder::createOrFold(), createPrivateMemRef(), deleteDeadness(), mlir::detail::DiagnosticEngineImpl::emit(), extractStrides(), mlir::Operation::fold(), foldExtractFromShapeCast(), foldExtractStridedOpFromInsertChain(), foldLoopBounds(), mlir::op_definition_impl::foldTraitsImpl(), foldTransferMaskAttribute(), mlir::MemRefDescriptor::fromStaticShape(), gatherInnermostLoops(), mlir::linalg::generateLibraryCallName(), generateShiftedLoop(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::ComputationSliceState::getAsConstraints(), mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::getFromOpaquePointer(), getNewNumDimsSymbols(), getPhiIncomingBlock(), mlir::ConvertToLLVMPattern::getStridedElementPtr(), getStridesAndOffset(), hasSizeMismatch(), inferTransposeResultType(), initializeAliases(), mlir::detail::PDLByteCode::initializeMutableState(), inlineCallsInSCC(), isFnEntryBlock(), isFusionLegal(), isStrided(), mlir::detail::constant_op_binder< AttrT >::match(), mlir::PatternApplicator::matchAndRewrite(), mlir::RewritePattern::matchAndRewrite(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), mlir::OpRewritePattern< vector::ContractionOp >::matchAndRewrite(), mlir::ConversionPattern::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite(), mlir::ConvertOpToLLVMPattern< gpu::ReturnOp >::matchAndRewrite(), mergeIdenticalBlocks(), mlirOperationVerify(), normalizeAffineFor(), mlir::detail::ConversionPatternRewriterImpl::notifyRegionWasClonedBefore(), parseAffineForOp(), parseAffineParallelOp(), parseAllocateAndAllocator(), parseAnyType(), parseAsyncDependencies(), parseAttributions(), parseBranchConditionalOp(), parseCommonStructuredOpParts(), parseControlAttribute(), parseCreateOperationOp(), parseExecuteOp(), parseForOp(), mlir::impl::parseFunctionArgumentList(), parseFunctionResultList(), mlir::impl::parseFunctionSignature(), parseGenericOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUFuncOp(), parseGroupNonUniformArithmeticOp(), parseInterfaceVarABIAttr(), parseKeywordList(), parseLandingpadOp(), parseListOfOperandsOrIntegers(), parseLoadOp(), parseLoopOp(), parseModuleOp(), parseNamedStructuredOpResults(), parseOperandAndTypeList(), parseOperandList(), parseOperationOp(), mlir::detail::Parser::parseOptionalAttribute(), mlir::detail::Parser::parseOptionalInteger(), parseOptionalKeywordAlternative(), parseOptionalOperand(), parseOptionalOperandAndType(), parseParallelOp(), parserOptionalOperandAndTypeWithPrefix(), parseSelectOp(), parseSpecConstantOp(), parseStoreOp(), parseStructMemberDecorations(), parseStructType(), parseTargetEnvAttr(), mlir::OpAsmParser::parseTypeList(), parseUniformType(), parseVariableDecorations(), parseVariableOp(), printDenseElementsAttrImpl(), printElidedElementsAttr(), mlir::LLVM::LLVMType::setStructTyBody(), simplifyRegions(), mlir::vector::splitFullAndPartialTransfer(), mlir::LLVM::detail::TypeFromLLVMIRTranslatorImpl::translateType(), tryIsolateBands(), mlir::linalg::vectorizeLinalgOp(), verify(), mlir::op_definition_impl::verifyTraitsImpl(), and wrap().
success()
LogicalResult mlir::success (bool isSuccess = true) inline
Utility function to generate a LogicalResult.
If isSuccess is true a success result is generated, otherwise a 'failure' result is generated.
Definition at line 26 of file LogicalResult.h.
References mlir::LogicalResult::Failure, and mlir::LogicalResult::Success.
Referenced by ableToUpdatePredOperands(), mlir::FlatAffineConstraints::addAffineForOpDomain(), mlir::FlatAffineConstraints::addLowerOrUpperBound(), addMemRefAccessConstraints(), addMissingLoopIVBounds(), mlir::FlatAffineConstraints::addSliceBounds(), mlir::PassPipelineCLParser::addToPipeline(), mlir::OpAsmParser::addTypesToList(), mlir::OpAsmParser::addTypeToList(), affineForOpBodySkew(), allocateBuffersForResults(), analyzeProfitability(), applyCmpPredicate(), applyMapToValues(), applyPatternsAndFoldGreedily(), mlir::linalg::applyStagedPatterns(), areAllLLVMTypes(), barePtrFuncArgTypeConverter(), mlir::ConstantIndexOp::build(), buildAffineLoopNest(), canFoldIntoConsumerOp(), mlir::AffineValueMap::canonicalize(), canonicalizeLoopBounds(), canonicalizeSetAndOperands(), checkAffineLoopNestMappable(), checkAffineLoopNestMappableImpl(), mlir::linalg::LinalgMarker::checkAndNotify(), checkAndUpdateCapabilityRequirements(), checkAndUpdateExtensionRequirements(), checkCapabilityRequirements(), checkCompatibleReturnType< float >(), checkCompatibleReturnType< int32_t >(), checkCompatibleReturnType< int64_t >(), checkedAddLLVMFnAttribute(), checkExtensionRequirements(), checkIfHyperRectangular(), checkTensorElementType(), checkTilingLegality(), collapseBranch(), collapseReassociationMaps(), collectValidReferencesFor(), compileAndExecute(), compileAndExecuteSingleReturnFunction(), mlir::FlatAffineConstraints::composeMap(), mlir::FlatAffineConstraints::composeMatchingMap(), mlir::MemRefRegion::compute(), computeConversionSet(), computeLocalVars(), computeSliceUnion(), mlir::AffineMap::constantFold(), mlir::FlatAffineConstraints::constantFoldId(), convertAffineLoopNestToGPULaunch(), mlir::TypeConverter::convertBlockSignature(), mlir::LLVM::ModuleTranslation::convertOmpMaster(), mlir::LLVM::ModuleTranslation::convertOmpOperation(), mlir::LLVM::ModuleTranslation::convertOmpParallel(), mlir::LLVM::ModuleTranslation::convertOperation(), convertPDLToPDLInterp(), convertRangeType(), mlir::TypeConverter::convertSignatureArg(), mlir::TypeConverter::convertSignatureArgs(), convertStructType(), mlir::TypeConverter::convertType(), mlir::TypeConverter::convertTypes(), createAffineDataCopyGenerationPass(), createFullTiles(), createGenericOpFromNamedOp(), mlir::ValueDecomposer::decomposeValue(), defaultDeallocBufferCallBack(), mlir::ContractionOpToMatmulOpLowering::defaultFilter(), mlir::ContractionOpToOuterProductOpLowering::defaultFilter(), mlir::ContractionOpToDotLowering::defaultFilter(), mlir::ContractionOpLowering::defaultFilter(), deleteDeadness(), encodeInstructionInto(), encodeKernelName(), mlir::spirv::encodeStringLiteralInto(), eraseUnreachableBlocks(), extractCompositeElement(), extractStrides(), extractValueFromConstOp(), finalizeBufferAllocation(), mlir::Operation::fold(), foldExtractOpFromExtractChain(), foldExtractOpFromTranspose(), foldExtractStridedOpFromInsertChain(), foldLoopBounds(), foldMemRefCast(), mlir::op_definition_impl::foldTrait(), mlir::op_definition_impl::foldTraitsImpl(), foldTransferMaskAttribute(), forwardPassthroughAttributes(), mlir::linalg::fuseTensorOps(), fuseWithReshapeByExpansion(), generateCopy(), generateCopyForMemRegion(), generateLocationsFromIR(), genStmt(), mlir::ComputationSliceState::getAsConstraints(), getAtomicOpScope(), getBase(), getBasePtr(), mlir::DialectAsmParser::getCurrentLocation(), mlir::OpAsmParser::getCurrentLocation(), getDefaultABIAttrs(), mlir::spirv::getElementPtr(), getFlattenedAffineExprs(), getFlattenedAffineExprs(), mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::getFromOpaquePointer(), getGenericEffectsImpl(), getIndexedPtrs(), getIndexSet(), getInterfaceVariables(), getKernelGlobalVariables(), getLaunchConfigIndex(), getLLVMAtomicOrdering(), getLocalInvocationDimSize(), getMemRefAlignment(), getMemRefSizeInBytes(), mlir::detail::PassOptions::getOptionWidth(), mlir::OperationFolder::getOrCreateConstant(), getOrCreateRanges(), mlir::scf::getParallelForInductionVarOwner(), getPhiIncomingBlock(), getStridesAndOffset(), getTransferOpAdapter(), handleMultidimensionalVectors(), hasSizeMismatch(), hoistAffineIfOp(), hoistOpsBetween(), mlir::detail::inferReturnTensorTypes(), initializeAliases(), inlineCall(), inlineCallsInSCC(), inlineRegion(), mlir::linalg::interchangeGenericLinalgOpPrecondition(), mlir::ExecutionEngine::invoke(), isAsyncWithOneDependency(), isContraction(), isElementwiseMappableOpOnRankedTensors(), isFnEntryBlock(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), isIntegerArrayAttrSmallerThanShape(), isSumOfIntegerArrayAttrConfinedToShape(), isValidExtractOrInsertSlicesType(), joinShapes(), mlir::linalg::linalgOpToAffineLoops(), mlir::linalg::linalgOpToLoops(), linalgOpToLoopsImpl(), mlir::linalg::linalgOpToParallelLoops(), logFailure(), lookupSymbolInImpl(), loopUnrollByFactor(), loopUnrollJamByFactor(), lowerAffineLowerBound(), lowerEntryPointABIAttr(), lowerLinalgToLoopsImpl(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::linalg::LinalgOpToLibraryCallRewrite::matchAndRewrite(), mlir::OpToFuncCallLowering< SourceOp >::matchAndRewrite(), mlir::GPUIndexIntrinsicOpLowering< Op, XOp, YOp, ZOp >::matchAndRewrite(), mlir::linalg::CopyOpToLibraryCallRewrite::matchAndRewrite(), mlir::PatternApplicator::matchAndRewrite(), mlir::linalg::CopyTransposeRewrite::matchAndRewrite(), mlir::linalg::IndexedGenericOpToLibraryCallRewrite::matchAndRewrite(), mlir::vector::UnrollVectorPattern::matchAndRewrite(), mlir::GPUReturnOpLowering::matchAndRewrite(), mlir::RewritePattern::matchAndRewrite(), mlir::vector::VectorTransferFullPartialRewriter::matchAndRewrite(), mlir::OpRewritePattern< vector::ContractionOp >::matchAndRewrite(), mlir::vector::PointwiseExtractPattern::matchAndRewrite(), mlir::ContractionOpToMatmulOpLowering::matchAndRewrite(), mlir::ConversionPattern::matchAndRewrite(), mlir::ContractionOpToOuterProductOpLowering::matchAndRewrite(), mlir::ContractionOpToDotLowering::matchAndRewrite(), mlir::OpConversionPattern< SPIRVOp >::matchAndRewrite(), mlir::linalg::LinalgTilingPattern< OpTy >::matchAndRewrite(), mlir::ContractionOpLowering::matchAndRewrite(), mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), mlir::linalg::LinalgBaseInterchangePattern::matchAndRewrite(), mlir::linalg::LinalgBasePromotionPattern::matchAndRewrite(), mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite(), mlir::linalg::LinalgBaseVectorizationPattern::matchAndRewrite(), mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite(), mlir::ConvertOpToLLVMPattern< gpu::ReturnOp >::matchAndRewrite(), mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite(), mlir::linalg::AffineMinSCFCanonicalizationPattern::matchAndRewrite(), mlir::linalg::ConvOpVectorization< ConvOp, N >::matchAndRewrite(), TransferReadExtractPattern::matchAndRewrite(), TransferWriteInsertPattern::matchAndRewrite(), mlir::linalg::LinalgBaseTilingPattern::matchAndRewriteBase(), matchSimpleAtomicOp(), mlir::TypeConverter::materializeTargetConversion(), mergeIdenticalBlocks(), MlirOptMain(), mlirTranslateMain(), mlir::LLVM::detail::LLVMStructTypeStorage::mutate(), mlir::spirv::detail::StructTypeStorage::mutate(), normalizeMemRef(), mlir::LLVM::detail::oneToOneRewrite(), mlir::FailureOr< T >::operator LogicalResult(), GpuAsyncRegionPass::ThreadTokenCallback::operator()(), outlineExecuteOp(), mlir::detail::ParallelDiagnosticHandlerImpl::ParallelDiagnosticHandlerImpl(), mlir::AffineDmaStartOp::parse(), mlir::DmaStartOp::parse(), mlir::DmaWaitOp::parse(), mlir::AffineDmaWaitOp::parse(), parseAccessChainOp(), parseAffineApplyOp(), parseAffineIfOp(), mlir::detail::Parser::parseAffineMapReference(), parseAffineParallelOp(), parseAffinePrefetchOp(), parseAllocaOp(), parseAllocateAndAllocator(), parseAssumingOp(), parseAtomicBinOp(), parseAtomicCmpXchgOp(), parseAtomicOrdering(), parseAtomicRMWOp(), mlir::detail::Parser::parseAttribute(), mlir::DialectAsmParser::parseAttribute(), mlir::OpAsmParser::parseAttribute(), mlir::detail::Parser::parseAttributeDict(), parseAttributions(), parseAwaitResultType(), parseBound(), parseBranchConditionalOp(), parseCallOp(), mlir::detail::Parser::parseCallSiteLocation(), parseCmpOp(), mlir::OpAsmParser::parseColonType(), mlir::detail::Parser::parseCommaSeparatedList(), mlir::detail::Parser::parseCommaSeparatedListUntil(), parseCommonStructuredOpParts(), parseCompositeExtractOp(), parseConstShapeOp(), parseContractionOp(), parseControlAttribute(), parseCooperativeMatrixLoadNVOp(), parseCooperativeMatrixStoreNVOp(), parseCopyMemoryOp(), parseCreateOperationOp(), mlir::detail::Parser::parseDimensionListRanked(), parseDynamicTensorFromElementsOp(), parseElementAttrHexValues(), parseEntryPointOp(), parseEnumKeywordAttr(), parseEnumKeywordAttr(), parseEnumStrAttr(), parseExecuteOp(), parseExecutionModeOp(), parseExtractElementOp(), parseExtractValueOp(), parseFenceOp(), parseForOp(), mlir::detail::PassOptions::parseFromString(), mlir::impl::parseFunctionArgumentList(), parseFunctionLibraryOp(), mlir::impl::parseFunctionLikeOp(), parseFunctionResultList(), mlir::detail::Parser::parseFunctionResultTypes(), mlir::impl::parseFunctionSignature(), mlir::detail::Parser::parseFusedLocation(), parseGenericAtomicRMWOp(), parseGenericOp(), parseGlobalMemrefOpTypeAndInitialValue(), parseGlobalOp(), parseGlobalVariableOp(), parseGPUModuleOp(), parseIfOp(), parseInsertElementOp(), parseInsertValueOp(), mlir::detail::Parser::parseIntegerSetReference(), parseInvokeOp(), mlir::DialectAsmParser::parseKeyword(), mlir::OpAsmParser::parseKeyword(), parseKeywordList(), parseLandingpadOp(), parseLaunchFuncOperands(), parseListOfOperandsOrIntegers(), parseLoadOp(), mlir::detail::Parser::parseLocationInstance(), parseLogicalBinaryOp(), parseLogicalUnaryOp(), parseLoopOp(), parseMemoryAccessAttributes(), mlir::detail::Parser::parseMemRefType(), parseModuleOp(), parseNamedStructuredOp(), parseNamedStructuredOpRegion(), parseNamedStructuredOpResults(), mlir::detail::Parser::parseNameOrFileLineColLocation(), parseOperandAndType(), parseOperandAndTypeList(), parseOperandList(), parseOperationOp(), parseOptionalArrayStride(), mlir::detail::Parser::parseOptionalAttribute(), mlir::detail::Parser::parseOptionalAttributeWithToken(), mlir::detail::Parser::parseOptionalInteger(), mlir::DialectAsmParser::parseOptionalInteger(), mlir::OpAsmParser::parseOptionalInteger(), parseOptionalLLVMKeyword(), parseOptionalOperand(), mlir::impl::parseOptionalVisibilityKeyword(), parseParallelOp(), parsePassPipeline(), parsePrefetchOp(), mlir::detail::Parser::parsePrettyDialectSymbolName(), parseQuantParams(), parseReduceOp(), parseReductionOp(), parseRegions(), parseReturnOp(), parseROCDLMubufStoreOp(), parseShiftOp(), parseShuffleOp(), parseShuffleVectorOp(), parseSourceMemoryAccessAttributes(), parseSpecConstantCompositeOp(), parseSpecConstantOp(), parseStorageRange(), parseStoreOp(), mlir::detail::Parser::parseStridedLayout(), mlir::detail::Parser::parseStrideList(), parseStructMemberDecorations(), parseSubgroupBlockReadINTELOp(), parseSubgroupBlockWriteINTELOp(), mlir::OpAsmParser::parseSymbolName(), mlir::detail::Parser::parseToken(), parseTransposeOp(), parseTupleGetOp(), mlir::DialectAsmParser::parseType(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::parseTypeList(), mlir::detail::Parser::parseTypeListNoParens(), mlir::detail::Parser::parseTypeListParens(), parseUnaryOp(), parseVariableDecorations(), parseVariableOp(), parseVerCapExtAttr(), mlir::detail::Parser::parseXInDimensionList(), mlir::PassPipelineRegistration< Options >::PassPipelineRegistration(), mlir::PassPipelineRegistration< EmptyPipelineOptions >::PassPipelineRegistration(), performActions(), mlir::vector::PointwiseExtractPattern::PointwiseExtractPattern(), populateBufferizeMaterializationLegality(), populateCallOpTypeConversionPattern(), populatePassManagers(), print(), printGPUFuncOp(), printLLVMFuncOp(), processParallelLoop(), produceSubViewErrorMsg(), promoteIfSingleIteration(), mlir::linalg::promoteSubviewsPrecondition(), registerArmNeonToLLVMIRTranslation(), registerArmSVEToLLVMIRTranslation(), registerAVX512ToLLVMIRTranslation(), mlir::DiagnosticEngine::registerHandler(), registerToLLVMIRTranslation(), registerToNVVMIRTranslation(), registerToROCDLIRTranslation(), registerTranslateToMLIRFunction(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), replaceAllMemRefUsesWith(), replaceAllSymbolUsesImpl(), replaceBlockArgForUnitDimLoops(), replaceBlockArgForUnitDimLoops< IndexedGenericOp >(), replaceOpWithRegion(), replaceSCFOutputValue(), replaceTransferOpWithLoadOrStore(), replaceTransferOpWithMasked(), replaceTransferOpWithMubuf(), replaceUnitExtents(), replaceWithLoadOrStore(), reshapeLowerToHigher(), mlir::OpAsmParser::resolveOperands(), resolveSourceIndices(), roundTripModule(), runRegionDCE(), runTransformOnCGSCCs(), separateFullTiles(), serializeModule(), mlir::FlatAffineConstraints::setIdValues(), mlir::gpu::setMappingAttr(), mlir::OpPassManager::setNesting(), mlir::Simplex::Simplex(), simplifyRegions(), sinkOperationsIntoLaunchOp(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), mlir::vector::splitFullAndPartialTransfer(), mlir::vector::splitFullAndPartialTransferPrecondition(), structFuncArgTypeConverter(), tilePerfectlyNested(), tilePerfectlyNestedParametric(), mlir::linalg::CodegenStrategy::transform(), mlir::OpBuilder::tryFold(), tryIsolateBands(), mlir::OperationFolder::tryToFold(), mlir::FlatAffineConstraints::unionBoundingBox(), mlir::vector::unrollSingleResultVectorOp(), mlir::vector::unrollTransferWriteOp(), unwrap(), updateSymbolAndAllUses(), vectorizeAffineForOp(), mlir::linalg::vectorizeLinalgOpPrecondition(), vectorizeLoopNest(), vectorizeLoopsAndLoads(), vectorizeNonTerminals(), vectorizeOneOperation(), vectorizeRootOrTerminal(), mlir::LLVM::detail::vectorOneToOneRewrite(), mlir::vector::VectorTransferFullPartialRewriter::VectorTransferFullPartialRewriter(), verify(), mlir::AffineDmaStartOp::verify(), mlir::DmaStartOp::verify(), mlir::OpState::verify(), mlir::DmaWaitOp::verify(), mlir::AffineDmaWaitOp::verify(), verify(), verifyAffineMinMaxOp(), verifyAllocLikeOp(), verifyAllReduce(), mlir::OpTrait::impl::verifyAtLeastNOperands(), mlir::OpTrait::impl::verifyAtLeastNRegions(), mlir::OpTrait::impl::verifyAtLeastNResults(), verifyAtomicUpdateOp(), verifyAttributions(), verifyBlockReadWritePtrAndValTypes(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyBody(), mlir::detail::verifyBranchSuccessorOperands(), verifyCastOp(), mlir::OpTrait::impl::verifyCompatibleOperandBroadcast(), verifyCompatibleShape(), mlir::quant::QuantizedType::verifyConstructionInvariants(), mlir::spirv::InterfaceVarABIAttr::verifyConstructionInvariants(), mlir::ComplexType::verifyConstructionInvariants(), mlir::spirv::VerCapExtAttr::verifyConstructionInvariants(), mlir::IntegerType::verifyConstructionInvariants(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::verifyConstructionInvariants(), mlir::spirv::TargetEnvAttr::verifyConstructionInvariants(), mlir::FloatAttr::verifyConstructionInvariants(), mlir::quant::AnyQuantizedType::verifyConstructionInvariants(), mlir::OpaqueType::verifyConstructionInvariants(), mlir::IntegerAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedType::verifyConstructionInvariants(), mlir::LLVM::LLVMArrayType::verifyConstructionInvariants(), mlir::OpaqueAttr::verifyConstructionInvariants(), mlir::quant::UniformQuantizedPerAxisType::verifyConstructionInvariants(), mlir::LLVM::LLVMFunctionType::verifyConstructionInvariants(), mlir::VectorType::verifyConstructionInvariants(), mlir::LLVM::LLVMIntegerType::verifyConstructionInvariants(), mlir::LLVM::LLVMPointerType::verifyConstructionInvariants(), mlir::quant::CalibratedQuantizedType::verifyConstructionInvariants(), mlir::spirv::MatrixType::verifyConstructionInvariants(), mlir::LLVM::LLVMStructType::verifyConstructionInvariants(), mlir::LLVM::LLVMVectorType::verifyConstructionInvariants(), mlir::UnrankedMemRefType::verifyConstructionInvariants(), verifyConvOp(), verifyCoopMatrixMulAdd(), verifyDependencies(), verifyDimAndSymbolIdentifiers(), mlir::OpTrait::impl::verifyElementwiseMappable(), verifyFloatTypeInvariants(), verifyGenericOp(), verifyGroupNonUniformArithmeticOp(), verifyHasBindingUseInMatcher(), verifyIndexOp(), mlir::detail::verifyInferredResultTypes(), verifyIntegerTypeInvariants(), mlir::OpTrait::impl::verifyIsIdempotent(), mlir::OpTrait::impl::verifyIsInvolution(), mlir::OpTrait::impl::verifyIsTerminator(), verifyLoadStorePtrAndValTypes(), verifyLoopOp(), verifyMatrixTimesMatrix(), verifyMatrixTimesScalar(), verifyMemoryAccessAttribute(), verifyMemoryOpIndexing(), verifyMemorySemantics(), verifyNamedStructuredOp(), mlir::OpTrait::impl::verifyNOperands(), mlir::OpTrait::impl::verifyNoRegionArguments(), mlir::OpTrait::impl::verifyNRegions(), mlir::OpTrait::impl::verifyNResults(), mlir::OpTrait::impl::verifyOneOperand(), mlir::OpTrait::impl::verifyOneRegion(), mlir::OpTrait::impl::verifyOneResult(), mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), mlir::Dialect::verifyOperationAttribute(), verifyOpWithOffsetSizesAndStridesPart(), verifyOutputShape(), verifyParallelOp(), verifyPermutationMap(), verifyPointerAndCoopMatrixType(), mlir::Dialect::verifyRegionArgAttribute(), verifyRegionAttribute(), verifyRegionOp(), mlir::Dialect::verifyRegionResultAttribute(), verifyReshapeLikeTypes(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike(), verifyResultTypesAreInferrable(), mlir::OpTrait::impl::verifySameOperandsAndResultElementType(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), mlir::OpTrait::impl::verifySameOperandsElementType(), mlir::OpTrait::impl::verifySameOperandsShape(), mlir::OpTrait::impl::verifySameTypeOperands(), verifyShapeOrExtentTensorOp(), verifyShiftOp(), verifyShuffleOp(), verifySingleInputPoolingOp(), verifySizeOrIndexOp(), verifySourceMemoryAccessAttribute(), verifyStrideOrDilation(), mlir::detail::verifySymbol(), mlir::detail::verifySymbolTable(), verifyTerminatorSuccessors(), mlir::OpTrait::linalg::StructuredOpTraits< ConcreteType >::verifyTrait(), mlir::OpTrait::ReturnLike< ConcreteType >::verifyTrait(), mlir::OpTrait::linalg::NamedStructuredOpTrait< ConcreteType >::verifyTrait(), mlir::OpTrait::SingleBlockImplicitTerminator< TerminatorOpType >::Impl< ConcreteType >::verifyTrait(), mlir::OpTrait::ConstantLike< ConcreteType >::verifyTrait(), mlir::OpTrait::IsIsolatedFromAbove< ConcreteType >::verifyTrait(), mlir::OpTrait::AffineScope< ConcreteType >::verifyTrait(), mlir::OpTrait::AutomaticAllocationScope< ConcreteType >::verifyTrait(), mlir::OpTrait::HasParent< ParentOpTypes >::Impl< ConcreteType >::verifyTrait(), mlir::op_definition_impl::verifyTraitsImpl(), verifyTransferOp(), verifyTranspose(), mlir::OpTrait::FunctionLike< ConcreteType >::verifyType(), verifyTypesAlongAllEdges(), mlir::detail::verifyTypesAlongControlFlowEdges(), verifyValueSizeAttr(), verifyVectorMemoryOp(), verifyVectorShapeCast(), verifyYield(), mlir::OpTrait::impl::verifyZeroOperands(), mlir::OpTrait::impl::verifyZeroRegion(), mlir::OpTrait::impl::verifyZeroResult(), mlir::OpTrait::impl::verifyZeroSuccessor(), visitInPrettyBlockOrder(), and wrapExternalFunction().
tile() [1/4]
SmallVector< SmallVector< AffineForOp, 8 >, 8 > mlir::tile (ArrayRef< AffineForOp > forOps, ArrayRef< uint64_t > sizes, ArrayRef< AffineForOp > targets)
Definition at line 1753 of file LoopUtils.cpp.
References tileImpl().
Referenced by extractFixedOuterLoops(), tileImpl(), and tilePerfectlyNested().
tile() [2/4]
SmallVector< Loops, 8 > mlir::tile (ArrayRef< scf::ForOp > forOps, ArrayRef< Value > sizes, ArrayRef< scf::ForOp > targets)
Definition at line 1758 of file LoopUtils.cpp.
References tileImpl().
tile() [3/4]
SmallVector< AffineForOp, 8 > mlir::tile (ArrayRef< AffineForOp > forOps, ArrayRef< uint64_t > sizes, AffineForOp target)
Performs tiling (with interchange) by strip-mining the forOps by sizes and sinking them, in their order of occurrence in forOps, under target.
Returns the new AffineForOps, one per forOps, nested immediately under target.
Definition at line 1775 of file LoopUtils.cpp.
References tileImpl().
tile() [4/4]
Loops mlir::tile (ArrayRef< scf::ForOp > forOps, ArrayRef< Value > sizes, scf::ForOp target)
Definition at line 1781 of file LoopUtils.cpp.
References tileImpl().
tilePerfectlyNested() [1/2]
LogicalResult mlir::tilePerfectlyNested (MutableArrayRef< AffineForOp > input, ArrayRef< unsigned > tileSizes, SmallVectorImpl< AffineForOp > * tiledNest = nullptr)
Tiles the specified band of perfectly nested loops creating tile-space loops and intra-tile loops.
A band is a contiguous set of loops.
Definition at line 902 of file LoopUtils.cpp.
References checkIfHyperRectangular(), constructTiledIndexSetHyperRect(), constructTiledLoopNest(), extractForInductionVars(), failed(), failure(), performPreTilingChecks(), and success().
Referenced by adjustToDivisorsOfTripCounts().
tilePerfectlyNested() [2/2]
Loops mlir::tilePerfectlyNested (scf::ForOp rootForOp, ArrayRef< Value > sizes)
Tile a nest of scf::ForOp loops rooted at rootForOp with the given (parametric) sizes.
Sizes are expected to be strictly positive values at runtime. If more sizes than loops are provided, discard the trailing values in sizes. Assumes the loop nest is permutable. Returns the newly created intra-tile loops.
Definition at line 1786 of file LoopUtils.cpp.
References getPerfectlyNestedLoopsImpl(), and tile().
tilePerfectlyNestedParametric()
LogicalResult mlir::tilePerfectlyNestedParametric (MutableArrayRef< AffineForOp > input, ArrayRef< Value > tileSizes, SmallVectorImpl< AffineForOp > * tiledNest = nullptr)
Tiles the specified band of perfectly nested loops creating tile-space loops and intra-tile loops, using SSA values as tiling parameters.
A band is a contiguous set of loops.
Definition at line 944 of file LoopUtils.cpp.
References checkIfHyperRectangular(), constructParametricallyTiledIndexSetHyperRect(), constructTiledLoopNest(), extractForInductionVars(), failed(), failure(), performPreTilingChecks(), and success().
topologicalSort()
llvm::SetVector<Operation *> mlir::topologicalSort (const llvm::SetVector< Operation *> & toSort)
Multi-root DAG topological sort.
Performs a topological sort of the Operation in the toSort SetVector. Returns a topologically sorted SetVector.
Referenced by mlir::LLVM::ModuleTranslation::convertOmpOpRegions(), DFSPostorder(), forwardPassthroughAttributes(), getSlice(), and vectorizeNonTerminals().
toString()
StringRef mlir::toString (IteratorType t) inline
Definition at line 126 of file StructuredOpsUtils.h.
References getParallelIteratorTypeName(), getReductionIteratorTypeName(), Parallel, and Reduction.
Referenced by mlir::edsc::makeGenericLinalgOp(), and mlir::edsc::ops::vector_contraction().
translateLLVMIRToModule()
OwningModuleRef mlir::translateLLVMIRToModule (std::unique_ptr< llvm::Module > llvmModule, MLIRContext * context)
Convert the given LLVM module into MLIR's LLVM dialect.
The LLVM context is extracted from the registered LLVM IR dialect. In case of error, report it to the error handler registered with the MLIR context, if any (obtained from the MLIR module), and return {}.
Definition at line 838 of file ConvertFromLLVMIR.cpp.
References failed(), mlir::FileLineColLoc::get(), and mlir::MLIRContext::loadDialect().
Referenced by translateLLVMIRToModule().
translateModuleToLLVMIR()
std::unique_ptr< llvm::Module > mlir::translateModuleToLLVMIR (ModuleOp m, llvm::LLVMContext & llvmContext, StringRef name = "LLVMDialectModule")
Convert the given MLIR module into LLVM IR.
The LLVM context is extracted from the registered LLVM IR dialect. In case of error, report it to the error handler registered with the MLIR context, if any (obtained from the MLIR module), and return nullptr.
Definition at line 27 of file ConvertToLLVMIR.cpp.
References emitError().
Referenced by mlir::ExecutionEngine::create().
translateModuleToNVVMIR()
std::unique_ptr<llvm::Module> mlir::translateModuleToNVVMIR (Operation * m, llvm::LLVMContext & llvmContext, llvm::StringRef name = "LLVMDialectModule")
Convert the given LLVM-module-like operation into NVVM IR.
This conversion requires the registration of the LLVM IR dialect and will extract the LLVM context from the registered LLVM IR dialect. In case of error, report it to the error handler registered with the MLIR context, if any (obtained from the MLIR module), and return nullptr.
Referenced by getShflBflyIntrinsicId(), and registerToNVVMIRTranslation().
translateModuleToROCDLIR()
std::unique_ptr<llvm::Module> mlir::translateModuleToROCDLIR (Operation * m, llvm::LLVMContext & llvmContext, llvm::StringRef name = "LLVMDialectModule")
Convert the given LLVM-module-like operation into ROCDL IR.
This conversion requires the registration of the LLVM IR dialect and will extract the LLVM context from the registered LLVM IR dialect. In case of error, report it to the error handler registered with the MLIR context, if any (obtained from the MLIR module), and return nullptr.
Referenced by createDeviceFunctionCall(), and registerToROCDLIRTranslation().
vectorizeAffineLoopNest()
LogicalResult mlir::vectorizeAffineLoopNest (std::vector< SmallVector< AffineForOp, 2 >> & loops, const VectorizationStrategy & strategy)
External utility to vectorize affine loops from a single loop nest using an n-D vectorization strategy (see doc in VectorizationStrategy definition).
Loops are provided in a 2D vector container. The first dimension represents the nesting level relative to the loops to be vectorized. The second dimension contains the loops. This means that: a) every loop in 'loops[i]' must have a parent loop in 'loops[i-1]', b) a loop in 'loops[i]' may or may not have a child loop in 'loops[i+1]'.
For example, for the following loop nest:
func (in0: memref<64x128x512xf32>, in1: memref<64x128x128xf32>, out0: memref<64x128x512xf32>, out1: memref<64x128x128xf32>) { affine.for i0 = 0 to 64 { affine.for i1 = 0 to 128 { affine.for i2 = 0 to 512 { ld = affine.load in0[i0, i1, i2] : memref<64x128x512xf32> affine.store ld, out0[i0, i1, i2] : memref<64x128x512xf32> } affine.for i3 = 0 to 128 { ld = affine.load in1[i0, i1, i3] : memref<64x128x128xf32> affine.store ld, out1[i0, i1, i3] : memref<64x128x128xf32> } } } return }
loops = {{i0}, {i2, i3}}, to vectorize the outermost and the two innermost loops; loops = {{i1}, {i2, i3}}, to vectorize the middle and the two innermost loops; loops = {{i2}}, to vectorize only the first innermost loop; loops = {{i3}}, to vectorize only the second innermost loop; loops = {{i1}}, to vectorize only the middle loop.
Definition at line 1419 of file SuperVectorize.cpp.
References vectorizeLoopNest(), and verifyLoopNesting().
vectorizeAffineLoops() [1/2]
void mlir::vectorizeAffineLoops (Operation * parentOp, llvm::DenseSet< Operation *, DenseMapInfo< Operation *>> & loops, ArrayRef< int64_t > vectorSizes, ArrayRef< int64_t > fastestVaryingPattern)
Vectorizes affine loops in 'loops' using the n-D vectorization factors in 'vectorSizes'.
By default, each vectorization factor is applied inner-to-outer to the loops of each loop nest. 'fastestVaryingPattern' can be optionally used to provide a different loop vectorization order.
vectorizeAffineLoops() [2/2]
void mlir::vectorizeAffineLoops (Operation * parentOp, DenseSet< Operation *> & loops, ArrayRef< int64_t > vectorSizes, ArrayRef< int64_t > fastestVaryingPattern)
External utility to vectorize affine loops in 'loops' using the n-D vectorization factors in 'vectorSizes'.
By default, each vectorization factor is applied inner-to-outer to the loops of each loop nest. 'fastestVaryingPattern' can be optionally used to provide a different loop vectorization order.
Definition at line 1375 of file SuperVectorize.cpp.
References vectorizeLoops().
verify() [1/2]
LogicalResult mlir::verify (Operation * op)
Perform (potentially expensive) checks of invariants, used to detect compiler bugs, on this operation and any nested operations.
Perform (potentially expensive) checks of invariants, used to detect compiler bugs.
On error, this reports the error through the MLIRContext and returns failure.
Definition at line 294 of file Verifier.cpp.
References mlir::Operation::getContext(), and verify().
verify() [2/2]
LogicalResult mlir::verify (OffsetSizeAndStrideOpInterface op)
Definition at line 38 of file ViewLikeInterface.cpp.
References failed(), failure(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), success(), and verifyOpWithOffsetSizesAndStridesPart().
Referenced by mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::getFromOpaquePointer(), getGenericEffectsImpl(), mlir::DmaWaitOp::getNumElements(), mlir::DmaStartOp::getOperationName(), mlirOperationVerify(), mlir::detail::Parser::parseOptionalInteger(), registerTranslateToMLIRFunction(), mlir::OpPassManager::setNesting(), verify(), and verify().
verifyCompatibleShape() [1/2]
LogicalResult mlir::verifyCompatibleShape (ArrayRef< int64_t > shape1, ArrayRef< int64_t > shape2)
Returns success if the given two shapes are compatible.
That is, they have the same size and each pair of the elements are equal or one of them is dynamic.
Definition at line 54 of file TypeUtilities.cpp.
References failure(), mlir::ShapedType::isDynamic(), and success().
Referenced by verify(), verifyCompatibleShape(), mlir::OpTrait::impl::verifySameOperandsAndResultShape(), mlir::OpTrait::impl::verifySameOperandsAndResultType(), and mlir::OpTrait::impl::verifySameOperandsShape().
verifyCompatibleShape() [2/2]
LogicalResult mlir::verifyCompatibleShape (Type type1, Type type2)
Returns success if the given two types have compatible shape.
That is, they are both scalars (not shaped), or they are both shaped types and at least one is unranked or they have compatible dimensions. Dimensions are compatible if at least one is dynamic or both are equal. The element type does not matter.
Definition at line 73 of file TypeUtilities.cpp.
References mlir::Type::dyn_cast(), failure(), mlir::ShapedType::getShape(), mlir::ShapedType::hasRank(), success(), and verifyCompatibleShape().
viewGraph() [1/2]
void mlir::viewGraph (Block & block, const Twine & name, bool shortNames = false, const Twine & title = "", llvm::GraphProgram::Name program = llvm::GraphProgram::DOT)
Displays the graph in a window.
This is for use from the debugger and depends on Graphviz to generate the graph.
Definition at line 153 of file ViewOpGraph.cpp.
Referenced by mlir::Region::viewGraph().
viewGraph() [2/2]
void mlir::viewGraph (Region & region, const Twine & name, bool shortNames = false, const Twine & title = "", llvm::GraphProgram::Name program = llvm::GraphProgram::DOT)
Displays the CFG in a window.
This is for use from the debugger and depends on Graphviz to generate the graph.
Definition at line 47 of file ViewRegionGraph.cpp.
visitUsedValuesDefinedAbove() [1/2]
void mlir::visitUsedValuesDefinedAbove (Region & region, Region & limit, function_ref< void(OpOperand *)> callback)
Calls callback for each use of a value within region or its descendants that was defined at the ancestors of the limit.
Definition at line 31 of file RegionUtils.cpp.
References mlir::Operation::getOpOperands(), mlir::Region::getParentRegion(), mlir::Region::isAncestor(), and mlir::Region::walk().
Referenced by areValuesDefinedAbove(), getUsedValuesDefinedAbove(), and visitUsedValuesDefinedAbove().
visitUsedValuesDefinedAbove() [2/2]
void mlir::visitUsedValuesDefinedAbove (MutableArrayRef< Region > regions, function_ref< void(OpOperand *)> callback)
Calls callback for each use of a value within any of the regions provided that was defined in one of the ancestors.
Definition at line 52 of file RegionUtils.cpp.
References visitUsedValuesDefinedAbove().
wouldOpBeTriviallyDead()
bool mlir::wouldOpBeTriviallyDead (Operation * op)
Return true if the given operation would be dead if unused, and has no side effects on memory that would prevent erasing.
This is equivalent to checking isOpTriviallyDead if op was unused.
Definition at line 93 of file SideEffectInterfaces.cpp.
References mlir::Operation::isKnownNonTerminator(), and wouldOpBeTriviallyDeadImpl().
Referenced by isOpTriviallyDead(), and verify().
writeGraph() [1/2]
raw_ostream & mlir::writeGraph (raw_ostream & os, Region & region, bool shortNames = false, const Twine & title = "")
Definition at line 52 of file ViewRegionGraph.cpp.
writeGraph() [2/2]
raw_ostream & mlir::writeGraph (raw_ostream & os, Block & block, bool shortNames = false, const Twine & title = "")
Definition at line 158 of file ViewOpGraph.cpp.
Referenced by mlir::Region::viewGraph().
Variable Documentation
kDeriveIndexBitwidthFromDataLayout
constexpr unsigned mlir::kDeriveIndexBitwidthFromDataLayout = 0 static
Value to pass as bitwidth for the index type when the converter is expected to derive the bitwidth from the LLVM data layout.
Definition at line 25 of file ConvertStandardToLLVMPass.h.
Referenced by encodeKernelName(), and mlir::LLVMTypeConverter::LLVMTypeConverter().
kUnknownNumRegionInvocations
const int64_t mlir::kUnknownNumRegionInvocations = -1
Definition at line 77 of file ControlFlowInterfaces.cpp.
Referenced by computeRegionBlockNumberOfExecutions().
makeLLVMPassesTransformer
std::function< llvm::Error(llvm::Module *)> mlir::makeLLVMPassesTransformer
Create a module transformer function for MLIR ExecutionEngine that runs LLVM IR passes explicitly specified, plus an optional optimization level, Any optimization passes, if present, will be inserted before the pass at position optPassesInsertPos.
If not null, targetMachine is used to initialize passes that provide target-specific information to the LLVM optimizer. targetMachine must outlive the returned std::function.
Definition at line 50 of file OptUtils.h.
Referenced by JitRunnerMain(), and populatePassManagers().
makeOptimizingTransformer
std::function< llvm::Error(llvm::Module *)> mlir::makeOptimizingTransformer
Create a module transformer function for MLIR ExecutionEngine that runs LLVM IR passes corresponding to the given speed and size optimization levels (e.g.
-O2 or -Os). If not null, targetMachine is used to initialize passes that provide target-specific information to the LLVM optimizer. targetMachine must outlive the returned std::function.
Definition at line 40 of file OptUtils.h.
Referenced by populatePassManagers().
nullIndex
const int mlir::nullIndex = std::numeric_limits<int>::max()
Definition at line 16 of file Simplex.cpp.