MLIR: mlir::LLVM::detail Namespace Reference
mlir::LLVM::detail Namespace Reference
Classes
class DebugTranslation
struct LLVMFunctionTypeStorage
Type storage for LLVM dialect function types.
struct LLVMIntegerTypeStorage
Storage type for LLVM dialect integer types. These are uniqued by bitwidth.
struct LLVMPointerTypeStorage
Storage type for LLVM dialect pointer types.
struct LLVMStructTypeStorage
Type storage for LLVM structure types.
struct LLVMTypeAndSizeStorage
Common storage used for LLVM dialect types that need an element type and a number: arrays, fixed and scalable vectors.
class TypeFromLLVMIRTranslatorImpl
Support for translating LLVM IR types to MLIR LLVM dialect types.
class TypeToLLVMIRTranslatorImpl
Support for translating MLIR LLVM dialect types to LLVM IR.
Functions
LogicalResult oneToOneRewrite (Operation *op, StringRef targetOp, ValueRange operands, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
Replaces the given operation "op" with a new operation of type "targetOp" and given operands.
LogicalResult vectorOneToOneRewrite (Operation *op, StringRef targetOp, ValueRange operands, LLVMTypeConverter &typeConverter, ConversionPatternRewriter &rewriter)
LLVMType parseType (DialectAsmParser &parser)
Parses an LLVM dialect type.
void printType (LLVMType type, DialectAsmPrinter &printer)
Prints an LLVM Dialect type.
Function Documentation
oneToOneRewrite()
LogicalResult mlir::LLVM::detail::oneToOneRewrite (Operation * op, StringRef targetOp, ValueRange operands, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter)
Replaces the given operation "op" with a new operation of type "targetOp" and given operands.
Definition at line 1568 of file StandardToLLVM.cpp.
References mlir::OperationState::addTypes(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::OpBuilder::createOperation(), mlir::ConversionPatternRewriter::eraseOp(), mlir::failure(), mlir::Operation::getAttrs(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getLoc(), mlir::Operation::getNumResults(), mlir::Operation::getResult(), mlir::Operation::getResultTypes(), mlir::Value::getType(), mlir::LLVMTypeConverter::packFunctionResults(), mlir::ConversionPatternRewriter::replaceOp(), and mlir::success().
Referenced by getSrcVectorElementType(), mlir::OneToOneConvertToLLVMPattern< SourceOp, TargetOp >::matchAndRewrite(), and vectorOneToOneRewrite().
parseType()
LLVMType mlir::LLVM::detail::parseType (DialectAsmParser & parser)
Parses an LLVM dialect type.
Definition at line 467 of file LLVMTypeSyntax.cpp.
Referenced by parseCalibratedType(), parseStructType(), and verifyShapeOrExtentTensorOp().
printType()
void mlir::LLVM::detail::printType (LLVMType type, DialectAsmPrinter & printer)
Prints an LLVM Dialect type.
Definition at line 174 of file LLVMTypeSyntax.cpp.
Referenced by mlir::Block::getSublistAccess(), getTransferOpAdapter(), operator<<(), print(), printCalibratedQuantizedType(), printDenseElementsAttrImpl(), printElidedElementsAttr(), verifyShapeOrExtentTensorOp(), and mlir::AsmState::~AsmState().
vectorOneToOneRewrite()
LogicalResult mlir::LLVM::detail::vectorOneToOneRewrite (Operation * op, StringRef targetOp, ValueRange operands, LLVMTypeConverter & typeConverter, ConversionPatternRewriter & rewriter)
Definition at line 1636 of file StandardToLLVM.cpp.
References mlir::OperationState::addTypes(), mlir::MemRefDescriptor::alignedPtr(), mlir::UnrankedMemRefDescriptor::alignedPtr(), mlir::MemRefDescriptor::allocatedPtr(), mlir::UnrankedMemRefDescriptor::allocatedPtr(), mlir::Attribute::cast(), mlir::Location::cast(), mlir::Type::cast(), mlir::OpBuilder::clone(), mlir::computeRankReductionMask(), mlir::UnrankedMemRefDescriptor::computeSizes(), mlir::TypeConverter::convertType(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), createIndexAttrConstant(), mlir::ConvertToLLVMPattern::createIndexConstant(), mlir::OpBuilder::createOperation(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::edsc::op::eq(), mlir::ConversionPatternRewriter::eraseOp(), extractFromI64ArrayAttr(), extractNDVectorTypeInfo(), mlir::failed(), mlir::failure(), mlir::VectorType::get(), mlir::MemRefType::get(), mlir::DenseElementsAttr::get(), mlir::LLVM::LLVMPointerType::getAddressSpace(), mlir::LLVM::LLVMType::getArrayTy(), mlir::Operation::getAttrs(), mlir::Builder::getBoolAttr(), mlir::Builder::getContext(), mlir::LLVMTypeConverter::getContext(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::MemRefDescriptor::getElementPtrType(), getElementPtrType(), getElementType(), mlir::getElementTypeOrSelf(), mlir::Builder::getFloatAttr(), mlir::LLVM::LLVMType::getFunctionTy(), mlir::Builder::getI32ArrayAttr(), mlir::Builder::getI32IntegerAttr(), mlir::Builder::getI32Type(), mlir::Builder::getI64ArrayAttr(), mlir::Builder::getI64IntegerAttr(), mlir::Builder::getIdentifier(), mlir::Builder::getIndexType(), mlir::LLVMTypeConverter::getIndexType(), mlir::ConvertToLLVMPattern::getIndexType(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), mlir::LLVM::LLVMType::getInt1Ty(), mlir::LLVM::LLVMType::getInt8PtrTy(), mlir::LLVM::LLVMType::getIntegerBitWidth(), mlir::Builder::getIntegerType(), mlir::Operation::getLoc(), mlir::Value::getLoc(), getMemRefEltSizeInBytes(), mlir::LLVM::LLVMType::getPointerTo(), mlir::Operation::getResult(), mlir::MemRefType::getShape(), mlir::getStridesAndOffset(), mlir::Builder::getSymbolRefAttr(), mlir::Value::getType(), mlir::ValueRange::getType(), mlir::ValueRange::getTypes(), mlir::Builder::getUnknownLoc(), mlir::ElementsAttr::getValue(), mlir::ConvertToLLVMPattern::getVoidPtrType(), mlir::LLVM::LLVMType::getVoidTy(), mlir::Builder::getZeroAttr(), handleMultidimensionalVectors(), mlir::Type::isa(), mlir::ShapedType::isDynamic(), mlir::ShapedType::isDynamicStrideOrOffset(), mlir::UnrankedMemRefDescriptor::memRefDescPtr(), mlir::mod(), nDVectorIterate(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::MemRefDescriptor::offset(), mlir::UnrankedMemRefDescriptor::offset(), oneToOneRewrite(), mlir::UnrankedMemRefDescriptor::rank(), mlir::MutableDictionaryAttr::remove(), mlir::ConversionPatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::UnrankedMemRefDescriptor::setAlignedPtr(), mlir::UnrankedMemRefDescriptor::setAllocatedPtr(), mlir::OpBuilder::setInsertionPointToEnd(), mlir::OpBuilder::setInsertionPointToStart(), mlir::UnrankedMemRefDescriptor::setOffset(), mlir::UnrankedMemRefDescriptor::setSize(), mlir::UnrankedMemRefDescriptor::setStride(), mlir::edsc::op::sge(), mlir::MemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::size(), mlir::UnrankedMemRefDescriptor::sizeBasePtr(), mlir::ConversionPatternRewriter::splitBlock(), mlir::UnrankedMemRefDescriptor::stride(), mlir::UnrankedMemRefDescriptor::strideBasePtr(), mlir::StructBuilder::structType, mlir::success(), mlir::ComplexStructBuilder::undef(), mlir::MemRefDescriptor::undef(), mlir::UnrankedMemRefDescriptor::undef(), and unwrap().
Referenced by mlir::VectorConvertToLLVMPattern< SourceOp, TargetOp >::matchAndRewrite().