MLIR: mlir::detail Namespace Reference
mlir::detail Namespace Reference
Namespaces
analysis_impl
Classes
struct AffineBinaryOpExprStorage
A binary operation appearing in an affine expression.
struct AffineConstantExprStorage
An integer constant appearing in affine expression.
struct AffineDimExprStorage
A dimensional or symbolic identifier appearing in an affine expression.
struct AffineExprStorage
Base storage class appearing in an affine expression.
struct AffineMapAttributeStorage
struct AffineMapStorage
struct AffineReadOpInterfaceInterfaceTraits
struct AffineWriteOpInterfaceInterfaceTraits
struct AnalysisConcept
The abstract polymorphic base class representing an analysis.
class AnalysisMap
This class represents a cache of analyses for a single operation.
struct AnalysisModel
A derived analysis model used to hold a specific analysis object.
struct AnyValueMatcher
Terminal matcher, always returns true.
struct ArrayAttributeStorage
An attribute representing an array of other attributes.
class AsmStateImpl
struct attr_value_binder
The matcher that matches a certain kind of Attribute and binds the value inside the Attribute.
class AttributeUniquer
struct BaseMemRefTypeStorage
class BlockArgumentImpl
The internal implementation of a BlockArgument.
class CallbackOstream
A simple raw ostream subclass that forwards write_impl calls to the user-supplied callback together with opaque user-supplied data.
struct CallSiteLocationStorage
struct ComplexTypeStorage
Complex Type Storage.
struct constant_int_not_value_matcher
The matcher that matches anything except the given target constant scalar / vector splat / tensor splat integer value.
struct constant_int_op_binder
The matcher that matches a constant scalar / vector splat / tensor splat integer operation and binds the constant integer value.
struct constant_int_value_matcher
The matcher that matches a given target constant scalar / vector splat / tensor splat integer value.
struct constant_op_binder
The matcher that matches operations that have the ConstantLike trait, and binds the folded attribute value.
struct constant_op_matcher
The matcher that matches operations that have the ConstantLike trait.
struct ConversionPatternRewriterImpl
class DenseElementDataPointerTypeTraits
DenseElementsAttr data is aligned to uint64_t, so this traits class is necessary to interop with PointerIntPair.
class DenseElementIndexedIteratorImpl
Impl iterator for indexed DenseElementsAttr iterators that records a data pointer and data index that is adjusted for the case of a splat attribute.
struct DenseElementsAttributeStorage
An attribute representing a reference to a dense vector or tensor object.
struct DenseIntOrFPElementsAttributeStorage
An attribute representing a reference to a dense vector or tensor object.
struct DenseStringElementsAttributeStorage
An attribute representing a reference to a dense vector or tensor object containing strings.
struct DiagnosticEngineImpl
class DialectInterfaceBase
The base class used for all derived interface types.
class DialectInterfaceCollectionBase
This class is the base class for a collection of instances for a specific interface kind.
struct DictionaryAttributeStorage
An attribute representing a dictionary of sorted named attributes.
class DominanceInfoBase
class ElementsAttrIterator
This class represents a general iterator over the values of an ElementsAttr.
class ElementsAttrRange
struct ExpectedDiag
struct FileLineColLocationStorage
struct FilterTypes
struct FilterTypeT
Utility to filter a given sequence of types base upon a predicate.
struct FilterTypeT< false >
struct FloatAttributeStorage
An attribute representing a floating point value.
struct FunctionTypeStorage
Function Type Storage and Uniquing.
struct FusedLocationStorage
struct InLineOpResult
This class provides the implementation for an in-line operation result.
struct IntegerAttributeStorage
An attribute representing an integral value.
struct IntegerSetAttributeStorage
struct IntegerSetStorage
struct IntegerTypeStorage
Integer Type Storage and Uniquing.
class Interface
This class represents an abstract interface.
class InterfaceMap
This class provides an efficient mapping between a given Interface type, and a particular implementation of its concept.
struct is_complex_t
Type trait detector that checks if a given type T is a complex type.
struct is_complex_t< std::complex< T > >
struct MemRefTypeStorage
struct NameLocationStorage
struct NestedAnalysisMap
An analysis map that contains a map for the current operation, and a set of maps for any child operations.
class op_filter_iterator
A utility iterator that filters out operations that are not 'OpT'.
class op_iterator
This class provides iteration over the held operations of a block for a specific operation type.
struct op_matcher
The matcher that matches a certain kind of op.
struct OpaqueAttributeStorage
Opaque Attribute Storage and Uniquing.
struct OpaqueElementsAttributeStorage
An attribute representing a reference to a tensor constant with opaque content.
struct OpaqueLocationStorage
struct OpaqueTypeStorage
Opaque Type Storage and Uniquing.
class OpaqueValue
This class provides an opaque type erased wrapper around a Value.
class OperandStorage
This class handles the management of operation operands.
struct OpPassManagerImpl
class OpToOpPassAdaptor
An adaptor pass used to run operation passes over nested operations.
struct ParallelDiagnosticHandlerImpl
class Parser
This class implement support for parsing global entities like attributes and types.
struct ParserState
This class refers to all of the state maintained globally by the parser, such as the current lexer position etc.
struct PassExecutionState
The state for a single execution of a pass.
struct PassInstrumentorImpl
class PassOptions
Base container class and manager for all pass options.
struct PassPipelineCLParserImpl
struct PatternMatcherValue
Binds to a specific value and matches it.
class PDLByteCode
The bytecode class is also the interpreter.
class PDLByteCodeMutableState
This class contains the mutable state of a bytecode instance.
class PDLByteCodePattern
All of the data pertaining to a specific pattern within the bytecode.
class PreservedAnalyses
A utility class to represent the analyses that are known to be preserved.
struct RankedTensorTypeStorage
struct RecursivePatternMatcher
RecursivePatternMatcher that composes.
struct SDBMBinaryExprStorage
struct SDBMConstantExprStorage
struct SDBMDiffExprStorage
struct SDBMExprStorage
struct SDBMNegExprStorage
struct SDBMTermExprStorage
struct ShapedTypeStorage
Shaped Type Storage.
struct SourceMgrDiagnosticHandlerImpl
struct SourceMgrDiagnosticVerifierHandlerImpl
struct SparseElementsAttributeStorage
An attribute representing a reference to a sparse vector or tensor object.
struct StorageUniquerImpl
This is the implementation of the StorageUniquer class.
class StorageUserBase
Utility class for implementing users of storage classes uniqued by a StorageUniquer.
class StorageUserTraitBase
Helper class for implementing traits for storage classes.
struct StringAttributeStorage
An attribute representing a string value.
struct SymbolRefAttributeStorage
An attribute representing a symbol reference.
struct SymbolState
This class contains record of any parsed top-level symbols.
struct TrailingOperandStorage
This class contains the information for a trailing operand storage.
struct TrailingOpResult
This class provides the implementation for an out-of-line operation result.
struct TupleTypeStorage
A type representing a collection of other types.
struct TypeAttributeStorage
An attribute representing a reference to a type.
struct TypeIDExported
The static local instance of each get method must be emitted with "default" (public) visibility across all shared libraries, regardless of whether they are compiled with hidden visibility or not.
struct TypeUniquer
A utility class to get, or create, unique instances of types within an MLIRContext.
struct UnrankedMemRefTypeStorage
Unranked MemRef is a MemRef with unknown rank.
struct UnrankedTensorTypeStorage
struct ValueRangeOwner
The type representing the owner of a ValueRange.
struct VectorTypeStorage
Vector Type Storage and Uniquing.
Typedefs
using DenseIterPtrAndSplat = llvm::PointerIntPair< const char *, 1, bool, DenseElementDataPointerTypeTraits >
Pair of raw pointer and a boolean flag of whether the pointer holds a splat,.
template<typename T , typename OperationOrValue >
using has_operation_or_value_matcher_t = decltype(std::declval< T >().match(std::declval< OperationOrValue >()))
Trait to check whether T provides a 'match' method with type OperationOrValue.
template<typename T >
using first_argument = decltype(first_argument_type(std::declval< T >()))
Type definition of the first argument to the given callable 'T'.
template<typename FnT >
using walkResultType = decltype(walk(nullptr, std::declval< FnT >()))
Utility to provide the return type of a templated walk method.
template<typename ImplTy , typename... Args>
using has_impltype_getkey_t = decltype(ImplTy::getKey(std::declval< Args >()...))
Trait to check if ImplTy provides a 'getKey' method with types 'Args'.
template<typename ImplTy , typename T >
using has_impltype_hash_t = decltype(ImplTy::hashKey(std::declval< T >()))
Trait to check if ImplTy provides a 'hashKey' method for 'T'.
using ByteCodeField = uint16_t
Use generic bytecode types.
using ByteCodeAddr = uint32_t
Functions
Optional< BlockArgument > getBranchSuccessorArgument (Optional< OperandRange > operands, unsigned operandIndex, Block *successor)
Return the BlockArgument corresponding to operand operandIndex in some successor if operandIndex is within the range of operands, or None if operandIndex isn't a successor operand index.
LogicalResult verifyBranchSuccessorOperands (Operation *op, unsigned succNo, Optional< OperandRange > operands)
Verify that the given operands match those of the given successor block.
LogicalResult verifyTypesAlongControlFlowEdges (Operation *op)
Verify that types match along control flow edges described the given op.
LogicalResult inferReturnTensorTypes (function_ref< LogicalResult(MLIRContext *, Optional< Location > location, ValueRange operands, DictionaryAttr attributes, RegionRange regions, SmallVectorImpl< ShapedTypeComponents > &retComponents)> componentTypeFn, MLIRContext *context, Optional< Location > location, ValueRange operands, DictionaryAttr attributes, RegionRange regions, SmallVectorImpl< Type > &inferredReturnTypes)
LogicalResult verifyInferredResultTypes (Operation *op)
Verifies that the inferred result types match the actual result types for the op.
template<int N>
void bindDims (MLIRContext *ctx)
template<int N, typename AffineExprTy , typename... AffineExprTy2>
void bindDims (MLIRContext *ctx, AffineExprTy &e, AffineExprTy2 &... exprs)
template<typename MatcherClass >
std::enable_if_t< llvm::is_detected< detail::has_operation_or_value_matcher_t, MatcherClass, Value >::value, bool > matchOperandOrValueAtIndex (Operation *op, unsigned idx, MatcherClass &matcher)
Statically switch to a Value matcher.
template<typename MatcherClass >
std::enable_if_t< llvm::is_detected< detail::has_operation_or_value_matcher_t, MatcherClass, Operation * >::value, bool > matchOperandOrValueAtIndex (Operation *op, unsigned idx, MatcherClass &matcher)
Statically switch to an Operation matcher.
template<typename TupleT , class CallbackT , std::size_t... Is>
constexpr void enumerateImpl (TupleT &&tuple, CallbackT &&callback, std::index_sequence< Is... >)
template<typename... Tys, typename CallbackT >
constexpr void enumerate (std::tuple< Tys... > &tuple, CallbackT &&callback)
const AttributeStorage * generateUnknownStorageLocation (MLIRContext *ctx)
Utility method to generate a raw default location for use when checking the construction invariants of a storage object.
LogicalResult verifySymbolTable (Operation *op)
LogicalResult verifySymbol (Operation *op)
template<typename Ret , typename Arg >
Arg first_argument_type (Ret(*)(Arg))
Helper templates to deduce the first argument of a callback parameter.
template<typename Ret , typename F , typename Arg >
Arg first_argument_type (Ret(F::*)(Arg))
void walk (Operation *op, function_ref< void(Region *)> callback)
Walk all of the regions, blocks, or operations nested under (and including) the given operation.
void walk (Operation *op, function_ref< void(Block *)> callback)
void walk (Operation *op, function_ref< void(Operation *)> callback)
WalkResult walk (Operation *op, function_ref< WalkResult(Region *)> callback)
Walk all of the regions, blocks, or operations nested under (and including) the given operation.
WalkResult walk (Operation *op, function_ref< WalkResult(Block *)> callback)
WalkResult walk (Operation *op, function_ref< WalkResult(Operation *)> callback)
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))>
std::enable_if< llvm::is_one_of< ArgT, Operation *, Region *, Block * >::value, RetT >::type walk (Operation *op, FuncTy &&callback)
Walk all of the regions, blocks, or operations nested under (and including) the given operation.
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))>
std::enable_if< !llvm::is_one_of< ArgT, Operation *, Region *, Block * >::value &&std::is_same< RetT, void >::value, RetT >::type walk (Operation *op, FuncTy &&callback)
Walk all of the operations of type 'ArgT' nested under and including the given operation.
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))>
std::enable_if< !llvm::is_one_of< ArgT, Operation *, Region *, Block * >::value &&std::is_same< RetT, WalkResult >::value, RetT >::type walk (Operation *op, FuncTy &&callback)
Walk all of the operations of type 'ArgT' nested under and including the given operation.
template<typename ContainerOpT >
OwningOpRef< ContainerOpT > constructContainerOpForParserIfNecessary (Block *parsedBlock, MLIRContext *context, Location sourceFileLoc)
Given a block containing operations that have just been parsed, if the block contains a single operation of ContainerOpT type then remove it from the block and return it.
size_t getDenseElementBitWidth (Type eltType)
Return the bit width which DenseElementsAttr should use for this type.
Variables
template<typename F >
decltype(first_argument_type(&F::operator())) first_argument_type (F)
Typedef Documentation
ByteCodeAddr
using mlir::detail::ByteCodeAddr = typedef uint32_t
Definition at line 31 of file ByteCode.h.
ByteCodeField
using mlir::detail::ByteCodeField = typedef uint16_t
Use generic bytecode types.
ByteCodeField refers to the actual bytecode entries (set to uint8_t for "byte" bytecode). ByteCodeAddr refers to size of indices into the bytecode. Correctness is checked with static asserts.
Definition at line 30 of file ByteCode.h.
DenseIterPtrAndSplat
using mlir::detail::DenseIterPtrAndSplat = typedef llvm::PointerIntPair<const char *, 1, bool, DenseElementDataPointerTypeTraits>
Pair of raw pointer and a boolean flag of whether the pointer holds a splat,.
Definition at line 516 of file BuiltinAttributes.h.
first_argument
template<typename T > using mlir::detail::first_argument = typedef decltype(first_argument_type(std::declval<T>()))
Type definition of the first argument to the given callable 'T'.
Definition at line 64 of file Visitors.h.
has_impltype_getkey_t
template<typename ImplTy , typename... Args> using mlir::detail::has_impltype_getkey_t = typedef decltype(ImplTy::getKey(std::declval<Args>()...))
Trait to check if ImplTy provides a 'getKey' method with types 'Args'.
Definition at line 24 of file StorageUniquer.h.
has_impltype_hash_t
template<typename ImplTy , typename T > using mlir::detail::has_impltype_hash_t = typedef decltype(ImplTy::hashKey(std::declval<T>()))
Trait to check if ImplTy provides a 'hashKey' method for 'T'.
Definition at line 28 of file StorageUniquer.h.
has_operation_or_value_matcher_t
template<typename T , typename OperationOrValue > using mlir::detail::has_operation_or_value_matcher_t = typedef decltype(std::declval<T>().match(std::declval<OperationOrValue>()))
Trait to check whether T provides a 'match' method with type OperationOrValue.
Definition at line 139 of file Matchers.h.
walkResultType
template<typename FnT > using mlir::detail::walkResultType = typedef decltype(walk(nullptr, std::declval<FnT>()))
Utility to provide the return type of a templated walk method.
Definition at line 150 of file Visitors.h.
Function Documentation
bindDims() [1/2]
template<int N> void mlir::detail::bindDims (MLIRContext * ctx)
Definition at line 279 of file AffineExpr.h.
Referenced by bindDims().
bindDims() [2/2]
template<int N, typename AffineExprTy , typename... AffineExprTy2> void mlir::detail::bindDims (MLIRContext * ctx, AffineExprTy & e, AffineExprTy2 &... exprs)
Definition at line 282 of file AffineExpr.h.
References bindDims(), and mlir::getAffineDimExpr().
constructContainerOpForParserIfNecessary()
template<typename ContainerOpT > OwningOpRef<ContainerOpT> mlir::detail::constructContainerOpForParserIfNecessary (Block * parsedBlock, MLIRContext * context, Location sourceFileLoc) inline
Given a block containing operations that have just been parsed, if the block contains a single operation of ContainerOpT type then remove it from the block and return it.
If the block does not contain just that operation, create a new operation instance of ContainerOpT and move all of the operations within parsedBlock into the first block of the first region. ContainerOpT is required to have a single region containing a single block, and must implement the SingleBlockImplicitTerminator trait.
Definition at line 36 of file Parser.h.
References mlir::Block::begin(), mlir::OpBuilder::create(), mlir::failed(), mlir::Block::front(), mlir::Block::getOperations(), mlir::parseSourceFile(), and mlir::parseSourceString().
enumerate()
template<typename... Tys, typename CallbackT > constexpr void mlir::detail::enumerate (std::tuple< Tys... > & tuple, CallbackT && callback)
Definition at line 185 of file Matchers.h.
References enumerateImpl().
Referenced by ableToUpdatePredOperands(), adjustIter(), mlir::AffineApplyNormalizer::AffineApplyNormalizer(), allocateBuffersForResults(), mlir::PatternApplicator::applyCostModel(), cloneMemref(), cloneWithLoopRanges(), computeCoalescedIndex(), computeIterationGraph(), computeRegionBlockNumberOfExecutions(), connectPHINodes(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::LLVM::ModuleTranslation::convertOmpOpRegions(), convertRangeType(), createFullTiles(), mlir::ConvertToLLVMPattern::createMemRefDescriptor(), createSwitchOp(), mlir::ValueDecomposer::decomposeValue(), defaultAllocBufferCallBack(), mlir::OpReducer< OpType >::deleteOps(), mlir::linalg::GenerateLoopNest< LoopTy >::doit(), mlir::ComputationSliceState::dump(), emitWithBoundsChecks(), encodeKernelName(), forwardPassthroughAttributes(), fuse(), fuseOperations(), fuseWithReshapeByExpansion(), generateFusedTensorOpRegion(), getBackwardSliceImpl(), mlir::linalg::LinalgDependenceGraph::getDependencesInto(), getDimMap(), mlir::spirv::getElementPtr(), getLLVMAtomicOrdering(), getPaddedInput(), mlir::getProjectedMap(), getShapeDefiningLoopRange(), getTransferOpAdapter(), getTreePredicates(), getTypeNumBytes(), indicesFromAffineApplyOp(), inferTransposeResultType(), injectGpuIndexOperations(), mlir::inlineRegion(), insertCopyLoops(), mlir::inversePermutation(), isAsyncWithOneDependency(), isConstantOne(), isMemRefNormalizable(), mlir::isOpwiseShiftValid(), isReassociationValid(), mlir::linalg::LinalgDependenceGraph::LinalgDependenceGraph(), logFailure(), lowerAsEntryFunction(), lowerEntryPointABIAttr(), mlir::makeStridedLinearLayoutMap(), makeTiledShapes(), mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::match(), mlir::GPUFuncOpLowering< AllocaAddrSpace >::matchAndRewrite(), mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite(), outlineKernelFuncImpl(), packFunctionArguments(), parseOptionalKeywordAlternative(), mlir::permuteLoops(), print(), printResultsAsList(), mlir::linalg::promoteSubviewAsNewBuffer(), promoteSubViews(), mlir::linalg::promoteSubviewsPrecondition(), pruneReductionDimsFromMap(), mlir::detail::ConversionPatternRewriterImpl::remapValues(), mlir::replaceAllMemRefUsesWith(), replaceBlockArgForUnitDimLoops< IndexedGenericOp >(), replaceUnitExtents(), resolveSourceIndices(), mlir::SPIRVTypeConverter::SPIRVTypeConverter(), tileAndFuseLinalgOpsImpl(), tileLinalgOpImpl(), mlir::OpBuilder::tryFold(), updateFuncOp(), mlir::LLVM::detail::vectorOneToOneRewrite(), verify(), verifyGenericOp(), verifyNamedStructuredOp(), verifyReshapeLikeTypes(), verifyTypesAlongAllEdges(), walkReturnOperations(), wrapExternalFunction(), and wrapForExternalCallers().
enumerateImpl()
template<typename TupleT , class CallbackT , std::size_t... Is> constexpr void mlir::detail::enumerateImpl (TupleT && tuple, CallbackT && callback, std::index_sequence< Is... >)
Definition at line 176 of file Matchers.h.
Referenced by enumerate().
first_argument_type() [1/2]
template<typename Ret , typename Arg > Arg mlir::detail::first_argument_type (Ret(*)(Arg))
Helper templates to deduce the first argument of a callback parameter.
first_argument_type() [2/2]
template<typename Ret , typename F , typename Arg > Arg mlir::detail::first_argument_type (Ret(F::*)(Arg))
Referenced by mlir::WalkResult::wasInterrupted().
generateUnknownStorageLocation()
const AttributeStorage * mlir::detail::generateUnknownStorageLocation (MLIRContext * ctx)
Utility method to generate a raw default location for use when checking the construction invariants of a storage object.
Utility method to generate a default location for use when checking the construction invariants of a storage object.
This is defined out-of-line to avoid the need to include Location.h.
Definition at line 945 of file MLIRContext.cpp.
References mlir::MLIRContext::getImpl(), and mlir::MLIRContextImpl::unknownLocAttr.
Referenced by mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get().
getBranchSuccessorArgument()
Optional< BlockArgument > mlir::detail::getBranchSuccessorArgument (Optional< OperandRange > operands, unsigned operandIndex, Block * successor)
Return the BlockArgument corresponding to operand operandIndex in some successor if operandIndex is within the range of operands, or None if operandIndex isn't a successor operand index.
Returns the BlockArgument corresponding to operand operandIndex in some successor if 'operandIndex' is within the range of 'operands', or None if operandIndex isn't a successor operand index.
Definition at line 29 of file ControlFlowInterfaces.cpp.
References mlir::Block::getArgument().
getDenseElementBitWidth()
size_t mlir::detail::getDenseElementBitWidth (Type eltType) inline
Return the bit width which DenseElementsAttr should use for this type.
Definition at line 352 of file AttributeDetail.h.
References mlir::Type::dyn_cast(), mlir::Type::getIntOrFloatBitWidth(), and mlir::Type::isIndex().
Referenced by mlir::DenseElementsAttr::get(), getDenseElementStorageWidth(), mlir::detail::DenseIntOrFPElementsAttributeStorage::getKey(), isValidIntOrFloat(), mappingHelper(), mlir::DenseElementsAttr::BoolElementIterator::operator*(), and mlir::DenseElementsAttr::IntElementIterator::operator*().
inferReturnTensorTypes()
LogicalResult mlir::detail::inferReturnTensorTypes (function_ref< LogicalResult(MLIRContext *, Optional< Location > location, ValueRange operands, DictionaryAttr attributes, RegionRange regions, SmallVectorImpl< ShapedTypeComponents > &retComponents)> componentTypeFn, MLIRContext * context, Optional< Location > location, ValueRange operands, DictionaryAttr attributes, RegionRange regions, SmallVectorImpl< Type > & inferredReturnTypes)
Definition at line 24 of file InferTypeOpInterface.cpp.
References mlir::failed(), mlir::failure(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), and mlir::success().
Referenced by mlir::ShapedTypeComponents::getAttribute(), and mlir::OpTrait::InferTensorType< ConcreteType >::inferReturnTypes().
matchOperandOrValueAtIndex() [1/2]
template<typename MatcherClass > std::enable_if_t< llvm::is_detected<detail::has_operation_or_value_matcher_t, MatcherClass, Value>::value, bool> mlir::detail::matchOperandOrValueAtIndex (Operation * op, unsigned idx, MatcherClass & matcher)
Statically switch to a Value matcher.
Definition at line 147 of file Matchers.h.
References mlir::Operation::getOperand().
Referenced by mlir::detail::RecursivePatternMatcher< OpType, OperandMatchers >::match().
matchOperandOrValueAtIndex() [2/2]
template<typename MatcherClass > std::enable_if_t< llvm::is_detected<detail::has_operation_or_value_matcher_t, MatcherClass, Operation *>::value, bool> mlir::detail::matchOperandOrValueAtIndex (Operation * op, unsigned idx, MatcherClass & matcher)
Statically switch to an Operation matcher.
Definition at line 157 of file Matchers.h.
References mlir::Value::getDefiningOp(), and mlir::Operation::getOperand().
verifyBranchSuccessorOperands()
LogicalResult mlir::detail::verifyBranchSuccessorOperands (Operation * op, unsigned succNo, Optional< OperandRange > operands)
Verify that the given operands match those of the given successor block.
Definition at line 48 of file ControlFlowInterfaces.cpp.
References mlir::Operation::emitError(), mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::Operation::getSuccessor(), mlir::BlockArgument::getType(), and mlir::success().
verifyInferredResultTypes()
LogicalResult mlir::detail::verifyInferredResultTypes (Operation * op)
Verifies that the inferred result types match the actual result types for the op.
Precondition: op implements InferTypeOpInterface.
Definition at line 49 of file InferTypeOpInterface.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getAttrDictionary(), mlir::Operation::getContext(), mlir::Operation::getLoc(), mlir::Operation::getOperands(), mlir::Operation::getRegions(), mlir::Operation::getResultTypes(), and mlir::success().
Referenced by mlir::ShapedTypeComponents::getAttribute().
verifySymbol()
LogicalResult mlir::detail::verifySymbol (Operation * op)
Definition at line 414 of file SymbolTable.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getAttr(), mlir::Operation::getAttrOfType(), mlir::SymbolTable::getSymbolAttrName(), mlir::StringAttr::getValue(), mlir::SymbolTable::getVisibilityAttrName(), and mlir::success().
Referenced by mlir::SymbolTableCollection::lookupNearestSymbolFrom().
verifySymbolTable()
LogicalResult mlir::detail::verifySymbolTable (Operation * op)
Definition at line 373 of file SymbolTable.cpp.
References mlir::WalkResult::advance(), mlir::InFlightDiagnostic::append(), mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::Operation::getAttrOfType(), mlir::Operation::getLoc(), mlir::Operation::getNumRegions(), mlir::Operation::getRegion(), mlir::Operation::getRegions(), mlir::SymbolTable::getSymbolAttrName(), mlir::success(), and walkSymbolTable().
Referenced by mlir::SymbolTableCollection::lookupNearestSymbolFrom(), and mlir::OpTrait::SymbolTable< ConcreteType >::verifyTrait().
verifyTypesAlongControlFlowEdges()
LogicalResult mlir::detail::verifyTypesAlongControlFlowEdges (Operation * op)
Verify that types match along control flow edges described the given op.
Definition at line 151 of file ControlFlowInterfaces.cpp.
References mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getNumRegions(), mlir::Operation::getOperands(), mlir::Operation::getOperandTypes(), mlir::Operation::getRegion(), mlir::Operation::getResultTypes(), mlir::OperandRange::getTypes(), mlir::Operation::hasTrait(), mlir::success(), and verifyTypesAlongAllEdges().
walk() [1/9]
void mlir::detail::walk (Operation * op, function_ref< void(Region *)> callback)
Walk all of the regions, blocks, or operations nested under (and including) the given operation.
Walk all of the regions/blocks/operations nested under and including the given operation.
Definition at line 16 of file Visitors.cpp.
References mlir::Operation::getRegions().
Referenced by mlir::PatternApplicator::applyDefaultCostModel(), isMemRefNormalizable(), mlir::loopUnrollJamByFactor(), mlir::AffineExpr::operator!(), print(), walk(), mlir::Block::walk(), mlir::Operation::walk(), mlir::PatternApplicator::walkAllPatterns(), mlir::SDBMVisitor< Derived, Result >::walkPostorder(), mlir::SDBMVisitor< Derived, Result >::walkPreorder(), walkSymbolUses(), and GpuAsyncRegionPass::DeferWaitCallback::~DeferWaitCallback().
walk() [2/9]
void mlir::detail::walk (Operation * op, function_ref< void(Block *)> callback)
Definition at line 26 of file Visitors.cpp.
References mlir::WalkResult::advance(), mlir::Operation::getRegions(), mlir::WalkResult::interrupt(), and walk().
walk() [3/9]
void mlir::detail::walk (Operation * op, function_ref< void(Operation *)> callback)
walk() [4/9]
WalkResult mlir::detail::walk (Operation * op, function_ref< WalkResult(Region *)> callback)
Walk all of the regions, blocks, or operations nested under (and including) the given operation.
These functions walk until an interrupt result is returned by the callback.
walk() [5/9]
WalkResult mlir::detail::walk (Operation * op, function_ref< WalkResult(Block *)> callback)
walk() [6/9]
WalkResult mlir::detail::walk (Operation * op, function_ref< WalkResult(Operation *)> callback)
walk() [7/9]
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))> std::enable_if< llvm::is_one_of<ArgT, Operation *, Region *, Block *>::value, RetT>::type mlir::detail::walk (Operation * op, FuncTy && callback)
Walk all of the regions, blocks, or operations nested under (and including) the given operation.
This method is selected for callbacks that operate on Region*, Block*, and Operation*.
Example: op->walk([](Region *r) { ... }); op->walk([](Block *b) { ... }); op->walk([](Operation *op) { ... });
Definition at line 97 of file Visitors.h.
References walk().
walk() [8/9]
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))> std::enable_if< !llvm::is_one_of<ArgT, Operation *, Region *, Block *>::value && std::is_same<RetT, void>::value, RetT>::type mlir::detail::walk (Operation * op, FuncTy && callback)
Walk all of the operations of type 'ArgT' nested under and including the given operation.
This method is selected for void returning callbacks that operate on a specific derived operation type.
Example: op->walk([](ReturnOp op) { ... });
Definition at line 114 of file Visitors.h.
References walk().
walk() [9/9]
template<typename FuncTy , typename ArgT = detail::first_argument<FuncTy>, typename RetT = decltype(std::declval<FuncTy>()(std::declval<ArgT>()))> std::enable_if< !llvm::is_one_of<ArgT, Operation *, Region *, Block *>::value && std::is_same<RetT, WalkResult>::value, RetT>::type mlir::detail::walk (Operation * op, FuncTy && callback)
Walk all of the operations of type 'ArgT' nested under and including the given operation.
This method is selected for WalkReturn returning interruptible callbacks that operate on a specific derived operation type.
Example: op->walk([](ReturnOp op) { if (some_invariant) return WalkResult::interrupt(); return WalkResult::advance(); });
Definition at line 139 of file Visitors.h.
References mlir::WalkResult::advance(), and walk().
Referenced by walk().
Variable Documentation
first_argument_type
template<typename F > decltype(first_argument_type(&F::operator())) mlir::detail::first_argument_type(F)
Definition at line 60 of file Visitors.h.