MLIR: mlir::edsc Namespace Reference
mlir::edsc Namespace Reference
Namespaces
intrinsics
op
ops
Classes
class BoundsCapture
Base class for MemRefBoundsCapture and VectorBoundsCapture.
class MemRefBoundsCapture
A MemRefBoundsCapture represents the information required to step through a MemRef.
struct OperationBuilder
class ScopedContext
Helper class to transparently handle builder insertion points by RAII.
struct StructuredIndexed
A StructuredIndexed represents an indexable quantity that is either:
class TemplatedIndexedValue
A TemplatedIndexedValue brings an index notation over the template Load and Store parameters.
struct ValueBuilder
class VectorBoundsCapture
A VectorBoundsCapture represents the information required to step through a Vector accessing each scalar element at a time.
Functions
void affineLoopNestBuilder (ValueRange lbs, ValueRange ubs, ArrayRef< int64_t > steps, function_ref< void(ValueRange)> bodyBuilderFn=nullptr)
Creates a perfect nest of affine "for" loops, given the list of lower bounds, upper bounds and steps.
void affineLoopBuilder (ValueRange lbs, ValueRange ubs, int64_t step, function_ref< void(Value)> bodyBuilderFn=nullptr)
Creates a single affine "for" loop, iterating from max(lbs) to min(ubs) with the given step.
void affineLoopBuilder (ValueRange lbs, ValueRange ubs, int64_t step, ValueRange iterArgs, function_ref< void(Value, ValueRange)> bodyBuilderFn=nullptr)
Creates a single affine "for" loop, iterating from max(lbs) to min(ubs) with the given step.
void defaultRegionBuilder (ValueRange args)
Operation * makeGenericLinalgOp (ArrayRef< IteratorType > iteratorTypes, ArrayRef< StructuredIndexed > inputs, ArrayRef< StructuredIndexed > outputBuffers, ArrayRef< Value > initTensors, ArrayRef< StructuredIndexed > resultTensorTypes, function_ref< void(ValueRange)> regionBuilder=defaultRegionBuilder, ArrayRef< Value > otherValues={}, ArrayRef< Attribute > otherAttributes={})
Build a linalg.generic op with the specified inputs, outputBuffers, initTensors, resultTensorsTypes and region.
scf::LoopNest loopNestBuilder (ValueRange lbs, ValueRange ubs, ValueRange steps, function_ref< void(ValueRange)> fun=nullptr)
Adapters for building loop nests using the builder and the location stored in ScopedContext.
scf::LoopNest loopNestBuilder (Value lb, Value ub, Value step, function_ref< void(Value)> fun=nullptr)
scf::LoopNest loopNestBuilder (Value lb, Value ub, Value step, ValueRange iterArgInitValues, function_ref< scf::ValueVector(Value, ValueRange)> fun=nullptr)
scf::LoopNest loopNestBuilder (ValueRange lbs, ValueRange ubs, ValueRange steps, ValueRange iterArgInitValues, function_ref< scf::ValueVector(ValueRange, ValueRange)> fun=nullptr)
ValueRange conditionBuilder (TypeRange results, Value condition, function_ref< scf::ValueVector()> thenBody, function_ref< scf::ValueVector()> elseBody=nullptr, scf::IfOp *ifOp=nullptr)
Adapters for building if conditions using the builder and the location stored in ScopedContext.
ValueRange conditionBuilder (Value condition, function_ref< void()> thenBody, function_ref< void()> elseBody=nullptr, scf::IfOp *ifOp=nullptr)
Block * createBlock (TypeRange argTypes=llvm::None)
Creates a block in the region that contains the insertion block of the OpBuilder currently at the top of ScopedContext stack (appends the block to the region).
Block * createBlockInRegion (Region &region, TypeRange argTypes=llvm::None)
Creates a block in the specified region using OpBuilder at the top of ScopedContext stack (appends the block to the region).
void appendToBlock (Block *block, function_ref< void(ValueRange)> builderFn)
Calls "builderFn" with ScopedContext reconfigured to insert into "block" and passes in the block arguments.
Block * buildInNewBlock (TypeRange argTypes, function_ref< void(ValueRange)> builderFn)
Creates a block in the region that contains the insertion block of the OpBuilder currently at the top of ScopedContext stack, and calls "builderFn" to populate the body of the block while passing it the block arguments.
Block * buildInNewBlock (Region &region, TypeRange argTypes, function_ref< void(ValueRange)> builderFn)
Creates a block in the specified region using OpBuilder at the top of ScopedContext stack, and calls "builderFn" to populate the body of the block while passing it the block arguments.
Function Documentation
affineLoopBuilder() [1/2]
void mlir::edsc::affineLoopBuilder (ValueRange lbs, ValueRange ubs, int64_t step, function_ref< void(Value)> bodyBuilderFn = nullptr)
Creates a single affine "for" loop, iterating from max(lbs) to min(ubs) with the given step.
Uses the OpBuilder and Location stored in ScopedContext and assumes they are non-null. The optional "bodyBuilderFn" callback is called to construct the body of the loop and is passed the induction variable. The function is expected to use the builder and location stored in ScopedContext at the moment of the call. The function should not create the affine terminator op, which will be added regardless of the "bodyBuilderFn" being present.
Definition at line 39 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), and mlir::Builder::getMultiDimIdentityMap().
affineLoopBuilder() [2/2]
void mlir::edsc::affineLoopBuilder (ValueRange lbs, ValueRange ubs, int64_t step, ValueRange iterArgs, function_ref< void(Value, ValueRange)> bodyBuilderFn = nullptr)
Creates a single affine "for" loop, iterating from max(lbs) to min(ubs) with the given step.
Uses the OpBuilder and Location stored in ScopedContext and assumes they are non-null. "iterArgs" is used to specify the initial values of the result affine "for" might yield. The optional "bodyBuilderFn" callback is called to construct the body of the loop and is passed the induction variable and the iteration arguments. The function is expected to use the builder and location stored in ScopedContext at the moment of the call. The function will create the affine terminator op in case "iterArgs" is empty and "bodyBuilderFn" is not present.
Definition at line 62 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), and mlir::Builder::getMultiDimIdentityMap().
affineLoopNestBuilder()
void mlir::edsc::affineLoopNestBuilder (ValueRange lbs, ValueRange ubs, ArrayRef< int64_t > steps, function_ref< void(ValueRange)> bodyBuilderFn = nullptr)
Creates a perfect nest of affine "for" loops, given the list of lower bounds, upper bounds and steps.
The three lists are expected to contain the same number of elements. Uses the OpBuilder and Location stored in ScopedContext and assumes they are non-null. The optional "bodyBuilderFn" callback is called to construct the body of the innermost loop and is passed the list of loop induction variables, in order from outermost to innermost. The function is expected to use the builder and location stored in ScopedContext at the moment of the call. The function should not create the affine terminator op, which will be added regardless of the "bodyBuilderFn" being present.
Definition at line 17 of file Builders.cpp.
References mlir::buildAffineLoopNest(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), and mlir::edsc::ScopedContext::getLocation().
Referenced by applyMapToValues(), and mlir::linalg::GenerateLoopNest< LoopTy >::doit().
appendToBlock()
void mlir::edsc::appendToBlock (Block * block, function_ref< void(ValueRange)> builderFn)
Calls "builderFn" with ScopedContext reconfigured to insert into "block" and passes in the block arguments.
If the block has a terminator, the operations are inserted before the terminator, otherwise appended to the block.
Definition at line 82 of file Builders.cpp.
References mlir::Block::back(), mlir::Block::empty(), mlir::Block::getArguments(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::Operation::isKnownNonTerminator(), mlir::OpBuilder::setInsertionPoint(), and mlir::OpBuilder::setInsertionPointToEnd().
buildInNewBlock() [1/2]
Block * mlir::edsc::buildInNewBlock (TypeRange argTypes, function_ref< void(ValueRange)> builderFn)
Creates a block in the region that contains the insertion block of the OpBuilder currently at the top of ScopedContext stack, and calls "builderFn" to populate the body of the block while passing it the block arguments.
Definition at line 95 of file Builders.cpp.
References mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::OpBuilder::getInsertionBlock(), and mlir::Block::getParent().
Referenced by makeGenericLinalgOp().
buildInNewBlock() [2/2]
Block * mlir::edsc::buildInNewBlock (Region & region, TypeRange argTypes, function_ref< void(ValueRange)> builderFn)
Creates a block in the specified region using OpBuilder at the top of ScopedContext stack, and calls "builderFn" to populate the body of the block while passing it the block arguments.
Definition at line 105 of file Builders.cpp.
References createBlockInRegion(), mlir::Block::getArguments(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), and mlir::OpBuilder::setInsertionPointToStart().
conditionBuilder() [1/2]
ValueRange mlir::edsc::conditionBuilder (TypeRange results, Value condition, function_ref< scf::ValueVector()> thenBody, function_ref< scf::ValueVector()> elseBody = nullptr, scf::IfOp * ifOp = nullptr)
Adapters for building if conditions using the builder and the location stored in ScopedContext.
'thenBody' is mandatory, 'elseBody' can be omitted if the condition should not have an 'else' part. When ifOp is specified, the scf::IfOp is captured. This is particularly convenient for 0-result conditions.
Definition at line 96 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), and wrapIfBody().
Referenced by applyMapToValues(), createScopedFullPartialLinalgCopy(), createScopedFullPartialVectorTransferRead(), emitWithBoundsChecks(), and mlir::linalg::generateParallelLoopNest().
conditionBuilder() [2/2]
ValueRange mlir::edsc::conditionBuilder (Value condition, function_ref< void()> thenBody, function_ref< void()> elseBody = nullptr, scf::IfOp * ifOp = nullptr)
Definition at line 120 of file Builders.cpp.
References mlir::OpBuilder::create(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::edsc::ScopedContext::getLocation(), and wrapZeroResultIfBody().
createBlock()
Block * mlir::edsc::createBlock (TypeRange argTypes = llvm::None)
Creates a block in the region that contains the insertion block of the OpBuilder currently at the top of ScopedContext stack (appends the block to the region).
Be aware that this will NOT update the insertion point of the builder to insert into the newly constructed block.
Definition at line 64 of file Builders.cpp.
References createBlockInRegion(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), mlir::OpBuilder::getInsertionBlock(), and mlir::Block::getParent().
Referenced by mlir::OpBuilder::createBlock(), and mlir::OpBuilder::getBlock().
createBlockInRegion()
Block * mlir::edsc::createBlockInRegion (Region & region, TypeRange argTypes = llvm::None)
Creates a block in the specified region using OpBuilder at the top of ScopedContext stack (appends the block to the region).
Be aware that this will NOT update the insertion point of the builder to insert into the newly constructed block.
Definition at line 74 of file Builders.cpp.
References mlir::OpBuilder::createBlock(), mlir::edsc::ScopedContext::getBuilderRef(), and mlir::edsc::ScopedContext::getContext().
Referenced by buildInNewBlock(), and createBlock().
defaultRegionBuilder()
void mlir::edsc::defaultRegionBuilder (ValueRange args) inline
Definition at line 31 of file Builders.h.
References makeGenericLinalgOp().
loopNestBuilder() [1/4]
mlir::scf::LoopNest mlir::edsc::loopNestBuilder (ValueRange lbs, ValueRange ubs, ValueRange steps, function_ref< void(ValueRange)> fun = nullptr)
Adapters for building loop nests using the builder and the location stored in ScopedContext.
Actual builders are in scf::buildLoopNest.
Definition at line 18 of file Builders.cpp.
References mlir::scf::buildLoopNest(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), and mlir::edsc::ScopedContext::getLocation().
Referenced by mlir::linalg::GenerateLoopNest< LoopTy >::doit(), mlir::linalg::generateParallelLoopNest(), insertCopyLoops(), loopNestBuilder(), and mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().
loopNestBuilder() [2/4]
mlir::scf::LoopNest mlir::edsc::loopNestBuilder (Value lb, Value ub, Value step, function_ref< void(Value)> fun = nullptr)
Definition at line 33 of file Builders.cpp.
References loopNestBuilder().
loopNestBuilder() [3/4]
mlir::scf::LoopNest mlir::edsc::loopNestBuilder (Value lb, Value ub, Value step, ValueRange iterArgInitValues, function_ref< scf::ValueVector(Value, ValueRange)> fun = nullptr)
Definition at line 45 of file Builders.cpp.
References mlir::scf::buildLoopNest(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), and mlir::edsc::ScopedContext::getLocation().
loopNestBuilder() [4/4]
mlir::scf::LoopNest mlir::edsc::loopNestBuilder (ValueRange lbs, ValueRange ubs, ValueRange steps, ValueRange iterArgInitValues, function_ref< scf::ValueVector(ValueRange, ValueRange)> fun = nullptr)
Definition at line 64 of file Builders.cpp.
References mlir::scf::buildLoopNest(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::edsc::ScopedContext::getContext(), and mlir::edsc::ScopedContext::getLocation().
makeGenericLinalgOp()
Operation * mlir::edsc::makeGenericLinalgOp (ArrayRef< IteratorType > iteratorTypes, ArrayRef< StructuredIndexed > inputs, ArrayRef< StructuredIndexed > outputBuffers, ArrayRef< Value > initTensors, ArrayRef< StructuredIndexed > resultTensorTypes, function_ref< void(ValueRange)> regionBuilder = defaultRegionBuilder, ArrayRef< Value > otherValues = {}, ArrayRef< Attribute > otherAttributes = {})
Build a linalg.generic op with the specified inputs, outputBuffers, initTensors, resultTensorsTypes and region.
otherValues and otherAttributes may be passed and will be appended as operands and attributes respectively.
Prerequisites:
inputs may contain StructuredIndexed that capture either buffer or tensor values.
outputsBuffers may contain StructuredIndexed that capture buffer values.
initTensors contain tensor values, without indexing maps.
resultTensorTypes may contain StructuredIndexed that capture return tensor types.
Definition at line 24 of file Builders.cpp.
References buildInNewBlock(), copy(), mlir::OpBuilder::create(), mlir::Builder::getAffineMapArrayAttr(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::getElementTypeOrSelf(), mlir::edsc::ScopedContext::getLocation(), mlir::Builder::getStrArrayAttr(), mlir::edsc::StructuredIndexed::getType(), mlir::edsc::StructuredIndexed::hasValue(), mlir::AffineMap::inferFromExprList(), and mlir::toString().
Referenced by defaultRegionBuilder(), mlir::edsc::ops::linalg_generic_conv_nhwc(), mlir::edsc::ops::linalg_generic_dilated_conv_nhwc(), mlir::edsc::ops::linalg_generic_matmul(), and mlir::edsc::ops::linalg_generic_pointwise().