MLIR: lib/Transforms/NormalizeMemRefs.cpp File Reference
NormalizeMemRefs.cpp File Reference
#include "PassDetail.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Transforms/Passes.h"
#include "mlir/Transforms/Utils.h"
#include "llvm/ADT/SmallSet.h"
Macros
#define DEBUG_TYPE "normalize-memrefs"
Functions
static bool isMemRefNormalizable (Value::user_range opUsers)
Check whether all the uses of oldMemRef are either dereferencing uses or the op is of type : DeallocOp, CallOp or ReturnOp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "normalize-memrefs"
Definition at line 20 of file NormalizeMemRefs.cpp.
Function Documentation
isMemRefNormalizable()
static bool isMemRefNormalizable (Value::user_range opUsers) static
Check whether all the uses of oldMemRef are either dereferencing uses or the op is of type : DeallocOp, CallOp or ReturnOp.
Only if these constraints are satisfied will the value become a candidate for replacement. TODO: Extend this for DimOps.
Definition at line 92 of file NormalizeMemRefs.cpp.
References mlir::OperationState::addOperands(), mlir::WalkResult::advance(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOperation(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::Operation::erase(), mlir::failed(), mlir::FunctionType::get(), mlir::MemRefType::getAffineMaps(), getAffineMaps(), mlir::Operation::getAttrs(), mlir::FunctionType::getInput(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::FunctionType::getNumInputs(), mlir::FunctionType::getNumResults(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Operation::getParentOfType(), mlir::FunctionType::getResult(), mlir::Operation::getResult(), mlir::FunctionType::getResults(), mlir::Builder::getSymbolRefAttr(), mlir::Value::getType(), mlir::BlockArgument::getType(), mlir::Value::getUsers(), mlir::Operation::hasTrait(), mlir::WalkResult::interrupt(), mlir::Type::isa(), mlir::normalizeMemRef(), mlir::normalizeMemRefType(), mlir::replaceAllMemRefUsesWith(), mlir::Operation::replaceAllUsesWith(), and mlir::detail::walk().