MLIR: lib/Analysis/NumberOfExecutions.cpp File Reference
NumberOfExecutions.cpp File Reference
#include "mlir/Analysis/NumberOfExecutions.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/RegionKindInterface.h"
#include "mlir/Interfaces/ControlFlowInterfaces.h"
#include "llvm/ADT/FunctionExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "number-of-executions-analysis"
Functions
static void computeRegionBlockNumberOfExecutions (Region &region, DenseMap< Block *, BlockNumberOfExecutionsInfo > &blockInfo)
Computes blocks number of executions information for the given region.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "number-of-executions-analysis"
Definition at line 23 of file NumberOfExecutions.cpp.
Function Documentation
computeRegionBlockNumberOfExecutions()
static void computeRegionBlockNumberOfExecutions (Region & region, DenseMap< Block *, BlockNumberOfExecutionsInfo > & blockInfo) static
Computes blocks number of executions information for the given region.
Definition at line 32 of file NumberOfExecutions.cpp.
References mlir::detail::enumerate(), mlir::Region::front(), mlir::Operation::getNumOperands(), mlir::Operation::getOperands(), mlir::Region::getParentOp(), mlir::Region::getRegionNumber(), mlir::Block::getSuccessors(), mlir::Graph, mlir::kUnknownNumRegionInvocations, mlir::m_Constant(), and mlir::matchPattern().
Referenced by mlir::NumberOfExecutions::NumberOfExecutions().