MLIR: lib/TableGen/Operator.cpp File Reference
Operator.cpp File Reference
#include "mlir/TableGen/Operator.h"
#include "mlir/TableGen/OpTrait.h"
#include "mlir/TableGen/Predicate.h"
#include "mlir/TableGen/Type.h"
#include "llvm/ADT/EquivalenceClasses.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Sequence.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
Macros
#define DEBUG_TYPE "mlir-tblgen-operator"
Functions
static int resultIndex (int i)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mlir-tblgen-operator"
Definition at line 28 of file Operator.cpp.
Function Documentation
resultIndex()
static int resultIndex (int i) static
Definition at line 253 of file Operator.cpp.
Referenced by allocateBuffersForResults(), mlir::detail::PDLByteCode::initializeMutableState(), mlir::tblgen::Operator::isVariadic(), mlir::Dialect::printType(), unrollSingleResultStructuredOp(), and mlir::vector::unrollSingleResultVectorOp().