MLIR: lib/IR/Operation.cpp File Reference
Operation.cpp File Reference
#include "mlir/IR/Operation.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Interfaces/FoldInterfaces.h"
#include <numeric>
Functions
static Type getTensorOrVectorElementType (Type type)
If this is a vector type, or a tensor type, return the scalar element type that it is built around, otherwise return the type unmodified.
static LogicalResult verifyTerminatorSuccessors (Operation *op)
static LogicalResult verifyValueSizeAttr (Operation *op, StringRef attrName, bool isOperand)
static bool areSameShapedTypeIgnoringElementType (ShapedType a, ShapedType b)
Checks if two ShapedTypes are the same, ignoring the element type.
Function Documentation
areSameShapedTypeIgnoringElementType()
static bool areSameShapedTypeIgnoringElementType (ShapedType a, ShapedType b) static
Checks if two ShapedTypes are the same, ignoring the element type.
Definition at line 1087 of file Operation.cpp.
References mlir::ShapedType::getShape(), mlir::Type::getTypeID(), and mlir::ShapedType::hasRank().
Referenced by mlir::OpTrait::impl::verifyElementwiseMappable().
getTensorOrVectorElementType()
static Type getTensorOrVectorElementType (Type type) static
If this is a vector type, or a tensor type, return the scalar element type that it is built around, otherwise return the type unmodified.
Definition at line 748 of file Operation.cpp.
References mlir::Type::dyn_cast().
Referenced by mlir::OpTrait::impl::verifyOperandsAreFloatLike(), mlir::OpTrait::impl::verifyOperandsAreSignlessIntegerLike(), mlir::OpTrait::impl::verifyResultsAreBoolLike(), mlir::OpTrait::impl::verifyResultsAreFloatLike(), and mlir::OpTrait::impl::verifyResultsAreSignlessIntegerLike().
verifyTerminatorSuccessors()
static LogicalResult verifyTerminatorSuccessors (Operation * op) static
Definition at line 958 of file Operation.cpp.
References mlir::Operation::emitError(), mlir::Operation::getParentRegion(), mlir::Operation::getSuccessors(), and mlir::success().
Referenced by mlir::OpTrait::impl::verifyAtLeastNSuccessors(), mlir::OpTrait::impl::verifyNSuccessors(), and mlir::OpTrait::impl::verifyOneSuccessor().
verifyValueSizeAttr()
static LogicalResult verifyValueSizeAttr (Operation * op, StringRef attrName, bool isOperand) static
Definition at line 1029 of file Operation.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getAttrOfType(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), and mlir::success().
Referenced by mlir::OpTrait::impl::verifyOperandSizeAttr(), and mlir::OpTrait::impl::verifyResultSizeAttr().