MLIR: lib/IR/OperationSupport.cpp File Reference
OperationSupport.cpp File Reference
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/Block.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/IR/Operation.h"
Functions
template<typename T >
static auto * findAttr (SmallVectorImpl< NamedAttribute > &attrs, T name, bool sorted)
Helper function to find attribute in possible sorted vector of NamedAttributes.
Function Documentation
findAttr()
template<typename T > static auto* findAttr (SmallVectorImpl< NamedAttribute > & attrs, T name, bool sorted) static
Helper function to find attribute in possible sorted vector of NamedAttributes.
Definition at line 102 of file OperationSupport.cpp.
Referenced by mlir::NamedAttrList::erase(), mlir::NamedAttrList::get(), mlir::NamedAttrList::getNamed(), and mlir::NamedAttrList::set().