MLIR: lib/Dialect/StandardOps/IR/Ops.cpp File Reference
Ops.cpp File Reference
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/CommonFolders.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Value.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include "mlir/Dialect/StandardOps/IR/OpsEnums.cpp.inc"
#include "mlir/Dialect/StandardOps/IR/Ops.cpp.inc"
Namespaces
saturated_arith
Helpers to write more idiomatic operations.
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Enumerations
enum SubViewVerificationResult {
Success, RankTooLarge, SizeMismatch, StrideMismatch,
ElemTypeMismatch, MemSpaceMismatch, AffineMapMismatch
}
Functions
static void printStandardUnaryOp (Operation *op, OpAsmPrinter &p)
A custom unary operation printer that omits the "std." prefix from the operation names.
static void printStandardBinaryOp (Operation *op, OpAsmPrinter &p)
A custom binary operation printer that omits the "std." prefix from the operation names.
static void printStandardCastOp (Operation *op, OpAsmPrinter &p)
A custom cast operation printer that omits the "std." prefix from the operation names.
template<typename T >
static LogicalResult verifyCastOp (T op)
A custom cast operation verifier.
static detail::op_matcher< ConstantIndexOp > m_ConstantIndex ()
Matches a ConstantIndexOp.
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
static bool areVectorCastSimpleCompatible (Type a, Type b, function_ref< bool(Type, Type)> areElementsCastCompatible)
This method checks for cast compatibility of vector types.
static Type getTensorTypeFromMemRefType (Type type)
static SmallVector< int64_t, 4 > extractFromI64ArrayAttr (Attribute attr)
Extract int64_t values from the assumed ArrayAttr of IntegerAttr.
template<typename AllocLikeOp >
static LogicalResult verifyAllocLikeOp (AllocLikeOp op)
static LogicalResult verify (AllocOp op)
static LogicalResult verify (AllocaOp op)
static LogicalResult verify (AssumeAlignmentOp op)
static LogicalResult verify (AtomicRMWOp op)
static LogicalResult verify (GenericAtomicRMWOp op)
static ParseResult parseGenericAtomicRMWOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, GenericAtomicRMWOp op)
static LogicalResult verify (AtomicYieldOp op)
static LogicalResult collapseBranch (Block *&successor, ValueRange &successorOperands, SmallVectorImpl< Value > &argStorage)
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
static Type getI1SameShape (Type type)
static void buildCmpIOp (OpBuilder &build, OperationState &result, CmpIPredicate predicate, Value lhs, Value rhs)
static bool applyCmpPredicateToEqualOperands (CmpIPredicate predicate)
static void buildCmpFOp (OpBuilder &build, OperationState &result, CmpFPredicate predicate, Value lhs, Value rhs)
static void print (OpAsmPrinter &p, ConstantOp &op)
static ParseResult parseConstantOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (ConstantOp &op)
The constant op requires an attribute, and furthermore requires that it matches the return type.
static LogicalResult verify (DeallocOp op)
static LogicalResult verify (DimOp op)
static ParseResult parseDynamicTensorFromElementsOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, DynamicTensorFromElementsOp op)
static LogicalResult verify (DynamicTensorFromElementsOp op)
static void printGlobalMemrefOpTypeAndInitialValue (OpAsmPrinter &p, GlobalMemrefOp op, TypeAttr type, Attribute initialValue)
static ParseResult parseGlobalMemrefOpTypeAndInitialValue (OpAsmParser &parser, TypeAttr &typeAttr, Attribute &initialValue)
static LogicalResult verify (GlobalMemrefOp op)
static LogicalResult verify (LoadOp op)
static void print (OpAsmPrinter &p, MemRefReinterpretCastOp op)
Print a memref_reinterpret_cast op of the form: `` memref_reinterpret_castssa-name to offset:[offset] sizes:[size-list] strides:[stride-list] :any-memref-type to strided-memref-type ``.
static ParseResult parseMemRefReinterpretCastOp (OpAsmParser &parser, OperationState &result)
Parse a memref_reinterpret_cast op of the form: `` memref_reinterpret_castssa-name to offset:[offset] sizes:[size-list] strides:[stride-list] :any-memref-type to strided-memref-type ``.
static LogicalResult verify (MemRefReinterpretCastOp op)
static LogicalResult verify (MemRefReshapeOp op)
static void print (OpAsmPrinter &p, PrefetchOp op)
static ParseResult parsePrefetchOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (PrefetchOp op)
static LogicalResult verify (ReturnOp op)
static void print (OpAsmPrinter &p, SelectOp op)
static ParseResult parseSelectOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (SelectOp op)
static LogicalResult verify (SignExtendIOp op)
static APInt signedCeilNonnegInputs (APInt a, APInt b, bool &overflow)
static LogicalResult verify (SplatOp op)
static LogicalResult verify (StoreOp op)
static void print (OpAsmPrinter &p, SubViewOp op)
Print a subview op of the form: `` subviewssa-name [offset-list][size-list][stride-list] :strided-memref-typetostrided-memref-type ``.
static ParseResult parseSubViewOp (OpAsmParser &parser, OperationState &result)
Parse a subview op of the form: `` subviewssa-name [offset-list][size-list][stride-list] :strided-memref-typetostrided-memref-type ``.
static SubViewVerificationResult isRankReducedType (Type originalType, Type reducedType)
Checks if original Type type can be rank reduced to reduced type.
template<typename OpTy >
static LogicalResult produceSubViewErrorMsg (SubViewVerificationResult result, OpTy op, Type expectedType)
static LogicalResult verify (SubViewOp op)
Verifier for SubViewOp.
static void print (OpAsmPrinter &p, SubTensorOp op)
Print a subtensor op of the form: `` subtensorssa-name [offset-list][size-list][stride-list] :ranked-tensor-typetoranked-tensor-type ``.
static ParseResult parseSubTensorOp (OpAsmParser &parser, OperationState &result)
Parse a subtensor op of the form: `` subtensorssa-name [offset-list][size-list][stride-list] :ranked-tensor-typetoranked-tensor-type ``.
static LogicalResult verify (SubTensorOp op)
Verifier for SubTensorOp.
static void print (OpAsmPrinter &p, SubTensorInsertOp op)
Print a subtensor_insert op of the form: `` subtensor_insertssa-nameintossa-name [offset-list][size-list][stride-list] :ranked-tensor-typeintoranked-tensor-type ``.
static ParseResult parseSubTensorInsertOp (OpAsmParser &parser, OperationState &result)
Parse a subtensor_insert op of the form: `` subtensor_insertssa-nameintossa-name [offset-list][size-list][stride-list] :ranked-tensor-typeintoranked-tensor-type ``.
static LogicalResult verify (SubTensorInsertOp op)
Verifier for SubViewOp.
static TensorType joinShapes (TensorType one, TensorType two)
Compute a TensorType that has the joined shape knowledge of the two given TensorTypes.
static MemRefType inferTransposeResultType (MemRefType memRefType, AffineMap permutationMap)
Build a strided memref type by applying permutationMap tp memRefType.
static void print (OpAsmPrinter &p, TransposeOp op)
static ParseResult parseTransposeOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (TransposeOp op)
static LogicalResult verify (TruncateIOp op)
static ParseResult parseViewOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ViewOp op)
static LogicalResult verify (ViewOp op)
static LogicalResult verify (ZeroExtendIOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 4337 of file Ops.cpp.
GET_OP_LIST
#define GET_OP_LIST
Enumeration Type Documentation
SubViewVerificationResult
enum SubViewVerificationResult
Enumerator
Success
RankTooLarge
SizeMismatch
StrideMismatch
ElemTypeMismatch
MemSpaceMismatch
AffineMapMismatch
Definition at line 3171 of file Ops.cpp.
Function Documentation
applyCmpPredicateToEqualOperands()
static bool applyCmpPredicateToEqualOperands (CmpIPredicate predicate) static
Definition at line 808 of file Ops.cpp.
References mlir::applyCmpPredicate(), mlir::edsc::op::eq(), mlir::BoolAttr::get(), mlir::IntegerAttr::getValue(), mlir::edsc::op::ne(), mlir::edsc::op::sge(), mlir::edsc::op::sgt(), mlir::edsc::op::sle(), mlir::edsc::op::slt(), mlir::edsc::op::uge(), mlir::edsc::op::ugt(), mlir::edsc::op::ule(), and mlir::edsc::op::ult().
areVectorCastSimpleCompatible()
static bool areVectorCastSimpleCompatible (Type a, Type b, function_ref< bool(Type, Type)> areElementsCastCompatible) static
This method checks for cast compatibility of vector types.
If 'a' and 'b' are vector types, and they are cast compatible, it calls the 'areElementsCastCompatible' function to check for element cast compatibility. Returns 'true' if the vector types are cast compatible, and 'false' otherwise.
Definition at line 209 of file Ops.cpp.
References mlir::Type::dyn_cast().
Referenced by signedCeilNonnegInputs(), and verify().
buildCmpFOp()
static void buildCmpFOp (OpBuilder & build, OperationState & result, CmpFPredicate predicate, Value lhs, Value rhs) static
Definition at line 848 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
buildCmpIOp()
static void buildCmpIOp (OpBuilder & build, OperationState & result, CmpIPredicate predicate, Value lhs, Value rhs) static
Definition at line 770 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), getI1SameShape(), mlir::Builder::getI64IntegerAttr(), mlir::Value::getType(), and mlir::OperationState::types.
collapseBranch()
static LogicalResult collapseBranch (Block *& successor, ValueRange & successorOperands, SmallVectorImpl< Value > & argStorage) static
Given a successor, try to collapse it to a new destination if it only contains a passthrough unconditional branch.
If the successor is collapsable, successor and successorOperands are updated to reference the new destination and values. argStorage is an optional storage to use if operands to the collapsed successor need to be remapped.
Definition at line 569 of file Ops.cpp.
References mlir::Block::args_empty(), mlir::Block::begin(), mlir::Value::dyn_cast(), mlir::Block::end(), mlir::PatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::FunctionType::get(), mlir::BlockArgument::getArgNumber(), mlir::Block::getArguments(), mlir::BlockArgument::getOwner(), mlir::Block::getPredecessors(), mlir::Block::getTerminator(), mlir::Operation::getUsers(), mlir::OwningRewritePatternList::insert(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), mlir::m_Constant(), mlir::matchPattern(), mlir::PatternRewriter::mergeBlocks(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by mlir::applyCmpPredicate().
extractFromI64ArrayAttr()
static SmallVector<int64_t, 4> extractFromI64ArrayAttr (Attribute attr) static
Extract int64_t values from the assumed ArrayAttr of IntegerAttr.
Definition at line 254 of file Ops.cpp.
References mlir::Attribute::cast().
Referenced by mlir::canFoldIntoConsumerOp(), finalizeBufferAllocation(), mlir::getOrCreateRanges(), mlir::LLVM::detail::vectorOneToOneRewrite(), and verify().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form "someop(memrefcast) -> someop".
It folds the source of any memref_cast into the root operation directly.
Definition at line 187 of file Ops.cpp.
References mlir::Operation::getOpOperands(), and mlir::success().
Referenced by mlir::DmaStartOp::fold(), mlir::DmaWaitOp::fold(), and verify().
getI1SameShape()
static Type getI1SameShape (Type type) static
Definition at line 755 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::IntegerType::get(), mlir::VectorType::get(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), mlir::Type::getContext(), and mlir::Type::isa().
Referenced by buildCmpFOp(), buildCmpIOp(), and verify().
getTensorTypeFromMemRefType()
static Type getTensorTypeFromMemRefType (Type type) static
Definition at line 223 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::RankedTensorType::get(), mlir::UnrankedTensorType::get(), mlir::Type::getContext(), mlir::m_Zero(), and mlir::matchPattern().
Referenced by parseGlobalMemrefOpTypeAndInitialValue(), and verify().
inferTransposeResultType()
static MemRefType inferTransposeResultType (MemRefType memRefType, AffineMap permutationMap) static
Build a strided memref type by applying permutationMap tp memRefType.
Definition at line 3969 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::Type::cast(), mlir::AffineMap::compose(), mlir::detail::enumerate(), mlir::AffineMap::getResults(), mlir::MemRefType::getShape(), mlir::getStridesAndOffset(), mlir::Value::getType(), mlir::AffineMapAttr::getValue(), mlir::makeStridedLinearLayoutMap(), mlir::MemRefType::Builder::setAffineMaps(), mlir::MemRefType::Builder::setShape(), and mlir::succeeded().
Referenced by verify().
isRankReducedType()
static SubViewVerificationResult isRankReducedType (Type originalType, Type reducedType) static
Checks if original Type type can be rank reduced to reduced type.
This function is slight variant of is subsequence algorithm where not matching dimension must be 1.
Definition at line 3184 of file Ops.cpp.
References AffineMapMismatch, mlir::Type::cast(), mlir::computeRankReductionMask(), ElemTypeMismatch, mlir::ShapedType::getShape(), mlir::getStridesAndOffset(), mlir::Type::isa(), mlir::makeStridedLinearLayoutMap(), MemSpaceMismatch, RankTooLarge, SizeMismatch, StrideMismatch, and Success.
Referenced by verify().
joinShapes()
static TensorType joinShapes (TensorType one, TensorType two) static
Compute a TensorType that has the joined shape knowledge of the two given TensorTypes.
The element types need to match.
Definition at line 3864 of file Ops.cpp.
References mlir::Type::cast(), mlir::failure(), mlir::RankedTensorType::get(), mlir::ShapedType::getDimSize(), mlir::ShapedType::getElementType(), mlir::ShapedType::getRank(), mlir::ShapedType::hasRank(), mlir::OwningRewritePatternList::insert(), mlir::ShapedType::isDynamicDim(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
m_ConstantIndex()
static detail::op_matcher<ConstantIndexOp> m_ConstantIndex () static
Matches a ConstantIndexOp.
TODO: This should probably just be a general matcher that uses m_Constant and checks the operation for an index type.
Definition at line 176 of file Ops.cpp.
Referenced by mlir::canFoldIntoConsumerOp(), mlir::getOrCreateRanges(), and verify().
parseConstantOp()
static ParseResult parseConstantOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1116 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), and mlir::OperationState::types.
parseDynamicTensorFromElementsOp()
static ParseResult parseDynamicTensorFromElementsOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1736 of file Ops.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperands(), and mlir::success().
parseGenericAtomicRMWOp()
static ParseResult parseGenericAtomicRMWOp (OpAsmParser & parser, OperationState & result) static
Definition at line 518 of file Ops.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, mlir::success(), and mlir::OperationState::types.
parseGlobalMemrefOpTypeAndInitialValue()
static ParseResult parseGlobalMemrefOpTypeAndInitialValue (OpAsmParser & parser, TypeAttr & typeAttr, Attribute & initialValue) static
Definition at line 2045 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::TypeAttr::get(), mlir::UnitAttr::get(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getNameLoc(), getTensorTypeFromMemRefType(), mlir::Attribute::isa(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseOptionalEqual(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseType(), mlir::succeeded(), and mlir::success().
parseMemRefReinterpretCastOp()
static ParseResult parseMemRefReinterpretCastOp (OpAsmParser & parser, OperationState & result) static
Parse a memref_reinterpret_cast op of the form: `` memref_reinterpret_castssa-name to offset:[offset] sizes:[size-list] strides:[stride-list] :any-memref-type to strided-memref-type ``.
Definition at line 2341 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failed(), mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColon(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseKeywordType(), mlir::parseOffsetsSizesAndStrides(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parsePrefetchOp()
static ParseResult parsePrefetchOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2521 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::Builder::getBoolAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::Builder::getIntegerType(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseGreater(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseLess(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::success().
parseSelectOp()
static ParseResult parseSelectOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2640 of file Ops.cpp.
References mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI1Type(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperands(), and mlir::succeeded().
parseSubTensorInsertOp()
static ParseResult parseSubTensorInsertOp (OpAsmParser & parser, OperationState & result) static
Parse a subtensor_insert op of the form: `` subtensor_insertssa-nameintossa-name [offset-list][size-list][stride-list] :ranked-tensor-typeintoranked-tensor-type ``.
Definition at line 3782 of file Ops.cpp.
References mlir::OperationState::addAttributes(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failed(), mlir::failure(), mlir::Builder::getI64ArrayAttr(), mlir::Value::getType(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseKeywordType(), mlir::parseOffsetsSizesAndStrides(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseSubTensorOp()
static ParseResult parseSubTensorOp (OpAsmParser & parser, OperationState & result) static
Parse a subtensor op of the form: `` subtensorssa-name [offset-list][size-list][stride-list] :ranked-tensor-typetoranked-tensor-type ``.
Definition at line 3668 of file Ops.cpp.
References mlir::OperationState::addAttributes(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failed(), mlir::failure(), mlir::RankedTensorType::get(), mlir::Builder::getI64ArrayAttr(), mlir::Value::getType(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::parseOffsetsSizesAndStrides(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseSubViewOp()
static ParseResult parseSubViewOp (OpAsmParser & parser, OperationState & result) static
Parse a subview op of the form: `` subviewssa-name [offset-list][size-list][stride-list] :strided-memref-typetostrided-memref-type ``.
Definition at line 3059 of file Ops.cpp.
References mlir::OperationState::addAttributes(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Type::cast(), mlir::failed(), mlir::failure(), mlir::Builder::getI64ArrayAttr(), mlir::Value::getType(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::parseOffsetsSizesAndStrides(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseTransposeOp()
static ParseResult parseTransposeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 4013 of file Ops.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::AffineMapAttr::get(), mlir::OperationState::operands, mlir::OpAsmParser::parseAffineMap(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseViewOp()
static ParseResult parseViewOp (OpAsmParser & parser, OperationState & result) static
Definition at line 4134 of file Ops.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::OpAsmParser::Square, and mlir::OperationState::types.
print() [1/11]
static void print (OpAsmPrinter & p, GenericAtomicRMWOp op) static
Definition at line 540 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [2/11]
static void print (OpAsmPrinter & p, ConstantOp & op) static
Definition at line 1103 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [3/11]
static void print (OpAsmPrinter & p, DynamicTensorFromElementsOp op) static
Definition at line 1760 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
print() [4/11]
static void print (OpAsmPrinter & p, MemRefReinterpretCastOp op) static
Print a memref_reinterpret_cast op of the form: `` memref_reinterpret_castssa-name to offset:[offset] sizes:[size-list] strides:[stride-list] :any-memref-type to strided-memref-type ``.
Definition at line 2323 of file Ops.cpp.
References mlir::printOffsetsSizesAndStrides().
print() [5/11]
static void print (OpAsmPrinter & p, PrefetchOp op) static
Definition at line 2509 of file Ops.cpp.
References mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [6/11]
static void print (OpAsmPrinter & p, SelectOp op) static
Definition at line 2631 of file Ops.cpp.
References mlir::Type::dyn_cast(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [7/11]
static void print (OpAsmPrinter & p, SubViewOp op) static
Print a subview op of the form: `` subviewssa-name [offset-list][size-list][stride-list] :strided-memref-typetostrided-memref-type ``.
Definition at line 3045 of file Ops.cpp.
References mlir::printOffsetsSizesAndStrides().
print() [8/11]
static void print (OpAsmPrinter & p, SubTensorOp op) static
Print a subtensor op of the form: `` subtensorssa-name [offset-list][size-list][stride-list] :ranked-tensor-typetoranked-tensor-type ``.
Definition at line 3654 of file Ops.cpp.
References mlir::printOffsetsSizesAndStrides().
print() [9/11]
static void print (OpAsmPrinter & p, SubTensorInsertOp op) static
Print a subtensor_insert op of the form: `` subtensor_insertssa-nameintossa-name [offset-list][size-list][stride-list] :ranked-tensor-typeintoranked-tensor-type ``.
Definition at line 3768 of file Ops.cpp.
References mlir::printOffsetsSizesAndStrides().
print() [10/11]
static void print (OpAsmPrinter & p, TransposeOp op) static
Definition at line 4006 of file Ops.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [11/11]
static void print (OpAsmPrinter & p, ViewOp op) static
Definition at line 4159 of file Ops.cpp.
References mlir::OpAsmPrinter::printOperand(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printGlobalMemrefOpTypeAndInitialValue()
static void printGlobalMemrefOpTypeAndInitialValue (OpAsmPrinter & p, GlobalMemrefOp op, TypeAttr type, Attribute initialValue) static
Definition at line 2030 of file Ops.cpp.
References mlir::OpAsmPrinter::printAttributeWithoutType().
printStandardBinaryOp()
static void printStandardBinaryOp (Operation * op, OpAsmPrinter & p) static
A custom binary operation printer that omits the "std." prefix from the operation names.
Definition at line 113 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), mlir::Value::getType(), mlir::OpAsmPrinter::printGenericOp(), and mlir::OpAsmPrinter::printOptionalAttrDict().
printStandardCastOp()
static void printStandardCastOp (Operation * op, OpAsmPrinter & p) static
A custom cast operation printer that omits the "std." prefix from the operation names.
Definition at line 137 of file Ops.cpp.
References mlir::Operation::getName(), mlir::Operation::getOperand(), mlir::Operation::getResult(), mlir::OperationName::getStringRef(), and mlir::Value::getType().
printStandardUnaryOp()
static void printStandardUnaryOp (Operation * op, OpAsmPrinter & p) static
A custom unary operation printer that omits the "std." prefix from the operation names.
Definition at line 100 of file Ops.cpp.
References mlir::Operation::getAttrs(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperand(), mlir::OperationName::getStringRef(), mlir::Value::getType(), and mlir::OpAsmPrinter::printOptionalAttrDict().
produceSubViewErrorMsg()
template<typename OpTy > static LogicalResult produceSubViewErrorMsg (SubViewVerificationResult result, OpTy op, Type expectedType) static
Definition at line 3253 of file Ops.cpp.
References AffineMapMismatch, mlir::Type::cast(), ElemTypeMismatch, MemSpaceMismatch, RankTooLarge, SizeMismatch, StrideMismatch, mlir::success(), and Success.
Referenced by verify().
signedCeilNonnegInputs()
static APInt signedCeilNonnegInputs (APInt a, APInt b, bool & overflow) static
Definition at line 2741 of file Ops.cpp.
References areVectorCastSimpleCompatible(), mlir::ceil(), mlir::IntegerAttr::get(), mlir::IntegerAttr::getValue(), mlir::Type::isa(), and mlir::Type::isSignlessInteger().
verify() [1/27]
static LogicalResult verify (AllocOp op) static
Definition at line 288 of file Ops.cpp.
References verifyAllocLikeOp().
verify() [2/27]
static LogicalResult verify (AllocaOp op) static
Definition at line 290 of file Ops.cpp.
References mlir::OpBuilder::create(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::OwningRewritePatternList::insert(), m_ConstantIndex(), mlir::m_ConstantInt(), mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), mlir::PatternRewriter::replaceOp(), mlir::MemRefType::Builder::setShape(), mlir::success(), and verifyAllocLikeOp().
verify() [3/27]
static LogicalResult verify (AssumeAlignmentOp op) static
Definition at line 436 of file Ops.cpp.
References mlir::success().
verify() [4/27]
static LogicalResult verify (AtomicRMWOp op) static
Definition at line 447 of file Ops.cpp.
References mlir::Region::addArgument(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::Value::getType(), mlir::Region::push_back(), and mlir::success().
verify() [5/27]
static LogicalResult verify (GenericAtomicRMWOp op) static
Definition at line 497 of file Ops.cpp.
References mlir::WalkResult::advance(), mlir::Operation::emitError(), mlir::failure(), hasSideEffects(), mlir::WalkResult::interrupt(), and mlir::success().
verify() [6/27]
static LogicalResult verify (AtomicYieldOp op) static
Definition at line 551 of file Ops.cpp.
References mlir::success().
verify() [7/27]
static LogicalResult verify (ConstantOp & op) static
The constant op requires an attribute, and furthermore requires that it matches the return type.
Definition at line 1136 of file Ops.cpp.
References mlir::Type::cast(), mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::Attribute::getType(), mlir::IntegerType::getWidth(), mlir::Attribute::isa(), mlir::Type::isa(), mlir::IntegerType::isSignless(), and mlir::success().
verify() [8/27]
static LogicalResult verify (DeallocOp op) static
Definition at line 1317 of file Ops.cpp.
References mlir::OpBuilder::create(), foldMemRefCast(), mlir::Builder::getIndexType(), mlir::OwningRewritePatternList::insert(), mlir::OperationState::location, and mlir::success().
verify() [9/27]
static LogicalResult verify (DimOp op) static
Definition at line 1357 of file Ops.cpp.
References mlir::Value::dyn_cast(), mlir::Type::dyn_cast(), mlir::failure(), foldMemRefCast(), mlir::Value::getDefiningOp(), mlir::Builder::getIndexAttr(), mlir::Value::getType(), mlir::OwningRewritePatternList::insert(), mlir::Type::isa(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::OpBuilder::setInsertionPointAfter(), mlir::succeeded(), and mlir::success().
verify() [10/27]
static LogicalResult verify (DynamicTensorFromElementsOp op) static
Definition at line 1767 of file Ops.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), areVectorCastSimpleCompatible(), mlir::Type::cast(), mlir::OpBuilder::clone(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Type::dyn_cast(), mlir::Region::end(), mlir::failure(), mlir::RankedTensorType::get(), mlir::Block::getArguments(), mlir::Builder::getIndexType(), mlir::Block::getTerminator(), mlir::ValueRange::getType(), mlir::PatternRewriter::inlineRegionBefore(), mlir::OwningRewritePatternList::insert(), mlir::Type::isa(), mlir::Type::isSignlessInteger(), mlir::OperationState::location, mlir::BlockAndValueMapping::lookupOrDefault(), mlir::m_ConstantInt(), mlir::BlockAndValueMapping::map(), mlir::matchPattern(), mlir::OperationState::regions, mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::success(), mlir::Block::without_terminator(), and mlir::wouldOpBeTriviallyDead().
verify() [11/27]
static LogicalResult verify (GlobalMemrefOp op) static
Definition at line 2074 of file Ops.cpp.
References mlir::Type::cast(), mlir::IntegerAttr::get(), mlir::ShapedType::getElementType(), mlir::ShapedType::getShape(), getTensorTypeFromMemRefType(), mlir::Attribute::getType(), mlir::Attribute::isa(), mlir::Type::isa(), mlir::Type::isIndex(), mlir::Type::isSignlessInteger(), mlir::SymbolTableCollection::lookupNearestSymbolFrom(), and mlir::success().
verify() [12/27]
static LogicalResult verify (LoadOp op) static
Definition at line 2164 of file Ops.cpp.
References mlir::OperationState::addAttributes(), mlir::Type::dyn_cast(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::impl::foldCastOp(), foldMemRefCast(), mlir::MemRefType::getAffineMaps(), mlir::MemRefType::getDynamicStrideOrOffset(), mlir::Builder::getI64ArrayAttr(), mlir::getStridesAndOffset(), mlir::OwningRewritePatternList::insert(), mlir::ShapedType::kDynamicSize, mlir::ShapedType::kDynamicStrideOrOffset, mlir::PatternRewriter::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
verify() [13/27]
static LogicalResult verify (MemRefReinterpretCastOp op) static
Definition at line 2376 of file Ops.cpp.
References mlir::detail::enumerate(), extractFromI64ArrayAttr(), mlir::failed(), mlir::failure(), mlir::BaseMemRefType::getMemorySpace(), mlir::getStridesAndOffset(), and mlir::success().
verify() [14/27]
static LogicalResult verify (MemRefReshapeOp op) static
Definition at line 2432 of file Ops.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), getElementType(), mlir::ShapedType::kDynamicSize, mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verify() [15/27]
static LogicalResult verify (PrefetchOp op) static
Definition at line 2562 of file Ops.cpp.
References mlir::Type::dyn_cast(), foldMemRefCast(), mlir::IntegerAttr::get(), and mlir::success().
verify() [16/27]
static LogicalResult verify (ReturnOp op) static
Definition at line 2593 of file Ops.cpp.
References mlir::m_One(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verify() [17/27]
static LogicalResult verify (SelectOp op) static
Definition at line 2663 of file Ops.cpp.
References getI1SameShape(), mlir::Type::isa(), mlir::Type::isSignlessInteger(), and mlir::success().
verify() [18/27]
static LogicalResult verify (SignExtendIOp op) static
Definition at line 2688 of file Ops.cpp.
References mlir::getElementTypeOrSelf(), mlir::IntegerAttr::getValue(), mlir::IntegerType::getWidth(), and mlir::success().
verify() [19/27]
static LogicalResult verify (SplatOp op) static
Definition at line 2885 of file Ops.cpp.
References mlir::DenseElementsAttr::get(), getElementType(), and mlir::success().
verify() [20/27]
static LogicalResult verify (StoreOp op) static
Definition at line 2914 of file Ops.cpp.
References areVectorCastSimpleCompatible(), foldMemRefCast(), mlir::Builder::getZeroAttr(), mlir::Type::isa(), mlir::Type::isSignlessInteger(), mlir::m_Zero(), mlir::matchPattern(), and mlir::success().
verify() [21/27]
static LogicalResult verify (SubViewOp op) static
Verifier for SubViewOp.
Definition at line 3284 of file Ops.cpp.
References extractFromI64ArrayAttr(), isRankReducedType(), mlir::isStrided(), and produceSubViewErrorMsg().
verify() [22/27]
static LogicalResult verify (SubTensorOp op) static
Verifier for SubTensorOp.
Definition at line 3741 of file Ops.cpp.
References extractFromI64ArrayAttr(), mlir::OwningRewritePatternList::insert(), isRankReducedType(), and produceSubViewErrorMsg().
verify() [23/27]
static LogicalResult verify (SubTensorInsertOp op) static
Verifier for SubViewOp.
Definition at line 3836 of file Ops.cpp.
References mlir::Type::dyn_cast(), mlir::impl::foldCastOp(), mlir::ShapedType::getElementType(), mlir::succeeded(), mlir::success(), and mlir::verifyCompatibleShape().
verify() [24/27]
static LogicalResult verify (TransposeOp op) static
Definition at line 4031 of file Ops.cpp.
References foldMemRefCast(), inferTransposeResultType(), mlir::succeeded(), and mlir::success().
verify() [25/27]
static LogicalResult verify (TruncateIOp op) static
Definition at line 4058 of file Ops.cpp.
References mlir::IntegerAttr::get(), mlir::getElementTypeOrSelf(), mlir::IntegerAttr::getValue(), mlir::IntegerType::getWidth(), and mlir::success().
verify() [26/27]
static LogicalResult verify (ViewOp op) static
Definition at line 4167 of file Ops.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::MemRefType::getAffineMaps(), mlir::Value::getDefiningOp(), mlir::getStridesAndOffset(), mlir::Builder::getZeroAttr(), mlir::OwningRewritePatternList::insert(), mlir::ShapedType::isDynamic(), m_ConstantIndex(), mlir::m_Zero(), mlir::matchPattern(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::MemRefType::Builder::setShape(), and mlir::success().
verify() [27/27]
static LogicalResult verify (ZeroExtendIOp op) static
Definition at line 4316 of file Ops.cpp.
References mlir::getElementTypeOrSelf(), mlir::IntegerType::getWidth(), and mlir::success().
verifyAllocLikeOp()
template<typename AllocLikeOp > static LogicalResult verifyAllocLikeOp (AllocLikeOp op) static
Definition at line 266 of file Ops.cpp.
References mlir::success().
Referenced by verify().
verifyCastOp()
template<typename T > static LogicalResult verifyCastOp (T op) static
A custom cast operation verifier.
Definition at line 146 of file Ops.cpp.
References mlir::OpBuilder::create(), materializeConstant(), and mlir::success().