MLIR: lib/Pass/Pass.cpp File Reference
Pass.cpp File Reference
#include "mlir/Pass/Pass.h"
#include "PassDetail.h"
#include "mlir/IR/Diagnostics.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Verifier.h"
#include "mlir/Support/FileUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/CrashRecoveryContext.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/Threading.h"
#include "llvm/Support/ToolOutputFile.h"
Classes
struct mlir::detail::OpPassManagerImpl
struct mlir::detail::PassInstrumentorImpl
Namespaces
mlir
Include the generated interface declarations.
mlir::detail
Functions
static void printAsTextualPipeline (ArrayRef< std::unique_ptr< Pass >> passes, raw_ostream &os)
Prints out the given passes as the textual representation of a pipeline.
static void registerDialectsForPipeline (const OpPassManager &pm, DialectRegistry &dialects)
static OpPassManager * findPassManagerFor (MutableArrayRef< OpPassManager > mgrs, StringRef name)
Find an operation pass manager that can operate on an operation of the given type, or nullptr if one does not exist.
static OpPassManager * findPassManagerFor (MutableArrayRef< OpPassManager > mgrs, Identifier name, MLIRContext &context)
Find an operation pass manager that can operate on an operation of the given type, or nullptr if one does not exist.
static bool hasSizeMismatch (ArrayRef< OpPassManager > lhs, ArrayRef< OpPassManager > rhs)
Utility functor that checks if the two ranges of pass managers have a size mismatch.
Function Documentation
findPassManagerFor() [1/2]
static OpPassManager* findPassManagerFor (MutableArrayRef< OpPassManager > mgrs, StringRef name) static
Find an operation pass manager that can operate on an operation of the given type, or nullptr if one does not exist.
Definition at line 419 of file Pass.cpp.
References mlir::OpPassManager::getOpName().
Referenced by hasSizeMismatch(), mlir::detail::OpToOpPassAdaptor::mergeInto(), and mlir::detail::OpToOpPassAdaptor::runOnOperation().
findPassManagerFor() [2/2]
static OpPassManager* findPassManagerFor (MutableArrayRef< OpPassManager > mgrs, Identifier name, MLIRContext & context) static
Find an operation pass manager that can operate on an operation of the given type, or nullptr if one does not exist.
Definition at line 428 of file Pass.cpp.
References mlir::OpPassManager::getOpName().
hasSizeMismatch()
static bool hasSizeMismatch (ArrayRef< OpPassManager > lhs, ArrayRef< OpPassManager > rhs) static
Utility functor that checks if the two ranges of pass managers have a size mismatch.
Definition at line 515 of file Pass.cpp.
References mlir::Operation::clone(), mlir::Operation::emitError(), mlir::ParallelDiagnosticHandler::eraseOrderIDForThread(), mlir::failed(), mlir::failure(), findPassManagerFor(), mlir::Operation::getContext(), mlir::OperationName::getIdentifier(), mlir::Operation::getName(), mlir::AnalysisManager::getPassInstrumentor(), mlir::AnalysisManager::nest(), mlir::openOutputFile(), mlir::OpPassManager::printAsTextualPipeline(), mlir::MLIRContext::printOpOnDiagnostic(), mlir::ParallelDiagnosticHandler::setOrderIDForThread(), mlir::MLIRContext::shouldPrintOpOnDiagnostic(), mlir::succeeded(), and mlir::success().
printAsTextualPipeline()
static void printAsTextualPipeline (ArrayRef< std::unique_ptr< Pass >> passes, raw_ostream & os) static
Prints out the given passes as the textual representation of a pipeline.
Definition at line 294 of file Pass.cpp.
Referenced by mlir::OpPassManager::addNestedPass(), and mlir::Pass::ListOption< DataType, OptionParser >::ListOption().
registerDialectsForPipeline()
static void registerDialectsForPipeline (const OpPassManager & pm, DialectRegistry & dialects) static
Definition at line 313 of file Pass.cpp.
References mlir::OpPassManager::getPasses().
Referenced by mlir::OpPassManager::getDependentDialects().