MLIR: lib/Dialect/PDLInterp/IR/PDLInterp.cpp File Reference
PDLInterp.cpp File Reference
#include "mlir/Dialect/PDLInterp/IR/PDLInterp.h"
#include "mlir/Dialect/PDL/IR/PDLTypes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/Dialect/PDLInterp/IR/PDLInterpOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static ParseResult parseCreateOperationOp (OpAsmParser &p, OperationState &state)
static void print (OpAsmPrinter &p, CreateOperationOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 121 of file PDLInterp.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseCreateOperationOp()
static ParseResult parseCreateOperationOp (OpAsmParser & p, OperationState & state) static
Definition at line 32 of file PDLInterp.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addTypes(), mlir::OperationState::attributes, mlir::failure(), mlir::Builder::getArrayAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getType(), mlir::OperationState::operands, mlir::OpAsmParser::parseArrow(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalLBrace(), mlir::OpAsmParser::parseOptionalLParen(), mlir::OpAsmParser::parseRBrace(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), and mlir::success().
print()
static void print (OpAsmPrinter & p, CreateOperationOp op) static
Definition at line 93 of file PDLInterp.cpp.
References mlir::ArrayAttr::empty(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::ArrayAttr::size().