MLIR: include/mlir-c/Registration.h File Reference
Registration.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_CAPI_EXPORTED void mlirRegisterAllDialects (MlirContext context)
Registers all dialects known to core MLIR with the provided Context.
Function Documentation
mlirRegisterAllDialects()
MLIR_CAPI_EXPORTED void mlirRegisterAllDialects (MlirContext context)
Registers all dialects known to core MLIR with the provided Context.
This is needed before creating IR for these Dialects.
Definition at line 14 of file Registration.cpp.
References mlir::registerAllDialects(), and unwrap().
Referenced by mlir::python::PyMlirContext::createNewContextForInit().