MLIR: lib/Dialect/SCF/SCF.cpp File Reference
SCF.cpp File Reference
#include "mlir/Dialect/SCF/SCF.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Support/MathExtras.h"
#include "mlir/Transforms/InliningUtils.h"
#include "mlir/Dialect/SCF/SCFOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static LogicalResult verify (ForOp op)
static void printInitializationList (OpAsmPrinter &p, Block::BlockArgListType blocksArgs, ValueRange initializers, StringRef prefix="")
Prints the initialization list in the form of <prefix>(inner = outer, inner2 = outer2, <...>) where 'inner' values are assumed to be region arguments and 'outer' values are regular SSA values.
static void print (OpAsmPrinter &p, ForOp op)
static ParseResult parseForOp (OpAsmParser &parser, OperationState &result)
static void replaceOpWithRegion (PatternRewriter &rewriter, Operation *op, Region &region, ValueRange blockArgs={})
Replaces the given op with the contents of the given single-block region, using the operands of the block terminator to replace operation results.
static LogicalResult verify (IfOp op)
static ParseResult parseIfOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, IfOp op)
static LogicalResult verify (ParallelOp op)
static ParseResult parseParallelOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ParallelOp op)
static LogicalResult verify (ReduceOp op)
static ParseResult parseReduceOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReduceOp op)
static LogicalResult verify (ReduceReturnOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
parseForOp()
static ParseResult parseForOp (OpAsmParser & parser, OperationState & result) static
Definition at line 178 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::ceilDiv(), mlir::Value::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::scf::getForInductionVarOwner(), mlir::Builder::getIndexType(), mlir::OpAsmParser::getNameLoc(), mlir::Value::getParentRegion(), mlir::IntegerAttr::getValue(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseArrowTypeList(), mlir::OpAsmParser::parseAssignmentList(), mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgument(), mlir::OpAsmParser::resolveOperand(), mlir::succeeded(), mlir::success(), and mlir::OperationState::types.
parseIfOp()
static ParseResult parseIfOp (OpAsmParser & parser, OperationState & result) static
Definition at line 627 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIntegerType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseParallelOp()
static ParseResult parseParallelOp (OpAsmParser & parser, OperationState & result) static
Definition at line 917 of file SCF.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseEqual(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRegionArgumentList(), mlir::OpAsmParser::resolveOperands(), mlir::succeeded(), mlir::success(), and mlir::OperationState::types.
parseReduceOp()
static ParseResult parseReduceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1141 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::failure(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseLParen(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseRParen(), mlir::OpAsmParser::resolveOperand(), and mlir::success().
print() [1/4]
static void print (OpAsmPrinter & p, ForOp op) static
Definition at line 164 of file SCF.cpp.
References printInitializationList(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
Referenced by verify().
print() [2/4]
static void print (OpAsmPrinter & p, IfOp op) static
Definition at line 660 of file SCF.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::Region::empty(), mlir::detail::enumerate(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::Block::getArguments(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::OpResult::getResultNumber(), mlir::Block::getTerminator(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::OwningRewritePatternList::insert(), mlir::OperationState::location, mlir::PatternRewriter::mergeBlocks(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::PatternRewriter::replaceOp(), replaceOpWithRegion(), mlir::OpBuilder::setInsertionPointToStart(), mlir::success(), and mlir::PatternRewriter::updateRootInPlace().
print() [3/4]
static void print (OpAsmPrinter & p, ParallelOp op) static
Definition at line 988 of file SCF.cpp.
References mlir::Value::getParentRegion(), mlir::Region::isAncestor(), mlir::Operation::moveBefore(), mlir::OpAsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), and mlir::success().
print() [4/4]
static void print (OpAsmPrinter & p, ReduceOp op) static
Definition at line 1162 of file SCF.cpp.
References mlir::OpAsmPrinter::printRegion().
printInitializationList()
static void printInitializationList (OpAsmPrinter & p, Block::BlockArgListType blocksArgs, ValueRange initializers, StringRef prefix = "") static
Prints the initialization list in the form of <prefix>(inner = outer, inner2 = outer2, <...>) where 'inner' values are assumed to be region arguments and 'outer' values are regular SSA values.
Definition at line 148 of file SCF.cpp.
Referenced by print(), and verify().
replaceOpWithRegion()
static void replaceOpWithRegion (PatternRewriter & rewriter, Operation * op, Region & region, ValueRange blockArgs = {}) static
Replaces the given op with the contents of the given single-block region, using the operands of the block terminator to replace operation results.
Definition at line 398 of file SCF.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Value::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createBlock(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::Region::front(), mlir::Block::front(), mlir::Value::getDefiningOp(), mlir::OpBuilder::getInsertionBlock(), mlir::Block::getNumArguments(), mlir::Operation::getOperands(), mlir::Block::getParent(), mlir::Block::getTerminator(), mlir::OwningRewritePatternList::insert(), mlir::OperationState::location, mlir::PatternRewriter::mergeBlockBefore(), mlir::PatternRewriter::mergeBlocks(), mlir::PatternRewriter::replaceOp(), mlir::OpBuilder::setInsertionPoint(), mlir::edsc::op::sge(), and mlir::success().
Referenced by print().
verify() [1/5]
static LogicalResult verify (ForOp op) static
Definition at line 101 of file SCF.cpp.
References mlir::success().
verify() [2/5]
static LogicalResult verify (IfOp op) static
Definition at line 620 of file SCF.cpp.
verify() [3/5]
static LogicalResult verify (ParallelOp op) static
Definition at line 856 of file SCF.cpp.
References mlir::Operation::emitOpError(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Operation::getNumOperands(), mlir::Block::getOps(), mlir::Block::getTerminator(), and mlir::success().
verify() [4/5]
static LogicalResult verify (ReduceOp op) static
Definition at line 1120 of file SCF.cpp.
References mlir::Operation::emitOpError(), mlir::Block::empty(), mlir::Block::front(), mlir::Block::getArguments(), mlir::Block::getNumArguments(), mlir::Block::getTerminator(), and mlir::success().
verify() [5/5]
static LogicalResult verify (ReduceReturnOp op) static
Definition at line 1172 of file SCF.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::InFlightDiagnostic::attachNote(), mlir::OperationState::attributes, diag(), mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::Region::front(), mlir::OpAsmParser::getCurrentLocation(), mlir::FunctionType::getInputs(), mlir::Operation::getLoc(), mlir::FunctionType::getNumInputs(), mlir::FunctionType::getResults(), mlir::Block::getTerminator(), mlir::OptionalParseResult::getValue(), mlir::OptionalParseResult::hasValue(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAssignmentList(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseOptionalColonTypeList(), mlir::OpAsmParser::parseRegion(), parseYieldOp(), print(), mlir::OpAsmPrinter::printFunctionalType(), printInitializationList(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::verify().