MLIR: lib/Dialect/Shape/IR/Shape.cpp File Reference
Shape.cpp File Reference
#include "mlir/Dialect/Shape/IR/Shape.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Traits.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Transforms/InliningUtils.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Support/raw_ostream.h"
#include "ShapeCanonicalization.inc"
#include "mlir/Dialect/Shape/IR/ShapeOps.cpp.inc"
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Functions
static bool isErrorPropagationPossible (TypeRange operandTypes)
static LogicalResult verifySizeOrIndexOp (Operation *op)
static LogicalResult verifyShapeOrExtentTensorOp (Operation *op)
static ParseResult parseAssumingOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, AssumingOp op)
static LogicalResult verify (AssumingAllOp op)
static void print (OpAsmPrinter &p, ConstShapeOp &op)
static ParseResult parseConstShapeOp (OpAsmParser &parser, OperationState &result)
ParseResult parseFunctionLibraryOp (OpAsmParser &parser, OperationState &result)
void print (OpAsmPrinter &p, FunctionLibraryOp op)
static LogicalResult verify (shape::YieldOp op)
static LogicalResult verify (ReduceOp op)
static ParseResult parseReduceOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReduceOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 985 of file Shape.cpp.
GET_OP_LIST
#define GET_OP_LIST
Function Documentation
isErrorPropagationPossible()
static bool isErrorPropagationPossible (TypeRange operandTypes) static
Definition at line 33 of file Shape.cpp.
References mlir::Type::isa().
Referenced by verifyShapeOrExtentTensorOp(), and verifySizeOrIndexOp().
parseAssumingOp()
static ParseResult parseAssumingOp (OpAsmParser & parser, OperationState & result) static
Definition at line 165 of file Shape.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OperationState::regions, mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseConstShapeOp()
static ParseResult parseConstShapeOp (OpAsmParser & parser, OperationState & result) static
Definition at line 363 of file Shape.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::BoolAttr::get(), mlir::OpAsmParser::getBuilder(), mlir::Value::getDefiningOp(), mlir::OperationName::getIdentifier(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexTensorAttr(), mlir::IntegerAttr::getInt(), mlir::Operation::getName(), mlir::Builder::getNamedAttr(), mlir::Builder::getStringAttr(), mlir::SymbolTable::getSymbolAttrName(), mlir::OwningRewritePatternList::insert(), mlir::OperationState::location, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::NamedAttrList::push_back(), mlir::OpTrait::util::staticallyKnownBroadcastable(), mlir::success(), and mlir::OperationState::types.
parseFunctionLibraryOp()
ParseResult parseFunctionLibraryOp (OpAsmParser & parser, OperationState & result)
Definition at line 584 of file Shape.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::SymbolTable::getSymbolAttrName(), mlir::Builder::getType(), mlir::OperationState::location, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseKeyword(), mlir::OpAsmParser::parseOptionalAttrDictWithKeyword(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::parseSymbolName(), and mlir::success().
parseReduceOp()
static ParseResult parseReduceOp (OpAsmParser & parser, OperationState & result) static
Definition at line 947 of file Shape.cpp.
References mlir::OperationState::addRegion(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::Paren, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalArrowTypeList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseRegion(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
print() [1/4]
static void print (OpAsmPrinter & p, AssumingOp op) static
Definition at line 192 of file Shape.cpp.
References mlir::Block::back(), mlir::Attribute::cast(), mlir::PatternRewriter::eraseOp(), mlir::failure(), mlir::BoolAttr::get(), mlir::OpBuilder::getInsertionBlock(), mlir::OpBuilder::getInsertionPoint(), mlir::BoolAttr::getValue(), mlir::PatternRewriter::inlineRegionBefore(), mlir::OwningRewritePatternList::insert(), mlir::PatternRewriter::mergeBlocks(), mlir::OpAsmPrinter::printOptionalAttrDict(), mlir::OpAsmPrinter::printRegion(), mlir::PatternRewriter::replaceOp(), mlir::PatternRewriter::splitBlock(), and mlir::success().
print() [2/4]
static void print (OpAsmPrinter & p, ConstShapeOp & op) static
Definition at line 353 of file Shape.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printType().
print() [3/4]
void print (OpAsmPrinter & p, FunctionLibraryOp op)
Definition at line 612 of file Shape.cpp.
References mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), mlir::failure(), mlir::impl::foldCastOp(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::IntegerAttr::get(), mlir::Builder::getContext(), mlir::shape::getExtentTensorType(), mlir::Builder::getIndexAttr(), mlir::Builder::getIndexTensorAttr(), mlir::Builder::getIndexType(), mlir::SymbolTable::getSymbolAttrName(), mlir::Builder::getType(), mlir::Value::getType(), mlir::IntegerAttr::getValue(), mlir::OwningRewritePatternList::insert(), mlir::Type::isa(), mlir::OperationState::location, mlir::OpAsmPrinter::printAttributeWithoutType(), mlir::OpAsmPrinter::printOptionalAttrDictWithKeyword(), mlir::OpAsmPrinter::printRegion(), mlir::OpAsmPrinter::printSymbolName(), mlir::PatternRewriter::replaceOpWithNewOp(), and mlir::success().
Referenced by mlir::Diagnostic::append(), mlir::tblgen::DagLeaf::DagLeaf(), mlir::Identifier::dump(), mlir::Attribute::dump(), mlir::AffineExpr::dump(), mlir::IntegerSet::dump(), mlir::SDBM::dump(), mlir::SDBMExpr::dump(), mlir::AffineMap::dump(), mlir::Type::dump(), mlir::Value::dump(), mlir::Operation::dump(), mlir::Block::dump(), mlir::OperationName::dump(), mlir::Operation::emitError(), mlir::CallGraph::end(), mlir::python::PyOperationBase::getAsm(), mlir::PDLValue::getAsOpaquePointer(), mlir::tblgen::Operator::getDialect(), mlir::Op< DmaStartOp, OpTrait::VariadicOperands, OpTrait::ZeroResult >::getFromOpaquePointer(), mlir::Value::getKind(), mlir::DmaWaitOp::getNumElements(), mlir::DmaStartOp::getOperationName(), mlir::Block::getSublistAccess(), isMemRefDereferencingOp(), mlir::OperationName::OperationName(), mlir::tblgen::DagNode::operator bool(), mlir::AffineExpr::operator!(), mlir::SDBMExpr::operator!(), mlir::AffineMap::operator!=(), operator<<(), mlir::IntegerSet::operator==(), impl::MemRefDataPrinter< T >::print(), mlir::Operation::print(), mlir::Block::print(), printDenseElementsAttrImpl(), printElidedElementsAttr(), impl::MemRefDataPrinter< T >::printFirst(), impl::MemRefDataPrinter< T >::printLast(), printMemRefMetaData(), printTimeEntry(), mlir::raw_indented_ostream::reindent(), and mlir::OpState::verify().
print() [4/4]
static void print (OpAsmPrinter & p, ReduceOp op) static
Definition at line 977 of file Shape.cpp.
References mlir::OpAsmPrinter::printOptionalArrowTypeList(), mlir::OpAsmPrinter::printOptionalAttrDict(), and mlir::OpAsmPrinter::printRegion().
verify() [1/3]
static LogicalResult verify (AssumingAllOp op) static
Definition at line 293 of file Shape.cpp.
References mlir::OpTrait::util::getBroadcastedShape(), mlir::Builder::getIndexTensorAttr(), and mlir::success().
verify() [2/3]
static LogicalResult verify (shape::YieldOp op) static
Definition at line 826 of file Shape.cpp.
References mlir::Block::addArgument(), mlir::OperationState::addOperands(), mlir::OperationState::addRegion(), mlir::OperationState::addTypes(), mlir::Type::dyn_cast(), mlir::failure(), mlir::impl::foldCastOp(), mlir::Region::front(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::RankedTensorType::get(), mlir::DenseIntElementsAttr::get(), mlir::Builder::getContext(), mlir::Builder::getIndexTensorAttr(), mlir::Builder::getIndexType(), mlir::Value::getType(), mlir::ValueRange::getTypes(), mlir::Region::push_back(), and mlir::success().
verify() [3/3]
static LogicalResult verify (ReduceOp op) static
Definition at line 909 of file Shape.cpp.
References mlir::Operation::emitOpError(), mlir::detail::enumerate(), mlir::Block::front(), mlir::Block::getArgument(), mlir::Block::getNumArguments(), mlir::BlockArgument::getType(), mlir::Type::isa(), and mlir::success().
verifyShapeOrExtentTensorOp()
static LogicalResult verifyShapeOrExtentTensorOp (Operation * op) static
Definition at line 51 of file Shape.cpp.
References mlir::Attribute::cast(), mlir::OpBuilder::create(), mlir::DialectInlinerInterface::DialectInlinerInterface(), mlir::DialectAsmParser::emitError(), mlir::Operation::emitOpError(), mlir::detail::StorageUserBase< ConcreteT, BaseT, StorageT, UniquerT, Traits >::get(), mlir::Builder::getContext(), mlir::shape::getExtentTensorType(), mlir::DialectAsmParser::getNameLoc(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), mlir::Type::isa(), isErrorPropagationPossible(), isLegalToInline(), materializeConstant(), mlir::DialectAsmParser::parseKeyword(), mlir::LLVM::detail::parseType(), mlir::LLVM::detail::printType(), and mlir::success().
verifySizeOrIndexOp()
static LogicalResult verifySizeOrIndexOp (Operation * op) static
Definition at line 39 of file Shape.cpp.
References mlir::Operation::emitOpError(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::Operation::getResultTypes(), isErrorPropagationPossible(), and mlir::success().