MLIR: include/mlir-c/StandardDialect.h File Reference
StandardDialect.h File Reference
#include "mlir-c/IR.h"
Functions
MLIR_CAPI_EXPORTED void mlirContextRegisterStandardDialect (MlirContext context)
Registers the Standard dialect with the given context.
MLIR_CAPI_EXPORTED MlirDialect mlirContextLoadStandardDialect (MlirContext context)
Loads the Standard dialect into the given context.
MLIR_CAPI_EXPORTED MlirStringRef mlirStandardDialectGetNamespace ()
Returns the namespace of the Standard dialect, suitable for loading it.
Function Documentation
mlirContextLoadStandardDialect()
MLIR_CAPI_EXPORTED MlirDialect mlirContextLoadStandardDialect (MlirContext context)
Loads the Standard dialect into the given context.
The dialect does not have to be registered in advance.
Definition at line 19 of file StandardDialect.cpp.
References unwrap(), and wrap().
mlirContextRegisterStandardDialect()
MLIR_CAPI_EXPORTED void mlirContextRegisterStandardDialect (MlirContext context)
Registers the Standard dialect with the given context.
This allows the dialect to be loaded dynamically if needed when parsing.
Definition at line 15 of file StandardDialect.cpp.
References unwrap().
mlirStandardDialectGetNamespace()
MLIR_CAPI_EXPORTED MlirStringRef mlirStandardDialectGetNamespace ()
Returns the namespace of the Standard dialect, suitable for loading it.
Definition at line 23 of file StandardDialect.cpp.
References wrap().