MLIR: mlir::LowerToLLVMOptions Struct Reference
mlir::LowerToLLVMOptions Struct Reference
Options to control the Standard dialect to LLVM lowering.
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h"
Static Public Member Functions
static const LowerToLLVMOptions & getDefaultOptions ()
Get a statically allocated copy of the default LowerToLLVMOptions.
Public Attributes
bool useBarePtrCallConv = false
bool emitCWrappers = false
unsigned indexBitwidth = kDeriveIndexBitwidthFromDataLayout
bool useAlignedAlloc = false
Use aligned_alloc for heap allocations.
llvm::DataLayout dataLayout = llvm::DataLayout("")
The data layout of the module to produce.
Detailed Description
Options to control the Standard dialect to LLVM lowering.
The struct is used to share lowering options between passes, patterns, and type converter.
Definition at line 29 of file ConvertStandardToLLVMPass.h.
Member Function Documentation
getDefaultOptions()
static const LowerToLLVMOptions& mlir::LowerToLLVMOptions::getDefaultOptions () inline static
Get a statically allocated copy of the default LowerToLLVMOptions.
Definition at line 42 of file ConvertStandardToLLVMPass.h.
References mlir::createLowerToLLVMPass(), options, mlir::populateStdToLLVMConversionPatterns(), mlir::populateStdToLLVMFuncOpConversionPattern(), mlir::populateStdToLLVMMemoryConversionPatterns(), and mlir::populateStdToLLVMNonMemoryConversionPatterns().
Member Data Documentation
dataLayout
llvm::DataLayout mlir::LowerToLLVMOptions::dataLayout = llvm::DataLayout("")
The data layout of the module to produce.
This must be consistent with the data layout used in the upper levels of the lowering pipeline.
Definition at line 39 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::createLowerToLLVMPass(), mlir::LLVMTypeConverter::getDataLayout(), mlir::LLVMTypeConverter::getPointerBitwidth(), and mlir::LLVMTypeConverter::LLVMTypeConverter().
emitCWrappers
bool mlir::LowerToLLVMOptions::emitCWrappers = false
Definition at line 31 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::createLowerToLLVMPass().
indexBitwidth
unsigned mlir::LowerToLLVMOptions::indexBitwidth = kDeriveIndexBitwidthFromDataLayout
Definition at line 32 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::createLowerToLLVMPass(), mlir::LLVMTypeConverter::getIndexTypeBitwidth(), and mlir::LLVMTypeConverter::LLVMTypeConverter().
useAlignedAlloc
bool mlir::LowerToLLVMOptions::useAlignedAlloc = false
Use aligned_alloc for heap allocations.
Definition at line 34 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::createLowerToLLVMPass(), and mlir::populateStdToLLVMMemoryConversionPatterns().
useBarePtrCallConv
bool mlir::LowerToLLVMOptions::useBarePtrCallConv = false
Definition at line 30 of file ConvertStandardToLLVMPass.h.
Referenced by mlir::LLVMTypeConverter::convertCallingConventionType(), mlir::LLVMTypeConverter::convertFunctionSignature(), mlir::createLowerToLLVMPass(), and mlir::populateStdToLLVMFuncOpConversionPattern().
The documentation for this struct was generated from the following file:
include/mlir/Conversion/StandardToLLVM/ConvertStandardToLLVMPass.h