MLIR: mlir::linalg::CodegenStrategy Struct Reference
mlir::linalg::CodegenStrategy Struct Reference
Codegen strategy controls how a Linalg op is progressively lowered.
#include "mlir/Dialect/Linalg/Transforms/CodegenStrategy.h"
Public Member Functions
template<typename LinalgOpType >
CodegenStrategy & tile (linalg::LinalgTilingOptions options)
Append a pattern to add a level of tiling for LinalgOpType with tiling options.
template<typename LinalgOpType >
CodegenStrategy & tileIf (bool b, linalg::LinalgTilingOptions options)
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
template<typename LinalgOpType >
CodegenStrategy & promote (linalg::LinalgPromotionOptions options)
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
template<typename LinalgOpType >
CodegenStrategy & promoteIf (bool b, linalg::LinalgPromotionOptions options)
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
template<typename LinalgOpType >
CodegenStrategy & vectorize ()
Append a pattern to rewrite LinalgOpType as a vector operation.
template<typename LinalgOpType >
CodegenStrategy & vectorizeIf (bool b)
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
CodegenStrategy & setVectorTransformsOptions (vector::VectorTransformsOptions options)
Configure the post staged-patterns late vector transformations.
CodegenStrategy & setVectorTransferToSCFOptions (VectorTransferToSCFOptions options)
Configure the post staged-patterns late vector.transfer to scf conversion.
void transform (FuncOp func) const
Apply the transformation patterns in sequence with cleanup transformations interleaved.
Detailed Description
Codegen strategy controls how a Linalg op is progressively lowered.
The application uses a 3-level staged patterns strategy which allows ordering transformations by using the Linalg applyStagedPatterns function, where:
The first stage consists of the successive tile, promote and vectorize patterns, applied sequentially.
The second stage consists of common local canonicalization patterns that are applied eagerly after each stage-1 pattern.
the third stage consists of more global transformation, also applied eagerly, after all stage-2 patterns. Such more global transformations
Definition at line 96 of file CodegenStrategy.h.
Member Function Documentation
promote()
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::promote (linalg::LinalgPromotionOptions options) inline
Append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 113 of file CodegenStrategy.h.
promoteIf()
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::promoteIf (bool b, linalg::LinalgPromotionOptions options) inline
Conditionally append a pattern to add a level of promotion for LinalgOpType with promotion options.
Definition at line 120 of file CodegenStrategy.h.
References options.
setVectorTransferToSCFOptions()
CodegenStrategy& mlir::linalg::CodegenStrategy::setVectorTransferToSCFOptions (VectorTransferToSCFOptions options) inline
Configure the post staged-patterns late vector.transfer to scf conversion.
Definition at line 145 of file CodegenStrategy.h.
References options.
setVectorTransformsOptions()
CodegenStrategy& mlir::linalg::CodegenStrategy::setVectorTransformsOptions (vector::VectorTransformsOptions options) inline
Configure the post staged-patterns late vector transformations.
Definition at line 139 of file CodegenStrategy.h.
References options.
tile()
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::tile (linalg::LinalgTilingOptions options) inline
Append a pattern to add a level of tiling for LinalgOpType with tiling options.
Definition at line 100 of file CodegenStrategy.h.
tileIf()
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::tileIf (bool b, linalg::LinalgTilingOptions options) inline
Conditionally append a pattern to add a level of tiling for LinalgOpType with tiling options.
Definition at line 107 of file CodegenStrategy.h.
References options.
transform()
void mlir::linalg::CodegenStrategy::transform (FuncOp func) const
Apply the transformation patterns in sequence with cleanup transformations interleaved.
Definition at line 29 of file CodegenStrategy.cpp.
References mlir::OpPassManager::addPass(), mlir::applyPatternsAndFoldGreedily(), mlir::linalg::applyStagedPatterns(), mlir::createLoopInvariantCodeMotionPass(), mlir::failed(), mlir::Identifier::get(), mlir::linalg::getLinalgTilingCanonicalizationPatterns(), mlir::linalg::hoistRedundantVectorTransfers(), mlir::linalg::hoistViewAllocOps(), mlir::OwningRewritePatternList::insert(), mlir::linalg::LinalgTransforms::kLinalgTransformMarker, mlir::populateVectorToSCFConversionPatterns(), mlir::promoteSingleIterationLoops(), and mlir::success().
vectorize()
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::vectorize () inline
Append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 126 of file CodegenStrategy.h.
vectorizeIf()
template<typename LinalgOpType > CodegenStrategy& mlir::linalg::CodegenStrategy::vectorizeIf (bool b) inline
Conditionally append a pattern to rewrite LinalgOpType as a vector operation.
Definition at line 133 of file CodegenStrategy.h.
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/CodegenStrategy.h
lib/Dialect/Linalg/Transforms/CodegenStrategy.cpp