MLIR: GpuAsyncRegionPass::ThreadTokenCallback Struct Reference
GpuAsyncRegionPass::ThreadTokenCallback Struct Reference
Public Member Functions
ThreadTokenCallback (MLIRContext &context)
WalkResult operator() (Operation *op)
Detailed Description
Definition at line 44 of file AsyncRegionRewriter.cpp.
Constructor & Destructor Documentation
ThreadTokenCallback()
GpuAsyncRegionPass::ThreadTokenCallback::ThreadTokenCallback (MLIRContext & context) inline
Definition at line 45 of file AsyncRegionRewriter.cpp.
Member Function Documentation
operator()()
WalkResult GpuAsyncRegionPass::ThreadTokenCallback::operator() (Operation * op) inline
Definition at line 55 of file AsyncRegionRewriter.cpp.
References copy(), mlir::Operation::create(), mlir::Operation::emitOpError(), mlir::Operation::getLoc(), mlir::Operation::getResults(), mlir::Builder::getType(), hasSideEffects(), isTerminator(), and mlir::success().
The documentation for this struct was generated from the following file:
lib/Dialect/GPU/Transforms/AsyncRegionRewriter.cpp