MLIR: mlir::linalg::LinalgLoweringPattern< OpTy > Struct Template Reference
mlir::linalg::LinalgLoweringPattern< OpTy > Struct Template Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Member Functions
LinalgLoweringPattern (MLIRContext *context, LinalgLoweringType loweringType, LinalgMarker marker=LinalgMarker(), PatternBenefit benefit=1)
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
template<typename OpTy>
struct mlir::linalg::LinalgLoweringPattern< OpTy >
Definition at line 591 of file Transforms.h.
Constructor & Destructor Documentation
LinalgLoweringPattern()
template<typename OpTy > mlir::linalg::LinalgLoweringPattern< OpTy >::LinalgLoweringPattern (MLIRContext * context, LinalgLoweringType loweringType, LinalgMarker marker = LinalgMarker(), PatternBenefit benefit = 1) inline
Definition at line 592 of file Transforms.h.
Member Function Documentation
matchAndRewrite()
template<typename OpTy > LogicalResult mlir::linalg::LinalgLoweringPattern< OpTy >::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const inline override virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented from mlir::RewritePattern.
Definition at line 598 of file Transforms.h.
References mlir::linalg::AffineLoops, mlir::PatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::linalg::LibraryCall, mlir::linalg::linalgOpToAffineLoops(), mlir::linalg::linalgOpToLoops(), mlir::linalg::linalgOpToParallelLoops(), mlir::linalg::Loops, mlir::linalg::TiledLinalgOp::op, mlir::linalg::populateLinalgConvGeneralizationPatterns(), mlir::linalg::populateLinalgNamedOpsGeneralizationPatterns(), and mlir::success().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Linalg/Transforms/Transforms.h