MLIR: mlir::linalg::AffineMinSCFCanonicalizationPattern Struct Reference
mlir::linalg::AffineMinSCFCanonicalizationPattern Struct Reference
Canonicalize AffineMinOp operations in the context of enclosing scf.for and scf.parallel by:
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
Public Member Functions
LogicalResult matchAndRewrite (AffineMinOp minOp, PatternRewriter &rewriter) const override
Public Member Functions inherited from mlir::OpRewritePattern< AffineMinOp >
OpRewritePattern (MLIRContext *context, PatternBenefit benefit=1)
Patterns must specify the root operation name they match against, and can also specify the benefit of the pattern matching.
void rewrite (Operation *op, PatternRewriter &rewriter) const final
Wrappers around the RewritePattern methods that pass the derived op type.
virtual void rewrite (AffineMinOp op, PatternRewriter &rewriter) const
Rewrite and Match methods that operate on the SourceOp type.
LogicalResult match (Operation *op) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
virtual LogicalResult match (AffineMinOp op) const
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const final
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Canonicalize AffineMinOp operations in the context of enclosing scf.for and scf.parallel by:
building an affine map where uses of the induction variable of a loop are replaced by either the min (i.e. lb) of the max (i.e. lb + step * floordiv(ub -1 - lb, step)) expression, depending on whether the induction variable is used with a positive or negative coefficient.
checking whether any of the results of this affine map is known to be greater than all other results.
replacing the AffineMinOp by the result of (2).
Definition at line 717 of file Transforms.h.
Member Function Documentation
matchAndRewrite()
LogicalResult AffineMinSCFCanonicalizationPattern::matchAndRewrite (AffineMinOp minOp, PatternRewriter & rewriter) const override virtual
Reimplemented from mlir::OpRewritePattern< AffineMinOp >.
Definition at line 466 of file Transforms.cpp.
References mlir::canonicalizeMapAndOperands(), DBGS, mlir::failure(), mlir::AffineMap::get(), mlir::AffineMap::getResults(), mlir::PatternRewriter::replaceOpWithNewOp(), mlir::simplifyAffineMap(), substitute(), and mlir::success().
The documentation for this struct was generated from the following files:
include/mlir/Dialect/Linalg/Transforms/Transforms.h
lib/Dialect/Linalg/Transforms/Transforms.cpp