MLIR: mlir::vector::UnrollVectorPattern Struct Reference
mlir::vector::UnrollVectorPattern Struct Reference
Pattern to apply unrollSingleResultVectorOp to a targetShape declaratively.
#include "mlir/Dialect/Vector/VectorTransforms.h"
Public Types
using FilterConstraintType = std::function< LogicalResult(Operation *op)>
Public Member Functions
UnrollVectorPattern (MLIRContext *context, UnrollVectorOptions options)
LogicalResult matchAndRewrite (Operation *op, PatternRewriter &rewriter) const override
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::RewritePattern
virtual ~RewritePattern ()
virtual void rewrite (Operation *op, PatternRewriter &rewriter) const
Rewrite the IR rooted at the specified operation with the result of this pattern, generating any new operations with the specified builder.
virtual LogicalResult match (Operation *op) const
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
Public Member Functions inherited from mlir::Pattern
ArrayRef< OperationName > getGeneratedOps () const
Return a list of operations that may be generated when rewriting an operation instance with this pattern.
Optional< OperationName > getRootKind () const
Return the root node that this pattern matches.
PatternBenefit getBenefit () const
Return the benefit (the inverse of "cost") of matching this pattern.
bool hasBoundedRewriteRecursion () const
Returns true if this pattern is known to result in recursive application, i.e.
Additional Inherited Members
Protected Member Functions inherited from mlir::RewritePattern
virtual void anchor ()
An anchor for the virtual table.
Protected Member Functions inherited from mlir::Pattern
Pattern (StringRef rootName, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (PatternBenefit benefit, MatchAnyOpTypeTag tag)
Construct a pattern with a certain benefit that matches any operation type.
Pattern (StringRef rootName, ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context)
Construct a pattern with a certain benefit that matches the operation with the given root name.
Pattern (ArrayRef< StringRef > generatedNames, PatternBenefit benefit, MLIRContext *context, MatchAnyOpTypeTag tag)
Construct a pattern that may match any operation type.
void setHasBoundedRewriteRecursion (bool hasBoundedRecursionArg=true)
Set the flag detailing if this pattern has bounded rewrite recursion or not.
Detailed Description
Pattern to apply unrollSingleResultVectorOp to a targetShape declaratively.
Definition at line 120 of file VectorTransforms.h.
Member Typedef Documentation
FilterConstraintType
using mlir::vector::UnrollVectorPattern::FilterConstraintType = std::function<LogicalResult(Operation *op)>
Definition at line 121 of file VectorTransforms.h.
Constructor & Destructor Documentation
UnrollVectorPattern()
mlir::vector::UnrollVectorPattern::UnrollVectorPattern (MLIRContext * context, UnrollVectorOptions options) inline
Definition at line 122 of file VectorTransforms.h.
Member Function Documentation
matchAndRewrite()
LogicalResult mlir::vector::UnrollVectorPattern::matchAndRewrite (Operation * op, PatternRewriter & rewriter) const inline override virtual
Attempt to match against code rooted at the specified operation, which is the same operation code as getRootKind().
If successful, this function will automatically perform the rewrite.
Reimplemented from mlir::RewritePattern.
Definition at line 124 of file VectorTransforms.h.
References mlir::Operation::emitError(), mlir::PatternRewriter::eraseOp(), mlir::failed(), mlir::failure(), mlir::Operation::getNumResults(), options, mlir::PatternRewriter::replaceOp(), mlir::shapeRatio(), mlir::vector::splitFullAndPartialTransfer(), mlir::vector::splitFullAndPartialTransferPrecondition(), mlir::success(), mlir::vector::unrollSingleResultVectorOp(), and mlir::vector::unrollTransferWriteOp().
The documentation for this struct was generated from the following file:
include/mlir/Dialect/Vector/VectorTransforms.h