MLIR: lib/Dialect/Tensor/IR/TensorOps.cpp File Reference
TensorOps.cpp File Reference
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/TypeUtilities.h"
#include "llvm/ADT/STLExtras.h"
#include "mlir/Dialect/Tensor/IR/TensorOps.cpp.inc"
Macros
#define GET_OP_CLASSES
Functions
static LogicalResult verify (ExtractOp op)
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 59 of file TensorOps.cpp.
Function Documentation
verify()
static LogicalResult verify (ExtractOp op) static
Definition at line 21 of file TensorOps.cpp.
References mlir::Attribute::dyn_cast(), mlir::IntegerAttr::getInt(), mlir::ElementsAttr::getValue(), and mlir::success().