MLIR: lib/Dialect/Linalg/Transforms/Vectorization.cpp File Reference
Vectorization.cpp File Reference
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <type_traits>
Macros
#define DEBUG_TYPE "linalg-vectorization"
Typedefs
using ConvOpConst = ConvOpVectorization< ConvWOp, 1 >
Functions
static bool hasMultiplyAddBody (Region &r)
static LogicalResult isContraction (Operation *op)
static bool hasOnlyScalarElementwiseOp (Region &r)
static bool isElementwise (Operation *op)
static VectorType extractVectorTypeFromScalarView (Value v)
static Value transferReadVector (OpBuilder &builder, Value memref)
static void transferWriteVector (OpBuilder &builder, Value value, Value memref)
static void vectorizeElementwise (linalg::GenericOp op, OpBuilder &builder)
static bool mayExistInterleavedUses (Operation *firstOp, Operation *secondOp, ValueRange values)
Check whether there is any interleaved use of any values between firstOp and secondOp.
static SubViewOp getSubViewUseIfUnique (Value v)
Return the unique subview use of v if it is indeed unique, null otherwise.
template<typename ConvOp , unsigned N>
static void populateVectorizationPatterns (OwningRewritePatternList &tilingPatterns, OwningRewritePatternList &promotionPatterns, OwningRewritePatternList &vectorizationPatterns, ArrayRef< int64_t > tileSizes, MLIRContext *context)
Inserts tiling, promotion and vectorization pattern for ConvOp conversion into corresponding pattern lists.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "linalg-vectorization"
Definition at line 37 of file Vectorization.cpp.
Referenced by mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), mayExistInterleavedUses(), and mlir::linalg::vectorizeLinalgOp().
Typedef Documentation
ConvOpConst
using ConvOpConst = ConvOpVectorization<ConvWOp, 1>
Definition at line 600 of file Vectorization.cpp.
Function Documentation
extractVectorTypeFromScalarView()
static VectorType extractVectorTypeFromScalarView (Value v) static
Definition at line 122 of file Vectorization.cpp.
References mlir::Type::cast(), mlir::VectorType::get(), mlir::MemRefType::getShape(), and mlir::Value::getType().
Referenced by transferReadVector(), transferWriteVector(), and mlir::linalg::vectorizeLinalgOp().
getSubViewUseIfUnique()
static SubViewOp getSubViewUseIfUnique (Value v) static
Return the unique subview use of v if it is indeed unique, null otherwise.
Definition at line 396 of file Vectorization.cpp.
References mlir::Value::getUses().
Referenced by mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), and mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite().
hasMultiplyAddBody()
static bool hasMultiplyAddBody (Region & r) static
Definition at line 39 of file Vectorization.cpp.
References mlir::Block::back(), mlir::Block::begin(), mlir::Block::end(), mlir::Region::front(), mlir::Region::getArgument(), and mlir::matchers::m_Val().
Referenced by isContraction().
hasOnlyScalarElementwiseOp()
static bool hasOnlyScalarElementwiseOp (Region & r) static
Definition at line 87 of file Vectorization.cpp.
References mlir::Region::front().
Referenced by isElementwise().
isContraction()
static LogicalResult isContraction (Operation * op) static
Definition at line 69 of file Vectorization.cpp.
References mlir::failure(), hasMultiplyAddBody(), mlir::AffineMap::isProjectedPermutation(), and mlir::success().
Referenced by mlir::linalg::vectorizeLinalgOp(), and mlir::linalg::vectorizeLinalgOpPrecondition().
isElementwise()
static bool isElementwise (Operation * op) static
Definition at line 101 of file Vectorization.cpp.
References hasOnlyScalarElementwiseOp().
Referenced by mlir::linalg::vectorizeLinalgOp(), and mlir::linalg::vectorizeLinalgOpPrecondition().
mayExistInterleavedUses()
static bool mayExistInterleavedUses (Operation * firstOp, Operation * secondOp, ValueRange values) static
Check whether there is any interleaved use of any values between firstOp and secondOp.
Conservatively return true if any op or value is in a different block.
Definition at line 366 of file Vectorization.cpp.
References DEBUG_TYPE, mlir::Operation::getBlock(), and mlir::Operation::isBeforeInBlock().
Referenced by mlir::linalg::LinalgCopyVTRForwardingPattern::matchAndRewrite(), and mlir::linalg::LinalgCopyVTWForwardingPattern::matchAndRewrite().
populateVectorizationPatterns()
template<typename ConvOp , unsigned N> static void populateVectorizationPatterns (OwningRewritePatternList & tilingPatterns, OwningRewritePatternList & promotionPatterns, OwningRewritePatternList & vectorizationPatterns, ArrayRef< int64_t > tileSizes, MLIRContext * context) static
Inserts tiling, promotion and vectorization pattern for ConvOp conversion into corresponding pattern lists.
Definition at line 606 of file Vectorization.cpp.
References mlir::Identifier::get(), mlir::OwningRewritePatternList::insert(), mlir::linalg::LinalgTilingOptions::setTileSizes(), and mlir::linalg::LinalgPromotionOptions::setUseFullTileBuffersByDefault().
transferReadVector()
static Value transferReadVector (OpBuilder & builder, Value memref) static
Definition at line 129 of file Vectorization.cpp.
References mlir::Type::cast(), extractVectorTypeFromScalarView(), and mlir::Value::getType().
Referenced by transferWriteVector(), and mlir::linalg::vectorizeLinalgOp().
transferWriteVector()
static void transferWriteVector (OpBuilder & builder, Value value, Value memref) static
Definition at line 139 of file Vectorization.cpp.
References mlir::OperationState::addAttributes(), mlir::Value::cast(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::OpBuilder::createOperation(), mlir::Type::dyn_cast(), extractVectorTypeFromScalarView(), mlir::VectorType::get(), mlir::Operation::getAttrs(), mlir::OpBuilder::getInsertionPoint(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumResults(), mlir::Operation::getOperands(), mlir::Value::getParentRegion(), mlir::Operation::getResults(), mlir::Operation::getResultTypes(), mlir::Value::getType(), and transferReadVector().
Referenced by mlir::linalg::vectorizeLinalgOp().
vectorizeElementwise()
static void vectorizeElementwise (linalg::GenericOp op, OpBuilder & builder) static
Definition at line 270 of file Vectorization.cpp.
Referenced by mlir::linalg::vectorizeLinalgOp().