MLIR: lib/Conversion/VectorToSCF/VectorToSCF.cpp File Reference
VectorToSCF.cpp File Reference
#include <type_traits>
#include "mlir/Conversion/VectorToSCF/VectorToSCF.h"
#include "../PassDetail.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/SCF/EDSC/Builders.h"
#include "mlir/Dialect/SCF/EDSC/Intrinsics.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "mlir/Transforms/Passes.h"
Namespaces
mlir
Include the generated interface declarations.
Functions
static SmallVector< Value, 4 > applyMapToValues (OpBuilder &b, Location loc, AffineMap map, ValueRange values)
template<typename TransferOpTy >
static int computeCoalescedIndex (TransferOpTy transfer)
Analyzes the transfer to find an access dimension along the fastest remote MemRef dimension.
static void emitWithBoundsChecks (PatternRewriter &rewriter, VectorTransferOpInterface transfer, ValueRange ivs, const MemRefBoundsCapture &memRefBoundsCapture, function_ref< void(ArrayRef< Value >)> inBoundsFun, function_ref< void(ArrayRef< Value >)> outOfBoundsFun=nullptr)
void mlir::populateVectorToSCFConversionPatterns (OwningRewritePatternList &patterns, MLIRContext *context, const VectorTransferToSCFOptions &options=VectorTransferToSCFOptions())
Collect a set of patterns to convert from the Vector dialect to SCF + std.
Function Documentation
applyMapToValues()
static SmallVector<Value, 4> applyMapToValues (OpBuilder & b, Location loc, AffineMap map, ValueRange values) static
Definition at line 44 of file VectorToSCF.cpp.
References mlir::edsc::affineLoopNestBuilder(), mlir::canonicalizeMapAndOperands(), mlir::computeMaxLinearIndex(), mlir::computeStrides(), mlir::edsc::conditionBuilder(), mlir::OpBuilder::createOrFold(), mlir::delinearize(), mlir::PatternRewriter::eraseOp(), extractConstantIndex(), mlir::Region::front(), mlir::fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::AffineMapAttr::get(), mlir::VectorType::get(), mlir::MemRefType::get(), mlir::Builder::getBoolArrayAttr(), mlir::edsc::ScopedContext::getBuilderRef(), mlir::Value::getDefiningOp(), mlir::edsc::BoundsCapture::getLbs(), mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::Operation::getParentWithTrait(), mlir::Operation::getRegion(), mlir::AffineMap::getResults(), mlir::edsc::BoundsCapture::getSteps(), mlir::vector::impl::getTransferMinorIdentityMap(), mlir::edsc::BoundsCapture::getUbs(), options, mlir::PatternRewriter::replaceOp(), mlir::edsc::op::slt(), and mlir::success().
Referenced by emitWithBoundsChecks(), makeTiledLoopRanges(), makeTiledShapes(), permuteIvs(), and tileLinalgOpImpl().
computeCoalescedIndex()
template<typename TransferOpTy > static int computeCoalescedIndex (TransferOpTy transfer) static
Analyzes the transfer to find an access dimension along the fastest remote MemRef dimension.
If such a dimension with coalescing properties is found, pivs and vectorBoundsCapture are swapped so that the invocation of LoopNestBuilder captures it in the innermost loop.
Definition at line 422 of file VectorToSCF.cpp.
References mlir::detail::enumerate(), and mlir::AffineDimExpr::getPosition().
Referenced by mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().
emitWithBoundsChecks()
static void emitWithBoundsChecks (PatternRewriter & rewriter, VectorTransferOpInterface transfer, ValueRange ivs, const MemRefBoundsCapture & memRefBoundsCapture, function_ref< void(ArrayRef< Value >)> inBoundsFun, function_ref< void(ArrayRef< Value >)> outOfBoundsFun = nullptr) static
Definition at line 464 of file VectorToSCF.cpp.
References applyMapToValues(), mlir::edsc::conditionBuilder(), mlir::detail::enumerate(), and mlir::AffineConstantExpr::getValue().
Referenced by mlir::VectorTransferRewriter< TransferOpTy >::matchAndRewrite().