MLIR: lib/Dialect/Vector/VectorTransforms.cpp File Reference
VectorTransforms.cpp File Reference
#include <type_traits>
#include "mlir/Dialect/Affine/EDSC/Builders.h"
#include "mlir/Dialect/Affine/EDSC/Intrinsics.h"
#include "mlir/Dialect/Affine/IR/AffineOps.h"
#include "mlir/Dialect/Linalg/EDSC/Intrinsics.h"
#include "mlir/Dialect/SCF/EDSC/Intrinsics.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/Vector/VectorTransforms.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/Location.h"
#include "mlir/IR/Matchers.h"
#include "mlir/IR/OperationSupport.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/IR/Types.h"
#include "mlir/Interfaces/VectorInterfaces.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct UnrolledVectorState
struct VectorState
struct TransferReadExtractPattern
struct TransferWriteInsertPattern
Namespaces
mlir
Include the generated interface declarations.
Macros
#define DEBUG_TYPE "vector-to-vector"
Functions
static Optional< int64_t > getResultIndex (AffineMap map, int64_t index)
static SmallVector< Attribute, 4 > adjustIter (ArrayAttr iteratorTypes, int64_t index)
static AffineMap adjustMap (AffineMap map, int64_t index, PatternRewriter &rewriter)
static Type adjustType (VectorType tp, int64_t index)
static Value reshapeLoad (Location loc, Value val, VectorType type, int64_t index, int64_t pos, PatternRewriter &rewriter)
static Value reshapeStore (Location loc, Value val, Value result, VectorType type, int64_t index, int64_t pos, PatternRewriter &rewriter)
static Operation * cloneOpWithOperandsAndTypes (OpBuilder &builder, Location loc, Operation *op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes)
static void getMappedElements (const DenseMap< int64_t, int64_t > &indexMap, ArrayRef< int64_t > inputElements, SmallVectorImpl< int64_t > &resultElements)
static TupleType generateExtractSlicesOpResultType (VectorType vectorType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, OpBuilder &builder)
static void initUnrolledVectorState (VectorType vectorType, Value initValue, const DenseMap< int64_t, int64_t > &indexMap, ArrayRef< int64_t > targetShape, UnrolledVectorState &state, OpBuilder &builder)
static int64_t getUnrolledVectorLinearIndex (UnrolledVectorState &state, ArrayRef< int64_t > vectorOffsets, DenseMap< int64_t, int64_t > &indexMap)
static Value getOrCreateUnrolledVectorSlice (Location loc, UnrolledVectorState &state, ArrayRef< int64_t > vectorOffsets, ArrayRef< int64_t > offsets, DenseMap< int64_t, int64_t > &indexMap, Value initValue, SmallVectorImpl< Value > &cache, OpBuilder &builder)
static Value unrollSingleResultStructuredOp (Operation *op, ArrayRef< int64_t > iterationBounds, std::vector< VectorState > &vectors, unsigned resultIndex, ArrayRef< int64_t > targetShape, OpBuilder &builder)
static void getVectorContractionOpUnrollState (vector::ContractionOp contractionOp, ArrayRef< int64_t > targetShape, std::vector< VectorState > &vectors, unsigned &resultIndex)
static void getVectorElementwiseOpUnrollState (Operation *op, ArrayRef< int64_t > targetShape, std::vector< VectorState > &vectors, unsigned &resultIndex)
static void generateTransferOpSlices (Type memrefElementType, VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, ArrayRef< Value > indices, OpBuilder &builder, function_ref< void(unsigned, ArrayRef< Value >)> fn)
Generates slices of 'vectorType' according to 'sizes' and 'strides, and calls 'fn' with linear index and indices for each slice.
static bool isIdentitySuffix (AffineMap map)
Returns true if 'map' is a suffix of an identity affine map, false otherwise.
static Value unrollTransferReadOp (vector::TransferReadOp readOp, ArrayRef< int64_t > targetShape, OpBuilder &builder)
Unroll transfer_read ops to the given shape and create an aggregate with all the chunks.
static Optional< int64_t > extractConstantIndex (Value v)
static Value createScopedFoldedSLE (Value v, Value ub)
static Value createScopedInBoundsCond (VectorTransferOpInterface xferOp)
static MemRefType getCastCompatibleMemRefType (MemRefType aT, MemRefType bT)
Given two MemRefTypes aT and bT, return a MemRefType to which both can be cast.
static Value createScopedSubViewIntersection (VectorTransferOpInterface xferOp, Value alloc)
Operates under a scoped context to build the intersection between the view xferOp.memref() @ xferOp.indices() and the view alloc.
static scf::IfOp createScopedFullPartialLinalgCopy (vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc)
Given an xferOp for which:
static scf::IfOp createScopedFullPartialVectorTransferRead (vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc)
Given an xferOp for which:
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "vector-to-vector"
Definition at line 44 of file VectorTransforms.cpp.
Function Documentation
adjustIter()
static SmallVector<Attribute, 4> adjustIter (ArrayAttr iteratorTypes, int64_t index) static
Definition at line 60 of file VectorTransforms.cpp.
References mlir::detail::enumerate().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
adjustMap()
static AffineMap adjustMap (AffineMap map, int64_t index, PatternRewriter & rewriter) static
Definition at line 73 of file VectorTransforms.cpp.
References mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::AffineMap::getDimPosition(), mlir::AffineMap::getNumDims(), and mlir::AffineMap::getNumResults().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
adjustType()
static Type adjustType (VectorType tp, int64_t index) static
Definition at line 90 of file VectorTransforms.cpp.
References mlir::VectorType::get().
Referenced by reshapeLoad(), and reshapeStore().
cloneOpWithOperandsAndTypes()
static Operation* cloneOpWithOperandsAndTypes (OpBuilder & builder, Location loc, Operation * op, ArrayRef< Value > operands, ArrayRef< Type > resultTypes) static
Definition at line 165 of file VectorTransforms.cpp.
References mlir::OpBuilder::createOperation(), mlir::Operation::getAttrs(), mlir::Operation::getName(), and mlir::OperationName::getStringRef().
Referenced by mlir::vector::PointwiseExtractPattern::matchAndRewrite(), and unrollSingleResultStructuredOp().
createScopedFoldedSLE()
static Value createScopedFoldedSLE (Value v, Value ub) static
Definition at line 2118 of file VectorTransforms.cpp.
References extractConstantIndex(), and mlir::edsc::op::sle().
Referenced by createScopedInBoundsCond().
createScopedFullPartialLinalgCopy()
static scf::IfOp createScopedFullPartialLinalgCopy (vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc) static
Given an xferOp for which:
inBoundsCond and a compatibleMemRefType have been computed.
a memref of single vector alloc has been allocated. Produce IR resembling:
 %1:3 = scf.if (%inBounds) {
   memref_cast %A: memref<A...> to compatibleMemRefType
   scf.yield %view, ... : compatibleMemRefType, index, index
 } else {
   %2 = linalg.fill(%alloc, %pad)
   %3 = subview %view [...][...][...]
   linalg.copy(%3, %alloc)
   memref_cast %alloc: memref<B...> to compatibleMemRefType
   scf.yield %4, ... : compatibleMemRefType, index, index
}
Return the produced scf::IfOp.
Definition at line 2259 of file VectorTransforms.cpp.
References mlir::edsc::conditionBuilder(), and createScopedSubViewIntersection().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createScopedFullPartialVectorTransferRead()
static scf::IfOp createScopedFullPartialVectorTransferRead (vector::TransferReadOp xferOp, TypeRange returnTypes, Value inBoundsCond, MemRefType compatibleMemRefType, Value alloc) static
Given an xferOp for which:
inBoundsCond and a compatibleMemRefType have been computed.
a memref of single vector alloc has been allocated. Produce IR resembling:
 %1:3 = scf.if (%inBounds) {
   memref_cast %A: memref<A...> to compatibleMemRefType
   scf.yield %view, ... : compatibleMemRefType, index, index
 } else {
   %2 = vector.transfer_read %view[...], %pad : memref<A...>, vector<...>
   %3 = vector.type_cast %extra_alloc :
     memref<...> to memref<vector<...>>
   store %2, %3[] : memref<vector<...>>
   %4 = memref_cast %alloc: memref<B...> to compatibleMemRefType
   scf.yield %4, ... : compatibleMemRefType, index, index
}
Return the produced scf::IfOp.
Definition at line 2313 of file VectorTransforms.cpp.
References mlir::Operation::clone(), mlir::edsc::conditionBuilder(), mlir::MemRefType::get(), and mlir::Value::getType().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createScopedInBoundsCond()
static Value createScopedInBoundsCond (VectorTransferOpInterface xferOp) static
Definition at line 2129 of file VectorTransforms.cpp.
References createScopedFoldedSLE().
Referenced by mlir::vector::splitFullAndPartialTransfer().
createScopedSubViewIntersection()
static Value createScopedSubViewIntersection (VectorTransferOpInterface xferOp, Value alloc) static
Operates under a scoped context to build the intersection between the view xferOp.memref() @ xferOp.indices() and the view alloc.
Definition at line 2212 of file VectorTransforms.cpp.
References mlir::bindDims(), mlir::Type::cast(), mlir::Value::getType(), and mlir::AffineMap::inferFromExprList().
Referenced by createScopedFullPartialLinalgCopy().
extractConstantIndex()
static Optional<int64_t> extractConstantIndex (Value v) static
Definition at line 2106 of file VectorTransforms.cpp.
References mlir::Value::getDefiningOp().
Referenced by applyMapToValues(), and createScopedFoldedSLE().
generateExtractSlicesOpResultType()
static TupleType generateExtractSlicesOpResultType (VectorType vectorType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, OpBuilder & builder) static
Definition at line 192 of file VectorTransforms.cpp.
References mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeMaxLinearIndex(), mlir::computeSliceSizes(), mlir::computeStrides(), mlir::delinearize(), mlir::VectorType::get(), mlir::TupleType::get(), mlir::Builder::getContext(), mlir::VectorType::getShape(), and mlir::shapeRatio().
Referenced by initUnrolledVectorState(), unrollTransferReadOp(), and mlir::vector::unrollTransferWriteOp().
generateTransferOpSlices()
static void generateTransferOpSlices (Type memrefElementType, VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides, ArrayRef< Value > indices, OpBuilder & builder, function_ref< void(unsigned, ArrayRef< Value >)> fn) static
Generates slices of 'vectorType' according to 'sizes' and 'strides, and calls 'fn' with linear index and indices for each slice.
Definition at line 515 of file VectorTransforms.cpp.
References mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeStrides(), mlir::OpBuilder::create(), mlir::delinearize(), mlir::Type::dyn_cast(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::getAffineDimExpr(), mlir::Builder::getContext(), mlir::VectorType::getShape(), mlir::shapeRatio(), and mlir::TupleType::size().
Referenced by mlir::vector::unrollSingleResultVectorOp(), unrollTransferReadOp(), and mlir::vector::unrollTransferWriteOp().
getCastCompatibleMemRefType()
static MemRefType getCastCompatibleMemRefType (MemRefType aT, MemRefType bT) static
Given two MemRefTypes aT and bT, return a MemRefType to which both can be cast.
If the MemRefTypes don't have the same rank or are not strided, return null; otherwise:
if aT and bT are cast-compatible, return aT.
else return a new MemRefType obtained by iterating over the shape and strides and: a. keeping the ones that are static and equal across aT and bT. b. using a dynamic shape and/or stride for the dimensions that don't agree.
Definition at line 2179 of file VectorTransforms.cpp.
References mlir::failed(), mlir::MemRefType::get(), mlir::MemRefType::getShape(), mlir::getStridesAndOffset(), and mlir::makeStridedLinearLayoutMap().
Referenced by mlir::vector::splitFullAndPartialTransfer().
getMappedElements()
static void getMappedElements (const DenseMap< int64_t, int64_t > & indexMap, ArrayRef< int64_t > inputElements, SmallVectorImpl< int64_t > & resultElements) static
Definition at line 176 of file VectorTransforms.cpp.
Referenced by getOrCreateUnrolledVectorSlice(), getUnrolledVectorLinearIndex(), and initUnrolledVectorState().
getOrCreateUnrolledVectorSlice()
static Value getOrCreateUnrolledVectorSlice (Location loc, UnrolledVectorState & state, ArrayRef< int64_t > vectorOffsets, ArrayRef< int64_t > offsets, DenseMap< int64_t, int64_t > & indexMap, Value initValue, SmallVectorImpl< Value > & cache, OpBuilder & builder) static
Definition at line 277 of file VectorTransforms.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), mlir::VectorType::get(), mlir::Builder::getI64IntegerAttr(), getMappedElements(), mlir::Value::getType(), getUnrolledVectorLinearIndex(), UnrolledVectorState::slicesTuple, and UnrolledVectorState::unrolledShape.
Referenced by unrollSingleResultStructuredOp().
getResultIndex()
static Optional<int64_t> getResultIndex (AffineMap map, int64_t index) static
Definition at line 50 of file VectorTransforms.cpp.
References mlir::AffineMap::getDimPosition(), and mlir::AffineMap::getNumResults().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
getUnrolledVectorLinearIndex()
static int64_t getUnrolledVectorLinearIndex (UnrolledVectorState & state, ArrayRef< int64_t > vectorOffsets, DenseMap< int64_t, int64_t > & indexMap) static
Definition at line 264 of file VectorTransforms.cpp.
References UnrolledVectorState::basis, getMappedElements(), mlir::linearize(), and UnrolledVectorState::unrolledShape.
Referenced by getOrCreateUnrolledVectorSlice(), and unrollSingleResultStructuredOp().
getVectorContractionOpUnrollState()
static void getVectorContractionOpUnrollState (vector::ContractionOp contractionOp, ArrayRef< int64_t > targetShape, std::vector< VectorState > & vectors, unsigned & resultIndex) static
Definition at line 457 of file VectorTransforms.cpp.
Referenced by mlir::vector::unrollSingleResultVectorOp().
getVectorElementwiseOpUnrollState()
static void getVectorElementwiseOpUnrollState (Operation * op, ArrayRef< int64_t > targetShape, std::vector< VectorState > & vectors, unsigned & resultIndex) static
Definition at line 486 of file VectorTransforms.cpp.
References mlir::Type::dyn_cast_or_null(), mlir::Operation::getNumOperands(), mlir::Operation::getNumResults(), mlir::Operation::getOperandTypes(), mlir::Operation::getResult(), and mlir::Value::getType().
Referenced by mlir::vector::unrollSingleResultVectorOp().
initUnrolledVectorState()
static void initUnrolledVectorState (VectorType vectorType, Value initValue, const DenseMap< int64_t, int64_t > & indexMap, ArrayRef< int64_t > targetShape, UnrolledVectorState & state, OpBuilder & builder) static
Definition at line 233 of file VectorTransforms.cpp.
References UnrolledVectorState::basis, mlir::computeMaxLinearIndex(), mlir::computeStrides(), mlir::OpBuilder::create(), generateExtractSlicesOpResultType(), mlir::Value::getLoc(), getMappedElements(), mlir::VectorType::getShape(), UnrolledVectorState::numInstances, mlir::shapeRatio(), UnrolledVectorState::slicesTuple, UnrolledVectorState::unrolledShape, and UnrolledVectorState::unrollFactors.
Referenced by unrollSingleResultStructuredOp().
isIdentitySuffix()
static bool isIdentitySuffix (AffineMap map) static
Returns true if 'map' is a suffix of an identity affine map, false otherwise.
Example: affine_map<(d0, d1, d2, d3) -> (d2, d3)>
Definition at line 571 of file VectorTransforms.cpp.
References mlir::AffineMap::getNumDims(), mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResults().
Referenced by mlir::vector::unrollSingleResultVectorOp(), unrollTransferReadOp(), and mlir::vector::unrollTransferWriteOp().
reshapeLoad()
static Value reshapeLoad (Location loc, Value val, VectorType type, int64_t index, int64_t pos, PatternRewriter & rewriter) static
Definition at line 110 of file VectorTransforms.cpp.
References adjustType(), mlir::Type::cast(), mlir::OpBuilder::create(), mlir::Builder::getI64ArrayAttr(), and mlir::Builder::getZeroAttr().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
reshapeStore()
static Value reshapeStore (Location loc, Value val, Value result, VectorType type, int64_t index, int64_t pos, PatternRewriter & rewriter) static
Definition at line 138 of file VectorTransforms.cpp.
References adjustType(), mlir::OpBuilder::create(), and mlir::Builder::getI64ArrayAttr().
Referenced by mlir::ContractionOpLowering::matchAndRewrite().
unrollSingleResultStructuredOp()
static Value unrollSingleResultStructuredOp (Operation * op, ArrayRef< int64_t > iterationBounds, std::vector< VectorState > & vectors, unsigned resultIndex, ArrayRef< int64_t > targetShape, OpBuilder & builder) static
Definition at line 367 of file VectorTransforms.cpp.
References mlir::Type::cast(), cloneOpWithOperandsAndTypes(), mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeMaxLinearIndex(), mlir::computeStrides(), mlir::OpBuilder::create(), mlir::delinearize(), mlir::Type::dyn_cast_or_null(), mlir::VectorType::get(), mlir::Builder::getI64ArrayAttr(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), getOrCreateUnrolledVectorSlice(), mlir::Operation::getResult(), mlir::Builder::getTupleType(), mlir::Value::getType(), getUnrolledVectorLinearIndex(), initUnrolledVectorState(), resultIndex(), and mlir::shapeRatio().
Referenced by mlir::vector::unrollSingleResultVectorOp().
unrollTransferReadOp()
static Value unrollTransferReadOp (vector::TransferReadOp readOp, ArrayRef< int64_t > targetShape, OpBuilder & builder) static
Unroll transfer_read ops to the given shape and create an aggregate with all the chunks.
Definition at line 590 of file VectorTransforms.cpp.
References mlir::Type::cast(), mlir::OpBuilder::create(), generateExtractSlicesOpResultType(), generateTransferOpSlices(), getElementType(), mlir::Builder::getI64ArrayAttr(), mlir::TupleType::getType(), isIdentitySuffix(), and mlir::TupleType::size().
Referenced by mlir::vector::unrollSingleResultVectorOp().