MLIR: lib/Interfaces/ViewLikeInterface.cpp File Reference
ViewLikeInterface.cpp File Reference
#include "mlir/Interfaces/ViewLikeInterface.h"
#include "mlir/Interfaces/ViewLikeInterface.cpp.inc"
Functions
static LogicalResult verifyOpWithOffsetSizesAndStridesPart (OffsetSizeAndStrideOpInterface op, StringRef name, unsigned expectedNumElements, StringRef attrName, ArrayAttr attr, llvm::function_ref< bool(int64_t)> isDynamic, ValueRange values)
Include the definitions of the loop-like interfaces.
static void printListOfOperandsOrIntegers (OpAsmPrinter &p, ValueRange values, ArrayAttr arrayAttr, llvm::function_ref< bool(int64_t)> isDynamic)
Print a list with either (1) the static integer value in arrayAttr if isDynamic evaluates to false or (2) the next value otherwise.
static ParseResult parseListOfOperandsOrIntegers (OpAsmParser &parser, OperationState &result, StringRef attrName, int64_t dynVal, SmallVectorImpl< OpAsmParser::OperandType > &ssa)
Parse a mixed list with either (1) static integer values or (2) SSA values.
Function Documentation
parseListOfOperandsOrIntegers()
static ParseResult parseListOfOperandsOrIntegers (OpAsmParser & parser, OperationState & result, StringRef attrName, int64_t dynVal, SmallVectorImpl< OpAsmParser::OperandType > & ssa) static
Parse a mixed list with either (1) static integer values or (2) SSA values.
Fill result with the integer ArrayAttr named attrName where dynVal encode the position of SSA values. Add the parsed SSA values to ssa in-order. E.g. after parsing "[%arg0, 7, 42, %arg42]":
result is filled with the i64 ArrayAttr "[`dynVal`, 7, 42, `dynVal`]"
ssa is filled with "[%arg0, %arg1]".
Definition at line 107 of file ViewLikeInterface.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::emitError(), mlir::failed(), mlir::failure(), mlir::Builder::getArrayAttr(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getI64ArrayAttr(), mlir::IntegerAttr::getInt(), mlir::OpAsmParser::getNameLoc(), mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseLSquare(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::parseOptionalOperand(), mlir::OpAsmParser::parseOptionalRSquare(), mlir::OpAsmParser::parseRSquare(), mlir::succeeded(), and mlir::success().
Referenced by mlir::parseOffsetsSizesAndStrides().
printListOfOperandsOrIntegers()
static void printListOfOperandsOrIntegers (OpAsmPrinter & p, ValueRange values, ArrayAttr arrayAttr, llvm::function_ref< bool(int64_t)> isDynamic) static
Print a list with either (1) the static integer value in arrayAttr if isDynamic evaluates to false or (2) the next value otherwise.
This allows idiomatic printing of mixed value and integer attributes in a list. E.g. [arg0, 7, 42, arg42].
Definition at line 65 of file ViewLikeInterface.cpp.
References mlir::Attribute::cast().
Referenced by mlir::printOffsetsSizesAndStrides().
verifyOpWithOffsetSizesAndStridesPart()
static LogicalResult verifyOpWithOffsetSizesAndStridesPart (OffsetSizeAndStrideOpInterface op, StringRef name, unsigned expectedNumElements, StringRef attrName, ArrayAttr attr, llvm::function_ref< bool(int64_t)> isDynamic, ValueRange values) static
Include the definitions of the loop-like interfaces.
Check static and dynamic offsets/sizes/strides breakdown.
Definition at line 20 of file ViewLikeInterface.cpp.
References mlir::IntegerAttr::getInt(), mlir::ArrayAttr::getValue(), mlir::ArrayAttr::size(), and mlir::success().
Referenced by mlir::verify().